### ISSUE TITLE
In lessons page, the display of the dropdown list should be change

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/qax-portal-2#100]
Steps to reproduce:
1. Open design in figma https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A1035
2. Pay attention of the display of the **dropdown list** for **desktop**, **tablet** and **mobile**

Description: For desktop, the inscription should be change for some expressive arrow, and add this arrow for tablet and mobile. 

Actual result:
![NVIDIA_Share_ru0c3Z](https://user-images.githubusercontent.com/57997443/190343250-baeda56e-0e30-47ad-a0fd-ce32324cb1b9.jpg)

Expected result (example, suggest your own):
![NVIDIA_Share_ru0c3ZWqc](https://user-images.githubusercontent.com/57997443/190343333-c49ad303-565d-463e-b3de-c7e04fcc1d98.jpg)

![NVIDIA_Share_rIySIBxgAE](https://user-images.githubusercontent.com/57997443/190344255-62302a1e-50c0-464b-842d-013a02b6a5c4.png)

**Comment by scholokov** [comment]
- прибрати слово Expand / Collapse
- може колір стрілочки зробити "помаранчовим"?

**Comment by scholokov** [comment]
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A1035&t=zxWBau6Mp0OgR8Ay-0

**Comment by dmitryylev** [comment]
verified
