### ISSUE TITLE
Cources - qa-courses / Font weight of the section "Наші поточні навчальні проекти" and other sections is different in the text of the accordion "Крок 2. Практика" 

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1002]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/qa-courses/
2. Scroll down to the accordion "Крок 2. Практика" - open it.
3. Pay attention to the font weight of the last section "Наші поточні навчальні проекти".

**Actual result:**
Font weight of the section "Наші поточні навчальні проекти" (font weight  - 700) and other sections (font weight  - 900) is different.

**Expected result:**
Font weight of the section "**Наші поточні навчальні проекти**" and other sections is the same - **font weight  - 900.**

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/54e66c50-e705-4a53-afc8-eea9f2ee2675)

**Comment by GNatala** [comment]
#998

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
