### ISSUE TITLE
Practice / Missed phrase "* Вартість навчання на проєкті вказана за тарифом “Мінімальний”"after the cards of current projects

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1003]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/practice/
2. Scroll down to the accordion "Діючі проєкти".
3. Pay attention to the absence phrase "* Вартість навчання на проєкті вказана за тарифом “Мінімальний”"after the cards of current projects.

**Actual result:**
The phrase "* Вартість навчання на проєкті вказана за тарифом “Мінімальний”"after the cards of current projects is absent.

**Expected result:**
The phrase "* Вартість навчання на проєкті вказана за тарифом “Мінімальний”"after the cards of current projects is present.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/898ebb38-6f05-437c-b1b1-cea1704ac599)

**Comment by GNatala** [comment]
#948

**Comment by scholokov** [comment]
виправлено
