### ISSUE TITLE
Cources - pm-courses-2 / Spelling mistake оf the word "проект" in the text of the accordion "Крок 2. Практика"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1004]
**Steps to reproduce:**

1. Open www.qax-camp.com.ua/pm-courses-2/
2. Scroll down to the accordion "Крок 2. Практика" - open it.
3. Pay attention to the 3-rd sentense "Обирай **проект** та починай рухатись на зустріч до першого оферу!".

**Actual result:**
Word "проект" is wrriten with letter "е"

**Expected result:**
Word "**проєкт**" is wrriten with letter "є"

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/9eb3437b-5d82-4a55-b2a9-1831abd7696d)

**Comment by GNatala** [comment]
#998

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
