### ISSUE TITLE
Cources-pm-courses-2/ Spelling mistake оf the word "впевності" in the text of the accordion "Крок 2. Практика"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1005]
**Steps to reproduce:**

1. Open www.qax-camp.com.ua/pm-courses-2/
2. Scroll down to the accordion "Крок 2. Практика" - open it.
3. Pay attention to the 4-th sentence "Купуючи абонемент ти отримуєш реальний досвід, набуваєш **впевності** в собі, як фахівець, отримуєш доступ до блоку курсів відповідно абонементу, який ти обрав!".

**Actual result:**
Word "впевності" is written without the syllable "не".

**Expected result:**
Word "**впевненості**" is written with the syllable "не".
**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/193f9500-8cce-4b15-a2c0-852324eead3c)

**Comment by GNatala** [comment]
#998

**Comment by DmytroMarkulych** [comment]
Давайте перефоразуємо Actual Expected results таким чином щоб замінити слова correct

**Comment by GNatala** [comment]
Дякую, змінила

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
An issue is reproduced.

**Actual result:**
Word "впевності" is written without the syllable "не".

**Expected result:**
Word "**впевненості**" is written with the syllable "не".

**Environment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/2d1152a2-8ea4-4ea2-b978-48f384ad1b0f)

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
