### ISSUE TITLE
Cources-pm-courses-2/ Mistake in writing sentence the "Наші поточні тестові проекти:" in the text of the accordion "Крок 2. Практика"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1006]
**Steps to reproduce:**

1. Open www.qax-camp.com.ua/pm-courses-2/
2. Scroll down to the accordion "Крок 2. Практика" - open it.
3. Pay attention to the sentence "Наші поточні тестові проекти:" before the cards with current projects.

**Actual result:**
The sentence "Наші поточні тестові проекти:"  is written not correctly, according to requirements. 

**Expected result:**
The sentence "Наші поточні **навчальні** про**є**кти:"  is written correctly, according to requirements.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://github.com/scholokov/qax-portal-2/assets/101987790/40297265-be55-44ff-8edd-be4ce133e080)
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/b80c4a7b-e5ae-4659-9cce-2811c3afad00)

**Comment by GNatala** [comment]
#998

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
