### ISSUE TITLE
Cources - ba-courses/ Mistake in writing sentence the "Наші поточні тестові проекти:" in the text of the accordion "Крок 2. Практика"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1007]
**Steps to reproduce:**

1. Open www.qax-camp.com.ua/ba-courses/
2. Scroll down to the accordion "Крок 2. Практика" - open it.
3. Pay attention to the sentence "Наші поточні тестові проекти:" before the cards with current projects.

**Actual result:**
The sentence "Наші поточні тестові проекти:"  is written not correctly, according to requirements. 

**Expected result:**
The sentence "Наші поточні **навчальні** про**є**кти:"  is written correctly, according to requirements.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://github.com/scholokov/qax-portal-2/assets/101987790/dd46f6dd-eda1-4e9d-9d37-6404d1c58033)
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/b80c4a7b-e5ae-4659-9cce-2811c3afad00)

**Comment by GNatala** [comment]
#998

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
passed
