### ISSUE TITLE
In footer, social icons should be change rendered size background-image items

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/qax-portal-2#101]
Steps to reproduce:
1. Open main page in tablet environment https://portal.qax-camp.com.ua/
2. Scroll down to footer
3. Pay attention to **rendered size** background image of **telegram**, **facebook**, **phone** and **mail**

Actual result: 54x54px
Expected result: 48x48px

![NVIDIA_Share_u78KE4Z2iD](https://user-images.githubusercontent.com/57997443/190364261-8b24f6de-3798-4ba9-ba11-8091c3d21eb3.png)

**Comment by DmytroMarkulych** [comment]
Нажаль, сайт не підтримує мобільну версію на даний момент

**Comment by DmytroMarkulych** [comment]
Тут у нас виходить 2 дефекти. Один по вирінюванню іконок, інший по розміру. Є сенс  цей дефект розділити на 2 різних дефекти. І водночас вказати як саме мають вирівнюватися іконки соціальних мереж

**Comment by dmitryylev** [comment]
> 
дефект по нерівності виникає саме від різного розміру іконок, якщо змінити розмір іконок на однаковий - іконки будуть стояти рівно

**Comment by dmitryylev** [comment]
> Тут у нас виходить 2 дефекти. Один по вирінюванню іконок, інший по розміру. Є сенс цей дефект розділити на 2 різних дефекти. І водночас вказати як саме мають вирівнюватися іконки соціальних мереж

дефект по нерівності виникає саме від різного розміру іконок, якщо змінити розмір іконок на однаковий - іконки будуть стояти рівно

**Comment by DmytroMarkulych** [comment]
тоді варто прибрати пункт 3 в steps for reproduce, щоб не виникало не зрозумілих питань)

**Comment by dmitryylev** [comment]
> тоді варто прибрати пункт 3 в steps for reproduce, щоб не виникало не зрозумілих питань)

виправлено

**Comment by DmytroMarkulych** [comment]
Чудово)

**Comment by dmitryylev** [comment]
Partially fixed. New issue #128 opened
