### ISSUE TITLE
Розташування "Postman" не відповідає вимогам

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#1010]
Передумови: (тестую як зарейстрований користувач)
Відкрити https://www.qax-camp.com.ua/courses/qa-basic-programs/
Кроки для відтворення:

1.Відкрийте вимоги [https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BA%D0%BE %D1%80%D0%B8%D1%81%D0%BD%D1%96-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC% D0%B8](https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BA%D0%BE%D1%80%D0%B8%D1%81%D0%BD%D1%96-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%B8)

2. Зверніть увагу на розташування Postman на сайті та у вимогах

Фактичний результат:  Розташування "Postman" не відповідає вимогам
Очікуваний результат:  Розташування "Postman" відповідає вимогам

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 110.0.5481.104
![Розташування постман не выдповыдаэ вимогам](https://github.com/scholokov/qax-portal-2/assets/113175298/f9f1599b-478a-4dfe-a13d-f98f47e5fd05)

**Comment by scholokov** [comment]
виправлено

**Comment by Nadiyk** [comment]
#755 
Баг відтворюється
![девТуулс-баг відтворюється](https://github.com/scholokov/qax-portal-2/assets/113175298/2371d97d-b98c-491e-b514-2527837ce8fd)

**Comment by Nadiyk** [comment]
pass
