### ISSUE TITLE
 У вимогах немає розділу  Web&Mobile

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#1011]
Передумови: (тестую як зарейстрований користувач)
Відкрити https://www.qax-camp.com.ua/courses/qa-basic-programs/
Кроки для відтворення:

1. Відкрийте вимоги  https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA
2. Зверніть увагу, що у вимогах немає розділу Web&Mobile

Фактичний результат: У вимогах немає розділу  Web&Mobile
Очікуваний результат: У вимогах є розділ  Web&Mobile

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 110.0.5481.104
![Web-Mobile немаэ у вимогах](https://github.com/scholokov/qax-portal-2/assets/113175298/6049d72e-5961-4625-bba2-f94492f53cae)

**Comment by Nadiyk** [comment]
#771

**Comment by DmytroMarkulych** [comment]
Скріншот точно до цього дефекту?

**Comment by Nadiyk** [comment]
виправила

**Comment by scholokov** [comment]
виправлено

**Comment by Nadiyk** [comment]
pass
