### ISSUE TITLE
Lessons - Check lesson for "DNS, ping, tracert" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1012]
We need to check lesson for "DNS, ping, tracert" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/lessons/dns-ping/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81#%D0%BF%D0%BE%D0%B2%D0%BD%D0%B8%D0%B9-%D0%BF%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA-%D0%BA%D1%83%D1%80%D1%81%D1%96%D0%B2
![DNS, ping, tracert](https://github.com/scholokov/qax-portal-2/assets/109460500/b71c3621-1a0d-43dc-800e-1b3ec112367f)

**Comment by ButKoff** [comment]
#664

**Comment by BatalovaOlha** [comment]
verified
