### ISSUE TITLE
Lessons - Check lesson for "Декомпозиція та створення mind map додатку з Miro" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1017]
We need to check lesson for "Декомпозиція та створення mind map додатку з Miro" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/mc-testing/lessons/decomposition/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F--%D0%BC%D0%B0%D0%B9%D1%81%D1%82%D0%B5%D1%80-%D0%BA%D0%BB%D0%B0%D1%81%D0%B8
![Декомпозиція та створення mind map додатку з Miro](https://github.com/scholokov/qax-portal-2/assets/109460500/b2eef6b2-be93-4aca-b256-bae9fc80f7db)

**Comment by ButKoff** [comment]
#664

**Comment by DmitriiNasonov** [comment]
Testing completed
