### ISSUE TITLE
Lessons - Check lesson for "Project Management Basics - Основи проектного менеджменту" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1022]
We need to check lesson for "Project Management Basics" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/pm-basics/lessons/pm-basics/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%B8-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BC%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%BC%D0%B5%D0%BD%D1%82%D1%83
![Project Management Basics_](https://github.com/scholokov/qax-portal-2/assets/109460500/87a15f5f-918d-47d5-ade8-2ea6bffcbd1d)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
verified
