### ISSUE TITLE
 В розділі "Які мінуси регресійного тестування?" є зайве слово   "Дуже"

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#1023]
Prerequisites:
Open: https://www.qax-camp.com.ua/courses/testing/lessons/regression/
Steps  to reproduce:

1. Прокрутіть сторінку до розділу "Які мінуси регресійного тестування?"
2. Зверніть увагу на  цей опис "рутина (дуже деякі отримують задоволення від проходження тих самих тестів по 100500 разів)"

Actual result: В розділі "Які мінуси регресійного тестування?" зайве слово  "Дуже"
Expected result: В розділі "Які мінуси регресійного тестування?" слово не має слова "Дуже"

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104
![не актуальне слово ДУЖЕ](https://github.com/scholokov/qax-portal-2/assets/113175298/366fe660-95ec-43d3-bc5f-908b33a5af2a)

**Comment by Nadiyk** [comment]
#464

**Comment by scholokov** [comment]
виправлено

**Comment by Nadiyk** [comment]
pass
