### ISSUE TITLE
В розділі "Які мінуси регресійного тестування" Перед літерою "Н" з великої букви немає знаку "." не має крапки

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#1024]
Prerequisites:
Open: https://www.qax-camp.com.ua/courses/testing/lessons/regression/
Steps to  reproduce:

1. Прочитайте третій останній абзац в розділі "Які мінуси регресійного тестування?"

Actual result:  В розділі "Які мінуси регресійного тестування" Перед літерою "Н" з великої букви немає знаку "." не має крапки
Expected result: В розділі "Які мінуси регресійного тестування" Перед літерою "Н" є знак "." 

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104
![Немає крапки](https://github.com/scholokov/qax-portal-2/assets/113175298/47b185b7-ba86-4346-80a5-9b81c22ebbb1)

**Comment by Nadiyk** [comment]
#464

**Comment by DmytroMarkulych** [comment]
Додайте деталей в баг репорт. В якому розділі

**Comment by Nadiyk** [comment]
виправила

**Comment by scholokov** [comment]
виправлено

**Comment by Nadiyk** [comment]
Pass
