### ISSUE TITLE
В "Розділі які мінуси регресійного тестування" Перед словом "Але" немає крапки

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#1025]
Prerequisites:
Open: https://www.qax-camp.com.ua/courses/testing/lessons/regression/
Steps to reproduce:

1. Зверніть увагу, що перед словом "Але" немає "."

Actual result: В "Розділі які мінуси регресійного тестування" Перед словом "Але" немає крапки
Expected result: В "Розділі які мінуси регресійного тестування" Перед словом "Але" є крапка

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104
![а з великої букви і пред А немає коми](https://github.com/scholokov/qax-portal-2/assets/113175298/0b22c88f-8fd5-4676-ae25-8e65de7b1da1)

**Comment by Nadiyk** [comment]
https://github.com/scholokov/qax-portal-2/issues/464

**Comment by Nadiyk** [comment]
виправила

**Comment by scholokov** [comment]
виправлено

**Comment by Nadiyk** [comment]
Pass
