### ISSUE TITLE
В розділі "Парадокс пестициду" Після  слова "Але" є кома

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#1026]
Prerequisites:
Open: https://www.qax-camp.com.ua/courses/testing/lessons/regression/
Steps to reproduce:

1. Зверніть увагу, що після слова "Але" є знак ","

Actual result:  В розділі "Парадокс пестициду" Після  слова "Але" є кома
Expected result:   В розділі "Парадокс пестициду" Після  слова "Але" немає коми
Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104
![АЛЕ ,](https://github.com/scholokov/qax-portal-2/assets/113175298/f14eab53-4dc9-4b17-8066-591ef592bdd5)

**Comment by Nadiyk** [comment]
https://github.com/scholokov/qax-portal-2/issues/464

**Comment by DmytroMarkulych** [comment]
Додайте деталей в якому розділі присутня проблема

**Comment by Nadiyk** [comment]
виправила

**Comment by scholokov** [comment]
мені здається кома там потрібна...

**Comment by Nadiyk** [comment]
pass
