### ISSUE TITLE
Написано "куа" замість QA

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#1027]
Prerequisites:
Open: https://www.qax-camp.com.ua/courses/testing/lessons/regression/
Steps to reproduce:

Зверніть увагу,  "куа" замість QA

Actual result:  Написано "куа" замість QA
Expected result:  Написано  QA

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104
![QA](https://github.com/scholokov/qax-portal-2/assets/113175298/e59880b0-cca5-45e2-93fa-1ba8e91c7a8b)

**Comment by Nadiyk** [comment]
https://github.com/scholokov/qax-portal-2/issues/464

**Comment by scholokov** [comment]
виправлено

**Comment by Nadiyk** [comment]
pass
