### ISSUE TITLE
Page - New template - no form

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#1028]
Зробити новий темплейт для сутності "сторінка"
на якій має бути відсутня "форма".
зробити у двох варіантах - з відгуками і без
![image](https://github.com/scholokov/qax-portal-2/assets/22824947/4c1fc953-a8c0-4d7b-ab51-a5e0b5564a30)

**Comment by poroskundenys** [comment]
https://prnt.sc/lDp0YRfkAyjP
