### ISSUE TITLE
GitHub Wiki - "1.7.1.-Урок" - "Тестування – Майстер-класи" - "Проведення Ретро" lesson is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1029]
**Steps of reproducing**
1. Open https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F--%D0%BC%D0%B0%D0%B9%D1%81%D1%82%D0%B5%D1%80-%D0%BA%D0%BB%D0%B0%D1%81%D0%B8
2. Scroll to "Тестування – Майстер-класи" cource
3. Pay attention to the absence of the lesson "Проведення Ретро"

**Actual Result**
"Проведення Ретро" lesson is missing

**Expected Result**
"Проведення Ретро" lesson is present

**Additional information**
https://www.qax-camp.com.ua/courses/mc-testing/

**Enviroments**
Windows 10, Chrome 114.0.5735.199 (64 bit)
![Балкани – Long-Travel - Google Chrome 05 07 2023 17_57_05](https://github.com/scholokov/qax-portal-2/assets/95171672/2aa9c87e-51a5-4be7-8fea-6fbc5ec35dd5)
![Тестування – Майстер-класи – QAX Camp - Google Chrome 05 07 2023 17_57_32](https://github.com/scholokov/qax-portal-2/assets/95171672/467332ab-54d2-49c8-bd90-cda1ae41256e)

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
