### ISSUE TITLE
In footer, instagram, phone and mail icons should change on hover

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/qax-portal-2#103]
Steps to reproduce:
1. Open disign in figma https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A22
2. Open main page in tablet environment https://portal.qax-camp.com.ua/
3. Scroll down to footer
4. Pay attention to the instagram, phone and mail icons on hover

Actual result: icons not changed
Expected result: icons changed

![NVIDIA_Share_VEhL5I1eDU](https://user-images.githubusercontent.com/57997443/190375433-d837d324-fcf0-4320-9c7f-39b157817197.png)

![NVIDIA_Share_9TZ76WWmM4](https://user-images.githubusercontent.com/57997443/190375451-caf77668-c428-40bb-9451-4dca099230fe.png)

**Comment by DmytroMarkulych** [comment]
Нажаль, сайт не підтримує мобільну версію на даний момент

**Comment by dmitryylev** [comment]
Partially fixed. New issue #128 opened
