### ISSUE TITLE
Lesson "Test Data Generation Tools"/The Preview, the Logo is missing in the lower left corner

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1030]
Steps to Reproduce:
1. Open page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/test-data-generation-tools/
2. Pay attention to the lower left corner of the Preview.

Actual Result: the logo is missing in the lower left corner
Expected Result: the logo is present in the lower left corner

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/a07572af-d3fa-4093-aa7d-0838be338c25)

**Comment by ODrobik** [comment]
#803

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
