### ISSUE TITLE
Lesson "Test Data Generation Tools"/Table - Line "Мультигенератор" - The word "Мультігенератор" is with a grammatical error

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1031]
Steps to Reproduce:
1. Open page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/test-data-generation-tools/
2. Pay attention to the word "Мультігенератор" in the line "Мультигенератор" of the table 

Actual Result: The word "Мультігенератор" is with a grammatical error
Expected Result: The word "Мультигенератор" is without a grammatical error

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/8465bd36-685c-4cc0-aa66-5210b4cf11ce)

**Comment by ODrobik** [comment]
#803

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
