### ISSUE TITLE
Lesson "Test Data Generation Tools"/Table - Сolumns "Comments" - The word "Строки" is written in Russian

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1032]
Steps to Reproduce:
1. Open page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/test-data-generation-tools/
2. Pay attention to the word "Cтроки" in the columns "Comments" of the table

Actual Result: The word "Строки" is written in Russian
Expected Result: The word "Рядки" is written in Ukrainian 

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/2f6fdc21-8a7f-4351-88db-ee5d64d135b8)

**Comment by ODrobik** [comment]
#803

**Comment by scholokov** [comment]
вправлено

**Comment by ODrobik** [comment]
перевірено
