### ISSUE TITLE
Lesson "Test Data Generation Tools"/Table - Сolumns "Comments" - After of the text "JSON – beautify" the punctuation mark is missed ":"  

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1033]
Steps to Reproduce:
1. Open page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/test-data-generation-tools/
2. Pay attention to the text "JSON – beautify" in the columns "Comments" of the table

Actual Result: After of the text "JSON – beautify" the punctuation mark is missed ":"  
Expected Result: After of the text "JSON – beautify" the punctuation mark is inserted ":"  

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment: 
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/d3ee5b0e-d647-4538-a11b-0876765e6032)

**Comment by ODrobik** [comment]
#803

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
