### ISSUE TITLE
"Абонемент “Стандартний”/ Buttons "$3200 /місяць", "Обрати цей курс" are different from the design in Figma

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1035]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/pass-standard/
2. Scroll down to the buttons "$3200 /місяць", "Обрати цей курс".

**Actual result:**
Buttons "$3200 /місяць", "Обрати цей курс" are different from the design in Figma.

**Expected result:**
Buttons "$3200 /місяць", "Обрати цей курс" are the same as the design in Figma.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=390-1035&mode=design&t=zrWihmokGoLEN3Io-0

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/8e82438d-84df-46d4-8d99-d0b513878488)

**Comment by GNatala** [comment]
#971

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
