### ISSUE TITLE
"Абонемент “Максимальний”/ Buttons "$3700 /місяць", "Обрати цей курс" are different from the design in Figma

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1036]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/pass-max/
2. Scroll down to the buttons "$3700 /місяць", "Обрати цей курс".

**Actual result:**
Buttons "$3700 /місяць", "Обрати цей курс" are different from the design in Figma.

**Expected result:**
Buttons "$3700 /місяць", "Обрати цей курс" are the same as the design in Figma.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=390-1035&mode=design&t=zrWihmokGoLEN3Io-0

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/e90dec02-7ab0-4fdd-ac35-5ff363eed0ab)

**Comment by GNatala** [comment]
#972

**Comment by scholokov** [comment]
вправлено
