### ISSUE TITLE
Invite - This form "Записатися на курс" should not be present on this page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1038]
You must delete this form "Записатися на курс" on this page.
Environments: https://www.qax-camp.com.ua/invite/
![Записатися на курси](https://github.com/scholokov/qax-portal-2/assets/109460500/6da898ab-5fae-46c7-811c-04645c1043a4)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
