### ISSUE TITLE
Register - This form "Записатися на курс" should not be present on this page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1039]
You must delete this form "Записатися на курс" on this page.
Environments: https://www.qax-camp.com.ua/register/
![Записатися на курси](https://github.com/scholokov/qax-portal-2/assets/109460500/ae25ebd1-1836-42c7-bfc2-ef21dbcbce66)

**Comment by scholokov** [comment]
виконано

**Comment by GNatala** [comment]
перевірено
