### ISSUE TITLE
In the lesson page, present how display item "Наступний урок" with other 3 items

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/qax-portal-2#104]
Steps to reproduce:
1. Open design in figma https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A12775
2. Pay attention to the items after lesson

Description: Present how looking all 4 items togather

Actual result: Not presented
Expected result: Presented

Notes: If it does not break the design concept and fits the style, change arrow for "Наступний урок" and "Попередній урок" to this
![chrome_QJ2A5gKh4q](https://user-images.githubusercontent.com/57997443/190445424-30fd5b09-5740-43a6-b3c6-a3103c138a78.png)

![ApplicationFrameHost_YNdbC5yKmi](https://user-images.githubusercontent.com/57997443/190443024-08296c4c-1c7e-4df6-bbd8-e6ba90bbbcc0.png)

**Comment by scholokov** [comment]
якої саме кнопки не вистачає на дизайні?

**Comment by dmitryylev** [comment]
> якої саме кнопки не вистачає на дизайні?

не вистачало "наступний урок", але вже є
