### ISSUE TITLE
Login - This form "Записатися на курс" should not be present on this page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1041]
You must delete this form "Записатися на курс" on this page.
Environments: https://www.qax-camp.com.ua/login/
![Записатися на курси](https://github.com/scholokov/qax-portal-2/assets/109460500/4d2e0c1d-3b73-4e80-bbc9-86cc37b3d501)

**Comment by scholokov** [comment]
виконано

**Comment by GNatala** [comment]
перевірено
