### ISSUE TITLE
Register / Size of the place for the avatar is 554x554px

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1046]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/register/
2. Pay attention to the place for the avatar.

**Actual result:**
Size of the place for the avatar is 554x554px.

**Expected result:**
Size of the place for the avatar is 554x554px for Decktop, width 1400px.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=2178-1133&mode=design&t=PXsIER9WTXICyjAN-0

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/7d10ac70-95b1-49c4-94bb-2fc0c638d2b2)

**Comment by GNatala** [comment]
#1039

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
