### ISSUE TITLE
Lesson "Test Data Generation Tools"/In the column "Comments" to the link "https://onlinetools.com/" the text "Рандомна строка" is written in Russian

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1048]
Steps to Reproduce:
1. Open page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/test-data-generation-tools/
2. Pay attention to the text "Рандомна строка" in the line "Мультигенератор" of the table

Actual Result: the text "Рандомна строка" is written in Russian
Expected Result: the text "Рандомний рядок" is written in Ukrainian

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/a57ef67a-2c12-496b-9e05-bf1feb7725e4)

**Comment by ODrobik** [comment]
#803

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
