### ISSUE TITLE
Розташування розділу "GitHub" на сайті не відповідає розташуванню у вимогах

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#1049]
Передумови:
Відкрити https://www.qax-camp.com.ua/courses/qa-basic-programs/
Кроки для відтворення:

Відкрийте вимоги https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BA%D0%BE%D1%80%D0%B8%D1%81%D0%BD%D1%96-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%B8

1. Зверніть увагу на розташування "GitHub" на сайті та у вимогах

Фактичний результат:  Розташування розділу "GitHub" на сайті не відповідає розташуванню у вимогах
Очікуваний результат:  Розташування розділу "GitHub" на сайті   відповідає розташуванню у вимогах

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104
![ГітХаб - вимоги](https://github.com/scholokov/qax-portal-2/assets/113175298/f989cf98-49e8-42b4-ab09-5556a9612909)

**Comment by scholokov** [comment]
виправлено

**Comment by Nadiyk** [comment]
виправоено
