### ISSUE TITLE
Events / Size of the Preview photo is 980x784px

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1051]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/events/test/
2. Pay attention to the Preview photo.

**Actual result:**
Size of the Preview photo is 980x784px.

**Expected result:**
Size of the Preview photo is **980x450px.**

**Environment:**
Decktop
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6076-950&mode=design&t=5CaoXyeDza2bdayO-0

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/451acd5d-e5e7-406e-a164-2cdf6847db5d)

**Comment by GNatala** [comment]
#770

**Comment by scholokov** [comment]
підставив для прикладу нашу стандартну превьюшку
