### ISSUE TITLE
Events / Font-family of the content of the page is Montserrat

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1052]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/events/test/
2. Pay attention to the font-family of the content of the page.

**Actual result:**
Font-family of the content of the page is Montserrat.

**Expected result:**
Font-family of the content of the page is Raleway.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6076-950&mode=design&t=5CaoXyeDza2bdayO-0

**Attachment:**

https://github.com/scholokov/qax-portal-2/assets/101987790/81b1ee37-32c2-4cfe-844f-61fd22c53988

![image](https://github.com/scholokov/qax-portal-2/assets/101987790/8d153616-9c61-43f0-a444-cb96b9e85768)

**Comment by GNatala** [comment]
#770

**Comment by scholokov** [comment]
ця проблема стосується лише ордера чи проблема глобальна?

**Comment by GNatala** [comment]
Бачу Montserrat тільки на сторінці https://www.qax-camp.com.ua/events/test/

**Comment by GNatala** [comment]
passed
