### ISSUE TITLE
Lessons - Lesson "Total Commander"/Grammar error "Завдяки двопанельному інтерфейсу інтерфейсу"

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1055]
**Steps to retroduce:**

1. Open: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/total-commander/
2. Scroll down to the text "Дві панелі для порівняння та копіювання: Завдяки двопанельному **інтерфейсу інтерфейсу** ви можете легко порівнювати файли та папки, виконувати синхронізацію та копіювання між двома різними місцями."
3. Pay attention to the text "Завдяки двопанельному **інтерфейсу інтерфейсу**"

**Actual result:**
Grammar error "Завдяки двопанельному **інтерфейсу інтерфейсу**"
**Expected result:**
Text must be "Завдяки двопанельному інтерфейсу"

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/32ab5055-ef18-433f-a6c9-b7de5092a0af)

**Comment by prokopenkoga1977** [comment]
[#780](https://github.com/scholokov/qax-portal-2/issues/780)

**Comment by scholokov** [comment]
виконано

**Comment by prokopenkoga1977** [comment]
Passed
