### ISSUE TITLE
Lessons - Lesson "Slack"/Grammar error "обмінюватися повідомленнями один на одного"

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1056]
**Steps to retroduce:**

1. Open: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/slack/
2. Scroll down to the text "Зручна комунікація: Slack забезпечує швидку та зручну комунікацію у режимі реального часу. Користувачі можуть обмінюватися повідомленнями **один на одного** або в рамках групових чатів, створювати тематичні канали для обговорення проектів та інтересів."
3. Pay attention to the text "Користувачі можуть обмінюватися повідомленнями **один на одного**"

**Actual result:**
Grammar error "обмінюватися повідомленнями **один на одного**"
**Expected result:**
Text must be "обмінюватися повідомленнями **один з одним**"

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/26d509f3-bb2a-4fdd-9055-b857059b156e)

**Comment by prokopenkoga1977** [comment]
[#816](https://github.com/scholokov/qax-portal-2/issues/816)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
