### ISSUE TITLE
Lessons - Lesson "Slack"/Grammar error "Це дозволяє команді працювати в єдиному екосистемі"

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1057]
**Steps to retroduce:**

1. Open: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/slack/
2. Scroll down to the text "Інтеграція з іншими інструментами: Slack має широкі можливості інтеграції з різними інструментами та сервісами, такими як Google Drive, Trello, GitHub, Jira та багатьма іншими. Це дозволяє команді працювати в єдиному екосистемі, отримувати сповіщення, спільно використовувати файли та отримувати оновлення з різних джерел у зручному для них місці."
3. Pay attention to the text "Це дозволяє команді працювати **в єдиному екосистемі**"

**Actual result:**
Grammar error "Це дозволяє команді працювати **в єдиному екосистемі**"
**Expected result:**
Text must be "Це дозволяє команді працювати в **єдиної** екосистемі"

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/21ea0137-2cbf-4611-9f9d-55df8d6e7412)

**Comment by prokopenkoga1977** [comment]
[#816](https://github.com/scholokov/qax-portal-2/issues/816)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
