### ISSUE TITLE
Lessons - Lesson "Slack"/Grammar error "і зберігає всю історію комунікації для подальшої зручної відстежування"

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1058]
**Steps to retroduce:**

1. Open: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/slack/
2. Scroll down to the text "Пошук інформації: Slack забезпечує можливість швидкого пошуку повідомлень, файлів та інформації в архівах. Це дозволяє легко знаходити потрібні дані, навіть якщо вони були надіслані раніше, і зберігає всю історію комунікації **для подальшої зручної відстежування**."
3. Pay attention to the text "для **подальшої зручної** відстежування"

**Actual result:**
Grammar error "і зберігає всю історію комунікації **для подальшої зручної** відстежування"
**Expected result:**
Text must be "і зберігає всю історію комунікації **для подальшого зручного** відстежування"

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/97a8b946-a6b5-4dc8-b9c8-859f07a4ea30)

**Comment by prokopenkoga1977** [comment]
[#816](https://github.com/scholokov/qax-portal-2/issues/816)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
