### ISSUE TITLE
Lessons - Lesson "Slack"/Grammar error "які працюють у розподілених команд"

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1059]
**Steps to retroduce:**

1. Open: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/slack/
2. Scroll down to the text "Мобільний доступ: Slack надає мобільні додатки для iOS та Android, що дозволяє користувачам залишатися підключеними та отримувати сповіщення навіть поза офісом. Це забезпечує гнучкість та доступність для команд, які працюють у **розподілених команд**, віддалених робочих місцях або в дорозі."
3. Pay attention to the text "які працюють у **розподілених команд**"

**Actual result:**
Grammar error "які працюють у **розподілених команд**"
**Expected result:**
Text must be "які працюють у розподілених **командах**"

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/3ab15f8f-0785-4997-a6b7-868e21f1a091)

**Comment by prokopenkoga1977** [comment]
[#816](https://github.com/scholokov/qax-portal-2/issues/816)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
