### ISSUE TITLE
Lessons - Check lesson for "Процес поставки ПЗ" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1062]
We need to check lesson for "Процес поставки ПЗ" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/processes/lessons/sw-delivery/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D0%B8
![Процес поставки ПЗ](https://github.com/scholokov/qax-portal-2/assets/109460500/7a49482a-2b0b-4556-a5bc-b931a9f5ac83)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
verified
