### ISSUE TITLE
Lessons - Check lesson for "Kickoff" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1063]
We need to check lesson for "Kickoff" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/processes/lessons/kickoff/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D0%B8
![Kickoff](https://github.com/scholokov/qax-portal-2/assets/109460500/8c77867b-56b4-4bc1-aaff-77a7285595b2)

**Comment by ButKoff** [comment]
#664

**Comment by DmitriiNasonov** [comment]
testing completed
