### ISSUE TITLE
Lessons - Check lesson for "Як тестувати те, чого “немає”?" page #859 - The link in the requirements is false

### ISSUE THREAD

**Issue by Artem-16** [scholokov/qax-portal-2#1064]
**Steps to playback:**
1. Open https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F--%D0%BC%D0%B0%D0%B9%D1%81%D1%82%D0%B5%D1%80-%D0%BA%D0%BB%D0%B0%D1%81%D0%B8
2. Scroll to "Testing - Master classes"
3. Pay attention to"Як тестувати те, чого “немає”?"

**Actual result:**
The link in the requirements is false

**Expected result:**
The link in the requirements is true
![лінка](https://github.com/scholokov/qax-portal-2/assets/132911639/cae737a5-6377-44cb-a7da-82fda5f0e345)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![невірна лінка вимоги](https://github.com/scholokov/qax-portal-2/assets/132911639/feccf72f-17ce-4490-b83f-44bf9403575f)

**Comment by Artem-16** [comment]
#859

**Comment by scholokov** [comment]
виправлено у вимогах
