### ISSUE TITLE
Lessons - Lesson "TestRail" page (update) #820/DS logo is missed in the preview.

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1067]
**Steps to retroduce:**

1. Open https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/testrail/
2. Scroll down to the Preview.
3. Pay attention to the absence of DS logo.

**Actual result:**
DS logo is missed in the preview.
**Expected result:**
DS logo is present in preview.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://github.com/scholokov/qax-portal-2/wiki/1.1.5-Preview

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/256cf1ec-081e-4d95-8d7a-038281a1f86a)

**Attachments:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/3f2d9bb3-0967-4f97-8f49-785bfdf86fa7)

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/7dbded74-2dab-43c0-b6fe-b203346f2b2c)

**Comment by prokopenkoga1977** [comment]
[#820](https://github.com/scholokov/qax-portal-2/issues/820)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
