### ISSUE TITLE
Courses - Check the grouping of lessons on the "Тестування – Майстер-класи" page (Update) - No author in the preview

### ISSUE THREAD

**Issue by Artem-16** [scholokov/qax-portal-2#1069]
**Steps to playback:**

1. Open https://www.qax-camp.com.ua/courses/mc-testing/
2. Pay attention to the "Preview" 

**Actual result:**
No author in the preview

**Expected result:**
 Author in the preview
![вимоги мастер клас](https://github.com/scholokov/qax-portal-2/assets/132911639/1add8779-fd81-418e-ae0e-0b02c1f80472)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![баг мастер клас](https://github.com/scholokov/qax-portal-2/assets/132911639/5819295f-f60a-4fdc-afcf-4370044c0834)

**Comment by Artem-16** [comment]
#858

**Comment by DmytroMarkulych** [comment]
Давайте перефразуємо bug report щоб не використовувати there is

**Comment by scholokov** [comment]
виправлено
