### ISSUE TITLE
Lessons - Lesson "TestRail" page (update) #820/DS logo is missed in the preview of the video (part 1)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1070]
**Steps to retroduce:**

1. Open https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/testrail/
2. Scroll down to the Preview of the video (part 1).
3. Pay attention to the absence of DS logo.

**Actual result:**
DS logo is missed in the preview of the video (part 1).
**Expected result:**
DS logo is present in preview of the video (part 1).
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/23bc4688-29ad-41f2-882f-e0db69cd28d6)

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/6327d543-e52a-4c2f-9eec-f217efc3ed63)

**Attachments:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/320d53c4-dd89-4550-ac1a-a9e6e6821880)

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/19c47a7c-4a70-457a-90e3-d4b4ab8da255)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
