### ISSUE TITLE
Lessons - Lesson "TestRail" page (update) #820/DS logo is missed in the preview of the video (part 2)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1072]
**Steps to retroduce:**

1. Open https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/testrail/
2. Scroll down to the Preview of the video (part 2).
3. Pay attention to the absence of DS logo.

**Actual result:**
DS logo is missed in the preview of the video (part 2).
**Expected result:**
DS logo is present in preview of the video (part 2).
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/48a3bc66-76ae-4389-92be-0a5852287e46)

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/065b7052-70d8-485a-88b0-71d649834397)

**Attachments:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/431e9337-415d-4ab6-9cf3-675cd42ac5b3)

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/cc8e1161-7c00-4ada-bb47-d9e97dfbc73a)

**Comment by prokopenkoga1977** [comment]
[#820](https://github.com/scholokov/qax-portal-2/issues/820)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
