### ISSUE TITLE
GitHub Wiki - 1.7.1. Урок - "Тестування – Майстер-класи" -  The last 5 lessons have the same "slug" and "id"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1075]
**Steps of reproducing**
1. Open https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F--%D0%BC%D0%B0%D0%B9%D1%81%D1%82%D0%B5%D1%80-%D0%BA%D0%BB%D0%B0%D1%81%D0%B8
2. Scroll to "Тестування – Майстер-класи" course

**Actual Result**
The last 5 lessons have the same "slug" and "id"

**Expected Result**
The last 5 lessons have different "slug" and "id"

**Enviroments**
Windows 10, Chrome 114.0.5735.199 (64 bit)
![1 7 1  Урок · scholokov_qax-portal-2 Wiki - Google Chrome 12 07 2023 13_16_55](https://github.com/scholokov/qax-portal-2/assets/95171672/ef1ecc16-1fc9-47a7-b20e-e50054fb3f37)

**Comment by scholokov** [comment]
виконано

**Comment by DmitriiNasonov** [comment]
Fixed partially. Bug with "id" is not fixed. created a new bug report

**Comment by DmitriiNasonov** [comment]
#1087
