### ISSUE TITLE
Lessons - Check lesson for "10 Min Mail" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1076]
We need to check lesson for "10 Min Mail" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/10-min-mail/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BA%D0%BE%D1%80%D0%B8%D1%81%D0%BD%D1%96-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%B8
![10 Min Mail](https://github.com/scholokov/qax-portal-2/assets/109460500/f467fd6a-b4da-4e78-b1d8-f53b6b5ad99c)

**Comment by ButKoff** [comment]
#664

**Comment by DmitriiNasonov** [comment]
Testing completed
