### ISSUE TITLE
Lessons - Check lesson for "Параметри Екрану" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1077]
We need to check lesson for "Параметри Екрану" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/lessons/screens/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#web--mobile
![Параметри Екрану](https://github.com/scholokov/qax-portal-2/assets/109460500/3e6e0ba8-ad3c-4f71-a1ed-413625ed00f6)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
verified
