### ISSUE TITLE
Lessons - Check lesson for "Як тестувати те, чого “немає”?" - Failed to formulate the text correctly

### ISSUE THREAD

**Issue by Artem-16** [scholokov/qax-portal-2#1078]
**Steps to playback:**

1. Open https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F--%D0%BC%D0%B0%D0%B9%D1%81%D1%82%D0%B5%D1%80-%D0%BA%D0%BB%D0%B0%D1%81%D0%B8
2. Scroll to don
3. Pay attention to - 1.11 Блок "Спробувати самостійно"

**Actual result:** 
Failed to formulate the text correctly - "Блок "Спробувати самостійно" має назву та вигляд, як на картинці"

**Expected result:**
 The text correctly  - "Може бути присутній - Блок "Спробувати самостійній" має назву та вигляд, як на картинці"

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![баг вимоги блок  Спробуй сам](https://github.com/scholokov/qax-portal-2/assets/132911639/86f1af7e-bb14-4ea1-899e-fcda313c6ae0)

**Comment by Artem-16** [comment]
#859

**Comment by scholokov** [comment]
додав до вимог підпункти 1.11.1 та 1.11.2
