### ISSUE TITLE
Lessons - Сheck lesson "Viewport" page that was deleted

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1079]
We need to check the lesson "Viewport" page, that was deleted.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/lessons/viewport/
![Viewport](https://github.com/scholokov/qax-portal-2/assets/109460500/54e6b43d-f3bb-48f4-8f2a-e692d80174dd)

**Comment by GNatala** [comment]
verified
