### ISSUE TITLE
Courses - Check all course previews and lesson according to Canva

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1080]
We need to check all course previews and lesson according to Canva.
Please check availability of requirements, functional compliance and design compliance.
Course requirements: https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81
Lesson requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA
![Повний перелік курсів](https://github.com/scholokov/qax-portal-2/assets/109460500/07ece179-5c98-46a5-a82e-2a45f573cbf9)

**Comment by GNatala** [comment]
verified
