### ISSUE TITLE
Lesson "Work search tips" / Spelling mistake оf the word "проект" in the subsection "Якщо запросили на тих співбесіду"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1081]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/cv/lessons/work-search-tips/
2. Scroll down to the subsection "Якщо запросили на тих співбесіду".
3. Pay attention to the 2-nd and 5-th sentences -  spelling оf the word "проект".

**Actual result:**
Word "проект" is wrriten with letter "е"

**Expected result:**
Word "**проєкт**" is wrriten with letter "є"

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://github.com/scholokov/qax-portal-2/assets/101987790/e637504d-72b4-46b0-8b23-10410bdc9897)

**Comment by GNatala** [comment]
#866

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
