### ISSUE TITLE
 Розділ "Топ питанняя на тех співбесіді" описано російською мовою

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#1083]
Передумови:
Відкрити: https://www.qax-camp.com.ua/courses/cv/lessons/interview-qestions/
Кроки для відтворення:

1. Зверніть увагу, що розділ "Топ питанняя на тех співбесіді" описано російською мовою

Фактичний результат: "Топ питанняя на тех співбесіді" описано російською мовою
Очікуваний результат: "Топ питанняя на тех співбесіді" описано українською мовою

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104
![Топ питань на співбесіді, описаний російською](https://github.com/scholokov/qax-portal-2/assets/113175298/b49f3935-d9ee-4f62-b039-0f9e50bbb65d)

**Comment by Nadiyk** [comment]
#869

**Comment by scholokov** [comment]
виправлено

**Comment by Nadiyk** [comment]
Виправлено
