### ISSUE TITLE
Lesson "Work search tips" / Spelling mistake оf the word "тих" in the phrase" тих співбесіда"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1084]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/cv/lessons/work-search-tips/
2. Scroll down to the subsection "Якщо запросили на тих співбесіду".
3. Pay attention to the title and 5-th sentences -  spelling оf the word "тих".

**Actual result:**
Word "тих" is wrriten with letter "и"

**Expected result:**
Word "**тих**" is wrriten with letter "е"

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://github.com/scholokov/qax-portal-2/assets/101987790/83747c35-a394-4b29-9a6d-00ae8f931119)

**Comment by GNatala** [comment]
#866

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
An issue is reproduced.
Pay attention to the title and 5-th sentences -  spelling оf the word "тих".

**Actual result:**
Word "тих" is wrriten with letter "и"

**Expected result:**
Word "**тих**" is wrriten with letter "е"

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

![image](https://github.com/scholokov/qax-portal-2/assets/101987790/2a4ba574-6580-484e-b3dd-962efaed31b0)

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
