### ISSUE TITLE
GitHub Wiki - 1.7.1. Урок - "Тестування – Майстер-класи" - The first 2 lessons have the same "id"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1086]
**Steps of reproducing**
1. Open https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F--%D0%BC%D0%B0%D0%B9%D1%81%D1%82%D0%B5%D1%80-%D0%BA%D0%BB%D0%B0%D1%81%D0%B8
2. Scroll to "Тестування – Майстер-класи" course

**Actual Result**
The first 2 lessons have the same "id"

**Expected Result**
The first 2 lessons have different "id"

**Enviroments**
Windows 10, Chrome 114.0.5735.199 (64 bit)
![1 7 1  Урок · scholokov_qax-portal-2 Wiki - Google Chrome 17 07 2023 18_13_50](https://github.com/scholokov/qax-portal-2/assets/95171672/408405a2-51db-419c-976c-dc7b178ad2d3)

**Comment by scholokov** [comment]
інформацію про айді вилалено з вимог

**Comment by DmitriiNasonov** [comment]
Canceled
