### ISSUE TITLE
GitHub Wiki - 1.7.1. Урок - "Тестування – Майстер-класи" - Lessons "Як створювати тестову документацію за вимогами у TestRail?" and "Тестування - Portal - Тест / SCRUM" have the same "id"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1088]
**Steps of reproducing**
1. Open https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F--%D0%BC%D0%B0%D0%B9%D1%81%D1%82%D0%B5%D1%80-%D0%BA%D0%BB%D0%B0%D1%81%D0%B8
2. Scroll to "Тестування – Майстер-класи" course

**Actual Result**
Lessons "Як створювати тестову документацію за вимогами у TestRail?" and "Тестування - Portal - Тест / SCRUM" have the same "id"

**Expected Result**
Lessons "Як створювати тестову документацію за вимогами у TestRail?" and "Тестування - Portal - Тест / SCRUM" have different "id"

**Enviroments**
Windows 10, Chrome 114.0.5735.199 (64 bit)
![1 7 1  Урок · scholokov_qax-portal-2 Wiki - Google Chrome 17 07 2023 18_49_51](https://github.com/scholokov/qax-portal-2/assets/95171672/13e2670b-05a0-4aeb-a1ff-db6307f43463)

**Comment by scholokov** [comment]
інформацію про айді видалено з вимог

**Comment by DmitriiNasonov** [comment]
Canceled
