### ISSUE TITLE
Courses - Check the grouping of lessons on the "Тестування – Майстер-класи" - Missing design "Тестування – Майстер-класи"

### ISSUE THREAD

**Issue by Artem-16** [scholokov/qax-portal-2#1092]
**Steps to playback:**

1. Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=4053-569&mode=design&t=A2NzDMvzvDU2gG6p-0

**Actual result:**
Missing design "Тестування – Майстер-класи"

**Expected result:**
Design is "Тестування – Майстер-класи"

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![Monosnap Portal design – Figma 2023-07-19 09-21-54](https://github.com/scholokov/qax-portal-2/assets/132911639/4ee9bc4d-e417-445a-9d29-9c32b018c74a)

**Comment by Artem-16** [comment]
#858

**Comment by DmytroMarkulych** [comment]
додайте всі дані в баг репорт
