### ISSUE TITLE
Lessons - Lesson "TestRail" page (update) #820/Grammar error "зручний" is lower case

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1093]
**Steps to retroduce:**

1. Open https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/testrail/
2. Scroll down to the text "зручний поділ та ефективне управління тест-кейсами, сьютами та тест-планами;"
3. Pay attention to the word "зручний".

**Actual result:**
"зручний" is lower case
**Expected result:**
"зручний" is uppercase
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&mode=design&t=YH9pJOI8ymJyw7XJ-0

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/0049c1e0-2c9e-4814-a759-e6aa1878481e)

**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/09800177-0fa7-414c-8364-05d2bb21ec22)

**Comment by prokopenkoga1977** [comment]
[#820](https://github.com/scholokov/qax-portal-2/issues/820)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
