### ISSUE TITLE
Lessons - Lesson "TestRail" page (update) #820/Grammar error "простий" is lower case

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1094]
**Steps to retroduce:**

1. Open https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/testrail/
2. Scroll down to the text "простий і зручний інтерфейс користувача;"
3. Pay attention to the word "простий".

**Actual result:**
"простий" is lower case
**Expected result:**
"простий" is uppercase
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&mode=design&t=YH9pJOI8ymJyw7XJ-0

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/043206ad-ab3b-4bc7-9d54-54df2ce9a6e9)

**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/ae5a88a4-13fb-4d89-a919-5de440c85e46)

**Comment by prokopenkoga1977** [comment]
[#820](https://github.com/scholokov/qax-portal-2/issues/820)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
