### ISSUE TITLE
Lessons - Lesson "TestRail" page (update) #820/Grammar error "графічне" is lower case

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1095]
**Steps to retroduce:**

1. Open https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/testrail/
2. Scroll down to the text "графічне відображення тестового прогону;"
3. Pay attention to the word "графічне".
**Actual result:**
"графічне" is lower case
**Expected result:**
"графічне" is uppercase
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements**: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&mode=design&t=YH9pJOI8ymJyw7XJ-0

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/fc5e2d05-336d-459d-bd0b-2369f801ec75)

**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/c025e809-e4db-402b-865d-7d0518d5264d)

**Comment by prokopenkoga1977** [comment]
[#820](https://github.com/scholokov/qax-portal-2/issues/820)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
