### ISSUE TITLE
Lessons - Lesson "TestRail" page (update) #820/Grammar error "надання" is lower case

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1096]
**Steps to retroduce:**

1. Open https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/testrail/
2. Scroll down to the text "надання інформації про хід тестування у реальному часі;"
3. Pay attention to the word "надання".

**Actual result:**
"надання" is lower case
**Expected result:**
"надання" is uppercase
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&mode=design&t=YH9pJOI8ymJyw7XJ-0

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/a85cbfe6-7198-4fae-af1e-6d942b091221)

**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/b327f44c-86ad-422e-af6a-5b7fca069d0d)

**Comment by prokopenkoga1977** [comment]
[#820](https://github.com/scholokov/qax-portal-2/issues/820)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
