### ISSUE TITLE
Lessons - Lesson "TestRail" page (update) #820/Grammar error "інтеграція" is lower case

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1097]
**Steps to retroduce:**

1. Open https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/testrail/
2. Scroll down to the text "інтеграція з такими баг-трекерами, як Jira;"
3. Pay attention to the word "інтеграція".
**Actual result:**
"інтеграція" is lower case
**Expected result:**
"інтеграція" is uppercase
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&mode=design&t=YH9pJOI8ymJyw7XJ-0

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/c28beb74-ac8b-466d-b219-c84c2abb9a20)

**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/65429497-2f75-4386-bfbd-378bdd0ac3fa)

**Comment by prokopenkoga1977** [comment]
[#820](https://github.com/scholokov/qax-portal-2/issues/820)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
