### ISSUE TITLE
Lessons - Lesson "TestRail" page (update) #820/Grammar error "гнучкість" is lower case

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1099]
**Steps to retroduce:**

1. Open https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/testrail/
2. Scroll down to the text "гнучкість та настроюваність під будь-які потреби;"
3. Pay attention to the word "гнучкість".
**Actual result:**
"гнучкість" is lower case
**Expected result:**
"гнучкість" is uppercase
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&mode=design&t=YH9pJOI8ymJyw7XJ-0

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/c8954f63-4f72-47fe-b869-6c9d2dc24833)

**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/28fab067-a91f-4693-b7d5-283da12747b6)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
