### ISSUE TITLE
Link: Hover

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#11]
Нужен ховер для линков:

https://portal.qax-camp.com.ua/courses/recruiter-program/lessons/lesson_5_continue-to-work-with-vacancy/

![image](https://user-images.githubusercontent.com/22824947/183054645-3e086f1c-57b8-4cf1-b59c-10355594c1b8.png)

**Comment by ABatalov** [comment]
Ready for testing: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=799%3A168

**Comment by KaterinaNimenko35** [comment]
verified
