### ISSUE TITLE
Remake design of lesson page 

### ISSUE THREAD

**Issue by ABatalov** [scholokov/qax-portal-2#110]
We need to remake design of lesson page. The main to change images. 
Please first add only some new images to choose right. 

![Снимок](https://user-images.githubusercontent.com/72439798/190859530-528aa390-43ac-440e-a650-916fad45d2d3.PNG)

Here is some examples: 
![Без названия](https://user-images.githubusercontent.com/72439798/190859433-780c6ca1-2211-4ed9-bcaa-8152805d8a15.png)

**Comment by AlonaSarapina** [comment]
ready for testing https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A1035
