### ISSUE TITLE
Lessons - Lesson "TestRail" page (update) #820/Grammar error "розвинена" is lower case

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1100]
**Steps to retroduce:**

1. Open https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/testrail/
2. Scroll down to the text "розвинена система генерування звітності;"
3. Pay attention to the word "розвинена".

**Actual result:**
"розвинена" is lower case
**Expected result:**
"розвинена" is uppercase
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&mode=design&t=YH9pJOI8ymJyw7XJ-0

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/25780acb-c93a-4954-b84f-90eebf007a8e)

**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/b55414a7-e01c-4289-99ac-60aa1949c64a)

**Comment by prokopenkoga1977** [comment]
[#820](https://github.com/scholokov/qax-portal-2/issues/820)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
