### ISSUE TITLE
Lessons - Lesson "TestRail" page (update) #820/Grammar error "організація" is lower case

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1101]
**Steps to retroduce:**

1. Open https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/testrail/
2. Scroll down to the text "організація та відстеження дій усіх співробітників;"
3. Pay attention to the word "організація".

**Actual result:**
"організація" is lower case
**Expected result:**
"організація" is uppercase
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&mode=design&t=YH9pJOI8ymJyw7XJ-0

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/327c0f89-2c5f-4482-98fb-2f894b4c2728)

**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/c71208b4-f02c-4fb4-9c35-bc77e3893061)

**Comment by prokopenkoga1977** [comment]
[#820](https://github.com/scholokov/qax-portal-2/issues/820)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
