### ISSUE TITLE
Lessons - Lesson "TestRail" page (update) #820/Grammar error "ліцензується" is lower case

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1102]
**Steps to retroduce:**

1. Open https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/testrail/
2. Scroll down to the text "ліцензується за кількістю користувачів, що реально користуються ним"
3. Pay attention to the word "ліцензується".

**Actual result:**
"ліцензується" is lower case
**Expected result:**
"ліцензується" is uppercase
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&mode=design&t=YH9pJOI8ymJyw7XJ-0

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/5ec2e4e3-6338-43f1-826d-3149ad84b21e)

**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/c1d235bb-5d28-4d0b-9620-97d1b36dd095)

**Comment by prokopenkoga1977** [comment]
[#820](https://github.com/scholokov/qax-portal-2/issues/820)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
