### ISSUE TITLE
Lesson "Успішна співбесіда – Точка зору тех спеціаліст" / Missed access to the lesson's presentation in archive

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1104]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/cv/lessons/interview-from-tech-side/
2. Scroll down to the archive.
3. Open it.
4. Pay attention to the presentation.

**Actual result:**
There is no access to the lesson's presentation.

**Expected result:**
There is access to the lesson's presentation.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/ac906e3d-b611-4bb3-a5ef-d3655e88978c)

**Comment by GNatala** [comment]
#864

**Comment by scholokov** [comment]
вправлено

**Comment by GNatala** [comment]
перевірено
