### ISSUE TITLE
Lesson "Work search tips" / Lesson "Work search tips" is 3-rd in the list of the "Программа курсу"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1105]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/cv/
2. Scroll down to the section "Программа курсу".
3. Pay attention to the position of the lesson "Work search tips".

**Actual result:**
Lesson "Work search tips" is 3-rd in the list of the "Программа курсу".

**Expected result:**
Lesson "Work search tips" is 2-nd in the list of the "Программа курсу".

**Additional information:**
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%96%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B8-%D0%BF%D0%BE%D1%88%D1%83%D0%BA%D1%83-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D1%96%D0%B9-%D0%BF%D1%96%D0%B4%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B4%D0%BE-%D0%BF%D1%80%D0%BE%D1%85%D0%BE%D0%B4%D0%B6%D0%B5%D0%BD%D0%BD%D1%8F-%D1%81%D0%BF%D1%96%D0%B2%D0%B1%D0%B5%D1%81%D1%96%D0%B4%D0%B8-%D1%81%D1%82%D0%B2%D0%BE%D1%80%D0%B5%D0%BD%D0%BD%D1%8F-%D1%81v

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://github.com/scholokov/qax-portal-2/assets/101987790/e71802ee-61dc-4bee-b4cf-c5890fc75c3e)

**Comment by GNatala** [comment]
#866

**Comment by scholokov** [comment]
виправлено у вимогах

**Comment by GNatala** [comment]
перевірено
