### ISSUE TITLE
Oops - Implement a new design "Oops" page according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1106]
We need to implement a new design "Oops" page according to Figma.
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=7712-1484&mode=design&t=tOOOy6Nk3Qf6CrTM-0
![Oops](https://github.com/scholokov/qax-portal-2/assets/109460500/4c45d285-9dd6-4846-a5b4-47552de036d4)

**Comment by poroskundenys** [comment]
Что это за страница?

**Comment by scholokov** [comment]
була ідея мати 2 різні сторінки:
404 - якщо ресурс не існую
і ця - якщо саме не має доступу до контенту
@poroskundenys

**Comment by poroskundenys** [comment]
@scholokov сейчас при открытии урока идет перенаправление на страницу курса, где можно его купить

**Comment by ButKoff** [comment]
not actual
