### ISSUE TITLE
Create design of Login page on Portal Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#111]
We need to add the "Login" page design to the Portal Figma.
Old design example: https://portal.qax-camp.com.ua/login/
New design on Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2129%3A748
![Login page](https://user-images.githubusercontent.com/109460500/190902795-874a7b6c-009f-4ea0-8fd8-acb84891d543.png)

**Comment by ButKoff** [comment]
Надо создать дизайн страницы на Figma (Portal design). 
Структура страницу отображена по указанной ссылке в теле задачи.

**Comment by BatalovaOlha** [comment]
#202
