### ISSUE TITLE
Lessons - Lesson "TestRail" page (update) #820/Grammar error "відстежувати" is lower case

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1111]
**Steps to retroduce:**

1. Open https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/testrail/
2. Scroll down to the section Description -> To Do -> text "відстежувати та фільтрувати поточні активності;"
3. Pay attention to the word "відстежувати".

**Actual result:**
"відстежувати" is lower case
**Expected result:**
"**ліцензується**" is uppercase
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&mode=design&t=YH9pJOI8ymJyw7XJ-0

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/e118f995-31e7-4f7d-89cf-4af650e61910)

**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/4ce2b9c2-a269-4160-829d-ef52580ddcdc)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
