### ISSUE TITLE
Lessons - Lesson "TestRail" page (update) #820/Grammar error "відстежити" is lower case

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1112]
**Steps to retroduce:**

1. Open https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/testrail/
2. Scroll down to the section Description -> To Do -> text "відстежити та розподілити навантаження між командою тестування;"
3. Pay attention to the word "відстежити".

**Actual result:**
"відстежити" is lower case
**Expected result:**
"відстежити" is uppercase
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements**: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&mode=design&t=YH9pJOI8ymJyw7XJ-0

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/945ff27c-2aaa-4fbd-91ca-b0c2eca5ccc2)

**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/f62893fd-5155-4764-9830-291b5a8d95db)

**Comment by prokopenkoga1977** [comment]
[#820](https://github.com/scholokov/qax-portal-2/issues/820)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
