### ISSUE TITLE
Lessons - Lesson "TestRail" page (update) #820/Grammar error "є" is lower case

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1114]
**Steps to retroduce:**

1. Open https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/testrail/
2. Scroll down to the section Description -> To Do -> text "є найкращим способом для тестера працювати над конкретними завданнями;"
3. Pay attention to the word "є".

**Actual result:**
"є" is lower case
**Expected result:**
"є" is uppercase
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&mode=design&t=YH9pJOI8ymJyw7XJ-0

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/1f23db0b-3d22-4b4e-b784-ecec64c02ecc)

**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/8ebc224c-7b60-485c-9108-6797b6eab655)

**Comment by prokopenkoga1977** [comment]
[#820](https://github.com/scholokov/qax-portal-2/issues/820)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
