### ISSUE TITLE
Lessons - Lesson "TestRail" page (update) #820/Grammar error "відразу" is lower case

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1115]
**Steps to retroduce:**

1. Open https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/testrail/
2. Scroll down to the section Description -> To Do -> text "відразу почати працювати над своїми завданнями."
3. Pay attention to the word "відразу".

**Actual result:**
"відразу" is lower case
**Expected result:**
"відразу" is uppercase
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&mode=design&t=YH9pJOI8ymJyw7XJ-0

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/3c00250c-ec32-45a2-bae2-04b2653d631e)

**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/ad69322f-13c2-4d29-84ce-68392d568f1d)

**Comment by prokopenkoga1977** [comment]
[#820](https://github.com/scholokov/qax-portal-2/issues/820)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
