### ISSUE TITLE
Create design of Register page on Portal Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#112]
We need to add the "Register" page design to the Portal Figma.
Old design example: https://portal.qax-camp.com.ua/register/
New design on Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2178%3A511
![Registr page](https://user-images.githubusercontent.com/109460500/190903295-e43174cb-27a7-4e18-936c-4b5c0c03cf79.png)

**Comment by ButKoff** [comment]
Надо создать дизайн страницы на Figma (Portal design). 
Структура страницу отображена по указанной ссылке в теле задачи.

**Comment by AlonaSarapina** [comment]
ready for testing https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2178%3A511

**Comment by BatalovaOlha** [comment]
verified
