### ISSUE TITLE
Lessons - Check lesson for "Віддалене Debugging пристроїв Android" page (transfer)

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1120]
We need to check lesson for "Віддалене Debugging пристроїв Android" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/lessons/remote-debug-android-devices/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#web--mobile
![Віддалене Debugging пристроїв Android](https://github.com/scholokov/qax-portal-2/assets/109460500/97cee411-660e-4290-b737-fe7428ad3157)

**Comment by ButKoff** [comment]
#664

**Comment by BatalovaOlha** [comment]
verified
