### ISSUE TITLE
Courses - Check course for "Особливості тестування на різних платформах" page (update)

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1121]
We need to check course for "Особливості тестування на різних платформах" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/platform-testing/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BE%D1%81%D0%BE%D0%B1%D0%BB%D0%B8%D0%B2%D0%BE%D1%81%D1%82%D1%96-%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F-%D0%BD%D0%B0-%D1%80%D1%96%D0%B7%D0%BD%D0%B8%D1%85-%D0%BF%D0%BB%D0%B0%D1%82%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%85
![Особливості тестування на різних платформах](https://github.com/scholokov/qax-portal-2/assets/109460500/ca2809f3-4dd1-46a6-a1c0-52af9fe468a5)

**Comment by ButKoff** [comment]
#663

**Comment by BatalovaOlha** [comment]
the lesson is tested
