### ISSUE TITLE
Lessons - Check lesson for "Компільовані та інтерпретовані мови програмування" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1122]
We need to check lesson for "Компільовані та інтерпретовані мови програмування" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/lessons/comp-lang/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#web--mobile
![Компільовані та інтерпретовані мови програмування](https://github.com/scholokov/qax-portal-2/assets/109460500/10c69f94-1c83-4ab1-afc7-326120339d09)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
verified
