### ISSUE TITLE
Lessons - Check lesson for "Основні принципи ООП" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1123]
We need to check lesson for "Основні принципи ООП" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/lessons/oop/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#web--mobile
![Основні принципи ООП](https://github.com/scholokov/qax-portal-2/assets/109460500/4f2f1677-fb27-477d-afb7-75e805f205a0)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
verified
