### ISSUE TITLE
Lessons - "Вступ у Performance Тестування" / Video's preview does not match the requirements in Canva

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1125]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/testing/lessons/perfomance-testing/
2. Pay attention to the Video's preview.

**Actual result:**
 Video's preview does not match the requirements in Canva.

**Expected result:**
Video's preview matches the requirements in Canva.

**Additional information:** 
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F
https://www.canva.com/design/DAFfaq-NrFI/aTHK4cEZYzwKE2R5DFOnXg/edit?analyticsCorrelationId=ba99a0c7-594f-4392-8dfe-ddb4326f5ffe

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/acd6394d-3f08-4bbd-81d9-f9e9d8e2e233)

**Comment by GNatala** [comment]
#1080

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
