### ISSUE TITLE
Lesson "Task/issue flow" / Missed access to the lesson's presentation in archive - Юлія 

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1126]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-task-issue-flow/
2. Scroll down to the archive "Архів – Task/issue flow – Юля".
3. Open it.
4. Pay attention to the presentation.

**Actual result:**
There is no access to the lesson's presentation.

**Expected result:**
There is access to the lesson's presentation.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/27eece27-8ab2-4986-9840-439c11f2a862)

**Comment by GNatala** [comment]
#944

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
