### ISSUE TITLE
Courses - Check the grouping of lessons on the "Тестування – Майстер-класи" - Design "Testing - master classes" size is not 36px

### ISSUE THREAD

**Issue by Artem-16** [scholokov/qax-portal-2#1127]
**Steps to playback:**

1. Open https://www.qax-camp.com.ua/courses/mc-testing/
2. Pay attention to "Тестування – Майстер-класи"

**Actual result:**
Design "Testing - master classes" size is not 36px

**Expected result:**
Design "Testing - master classes" size 48px
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A1056&mode=dev
![вимоги заголовок](https://github.com/scholokov/qax-portal-2/assets/132911639/e060442f-451b-4836-9f68-1def049650b8)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![баг заголовок](https://github.com/scholokov/qax-portal-2/assets/132911639/a794d841-4a3e-4d2b-9216-360b3d7d8acd)

**Comment by Artem-16** [comment]
#858

**Comment by poroskundenys** [comment]
@Artem-16 Панель нужно снизу открывать https://prnt.sc/jf60RE4YAzW5, тогда ширина сайта будет нормальная

**Comment by Artem-16** [comment]
так розмір змінився
