### ISSUE TITLE
Calendar - Implement the design of the "Найближча подія" block according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1128]
We need to implement the design of the "Найближча подія" block according to Figma.
Environment: https://www.qax-camp.com.ua/calendars/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6704-1434&mode=design&t=A9q84hDXeMnKzDyt-0
Desktop design:
![Desktop](https://github.com/scholokov/qax-portal-2/assets/109460500/6a3f20c8-0d92-46ed-977a-bcad5644a763)
Tablet design:
![Tablet](https://github.com/scholokov/qax-portal-2/assets/109460500/b850622b-90ae-4746-8b6c-7d072fac619a)
Mobile design:
![Mobile](https://github.com/scholokov/qax-portal-2/assets/109460500/3f3a6b2b-ed95-4acb-985a-cb45d38cb3a4)

**Comment by poroskundenys** [comment]
@scholokov можешь попросить дизайнера, чтобы это было одним изображением? https://prnt.sc/8dFTKArS3Zim и его можно было скачать

**Comment by scholokov** [comment]
@poroskundenys 
https://www.canva.com/design/DAFriTsfIzU/Gdpvyco4tXDnpCwa08zMXw/edit

**Comment by poroskundenys** [comment]
Готово. Стиля сделаны для таких настроек https://prnt.sc/8h-ZbRY6iYww

**Comment by ButKoff** [comment]
#702

**Comment by DmitriiNasonov** [comment]
Testing completed
