### ISSUE TITLE
Create design of Password Reset page on Portal Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#113]
We need to add the "Password Reset" page design to the Portal Figma.
https://portal.qax-camp.com.ua/password-reset/
![Password Reset page](https://user-images.githubusercontent.com/109460500/190903503-3049ebf6-a6b5-4c0f-b86d-ad7a73c51424.png)

**Comment by ButKoff** [comment]
Надо создать дизайн страницы на Figma (Portal design). 
Структура страницу отображена по указанной ссылке в теле задачи.

**Comment by AlonaSarapina** [comment]
Ready for testing https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2120%3A431
