### ISSUE TITLE
Courses - Check the grouping of lessons on the "Тестування – Майстер-класи" - Design block  width: 839px height: 183px

### ISSUE THREAD

**Issue by Artem-16** [scholokov/qax-portal-2#1131]
**Steps to playback:**

1. Open https://www.qax-camp.com.ua/courses/mc-testing/
2. Pay attention to block

**Actual result:**
Design block width: 839px height: 183px

**Expected result:**
Design block  width: 1200px height: 198px
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A6926&mode=dev
![вимоги блок](https://github.com/scholokov/qax-portal-2/assets/132911639/6c2c1c7a-2936-422b-9685-aacb7fa54a9e)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![Баг Портал](https://github.com/scholokov/qax-portal-2/assets/132911639/b16b7296-e44e-49af-8dc7-b84bf532cb45)
![Баг Ретро](https://github.com/scholokov/qax-portal-2/assets/132911639/f909163e-e519-4b24-af52-96fc7875eaac)
![Баг Чат бот](https://github.com/scholokov/qax-portal-2/assets/132911639/14027ff9-5d1c-4355-b7c0-b49607461789)
![Баг як тестувати Дизайн](https://github.com/scholokov/qax-portal-2/assets/132911639/b6345103-5229-4688-90d7-6cb03ba89a61)
![Баг як тестувати коли нема](https://github.com/scholokov/qax-portal-2/assets/132911639/bebae976-1cb4-4741-8aa1-70d1d7d65bc1)
![Баг як тестувати приклад](https://github.com/scholokov/qax-portal-2/assets/132911639/96e53f0d-13ce-4c44-8ed0-431880e50754)
![Баг як тестувати](https://github.com/scholokov/qax-portal-2/assets/132911639/d743959a-eca2-4e00-928d-6cf780f0be9d)
![Баг за вимогами тестраіл](https://github.com/scholokov/qax-portal-2/assets/132911639/4bf90033-edc9-4eff-a7bf-6efa75155898)
![Баг кік оф](https://github.com/scholokov/qax-portal-2/assets/132911639/76670cc3-004d-4a20-96ff-f52e92866a4e)
![Баг Міро](https://github.com/scholokov/qax-portal-2/assets/132911639/2accae6e-36db-44e6-aa70-cb7042a81826)

**Comment by Artem-16** [comment]
#858

**Comment by DmytroMarkulych** [comment]
в Summary вказуйте фактично що є. Так само як і в Актуальному результаті.

**Comment by DmytroMarkulych** [comment]
спробуйте розмістити devtools по низу екрану і ще раз перевірит

**Comment by Artem-16** [comment]
Розмір відповідає вимогам якщо devtools в низу
я закриваю цей баг
