### ISSUE TITLE
Courses - Check the grouping of lessons on the "Тестування – Майстер-класи" - Design block "Як створювати тестову документацію за вимогами у TestRail?"  width: 839px height: 201px

### ISSUE THREAD

**Issue by Artem-16** [scholokov/qax-portal-2#1132]
**Steps to playback:**

1. Open https://www.qax-camp.com.ua/courses/mc-testing/
2. Pay attention to "Як створювати тестову документацію за вимогами у TestRail?"

**Actual result:**
Design block "Як створювати тестову документацію за вимогами у TestRail?"  width: 839px height: 201px

**Expected result:**
Design block "Як створювати тестову документацію за вимогами у TestRail?"  width: 1200px height: 198px
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A6926&mode=dev
![вимоги блок](https://github.com/scholokov/qax-portal-2/assets/132911639/583d297c-16b8-40ff-aa89-04703f8fcd8b)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![Баг за вимогами тестраіл](https://github.com/scholokov/qax-portal-2/assets/132911639/c09b4831-a25e-41ea-81d1-c1b30c06434b)

**Comment by Artem-16** [comment]
#858

**Comment by DmytroMarkulych** [comment]
в Summary вказуйте фактично що є. Так само як і в Актуальному результаті.

**Comment by DmytroMarkulych** [comment]
спробуйте розмістити devtools по низу екрану і ще раз перевірит

**Comment by Artem-16** [comment]
Розмір відповідає вимогам якщо devtools в низу
Я закриваю цей баг
