### ISSUE TITLE
Course - "Базовий курс QA" /  Preview of the lesson "Тестувальник. Хто це?" does not match the requirements in Canva

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1136]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q6-basic/
2. Pay attention to the preview of the lesson "Тестувальник. Хто це?" in "Програма курсу".

**Actual result:**
 Preview of the lesson "Тестувальник. Хто це?" does not match the requirements in Canva.

**Expected result:**
Preview of the lesson "Тестувальник. Хто це?" matches the requirements in Canva.

**Additional information:** 
https://www.canva.com/design/DAFewJdOmbo/x7TMMfd1LHtNoL70XYiZrg/edit?utm_content=DAFewJdOmbo&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/3c2dd681-4ed0-4507-9810-94aaafd5d761)

**Comment by GNatala** [comment]
#1080

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/qax-portal-2/assets/88647733/109852ba-2ffa-40e6-ba77-480d0024d83d)

**Comment by GNatala** [comment]
Дякую, додала

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
