### ISSUE TITLE
Course - "Базовий курс QA" / Preview of the lesson "Види, методи та рівні тестування" does not match the requirements in Canva

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1137]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q6-basic/
2. Pay attention to the preview of the lesson "Види, методи та рівні тестування".

**Actual result:**
 Preview of the lesson "Види, методи та рівні тестування" does not match the requirements in Canva.

**Expected result:**
Preview of the lesson "Види, методи та рівні тестування" matches the requirements in Canva.

**Additional information:** 
https://www.canva.com/design/DAFewJdOmbo/x7TMMfd1LHtNoL70XYiZrg/edit?utm_content=DAFewJdOmbo&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://github.com/scholokov/qax-portal-2/assets/101987790/f93734b8-40b7-4d3a-aea1-3e113b8bdbe6)

**Comment by GNatala** [comment]
#1080

**Comment by scholokov** [comment]
виправлено у вимогах

**Comment by GNatala** [comment]
перевірено
