### ISSUE TITLE
wiki/Requirements / Link "Canva" does not lead to the appropriate page

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1138]
**Steps to reproduce:**

1. Open page: https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81
2. Pay attention to point 2 - course "Базовий курс QA" by Rudchenko Yuliya.
3. Press on the link "Canva"

**Actual Result:**  
Link "Canva" does not lead to the appropriate page.

**Expected Result:**  
Link "Canva" leads to the appropriate page.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/8a2aa674-4889-4e3e-907d-83cdb59dca4e)

**Comment by GNatala** [comment]
#1080

**Comment by scholokov** [comment]
видалено з вимог застарілий курс
