### ISSUE TITLE
Create design of Privacy Policy page on Portal Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#114]
We need to add the "Privacy Policy" page design to the Portal Figma.
Implementation: https://portal.qax-camp.com.ua/privacy_policy/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2090%3A1244
![Privacy Policy](https://user-images.githubusercontent.com/109460500/195607745-99921904-5174-4934-98ad-8f971c215e42.png)

**Comment by ButKoff** [comment]
Надо создать дизайн страницы на Figma (Portal design) аналогично, как реализовано по указанной ссылке в теле задачи.

**Comment by BatalovaOlha** [comment]
#204

**Comment by BatalovaOlha** [comment]
#205

**Comment by BatalovaOlha** [comment]
#206

**Comment by BatalovaOlha** [comment]
#207

**Comment by BatalovaOlha** [comment]
#209

**Comment by BatalovaOlha** [comment]
#210
