### ISSUE TITLE
Course - "Процеси" / List of lessons in "Програма курсу" does not match wiki/1.7.1.-Урок "Процеси"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1144]
**Steps to reproduce:**
1. Open https://www.qax-camp.com.ua/courses/processes/
2. Pay attention to the list of lessons in "Програма курсу".

**Actual result:**
List of lessons in "Програма курсу" does not match wiki/1.7.1.-Урок "Процеси".
**Expected result:**
List of lessons in "Програма курсу" match wiki/1.7.1.-Урок "Процеси".

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

Additional information:
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D0%B8

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/e386f035-a232-4750-840b-d7901443c571)

**Comment by GNatala** [comment]
#1080

**Comment by scholokov** [comment]
виправлено у вимогах

**Comment by GNatala** [comment]
перевірено
