### ISSUE TITLE
Lesson "HTML&CSS Basics"/The Logo of the course "Web & Mobile" does not match the design of the logo in Canva

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1145]
Steps to Reproduce:
1. Open page https://www.qax-camp.com.ua/courses/web-mobile/lessons/basic-html-for-qa/
2. Pay attention to the Logo of the lesson "HTML&CSS Basics" of the course "Web & Mobile"

Actual Result: The course Logo does not match the design of the logo in Canva
Expected Result: The course Logo does match the design of the logo in Canva

Additional information: https://www.canva.com/design/DAFhwFscemU/71obqTC7YqTrPPH7iaacsg/edit

Environment:
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/66da204c-ada8-48a9-9cc2-a561d3bf238f)

**Comment by ODrobik** [comment]
#949

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
