### ISSUE TITLE
Lessons - "Zephyr Scale (TM4J)" / Missed Video's preview in the accordion "Архівне відео"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1146]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/zephyr-scale-tm4j-basics/
2. Scroll down to the accordion "Архівне відео" - open it.
3. Pay attention to the Video's preview.

**Actual result:**
 Missed Video's preview in the accordion "Архівне відео".

**Expected result:**
 The video's preview in the accordion "Архівне відео" is present.

**Additional information:** 
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F
https://www.canva.com/design/DAFfaq-NrFI/aTHK4cEZYzwKE2R5DFOnXg/edit?analyticsCorrelationId=ba99a0c7-594f-4392-8dfe-ddb4326f5ffe

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/7e8a2f2d-b76e-46a7-8f4f-9827aba4c743)

**Comment by GNatala** [comment]
#1080

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
verified
