### ISSUE TITLE
Grammatical error in the word "Непротирливість" - page "Вимоги: навіщо їх тестувати?"- "Властивості якісних вимог" - "Архів – Requirements: навіщо їх тестувати?"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#1148]
**STR**
1. Open https://www.qax-camp.com.ua/courses/testing/lessons/q6-requirements/
2. You should be login

**ACTUAL RESULT**
In the paragraph "Властивості якісних вимог" is a grammatical error in the word "Непротирливість" 

**EXPECTED RESULT**
In the paragraph "Властивості якісних вимог" should be "Несуперечність" – Вимоги не повинні суперечити самі собі.

![CuNk6hxqhW](https://github.com/scholokov/qax-portal-2/assets/109384052/e3e6c520-1543-4ec0-bef1-01515ced145f)

**Comment by BatalovaOlha** [comment]
#914

**Comment by scholokov** [comment]
виправлено

**Comment by BatalovaOlha** [comment]
verified
