### ISSUE TITLE
Create variants courses design with buttons 

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#115]
We need to do design variants courses design with one, two, three and four buttons.
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=1412%3A425
![Courses design page](https://user-images.githubusercontent.com/109460500/190904153-a13d9c18-955c-4823-903a-6c53c34a4d33.png)

**Comment by scholokov** [comment]
not actual
