### ISSUE TITLE
The presentation in the section "Архів – Defect – Юля" is not displayed - page "Defect" 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#1150]
**STR**

1. Open https://www.qax-camp.com.ua/courses/testing/lessons/q6-defect/
2. You must be logged in for the correct opening page.

**ACTUAL RESULT**
In the block "Архів – Defect – Юля" the presentation is NOT displayed and shows the error message "Файл удален."

**EXPECTED RESULT**
In the block "Архів – Defect – Юля" the presentation is displayed

![y32u238LnI](https://github.com/scholokov/qax-portal-2/assets/109384052/59224202-56a7-4490-a92d-3d4059900ff2)

**Comment by BatalovaOlha** [comment]
#917

**Comment by scholokov** [comment]
виправлено

**Comment by BatalovaOlha** [comment]
verified

**Comment by BatalovaOlha** [comment]
again the same

**Comment by BatalovaOlha** [comment]
![Image](https://github.com/scholokov/qax-portal-2/assets/109384052/f25f2dc8-6325-46fb-8d14-f24f001f66d4)

**Comment by scholokov** [comment]
виправлено

**Comment by BatalovaOlha** [comment]
verified
