### ISSUE TITLE
The presentation in the section "Архів – Вимоги: навіщо їх тестувати? – Юля" is not displayed - page "Вимоги: навіщо їх тестувати?"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#1151]
**STR**

1. Open https://www.qax-camp.com.ua/courses/testing/lessons/q6-requirements/
2. You must be logged in for the correct opening page.

**ACTUAL RESULT**
In the block "Архів – Вимоги: навіщо їх тестувати? – Юля" the presentation is NOT displayed and shows the error message "Файл удален."

**EXPECTED RESULT**
In the block "Архів – Вимоги: навіщо їх тестувати? – Юля" the presentation is displayed
![IjaivUvHr8](https://github.com/scholokov/qax-portal-2/assets/109384052/f604f2b5-8110-4cc1-9b88-bf634f029a06)

**Comment by BatalovaOlha** [comment]
#914

**Comment by scholokov** [comment]
виправлено

**Comment by BatalovaOlha** [comment]
verified
