### ISSUE TITLE
Lessons - "Вступ у Performance Тестування" / Sentence "Проведение необходимых тестов' is written in russian in the accordion "Альтернативний погляд"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1152]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/testing/lessons/perfomance-testing/
2. Scroll down to the accordion "Альтернативний погляд" - open it.
3. Pay attention to the sentence "Проведение необходимых тестов' in the paragraph "Процес навантажувального тестування".

**Actual result:**
 Sentence "Проведение необходимых тестов' is written in russian.

**Expected result:**
 Sentence "Проведение необходимых тестов' is written in Ukranian.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/7dd63def-8754-4624-8c2e-8a601b9f0eea)

**Comment by GNatala** [comment]
#876

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
verified
