### ISSUE TITLE
Lessons - "Вступ у Performance Тестування" / Spelling mistake оf the word "проект" and its variants in the accordion "Альтернативний погляд"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1153]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/testing/lessons/perfomance-testing/
2. Scroll down to the accordion "Альтернативний погляд" - open it.
3. Pay attention to the spelling of the words "проект" in the section.

**Actual result:**
 The word "проект" and its variants are written with the letter "е".

**Expected result:**
 The word "проект" and its variants are written with the letter "є".

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/ee5a75eb-a816-4671-8352-2f9944d927aa)

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
verified
