### ISSUE TITLE
Lessons - "Вступ у Performance Тестування" / Video's preview does not match the requirements in Canva in the accordion "Альтернативний погляд

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1155]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/testing/lessons/perfomance-testing/
2. Scroll down to the accordion "Альтернативний погляд" - open it.
3. Pay attention to the Video's preview.

**Actual result:**
 Video's preview does not match the requirements in Canva.

**Expected result:**
Video's preview matches the requirements in Canva.

**Additional information:** 
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F
https://www.canva.com/design/DAFfaq-NrFI/aTHK4cEZYzwKE2R5DFOnXg/edit?analyticsCorrelationId=ba99a0c7-594f-4392-8dfe-ddb4326f5ffe

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/ec58e562-79c3-452c-b9b7-2fdfd293f714)

**Comment by GNatala** [comment]
#876

**Comment by scholokov** [comment]
оновив порядок превью у канва
буд ласка повторіть тестування

**Comment by GNatala** [comment]
An issue is reproduced.

**Actual result:**
 Video's preview does not match the requirements in Canva. **"Логотип уроку" is not the same as in Canva.**

**Expected result:**
Video's preview matches the requirements in Canva. **"Логотип уроку" is the same as in Canva.**

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/6895f278-3256-4fa1-b1d6-52631eb7823a)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
