### ISSUE TITLE
The presentation in the section "Архів – Тестова документація – Юля" is not displayed - page "Тестова документація: чек-лісти та тест-кейси"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#1156]
**STR**
1. Open https://www.qax-camp.com.ua/courses/testing/lessons/q6-test-documentation/;
2. You must be logged in for the correct opening page.

**ACTUAL RESULT**
In the block "Архів – Тестова документація – Юля" the presentation is NOT displayed and shows the error message "Файл удален."

**EXPECTED RESULT**
In the block "Архів – Тестова документація – Юля" the presentation is displayed

![chrome_XB1oeZdpRj](https://github.com/scholokov/qax-portal-2/assets/109384052/0de1b1cb-d4c6-4b0b-94bf-243edfab093b)

**Comment by BatalovaOlha** [comment]
#918

**Comment by scholokov** [comment]
виправлено

**Comment by BatalovaOlha** [comment]
verified
