### ISSUE TITLE
Lesson "Структура команди, як чинник її ефективності"/In the section About Author the text "Scholokov Denis" is written in English

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1157]
Steps to Reproduce:
1.Open page https://www.qax-camp.com.ua/courses/processes/lessons/team-structure/
2. Pay attention to the text "Scholokov Denis in the section About Author of the page

Actual Result: the text "Scholokov Denis" is written in English
Expected Result: the text "Денис Щолоков" is written in Ukrainian

Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D0%B8

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/76911062-c5d9-47ae-80fa-54d277b2b736)

**Comment by ODrobik** [comment]
#892

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
