### ISSUE TITLE
Account - Implement the design of the Account page according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1158]
We need to Implement the design of the Account page according to Figma.
Product environment: https://www.qax-camp.com.ua/user/butkoff/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6570-1350&mode=design&t=nE4MxR8JXciC5mWp-0
![Account](https://github.com/scholokov/qax-portal-2/assets/109460500/08d0c3ac-c960-4b79-b59d-1849e33b4465)

**Comment by poroskundenys** [comment]
Готово.
Это дизайн шаблона редактирования профиля. Открывается он тут на странице своего профиля https://prnt.sc/iGoSfTrDWhxj

**Comment by ODrobik** [comment]
verified
