### ISSUE TITLE
Lessons - Check lesson for "Critical Rendering Path" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1159]
We need to check lesson for "Critical Rendering Path" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/lessons/critical-rendering-path/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#web--mobile
![Critical Rendering Path](https://github.com/scholokov/qax-portal-2/assets/109460500/675096f6-5a63-42d7-9bfa-6faaa477296c)

**Comment by ButKoff** [comment]
#664

**Comment by DmitriiNasonov** [comment]
Testing completed
