### ISSUE TITLE
Recruitment - the title of the lesson «HR и Рекрутмент функция» in Russian 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#116]
Steps To Reproduce:
1. Open the pagehttps://portal.qax-camp.com.ua/courses/recruiter-program/
2. Pay attention to the title of the second lesson 

Actual result: HR и Рекрутмент функция
Expected result: HR та Рекрутмент функція 
<img width="1440" alt="Снимок экрана 2022-09-19 в 1 25 29 PM" src="https://user-images.githubusercontent.com/110661667/190998024-bc4545dd-606f-43d3-b816-1b408e9afcea.png">

**Comment by scholokov** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
