### ISSUE TITLE
Lessons - Сheck lesson "Путь критической визуализации" page that was deleted

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1160]
We need to check the lesson "Путь критической визуализации" page, that was deleted.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/lessons/%d0%bf%d1%83%d1%82%d1%8c-%d0%ba%d1%80%d0%b8%d1%82%d0%b8%d1%87%d0%b5%d1%81%d0%ba%d0%be%d0%b9-%d0%b2%d0%b8%d0%b7%d1%83%d0%b0%d0%bb%d0%b8%d0%b7%d0%b0%d1%86%d0%b8%d0%b8/
![Путь критической визуализации](https://github.com/scholokov/qax-portal-2/assets/109460500/d0408289-ba3e-4da4-bfce-91d0e52443e5)

**Comment by BatalovaOlha** [comment]
verified
