### ISSUE TITLE
Lessons - Check lesson for "Оцінка компетенції команди, PDP, плани розвитку" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1162]
We need to check lesson for "Оцінка компетенції команди, PDP, плани розвитку" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/processes/lessons/pdp-360/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D0%B8
![Оцінка компетенції команди, PDP, плани розвитку](https://github.com/scholokov/qax-portal-2/assets/109460500/fda5cfe3-053a-4032-ab8b-3a2b1d804050)

**Comment by ButKoff** [comment]
#664

**Comment by BatalovaOlha** [comment]
verified
