### ISSUE TITLE
Lesson "Структура команди, як чинник її ефективності"/The Size of the Preview of the lesson is 980x551px 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1163]
Steps to Reproduce:
1.Open page https://www.qax-camp.com.ua/courses/processes/lessons/team-structure/
2. Pay attention to the Size of the Preview

Actual Result:The Size of the Preview of the lesson is 980x551px 
Expected Result: The Size of the Preview of the lesson is 980x450px 

Requirements: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=390-12775&mode=design&t=EeGRFaGNF0s70cXM-0

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/5729393d-4606-4a70-bbd2-bc452b090efc)

**Comment by ODrobik** [comment]
#892

**Comment by scholokov** [comment]
issue in design
