### ISSUE TITLE
GitHub Wiki - 1.7.1. Урок - List of "Тестування" cource lessons - Lesson "Test Management System (TMS)" is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1165]
**Steps of reproducing**
1. Open https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F
2. Scroll to "Тестування" cource
3. Pay attention to the list of lessons

**Actual Result**
Lesson "Test Management System (TMS)" is missing

**Expected Result**
Lesson "Test Management System (TMS)" is present

**Additional information**
https://www.qax-camp.com.ua/courses/testing/lessons/tms/

**Enviroments**
Windows 10, Chrome 115.0.5790.110 (64 bit)
![1 7 1  Урок · scholokov_qax-portal-2 Wiki - Google Chrome 02 08 2023 16_33_46](https://github.com/scholokov/qax-portal-2/assets/95171672/c6932abb-8c61-45cf-87e2-cc7b74993543)

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
