### ISSUE TITLE
"Test Management System (TMS)" lesson - Lesson Preview - Course logo doesn't meet Canva requirements

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1166]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/courses/testing/lessons/tms/
2. Pay attention to Course logo

**Actual Result**
Course logo doesn't meet Canva requirements

**Expected Result**
Course logo meets Canva requirements

**Additional information**
https://www.canva.com/design/DAFfaq-NrFI/aTHK4cEZYzwKE2R5DFOnXg/edit

**Enviroments**
Windows 10, Chrome 115.0.5790.110 (64 bit)
Android 8.1.0, Chrome 115.0.5790.138
![Test Management System (TMS) – QAX Camp - Google Chrome 02 08 2023 16_59_21](https://github.com/scholokov/qax-portal-2/assets/95171672/b6a7b3d2-cb00-4161-99d3-16bbf8040244)
![Test Management System (TMS) – QAX Camp - Google Chrome 02 08 2023 16_59_21](https://github.com/scholokov/qax-portal-2/assets/95171672/ee3457fe-cd55-4402-a975-ca808e76eaca)
![photo_2023-08-02_16-59-47](https://github.com/scholokov/qax-portal-2/assets/95171672/48b17cbc-f48a-4608-b49b-6f09bb3e6c12)

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
