### ISSUE TITLE
"Test Management System (TMS)" lesson - Lesson Preview - "DS" Logo is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1167]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/courses/testing/lessons/tms/
2. Pay attention to lesson preview

**Actual Result**
"DS" Logo is missing

**Expected Result**
"DS" Logo is present

**Additional information**
https://www.canva.com/design/DAFfaq-NrFI/aTHK4cEZYzwKE2R5DFOnXg/edit

**Enviroments**
Windows 10, Chrome 115.0.5790.110 (64 bit)
Android 8.1.0, Chrome 115.0.5790.138
![Test Management System (TMS) – QAX Camp - Google Chrome 02 08 2023 17_03_58](https://github.com/scholokov/qax-portal-2/assets/95171672/33f3e371-fa84-411a-97f7-5ad91d1d1eb3)
![photo_2023-08-02_17-05-29](https://github.com/scholokov/qax-portal-2/assets/95171672/3a41d10b-40d9-47e5-83f0-c916501e7a3b)

**Comment by DmitriiNasonov** [comment]
#889

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
