### ISSUE TITLE
Recruitment Course Content - title of the third lesson is «Разновидности бизнесов» in Russian 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#117]
Steps To Reproduce:
1. Open the pagehttps://portal.qax-camp.com.ua/courses/recruiter-program/
2. Pay attention to the title of the third lesson

Actual result: Разновидности бизнесов и компаний на ИТ рынке: продуктовая/аутсорс/аутстаф. Чем отличается роль рекрутера в каждой из компаний?
Expected result: Різновиди бізнесів та компаній на ІТ ринку: продуктова/аутсорс/аутстаф. Чим відрізняється роль рекрутера в кожній компанії?
<img width="1440" alt="Снимок экрана 2022-09-19 в 1 39 28 PM" src="https://user-images.githubusercontent.com/110661667/191000261-ddbb761a-530c-438a-8b5f-b289686db7da.png">

**Comment by DmytroMarkulych** [comment]
@LesiaBezukh очевидні позитивні результати в правельності оформлення баг репортів) Молодець, так тримати)

**Comment by scholokov** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
