### ISSUE TITLE
Lessons - Check lesson for "Класи еквівалентності, Граничні значення" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1179]
We need to check lesson for "Класи еквівалентності, Граничні значення" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/testing/lessons/td-ke-gz/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F
![Класи еквівалентності, Граничні значення](https://github.com/scholokov/qax-portal-2/assets/109460500/736197c5-a337-4ace-b667-c15520112e79)
![Класи еквівалентності, Граничні значення_](https://github.com/scholokov/qax-portal-2/assets/109460500/f2c8e56a-dc84-4cac-924c-03ca8ef5804f)

**Comment by ButKoff** [comment]
#664

**Comment by DmitriiNasonov** [comment]
Testing completed
