### ISSUE TITLE
Recruitment Course Content - title of the fourth lesson is «Начало работы с вакансией» in Russian 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#118]
Steps To Reproduce:
1. Open the pagehttps://portal.qax-camp.com.ua/courses/recruiter-program/
2. Pay attention to the title of the fourth lesson

Actual result: Начало работы с вакансией. Понимание роли. Что такое заявка на вакансию? Что такое intake meeting?
Expected result: Початок роботи із вакансією. Розуміння ролі. Що таке заявка на роботу? Що таке intake meeting?
<img width="1440" alt="Снимок экрана 2022-09-19 в 1 48 19 PM" src="https://user-images.githubusercontent.com/110661667/191001602-0a93382f-43bd-42d1-9add-f5df7e6ef533.png">

**Comment by scholokov** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
