### ISSUE TITLE
Courses - Check course for "Тестування" page (decomposition into topics)

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1180]
We need to check lesson for "Тестування" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/testing/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F
![1](https://github.com/scholokov/qax-portal-2/assets/109460500/cffeef76-f1c8-47e9-8088-ce57ff26769d)
![2](https://github.com/scholokov/qax-portal-2/assets/109460500/c5aaf5a5-4719-4727-9df5-931c1ccfe982)
![3](https://github.com/scholokov/qax-portal-2/assets/109460500/5248f67d-0627-485e-92ec-e437e5b747d9)

**Comment by ButKoff** [comment]
#663

**Comment by DmitriiNasonov** [comment]
The ability to write bug reports is blocked by the lack of a course in the current requirements.
I'm starting to transfer requirements from Github to Confluence

**Comment by DmitriiNasonov** [comment]
Requirements transfer is complete.
I'm starting testing.
Link to course requirements in Confluence: https://qaxm.atlassian.net/wiki/spaces/PM/pages/30965858

**Comment by DmitriiNasonov** [comment]
Testing completed
