### ISSUE TITLE
Lessons - Check lesson for "Pairwise" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1181]
We need to check lesson for "Pairwise" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/testing/lessons/td-pairwise/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F
![Pairwise](https://github.com/scholokov/qax-portal-2/assets/109460500/31d23e7f-32fc-4920-a7d4-49f191270347)
![Pairwise_](https://github.com/scholokov/qax-portal-2/assets/109460500/4780c67c-84d0-4ad1-8be4-817d6ff3b958)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
verified
