### ISSUE TITLE
wiki/Requirement - Table "Процеси" - In the column "Автор" the text "Scholokov Denis" is written in English

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1185]
Steps to Reproduce:
1.Open page https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D0%B8
2. Pay attention to the text "Scholokov Denis In the column "Автор" of the table

Actual Result: the text "Scholokov Denis" is written in English
Expected Result: the text "Денис Щолоков" is written in Ukrainian

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/0ad2b39d-75d7-4882-b7d8-bbe1c8fe2b5b)

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
