### ISSUE TITLE
Lessons - "Вступ у Performance Тестування" / The text "Scholokov Denis" is written in English

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1187]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/testing/lessons/perfomance-testing/
2. Scroll down to the text "Автор: Scholokov Denis".
3. Pay attention to the language of the name and surname.

**Actual result:**
 Text "Scholokov Denis" is written in English.

**Expected result:**
Text "Scholokov Denis" is written in Ukrainian.

**Requirements:** 
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D0%B8

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/9574529a-24a8-4321-8f47-81f72795231f)

**Comment by GNatala** [comment]
#876

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
