### ISSUE TITLE
Course/Lesson/Quizzes pages - Context menu doesn't open

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1189]
**Steps of reproducing**
1.  Open Course, Lesson or Quizzes page
2. Right click on any page element

**Actual Result**
Context menu doesn't open

**Expected Result**
Context menu opened

**Additional information**
During page refresh there is 1-2 seconds during which the context menu can be opened

**Enviroments**
Windows 10, Chrome 115.0.5790.110 (64 bit), Firefox 116.0.2 (64 bit)

https://github.com/scholokov/qax-portal-2/assets/95171672/36e31426-09bb-438d-a88c-bfd9e8e920e6

https://github.com/scholokov/qax-portal-2/assets/95171672/8ed9d8fe-ae35-484f-9202-9841952bd447

**Comment by scholokov** [comment]
це нормальна поведінка

**Comment by DmitriiNasonov** [comment]
canceled
