### ISSUE TITLE
Recruitment Course Content - title of the fifth lesson is «Технический ликбез» in Russian 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#119]
Steps To Reproduce:
1. Open the pagehttps://portal.qax-camp.com.ua/courses/recruiter-program/
2. Pay attention to the title of the fifth lesson

Actual result: Технический ликбез для Рекрутеров
Expected result:Технічний лікнеп для рекрутерів
<img width="1440" alt="Снимок экрана 2022-09-19 в 1 49 54 PM" src="https://user-images.githubusercontent.com/110661667/191002033-e4826e00-7274-4ba9-88b5-53a0d84d0e2e.png">

**Comment by scholokov** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
