### ISSUE TITLE
wiki/ Requirements - The page "1.7.1. Урок" the word "Превью" is in russian language

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1190]
Steps to Reproduce:
1. Open: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D0%B8
2. Pay attention to the word "превью" of page "1.7.1. Урок"

Actual Result: the word "превью" is in russian language
Expected Result: the word "прев'ю" is in ukrainian language

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/6e914f27-8caf-4123-a17c-d5002c208b6c)

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
