### ISSUE TITLE
wiki/ Requirements - The page "1.2.1. Курс" the word "превью" is in russian language 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1191]
Steps to Reproduce:

1. Open: https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81
2. Pay attention to the word "превью" of page "1.2.1. Курс

Actual Result: the word "превью" is in russian language
Expected Result: the word "прев'ю" is in ukrainian language

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/300057a2-943c-4575-87b7-1d18f31c9149)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/qax-portal-2/assets/88647733/5973f293-6282-4f6d-b924-19ce8052db78)

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
