### ISSUE TITLE
wiki/ Requirements - The page "1.7.1. Урок" the points "1.7" and "1.9" are repeated

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1192]
Steps to Reproduce:
1. Open: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA
2. Pay attention to thethe points "1.7" and "1.9" of page "1.7.1. Урок"

Actual Result: the points "1.7" and "1.9" **are** repeated
Expected Result: the points "1.7" and "1.9" **are not** repeated

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/c5dc45c9-188b-458a-8b30-4d6c5e1c7259)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/qax-portal-2/assets/88647733/3a1d8a1d-3713-4c2c-941f-cb97ca975f2b)

**Comment by scholokov** [comment]
виправлено
