### ISSUE TITLE
Lesson-Topic: Выполнение урока

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#12]
подумать над кнопками управления урока
взможные варианты:

https://portal.qax-camp.com.ua/courses/recruiter-program/lessons/lesson_4/

![image](https://user-images.githubusercontent.com/22824947/183055216-da8ae5cb-1742-4386-9098-124e24696a37.png)
![image](https://user-images.githubusercontent.com/22824947/183055295-e91a920a-6d9f-45dc-9cac-be31f37636b5.png)
![image](https://user-images.githubusercontent.com/22824947/183055371-11245ffa-1c10-46b2-ab55-9758bd7cc1fa.png)
![image](https://user-images.githubusercontent.com/22824947/183055452-45c54e48-64b8-49df-94ff-882a1caf20d6.png)

**Comment by AlonaSarapina** [comment]
ready for testing https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A12775

**Comment by AlonaSarapina** [comment]
![image](https://user-images.githubusercontent.com/99277105/193267530-76109e2b-f79f-4615-bec9-99272c966a90.png)

**Comment by AlonaSarapina** [comment]
![image](https://user-images.githubusercontent.com/99277105/193267618-59ec9337-1ade-48f3-a662-58e032803802.png)

**Comment by KaterinaNimenko35** [comment]
Verified
