### ISSUE TITLE
Recruitment Course Content - title of the sixth lesson is «Продолжение работы над вакансией» in Russian 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#120]
Steps To Reproduce:
1. Open the pagehttps://portal.qax-camp.com.ua/courses/recruiter-program/
2. Pay attention to the title of the **Sixth** lesson

Actual result: Продолжение работы над вакансией (составление описания вакансии)
Expected result: Продовження роботи над вакансією (складання опису вакансії)
<img width="1440" alt="Снимок экрана 2022-09-19 в 1 56 31 PM" src="https://user-images.githubusercontent.com/110661667/191002701-e2657502-4d03-47c8-92b6-a5750d2bfe44.png">

**Comment by scholokov** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
