### ISSUE TITLE
Course - "Базовий курс QA" / Missed the Lesson's Logo in Video's preview in the lesson: "Тестувальник. Хто це?"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1201]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q6-basic/lessons/who-is-qa/
2. Scroll down to the Video's preview.
3. Pay attention to the absence of the Lesson's Logo.

**Actual result:**
 Missed the Lesson's Logo in Video's preview.

**Expected result:**
The Lesson's Logo is present in Video's preview.

**Additional information:** 
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F
https://www.canva.com/design/DAFfaq-NrFI/aTHK4cEZYzwKE2R5DFOnXg/edit?analyticsCorrelationId=ba99a0c7-594f-4392-8dfe-ddb4326f5ffe

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/633c98ba-d4b7-4b1a-a594-6e9ae597610b)

**Comment by GNatala** [comment]
#1080

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
