### ISSUE TITLE
 Recruitment Course Content - title of the seventh lesson is «Сорсинг» in Russian 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#121]
Steps To Reproduce:
1. Open the pagehttps://portal.qax-camp.com.ua/courses/recruiter-program/
2. Pay attention to the title of the seventh lesson 

Actual result: Сорсинг. Инструменты сорсинга
Expected result: Сорсинг. Інструменти сорсингу
<img width="1440" alt="Снимок экрана 2022-09-19 в 2 01 13 PM" src="https://user-images.githubusercontent.com/110661667/191003449-f1da7e2d-c848-43a1-a54a-1966abfb9e59.png">

**Comment by DmytroMarkulych** [comment]
@LesiaBezukh "Expected result: **Сорсінг**. Інструменти **сорсингу**" виходить 2 різних слова, котре правильне?)

**Comment by LesiaBezukh** [comment]
<img width="1440" alt="Снимок экрана 2022-09-20 в 10 23 30 AM" src="https://user-images.githubusercontent.com/110661667/191193457-1c591be4-4129-4a07-9c43-3d10cc921746.png">

**Comment by DmytroMarkulych** [comment]
@LesiaBezukh в одному випадку у Вас через "і" в іншому через "и" . Expected result: Сорс**і**нг. Інструменти сорс**и**нгу

**Comment by LesiaBezukh** [comment]
Verified
