### ISSUE TITLE
Achievement /  The system prohibits passing the 2-nd test after successfully passing the 1-st

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1210]
**Steps to reproduce:**

1. Open  https://www.qax-camp.com.ua/ach-travel/ as an authorized user.
2. First test is completed.
3. Click on "Занести результат".

**Actual result:** 
Message: "Please go back and complete the previous Тест.".

**Expected result:**
Passing the second test is allowed. The form for passing the test is open,

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

https://github.com/scholokov/qax-portal-2/assets/101987790/eb687c7f-80bf-4ae7-a989-a1aad0b9e059

**Comment by GNatala** [comment]
#1197

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
