### ISSUE TITLE
Events / Missed speaker's photo ot the Event

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1211]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/events/test/
2. Pay attention to the text "ДЕНИС ЩОЛОКОВ" before the button "Зареєструватись".

**Actual result:**
Missed speaker's photo before the text "ДЕНИС ЩОЛОКОВ".

**Expected result:**
Speaker's photo before the text "ДЕНИС ЩОЛОКОВ" is present.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6076-950&mode=design&t=5CaoXyeDza2bdayO-0

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/49b72c2b-2a71-49f0-81cb-86eec3eb57bd)

**Comment by GNatala** [comment]
#770

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
