### ISSUE TITLE
Event - Create a new design "Ongoing", "Expired" and "Картка урока"

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1212]
We need to create a new design "Ongoing", "Expired" and "Картка урока".
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6076-949&mode=design&t=RVaPHY7Q3omwyMY6-0

1. Сhange design "Картка урока"

![Картка уроку](https://github.com/scholokov/qax-portal-2/assets/109460500/6fa8a92d-9edd-447b-ab1d-726f433487d9)

2. Сhange font and color "Ongoing"

![Ongoing](https://github.com/scholokov/qax-portal-2/assets/109460500/cc470248-fefd-4f93-854f-271aafae7396)

3. Сhange font and color "Expired"

![Expired](https://github.com/scholokov/qax-portal-2/assets/109460500/e7454909-25f0-4632-bf5e-c260feae2cbc)

**Comment by AlonaSarapina** [comment]
ready for testing

Ongoing: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6076%3A950&mode=design&t=GL75jbuvaOpa5xPc-1

Expired/new card: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=8214%3A746&mode=design&t=GL75jbuvaOpa5xPc-1

**Comment by ButKoff** [comment]
#1238

**Comment by GNatala** [comment]
verified
