### ISSUE TITLE
Events / Text "Ongoing" in the current event is written in English

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1213]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/calendars/
2. Open an event that has already started.
3. Pay attention to the text "Ongoing" after the date of the event.

**Actual result:**
**Text "Ongoing"** in the current event is written in **English.**

**Expected result:**
**Text "Ongoing"** in the current event is written in **Ukrainian.**

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/6fef5ee4-78e3-413c-a540-f4f27567c43e)

**Comment by GNatala** [comment]
#770

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
