### ISSUE TITLE
Events / Text "Expired!" in the current event is written in English

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1214]
**Steps to reproduce:**

1. Open an event that has already finished https://www.qax-camp.com.ua/events/td-ucd/.
2. Pay attention to the text "Expired!" after the event date.

**Actual result:**
**Text "Expired!"** in the current event is written in **English.**

**Expected result:**
**Text "Expired!** in the current event is written in **Ukrainian.**

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/f0276218-8020-460d-a325-025710190ec6)

**Comment by GNatala** [comment]
#770

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/qax-portal-2/assets/88647733/f97ca5a5-9b96-4086-bded-45e8e4ba29c1)

**Comment by GNatala** [comment]
Дякую, виправила

**Comment by GNatala** [comment]
@DmytroMarkulych 
Дякую, знаю, Так і було.
Але 15.08.2023 Денис записував відео про строрення багів, де акцентував, що Пріорітет треба вчитися ставити.
Відео ось тут "Як створювати Баг?"на 3.30хв  https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/github/

**Comment by GNatala** [comment]
перевірено
