### ISSUE TITLE
Order/ The Hover of the button "Придбати зараз" is missing

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1215]
Steps to reproduce:
1. Open page https://www.qax-camp.com.ua/product/test/
2. Pay attention to the Hover of the button "Придбати зараз"

Actual Result: The Hover of the button "Придбати зараз" is missing
Expected Result: The Hover of the button "Придбати зараз" is present

Additional information: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=6218%3A1264&mode=dev

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
https://github.com/scholokov/qax-portal-2/assets/123776698/0e9f1606-85c9-40a1-bb96-d93d09a8967b

**Comment by ODrobik** [comment]
#768

**Comment by poroskundenys** [comment]
Готово

**Comment by ODrobik** [comment]
перевірено
