### ISSUE TITLE
Courses - Check course for "Безкоштовний тестовий період" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1216]
We need to check course for "Безкоштовний тестовий період" page
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/trial/
Requirements: in progress
![Trial](https://github.com/scholokov/qax-portal-2/assets/109460500/cdaec165-41be-4882-818f-161b53f34309)

**Comment by ButKoff** [comment]
#663

**Comment by DmitriiNasonov** [comment]
Testing completed
