### ISSUE TITLE
Unreading text on the page "Q5 – Види тестування" after clicking button "Start Quiz"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#122]
**STR**
1. Open page https://portal.qax-camp.com.ua/quizzes/q5-test-levels/
2. Scroll to the button "Start Quiz" 
3. Press the button "Start Quiz" shown unreading text color #E8E8E8 on white background 

**ACTUAL RESULT**
After clicking button "Start Quiz" shown unreading text ( <p>You must sign in or sign up to start the quiz.</p> ) color #E8E8E8 on white background 

**EXPECTED RESULT** 
After clicking button "Start Quiz" shown readable text ( <p>You must sign in or sign up to start the quiz.</p> ) on white background 
![Q5 – Рівні тестування – QAX Camp - Google Chrome 2022-09-19 15-17-04](https://user-images.githubusercontent.com/109384052/191027528-0bbbcb8f-377c-47b2-ab5b-3345218728e4.gif)
![kXWe1cgK0t](https://user-images.githubusercontent.com/109384052/191027697-b55dad52-7784-4d4e-b797-a5bcac613a44.png)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
