### ISSUE TITLE
Events / Blocks: "Date", "Author", "Місцевий час", "Додати в Google Календар", "iCal/Outlook export" are shifted in Expired Event

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1220]
**Steps to reproduce:**

1. Open an event that **has already finished https://www.qax-camp.com.ua/events/td-ucd/.**
2. Pay attention to the position of the blocks: "Date", "Author", "Місцевий час", "Додати в Google Календар", "iCal/Outlook export".

**Actual result:**
Blocks: "Date", "Author", "Місцевий час", "Додати в Google Календар", "iCal/Outlook export" are shifted  in Expired Event.

**Expected result:**
Blocks: "Date", "Author", "Місцевий час", "Додати в Google Календар", "iCal/Outlook export" are not shifted  in Expired Event.

**Notes:**
**In case the event is "Ongoing"  or "In future" and the button "Зареєструватись" is present, the design matches Figma.**

**Environment:**
Decktop
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6076-950&mode=design&t=5CaoXyeDza2bdayO-0

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/8b64cce3-d7b4-4c93-b1d7-95e04a78d208)

**Comment by GNatala** [comment]
#770

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
перевірено
