### ISSUE TITLE
Events / The Preview block is partially located on the Header block

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1221]
**Steps to reproduce:**

1. Open an event that has already finished https://www.qax-camp.com.ua/events/td-ucd/ on Mobile, Tablet
2. Pay attention to the position of the Preview block.

**Actual result:**
The Preview block is partially located on the Header block

**Expected result:**
Space between the Preview block and the Header block is 40px

**Environment:**
Mobile  Sony Xperia xz2
Google Chrome

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6076-950&mode=design&t=5CaoXyeDza2bdayO-0

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/338fa9d6-44b5-40e2-83c6-226fcd81426a)
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/7682d6d3-d07a-4e55-9a94-1facc0e129b8)

**Comment by GNatala** [comment]
#770

**Comment by scholokov** [comment]
а як в інших місцях? кроки, круси і тд

**Comment by GNatala** [comment]
Так все добре. Як і було.

**Comment by poroskundenys** [comment]
готово

**Comment by GNatala** [comment]
перевірено
