### ISSUE TITLE
"Безкоштовний тестовий період" course page - The height of the course preview is 675px

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1222]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/courses/trial/
2. Check course preview sizes

**Actual Result**
The height of the course preview is 675 px

**Expected Result**
The height of the course preview is 450 px

**Additional information**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=390-1036&mode=design&t=Z3BhSmFUUirFE6cj-0

**Enviroments**
Windows 10, Chrome 116.0.5845.97 (64 bit), Firefox 116.0.3 (64 bit)
![Безкоштовний тестовий період – QAX Camp - Google Chrome 22 08 2023 13_32_36](https://github.com/scholokov/qax-portal-2/assets/95171672/badbb5ed-cb90-47ff-a3a4-320de4013cd6)
![Безкоштовний тестовий період – QAX Camp — Mozilla Firefox 22 08 2023 13_34_42](https://github.com/scholokov/qax-portal-2/assets/95171672/99e736d4-8346-4f04-b69d-62a9b19ca9ae)

**Comment by DmitriiNasonov** [comment]
#1216

**Comment by scholokov** [comment]
it is ok

**Comment by DmitriiNasonov** [comment]
canceled
