### ISSUE TITLE
"Безкоштовний тестовий період" course page - Course prewiev is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1223]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/courses/trial/
2. Pay attention to the lack of a course preview

**Actual Result**
Course prewiev is missing

**Expected Result**
Course prewiev is present

**Additional information**
https://www.qax-camp.com.ua/courses/trial/ (PC version)
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=390-1036&mode=design&t=Z3BhSmFUUirFE6cj-0

**Enviroments**
Devtools Device toolbar (Windows 10), Chrome 116.0.5845.97 (64 bit), Firefox 116.3.0 (64 bit)
Android 8.1.0, Chrome 115.0.5790.168, Firefox 116.3.0

![Image](https://github.com/scholokov/qax-portal-2/assets/95171672/dc0722e6-b1f1-4f2d-b82b-bd3ec2a0ac45)
![Image](https://github.com/scholokov/qax-portal-2/assets/95171672/a5e6c646-beeb-4787-8242-9f557186f923)

![photo_2023-08-22_13-57-00](https://github.com/scholokov/qax-portal-2/assets/95171672/e6707e85-6130-47ca-85bd-c97166d97992)
![photo_2023-08-22_13-57-03](https://github.com/scholokov/qax-portal-2/assets/95171672/aea60112-4532-4ca0-ab17-0379660052ef)

**Comment by DmitriiNasonov** [comment]
#1216

**Comment by scholokov** [comment]
please retest

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced 
![Безкоштовний тестовий період – QAX Camp - Google Chrome 19 09 2023 18_13_16](https://github.com/scholokov/qax-portal-2/assets/95171672/68aa8827-1331-4cdf-89d9-f732d4b0b74a)
![Mozilla Firefox 19 09 2023 18_14_06](https://github.com/scholokov/qax-portal-2/assets/95171672/c7703bda-7ccf-40d9-bf75-4c5ffff4a252)
![photo_2023-09-19_18-15-49](https://github.com/scholokov/qax-portal-2/assets/95171672/4d07a600-e688-4b53-ad73-9030a35698ed)
![photo_2023-09-19_18-15-46](https://github.com/scholokov/qax-portal-2/assets/95171672/123aef8e-4a6d-40ed-8b1b-a78241cb12ed)

**Comment by scholokov** [comment]
треба написати загальний баг - що у "курсів" на таблеті та мобілі немає превью. і зробити силку на дизайн

**Comment by DmitriiNasonov** [comment]
bug-report isn't actual
