### ISSUE TITLE
"Безкоштовний тестовий період" course page - Previews of the lessons has sizes is ≈ 228 px * 128 px

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1225]
**Steps of reproducing**
1.  Open https://www.qax-camp.com.ua/courses/trial/
2. Scroll to lessons
3. Check sizes of the lessons preview

**Actual Result**
Previews of the lessons has sizes is ≈ 228 px * 128 px

**Expected Result**
Previews of the lessons has sizes is 180 px * 138 px

**Additional information**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&mode=design&t=jxbcSqJ1RIumLJgR-0

**Enviroments**
Windows 10, Chrome 116.0.5845.97 (64 bit), Firefox 116.0.3 (64 bit)
![Безкоштовний тестовий період – QAX Camp - Google Chrome 22 08 2023 16_18_55](https://github.com/scholokov/qax-portal-2/assets/95171672/f436c74b-7e6f-4e57-825d-91461d243883)
![Безкоштовний тестовий період – QAX Camp — Mozilla Firefox 22 08 2023 16_18_10](https://github.com/scholokov/qax-portal-2/assets/95171672/716081f2-b5d6-479a-86a9-9e6339743f3d)

**Comment by DmitriiNasonov** [comment]
#1216

**Comment by scholokov** [comment]
проблема у дизайні. у додатку все ок

**Comment by DmitriiNasonov** [comment]
canceled
