### ISSUE TITLE
"Безкоштовний тестовий період" course page - "Якщо не зрозуміло що робити далі" accordeon - Picture is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1227]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/courses/trial/
2. Open "Якщо не зрозуміло що робити далі" accordeon
3. Pay attention to the lack of a picture

**Actual Result**
Picture is missing

**Expected Result**
Picture is present

**Additional information**
https://www.qax-camp.com.ua/courses/trial/ (Check the PC version)

**Enviroments**
Devtools Device toolbar (Windows 10), Chrome 116.0.5845.97 (64 bit), Firefox 116.3.0 (64 bit)
Android 8.1.0, Chrome 115.0.5790.168, Firefox 116.3.0

![Image](https://github.com/scholokov/qax-portal-2/assets/95171672/b5168d03-b7ff-4b78-a098-7b4ca657dfed)
![Image](https://github.com/scholokov/qax-portal-2/assets/95171672/d9f564a6-196a-4de4-98f3-26b3528f889c)

![photo_2023-08-22_17-25-49](https://github.com/scholokov/qax-portal-2/assets/95171672/6cddd994-8411-4fe7-9630-673f03000939)
![photo_2023-08-22_17-25-46](https://github.com/scholokov/qax-portal-2/assets/95171672/0be2c6ed-0ea4-44c6-b868-7567c067fb50)

**Comment by DmitriiNasonov** [comment]
#1216

**Comment by scholokov** [comment]
please retest

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced partly
Created new bug report
