### ISSUE TITLE
Events / Text "The event is ongoing" in the current event is written in English

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1228]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/calendars/
2. Open an event that has already started.
3. Pay attention to the text "The event is ongoing" after the "iCal/Outlook export" block.

**Actual result:**
**Text "The event is ongoing"** in the current event is written in **English.**

**Expected result:**
**Text "The event is ongoing"** in the current event is written in **Ukrainian.**

**Environment:**
Desktop. Tablet, Mobile
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/eaab833d-db8e-400e-9c4f-3c83de6e1708)

**Comment by GNatala** [comment]
#770

**Comment by poroskundenys** [comment]
готово

**Comment by GNatala** [comment]
перевірено
