### ISSUE TITLE
Achievement /  Message "You must sign in or sign up to start the Тест." is written in English when a non-authorized user try to pass the test

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1229]
**Steps to reproduce:**

1. Open  https://www.qax-camp.com.ua/ach-travel/ as a non-authorized user.
2. Open the First test.
3. Click on "Show Details".
4. Click on "Занести результат".
5. Pay attention to the message: "You must sign in or sign up to start the Тест."

**Actual result:** 
The message "You must sign in or sign up to start the Тест." is written in English.

**Expected result:**
The message "**Ви маєте авторизуватися для початку теста**" is written in Ukrainian.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/83846a01-1927-4a37-8550-34123252634f)

**Comment by GNatala** [comment]
#1197

**Comment by scholokov** [comment]
пов'язана з

**Comment by scholokov** [comment]
#1230

**Comment by poroskundenys** [comment]
готово

**Comment by GNatala** [comment]
перевірено
