### ISSUE TITLE
The button "Відгуки" - on the main page - after clicking the button page reloads to the top without opening reviews

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#123]
**STR**
1. Open https://portal.qax-camp.com.ua/
2. Scroll to the button "Відгуки" 
3. Click the button "Відгуки" 

**ACTUAL RESULT**
After clicking the button "Відгуки" the page reloads to the top without opening reviews

**EXPECTED RESULT**
After clicking the button "Відгуки" open the page https://portal.qax-camp.com.ua/current_cources/ - down part of the page with reviews (focus should be on the reviews block at the end of the page) 

![qLeO9SO7Qv](https://user-images.githubusercontent.com/109384052/191036045-b17ac84d-3b3c-4bbc-8a25-6054026d7ed3.png)
![QAX Camp – Students Portal - Google Chrome 2022-09-19 16-03-52](https://user-images.githubusercontent.com/109384052/191036238-5ff9d070-caa5-4231-9039-25425ac47275.gif)

![1Bs3bbhqRv](https://user-images.githubusercontent.com/109384052/196793003-4232a53c-831d-4d04-b94f-f26b94523a09.png)

**Note**
1. Open https://github.com/scholokov/qax-portal-2/wiki/Block-%22%D0%86%D1%81%D1%82%D0%BE%D1%80%D1%96%D1%97-%D0%A3%D1%81%D0%BF%D1%96%D1%85%D1%83%22
2. Scroll to the end of the page;
3. According to requirements the button "Відгуки" is active - "Відгуки - переходе у відгіки"

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha давайте поправимо steps for reproduce. Насилання на Git винесемо як Note. І додами рункт, де вкажемо що клікаємо на кнопку "Відгуки"

**Comment by BatalovaOlha** [comment]
> @BatalovaOlha давайте поправимо steps for reproduce. Насилання на Git винесемо як Note. І додами рункт, де вкажемо що клікаємо на кнопку "Відгуки"

Я додала. Сподіваюсь що вірно, бо пункт Note я ще не додавала в баг репорт.

**Comment by BatalovaOlha** [comment]
verified
