### ISSUE TITLE
Order/ The Preview is an active element in the "Order" page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1231]
Steps to reproduce:
1. Open page https://www.qax-camp.com.ua/product/test/
2. Pay attention to the Preview of the "Order" page

Actual Result:  The Preview is an active element in the "Order" page
Expected Result:  The Preview is not an active element in the "Order" page

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/24bc6a07-ff7b-40c4-86e8-386d3ccb6827)

**Comment by ODrobik** [comment]
#768

**Comment by poroskundenys** [comment]
Готово

**Comment by ODrobik** [comment]
перевірено
