### ISSUE TITLE
Calendar - Імплементувати блок "Календар" - The mobile view of the "Calendar - month" fails to match the figma

### ISSUE THREAD

**Issue by Artem-16** [scholokov/qax-portal-2#1232]
**Steps to playback:**

1. Open https://www.qax-camp.com.ua/calendar-month/
2. Open Dev tools
3. Toggle device toolbar
4. Dimensions iPhone XR

**Actual result:**
 "Calendar - month" design fails to match the figma

**Expected result:**
"Calendar-month" design corresponds to figma
![фігма календарик](https://github.com/scholokov/qax-portal-2/assets/132911639/88896b32-a7dc-4f61-9458-4ce1ec29cbf7)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![баг календар дизайн ](https://github.com/scholokov/qax-portal-2/assets/132911639/d7927800-e523-45ad-8355-2c10569c913d)

**Comment by Artem-16** [comment]
#737

**Comment by scholokov** [comment]
technical limitation

**Comment by Artem-16** [comment]
то лишати цей баг чи закривати?

**Comment by scholokov** [comment]
закриваємо

**Comment by Artem-16** [comment]
ок
