### ISSUE TITLE
Calendar - Імплементувати блок "Календар" - Mobile "calendar" fails to work when you click on an event 

### ISSUE THREAD

**Issue by Artem-16** [scholokov/qax-portal-2#1234]
**Steps to playback:**

1. Open https://www.qax-camp.com.ua/calendar-month/
2. Open Dev tools
3. Toggle device toolbar
4. Dimensions iPhone XR
5. Scroll down to the second calendar
6. Date 23 August
7. Click on "QAX Travel - Практика"

**Actual result:**
Mobile "calendar" fails to work when you click on an event 

**Expected result:**
Mobile "calendar" works when you click on an event 

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![не кликабельний календарик урок](https://github.com/scholokov/qax-portal-2/assets/132911639/af7e76bc-f714-4846-8022-2667206e93e0)

**Comment by Artem-16** [comment]
#737

**Comment by poroskundenys** [comment]
Готово
