### ISSUE TITLE
Lesson "HTML&CSS Basics"/In the course "Web & Mobile" the Content of the lesson "HTML&CSS Basics" is written in Russian

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1235]
Steps to Reproduce:

1. Open page https://www.qax-camp.com.ua/courses/web-mobile/lessons/basic-html-for-qa/
2. Pay attention to the Content of the lesson "HTML&CSS Basics" of the course "Web & Mobile"

Actual Result: the Content of the lesson "HTML&CSS Basics" is written in Russian
Expected Result: the Content of the lesson "HTML&CSS Basics" is written in Ukrainian

Environment:
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/26468a6d-17bd-45a6-8bf1-b1bf3bae9e92)

**Comment by ODrobik** [comment]
#949

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
