### ISSUE TITLE
Event - Registration - After confirming registration, a link to the meeting should appear

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1236]
Must be done after confirming the registration, a link to the meeting should appear.
Environment: https://www.qax-camp.com.ua/events/security-basics/
![Registration](https://github.com/scholokov/qax-portal-2/assets/109460500/1c8a0677-a3ed-4445-9f1a-4b8dde322498)

**Comment by DmitriiNasonov** [comment]
Testing completed
