### ISSUE TITLE
Event - Email - After confirming registration, you should receive a confirmation email.

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1237]
Must be done after confirming registration, you should receive a confirmation email.
Environment: https://www.qax-camp.com.ua/events/
Requirements: https://qaxm.atlassian.net/wiki/spaces/PM/pages/23363585

![Email](https://github.com/scholokov/qax-portal-2/assets/109460500/e648c621-4089-4229-b1a2-3908a3fd5a29)

**Email content №1**

 Привіт Ім'я, 
Реєстрація пройшла успішно. 
Ми перевіримо та надішлемо підтвердження якнайшвидше. 

Дякуємо що обираєш QAX ❤️

З повагою, 
QAX- Camp

**Email content №2**

Привіт Ім'я, 
Реєстрацію на подію "LinkedIn" підтверджено.

Нагадуємо, що подія відбудеться:

🗓28.08.2023 
⏰️17:30 

Посилання на зустріч у GoogleMeet:

 

Чекаємо тебе у прогресивному просторі QAX-Camp!

**Comment by DmitriiNasonov** [comment]
Testing completed. Bugs not found
