### ISSUE TITLE
Event - Implement a new design "Ongoing", "Expired" and "Картка урока"

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1238]
We need to implement a new design "Ongoing", "Expired" and "Картка урока".
Environment: https://www.qax-camp.com.ua/events/td-ucd/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6076-949&mode=design&t=TUzwvF8R6yIxiOZM-0

![Expired](https://github.com/scholokov/qax-portal-2/assets/109460500/e94f5193-77d8-470b-b678-7b479c983510)

![Ongoing](https://github.com/scholokov/qax-portal-2/assets/109460500/790cec39-7221-4bcb-b17f-9dbd1f7965c4)

**Comment by ButKoff** [comment]
#1212

**Comment by poroskundenys** [comment]
Когда появляется надпись Ongoing?

**Comment by scholokov** [comment]
коли івент іде прям зараз

**Comment by poroskundenys** [comment]
Готово. В шорткод уроков нужно добавлять этот параметр col=2, чтобы уроки в две колонки выводились

**Comment by GNatala** [comment]
verified
