### ISSUE TITLE
Events / Extra element button "Зареєструватись" is on the "QAX WiDiQ – Практика" Event page

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1239]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/events/widiq/
2. Pay attention to the button "Зареєструватись".

**Actual result:**
Extra element button "Зареєструватись" is on the "QAX WiDiQ – Практика" Event page.

**Expected result:**
Element button "Зареєструватись" is absent on the "QAX WiDiQ – Практика" Event page.

**Environment:**
Desktop. Tablet, Mobile
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/bbfaed9f-97f7-4576-8057-47b52373ba8d)

**Comment by GNatala** [comment]
#770

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
