### ISSUE TITLE
Extra space after the word "менторство" in the block "До оферу разом з QAX" on the main page

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#124]
**STR**
1. Open https://portal.qax-camp.com.ua/
2. Pay attention to the first phrase  / block "До оферу разом з QAX"

**ACTUAL RESULT**
After the word "менторство" is shown extra space at the end of the phrase.

**EXPECTED RESULT**
After the word "менторство" is NOT shown extra space at the end of the phrase.

![CDtI0I6Y7G](https://user-images.githubusercontent.com/109384052/191041278-f1d40e75-f6e6-423f-8554-527041512bb5.png)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
