### ISSUE TITLE
Events / Extra element button "Зареєструватись" is on the "QAX Travel – Практика" Event page

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1240]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/events/qax-practice-travel/
2. Pay attention to the button "Зареєструватись".

**Actual result:**
Extra element button "Зареєструватись" is on the "QAX Travel – Практика" Event page.

**Expected result:**
Extra element button "Зареєструватись" is on the "QAX Travel – Практика" Event page.

**Environment:**
Desktop. Tablet, Mobile
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/d1e7a737-f598-424e-a079-527b2c377020)

**Comment by GNatala** [comment]
#770

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
