### ISSUE TITLE
Детальний опис проекту Travel 2.0 /  In the accordion "Основна інформація" - link "Вимоги" leads to the previous requirements

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1241]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/project-travel/lessons/project-dt-travel-2-0/
2. Open the accordion "Основна інформація".
3. Pay attention to the link "Вимоги".

**Actual result:**
 Link "Вимоги" leads to the previous requirements https://github.com/scholokov/long-travel-2/wiki

**Expected result:**
 **Link "Вимоги" leads to the actual requirements https://qax.gitbook.io/qax-travel/requirements.**

**Environment:**
Desktop. Tablet, Mobile
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/aa66afbd-d23e-40a0-b946-d089e2322805)

**Comment by GNatala** [comment]
#907

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
