### ISSUE TITLE
Test - Implement the design of the "Ви маєте авторизуватися для початку теста" message

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1242]
We need to implement the design of the "Ви маєте авторизуватися для початку теста" message.
Environment: https://www.qax-camp.com.ua/courses/travel-quiz__trashed/quizzes/travel-first-best/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=8317-148&mode=design&t=yYxFEMt7kdSuMJ7Q-0
Requirements: https://github.com/scholokov/qax-portal-2/wiki/8.0-%D0%90%D1%87%D1%96%D0%B2%D0%BA%D0%B8

Old design:
![Achievement_old](https://github.com/scholokov/qax-portal-2/assets/109460500/20ba65fa-6d99-428c-978d-2c086734bb51)

New design:
![Achievement_new](https://github.com/scholokov/qax-portal-2/assets/109460500/55f61db4-8d01-4eb1-81de-06e0dfadeae6)

**Comment by ButKoff** [comment]
#1230

**Comment by poroskundenys** [comment]
готово

**Comment by GNatala** [comment]
перевірено
