### ISSUE TITLE
Order - Received - Create a new design "Замовлення отримано" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1243]
We need to create a new design "Замовлення отримано" page.
Environment: https://www.qax-camp.com.ua/checkout/order-received/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6398-1146&mode=design&t=YEXWnomKJ5O4C08Q-0

![Order-received](https://github.com/scholokov/qax-portal-2/assets/109460500/edbd8445-d87e-4502-9eee-e7efb3af05d2)

**Comment by AlonaSarapina** [comment]
ready for testing 
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=8377%3A533&mode=design&t=4O41H9a4R0ESuRLi-1

**Comment by ButKoff** [comment]
#1274

**Comment by ODrobik** [comment]
verified
