### ISSUE TITLE
"calendars" page  - "Найближча подія" block - Font-family of text with date of event is Raleway

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1244]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/calendars/
2. Check font-family of text with date of event

**Actual Result**
Font-family of text with date of event is Raleway

**Expected Result**
Font-family of text with date of event is Rubik

**Additional information**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6877-1444&mode=design&t=qHluz5TJCc540d5j-0

**Enviroments**
Windows 10, Chrome 116.0.5845.111 (64 bit)
![calendars – QAX Camp - Google Chrome 29 08 2023 19_16_15](https://github.com/scholokov/qax-portal-2/assets/95171672/70528349-775e-4492-9ff5-042d5d46eb91)
![Portal design – Figma - Google Chrome 05 09 2023 15_57_54](https://github.com/scholokov/qax-portal-2/assets/95171672/42480182-edc7-422a-ab05-251c7fb3bb62)

**Comment by DmitriiNasonov** [comment]
#1128

**Comment by scholokov** [comment]
краще ще додати скріна з фігми

**Comment by DmitriiNasonov** [comment]
added

**Comment by poroskundenys** [comment]
готово

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
