### ISSUE TITLE
GitHub Project - Portal - Task/Issue - "Component" - Component "calendars" is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1245]
**Steps of reproducing**
1. Open https://github.com/users/scholokov/projects/1/views/5
2. Open any issue or task
3. Click to "Component" block

**Actual Result**
Component "calendars" is missing

**Expected Result**
Component "calendars" is present

**Additional information**
https://www.qax-camp.com.ua/calendars/

**Enviroments**
Windows 10, Chrome 116.0.5845.111 (64 bit)
![_calendars_ page - _Найближча подія_ block - Font-family of text with date of event is Raleway · Portal - Google Chrome 29 08 2023 19_37_29](https://github.com/scholokov/qax-portal-2/assets/95171672/5593ac87-7370-4ee0-ac88-efdfc3a6825f)

**Comment by DmitriiNasonov** [comment]
#1128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
