### ISSUE TITLE
Events / Missed Speaker's Block in the Event "QAX Portal – Практика"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1246]
**Steps to reproduce:**

1. Open: https://www.qax-camp.com.ua/events/qax-practice-portal/
2. Pay attention to the absence of Speaker's Block.

**Actual result:**
Missed Speaker's Block in the Event "QAX Portal – Практика".

**Expected result:**
Speaker's Block in the Event "QAX Portal – Практика" is present.

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6076-950&mode=design&t=5CaoXyeDza2bdayO-0

**Environment:**
Desktop. Tablet, Mobile
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/f1e936a1-fde1-4f22-95c9-6264be29b976)

**Comment by GNatala** [comment]
#770

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
