### ISSUE TITLE
Events / The name of the author "DENIS SCHOLOKOV" is written in English in Event "QAX WiDiQ – Практика"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1247]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/events/widiq/
2. Pay attention to the text "DENIS SCHOLOKOV" between Date and "Місцевий час".

**Actual result:**
The name of the author "DENIS SCHOLOKOV" is written in English.

**Expected result:**
The name of the author "DENIS SCHOLOKOV" is written in Ukrainian.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6076-950&mode=design&t=5CaoXyeDza2bdayO-0

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/5a4935d7-5ad5-4256-9fd6-a97a1ebfd78e)

**Comment by GNatala** [comment]
#770

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
