### ISSUE TITLE
Courses - Implement course preview on Tablet and Mobile according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1250]
We need to implement course preview on Tablet and Mobile according to Figma.
Environment: https://www.qax-camp.com.ua/courses/q6-basic/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=390-1035&mode=design&t=WYWm4Y9eVZ35dsxZ-0

Tablet design:
![Tablet](https://github.com/scholokov/qax-portal-2/assets/109460500/7dda9e07-c9f6-4660-b025-a74ac2cc978c)

Mobile design:
![Mobile](https://github.com/scholokov/qax-portal-2/assets/109460500/5dc6f79e-1e55-4c9c-a922-6b1cb87e9e33)

**Comment by poroskundenys** [comment]
готово
