### ISSUE TITLE
Lessons - Check lesson for "GitFlow" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1252]
We need to check lesson for "GitFlow" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/processes/lessons/gitflow/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D0%B8
![GitFlow](https://github.com/scholokov/qax-portal-2/assets/109460500/4e8e3e0e-b072-466f-935c-92f25a9566f2)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
passed
