### ISSUE TITLE
Lessons - Events - Check lesson and event for "Project Quality Level" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1254]
We need to check lesson and event for "Project Quality Level" page.
Please check availability of requirements, functional compliance and design compliance.
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D0%B8

Environment lesson: https://www.qax-camp.com.ua/courses/processes/lessons/q-levels/
![Project Quality Level](https://github.com/scholokov/qax-portal-2/assets/109460500/810cb21e-8e6f-4f9a-b4aa-cc76af8ada03)

Environment event: https://www.qax-camp.com.ua/events/q-levels/
![Project Quality Level_event](https://github.com/scholokov/qax-portal-2/assets/109460500/79ebc330-064d-4343-894e-b9b22158404d)

**Comment by ButKoff** [comment]
#664

**Comment by ODrobik** [comment]
verified
