### ISSUE TITLE
Lessons - Events - Check lesson and event for "Regression" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1256]
We need to check lesson and event for "Regression" page.
Please check availability of requirements, functional compliance and design compliance.
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F

Environment lesson: https://www.qax-camp.com.ua/courses/testing/lessons/regression/
![Regression](https://github.com/scholokov/qax-portal-2/assets/109460500/cd146483-02d1-4d89-bfea-2455801c572e)

Environment event: https://www.qax-camp.com.ua/events/regression/
![Regression_event](https://github.com/scholokov/qax-portal-2/assets/109460500/fbec560e-5d61-4bb3-a115-84e9cae51278)

**Comment by ButKoff** [comment]
#664

**Comment by DmitriiNasonov** [comment]
Lesson testing completed. Event testing blocked by missing design of completed event
