### ISSUE TITLE
Events / The elements "Денис Щолоков", and "Місцевий час" are not vertically centered in their blocks

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1257]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/events/td-ucd/
2. Pay attention to the position of the elements "Денис Щолоков", "Місцевий час".

**Actual result:**
The elements "Денис Щолоков", and "Місцевий час" are not vertically centered in their blocks.

**Expected result:**
The elements "Денис Щолоков", and "Місцевий час" are vertically centered in their blocks.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6076-950&mode=design&t=5CaoXyeDza2bdayO-0

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/da8e4c83-7c8c-4d41-ac26-9eb3f6c34797)

**Comment by GNatala** [comment]
#770

**Comment by poroskundenys** [comment]
готово

**Comment by GNatala** [comment]
перевірено
