### ISSUE TITLE
Events / Block "Місцевий час" is wider than other blocks on Mobile

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1258]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/calendars/ on Mobile
2. Choose any Event - https://www.qax-camp.com.ua/events/traceability-matrix/ .
3. Pay attention to the width of the block "Місцевий час".

**Actual result:**
Block "Місцевий час" is wider than other blocks.

**Expected result:**
Block "Місцевий час" has the same width as other blocks.

**Environment:**
Mobile iPhone 12 Pro

Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6076-950&mode=design&t=5CaoXyeDza2bdayO-0

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/f0fbb555-6a45-4a09-92a7-6255342bff03)

**Comment by GNatala** [comment]
#770

**Comment by poroskundenys** [comment]
готово

**Comment by GNatala** [comment]
перевірено
