### ISSUE TITLE
Events / Hover of the Speaker's photo color is  #40d9f1 

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1259]
**Steps to reproduce:**

1. Open  https://www.qax-camp.com.ua/events/traceability-matrix/ 
2. Pay attention to the Hover of the Speaker's photo.

**Actual result:**
Hover of the Speaker's photo color is #40d9f1.

**Expected result:**
Hover of the Speaker's photo color is #F66F5D.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6076-950&mode=design&t=5CaoXyeDza2bdayO-0

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/20ff8b01-eb5a-4460-99f3-ebfa71379654)

**Comment by GNatala** [comment]
#770

**Comment by poroskundenys** [comment]
готово

**Comment by GNatala** [comment]
перевірено
