### ISSUE TITLE
"Наступна подія" block - Numbers in the countdown are not displayed on the first page load

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1260]
**Steps of reproducing**
1. Clear browser cache
2. Open https://www.qax-camp.com.ua/calendars/
3. Pay attention to the numbers in the countdown

**Actual Result**
Numbers in the countdown are not displayed on the first page load

**Expected Result**
Numbers in the countdown are displayed on the first page load

**Additional information**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6704-1434&mode=design&t=tJVbnqhVdHpiyNYu-0

**Enviroments**
Android 8.1.0, Chrome 116.0.5845.163
![photo_2023-09-06_15-45-35](https://github.com/scholokov/qax-portal-2/assets/95171672/dd4ed8b3-74d6-4cf7-9958-3079e385b4a7)

**Comment by DmitriiNasonov** [comment]
#1128

**Comment by DmitriiNasonov** [comment]
#1309

**Comment by poroskundenys** [comment]
готово

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
