### ISSUE TITLE
"Наступна подія" block - The date and time of the event has been partially moved to the line below

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1261]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/calendars/
2. Pay attention to date and time of the event

**Actual Result**
The date and time of the event has been partially moved to the line below

**Expected Result**
The date and time of the event is NOT moved to the line below.

**Additional information**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6704-1434&mode=design&t=tJVbnqhVdHpiyNYu-0

**Enviroments**
Android 8.1.0, Chrome 116.0.5845.163, Firefox 117.0
![photo_2023-09-06_15-48-47](https://github.com/scholokov/qax-portal-2/assets/95171672/990e4944-d247-4fb9-8036-5f613684fb68)
![photo_2023-09-06_15-49-20](https://github.com/scholokov/qax-portal-2/assets/95171672/952ca09a-ddb1-4530-951d-6502d84bf219)

**Comment by DmitriiNasonov** [comment]
#1128

**Comment by scholokov** [comment]
яка ширина екрану?
чи входить у дизайн?

**Comment by DmitriiNasonov** [comment]
canceled. created new bug report:
https://github.com/scholokov/qax-portal-2/issues/1313
