### ISSUE TITLE
Calendar - Implement color markers on days of the week according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1266]
We need to have the possibility to set point colors for each event.

Environment: https://www.qax-camp.com.ua/calendar/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6112-975&mode=design&t=29CnvwJHppQDSkOO-0

Monday and Thursday marker color - #F66F5D
Tuesday and Wednesday marker color - #6758EE

![Calendar markers](https://github.com/scholokov/qax-portal-2/assets/109460500/3d5a10ff-a5c6-4489-bc20-4ede200153b5)

**Comment by poroskundenys** [comment]
готово

**Comment by GNatala** [comment]
перевірено
