### ISSUE TITLE
Event - Implement a ban on registration after the start of the event

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1267]
We need to implement a ban on registration after the start of the event.
Environment: https://www.qax-camp.com.ua/events/htmlcss-%d0%be%d1%81%d0%bd%d0%be%d0%b2%d0%b8/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6076-949&mode=design&t=PlYNn0dViY8JDJ2W-0

![Event ban](https://github.com/scholokov/qax-portal-2/assets/109460500/1a8eec85-d05a-40f1-92d8-121b63c4f467)

**Comment by scholokov** [comment]
ready for testing

**Comment by GNatala** [comment]
verified
