### ISSUE TITLE
Calendar / The current date color is #40d9f1

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1268]
**Steps to reproduce:**

1. Open  https://www.qax-camp.com.ua/calendars/
2. Pay attention to the current date color.

**Actual result:**
The current date color is #40d9f1.

**Expected result:**
The current date color is #F66F5D.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6112-976&mode=design&t=Ef82tSUGZqS6zutk-0

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/c4d843de-db35-4c62-aa6e-4742ed4ad77d)

**Comment by GNatala** [comment]
#737

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
An issue is reproduced.

Windows 7 
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/b67c5a39-e7c5-4282-8e75-fbf7f143e36b)

**Comment by poroskundenys** [comment]
готово

**Comment by GNatala** [comment]
перевірено
