### ISSUE TITLE
Practice / Missed preview of the card "Підписка на 1 місяць"  in the accordion "Підписка на використання навчальних матеріалів"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1269]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/practice/
2. Open the accordion "Підписка на використання навчальних матеріалів".
3. Pay attention to the preview of the card "Підписка на 1 місяць".

**Actual result:**
Missed preview of the card "Підписка на 1 місяць".

**Expected result:**
The preview of the card "Підписка на 1 місяць" is present.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/865e6820-dde4-46ff-82ac-18d07473a8ea)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
