### ISSUE TITLE
Checkout/Figma - The size of the "Підтвердити замовлення" button in the section "Оформлення замовлення" is "278x41px" 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1270]
Steps to Reproduce:

1. Open page https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6423-1537&mode=design&t=xDtWvvjvsVs6jtVM-0
2. Scroll down to the Tablet environment
3. Pay attention to the size of the "Підтвердити замовлення" button on the  "Оформлення замовлення" section

Actual Result: The size of the "Підтвердити замовлення" button in the section "Оформлення замовлення" is "278x41px" 
Expected Result: The size of the "Підтвердити замовлення" button in the section "Оформлення замовлення" is "738x40px" 

Environment: **Lenovo Tab10**
**OS:** Windows 10 Pro (x64),
**Browser:** Google Chrome v 110.0.5481.105 (x64)
**Viewport:** 768x461px

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/71c0beca-5415-4e38-bca7-4d639f4afd1e)

**Comment by ODrobik** [comment]
#723

**Comment by AlonaSarapina** [comment]
fixed 
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6423%3A1449&mode=design&t=Z2CumR6RjbvInJDF-1

**Comment by ODrobik** [comment]
verified
