### ISSUE TITLE
Checkout/The "правила та умови" text is displayed in the section "Оформлення замовлення"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1271]
Steps to Reproduce:

1. Open page https://www.qax-camp.com.ua/checkout/
2. Pay attention to the "правила та умови" text in the section "Оформлення замовлення"

Actual Result: 
The "правила та умови" text is displayed in the section "Оформлення замовлення"

Expected Result: 
The "правилами та умовами" text is displayed in the section "Оформлення замовлення"

Environment: Lenovo Tab10
OS: Windows 10 Pro (x64),
Browser: Google Chrome v 110.0.5481.105 (x64)
Viewport: 768x461px

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/8722ee0a-503b-482f-a898-26dc80e6a268)

**Comment by ODrobik** [comment]
#769

**Comment by scholokov** [comment]
не зрозуміло у чому саме помилка. єкспектід та екшуал співпадають

**Comment by ODrobik** [comment]
слова мають закінчення не по тексту "та погоджуюсь з правил**ами** та умов**ами**"
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/77431031-7329-4cf0-8ac1-b6c42ac3689c)

**Comment by scholokov** [comment]
а якби було написано:
Actual Result: 
The "правила та умови" text is displayed in the section "Оформлення замовлення"

Expected Result: 
The "правилами та умовами" text is displayed in the section "Оформлення замовлення"

зрозуміти було простіше :))))

**Comment by ODrobik** [comment]
виправлено

**Comment by poroskundenys** [comment]
готово

**Comment by ODrobik** [comment]
verified
