### ISSUE TITLE
Course "Процеси" / Missed preview of the lesson "Хто такий IT PM?"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1273]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/pm-basics/
2. Pay attention to the preview of the lesson "Хто такий IT PM?".

**Actual result:**
Missed preview of the lesson "Хто такий IT PM?".

**Expected result:**
The preview of the lesson "Хто такий IT PM?" is present.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/aea37f9a-f721-45c8-9c7d-78c48188728c)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
