### ISSUE TITLE
Order - Received - Implement a design "Замовлення отримано" page according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1274]
We need to implement a new design "Замовлення отримано" page.
Environment: https://www.qax-camp.com.ua/checkout/order-received/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6398-1146&mode=design&t=YEXWnomKJ5O4C08Q-0

![Замовлення отримано](https://github.com/scholokov/qax-portal-2/assets/109460500/680e2ac2-5e63-4e33-a77b-a40960c56139)

**Comment by ButKoff** [comment]
#1243

**Comment by poroskundenys** [comment]
Готово.
Для создание тестового заказа нужно включить еще один способ оплаты https://prnt.sc/OQMfpnUU-pg0 и на чекауте его выбрать

**Comment by ODrobik** [comment]
verified
