### ISSUE TITLE
Lessons - Events - Check lesson and event for "Git + GitHub – Основи" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1275]
We need to check lesson and event for "Git + GitHub – Основи" page.
Please check availability of requirements, functional compliance and design compliance.
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#web--mobile

Environment lesson: https://www.qax-camp.com.ua/courses/%d1%82%d0%b8%d0%bc%d1%87%d0%b0%d1%81%d0%be%d0%b2%d0%b8%d0%b9-%d0%b4%d0%be%d1%81%d1%82%d1%83%d0%bf-%d0%b4%d0%bb%d1%8f-%d0%bf%d0%b0%d0%ba%d0%b5%d1%82%d1%96%d0%b2-medmax/lessons/git-github/
![Git + GitHub – Основи](https://github.com/scholokov/qax-portal-2/assets/109460500/69cf48ea-d87f-47f7-b522-925d40be0aa7)

Environment event: https://www.qax-camp.com.ua/events/git-github/
![Git + GitHub – Основи_](https://github.com/scholokov/qax-portal-2/assets/109460500/006894f7-df4c-45e1-b30d-f79cd2e56a8f)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
verified
