### ISSUE TITLE
Lessons - Events - Check lesson and event for "Traceability matrix" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1276]
We need to check lesson and event for "Traceability matrix" page.
Please check availability of requirements, functional compliance and design compliance.
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F

1. Environment lesson: https://www.qax-camp.com.ua/courses/testing/lessons/traceability-matrix/

![Traceability matrix](https://github.com/scholokov/qax-portal-2/assets/109460500/eeeded0c-679d-4057-9c54-0cbf3a61658a)

2. Environment event: https://www.qax-camp.com.ua/events/traceability-matrix/

![Traceability matrix_](https://github.com/scholokov/qax-portal-2/assets/109460500/2cafce7c-e18d-42a8-b2e6-7206eb642723)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
verified
