### ISSUE TITLE
Event / Font-weight of the text "Завершилася" is 400 in the block "Date"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1277]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/events/td-ucd/
2. Pay attention to the text "Завершилася" in the block "Date".

**Actual result:**
Font-weight of the text "Завершилася" is 400.

**Expected result:**
Font-weight of the text "Завершилася" is 500.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6076-949&mode=design&t=TUzwvF8R6yIxiOZM-0

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/3c1f1759-fe30-4c90-95ec-33fff6ca3e66)

**Comment by GNatala** [comment]
#1238

**Comment by poroskundenys** [comment]
готово

**Comment by GNatala** [comment]
перевірено
