### ISSUE TITLE
Lessons - "Види, методи та рівні тестування" / Archive Video's previews do not match the requirements in Canva in the accordions "Архів"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1278]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/testing/lessons/q6-02-testing-types/
2. Scroll down to the accordions "Архів" - open them.
3. Pay attention to the Video's preview.

**Actual result:**
Archive Video's previews do not match the requirements in Canva.

**Expected result:**
Archive Video's previews match the requirements in Canva.

**Additional information:** 
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F

https://www.canva.com/design/DAFfaq-NrFI/aTHK4cEZYzwKE2R5DFOnXg/edit

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/78800f66-16e5-4d33-a05a-23829c27137f)

**Comment by GNatala** [comment]
#916

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
