### ISSUE TITLE
Lessons - "Види, методи та рівні тестування" / The text "Scholokov Denis" is written in English

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1279]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/testing/lessons/q6-02-testing-types/
2. Scroll down to the text "Автор: Scholokov Denis".
3. Pay attention to the language of the name and surname.

**Actual result:**
 Text "Scholokov Denis" is written in English.

**Expected result:**
Text "Scholokov Denis" is written in Ukrainian.

**Requirements:** 
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D0%B8

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/5c8979a0-8465-44b6-b864-aacf5d26b73c)

**Comment by GNatala** [comment]
#916

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
