### ISSUE TITLE
Lessons - "Verification vs Validation" / Spelling mistake in the word  "Верифікация" in accordion "Архів"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1280]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/testing/lessons/verification-vs-validation/
2. Open accordion "Архів".
3. Pay attention to the spelling of the title of the section "Верифікация".

**Actual result:**
Spelling mistake in the word "Верифікац**и**я".

**Expected result:**
The word "Верифікація"  is written with the letter "і".

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/e0cdb6d6-4cda-4353-b013-69b11cfecd0e)

**Comment by GNatala** [comment]
#913

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
