### ISSUE TITLE
Lessons - "Verification vs Validation" / Missed word "робимо" in the phrase “Чи ми продукт правильно?” in the accordion "Архів"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1281]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/testing/lessons/verification-vs-validation/
2. Open accordion "Архів".
3. Pay attention to the phrase “Чи ми продукт правильно?” in the section "Верифікация".

**Actual result:**
 Missed word "робимо" in the phrase “Чи ми продукт правильно?".

**Expected result:**
The phrase “Чи ми продукт правильно?" containes word "робимо" .

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/b68001ba-2160-4c15-885e-4771cae1e12a)

**Comment by GNatala** [comment]
#913

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
