### ISSUE TITLE
"Priority vs Severity" lesson - Video preview is cuttered

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1283]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/courses/testing/lessons/priority-vs-severity/
2. Scroll to video
3. Pay attention to the video preview

**Actual Result**
Video preview is cuttered

**Expected Result**
Video preview isn't cuttered

**Additional information**
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F
https://www.canva.com/design/DAFfaq-NrFI/aTHK4cEZYzwKE2R5DFOnXg/edit

**Enviroments**
Windows 10, DevTools, Chrome 117.0.5938.63 (64 bit), Firefox 117.0.1 (64 bit)
Android 8.1.0, Chrome 116.0.5845.172, Firefox 117.0.1
![Priority vs Severity – QAX Camp - Google Chrome 13 09 2023 15_17_12](https://github.com/scholokov/qax-portal-2/assets/95171672/6681668f-13dc-40ea-8dad-c7c05eb6e815)
![Priority vs Severity – QAX Camp — Mozilla Firefox 13 09 2023 15_19_48](https://github.com/scholokov/qax-portal-2/assets/95171672/c68b5091-0eeb-43e0-84fc-b677dfd70b1e)
![Priority vs Severity – QAX Camp — Mozilla Firefox 13 09 2023 15_20_53](https://github.com/scholokov/qax-portal-2/assets/95171672/f42b50e0-c7f9-4cc2-8ce9-f2fbbf4f8980)
![Priority vs Severity – QAX Camp - Google Chrome 13 09 2023 15_17_02](https://github.com/scholokov/qax-portal-2/assets/95171672/503aa980-9b5b-400a-81d4-1cbced0705ec)

**Comment by DmitriiNasonov** [comment]
#912

**Comment by poroskundenys** [comment]
готово

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
