### ISSUE TITLE
Calendar - "Найближча подія" block - Photo preview of the event is displayed in poor quality

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1284]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/calendars/
2. Pay attention to the photo preview of the event

**Actual Result**
Photo preview of the event is displayed in POOR quality

**Expected Result**
Photo preview of the event is displayed in GOOD quality

**Enviroments**
Windows 10, Chrome 117.0.5938.63 (64 bit)
Android 8.1.0, Chrome 116.0.5845.172
![calendars – QAX Camp - Google Chrome 04 09 2023 19_12_21](https://github.com/scholokov/qax-portal-2/assets/95171672/9db9b85c-1b4f-4bf6-87f3-84f3028d738c)
![calendars – QAX Camp - Google Chrome 11 09 2023 13_03_19](https://github.com/scholokov/qax-portal-2/assets/95171672/52a7162e-b13b-4820-9f50-2480ff3da452)t
![photo_2023-09-13_15-57-15](https://github.com/scholokov/qax-portal-2/assets/95171672/9e29bbaf-587b-4b38-a61d-b1d0f59b87e2)

**Comment by DmitriiNasonov** [comment]
#1128

**Comment by poroskundenys** [comment]
Готово

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
