### ISSUE TITLE
Event / Missed Preview of the Event "QAX Travel – Практика"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1285]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/events/qax-practice-travel/
2. Pay attention to the Preview of the Event.

**Actual result:**
A preview of the Event "QAX Travel – Практика" is missed.

**Expected result:**
A preview of the Event "QAX Travel – Практика" is present.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://github.com/scholokov/qax-portal-2/wiki/7.0-%D0%86%D0%B2%D0%B5%D0%BD%D1%82

![image](https://github.com/scholokov/qax-portal-2/assets/101987790/2a9d5f8a-f171-4b70-bf10-91539df63e8a)

**Comment by GNatala** [comment]
#770

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
