### ISSUE TITLE
Product - Check proof of purchase on the “Базовий курс QA” page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1289]
We need to check proof of purchase on the “Базовий курс QA” page.
Please check availability of requirements, functional compliance and design compliance.
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%B1%D0%B0%D0%B7%D0%BE%D0%B2%D0%B8%D0%B9-%D0%BA%D1%83%D1%80%D1%81-qa
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6195-1085&mode=design&t=7Cibxr7Nu6LDfxKC-0

First step environment: https://www.qax-camp.com.ua/programs/
![Курси в записі_](https://github.com/scholokov/qax-portal-2/assets/109460500/7f63080a-3827-4414-aee4-df027f85e420)

Second step environment: https://www.qax-camp.com.ua/courses/q6-basic/
![Базовий курс QA](https://github.com/scholokov/qax-portal-2/assets/109460500/76ba80d5-b6fa-4059-9c01-6762c5cbcfd6)

Third step environment: https://www.qax-camp.com.ua/product/basic-qa/
![Базовий курс QA_](https://github.com/scholokov/qax-portal-2/assets/109460500/19d72a50-b86d-4e4e-9c54-6fc3a37c9fe3)

Fourth step environment: https://www.qax-camp.com.ua/checkout/
![Базовий курс QA_оформлення](https://github.com/scholokov/qax-portal-2/assets/109460500/79a733f8-8c10-4ee0-bbdd-d4b6e668b4e6)

**Comment by ODrobik** [comment]
verified
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/1dbe0baf-f3c1-47bc-9aca-b1aa097c5cad)
