### ISSUE TITLE
Recruitment - "Introduction to Recruitment" PREVIEW-PHOTO is different from the course preview photo 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#129]
Steps To Reproduce:
1. Open the https://portal.qax-camp.com.ua/courses/recruiter-program/lessons/introduction-2/
2. Pay attention to the PREVIEW PHOTO 

Actual result: The preview photo is **different** from the course preview photo 
Expected result: The preview photo **is the same as** the course preview photo 
<img width="1440" alt="Снимок экрана 2022-09-21 в 11 27 53 AM" src="https://user-images.githubusercontent.com/110661667/191457564-2cb046fa-55a9-46bd-9f2a-62bb61290dc6.png">
<img width="1440" alt="Снимок экрана 2022-09-21 в 11 40 07 AM" src="https://user-images.githubusercontent.com/110661667/191457782-bf4f076c-9230-4a5e-a366-f899b93b9442.png">
<img width="1440" alt="Снимок экрана 2022-09-21 в 11 41 28 AM" src="https://user-images.githubusercontent.com/110661667/191458069-ed9855bd-279c-42cd-8785-e590120ee456.png">

**Comment by scholokov** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
