### ISSUE TITLE
Product - Check proof of purchase on the “Основи проектного менеджменту” page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1290]
We need to check proof of purchase on the “Основи проектного менеджменту” page.
Please check availability of requirements, functional compliance and design compliance.
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%B8-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BC%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%BC%D0%B5%D0%BD%D1%82%D1%83
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6195-1085&mode=design&t=7Cibxr7Nu6LDfxKC-0

First step environment: https://www.qax-camp.com.ua/programs/
![Курси в записі](https://github.com/scholokov/qax-portal-2/assets/109460500/e53ed675-a5df-45fb-97bb-8696081e0dde)

Second step environment: https://www.qax-camp.com.ua/courses/pm-basics/
![Основи проектного менеджменту](https://github.com/scholokov/qax-portal-2/assets/109460500/acad8254-f9b7-4e20-b053-d3c98f326880)

Third step environment: https://www.qax-camp.com.ua/product/pm-basic/
![Основи проектного менеджменту_](https://github.com/scholokov/qax-portal-2/assets/109460500/70fb5d02-2178-4fb4-9ecf-0e8abb46c93b)

Fourth step environment: https://www.qax-camp.com.ua/checkout/
![Основи проектного менеджменту_оформлення](https://github.com/scholokov/qax-portal-2/assets/109460500/ddbe8a3c-8e63-4fc9-9786-c8e77da3420f)

**Comment by ODrobik** [comment]
verified
