### ISSUE TITLE
Lessons - Events - Check lesson and event for "JSON vs XML vs HTML" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1291]
We need to check lesson and event for "JSON vs XML vs HTML" page.
Please check availability of requirements, functional compliance and design compliance.
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#web--mobile

Environment lesson: https://www.qax-camp.com.ua/courses/web-mobile/lessons/json-vs-xml-vs-html/
![JSON vs XML vs HTML](https://github.com/scholokov/qax-portal-2/assets/109460500/0719eb6c-e039-4faa-8c0f-f812cd2a940f)

Environment event: https://www.qax-camp.com.ua/events/json-vs-xml-vs-html/
![JSON vs XML vs HTML_Event](https://github.com/scholokov/qax-portal-2/assets/109460500/dc0b5072-5e95-4161-913d-97de70a802f0)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
verified
