### ISSUE TITLE
Lessons - "Traceability matrix" / Missed Video's preview in the accordion "Traceability matrix – Юля Рудченко"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1292]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/testing/lessons/traceability-matrix/
2. Open accordion "Traceability matrix – Юля Рудченко".
3. Pay attention to the absence of the Video's preview.

**Actual result:**
 Missed Video's preview in the accordion "Traceability matrix – Юля Рудченко".

**Expected result:**
The video's preview in the accordion "Traceability matrix – Юля Рудченко" is present.

Additional information:
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/4f2f68e2-36bb-4bde-84d8-3c9e72bcac6b)

**Comment by GNatala** [comment]
#933

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
