### ISSUE TITLE
Lessons - Check lesson for "HTML&CSS Основи" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1293]
We need to check lesson for "HTML&CSS Основи" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/%d1%82%d0%b8%d0%bc%d1%87%d0%b0%d1%81%d0%be%d0%b2%d0%b8%d0%b9-%d0%b4%d0%be%d1%81%d1%82%d1%83%d0%bf-%d0%b4%d0%bb%d1%8f-%d0%bf%d0%b0%d0%ba%d0%b5%d1%82%d1%96%d0%b2-medmax/lessons/basic-html-for-qa/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#web--mobile
![HTML CSS Основи](https://github.com/scholokov/qax-portal-2/assets/109460500/b577f9f4-a19f-4739-be85-55619b8cd0df)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
passed
