### ISSUE TITLE
"Безкоштовний тестовий період" course page - "Якщо не зрозуміло що робити далі" accordeon - Picture is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1297]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/courses/trial/
2. Open "Якщо не зрозуміло що робити далі" accordeon
3. Pay attention to the lack of a picture

**Actual Result**
Picture is missing

**Expected Result**
Picture is present

**Additional information**
https://www.qax-camp.com.ua/courses/trial/ (Check the PC version)

**Enviroments**
Android 8.1.0, Chrome 116.0.5845.173, Firefox 117.1.0
![photo_2023-09-19_18-24-06](https://github.com/scholokov/qax-portal-2/assets/95171672/e88fb792-3acf-45f3-8cd0-455305907157)
![photo_2023-09-19_18-24-11](https://github.com/scholokov/qax-portal-2/assets/95171672/2624c5bc-cd4f-4d7d-9594-ce0797d4def8)

**Comment by DmitriiNasonov** [comment]
#1227

**Comment by scholokov** [comment]
please retest

**Comment by DmitriiNasonov** [comment]
retested. bug isn't reproduced
