### ISSUE TITLE
Checkout/The "Tелефон" and "Email" fields are not displayed on the same level in the "Платіжні дані" block with opposite lines in the "Ваше замовлення" block

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1299]
Steps to Reproduce:

1. Open page https://www.qax-camp.com.ua/checkout/
2. Scroll down to the "Tелефон" and "Email" fields in the "Платіжні дані" block
3. Pay attention to the location "Tелефон" and "Email" fields in the "Платіжні дані" block with opposite lines in the "Ваше замовлення" block

Actual Result:
The "Tелефон" and "Email" fields are not displayed on the same level in the "Платіжні дані" block with opposite lines in the "Ваше замовлення" block

Expected Result:
The "Tелефон" and "Email" fields are displayed on the same level in the "Платіжні дані" block with opposite lines in the "Ваше замовлення" block

Environment: 
OS: Windows 10 Pro (x64),
Browser: Google Chrome v 117.0.5938.89 (x64)
Viewport: 1920x1080px

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/2d90331a-8657-4cc2-8ceb-2d7f6e42d168)

**Comment by ODrobik** [comment]
#769

**Comment by poroskundenys** [comment]
готово

**Comment by ODrobik** [comment]
verified
