### ISSUE TITLE
Course: Выпадающий список

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#13]
Подумать над внешним видом выпадающего списка

https://portal.qax-camp.com.ua/courses/recruiter-program/

![image](https://user-images.githubusercontent.com/22824947/183055785-d12af7b5-3017-4dc4-b8ac-7095dca3fc2a.png)
![image](https://user-images.githubusercontent.com/22824947/183055834-6e1508b8-15e5-4eb8-aa49-3679893ced10.png)
![image](https://user-images.githubusercontent.com/22824947/183055888-ecf65735-24d3-40b0-91f5-dc9133275860.png)
![image](https://user-images.githubusercontent.com/22824947/183056012-6e689221-f0a2-4235-b827-7b6f50d96865.png)

**Comment by ABatalov** [comment]
Ready for testing:  https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A1036 
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=564%3A52

**Comment by KaterinaNimenko35** [comment]
verified
