### ISSUE TITLE
Recruitment - "Разновидности бизнесов" PREVIEW-PHOTO is different from the course preview photo 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#130]
Steps To Reproduce:
1. Open the https://portal.qax-camp.com.ua/courses/recruiter-program/lessons/differense-in-type-of-it-comanies/
2. Pay attention to the  PREVIEW PHOTO 

Actual result: The preview photo is different from the course preview photo 
Expected result: The preview photo is the same as the course preview photo 
<img width="1440" alt="Снимок экрана 2022-09-21 в 11 44 35 AM" src="https://user-images.githubusercontent.com/110661667/191458747-4982ec2c-6ee5-45a4-9287-7c09cefbfefe.png">
<img width="1440" alt="Снимок экрана 2022-09-21 в 11 41 28 AM" src="https://user-images.githubusercontent.com/110661667/191458782-1972b459-c153-49e7-8b5a-440ffa4e6dd0.png">
<img width="1440" alt="Снимок экрана 2022-09-21 в 11 40 07 AM" src="https://user-images.githubusercontent.com/110661667/191458806-a5470b1e-72d1-42eb-b977-ba8373095c12.png">

**Comment by scholokov** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
