### ISSUE TITLE
Slug of the lesson "Параметри Екрану" is "screens"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1300]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/courses/web-mobile/lessons/screens/
2. Pay attention to the lesson's slug in URL

**Actual Result**
Slug of the lesson "Параметри Екрану" is "screens"

**Expected Result**
Slug of the lesson "Параметри Екрану" is "introduction"

**Additional information**
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA

**Enviroments**
Windows 10, Chrome 117.0.5938.89 (64 bit)
Android 8.1.0, Chrome 116.0.5845.173
![1 7 1  Урок · scholokov_qax-portal-2 Wiki - Google Chrome 20 09 2023 13_52_58](https://github.com/scholokov/qax-portal-2/assets/95171672/c0b36c05-5169-4f6f-b525-d04a233a571a)
![photo_2023-09-20_13-54-57](https://github.com/scholokov/qax-portal-2/assets/95171672/242db2aa-e4e2-421a-a020-f9c4bc3cd96a)

**Comment by DmitriiNasonov** [comment]
#940

**Comment by scholokov** [comment]
виправлено у вимогах

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
