### ISSUE TITLE
Checkout/The "CVV" field "Деталі оплати" block are displayed on the same level with "Термін дії" field

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1302]
Steps to Reproduce:

1. Open page https://www.qax-camp.com.ua/checkout/
2. Swipe down to the "CVV" in the "Деталі оплати" block
3. Pay attention to the location "СVV" field in the "Деталі оплати" block 

**Actual Result:**
The "CVV" field "Деталі оплати" block are displayed on the same level with "Термін дії" field
**Expected Result:**
The "CVV" field "Деталі оплати" block are displayed under "Термін дії" field

Environment: Samsung   A31
OS: Android 12 
Browser:  Google Chrome 116.0.5845.172

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/f2585d11-2ddb-4e2b-8320-40f160425ac1)

**Comment by ODrobik** [comment]
#769

**Comment by poroskundenys** [comment]
готово

**Comment by ODrobik** [comment]
verified
