### ISSUE TITLE
GitHub Project - Portal - Task/Issue - "Component" - Component "Achievement" is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1304]
**Steps of reproducing**
1. Open https://github.com/users/scholokov/projects/1/views/5
2. Open any issue or task
3. Click to "Component" block

**Actual Result**
Component "Achievement" is missing

**Expected Result**
Component "Achievement" is present

**Additional information**
https://www.qax-camp.com.ua/ach-travel/

**Enviroments**
Windows 10, Chrome 117.0.5938.89 (64 bit)
![Achievement - _ВиБАГливий_ - The test result comes before verification · Portal - Google Chrome 20 09 2023 14_48_50](https://github.com/scholokov/qax-portal-2/assets/95171672/4e2fe6ab-d124-4bca-aadd-b06bf7b8c434)

**Comment by DmitriiNasonov** [comment]
#1200

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
