### ISSUE TITLE
Events - Check the future event on the "STLC очима тестувальника" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1306]
We need to check the future event on the "STLC очима тестувальника" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/events/stlc_qa_vision/
![STLC очима тестувальника](https://github.com/scholokov/qax-portal-2/assets/109460500/e87a5bff-f2dc-4672-beec-82454b8f7c46)

**Comment by GNatala** [comment]
verified
