### ISSUE TITLE
Events - Check the future event on the "CI / CD" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1307]
We need to check the future event on the "CI / CD" page.
Please check availability of requirements, functional compliance and design compliance.

Environment: https://www.qax-camp.com.ua/events/ci-cd/

![CI  CD](https://github.com/scholokov/qax-portal-2/assets/109460500/3f94b4a9-ef9f-472e-b312-15317417e350)

**Comment by GNatala** [comment]
verified
