### ISSUE TITLE
Tests - Реалізувати форматування шрифтів згідно з дизайном

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#1308]
шрифти:
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=5699-913&mode=design&t=SnyUaDVOj79DuyhU-0

таблиця:
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=390-12775&mode=design&t=SnyUaDVOj79DuyhU-0

приклад:
https://www.qax-camp.com.ua/courses/req-test/lessons/req-test-doc/quizzes/req-test-docs/

**Comment by poroskundenys** [comment]
готово

**Comment by DmitriiNasonov** [comment]
Testing completed
