### ISSUE TITLE
Events - Check the block "Найближча подія" on the Home page 

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1309]
We need to check the block "Найближча подія" on the Home page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/home-2/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6704-1434&mode=design&t=vveuarIRTx21TfTc-0
![Найближча подія](https://github.com/scholokov/qax-portal-2/assets/109460500/5edc7a7c-4f67-433d-bf4a-1a000fe90c07)

**Comment by DmitriiNasonov** [comment]
Testing completed
