### ISSUE TITLE
Recruitment - "Начало работы с вакансией" PREVIEW-PHOTO is different from the course preview photo 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#131]
Steps To Reproduce:
1. Open the https://portal.qax-camp.com.ua/courses/recruiter-program/lessons/lesson_4/
2. Pay attention to the  PREVIEW PHOTO 

Actual result: The preview photo is **different** from the course preview photo 
Expected result: The preview photo is the **same as** the course preview photo 
<img width="1440" alt="Снимок экрана 2022-09-21 в 11 50 01 AM" src="https://user-images.githubusercontent.com/110661667/191459948-e207cb7a-2936-42d0-b240-4a01402e5680.png">
<img width="1440" alt="Снимок экрана 2022-09-21 в 11 40 07 AM" src="https://user-images.githubusercontent.com/110661667/191459998-4707c07e-bc83-4076-b73a-d9149450df48.png">
<img width="1440" alt="Снимок экрана 2022-09-21 в 11 41 28 AM" src="https://user-images.githubusercontent.com/110661667/191460026-0f2800f1-e950-4600-9d30-c8085d063866.png">

**Comment by scholokov** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
