### ISSUE TITLE
Lesson "Ролі та артефакти у проектній команді" / Missed access to the lesson's presentation in archive - Юлія

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1310]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-roles/
2. Scroll down to the archive "Архів – Роли и артефакты в проектной команде – Юля".
3. Open it.
4. Pay attention to the presentation.

**Actual result:**
There is no access to the lesson's presentation.

**Expected result:**
There is access to the lesson's presentation.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://github.com/scholokov/qax-portal-2/assets/101987790/e8ba7923-d6e3-4f76-be90-80f9271aceea)

**Comment by GNatala** [comment]
#942

**Comment by scholokov** [comment]
виправлено (видалено презентацію)

**Comment by GNatala** [comment]
перевірено
