### ISSUE TITLE
Lesson "SDLC / STLC" / Missed access to the lesson's presentation in archive - Юлія

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1311]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-sdlc-stlc/
2. Scroll down to the archive "Архів – SDLC / STLC – Юля".
3. Open it.
4. Pay attention to the presentation.

**Actual result:**
There is no access to the lesson's presentation.

**Expected result:**
There is access to the lesson's presentation.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/52859eec-ba85-4c66-9221-f5c6fcad5465)

**Comment by GNatala** [comment]
#943

**Comment by scholokov** [comment]
виправлено (видалено презентацію)

**Comment by GNatala** [comment]
перевірено
