### ISSUE TITLE
Calendar / The current date color in the next month is #F66F5D

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1312]
**Steps to reproduce:**

1. Open  https://www.qax-camp.com.ua/calendars/
2. Turn the calendar to the next month.
3. Pay attention to the current date color.

**Actual result:**
The current date color in the next month is #F66F5D.

**Expected result:**
The current date color in the next month is #F7F7F7.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6112-976&mode=design&t=Ef82tSUGZqS6zutk-0

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/f6568314-5ee6-4ba2-84c1-53c108301a08)
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/f9c978b5-a217-427b-8b24-f3b9e9c4fe50)

**Comment by poroskundenys** [comment]
@scholokov нужно обновить плагин Modern Events Calendar. Для сегодняшнего дня добавляется отдельный класс, но почему-то также добавляется и на всех остальных месяцах.  Может в новых версиях нет этого бага.

**Comment by poroskundenys** [comment]
готово

**Comment by GNatala** [comment]
passed
