### ISSUE TITLE
"Наступна подія" block - Font size of the date and time of the event is 18 px

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1313]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/home-2/
2. Pay attention to font size of the date and time of the event

**Actual Result**
Font size of the date and time of the event is 18 px

**Expected Result**
Font size of the date and time of the event is 14 px

**Additional information**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=7051-3394&mode=design&t=v9BlCPRGB587MqSY-0

**Enviroments**
Windows 10 (Devtools), Chrome 117.0.5938.92 (64 bit)
![QAX Camp - Google Chrome 25 09 2023 17_20_27](https://github.com/scholokov/qax-portal-2/assets/95171672/78c0bb17-836d-4148-a46a-bd2ef0f1a615)

**Comment by DmitriiNasonov** [comment]
#1309

**Comment by DmitriiNasonov** [comment]
#1309

**Comment by DmitriiNasonov** [comment]
#1128

**Comment by poroskundenys** [comment]
готово

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
