### ISSUE TITLE
"Найближча подія" block - Width of the "Найближча подія" block is 1240 px

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1314]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/home-2/
2. Check the width of the "Найближча подія" block

**Actual Result**
Width of the "Найближча подія" block is 1240 px

**Expected Result**
Width of the "Найближча подія" block is 960 px

**Additional information**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6704-1435&mode=design&t=ZcFmb117OSldizue-0

**Enviroments**
Windows 10, Chrome 117.0.5938.92 (64 bit)
![QAX Camp - Google Chrome 27 09 2023 15_34_45](https://github.com/scholokov/qax-portal-2/assets/95171672/c73b167b-8f58-48fd-a109-3fc31d240042)
![QAX Camp - Google Chrome 27 09 2023 15_34_48](https://github.com/scholokov/qax-portal-2/assets/95171672/2a44d63e-ce2d-4769-8749-a80d01a67e2a)

**Comment by DmitriiNasonov** [comment]
#1309

**Comment by poroskundenys** [comment]
готово

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
