### ISSUE TITLE
Essay - Розробити сторінку - Розбір виконаного завдання

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#1315]
Essay - Розробити сторінку - Розбір виконаного завдання

<img width="343" alt="image" src="https://github.com/scholokov/qax-portal-2/assets/22824947/8187985d-5ecf-4925-8fa1-09af12046509">

<img width="392" alt="image" src="https://github.com/scholokov/qax-portal-2/assets/22824947/0884fe2f-2ba0-45c3-9990-edbacdd1d6c1">

**Comment by AlonaSarapina** [comment]
ready for testing 
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=9160%3A1524&mode=design&t=DpDNyCOFBGj03UY0-1

**Comment by ABatalov** [comment]
@AlonaSarapina need to create tablet and mobile version

**Comment by AlonaSarapina** [comment]
added tablet and mobile version
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=9160%3A1524&mode=design&t=Q7ZmhC2npab3erbu-1

**Comment by ButKoff** [comment]
#1470
