### ISSUE TITLE
Awards - Імплементувати дизайн сторінок

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#1316]
Елемент "Нагороди" має 2 дизайни. І буде використовуватись на різних сторінках.
створити можливість вибору поточного дизайну (одразу обидва на одній сторінці використовуватися не будуть)

Invarement: https://www.qax-camp.com.ua/ach-travel/
                     https://www.qax-camp.com.ua/arc/

Figma (Awards summary): https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=8846-148&mode=design&t=6jZcU5QdxRVQQCY1-0
![Awards summary](https://github.com/scholokov/qax-portal-2/assets/109460500/1a9de553-c9ee-4651-961f-188534c34867)

Figma (Awards): https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=8645-188&mode=design&t=6jZcU5QdxRVQQCY1-0
![Awards](https://github.com/scholokov/qax-portal-2/assets/109460500/54a7cdbe-b50b-47a6-9970-9bef9fd1380c)

**Comment by ABatalov** [comment]
Still in Progress

**Comment by poroskundenys** [comment]
Для awards summary нужно добавлять в шорткод параметр layout="none" до того что уже было https://prnt.sc/bKROWlB9aQxj

**Comment by poroskundenys** [comment]
Для Awards нужно добавлять в шорткод параметр columns="4" toggle="no" до того что уже было https://prnt.sc/AL8Sg29mFXKW

**Comment by poroskundenys** [comment]
Готово

**Comment by DmitriiNasonov** [comment]
Testing completed
