### ISSUE TITLE
Нагорода - детальна сторінка

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#1317]
Нагороди - Блок нагород - Нагорода

Розробити окрему сторінку нагорода
на сторінці буде лише одна нагорода, та опис:

текстовий опис як її отримати нагороду
"кроки отримання нагороди". активний елемент, куди пицнути, щоб занести досягнуті результати

Invarement: https://www.qax-camp.com.ua/qa-fundamentals/%d1%82%d0%b5%d1%81%d1%82%d1%83%d0%b2%d0%b0%d0%bb%d1%8c%d0%bd%d0%b8%d0%ba-%d1%85%d1%82%d0%be-%d1%86%d0%b5/

![image](https://github.com/scholokov/qax-portal-2/assets/22824947/d4d92bc3-8642-45af-8615-d1d779120394)

https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=9014-82&mode=design&t=ggFmkUQGtnFNXpn4-0

**Comment by poroskundenys** [comment]
Готово. В настройках нужно этот параметр всегда выбирать https://prnt.sc/0Q4ePOSz4cBb

**Comment by DmitriiNasonov** [comment]
Testing completed
