### ISSUE TITLE
Lessons - Check lesson for "Типи Web-атак" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1318]
We need to check lesson for "Типи Web-атак" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://t.qax-camp.com.ua/courses/web-mobile/lessons/types-of-web-attack/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#web--mobile
![Типи Web-атак](https://github.com/scholokov/qax-portal-2/assets/109460500/315e4984-8906-4aed-8125-f1e5ac212908)

**Comment by ButKoff** [comment]
#664

**Comment by DmitriiNasonov** [comment]
Testing completed
