### ISSUE TITLE
Lessons - Check lesson for "STLC очима тестувальника" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1319]
We need to check lesson for "STLC очима тестувальника" page: https://www.qax-camp.com.ua/courses/testing/lessons/stlc-qa-vision/
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/%d1%82%d0%b8%d0%bc%d1%87%d0%b0%d1%81%d0%be%d0%b2%d0%b8%d0%b9-%d0%b4%d0%be%d1%81%d1%82%d1%83%d0%bf-%d0%b4%d0%bb%d1%8f-%d0%bf%d0%b0%d0%ba%d0%b5%d1%82%d1%96%d0%b2-medmax/lessons/stlc-qa-vision/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F
![STLC очима тестувальника](https://github.com/scholokov/qax-portal-2/assets/109460500/7ec9a9c3-b024-445d-ae6a-49d956fd8d23)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
verified
