### ISSUE TITLE
 Recruitment - "Технический ликбез " PREVIEW-PHOTO is different from the course preview photo 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#132]
Steps To Reproduce:
1. Open the https://portal.qax-camp.com.ua/courses/recruiter-program/lessons/technical_lecture_for_recruiters/
2. Pay attention to the  PREVIEW PHOTO 

Actual result: The preview photo is **different** from the course preview photo 
Expected result: The preview photo is the **same as** the course preview photo 
<img width="1440" alt="Снимок экрана 2022-09-21 в 11 53 31 AM" src="https://user-images.githubusercontent.com/110661667/191460755-02c92134-a6c1-4481-b645-5a39a0cb48fa.png">
<img width="1440" alt="Снимок экрана 2022-09-21 в 11 40 07 AM" src="https://user-images.githubusercontent.com/110661667/191460781-b337bfc7-25c2-4bd9-9f38-8fdf1bdc6eb2.png">
<img width="1440" alt="Снимок экрана 2022-09-21 в 11 41 28 AM" src="https://user-images.githubusercontent.com/110661667/191460796-8446e822-cc4e-488f-b936-257b2f2a5676.png">

**Comment by scholokov** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
