### ISSUE TITLE
Lesson "Вимоги: навіщо їх тестувати" / The button "Next  Урок" is in English

### ISSUE THREAD

**Issue by Aleksandrkobets99** [scholokov/qax-portal-2#1325]
**Steps to reproduce:**

1. Open page: https://www.qax-camp.com.ua/courses/testing/lessons/q6-requirements/
2. Find button "Next Урок"
3. Look at the button "Next  Урок"

**Actual result:** The button "Next  Урок" is in English
**Expected result:** The button "Next  Урок" is in Ukrainian

**Requirements:** https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F

**Environment:**
Windows 10
Google Chrome v 117.0.5938.132

**Attachment:**
![chrome_wAcSxpmEgq — копия](https://github.com/scholokov/qax-portal-2/assets/126480322/d310a431-154d-44e0-8707-6c38858ebd87)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/qax-portal-2/assets/88647733/bedd6760-b84e-402c-9e79-6f333d257ba6)

**Comment by Aleksandrkobets99** [comment]
#919

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
