### ISSUE TITLE
Recruitment - "Продолжение работы" PREVIEW-PHOTO is different from the course preview photo 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#133]
Steps To Reproduce:
1. Open the https://portal.qax-camp.com.ua/courses/recruiter-program/lessons/lesson_5_continue-to-work-with-vacancy/
2. Pay attention to the  PREVIEW PHOTO 

Actual result: The preview photo is **different** from the course preview photo 
Expected result: The preview photo is the **same as** the course preview photo 
<img width="1440" alt="Снимок экрана 2022-09-21 в 11 56 10 AM" src="https://user-images.githubusercontent.com/110661667/191461484-0cbc5d29-d2ed-4d91-ab61-f7171c997b56.png">
<img width="1440" alt="Снимок экрана 2022-09-21 в 11 40 07 AM" src="https://user-images.githubusercontent.com/110661667/191461507-9fb5906a-d354-4fdf-ab4a-df920faf61bd.png">
<img width="1440" alt="Снимок экрана 2022-09-21 в 11 41 28 AM" src="https://user-images.githubusercontent.com/110661667/191461532-d7f2869e-fce5-4bdd-b2b7-af45489fd503.png">

**Comment by scholokov** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
