### ISSUE TITLE
 Recruitment - «Сорсинг» PREVIEW-PHOTO is different from the course preview photo 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#134]
Steps To Reproduce:
1. Open the https://portal.qax-camp.com.ua/courses/recruiter-program/lessons/sourcing_sourcing-technologies/
2. Pay attention to the  PREVIEW PHOTO 

Actual result: The preview photo is different from the course preview photo 
Expected result: The preview photo is the same as the course preview photo 
<img width="1440" alt="Снимок экрана 2022-09-21 в 11 58 53 AM" src="https://user-images.githubusercontent.com/110661667/191462065-1e9383e8-02dd-42e5-9892-135c1279379e.png">
<img width="1440" alt="Снимок экрана 2022-09-21 в 11 40 07 AM" src="https://user-images.githubusercontent.com/110661667/191462087-35e8c918-6675-4a8e-bead-a1f7c6c975b3.png">
<img width="1440" alt="Снимок экрана 2022-09-21 в 11 41 28 AM" src="https://user-images.githubusercontent.com/110661667/191462119-e75fbac4-c4e1-411e-9e2f-017a7b9c9708.png">

**Comment by scholokov** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
