### ISSUE TITLE
The word "по-друге" must be capitalized. There must be a colon at the end of the sentence - lesson "Топ питання на тех співбесіді..." - course "Інструменти пошуку вакансій. Підготовка до проходження співбесіди. Створення СV"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#1343]
**STR**
1. Open https://www.qax-camp.com.ua/courses/cv/lessons/interview-questions/#1  / you should be login 
2. Pay attention to the phrase "по-друге – кілька варіантів, щоб наштовхнути на думки, але не більше"  

**ACTUAL RESULT**
The word "по-друге" is shown with a small letter; 
There is NO colon ":" at the end of the sentence.

**EXPECTED RESULT**
The phrase look like "**П**о-друге – кілька варіантів, щоб наштовхнути на думки, але не більше**:**" 

![2oiil6caV6](https://github.com/scholokov/qax-portal-2/assets/109384052/0f3a8eeb-9a16-4976-8e5f-84fbb5e5d199)

**Comment by BatalovaOlha** [comment]
#1119

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
