### ISSUE TITLE
Double marking in the list - block "1. Уявіть ситуацію, коли ви повідомили про ПОМИЛКУ..." - lesson "Топ питання на тех співбесіді..." - course "Інструменти пошуку вакансій. Підготовка до проходження співбесіди. Створення СV"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#1344]
**STR**

1. Open https://www.qax-camp.com.ua/courses/cv/lessons/interview-questions/#1 / you should be login;
2. Pay attention to the phrase "по-друге – кілька варіантів, щоб наштовхнути на думки, але не більше".

**ACTUAL RESULT**
The list is marked double - with points and numbers

**EXPECTED RESULT**
There is only one type for marking in the list 

![3WWsElmJkO](https://github.com/scholokov/qax-portal-2/assets/109384052/f7db622d-abf0-477a-8368-db414efb42d5)

**Comment by BatalovaOlha** [comment]
#1119

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
