### ISSUE TITLE
The name of block "15. Риски в тестировании" in russian- lesson "Топ питання на тех співбесіді..." - course "Інструменти пошуку вакансій. Підготовка до проходження співбесіди. Створення СV"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#1345]
**STR**

1. Open https://www.qax-camp.com.ua/courses/cv/lessons/interview-questions/#15  / you should be login;
2. Pay attention to the language of the name of the block

ACTUAL RESULT
The name of the block looks like "Риски в тестировании"

EXPECTED RESULT
The name of the block should look like "Ризики якості" as in the preview list

![L5yfb8adwI](https://github.com/scholokov/qax-portal-2/assets/109384052/11f0119f-0202-425d-93f2-c0106cc11789)
![smuDxT4LMb](https://github.com/scholokov/qax-portal-2/assets/109384052/5007bfe2-b956-4681-ac01-1f5ce9f983a8)

**Comment by BatalovaOlha** [comment]
#1119

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
