### ISSUE TITLE
Lesson "Ролі та артефакти у проектній команді" / Names of the accordions with archives are written in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1346]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-roles/
2. Scroll down to the archives "Архів – Роли и артефакты в проектной команде – Юля", "Архів – Роли и артефакты в проектной команде – Максим"
5. Pay attention to the language of the names of the accordions.

**Actual result:**
Names of the accordions with archives:  "Архів – **Роли и артефакты в проектной команде** – Юля", "Архів – **Роли и артефакты в проектной команде** – Максим" are written in russian.

**Expected result:**
Names of the accordions with archives:  "Архів – **Роли и артефакты в проектной команде** – Юля", "Архів – **Роли и артефакты в проектной команде** – Максим" are written in Ukrainian.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/718ccb4c-6b31-45eb-b24c-37050053b26e)

**Comment by GNatala** [comment]
#942

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
