### ISSUE TITLE
Lessons - "Traceability matrix" / Extra symbol "\" is before the text "Специфіка оцінки покриття за допомогою матриць трасування".

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1347]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/testing/lessons/traceability-matrix/
2. Open accordion "Traceability matrix – Юля Рудченко".
3. Scroll down the text to the chapter "Специфіка оцінки покриття за допомогою матриць трасування".
4. Pay attention to the extra symbol \  before the text "Специфіка оцінки покриття за допомогою матриць трасування".

**Actual result:**
 Extra symbol \ is before the text "Специфіка оцінки покриття за допомогою матриць трасування".

**Expected result:**
Extra symbol \ before the text "Специфіка оцінки покриття за допомогою матриць трасування" is absent.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/705da488-cfd7-4bbd-a6a2-a6fc29e7f545)

**Comment by GNatala** [comment]
#933

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
