### ISSUE TITLE
Recruitment - «HR и Рекрутмент» extra PREVIEW-PHOTO 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#135]
Steps To Reproduce:
1. Open the https://portal.qax-camp.com.ua/courses/recruiter-program/lessons/hr-%d0%b8-%d1%80%d0%b5%d0%ba%d1%80%d1%83%d1%82%d0%bc%d0%b5%d0%bd%d1%82-%d1%84%d1%83%d0%bd%d0%ba%d1%86%d0%b8%d1%8f/
2. Pay attention to the first PREVIEW PHOTO 

Actual result: there are two photos in the preview photo  
Expected result: one photo that matches the preview photo of the course
<img width="1440" alt="Снимок экрана 2022-09-21 в 12 05 12 PM" src="https://user-images.githubusercontent.com/110661667/191463496-bc601b7c-3de7-40ba-bdd3-cd7fdbda3d9b.png">
<img width="1440" alt="Снимок экрана 2022-09-21 в 11 40 07 AM" src="https://user-images.githubusercontent.com/110661667/191463531-a77edc8c-da73-4329-8a05-9039fcbc8ce5.png">
<img width="1440" alt="Снимок экрана 2022-09-21 в 11 41 28 AM" src="https://user-images.githubusercontent.com/110661667/191463558-dac52a6c-114e-42f2-9ee8-ef981e18c8b9.png">
<img width="1440" alt="Снимок экрана 2022-09-21 в 12 06 04 PM" src="https://user-images.githubusercontent.com/110661667/191463700-459bc714-cefe-4083-9199-24ebb00b49c9.png">

**Comment by scholokov** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
