### ISSUE TITLE
Certificate - Create a new Сertificate design

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1350]
We need to create a new Сertificate design.

![Сertificate](https://github.com/scholokov/qax-portal-2/assets/109460500/a90ce934-2f68-43a4-9fd5-fb385f9283cc)

**Comment by AlonaSarapina** [comment]
ready for testing 
https://www.figma.com/file/zv1PXjRPmCwXg6Vh3A68zb/Certificate?type=design&node-id=0%3A1&mode=design&t=pxiMj3uZx5EdvOcI-1

**Comment by ButKoff** [comment]
#1609

**Comment by GNatala** [comment]
verified

**Comment by AlonaSarapina** [comment]
update - [link ](https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=9618%3A115&mode=design&t=4bK3BWuqG7L9cd0X-1)
