### ISSUE TITLE
Events - Check the future event on the "QA Звітність" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1351]
We need to check the future event on the "QA Звітність" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/events/qa-report/

![QA Звітність](https://github.com/scholokov/qax-portal-2/assets/109460500/e46ed2c4-8217-4fb7-97fc-8bda6b28a993)

**Comment by GNatala** [comment]
verified
