### ISSUE TITLE
Lessons - "Коды состояния HTTP и как их интерпретировать" / The slug of the lesson is in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1354]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/web-mobile/lessons/%d0%ba%d0%be%d0%b4%d1%8b-%d1%81%d0%be%d1%81%d1%82%d0%be%d1%8f%d0%bd%d0%b8%d1%8f-http-%d0%b8-%d0%ba%d0%b0%d0%ba-%d0%b8%d1%85-%d0%b8%d0%bd%d1%82%d0%b5%d1%80%d0%bf%d1%80%d0%b5%d1%82%d0%b8%d1%80%d0%be/
2. Pay attention to the slug of the lesson.

**Actual result:**
 The slug of the lesson is in russian.

**Expected result:**
The slug of the lesson is in English.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/884a355e-86ed-4454-a868-3a6dc6ebccdf)

**Comment by GNatala** [comment]
#952

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
