### ISSUE TITLE
Checkout/The "CVV" field is allowed to enter 4 characters in the "Деталі оплати" block of the "Оформлення замовлення"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1355]
Steps to Reproduce:

1. Open page https://www.qax-camp.com.ua/checkout/
2. Scroll down to the "CVV" in the "Деталі оплати" block
3. Pay attention to the "СVV" field in the "Деталі оплати" block

Actual Result:
The "CVV" field is allowed **to enter 4 characters** in the "Деталі оплати" block of the "Оформлення замовлення"
Expected Result:
The "CVV" field is allowed **to enter 3 characters** in the "Деталі оплати" block of the "Оформлення замовлення"

Environment:
OS: Windows 10 Pro (x64),
Browser: Google Chrome v 117.0.5938.89 (x64)
Viewport: 1920x1080px

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/f9339637-8132-475a-a004-4ce550a3c320)

**Comment by ODrobik** [comment]
#769

**Comment by poroskundenys** [comment]
Сколько цифр должно быть в CVV?
Для большинства карт (Visa, MasterCard, банковские карты и т. д.) это последние три цифры числа, напечатанного в поле подписи на обратной стороне карты. Для карт American Express (AMEX) это, как правило, четырехзначный код на лицевой стороне карты.

**Comment by scholokov** [comment]
мені здавалося для всіх має бути 3. якщо є варіанти з чотирма, то хай так і буде...

**Comment by ODrobik** [comment]
is not an error
