### ISSUE TITLE
In "about us page", text font-weight: 500

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/qax-portal-2#136]
Steps to reproduce:
1. Open design in Figma https://www.figma.com/file/JwKf4NLnNlzrSCaBlbhKu4/QAX-Camp-(Copy)?node-id=4542%3A7252
2. Open the "about us page" https://portal.qax-camp.com.ua/about-us/
3. Pay attention to the text font-weight

Actual result:
- text font-weight: 500
- text with background color font-weight: 500

Expected result: 
- text font-weight: 300
- text with background color font-weight: 400

![chrome_aTfYZYc6yT](https://user-images.githubusercontent.com/57997443/191464662-00d2c254-960d-407b-a58a-e974e1d9bc64.png)

![chrome_aTfYZYc6yT копия](https://user-images.githubusercontent.com/57997443/191466294-5c3924bc-d040-4541-934f-d2aa68f4c8ec.png)

**Comment by DmytroMarkulych** [comment]
@dmitryylev краще вкажіть не "should be change", а фактично вкажіть на помилку, що font-weight: 500

**Comment by dmitryylev** [comment]
changed

**Comment by poroskundenys** [comment]
Есть дизайн для текста на сайте. https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A12776.
Жирность берется с него. Думаю что переделывать стили для отдельной страницы не стоит. Можно переделать текущий дизайн с новой жирностью, чтобы эту проблему в будущем снова не решали.

**Comment by dmitryylev** [comment]
verified
