### ISSUE TITLE
Events -"STLC очима тестувальника"/ The title of the element "Local Time" is written in English

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1362]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/events/stlc_qa_vision/
2. Pay attention to the element "Local Time".

**Actual result:**
The title of the element "Local Time" is written in English.

**Expected result:**
The title of the element "Local Time" is written in Ukrainian -  "Місцевий час".

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6076-950&mode=design&t=5CaoXyeDza2bdayO-0

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/2aa52ca6-6b0c-4e22-8fd1-568d6157c431)
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/0d492974-4774-468f-bc3d-9a9a0082ae04)

**Comment by GNatala** [comment]
#1306

**Comment by poroskundenys** [comment]
готово

**Comment by GNatala** [comment]
перевірено
