### ISSUE TITLE
Events - "QA Звітність" page/ Elements "Days", "Hours", "Minutes", "Seconds" are written in English

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1363]
**Steps to reproduce:**

1. Open: https://www.qax-camp.com.ua/events/qa-report/
2. Pay attention to the elements "Days", "Hours", "Minutes", "Seconds".

**Actual result:**
Elements "Days", "Hours", "Minutes", "Seconds" are written in English.

**Expected result:**
Elements "Days", "Hours", "Minutes", "Seconds" are written in Ukrainian.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6076-950&mode=design&t=5CaoXyeDza2bdayO-0

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/da2ef3f3-5891-4823-a5b9-8d1d5a3b3d45)

**Comment by GNatala** [comment]
#1351

**Comment by poroskundenys** [comment]
готово

**Comment by GNatala** [comment]
перевірено
