### ISSUE TITLE
Events - "QA Звітність" page/ Font color of the elements "+ Add to Google Calendar", "+ iCal / Outlook export" is #F66F5D.

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1364]
**Steps to reproduce:**

1. Open: https://www.qax-camp.com.ua/events/qa-report/
2. Pay attention to the elements "+ Add to Google Calendar", "+ iCal / Outlook export".

**Actual result:**
Font color of the elements "+ Add to Google Calendar", "+ iCal / Outlook export" is  #F66F5D.

**Expected result:**
Font color of the elements "+ Add to Google Calendar", "+ iCal / Outlook export" is  #F7F7F7.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6076-950&mode=design&t=5CaoXyeDza2bdayO-0

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/8b8f4240-64d2-4724-a34d-e9f35b14aa6a)

**Comment by GNatala** [comment]
#1351

**Comment by poroskundenys** [comment]
готово

**Comment by GNatala** [comment]
перевірено
