### ISSUE TITLE
Lesson "IT Vocabulary – АйТі Сленг"/The Logo of the "Процеси" course is not displayed on the Preview of the "IT Vocabulary – АйТі Сленг" lesson 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1370]
Steps to Reproduce:

1. Open page https://www.qax-camp.com.ua/courses/processes/lessons/it-vocabulary/
2. Pay attention to the Logo of the lesson "IT Vocabulary – АйТі Сленг" of the course "Процеси"

Actual Result: The Logo of the "Процеси" course is not displayed on the Preview of the "IT Vocabulary – АйТі Сленг" lesson 
Expected Result: The Logo of the "Процеси" course is displayed on the Preview of the "IT Vocabulary – АйТі Сленг" lesson 

Additional information: https://www.canva.com/design/DAFdjgYP8G4/Fj32w2yMqdZqBcQS1z9ioA/edit

Environment:
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/6ce29a30-ffee-41e7-8efc-0a723da52656)

**Comment by ODrobik** [comment]
#938

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
