### ISSUE TITLE
Lesson "IT Vocabulary – АйТі Сленг"/ The 2nd point of the "Існують деякі модифікації snake_case:" list is displayed to the right of other list items in the "CamelCase, snake_case та інші регістри" section

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1371]
Steps to Reproduce:

1. Open page https://www.qax-camp.com.ua/courses/processes/lessons/it-vocabulary/
2. Scroll down to the "CamelCase, snake_case та інші регістри" section of the lesson
3. Pay attention to the location 2nd point "Існують деякі модифікації snake_case:" list in the "CamelCase, snake_case та інші регістри" section

Actual Result: The 2nd point of the "Існують деякі модифікації snake_case:" list is displayed to the right of other list items 

Expected Result: The 2nd point of the "Існують деякі модифікації snake_case:" list is displayed to the same level as other list points 

Environment:
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/9996ec97-edf1-40fb-a374-a206291971af)

**Comment by ODrobik** [comment]
#938

**Comment by scholokov** [comment]
<img width="632" alt="image" src="https://github.com/scholokov/qax-portal-2/assets/22824947/0b6f4970-dbfa-424c-8cc9-2f20bd8fa29e">
дуже важко читати
інформація в результатах чомусь дублює кроки
в результаті має бути лише сам результат. "де" має бути описано у кроках. в іншому випадку дуже багато тексту і зрозуміти що саме мається на увазі дуже важко

**Comment by ODrobik** [comment]
виправлено

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
