### ISSUE TITLE
Lesson "IT Vocabulary – АйТі Сленг"/The Author of the "IT Vocabulary – АйТі Сленг" lesson is written in English in the End of the page 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1372]
Steps to Reproduce:

1. Open page https://www.qax-camp.com.ua/courses/processes/lessons/it-vocabulary/
2. Pay attention to the "Scholokov Denis" text the Author of the "IT Vocabulary – АйТі Сленг" lesson

Actual Result: The Author of the "IT Vocabulary – АйТі Сленг" lesson is written in English in the End of the page 
Expected Result: The Author of the "IT Vocabulary – АйТі Сленг" lesson is written in Ukrainian in the End of the page 

Environment:
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/b51f6ba3-fef5-4cba-a44c-a8188f526236)

**Comment by ODrobik** [comment]
#938

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
