### ISSUE TITLE
Lessons - Events - Check lesson and event for "Test Management System (TMS)" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1373]
We need to check lesson and event for "Test Management System (TMS)" page.
Please check availability of requirements, functional compliance and design compliance.
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F

1. Environment lesson: https://www.qax-camp.com.ua/courses/testing/

![Test Management System](https://github.com/scholokov/qax-portal-2/assets/109460500/45ec1b50-59bb-4682-a041-546f1cf0adb6)

2. Environment event: https://www.qax-camp.com.ua/events/test-management-system-tms/

![Test Management System_](https://github.com/scholokov/qax-portal-2/assets/109460500/0dd31a55-93f8-4529-beb3-023bf1f08a43)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
passed
