### ISSUE TITLE
QA Quest/The "Записатися" button is displayed in the "QA Quest. Додаток Sandbox" block on the "QA Quest" page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1376]
Steps to reproduce:

1. Open page https://www.qax-camp.com.ua/qa-quest/
2. Scroll down to the "QA Quest. Додаток Sandbox" block on the "QA Quest" page
3. Pay attention to the "Записатися" button 

Actual Result: The **"Записатися**" button is displayed in the "QA Quest. Додаток Sandbox" block on the "QA Quest" page

Expected Result: The **"Обрати"** button is displayed in the "QA Quest. Додаток Sandbox" block on the "QA Quest" page 

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/d83090e2-ed80-4768-8eee-9992ae3f5c52)

**Comment by poroskundenys** [comment]
готово

**Comment by ODrobik** [comment]
verified
