### ISSUE TITLE
Test "Tools PICT" content - There are NO elements of the ellipse in the "questions" of the tests 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#139]
Steps To Reproduce:
1. Open the https://portal.qax-camp.com.ua/quizzes/tools-pict/
2. Pay attention to the transfer items

Actual result: there are **no element**s of an ellipse on the left side of the enumeration items
Expected result: there are elements of the ellipse on the left side of the items 

<img width="1440" alt="Снимок экрана 2022-09-21 в 1 24 30 PM" src="https://user-images.githubusercontent.com/110661667/191481830-5a7aa129-5b34-4bc8-95b7-9b42026a2ad4.png">
<img width="1440" alt="Снимок экрана 2022-09-21 в 1 12 25 PM" src="https://user-images.githubusercontent.com/110661667/191481985-084bb583-7194-433b-b21c-796a27f77848.png">

**Comment by DmytroMarkulych** [comment]
@LesiaBezukh при написані summary використайте правило Де? Що? Коли? і вкажіть будь ласка точну назву UI елементів

**Comment by Xalep4ik** [comment]
Verified
