### ISSUE TITLE
Test: Need design

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#14]
Необходим шаблонный дизайн для страницы с тестами. пример
https://portal.qax-camp.com.ua/courses/recruiter-program/lessons/technical_lecture_for_recruiters/quizzes/technical_lecture_test/
открытый вопрос
![image](https://user-images.githubusercontent.com/22824947/183056354-9fda42ce-6780-4a38-857f-9ab9e16784e2.png)
радиобатоны
![image](https://user-images.githubusercontent.com/22824947/183056444-d30fb95d-4efa-4cee-abff-73da4a679353.png)

чекбоксы
![image](https://user-images.githubusercontent.com/22824947/183056502-fe775cd7-e9f6-4342-b783-42ce25d51d89.png)

**Comment by ABatalov** [comment]
Ready for testing: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=931%3A92

**Comment by KaterinaNimenko35** [comment]
verified
