### ISSUE TITLE
Design - test page - no test button footer design 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#140]
Steps To Reproduce:
1. Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=931%3A91
2. Pay attention to the note about the lack of a test button footer 

actual result: the design has no test button 
expected result: the design has a test button 

example of button design: 
https://portal.qax-camp.com.ua/quizzes/q5-test-levels/
<img width="1440" alt="Снимок экрана 2022-09-22 в 11 02 37 AM" src="https://user-images.githubusercontent.com/110661667/191693831-b0a16230-ca9c-4684-a28b-d63a3182680e.png">

<img width="1440" alt="Снимок экрана 2022-09-22 в 10 59 03 AM" src="https://user-images.githubusercontent.com/110661667/191694024-04caba61-1e16-476c-ad35-cae2d00c6ca5.png">

**Comment by scholokov** [comment]
@LesiaBezukh 
додай будь ласка лінку - де можна подивитись приклад тесту з часом

**Comment by ButKoff** [comment]
fixed
