### ISSUE TITLE
Courses "Базовий курс QA" / The preview isn't displaying

### ISSUE THREAD

**Issue by Aleksandrkobets99** [scholokov/qax-portal-2#1404]
**Steps to reproduce:**

1. Open page using tablet version DevTools: https://www.qax-camp.com.ua/courses/q6-basic/
2. Look at the preview of courses

**Actual result:** The preview isn't displaying
**Expected result:** The preview is displaying

**Additional information:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=476-32&mode=design&t=i7B25BlL22exHNoj-0

**Environment:**
Windows 10
Google Chrome v 117.0.5938.132

**Attachment:** 
![chrome_j8S2okBgku](https://github.com/scholokov/qax-portal-2/assets/126480322/43b1551b-3e03-4bee-9eb2-3d8e8c240399)

**Comment by Aleksandrkobets99** [comment]
#1250

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
