### ISSUE TITLE
Courses "Базовий курс QA" / The text "І ще багато цікавого." isn't in the enumeration

### ISSUE THREAD

**Issue by Aleksandrkobets99** [scholokov/qax-portal-2#1408]
**Steps to reproduce:**

1. Open page using tablet version DevTools: https://www.qax-camp.com.ua/courses/q6-basic/
2. Look at the text "І ще багато цікавого."

**Actual result:** The text "І ще багато цікавого." isn't in the enumeration
**Expected result:** The text "І ще багато цікавого." is in the enumeration

**Requirements:**https://github.com/scholokov/qax-portal-2/wiki/1.2.-Courses-page#%D0%B1%D0%B0%D0%B7%D0%BE%D0%B2%D0%B8%D0%B9-%D0%BA%D1%83%D1%80%D1%81-qa

**Additional information:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=476-32&mode=design&t=i7B25BlL22exHNoj-0

**Environment:**
Windows 10
Google Chrome v 117.0.5938.132

**Attachment:** 
![chrome_hWK99O9PPW](https://github.com/scholokov/qax-portal-2/assets/126480322/9882f8b8-f651-4232-9dec-a28bdbc7decb)

**Comment by Aleksandrkobets99** [comment]
#1250

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
