### ISSUE TITLE
Courses "Базовий курс QA" / The text is "Після проходження курсу “Базовий курс QA“  in the last paragraph

### ISSUE THREAD

**Issue by Aleksandrkobets99** [scholokov/qax-portal-2#1409]
**Steps to reproduce:**

1. Open page using tablet version DevTools: https://www.qax-camp.com.ua/courses/q6-basic/
2. Look at the text in the last paragraph

**Actual result:** The text is "Після проходження курсу **“Базовий курс QA“** ти зможеш повністю зрозуміти з чого складається напрям тестування програмного забезпечення та перейти до практичних занять з тестування.“ in the last paragraph
**Expected result:** Після проходження курсу **“Теорія QA“** ти зможеш повністю зрозуміти з чого складається напрям тестування програмного забезпечення та перейти до практичних занять з тестування.

**Requirements:**https://github.com/scholokov/qax-portal-2/wiki/1.2.-Courses-page#%D0%B1%D0%B0%D0%B7%D0%BE%D0%B2%D0%B8%D0%B9-%D0%BA%D1%83%D1%80%D1%81-qa

**Additional information:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=476-32&mode=design&t=i7B25BlL22exHNoj-0

**Environment:**
Windows 10
Google Chrome v 117.0.5938.132

**Attachment:** 
![chrome_enGjOq29zv](https://github.com/scholokov/qax-portal-2/assets/126480322/2aae9695-371d-4bf0-9bcf-c4aa9e2af4c4)

**Comment by Aleksandrkobets99** [comment]
#1250

**Comment by scholokov** [comment]
виправлено у вимогах

**Comment by GNatala** [comment]
passed
