### ISSUE TITLE
Russian text in links description after open page QAX 8.0 Travel 2.0 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#141]
**STR**
1. Login on the page https://portal.qax-camp.com.ua/
2. Open https://portal.qax-camp.com.ua/qax-8-0-travel-2-0/

**ACTUAL RESULT**
Description of the links are showns in russian 

**EXPECTED RESULT **
Description of the links are shown in Ukrainian.

![UU0EkIZ7As](https://user-images.githubusercontent.com/109384052/191711378-5d2e8b7a-9607-44c5-b1a0-5eb8a3644772.png)
![wyeRzibk2e](https://user-images.githubusercontent.com/109384052/191711653-e557fd6c-90f6-4a02-95e0-8e5780540d58.png)

**Comment by scholokov** [comment]
fixed
https://www.qax-camp.com.ua/qax-8-0-travel-2-0/

**Comment by BatalovaOlha** [comment]
Resolved
