### ISSUE TITLE
Courses "Базовий курс QA" /The button "Price" is in EN

### ISSUE THREAD

**Issue by Aleksandrkobets99** [scholokov/qax-portal-2#1412]
**Steps to reproduce:**

1. Open page using tablet version DevTools: https://www.qax-camp.com.ua/courses/q6-basic/
2. Find button "Price"
3. Look at the button "Price"

**Actual result:** The button "Price" is in EN
**Expected result:** The button "Price" is in UA

**Additional information:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=476-32&mode=design&t=i7B25BlL22exHNoj-0

**Environment:**
Windows 10
Google Chrome v 117.0.5938.132

**Attachment:** 
![chrome_YPJQ9MwvcM](https://github.com/scholokov/qax-portal-2/assets/126480322/543be0c8-17f4-4003-9aa1-1a1499999fc6)

**Comment by Aleksandrkobets99** [comment]
#1250

**Comment by poroskundenys** [comment]
готово

**Comment by GNatala** [comment]
passed
