### ISSUE TITLE
QA Quest. Додаток Sandbox - Тестування модулю "Реєстрація"/The "(Ім’я По Батькові) text is displayed in the "Задача:" section of the "Створення тестової документації" page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1414]
Steps to reproduce:

1. Open page https://www.qax-camp.com.ua/courses/sandbox-req/lessons/sandbox-req-test-doc/quizzes/sandbox-req-test-docs/
2. Scroll down to the "Задача:" section of the "Створення тестової документаці" page
3. Pay attention to the "(Ім’я По Батькові) text in the "Задача:" section of the "Створення тестової документації" page

Actual Result: The "(Ім’я По Батькові) text is displayed in the "Задача:" section of the "Створення тестової документації" page

Expected Result: The "(Ім’я Прізвище) text is displayed in the "Задача:" section of the "Створення тестової документації" page

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/e4adf935-4d42-49cd-b2ac-29858a5e21b0)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
