### ISSUE TITLE
Unreading text on the page QAX 8.0 Travel 2.0 - paragraph "Записи встреч" - links to the meeting videos 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#142]
**STR**

1. Open page https://portal.qax-camp.com.ua/
2. Login
3. Open https://portal.qax-camp.com.ua/qax-8-0-travel-2-0/
4. Pay attention to the paragraph "Записи встреч".

**ACTUAL RESULT**
 Links to the meeting videos in paragraph "Записи встреч" are shown in black color (#000000) on a dark purple background (#2c2a3f)

**EXPECTED RESULT**
 Links to the meeting videos in paragraph "Записи встреч" are NOT shown in black color 

![bmLfnlyyao](https://user-images.githubusercontent.com/109384052/191714969-5f5a9809-e4e1-407b-8f39-149dd3df1f95.png)

**Comment by scholokov** [comment]
please retest
https://www.qax-camp.com.ua/qax-8-0-travel-2-0/

**Comment by BatalovaOlha** [comment]
Resolved
