### ISSUE TITLE
Lessons - "Коди стану HTTP і як їх інтерпретувати" / Misspelling word "подавляючому"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1421]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/web-mobile/lessons/http-status-codes/
2. Scroll down to the title: "Список кодів стану:"
3. Pay attention to the phrase "**подавляючому більшості** " in the next paragraph.

**Actual result:**
 The word is written "**подавляючому**".

**Expected result:**
 The word is written "**переважній**".

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/abdea052-da54-4249-8c21-3b22a621bda6)

**Comment by GNatala** [comment]
#952

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
