### ISSUE TITLE
Lessons - Events - Check lesson and event for "QA Звітність" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1426]
We need to check lesson for "QA Звітність" page.
Please check availability of requirements, functional compliance and design compliance.
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F

1. Environment lesson: https://www.qax-camp.com.ua/courses/testing/lessons/qa-report/

![QA Звітність](https://github.com/scholokov/qax-portal-2/assets/109460500/3df75179-cc66-4b0f-959c-a44a7f1fbd79)

2. Environment event: https://www.qax-camp.com.ua/events/qa-report/

![QA Звітність_](https://github.com/scholokov/qax-portal-2/assets/109460500/4d5b2a89-0cb7-4c4b-ab2e-f77abf063f92)

**Comment by ButKoff** [comment]
#664

**Comment by ODrobik** [comment]
verified
