### ISSUE TITLE
Lessons - Check lesson for "StatCounter" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1427]
We need to check lesson for "StatCounter" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/statcounter/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BA%D0%BE%D1%80%D0%B8%D1%81%D0%BD%D1%96-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%B8
![StatCounter](https://github.com/scholokov/qax-portal-2/assets/109460500/7f4009d4-e45c-40c3-bb75-c0b34fec5f1c)

**Comment by ButKoff** [comment]
#664

**Comment by ODrobik** [comment]
verified
