### ISSUE TITLE
Test page - Fonts - Font "h3" is have size 21 px

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1428]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/quizzes/%d1%82%d0%b5%d1%81%d1%82-%d0%b4%d0%bb%d1%8f-%d1%88%d1%80%d0%b8%d1%84%d1%82%d1%96%d0%b2/
2. Check font "h3" size

**Actual Result**
Font "h3" is have size 21 px

**Expected Result**
Font "h3" is have size 24 px

**Additional information**
Screen resolution: 1920 by 1080 pixels
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=5699-914&mode=design&t=ny2FRdWUlQoSYWSZ-0

**Enviroments**
Windows 10, Chrome 118.0.5993.71 (64 bit), Firefox 118.0.2 (64 bit)
![Тест для шрифтів – QAX Camp - Google Chrome 18 10 2023 13_16_39](https://github.com/scholokov/qax-portal-2/assets/95171672/3f096c50-eaaf-4b98-8573-56ae77a92e7b)

**Comment by DmitriiNasonov** [comment]
#1308

**Comment by scholokov** [comment]
не має даних про ширину екрану, при якому відбувалося тествання

**Comment by DmitriiNasonov** [comment]
bug-report is fixed

**Comment by scholokov** [comment]
please retest

**Comment by DmitriiNasonov** [comment]
retested. bug is reproduced
![Тест для шрифтів – QAX Camp - Google Chrome 31 10 2023 12_00_01](https://github.com/scholokov/qax-portal-2/assets/95171672/159b003d-47c0-4d7b-a9bd-643308895470)

**Comment by poroskundenys** [comment]
готово

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
