### ISSUE TITLE
Test page - Fonts - Font "h3" is have size 16 px

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1429]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/quizzes/%d1%82%d0%b5%d1%81%d1%82-%d0%b4%d0%bb%d1%8f-%d1%88%d1%80%d0%b8%d1%84%d1%82%d1%96%d0%b2/
2. Check font "h3" size

**Actual Result**
Font "h3" is have size 16 px

**Expected Result**
Font "h3" is have size 21 px

**Additional information**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=5699-914&mode=design&t=ny2FRdWUlQoSYWSZ-0

**Enviroments**
Windows 10 (DevTools), Chrome 118.0.5993.71 (64 bit), Firefox 118.0.2 (64 bit)
![Тест для шрифтів – QAX Camp - Google Chrome 18 10 2023 14_32_41](https://github.com/scholokov/qax-portal-2/assets/95171672/261e1ef3-df00-49d6-bacb-a99313762168)

**Comment by DmitriiNasonov** [comment]
#1308

**Comment by scholokov** [comment]
please retest

**Comment by DmitriiNasonov** [comment]
retested. bug is reproduced
![Тест для шрифтів – QAX Camp - Google Chrome 29 10 2023 17_18_53](https://github.com/scholokov/qax-portal-2/assets/95171672/c166738a-ad71-4f59-8142-3157d23b32de)

**Comment by poroskundenys** [comment]
готово

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
