### ISSUE TITLE
The name of the subsection "Усі види тестування продуктивності" is included in the general list - "Нефункціональні види тестування" - block 22. Типи тестування - lesson "Топ питання на тех співбесіді..." - course "Інструменти пошуку вакансій. Підготовка до проходження співбесіди. Створення СV"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#1430]
**STR**

1. Open https://www.qax-camp.com.ua/courses/cv/lessons/interview-questions/#22 you should be login;
2. Pay attention to the language of the name of the block

**ACTUAL RESULT**
The name of the subsection "Усі види тестування продуктивності" is included in the general list - "Нефункціональні види тестування"

EXPECTED RESULT
The name of the subsection "Усі види тестування продуктивності" is the name of the subsection and stays at the top of the list

Нефункціональні види тестування

Усі види тестування продуктивності:

- Навантажувальне тестування (Performance and Load Testing)
- Стресове тестування (Stress Testing)
- Тестування стабільності або надійності (Stability / Reliability Testing)
- Об’ємне тестування (Volume Testing)
- Тестування установки (Installation testing)
- Тестування зручності користування (Usability Testing)
- Тестування на відмову та відновлення (Failover and Recovery Testing)
- Конфігураційне тестування (Configuration Testing)

![6oyG9oJkkV](https://github.com/scholokov/qax-portal-2/assets/109384052/d9d1a88e-87e4-4539-9b63-578e9559d8c9)

**Comment by BatalovaOlha** [comment]
#1119

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
