### ISSUE TITLE
The name of block "36. Атрибуты баг-репорта" in russian- lesson "Топ питання на тех співбесіді..." - course "Інструменти пошуку вакансій. Підготовка до проходження співбесіди. Створення СV"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#1431]
**STR**

1. Open https://www.qax-camp.com.ua/courses/cv/lessons/interview-questions/#36 / you should be login;
2. Pay attention to the language of the name of the block.

**ACTUAL RESULT**
The name of the block looks like "Атрибуты баг-репорта"

**EXPECTED RESULT**
The name of the block should look like "Атрибути баг-репорта" as in the preview list
![yWuZwaFqRH](https://github.com/scholokov/qax-portal-2/assets/109384052/c6bad8ab-cae2-4ee5-8900-9337534ca752)

**Comment by BatalovaOlha** [comment]
#1119

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
