### ISSUE TITLE
QA Quest. Додаток Sandbox - Тестування модулю "Реєстрація"/The price 750 UAH is not available on Android.

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1432]
**Steps to retroduce:**

1. Open: [qax-camp.com.ua/qa-quest](http://qax-camp.com.ua/qa-quest);
2. Scroll down to QA Quest. Додаток Sandbox - Тестування модулю "Реєстрація";
3. Pay attantion to the absence of price;

**Actual result:** The price 750 UAH is not available on Android.
**Expected result:** The price 750 UAH is available on Android.

**Environment:**
Android version 12SKQ1.211006.001
Chrome Version: 117.0.5938.153

**Attachments:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/d3905b7b-c415-44c4-8049-20fedc05dc23)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/qax-portal-2/assets/88647733/95702598-7917-4d98-9fd3-c6b384d00b0f)

**Comment by prokopenkoga1977** [comment]
@DmytroMarkulych виправив

**Comment by prokopenkoga1977** [comment]
Passed
