### ISSUE TITLE
QA Quest. Додаток Sandbox - Тестування модулю "Авторизація"/The price 500 UAH is not available on Android.

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#1433]
**Steps to retroduce:**

1. Open: [qax-camp.com.ua/qa-quest](http://qax-camp.com.ua/qa-quest);
2. Scroll down to QA Quest. Додаток Sandbox - Тестування модулю "Авторизація";
3. Pay attantion to the absence of price;

**Actual result:** The price 500 UAH is not available on Android.
**Expected result:** The price 500 UAH is available on Android.

**Environment:**
Android version 12SKQ1.211006.001
Chrome Version: 117.0.5938.153

**Attachments:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/45359cc3-5ff7-4c8d-9bba-1790b8fd1a2c)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/qax-portal-2/assets/88647733/f8d07540-e6b8-4487-afee-13a755b672ce)

**Comment by prokopenkoga1977** [comment]
@DmytroMarkulych виправив

**Comment by poroskundenys** [comment]
готово

**Comment by prokopenkoga1977** [comment]
Passed
