### ISSUE TITLE
Lesson "Regression" / The title of preview of lesson is "Regression"

### ISSUE THREAD

**Issue by Aleksandrkobets99** [scholokov/qax-portal-2#1436]
**Steps to reproduce:**

1. Open page: https://www.qax-camp.com.ua/courses/testing/lessons/regression/
2. Look at the title of lesson preview

**Actual result:** The title of preview of lesson is "Regression"
**Expected result:** The title of preview of lesson is "Що таке регресія?"

**Requirements:** https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F

**Additional information:** https://www.canva.com/design/DAFfaq-NrFI/aTHK4cEZYzwKE2R5DFOnXg/edit

**Environment:**
Windows 10
Google Chrome v 117.0.5938.132

**Attachment:** 
![chrome_OOyGhOi64y](https://github.com/scholokov/qax-portal-2/assets/126480322/3de63b3d-028f-4de1-93b1-cae30162bb61)

**Comment by Aleksandrkobets99** [comment]
#931

**Comment by scholokov** [comment]
виправлено у вимогах

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
