### ISSUE TITLE
Lesson "Regression" / The title of lesson is "Regression"

### ISSUE THREAD

**Issue by Aleksandrkobets99** [scholokov/qax-portal-2#1437]
**Steps to reproduce:**

1. Open page: https://www.qax-camp.com.ua/courses/testing/lessons/regression/
2. Look at the title of lesson 

**Actual result:** The title of the lesson is "Regression"
**Expected result:** The title of the lesson is "Що таке регресія?"

**Requirements:** https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F

**Environment:**
Windows 10
Google Chrome v 117.0.5938.132

**Attachment:** 
![chrome_36hcwAmO4m](https://github.com/scholokov/qax-portal-2/assets/126480322/0fbcd58a-2446-4b41-8b2b-0e9e7e395bda)

**Comment by Aleksandrkobets99** [comment]
#931

**Comment by scholokov** [comment]
виправлено у вимогах

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
