### ISSUE TITLE
Lesson "Regression" / The text "Зміст" isn't bold

### ISSUE THREAD

**Issue by Aleksandrkobets99** [scholokov/qax-portal-2#1439]
**Steps to reproduce:**

1. Open page: https://www.qax-camp.com.ua/courses/testing/lessons/regression/
2. Find section with information
3. Look at the text "Зміст"

**Actual result:** The text "Зміст" isn't bold
**Expected result:** The text "Зміст" is bold

**Additional information:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=390-12776&mode=design&t=oqVbmB3btVjpVexx-0

**Environment:**
Windows 10
Google Chrome v 117.0.5938.132

**Attachment:** 
![chrome_p1caq24lOv](https://github.com/scholokov/qax-portal-2/assets/126480322/b89724b5-f318-4e05-8d13-18eba8c3d317)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/qax-portal-2/assets/88647733/5460aac4-1289-497c-834d-6dfdc65ba26d)

**Comment by Aleksandrkobets99** [comment]
#931

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
