### ISSUE TITLE
Tools-Trello test - The font-weight of the question text is less than in the design figma

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#144]
Steps To Reproduce:
1. Open https://portal.qax-camp.com.ua/courses/practical-tools/lessons/trello-confluence-miro/quizzes/miro/
2. Pay attention to **font-weigh**t of the question text

Actual result: font-weight 400
Expected result: font-weight 791 
<img width="1440" alt="Снимок экрана 2022-09-22 в 1 32 58 PM" src="https://user-images.githubusercontent.com/110661667/191725248-8bce095a-8aed-47c1-b685-25c52d3257ff.png">
<img width="1440" alt="Снимок экрана 2022-09-22 в 1 32 09 PM" src="https://user-images.githubusercontent.com/110661667/191725289-c5027c72-ca10-4591-ba73-f28ff883f1af.png">

**Comment by poroskundenys** [comment]
Font-weigth тут указывается https://prnt.sc/3VNDw3mgPSts

**Comment by Xalep4ik** [comment]
@scholokov Привіт) є питання 
цей текст має бути увесь 700 шрифтом як задача чи то як роз'яснення може бути й 400 шрифтом? бо в 2х інших тестах теж по різному

**Comment by scholokov** [comment]
так. дивись. там є 2 сутності:
- питання тесту (вони повинні бути жирним шрифтом. як вони і є)
- опис тесту. він повинен бути звичайним шрифтом. він знаходиться зверху. але він відсутній на дизайні. оце є помилкою

**Comment by Xalep4ik** [comment]
@scholokov тобто потрібно завести баг на дизайн, а цей репорт закрити?

**Comment by scholokov** [comment]
так

**Comment by Xalep4ik** [comment]
Verified
