### ISSUE TITLE
Lesson "Regression" / The order of headings is "9, 12" 

### ISSUE THREAD

**Issue by Aleksandrkobets99** [scholokov/qax-portal-2#1442]
**Steps to reproduce:**

1. Open page: https://www.qax-camp.com.ua/courses/testing/lessons/regression/
2. Find section with information
3. Look at the order of headings

**Actual result:** The order of headings is "9, 12" 
**Expected result:** The order of headings is "9, 10" 

**Additional information:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=390-12776&mode=design&t=oqVbmB3btVjpVexx-0

**Environment:**
Windows 10
Google Chrome v 117.0.5938.132

**Attachment:** 
![chrome_2Iq6kvl0xx](https://github.com/scholokov/qax-portal-2/assets/126480322/6bef955e-1c50-4f0d-ac1e-b11754052bb9)

**Comment by Aleksandrkobets99** [comment]
#931

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
