### ISSUE TITLE
Tools-TestRail test - punctuation error in the text of the assignment

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#145]
Steps To Reproduce:
1. Open the https://portal.qax-camp.com.ua/courses/practical-tools/lessons/jira-testrail/quizzes/tools-testrail/ 
2. Pay attention to «Скріншот вставити у відповідь»

Actual result: there is **no** period at the end of the sentence 
Expected result: there is a period at the end of the sentence
<img width="1440" alt="Снимок экрана 2022-09-22 в 1 42 30 PM" src="https://user-images.githubusercontent.com/110661667/191727970-cddbe54a-d3bc-4661-a157-6da521c8e280.png">

**Comment by scholokov** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
