### ISSUE TITLE
Checkout - Купони

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#1455]
Додати блок "купони" на сторінку чекауту:

1.  Розташовується під блоком "Авторизуватися"
у згорнутому вигляді має вид:
<img width="791" alt="image" src="https://github.com/scholokov/qax-portal-2/assets/22824947/959f8c5b-93a8-4f48-98a8-3ce5e279c264">

2. У розгорнутому вигляді має вид:
<img width="800" alt="image" src="https://github.com/scholokov/qax-portal-2/assets/22824947/09fcea29-5702-48a2-8cbf-58300ab6fa0e">

3. Повідомлення, у випадку неправильного купону:
<img width="784" alt="image" src="https://github.com/scholokov/qax-portal-2/assets/22824947/14dc8f2b-a149-46d9-895e-77325800ccf0">

фігма:
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6398-1146&mode=design&t=K1XcxIkblQytzx01-0

**Comment by AlonaSarapina** [comment]
ready for testing 
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=9646%3A751&mode=design&t=kOjs3wGedBF5dvxx-1

**Comment by ButKoff** [comment]
#1608

**Comment by ODrobik** [comment]
verified
