### ISSUE TITLE
Lessons - "Коди стану HTTP і як їх інтерпретувати" / Spelling mistake in the word "уточняючі"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1457]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/web-mobile/lessons/http-status-codes/
2. Scroll down to the title: "Класи кодів стану:"
3. Pay attention to the word "уточняючі" in the next sentence.

**Actual result:**
 The word is written "**уточняючі**".

**Expected result:**
 The word is written "**уточнюючі**".

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/2ccdfbec-132e-4285-ac67-23f7faf54342)

**Comment by GNatala** [comment]
#952

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
