### ISSUE TITLE
Lessons - "Коди стану HTTP і як їх інтерпретувати" / Misspelling phrase "На самому ділі" 

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1458]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/web-mobile/lessons/http-status-codes/
2. Scroll down to the title: "Список кодів стану:"
3. Pay attention to the phrase "**На самому ділі** " in the next paragraph.

**Actual result:**
 The phrase is written "**На самому ділі**".

**Expected result:**
 The phrase is written "**Насправді**".

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/fc3f91f3-7105-4edb-92c2-9e3ae8c10ffc)

**Comment by GNatala** [comment]
#952

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
