### ISSUE TITLE
Lessons - "Коди стану HTTP і як їх інтерпретувати" / An extra word "навсього" in phrase "301: «Запитуваний ресурс був навсього переміщений»."

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1459]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/web-mobile/lessons/http-status-codes/
2. Scroll down to the title: "300 Код стану"
3. Pay attention to the phrase "**301: «Запитуваний ресурс був навсього переміщений».** " in the next paragraph.

**Actual result:**
 The phrase is written "**301: «Запитуваний ресурс був навсього переміщений».**".

**Expected result:**
 The phrase is written "**301: «Запитуваний ресурс був переміщений».**".

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/e47ca229-de32-4bd9-85a3-6d54e7e8d508)

**Comment by GNatala** [comment]
#952

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/qax-portal-2/assets/88647733/2c43bafb-24fc-455a-bc2c-ba6f1719c437)

**Comment by GNatala** [comment]
Дякую, виправила

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
