### ISSUE TITLE
Tools-TestRail test - The dash element is used instead of the ellipse marker element in the text of the test 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#146]
STR:
1. Open the https://portal.qax-camp.com.ua/courses/practical-tools/lessons/jira-testrail/quizzes/tools-testrail/ 
2. Pay attention to dash element  

Actual result: in the text of the task in the enumeration there is an element of ellipse
Expected result: in the text of the task in the enumeration there is an element of ellipse marker
<img width="1440" alt="Снимок экрана 2022-09-22 в 1 42 05 PM" src="https://user-images.githubusercontent.com/110661667/191729361-10474ed0-1422-4afa-a46a-2f74f288978d.png">
<img width="1440" alt="Снимок экрана 2022-09-22 в 1 58 17 PM" src="https://user-images.githubusercontent.com/110661667/191729563-b9db2dfc-9a9b-4c8f-a07c-df6d9822c91a.png">
<img width="1440" alt="Снимок экрана 2022-09-22 в 1 59 11 PM" src="https://user-images.githubusercontent.com/110661667/191729690-1f6002d2-e15d-4e36-8a29-30697d7ec369.png">

**Comment by scholokov** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
