### ISSUE TITLE
Lessons - "Коди стану HTTP і як їх інтерпретувати" / Misspelling word "столкнутися"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1460]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/web-mobile/lessons/http-status-codes/
2. Scroll down to the last word in the content.
3. Pay attention to the phrase "**з якими ви можете столкнутися** " .

**Actual result:**
 The word is written "**столкнутися**".

**Expected result:**
 The word is written "**стикнутися**".

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/90acc24d-2ef0-41ca-8854-4ff36019e52b)

**Comment by GNatala** [comment]
#952

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
