### ISSUE TITLE
Lessons - "Обзор способов и протоколов аутентификации в веб-приложениях" / The slug of the lesson is in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1462]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/web-mobile/lessons/%d0%be%d0%b1%d0%b7%d0%be%d1%80-%d1%81%d0%bf%d0%be%d1%81%d0%be%d0%b1%d0%be%d0%b2-%d0%b8-%d0%bf%d1%80%d0%be%d1%82%d0%be%d0%ba%d0%be%d0%bb%d0%be%d0%b2-%d0%b0%d1%83%d1%82%d0%b5%d0%bd%d1%82%d0%b8%d1%84/
2. Pay attention to the slug of the lesson.

**Actual result:**
 The slug of the lesson is in russian.

**Expected result:**
The slug of the lesson is in English.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/d53e4508-f0ce-4629-92ad-902002042bfa)

**Comment by GNatala** [comment]
#965

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
