### ISSUE TITLE
Lessons - "Как работает SSL-сертификат, как браузер и сайт устанавливают безопасное соединение" / The slug of the lesson is in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1465]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/web-mobile/lessons/%d0%ba%d0%b0%d0%ba-%d1%80%d0%b0%d0%b1%d0%be%d1%82%d0%b0%d0%b5%d1%82-ssl-%d1%81%d0%b5%d1%80%d1%82%d0%b8%d1%84%d0%b8%d0%ba%d0%b0%d1%82-%d0%ba%d0%b0%d0%ba-%d0%b1%d1%80%d0%b0%d1%83%d0%b7%d0%b5%d1%80/
2. Pay attention to the slug of the lesson.

**Actual result:**
 The slug of the lesson is in russian.

**Expected result:**
The slug of the lesson is in English.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/cb7536fc-d239-4c44-86cf-1b9482558041)

**Comment by GNatala** [comment]
#964

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
