### ISSUE TITLE
wiki/Requirements - Course "Testing" / Six Lessons are absence in the list lessons for course

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1468]
**Steps to reproduce:**

1. Open page: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F
2. Open page: https://www.qax-camp.com.ua/courses/testing/
3. Match lists of lessons.
4. Pay attention to the absence of 6 Lessons in the Requirements and present on site.

**Actual Result:**  
Lessons:
**Таблиці рішень
State & Transition Diagram
Use-case Diagram
Traceability matrix
QA Звітність
Metrics
are absent in the Requirements**

**Expected Result:**  
Lessons:
**Таблиці рішень
State & Transition Diagram
Use-case Diagram
Traceability matrix
QA Звітність
Metrics
are present in the Requirements**

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/96111c1f-b3f6-493a-8b77-19ab1136f288)

**Comment by GNatala** [comment]
#1080

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
changed in new Courses
