### ISSUE TITLE
Tests - Text on the answer forms and below them in English

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#147]
STR: 
1. Open https://portal.qax-camp.com.ua/courses/recruiter-program/lessons/technical_lecture_for_recruiters/quizzes/technical_lecture_test/
2. Pay attention to the language of the text in the answer forms and the text below them 

Actual result: English text
Expected result: Ukrainian text:
"Впишіть вашу відповідь"
"За цю відповідь буде автоматично нараховано повну кількість балів, але вона може бути переглянута та відредагована після відсилання"

<img width="1440" alt="Снимок экрана 2022-09-22 в 12 09 53 PM" src="https://user-images.githubusercontent.com/110661667/191752164-1d8d1312-05d3-4833-988e-947be69005a4.png">

**Comment by Xalep4ik** [comment]
verified
