### ISSUE TITLE
Essay - Implement a design "Essay" page according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1470]
We need to implement a new design "Essay" page.
Environment: https://www.qax-camp.com.ua/courses/widiq-test/lessons/widiq-report/quizzes/widiq-report-weekly-status-confluence/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=9160-1524&mode=design&t=RWUttv5AzVixkPMy-0

![Essay](https://github.com/scholokov/qax-portal-2/assets/109460500/473a0707-366f-4b8a-a571-0e7d34bcb298)

**Comment by poroskundenys** [comment]
Готово. 
Тут пример https://www.qax-camp.com.ua/essay/%D1%81%D1%82%D0%B2%D0%BE%D1%80%D0%B5%D0%BD%D0%BD%D1%8F-%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D0%BE%D1%97-%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D1%96%D1%97-%D1%80%D0%B5%D1%94-2/

**Comment by ButKoff** [comment]
#1315

**Comment by GNatala** [comment]
passed
