### ISSUE TITLE
QA Quest. Додаток Sandbox - Тестування модулю "Реєстрація"/The "(Ім’я По Батькові) text is displayed in the "Задача:" section of the "Тестування" page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1471]
Steps to reproduce:

1. Open page https://www.qax-camp.com.ua/courses/sandbox-req/lessons/sandbox-req-testing/quizzes/sandbox-req-testing/
2. Scroll down to the "Задача:" section of the "Тестування" page
3. Pay attention to the "(Ім’я По Батькові) text in the "Задача:" section of the "Тестування" page

Actual Result: The "(Ім’я По Батькові) text is displayed in the "Задача:" section of the "Тестування" page

Expected Result: The "(Ім’я та Прізвище) text is displayed in the "Задача:" section of the "Тестування" page

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/f32cf6c8-24d9-4a32-9c97-f89d1e454ff9)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
