### ISSUE TITLE
Tests - add the "Start quiz" button design to the figma 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#149]
STR: 
1. Open https://portal.qax-camp.com.ua/courses/practical-tools/lessons/figma-pict-datagrip/quizzes/tools-datagrip/
2.  Pay attention to "Start quiz" button 

Actual result: Not presented
Expected result: Presented
Notes: Notes: If it does not violate the design concept and fits the style, add a button design like "Позначити як виконено" 
<img width="1440" alt="Снимок экрана 2022-09-22 в 4 09 23 PM" src="https://user-images.githubusercontent.com/110661667/191756578-bdb39e38-b635-4cf8-bd6c-953d068f1fe4.png">
<img width="1440" alt="Снимок экрана 2022-09-22 в 4 16 28 PM" src="https://user-images.githubusercontent.com/110661667/191758133-ad065490-0ce0-4805-a507-080ccc150502.png">

**Comment by scholokov** [comment]
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=931%3A91&t=H7creaGSejKIzNoB-0

**Comment by SOlkhova** [comment]
Verified
