### ISSUE TITLE
Russian text is shown on the page QAX 7.0 Sandbox

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#150]
**STR**
1. Open https://portal.qax-camp.com.ua/ and login
2. Go to the page https://portal.qax-camp.com.ua/qax-7-0-sandbox/
3. Pay attention to the language of the page 

**ACTUAL RESULT**
Page QAX 7.0 Sandbox is shown in russian language.

**EXPECTED RESULT**
Page QAX 7.0 Sandbox is NOT shown in russian language.

![gWFNeZH6XO](https://user-images.githubusercontent.com/109384052/191839887-f66f76be-37d0-4ef8-936a-c0617de383c4.png)

**Comment by scholokov** [comment]
please retest to update current status

**Comment by BatalovaOlha** [comment]
not actual
