### ISSUE TITLE
Lesson "Что такое сетевой протокол" / The URL of lesson is /courses/web-mobile/lessons/что-такое-сетевой-протокол/

### ISSUE THREAD

**Issue by Aleksandrkobets99** [scholokov/qax-portal-2#1502]
**Steps to reproduce:**

1. Open page: https://www.qax-camp.com.ua/courses/web-mobile/lessons/%d1%87%d1%82%d0%be-%d1%82%d0%b0%d0%ba%d0%be%d0%b5-%d1%81%d0%b5%d1%82%d0%b5%d0%b2%d0%be%d0%b9-%d0%bf%d1%80%d0%be%d1%82%d0%be%d0%ba%d0%be%d0%bb/
2. Look at the URL of page

**Actual result:** The URL of lesson is /courses/web-mobile/lessons/что-такое-сетевой-протокол/
**Expected result:** The URL of lesson is /courses/web-mobile/lessons/dns/

**Requirements:** https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F

**Environment:**
Windows 10
Google Chrome v 117.0.5938.132

**Attachment:** 
![chrome_7wjcqTR1p7](https://github.com/scholokov/qax-portal-2/assets/126480322/6fc34701-83a3-4fda-973c-3b7038d350b9)

**Comment by Aleksandrkobets99** [comment]
#967

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
