### ISSUE TITLE
Russian text is shown on the page QAX 6.0 Portal

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#153]
**STR**

1. Open https://portal.qax-camp.com.ua/ and login
2. Go to the page https://portal.qax-camp.com.ua/qax-6-0-portal/
3. Pay attention to the language of the page

ACTUAL RESULT
Page QAX 6.0 Portal is shown in russian language.

EXPECTED RESULT
Page QAX 6.0 Portal is NOT shown in russian language.

![UimwYVTA4l](https://user-images.githubusercontent.com/109384052/191845720-0a5a9def-a376-4378-a6d8-9e8ef632f9e9.png)

**Comment by scholokov** [comment]
please retest
