### ISSUE TITLE
Lessons - "ShareX" / Spelling mistake in the word **ваши м **

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1535]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/sharex/
2. Scroll down to the end of the content.
3. Pay attention to the second to last paragraph -  sentence "Розширені налаштування: ShareX має велику кількість налаштувань, які дозволяють налаштувати додаток згідно з **ваши м** потребами. ".

**Actual result:**
 The word is written **ваши м** - extra space and without the letter "и".

**Expected result:**
 The word is written **вашими**.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/0d2bfab4-1025-4b68-a9de-895727974007)

**Comment by GNatala** [comment]
#1014

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
