### ISSUE TITLE
Lessons - "Что на самом деле происходит, когда пользователь вбивает в браузер адрес google.com" / The slug of the lesson is in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1537]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/web-mobile/lessons/%d1%87%d1%82%d0%be-%d0%bd%d0%b0-%d1%81%d0%b0%d0%bc%d0%be%d0%bc-%d0%b4%d0%b5%d0%bb%d0%b5-%d0%bf%d1%80%d0%be%d0%b8%d1%81%d1%85%d0%be%d0%b4%d0%b8%d1%82-%d0%ba%d0%be%d0%b3%d0%b4%d0%b0-%d0%bf%d0%be%d0%bb/
2. Pay attention to the slug of the lesson.

**Actual result:**
 The slug of the lesson is in russian.

**Expected result:**
The slug of the lesson is in English.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/a1a1325a-744c-451a-b578-885a07843c59)

**Comment by GNatala** [comment]
#969

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
