### ISSUE TITLE
An incorrect phrase that does not correspond to the context - section "Що таке DNS?" - lesson "DNS, ping, tracert" 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#1539]
**STR**
1. Open https://www.qax-camp.com.ua/courses/web-mobile/lessons/dns-ping/ (log in before opening)
2. Pay attention to the first section "Що таке DNS?"

**ACTUAL RESULT**
End of phrase "...знайти запитаний користувачем сайт на ім’я" is out of context

**EXPECTED RESULT**
The phrase "DNS (Domain Name System) – це технологія, яка дозволяє браузеру на кшталт Firefox, Chrome або Edge знайти запитаний користувачем **сайт на ім’я.**" at the end of the phrase _must match the content_

![rf0Y2zzxGS](https://github.com/scholokov/qax-portal-2/assets/109384052/b0da5658-5fbd-427b-8fe8-5ed19e36ad3f)

**Comment by BatalovaOlha** [comment]
#1012

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
