### ISSUE TITLE
Unreading text on the page QAX 6.0 Portal - paragraph QAX 6.0 Portal - links to the meeting videos

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#154]
**STR**

1. Open page https://portal.qax-camp.com.ua/
2. Login
3. Open https://portal.qax-camp.com.ua/qax-6-0-portal/
4. Pay attention to the paragraph "QAX 6.0 Portal"

ACTUAL RESULT
Links to the meeting videos in paragraph "QAX 6.0 Portal"  are shown in black color (#000000) on a dark purple background (#2c2a3f)

EXPECTED RESULT
Links to the meeting videos in paragraph "QAX 6.0 Portal"  are NOT shown in black color

![Bquxgo2Sac](https://user-images.githubusercontent.com/109384052/191848009-1c84d134-9af3-40c0-a2dc-57b3ee257ed2.png)
![g0DGuuSfSD](https://user-images.githubusercontent.com/109384052/191848015-00e52e1c-5736-42eb-9842-62018404324b.png)

**Comment by scholokov** [comment]
technical limitation

**Comment by BatalovaOlha** [comment]
no actual
