### ISSUE TITLE
The phrase is not logical and does not match the context - block "Навіщо потрібні DNS-сервери та які вони бувають?" - lesson "DNS, ping, tracert"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#1540]
**STR**

1. Open https://www.qax-camp.com.ua/courses/web-mobile/lessons/dns-ping/ (log in before opening)
2. Pay attention to the first section "Що таке DNS?"

**ACTUAL RESULT**
The phrase "Якщо користувач звернеться до сайту, який раніше був запрошений, знову відкриється, оскільки використовується збережена інформація. " is out of context 

**EXPECTED RESULT**
The phrase must be corrected according to the context

![MgxHvv0lSF](https://github.com/scholokov/qax-portal-2/assets/109384052/937b3ee2-2389-4188-b6aa-b1b148680263)

**Comment by BatalovaOlha** [comment]
#1012

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
