### ISSUE TITLE
QA Quest. Додаток WiDiQ/The "(Ім’я По Батькові) text is displayed in the " "Створити сторінку “Reports" point of the  "Звіт по виконаній роботі QA на проекті – Confluence" page 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1541]
Steps to reproduce:

1. Open page https://www.qax-camp.com.ua/courses/widiq-test/lessons/widiq-report/quizzes/widiq-report-own-confluence/
2. Scroll down to the "Створити сторінку “Reports (Ім’я По Батькові)" point 
3. Pay attention to the "(Ім’я По Батькові) text in the "Звіт по виконаній роботі QA на проекті – Confluence" page

Actual Result: The "(Ім’я По Батькові) text is displayed in the "Створити сторінку “Reports (Ім’я По Батькові)" point 

Expected Result: The "(Ім’я та Прізвище) text is displayed in the "Створити сторінку “Reports (Ім’я та Прізвище)" point 

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/5f69bdef-79ab-4bd1-8de2-5d03b28d054a)

**Comment by scholokov** [comment]
please retest

**Comment by ODrobik** [comment]
Issues is still 
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/099c9832-a2bd-4465-96dd-6b25e9c26d1d)

**Comment by scholokov** [comment]
please retest

**Comment by ODrobik** [comment]
verified
