### ISSUE TITLE
Lessons - Check lesson for "TestRail" page (update)

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1543]
We need to check lesson for "TestRail" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/testrail/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F--%D0%BC%D0%B0%D0%B9%D1%81%D1%82%D0%B5%D1%80-%D0%BA%D0%BB%D0%B0%D1%81%D0%B8
![TestRail](https://github.com/scholokov/qax-portal-2/assets/109460500/51a9080e-42cb-4446-bfc6-b0a4ec3c0801)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
verified
