### ISSUE TITLE
QA Quest. Додаток WiDiQ/The "(Ім’я По Батькові) text is displayed in the " "Створити сторінку “Reports" point of the "Статус-звіт по проекту – Confluence" page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1545]
Steps to reproduce:

1. Open page https://www.qax-camp.com.ua/courses/widiq-test/lessons/widiq-report/quizzes/widiq-report-own-confluence/
2. Scroll down to the "Створити сторінку “Reports (Ім’я По Батькові)" point
3. Pay attention to the "(Ім’я По Батькові) text in the "Статус-звіт по проекту – Confluence" page

Actual Result: The "(Ім’я По Батькові) text is displayed in the "Створити сторінку “Reports **(Ім’я По Батькові)**" point

Expected Result: The "(Ім’я та Прізвище) text is displayed in the "Створити сторінку “Reports **(Ім’я та Прізвище)**" point

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/9f2f1df8-f23d-4a0e-b619-52603a374cde)

**Comment by scholokov** [comment]
please retest

**Comment by ODrobik** [comment]
issues is still 
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/69f3587c-fe9b-454d-bec9-9a7ef11158e0)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
