### ISSUE TITLE
Lessons - Events - Check lesson and event for "Коди стану HTTP і як їх інтерпретувати" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1555]
We need to check lesson for "Коди стану HTTP і як їх інтерпретувати" page.
Please check availability of requirements, functional compliance and design compliance.
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#web--mobile

1. Environment lesson: https://www.qax-camp.com.ua/courses/web-mobile/lessons/http-status-codes/

![Коди стану HTTP і як їх інтерпретувати](https://github.com/scholokov/qax-portal-2/assets/109460500/4e3897ba-51f7-4e14-ba31-4e9743a79005)

2. Environment event: https://www.qax-camp.com.ua/events/http-status-codes/

![Коди стану HTTP і як їх інтерпретувати)_Event](https://github.com/scholokov/qax-portal-2/assets/109460500/0f27384a-456d-4677-af10-645cb9cdf02b)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
passed
