### ISSUE TITLE
Lessons - Check lesson for "CI / CD" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1556]
We need to check lesson for "CI / CD" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/processes/lessons/ci-cd/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D0%B8
![CI  CD](https://github.com/scholokov/qax-portal-2/assets/109460500/7e2f3ef0-b8d7-4ad2-8a52-77c565529406)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
passed
