### ISSUE TITLE
Quest - Check quest for "Генерація тестових даних використовуючи техніки тест дизайну" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1557]
We need to check quest for "Генерація тестових даних використовуючи техніки тест дизайну" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/sandbox-req/lessons/sandbox-req-test-data/
![Генерація тестових даних використовуючи техніки тест дизайну](https://github.com/scholokov/qax-portal-2/assets/109460500/371c65e6-d12b-4959-b722-dc44c869804f)

**Comment by GNatala** [comment]
verified
