### ISSUE TITLE
Quest - Check quest for "Створення тестової документації" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1558]
We need to check quest for "Створення тестової документації" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/sandbox-req/lessons/sandbox-req-test-doc/
![Створення тестової документації](https://github.com/scholokov/qax-portal-2/assets/109460500/472881b1-eee9-4070-a1ef-d5bd951ad32f)

**Comment by GNatala** [comment]
verified
