### ISSUE TITLE
"Декомпозиція та створення mind map додатку з Miro" lesson - Lesson preview - Lesson name is "Cтворення mind map додатку"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1592]
**Steps of reproducing**
1. https://www.qax-camp.com.ua/courses/mc-testing/lessons/decomposition/
2. Check lesson name in the lesson preview

**Actual Result**
Lesson name is "Cтворення mind map додатку"

**Expected Result**
Lesson name is "Декомпозиція та створення mind map додатку з Miro"

**Additional information**
https://www.canva.com/design/DAFeSN9YPTM/LEJztioQWSZfPUhf_Fu37g/edit

**Enviroments**
Windows 10, Chrome 119.0.6045.124 (64 bit)
Android 8.1.0, Chrome 118.0.5993.111
![Парки – Long-Travel - Google Chrome 08 11 2023 14_15_24](https://github.com/scholokov/qax-portal-2/assets/95171672/eaab7563-5e23-45a1-abfa-f101b4f5a9b2)
![photo_2023-11-08_14-35-28](https://github.com/scholokov/qax-portal-2/assets/95171672/215bc714-bc48-4639-ab32-24bf85b1e7a2)

**Comment by DmitriiNasonov** [comment]
#1017

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
