### ISSUE TITLE
Calendar / The current date color is #F7F7F7

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1596]
**Steps to reproduce:**

1. Open  https://www.qax-camp.com.ua/calendars/
2. Pay attention to the current date color.

**Actual result:**
The current date color is #F7F7F7.

**Expected result:**
The current date color is #F66F5D.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6112-976&mode=design&t=Ef82tSUGZqS6zutk-0

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/e952c175-f2f5-465b-a8f2-439c3ed49d92)

**Comment by poroskundenys** [comment]
готово

**Comment by GNatala** [comment]
перевірено
