### ISSUE TITLE
"Нагороди – QAX Travel" - Awards -  Block "Умови:" is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1598]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/ach-travel/

**Actual Result**
Block "Умови:" is missing

**Expected Result**
Block "Умови:" is present

**Additional information**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=8784-148&mode=design&t=jq4BWf4IWC1lCVcE-0

**Enviroments**
Windows 10, Chrome 119.0.6045.124 (64 bit)
Android 8.1.0, Chrome 118.0.5993.111
![Декомпозиція та створення mind map додатку з Miro – QAX Camp - Google Chrome 08 11 2023 15_19_31](https://github.com/scholokov/qax-portal-2/assets/95171672/87459732-e32d-4441-ac66-a76fb8135ed6)

**Comment by DmitriiNasonov** [comment]
#1316

**Comment by poroskundenys** [comment]
готово

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
