### ISSUE TITLE
"Найближча подія" block/  Extra elements "scroll bars" are in the Timer Block

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1599]
**Steps to reproduce:**

1. Open  https://www.qax-camp.com.ua/calendars/
2. Pay attention to the "Найближча подія" block - Timer Block.

**Actual result:**
Extra elements "scroll bars" are in the Timer Block.

**Expected result:**
Extra elements "scroll bars" are absent in the Timer Block.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6704-1435&mode=design&t=WA2VgQX3UELcAW2Y-0

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/aeb0d63f-9e62-4fbc-b699-5ecd40d79891)
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/3eea3bcc-c2dc-4d9a-864f-446d424c7a8b)

**Comment by poroskundenys** [comment]
У меня не воспроизводится пробелема

**Comment by GNatala** [comment]
@poroskundenys 

Спробуйте зачекати секунд 5.

**Environment:**
Windows 10,
Google Chrome v 119

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/3e507142-ee73-4731-8d20-ee117d24f4d9)

**Comment by poroskundenys** [comment]
готово

**Comment by GNatala** [comment]
Баг відтворюється - ось статистика по Calendars використовуючи Lambdatest:
- Windows 10, Chrome, RESOLUTION від 1024 до 1920 bug відтворюється
- macOS, Chrome  відтворюється
- Windows 10, Firefox не відтворюється
- macOS, Safari  не відтворюється

**Comment by poroskundenys** [comment]
@GNatala поправил

**Comment by GNatala** [comment]
перевірено
