### ISSUE TITLE
Lessons - Events - Check lesson and event for "Естімація" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1606]
We need to check lesson and event for "Естімація" page.
Please check availability of requirements, functional compliance and design compliance.
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D0%B8

1. Environment lesson: https://www.qax-camp.com.ua/courses/processes/lessons/estimation/

![Естімація](https://github.com/scholokov/qax-portal-2/assets/109460500/17bca08d-e424-4797-86ec-dab2b111ca7d)

2. Environment event: https://www.qax-camp.com.ua/events/estimation/

![Естімація_Event](https://github.com/scholokov/qax-portal-2/assets/109460500/e2d2c105-a43e-4ac7-9fcb-5a2e07fe57d1)

**Comment by GNatala** [comment]
verified
