### ISSUE TITLE
Checkout - Implement a new design "Купон на знижку" block

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1608]
We need to implement a new design "Купон на знижку" block.
Environment: https://qax-camp.com.ua/checkout/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6398-1146&mode=design&t=NmmcLMiuHGkLmRtr-0

1. Розташовується під блоком "Авторизуватися" у згорнутому вигляді має вид:

![Discount](https://github.com/scholokov/qax-portal-2/assets/109460500/3a9cb53e-081a-4dd8-9382-26dc3945b94e)

2. У розгорнутому вигляді має вид:

![Discount_](https://github.com/scholokov/qax-portal-2/assets/109460500/b263ed05-212d-4909-b105-2638de789a0c)

3. Повідомлення, у випадку неправильного купону:

![Discount_1](https://github.com/scholokov/qax-portal-2/assets/109460500/5a640171-34af-41aa-8508-6b210f43c7fb)

**Comment by ButKoff** [comment]
#1455

**Comment by poroskundenys** [comment]
После отправки кода купона сообщение о его обработки приходят в таком формате https://prnt.sc/GDAs6rEGHTVH https://prnt.sc/lsmfnuXd6ar9. Мне не понятно как переделать вывод текущих сообщений под дизайн, чтобы не поломалась логика работы функционала купона

**Comment by scholokov** [comment]
@poroskundenys 
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=9850-228&mode=design&t=YEdpfASOv2o6TtYi-0

**Comment by poroskundenys** [comment]
готово

**Comment by ODrobik** [comment]
verified
