### ISSUE TITLE
Certificate - Implement a Certificate template for downloading

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1609]
We need to implement a Certificate template for downloading.
Environment: https://www.qax-camp.com.ua/wp-admin/post.php?post=14623&action=edit
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=9618-114&mode=design&t=tNOBJkrPbwhhp0md-0

![Certificate](https://github.com/scholokov/qax-portal-2/assets/109460500/dfa3909f-8092-4254-9d60-0d4bd36995b6)

**Comment by ButKoff** [comment]
#1350

**Comment by poroskundenys** [comment]
Если указывать размеры шрифтов как в фигме получается такое https://prnt.sc/E2XZmlE3n7Af. Размер сертификата это А4. Нужно размеры шрифтов увеличить под этот размер сертификата

**Comment by poroskundenys** [comment]
Готово. 
Я сделал шаблон с классами и тегами. Его нужно копировать для новых сертификатов и заменять нужный текст. Также обязательно менять размер сертификата на А4, чтобы нижняя строчка сертификата не перемещалась на новую страницу

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
verified
