### ISSUE TITLE
Lessons - Events - Check lesson and event for "Production. Як його тестувати?" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1610]
We need to check lesson and event for "Production. Як його тестувати?" page.
Please check availability of requirements, functional compliance and design compliance.
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F

1. Environment lesson: https://www.qax-camp.com.ua/courses/testing/lessons/test-prod/

![Production  Як його тестувати](https://github.com/scholokov/qax-portal-2/assets/109460500/eae8dbee-81c5-45f2-974e-2e8320b4a003)

2. Environment event: https://www.qax-camp.com.ua/events/test-prod/

![Production  Як його тестувати_Event](https://github.com/scholokov/qax-portal-2/assets/109460500/e81bfbd8-1175-4d09-a76c-8aaf2fa3c01f)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
verified
