### ISSUE TITLE
Quest - Check quest for "Додаток Outsource 2.0" page

### ISSUE THREAD

**Issue by steblinka1111** [scholokov/qax-portal-2#1611]
We need to check quest for "Оновлено сторінку з квестами. Додано новий квест "Додаток Outsource 2.0" page.

Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/qa-quest/
<img width="1014" alt="зображення" src="https://github.com/scholokov/qax-portal-2/assets/147995195/83e41ca3-d43d-449d-b549-67762f2e5bcd">

<img width="476" alt="зображення" src="https://github.com/scholokov/qax-portal-2/assets/147995195/c55c1f37-95c3-4d9e-99fc-f3f99db7fba2">

**Comment by DmitriiNasonov** [comment]
testing completed
