### ISSUE TITLE
Events - Check the future event on  "Майстер-клас по тестуванню модулю “Реєстрація” ч.3  page 

### ISSUE THREAD

**Issue by steblinka1111** [scholokov/qax-portal-2#1612]
We need to check the future event on the "Майстер-клас по тестуванню модулю “Реєстрація” ч.3" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/events/mc-req-3/
<img width="788" alt="зображення" src="https://github.com/scholokov/qax-portal-2/assets/147995195/3668accc-2d54-4f99-8c53-ff66b4cc2794">

**Comment by DmitriiNasonov** [comment]
The event has ended. Testing is not possible
