### ISSUE TITLE
Lessons - "IT Vocabulary – АйТі Сленг" / Spelling mistake оf the word "проект" and its variants in the content

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1615]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/processes/lessons/it-vocabulary/
2. Find all variants of the word "проект"  in the content. **It appears 10 times.**
3. Pay attention to the spelling of the words "проект".

**Actual result:**
 The word "проект" and its variants are written with the letter "е" - 10 times.

**Expected result:**
 The word "проект" and its variants are written with the letter "є" - 10 times.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/c3b29d59-23cf-4b2a-9109-a944c0659911)

**Comment by GNatala** [comment]
#1019

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
