### ISSUE TITLE
wiki/ Requirements - course "Процеси" / The Lesson "Естімація" is absent in the list of for course "Процеси"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1616]
**Steps to reproduce:**
1. Open https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D0%B8
2. Pay attention to the list of lessons for course "Процеси".

**Actual result:**
The Lesson "Естімація" is absent in the list of for course "Процеси".

**Expected result:**
The Lesson "Естімація" is present in the list of for course "Процеси".

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/72f12e4b-1093-493c-ad1e-518ad4ead0f7)

**Comment by GNatala** [comment]
#1606

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
