### ISSUE TITLE
Lesson "IT Vocabulary – АйТі Сленг"/ The Space is not displayed in "Estimation (Естімація)- Кількість" text after word "(Естімація)"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1619]
Steps to Reproduce:

1. Open page https://www.qax-camp.com.ua/courses/processes/lessons/it-vocabulary/
2. Pay attention to the "Estimation (Естімація)- Кількість" text of the "IT Vocabulary – АйТі Сленг" lesson

Actual Result: The Space is not displayed in **"Estimation (Естімація)- Кількість"** text after word "(Естімація)"
Expected Result: The Space is displayed in **"Estimation (Естімація) - Кількість"** text after word "(Естімація)"

Environment:
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/2d5ea27f-d3c7-4b8a-9b5a-f2927a69d7f6)

**Comment by ODrobik** [comment]
#938

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
