### ISSUE TITLE
Check the Home page 

### ISSUE THREAD

**Issue by ABatalov** [scholokov/qax-portal-2#162]
We need to check all blocks in implementation of Home page except Registration form. Registration form it's separate task.  

Design you can find: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A22 

Requirements home here: https://github.com/scholokov/qax-portal-2/wiki 
Requirements Foter here: https://github.com/scholokov/qax-portal-2/wiki/Footer 
Requirements main Menu: https://github.com/scholokov/qax-portal-2/wiki/Main-menu

**Comment by BatalovaOlha** [comment]
#200

**Comment by BatalovaOlha** [comment]
#174
