### ISSUE TITLE
Quest - Check quest for "Діаграма станів (UML)" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1622]
We need to check quest for "Діаграма станів (UML)" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/sandbox-auth/lessons/sandbox-auth-uml/
![Діаграма станів (UML)](https://github.com/scholokov/qax-portal-2/assets/109460500/f01f340d-b96b-43d7-8ce0-845a206c057e)

**Comment by GNatala** [comment]
verified
