### ISSUE TITLE
Lessons - Check lesson for "Тестуємо форму Реєстрації" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1623]
We need to check lesson for "Тестуємо форму Реєстрації" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/mc-testing/lessons/sandbox-reg-testing/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F--%D0%BC%D0%B0%D0%B9%D1%81%D1%82%D0%B5%D1%80-%D0%BA%D0%BB%D0%B0%D1%81%D0%B8
![Тестуємо форму Реєстрації](https://github.com/scholokov/qax-portal-2/assets/109460500/7a32a067-3d95-4664-a0c2-a3a94c821a59)

**Comment by GNatala** [comment]
verified
