### ISSUE TITLE
Check Form 

### ISSUE THREAD

**Issue by ABatalov** [scholokov/qax-portal-2#163]
We need to check implementation of the Form. 

Design: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A22 
Web: https://portal.qax-camp.com.ua/ 
Requirements:  https://github.com/scholokov/qax-portal-2/wiki/Form

**Comment by BatalovaOlha** [comment]
#194   #193
