### ISSUE TITLE
Quest - Page -"Створення тестової документації" / Extra element "line" under the  "AkbSZUXcgIxULcWKxqBA " appears on breakpoint 435px

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1646]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/sandbox-req/lessons/sandbox-req-test-doc/
2. Make breakpoint 435px.
3. Scroll down to the: "Password: AkbSZUXcgIxULcWKxqBA" 
4. Pay attention to the element "line" under the  "AkbSZUXcgIxULcWKxqBA ".

**Actual result:**
Extra element "line" under the  "AkbSZUXcgIxULcWKxqBA " appears on breakpoint 435px.

**Expected result:**
Element "line" under the  "AkbSZUXcgIxULcWKxqBA " does not appear on breakpoint 435px.

**Environment:**
**Mobile from the screen extension 435px**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/f6be5590-0ec2-4c80-bcb6-26035f2fbd03)

**Comment by GNatala** [comment]
#1558

**Comment by DmytroMarkulych** [comment]
Вкажіть що це розширення для mobile в блоці Environment

**Comment by GNatala** [comment]
Дякую, додала

**Comment by scholokov** [comment]
pleade retest

**Comment by GNatala** [comment]
passed
