### ISSUE TITLE
Check our trainers page 

### ISSUE THREAD

**Issue by ABatalov** [scholokov/qax-portal-2#165]
We need to check implementation of Our trainers page. 

Design: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=1617%3A70
Web: https://portal.qax-camp.com.ua/trainers/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/Our-Trainers

**Comment by BatalovaOlha** [comment]
#220

**Comment by BatalovaOlha** [comment]
#227

**Comment by BatalovaOlha** [comment]
#228

**Comment by BatalovaOlha** [comment]
#229

**Comment by BatalovaOlha** [comment]
#230

**Comment by ABatalov** [comment]
@BatalovaOlha Can we move this task to resolved?

**Comment by BatalovaOlha** [comment]
#241

**Comment by BatalovaOlha** [comment]
> @BatalovaOlha Can we move this task to resolved?

There are still open bugs but in general everything is ok

**Comment by BatalovaOlha** [comment]
#242
