### ISSUE TITLE
Quest - Page -"Створення тестової документації" / Missed link from the text "https://sandbox.qax-camp.com.ua/register/" to the corresponding page

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1654]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/sandbox-req/lessons/sandbox-req-test-doc/
2. Scroll down to the quizz  "Створення тестової документації" - open it. 
4. Pay attention to the text "https://sandbox.qax-camp.com.ua/register/".

**Actual result:**
The text "https://sandbox.qax-camp.com.ua/register/" is not a link to the corresponding page.

**Expected result:**
The text **"https://sandbox.qax-camp.com.ua/register/" is a lin**k to the corresponding page

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/290f1dff-41d2-4485-9765-60a7099fde3e)

**Comment by GNatala** [comment]
#1558

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
