### ISSUE TITLE
Quest - Page -"Створення тестової документації" / Missed link from the text "qaxcampqa.testrail.io/index.php?/suites/overview/28" to the corresponding page

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1658]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/sandbox-req/lessons/sandbox-req-test-doc/
2. Scroll down to the quizz  "Створення тестової документації" - open it. 
3. Scroll down to the article "Задача:"
4. Pay attention to the text "qaxcampqa.testrail.io/index.php?/suites/overview/28".

**Actual result:**
The text "qaxcampqa.testrail.io/index.php?/suites/overview/28" is not a link to the corresponding page.

**Expected result:**
The text **"qaxcampqa.testrail.io/index.php?/suites/overview/28" is a link** to the corresponding page

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/809e2b3a-839d-42fd-9682-25b23de72c89)

**Comment by GNatala** [comment]
#1558

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
