### ISSUE TITLE
Create design of login logout 

### ISSUE THREAD

**Issue by ABatalov** [scholokov/qax-portal-2#166]
We need to create design icons login and logout. 
Design on Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=1979%3A247
Here is some examples:  

![log-in-logout-icone-de-saida-da-conta-simbolo-no-neumorfismo-ui-neumorfico_248162-1240](https://user-images.githubusercontent.com/72439798/192148981-8c1fea12-26eb-41e8-9419-be0a4f9c5412.jpg)
![login-logout-icon-people-arrow-flat-design-login-logout-icon-people-arrow-flat-design-eps-file-available-112719317](https://user-images.githubusercontent.com/72439798/192148983-ce3f9da3-608c-4139-b86a-86e17deb3b96.jpg)
![neumorphism-arrow-login-logout-icon-exit-entry-symbol-ui-ux-app-web-white-neumorphic-buttons_248162-918](https://user-images.githubusercontent.com/72439798/192148984-c3cbfd17-0008-4b52-b5a1-cd0e4a502b49.jpg)
![pngtree-logout-icon-vectors-png-image_1737872](https://user-images.githubusercontent.com/72439798/192148985-3d0f0ae6-525c-4cf9-846c-28884d4806e1.jpg)

**Comment by ABatalov** [comment]
@scholokov , please check this task, are this exampls ok?

**Comment by AlonaSarapina** [comment]
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=1979%3A247
Варіант з просто іконками, + як вони виглядатимуть в дизайні

**Comment by ABatalov** [comment]
> 

Супер, дякую

**Comment by ABatalov** [comment]
> https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=1979%3A247 Варіант з просто іконками, + як вони виглядатимуть в дизайні

@AlonaSarapina , нам потрібно щоб кнопка Записатись залишилась, це буде різний функціонал у Записатися та login/logout. Я думаю, що треба поставити ogin/logout правіше Записатися

**Comment by ABatalov** [comment]
@AlonaSarapina , питання: може текст "увійти" прибрати? тобто залишити лише картинки? щоб у нас ширина елементу була однакова? ..

**Comment by AlonaSarapina** [comment]
added new button design https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=1979%3A247

**Comment by ABatalov** [comment]
Super )

**Comment by dmitryylev** [comment]
verified
