### ISSUE TITLE
Quest - Page -"Генерація тестових даних ..." / Missed link from the text "https://sandbox.qax-camp.com.ua/register/ " to the corresponding page

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1663]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/sandbox-req/lessons/sandbox-req-test-data/
2. Scroll down to the quizz  "Генерація тестових даних використовуючи техніки тест дизайну" - open it. 
3. Pay attention to the text "https://sandbox.qax-camp.com.ua/register/  " after the "Додаток, що тестується:".

**Actual result:**
The text "https://sandbox.qax-camp.com.ua/register/ " is not a link to the corresponding page.

**Expected result:**
The text **"https://sandbox.qax-camp.com.ua/register/  " is a link** to the corresponding page.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/57d5b572-e11f-489f-b995-78997e18869d)

**Comment by GNatala** [comment]
#1557

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
