### ISSUE TITLE
Lesson "Путь критической визуализации" When click on the URL lesson isn`t opening page

### ISSUE THREAD

**Issue by Aleksandrkobets99** [scholokov/qax-portal-2#1665]
**Steps to reproduce:**

1. Open page: https://github.com/scholokov/qax-portal-2/issues/966
2. Click on the URL of lesson

**Actual result:** When click on the URL lesson isn`t opening page
**Expected result:** When click on the URL lesson is opening page

**Additional information:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=5900-938&mode=design&t=6i2MbSY5QGWCgXLx-0

**Environment:**
Windows 10
Google Chrome v 119.0.6045.160

**Attachment:** 
![chrome_jpNwvXGvDV](https://github.com/scholokov/qax-portal-2/assets/126480322/d87c07dc-fa4b-465a-a60c-e38f3e62d162)
![chrome_qjctAFQKbf](https://github.com/scholokov/qax-portal-2/assets/126480322/ea4b80cd-0bf7-49c8-be6f-698d1011c018)
![image](https://github.com/scholokov/qax-portal-2/assets/126480322/2acd76bd-c792-42d2-9b59-376263bc2527)

**Comment by DmytroMarkulych** [comment]
Вкажіть що це розширення для laptop в блоці Environment


![Image](https://github.com/scholokov/qax-portal-2/assets/88647733/e41753a0-4eee-4f69-a928-be51eb0a6294)

**Comment by Aleksandrkobets99** [comment]
Not a bug
