### ISSUE TITLE
 Russian text on the page QA Cources block "Q0. Тестирование. Основы"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#169]
**STR**
1. Open https://portal.qax-camp.com.ua/qa-cources/
2. Scroll to the block "[Q0. Тестирование. Основы]"
3. Pay attention to the block name language.

**ACTUAL RESULT**
On the page "QA Cources block" "Q0. Тестирование. Основы" name language is russian.

**EXPECTED RESULT**
On the page "QA Cources block" "Q0. Тестирование. Основы" name language is  NOT russian.

![tNq0Nt9xY7](https://user-images.githubusercontent.com/109384052/192292901-5213337d-a083-4b14-8b55-4ecf14717aaa.png)

**Comment by scholokov** [comment]
fixed
