### ISSUE TITLE
Regression - Check font formatting according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1695]
We need to check font formatting according to Figma.
Fonts on Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=5699-913&mode=design&t=o5VxOkp97op9u5wI-0
Table on Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=390-12775&mode=design&t=BH1fLESFGh57k4sI-0
Environment: https://www.qax-camp.com.ua/quizzes/%d1%82%d0%b5%d1%81%d1%82-%d0%b4%d0%bb%d1%8f-%d1%88%d1%80%d0%b8%d1%84%d1%82%d1%96%d0%b2/
![Шрифти](https://github.com/scholokov/qax-portal-2/assets/109460500/fdb1ac72-6f78-4eb0-a81d-3ba96f1039fa)

**Comment by DmitriiNasonov** [comment]
Testing completed. Bugs isn't found
