### ISSUE TITLE
Home Page - Create a new design "Main menu" block on Portal Figma (update)

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1696]
We need to create a new design "Main menu" block on Portal Figma (update).
Environment example: https://t.qax-camp.com.ua/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=408-22&mode=design&t=q7hECTMZMw0sCr0F-0
![Main Menu](https://github.com/scholokov/qax-portal-2/assets/109460500/68b06b35-0419-4fab-89cd-6cd97e23b01d)

**Comment by AlonaSarapina** [comment]
ready for testing
[link](https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=10048%3A149&mode=design&t=LxqDauJNaXYIdjwx-1)

**Comment by DmitriiNasonov** [comment]
Testing completed
