### ISSUE TITLE
Сalendar - Сheck the link to "Quest Комплексне тестування Outsource 1.0" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1697]
We need to сheck the link to "Quest Комплексне тестування Outsource 1.0" page. Еvent dates: 7-14-21-28 december 2023
Please check availability of requirements, functional compliance and design compliance.
Requirements: Є посилання на відповідний квест - Можна зарєеструватися - Має прийти лист з лінкою.
Environment: https://www.qax-camp.com.ua/calendars/
![Quest Комплексне тестування Outsource 1 0](https://github.com/scholokov/qax-portal-2/assets/109460500/0718ee4e-8330-4118-adcc-8ba9cb2b0a45)

**Comment by GNatala** [comment]
verified
