### ISSUE TITLE
Сalendar - Сheck the link to "QAX Portal Mobile – Практика" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1698]
We need to сheck the link to "QAX Portal Mobile – Практика" page. First event: 28 november 2023
Please check availability of requirements, functional compliance and design compliance.
Requirements: Не можна зареєструватися - Містить посилання на відповідний проект - Рекурсивне.
Початок 28.11.23 - далі без обмежень.
Environment: https://www.qax-camp.com.ua/calendars/
![QAX Portal Mobile – Практика](https://github.com/scholokov/qax-portal-2/assets/109460500/6167bf12-2195-4350-8b58-35738884aa1e)

**Comment by ODrobik** [comment]
verified
