### ISSUE TITLE
Projects - внешний вид

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#17]
Погрумить на тему - как должна выглядеть страницы с "проектами"

возможно разделить на 2 части:
текущие проекты
законченные проекты

возможно необходим какой то текст на странице? если что - запросить у Светы

https://portal.qax-camp.com.ua/projects/

**Comment by ABatalov** [comment]
Мое мнение нужно сделать лого или картинку для каждого проекта, которая будет визуально немного раскрывать проект. Разбить на две части current и resolved. Текст такой предлагаю: 
"Розділ проєкти, це розділ де ти зможеш знайти всі наші поточні та минулі проєкти. Зайшовши на проект ти зможеш ознайомитись зі всіма його ресурсами для зручного старту та ефективної роботи. Кожен наш проєкт має набір унікальних особливостей, різних product owners, різні програми для управління та різні команди, а також всі проєкти максимально наближено до реального, тому набуті скіли ти обов’язково зможеш застосувати в майбутньому.  " , Свете отправил на корректировки )

**Comment by ABatalov** [comment]
@scholokov - на скільки зараз актуальна ця таска? Чи робимо на Portal розділення для поточних та завершених проєктів?
