### ISSUE TITLE
Сalendar - Сheck the link to "Q&A" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1700]
We need to сheck the link to "Q&A" page. Еvent dates: 11-25 december 2023
Please check availability of requirements, functional compliance and design compliance.
Requirements: Не можна зареєструватися - Не має посилань.
Environment: https://www.qax-camp.com.ua/calendars/
![Q A](https://github.com/scholokov/qax-portal-2/assets/109460500/5d3651e0-b186-4568-8cc4-7e40a4c52e0d)

**Comment by DmitriiNasonov** [comment]
Testing completed
