### ISSUE TITLE
Lessons - Check lesson for "Робимо естимацію для тестування модуля Авторизації" page

### ISSUE THREAD

**Issue by steblinka1111** [scholokov/qax-portal-2#1701]
We need to check lesson for "Робимо естимацію для тестування модуля Авторизаціїї" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/mc-testing/lessons/mc-sandbox-auth-estimation/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F--%D0%BC%D0%B0%D0%B9%D1%81%D1%82%D0%B5%D1%80-%D0%BA%D0%BB%D0%B0%D1%81%D0%B8
Тестування – Майстер-класи
https://www.qax-camp.com.ua/courses/mc-testing/
<img width="872" alt="зображення" src="https://github.com/scholokov/qax-portal-2/assets/147995195/28ad5194-dcfd-4507-9215-aa1d16c9432e">

**Comment by GNatala** [comment]
verified
