### ISSUE TITLE
Interview - Сheck the course description on the "Тестова співбесіда з детальним фідбеком" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1702]
We need to check the course description on the "Тестова співбесіда з детальним фідбеком" page
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/interview/
![Тестова співбесіда з детальним фідбеком](https://github.com/scholokov/qax-portal-2/assets/109460500/bc7caf44-7cfc-4b03-a2b2-e9d3e9a7f699)

**Comment by DmitriiNasonov** [comment]
Testing completed
