### ISSUE TITLE
Design of "about us" page on Portal Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#171]
We need to add the "about us" page design to the Portal Figma.
Design on Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2090%3A286
![About us](https://user-images.githubusercontent.com/109460500/202236492-adb42315-1196-43d8-856d-c4d0b24ef4e6.png)

**Comment by AlonaSarapina** [comment]
ready for testing https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2090%3A286

**Comment by AlonaSarapina** [comment]
added tablet and mobile https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2090%3A286

**Comment by BatalovaOlha** [comment]
verified
