### ISSUE TITLE
Update design of Footer

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#172]
We need to update design of Footer according to Wiki.
Footer requirement: https://github.com/scholokov/qax-portal-2/wiki/Footer
Design on Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A22
This is an example of the design after the update:
![Footer](https://user-images.githubusercontent.com/109460500/193461210-7b45cc84-5614-431b-ac9c-5592a9e91131.jpg)

**Comment by ButKoff** [comment]
Надо обновить дизайн в соответствии с требованиями.

**Comment by AlonaSarapina** [comment]
ready for testing https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A22

**Comment by dmitryylev** [comment]
verified
