### ISSUE TITLE
"Тестування – Майстер-класи" course - "Звітуємо по тестуванню форми Реєстрації" lesson - Preview of the lesson is "default"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1726]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/courses/mc-testing/lessons/sandbox-reg-reporting/

**Actual Result**
Preview of the lesson is "default"

**Expected Result**
Preview of the lesson isn't "default"

**Additional information**
Preview in Canva is misssing
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA

**Enviroments**
Windows 10, Chrome 119.0.6045.200 (64 bit)
![Звітуємо по тестуванню форми Реєстрації – QAX Camp - Google Chrome 29 11 2023 14_45_44](https://github.com/scholokov/qax-portal-2/assets/95171672/9f42f4c1-71ad-436f-8963-1d12c3a614d0)

**Comment by DmitriiNasonov** [comment]
#858

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
