### ISSUE TITLE
Canva - "Тестування – Майстер-класи" course - Preview of the "Звітуємо по тестуванню форми Реєстрації" lesson is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1727]
**Steps of reproducing**
1. Open https://www.canva.com/design/DAFeSN9YPTM/LEJztioQWSZfPUhf_Fu37g/edit

**Actual Result**
Preview of the "Звітуємо по тестуванню форми Реєстрації" lesson is missing

**Expected Result**
Preview of the "Звітуємо по тестуванню форми Реєстрації" lesson is present

**Additional information**
https://www.qax-camp.com.ua/courses/mc-testing/

**Enviroments**
Windows 10, Chrome 119.0.6045.200 (64 bit)
![Звітуємо по тестуванню форми Реєстрації – QAX Camp - Google Chrome 29 11 2023 14_51_17](https://github.com/scholokov/qax-portal-2/assets/95171672/57a78ba8-b8d7-4fbd-8758-2a4428d555ac)

**Comment by DmitriiNasonov** [comment]
#858

**Comment by scholokov** [comment]
please retest

**Comment by DmitriiNasonov** [comment]
retested. bug report isn't actual
