### ISSUE TITLE
Reviews - Implement the "Відгуки" block on the "QA Quest" and "Тестова співбесіда" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1732]
We need to implement the Facebook comments block on the "QA Quest" and "Тестова співбесіда" page.
They should have separate information

1. Environment: https://www.qax-camp.com.ua/qa-quest/

![QA Quest](https://github.com/scholokov/qax-portal-2/assets/109460500/5ed0a9e0-af73-4b21-9195-6350317cb810)

2. Environment: https://www.qax-camp.com.ua/courses/interview/

![Співбесіда](https://github.com/scholokov/qax-portal-2/assets/109460500/91a067f9-a3d9-4145-90a8-d627f309ba5b)

**Comment by poroskundenys** [comment]
@scholokov 
Готово.
Для страниц есть два блока для добавление уникальных страниц комментариев из facebook https://prnt.sc/CIvVw5Mn4fkn. Нужно только поменять выделенное на новые параметры facebook комментраиев. Создавать новые комментарии тут https://developers.facebook.com/docs/plugins/comments/. Для курсов эти блоки тут находятся https://prnt.sc/G6JKzluzWcpo. 
Для наглядности я добавил код старых комментариев, которые используются на сайте
