### ISSUE TITLE
Сalendar -  When you click on any "Q&A" activity, the nearest future "Q&A" activity opens

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1746]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/calendars/
2. Click on any "Q&A" activity

**Actual Result**
Nearest future activity "Q&A" has opened

**Expected Result**
The "Q&A" activity page you selected has opened

**Enviroments**
Windows 10, Chrome 119.0.6045.200 (64 bit), Firefox 120.0.1 (64 bit)
Android 8.1.0, Chrome 119.0.6045.163, Firefox 120.0.1
![calendars – QAX Camp - Google Chrome 11 12 2023 13_41_26](https://github.com/scholokov/qax-portal-2/assets/95171672/092a6ed9-f58f-40f5-beb2-a088a9fdecbe)
![calendars – QAX Camp - Google Chrome 11 12 2023 13_41_36](https://github.com/scholokov/qax-portal-2/assets/95171672/51706ed5-2d82-4126-ba58-48c45af5d82c)

https://github.com/scholokov/qax-portal-2/assets/95171672/9643da2f-90c2-4e34-9003-3748cd7ea6cc

https://github.com/scholokov/qax-portal-2/assets/95171672/36deb204-7f9e-49a3-b9c2-ebc999429584

https://github.com/scholokov/qax-portal-2/assets/95171672/781c6b0c-6229-4b90-8cdd-aed83e1ab953

**Comment by DmitriiNasonov** [comment]
#1700

**Comment by scholokov** [comment]
а скрін можна?

**Comment by scholokov** [comment]
опису недостатньо. краще з прикладами
це стосовно опису
а так зверни увагу на посилання - це одна та сама подія, яка розтянута на декіка днів. тому вона і відображає останню подію

**Comment by DmitriiNasonov** [comment]
bug-report is canceled
