### ISSUE TITLE
Quest - Check quest for "Естімація - Авторизація" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1748]
We need to check quest for "Естімація - Авторизація" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/sandbox-auth/lessons/sandbox-auth-estimation/

![Естімація_](https://github.com/scholokov/qax-portal-2/assets/109460500/233a1c6f-1d2f-4f07-9152-57073a7c8932)

**Comment by GNatala** [comment]
verified
