### ISSUE TITLE
Quest - Page -"Генерація тестових даних ..." / Not underlined text of the link "https://sandbox.qax-camp.com.ua/register/ "

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1749]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/sandbox-req/lessons/sandbox-req-test-data/
2. Scroll down to the quizz  "Генерація тестових даних використовуючи техніки тест дизайну" - open it. 
3. Pay attention to the text "https://sandbox.qax-camp.com.ua/register/  " after the "Додаток, що тестується:".

**Actual result:**
Text of the link "https://sandbox.qax-camp.com.ua/register/ " is not underlined.

**Expected result:**
Text of the **link "https://sandbox.qax-camp.com.ua/register/ " is underlined.**

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=390-12775&mode=design&t=ZUByRutkM5ZfCMvY-0

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/52029195-bb75-47c3-8272-b006280ad69e)

**Comment by GNatala** [comment]
#1557

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
перевірено
