### ISSUE TITLE
Wrong word "Recruitment.." except "IT Recruiter.." on the page "About us page"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#175]
**STR**
1. Open https://github.com/scholokov/qax-portal-2/wiki/About-us-page 
2. Open https://portal.qax-camp.com.ua/about-us/ 
3. Pay attention to the first block "Що таке Camp?"/second paragraph 

**ACTUAL RESULT**
The description block "Що таке Camp?" is shown the wrong word "Recruitment.."

**EXPECTED RESULT**
The description block "Що таке Camp?" is shown the word "IT Recruiter.."

![aHkN0wLqw6](https://user-images.githubusercontent.com/109384052/192846138-c43100c4-835a-4fd6-b8f9-30a24a1414fc.png)
![ksmKIxS4qz](https://user-images.githubusercontent.com/109384052/192846142-a3998a2a-9bef-4d28-80aa-4490f3ece222.png)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
