### ISSUE TITLE
Quizz - "Створення тестової документації" / Not underlined text of the three links on the page

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1750]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/sandbox-req/lessons/sandbox-req-test-doc/quizzes/sandbox-req-test-docs/
2. Pay attention to the links: 
                                           **https://sandbox.qax-camp.com.ua/register/ 
                                              http://qaxcampqa.testrail.io/index.php?/suites/overview/28 and
                                              http://qaxcampqa.testrail.io/index.php?/suites/overview/28**
                                         
**Actual result:**
Text of the three links: 
                                           **https://sandbox.qax-camp.com.ua/register/ 
                                              http://qaxcampqa.testrail.io/index.php?/suites/overview/28 and
                                              http://qaxcampqa.testrail.io/index.php?/suites/overview/28 are not underlined.**

**Expected result:**
Text of the **three links:
                                           **https://sandbox.qax-camp.com.ua/register/ 
                                              http://qaxcampqa.testrail.io/index.php?/suites/overview/28 and
                                              http://qaxcampqa.testrail.io/index.php?/suites/overview/28 are underlined.**

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/39c5f458-f97a-4143-8d8f-2caa12a2d445)

**Comment by GNatala** [comment]
#1558

**Comment by scholokov** [comment]
а чому не одразу посилання тест?
https://www.qax-camp.com.ua/courses/sandbox-req/lessons/sandbox-req-test-data/quizzes/sandbox-req-test-data-generation/

тут проблема не у сутності Quest, а у Question? бо у квесті все нормально відображається
проблема глобальна для всіх сутнотсей "Питання", але його можна показати на саме цьому прикладі

**Comment by GNatala** [comment]
Дякую, трохи змінила. Так перевірила, що то є проблема сутності Quizz-Question, як і те що, наприклад https://sandbox.qax-camp.com.ua/register/ та інші взагалі не є лінками.

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
