### ISSUE TITLE
"Regression" lesson - The author of the lesson is "Plaksa Maksym"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1756]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/courses/testing/lessons/regression/
2. Check the lesson title font size

**Actual Result**
The author of the lesson is "Plaksa Maksym"

**Expected Result**
The author of the lesson is "Денис Щолоков"

**Additional information**
The author of the video is "Денис Щолоков"
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F

**Environments**
Windows 10, Chrome 120.0.6099.63 (64 bit)
![Regression – QAX Camp - Google Chrome 06 12 2023 16_02_54](https://github.com/scholokov/qax-portal-2/assets/95171672/727cf959-2a7b-4a51-a8e3-c6c2d7e04cc9)
![Regression – QAX Camp - Google Chrome 06 12 2023 16_03_05](https://github.com/scholokov/qax-portal-2/assets/95171672/2b2d98eb-e918-496c-963b-6b8a707ea4e2)

**Comment by DmitriiNasonov** [comment]
#1018

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
