### ISSUE TITLE
Quest - Комплексне тестування Outsource 1.0 / Spelling mistake in the word **вокинане** 

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1761]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/events/quest-outsource-1-0/
2. Scroll down to the mark **.
3. Pay attention to the sentence "Залік – це вокинане завдання ... ".

**Actual result:**
 Spelling mistake in the word **вокинане**.

**Expected result:**
 The word is written as **виконане**.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/4ed88a22-cf7f-49b3-bf87-19a3f70c16c3)

**Comment by GNatala** [comment]
#1697

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
