### ISSUE TITLE
Design - Create a design testing Сhecklist on Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1763]
We need to create a design testing checklist on Figma.
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6704-1434&mode=design&t=mhvxYFoCmcDusocO-0

This example :))

![Чек лист](https://github.com/scholokov/qax-portal-2/assets/109460500/beeda541-1fa6-43c4-9f97-062a4ae67876)

**Comment by DmitriiNasonov** [comment]
https://docs.google.com/spreadsheets/d/1TZ_nU1U8JM4i1vFT4fS50AS_fugFn1UGXDDOHqg3C-c/edit#gid=0

**Comment by DmitriiNasonov** [comment]
Task is completed
