### ISSUE TITLE
Lessons - "Параметри Екрану" / The content of 3 sections is in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1764]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/web-mobile/lessons/screens/
2. Pay attention to the content of the lesson.

**Actual result:**
 The content of the sections:  "Щільність екрану", "Орієнтація", "Розширення" is in russian.

**Expected result:**
The content of the sections:  "Щільність екрану", "Орієнтація", "Розширення" is Ukrainian.

**Requirements:**
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/247cdab2-e8d3-4b97-b2d6-74d1611a8df0)

**Comment by GNatala** [comment]
#1077

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
