### ISSUE TITLE
Lessons - Check lesson for "Testomat" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1766]
We need to check lesson for "Testomat" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/testomat/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BA%D0%BE%D1%80%D0%B8%D1%81%D0%BD%D1%96-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%B8

![Testomat](https://github.com/scholokov/qax-portal-2/assets/109460500/89ca877e-b7dc-46b5-8b2a-ddd2ae7a54d5)

**Comment by GNatala** [comment]
Verified
