### ISSUE TITLE
Courses - Check course for "Корисні програми" page (content update)

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1767]
We need to check lesson for "Корисні програми" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/qa-basic-programs/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81

![Корисні програми](https://github.com/scholokov/qax-portal-2/assets/109460500/bcd04bd1-e98d-42b3-b929-64c0697a98ed)

**Comment by GNatala** [comment]
verified
