### ISSUE TITLE
Quest - Check quest for "Комплексне тестування" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1769]
We need to check quest for "Комплексне тестування" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/qax-outsource-1-0/

![Комплексне тестування](https://github.com/scholokov/qax-portal-2/assets/109460500/b3f37d87-9f02-4d2d-a8b2-1f6c937c911a)

**Comment by GNatala** [comment]
verified
