### ISSUE TITLE
QA Courses - Потрібні 5 картинок

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#177]
Потрібні 5 картинок стандартного розміру:

самі курси можна подивитись тут:
https://portal.qax-camp.com.ua/qa-courses/
![QA course](https://user-images.githubusercontent.com/109460500/194336269-be04f49a-4d11-4897-8aa5-3c2f90939593.png)

**Comment by ButKoff** [comment]
Надо предложить варианты картинок «под курсов» на отдельной странице курсов QA. 
Пожелания от РО: Я думаю варто попередити, що це просто пропозиція варіанту оформлення, потрібно підібрати варіанти, які гармонічно впишуться в загальну концепцію сайту.

**Comment by ABatalov** [comment]
@AlonaSarapina - картинку робимо без назви курсу

**Comment by AlonaSarapina** [comment]
ready for testing https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2308%3A1473
