### ISSUE TITLE
Lessons - Check lesson for "GitHub" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1771]
We need to check lesson for "GitHub" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/github/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BA%D0%BE%D1%80%D0%B8%D1%81%D0%BD%D1%96-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%B8

![GitHub](https://github.com/scholokov/qax-portal-2/assets/109460500/b2e47d34-d884-4466-ba92-5c6618d19ea9)

**Comment by DmitriiNasonov** [comment]
Testing completed
