### ISSUE TITLE
Lessons - Check lesson for "Робимо Декомпозицію робіт для проведення Естімації" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1774]
We need to check lesson for "Робимо Декомпозицію робіт для проведення Естімації" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/mc-testing/lessons/%d1%80%d0%be%d0%b1%d0%b8%d0%bc%d0%be-%d0%b4%d0%b5%d0%ba%d0%be%d0%bc%d0%bf%d0%be%d0%b7%d0%b8%d1%86%d1%96%d1%8e-%d1%80%d0%be%d0%b1%d1%96%d1%82-%d0%b4%d0%bb%d1%8f-%d0%bf%d1%80%d0%be%d0%b2%d0%b5%d0%b4/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F--%D0%BC%D0%B0%D0%B9%D1%81%D1%82%D0%B5%D1%80-%D0%BA%D0%BB%D0%B0%D1%81%D0%B8

![Робимо Декомпозицію робіт для проведення Естімації](https://github.com/scholokov/qax-portal-2/assets/109460500/8bd46152-6357-4681-9ff9-dff0dbbd552c)

**Comment by ODrobik** [comment]
перевірено
