### ISSUE TITLE
Lessons - Check lesson for "Kickoff" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1775]
We need to check lesson for "Kickoff" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/portal-mobile/lessons/portal-m-kickoff/
Requirements: will be soon

![Kickoff](https://github.com/scholokov/qax-portal-2/assets/109460500/095de405-9d33-4e6d-9162-9b5d083944e6)

**Comment by ODrobik** [comment]
перевірено
