### ISSUE TITLE
Lessons - Check lesson for "Декомпозиція робіт для проведення Естімації" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1777]
We need to check lesson for "Декомпозиція робіт для проведення Естімації" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/portal-mobile/lessons/portal-m-work-decomposition/
Requirements: will be soon

![Декомпозиція робіт для проведення Естімації](https://github.com/scholokov/qax-portal-2/assets/109460500/d7da6449-43f9-4bca-9aea-686bbd6b6b0b)

**Comment by GNatala** [comment]
passed
