### ISSUE TITLE
Lessons - Check lesson for "Естімації" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1778]
We need to check lesson for "Естімації" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/portal-mobile/lessons/portal-m-estimation/
Requirements: will be soon

![Естімація](https://github.com/scholokov/qax-portal-2/assets/109460500/6591e927-4d22-4672-b730-d24b5c321d93)

**Comment by GNatala** [comment]
passed
