### ISSUE TITLE
Lessons - Check lesson for "Ризики" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1782]
We need to check lesson for "Ризики" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/processes/lessons/risk/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D0%B8

![Ризики](https://github.com/scholokov/qax-portal-2/assets/109460500/09a6f371-d249-4c45-be2e-fb0226693b93)

**Comment by ODrobik** [comment]
verified
