### ISSUE TITLE
Lessons - Check lesson for "Оцінка ризиків" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1783]
We need to check lesson for "Оцінка ризиків" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/portal-mobile/lessons/m-portal-risk/
Requirements: will be soon

![Оцінка ризиків](https://github.com/scholokov/qax-portal-2/assets/109460500/e9249a27-d8c9-4885-9748-c597fd2fe1b5)

**Comment by GNatala** [comment]
passed
