### ISSUE TITLE
Extra letter "c" in the company name "Ajax Systemsс" in the block "Andrey Samoilenko, Founder, Trainer" in the wiki requirement

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#181]
**STR**
1. Open https://github.com/scholokov/qax-portal-2/wiki/Our-Trainers
2. Pay attention to the block "Andrey Samoilenko, Founder, Trainer" / phrase "2017 - 2018 – Tech Recruiter в Ajax Systemsс"

**ACTUAL RESULT**
Letter "c" in the company name "Ajax Systemsс" in the block "Andrey Samoilenko, Founder, Trainer" is shown

**EXPECTED RESULT**
Letter "c" in the company name "Ajax Systemsс" in the block "Andrey Samoilenko, Founder, Trainer" is NOT shown
![eePJmuIy6J](https://user-images.githubusercontent.com/109384052/193466513-af0e54aa-8d4a-475c-89dd-61080e7d21c7.png)

**Comment by ABatalov** [comment]
Fixed

**Comment by BatalovaOlha** [comment]
verified
