### ISSUE TITLE
Lessons - "Робимо естімацію для тестування форми Реєстрації" / Spelling mistake in the word "проект"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1824]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/mc-testing/lessons/mc-sandbox-reg-estimation/
2. Pay attention to the spelling of the word "проект" in the sentence "Розбираємо яким чином вирішувати завдання “Естімація” на **проекті** Sandbox.".

**Actual result:**
 The word "проект" is written with the letter "е".

**Expected result:**
 The word "проект" is written with the letter "є".

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/dc0fa89a-9ffa-4772-b979-3d623c3694f9)

**Comment by GNatala** [comment]
#1703

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
