### ISSUE TITLE
"Процеси" course - "Kickoff" lesson - Lesson preview doesn't match Canva

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1825]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/courses/processes/lessons/kickoff/

**Actual Result**
The lesson preview doesn't match Canva

**Expected Result**
The lesson preview matches Canva

**Additional information**
https://www.canva.com/design/DAFdjgYP8G4/Fj32w2yMqdZqBcQS1z9ioA/edit

**Environments**
Windows 10, Chrome 120.0.6099.110 (64-bit)
Android 8.1.0, Chrome 120.0.6099.43
![Старий Солотвин – Long-Travel - Google Chrome 19 12 2023 14_22_47](https://github.com/scholokov/qax-portal-2/assets/95171672/e4b7788d-5887-4714-bb0b-5f659e7eb3e1)
![photo_2023-12-19_14-44-08](https://github.com/scholokov/qax-portal-2/assets/95171672/2f0a54c9-c8dd-4f79-b7b7-e259e4fae780)

**Comment by DmitriiNasonov** [comment]
#1063

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
