### ISSUE TITLE
Test "Технічний лікнеп" - Punctuation error in the text of the assignment 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#185]
STR 
1. Open https://portal.qax-camp.com.ua/courses/recruiter-program/lessons/%d1%82%d0%b5%d1%85%d0%bd%d1%96%d1%87%d0%bd%d0%b8%d0%b9-%d0%bb%d1%96%d0%ba%d0%bd%d0%b5%d0%bf-%d0%b4%d0%bb%d1%8f-%d1%80%d0%b5%d0%ba%d1%80%d1%83%d1%82%d0%b5%d1%80%d1%96%d0%b2/quizzes/technical_lecture_test/
2. Pay attention to «Напишіть склад команди розробки»

Actual result: no point at the end of the sentence 
Expected result: there is a point at the end of the sentence 

<img width="1440" alt="Снимок экрана 2022-10-03 в 1 59 21 PM" src="https://user-images.githubusercontent.com/110661667/193562790-bc2101b4-4708-4b2d-9fee-d82e6df31233.png">

**Comment by Xalep4ik** [comment]
Verified
