### ISSUE TITLE
Home page - Implement a new design for the "Toolbar" block

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1857]
We need to Implement a new design for the "Toolbar" block.

You can use, for example: 
https://t.qax-camp.com.ua/

Product environment: https://www.qax-camp.com.ua

Probably better to use test env first:
https://t.qax-camp.com.ua/

Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=10048-108&mode=design&t=VMqUJcDbtvaoh4d1-0

![Tools bar](https://github.com/scholokov/qax-portal-2/assets/109460500/7cee5299-bbb2-436d-b658-d6e1e03fc444)

**Comment by ButKoff** [comment]
#1607

**Comment by poroskundenys** [comment]
Готово.
Дизайн https://www.figma.com/file/2JlqZybc4fOvZcPT7oiqrg/Portal-design?node-id=10516%3A1886&mode=dev

**Comment by DmitriiNasonov** [comment]
Testing completed
