### ISSUE TITLE
QA Quest. Додаток Outsource 1.0/ "https://app.testomat.io/projects/qax-outsource-1-0/" URL is not displayed as link in the "Задача" section of the "Тестування" stage

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1863]
Steps to reproduce:

1. Open page https://www.qax-camp.com.ua/courses/qax-outsource-1-0/
2. Check the "Тестування" stage of the "Комплексне тестування" quest
3. scroll down to the "Задача" section of the "Тестування" stage
4. Pay attention to the "https://app.testomat.io/projects/qax-outsource-1-0/" URL in the "Задача" section

Actual Result: "https://app.testomat.io/projects/qax-outsource-1-0/" URL **is not** displayed as link in the "Задача" section

Expected Result: "https://app.testomat.io/projects/qax-outsource-1-0/" URL **is** displayed as link in the "Задача" section 

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/93706781-bad6-4802-bd1e-e3abe1623f61)

**Comment by ODrobik** [comment]
#1769

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
