### ISSUE TITLE
QA Quest. Додаток Outsource 1.0/ "https://github.com/scholokov/qax-outsource-1-0/issues" URL is not displayed as link in the "Задача" section of the "Тестування" stage 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1864]
Steps to reproduce:

1. Open page https://www.qax-camp.com.ua/courses/qax-outsource-1-0/
2. Check the "Тестування" stage of the "Комплексне тестування" quest
3. Scroll down to the "Задача" section of the "Тестування" stage
4. Pay attention to the "https://github.com/scholokov/qax-outsource-1-0/issues" URL in the "Задача" section

Actual Result: "https://github.com/scholokov/qax-outsource-1-0/issues" URL is not displayed as link in the "Задача" section

Expected Result: "https://github.com/scholokov/qax-outsource-1-0/issues" URL is displayed as link in the "Задача" section

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/9545c13b-5408-4549-b1d0-7d139ea32287)

**Comment by ODrobik** [comment]
#1769

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
