### ISSUE TITLE
Сontainer - Сheck the width of the container on the "About us" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1866]
We need to check the width of the container on the "About us" page.
The maximum width of the container should be 1270px
Environment: https://www.qax-camp.com.ua/about-us-2/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.3.-About-us-page
![About us](https://github.com/scholokov/qax-portal-2/assets/109460500/653a6301-7db0-4d9c-96fe-a8b446ab2aab)

**Comment by ODrobik** [comment]
verified
