### ISSUE TITLE
Сontainer - Сheck the width of the container on the "Courses/..." page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1867]
We need to check the width of the container on **ALL** "Courses/..." page.
The maximum width of the container should be 1270px
Environment example: https://www.qax-camp.com.ua/courses/q6-basic/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81

![Курсы](https://github.com/scholokov/qax-portal-2/assets/109460500/41e0ebf3-fbb3-49e7-9947-85e95a5ab393)

**Comment by DmitriiNasonov** [comment]
Testing is complete. no bugs found
