### ISSUE TITLE
Сontainer - Сheck the width of the container on the "Lessons/..." page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1868]
We need to check the width of the container on **ALL** "Lessons/..." page.
The maximum width of the container should be 1270px
Environment example: https://www.qax-camp.com.ua/courses/q6-basic/lessons/who-is-qa/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA

![Урок](https://github.com/scholokov/qax-portal-2/assets/109460500/a6085987-a7c6-44c1-b6d2-b01609040d81)

**Comment by DmitriiNasonov** [comment]
checked. bugs aren't found
