### ISSUE TITLE
Сontainer - Сheck the width of the container on the "Esse/..." page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1869]
We need to check the width of the container on **ALL** "Esse/..." page.
The maximum width of the container should be 1270px
Requirements: https://github.com/scholokov/qax-portal-2/wiki

![Essay](https://github.com/scholokov/qax-portal-2/assets/109460500/fb3aa983-4786-4c55-9729-29bfb8cf16bd)

**Comment by GNatala** [comment]
verified
