### ISSUE TITLE
Update image on "about us" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#187]
We need to update image on "about us" page.
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2090%3A286

**Comment by ButKoff** [comment]
Надо обновить картинку «посвящение в джедаи» на новую. 
Предложенный вариант утверждён и других вариантов не требует.

**Comment by AlonaSarapina** [comment]
ready for testing https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2090%3A286

**Comment by ButKoff** [comment]
not actual
