### ISSUE TITLE
Lessons - Check lesson for "Види, методи та рівні тестування" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1873]
We need to check new section "Team Interview".
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-02-testing-types/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#q2-%D0%B1%D0%B0%D0%B7%D0%BE%D0%B2%D0%B8%D0%B9-%D0%BA%D1%83%D1%80%D1%81-qa

![Види, методи та рівні тестування](https://github.com/scholokov/qax-portal-2/assets/109460500/206fb70a-844b-42aa-bd66-011213d3dd0d)

**Comment by ODrobik** [comment]
verified
