### ISSUE TITLE
Lessons - "Djinni – Яка його користь?" / The author of the lesson is Kazarinova Daria

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1878]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/cv/lessons/djinni/
2. Scroll down to the text "Автор: Kazarinova Daria".
3. Pay attention to the name and surname.

**Actual result:**
 The author of the lesson is Kazarinova Daria.

**Expected result:**
**The author of the lesson is Денис Щолоков.**

**Requirements:** 
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%96%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B8-%D0%BF%D0%BE%D1%88%D1%83%D0%BA%D1%83-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D1%96%D0%B9-%D0%BF%D1%96%D0%B4%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B4%D0%BE-%D0%BF%D1%80%D0%BE%D1%85%D0%BE%D0%B4%D0%B6%D0%B5%D0%BD%D0%BD%D1%8F-%D1%81%D0%BF%D1%96%D0%B2%D0%B1%D0%B5%D1%81%D1%96%D0%B4%D0%B8-%D1%81%D1%82%D0%B2%D0%BE%D1%80%D0%B5%D0%BD%D0%BD%D1%8F-%D1%81v

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/7d384f4e-6595-4a10-b57d-421cee26b73f)

**Comment by GNatala** [comment]
#1109

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
