### ISSUE TITLE
Quest - Сheck for new "QA Quest" page updates

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1879]
We need to check for new "QA Quest" page updates.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/qa-quest/

![Quest](https://github.com/scholokov/qax-portal-2/assets/109460500/5d0f7245-d540-4142-a7d3-bb3daf3fd7fa)

**Comment by GNatala** [comment]
verified
