### ISSUE TITLE
Certificate / The certificate for the quest "Database - User CRUD" is loaded instead of the certificate for the quest "Тестування валідації форми “Реєстрація”"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1880]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/sandbox-req/
2. Scroll down and press the certificate download button.
3. Pay attention to the content of the certificate.

**Actual result:**
The certificate for the quest "Database - User CRUD" is loaded instead of the certificate for the quest "Тестування валідації форми “Реєстрація"”.

**Expected result:**
The corresponding certificate is downloaded for the quest "Тестування валідації форми “Реєстрація"”.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

https://github.com/scholokov/qax-portal-2/assets/101987790/2c32b691-3dbf-427f-aa82-e1310703f970

![image](https://github.com/scholokov/qax-portal-2/assets/101987790/d1343d8c-ff37-496c-9358-96082cb4ad4c)

**Comment by GNatala** [comment]
#1609

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
