### ISSUE TITLE
Lesson "IT Vocabulary – АйТі Сленг"/ "\" symbol is displayed in the Mob view definition

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1882]
Steps to Reproduce:

1. Open page https://www.qax-camp.com.ua/courses/processes/lessons/it-vocabulary/
2. Pay attention to the"\" symbol in the Mob view definition

Actual Result: **" \ "** symbol is displayed in the **Mob view** definition

Expected Result: **" / "** symbol is displayed in the **Mob view** definition

Environment:
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/ad5fd170-ac73-40dd-b90b-80197e2bcf82)

**Comment by ODrobik** [comment]
#938

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
