### ISSUE TITLE
Lesson "IT Vocabulary – АйТі Сленг"/ "Зацікавлена сторона" text is displayed does not contain brackets "( )"  in the Stakeholder definition

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1884]
Steps to Reproduce:

1. Open page https://www.qax-camp.com.ua/courses/processes/lessons/it-vocabulary/
2. Pay attention to the  "Зацікавлена сторона" text in the Stakeholder definition

Actual Result:  "Зацікавлена сторона" text is displayed does not contain brackets "( )"  in the Stakeholder definition

Expected Result:  "(Зацікавлена сторона)" text is displayed in the Stakeholder definition

Environment:
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/8491808a-51a1-49a7-95e5-ba4686d8eb5d)

**Comment by ODrobik** [comment]
#938

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
