### ISSUE TITLE
Lesson "IT Vocabulary – АйТі Сленг"/ "Тестове покриття" text is displayed does not contain brackets "( )" in the Test coverage definition

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1885]
Steps to Reproduce:

1. Open page https://www.qax-camp.com.ua/courses/processes/lessons/it-vocabulary/
2. Pay attention to the "Тестове покриття" text in the Test coverage definition

Actual Result: "Тестове покриття" text is displayed does not contain brackets "( )" in the Test coverage definition

Expected Result: "(Тестове покриття)" text is displayed in the Test coverage definition

Environment:
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/decb3bc9-1b2d-468d-993a-165847be1624)

**Comment by ODrobik** [comment]
#938

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
