### ISSUE TITLE
Lesson "IT Vocabulary – АйТі Сленг"/ "Інтерфейс користувача" text is displayed does not contain brackets "( )" in the UI definition

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1886]
Steps to Reproduce:

1. Open page https://www.qax-camp.com.ua/courses/processes/lessons/it-vocabulary/
2. Pay attention to the "Інтерфейс користувача" text in the UI definition

Actual Result: "Інтерфейс користувача" text is displayed does not contain brackets "( )" in the UI definition

Expected Result: "(Інтерфейс користувача)" text is displayed in the UI definition

Environment:
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/ac43a299-1aca-49f8-b7f1-433ff04b69a3)

**Comment by ODrobik** [comment]
#938

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
