### ISSUE TITLE
Lesson "IT Vocabulary – АйТі Сленг"/ "()" characters are displayed in the snake_case definition

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1887]
Steps to Reproduce:

1. Open page https://www.qax-camp.com.ua/courses/processes/lessons/it-vocabulary/
2. Pay attention to the "()" characters in the snake_case definition

Actual Result: "**()**" characters is displayed in the **snake_case** definition

Expected Result: "**_**" character is displayed in the **snake_case** definition

Environment:
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/cede747b-5579-4e1c-9133-df0a45983188)

**Comment by ODrobik** [comment]
#938

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
