### ISSUE TITLE
Lesson "IT Vocabulary – АйТі Сленг"/ "д." character is displayed in the "foo_bar, hello_world і т.д. д." text in the snake_case definition

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1888]
Steps to Reproduce:

1. Open page https://www.qax-camp.com.ua/courses/processes/lessons/it-vocabulary/
2. Pay attention to the "д." character in the "foo_bar, hello_world і т.д. д." text

Actual Result: "д." characters is displayed in the "foo_bar, hello_world і т.д. д." text in the snake_case definition

Expected Result: "д." character is not displayed "foo_bar, hello_world і т.д." in the snake_case definition

Environment:
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/d0c33abc-a439-4dcb-9ab7-c19e4196f06d)

**Comment by ODrobik** [comment]
#938

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
