### ISSUE TITLE
Create new images for Home page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#189]
We need to create new images for Home page.
Design on Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A22
This is approved an design:
![Home](https://user-images.githubusercontent.com/109460500/198308838-fa7b5e0b-453f-48f4-89a8-3288b7887d0c.png)

**Comment by AlonaSarapina** [comment]
Два нові макети з новими ілюстраціями на вибір 
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2259%3A817
