### ISSUE TITLE
Lessons - "Evernote" / Spelling mistake оf the word "проект" and its variants in the content

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1892]
**Steps to reproduce:**

1. Open  https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/evernote/
2. Find all variants of the word "проект"  in the content. **It appears 2 times.**
3. Pay attention to the spelling of the words "проект".

**Actual result:**
 The word "проект" and its variants are written with the letter "е" - 2 times.

**Expected result:**
 The word "проект" and its variants are written with the letter "є" - 2 times.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/ddcde63a-52b4-4331-9f4c-836049ce5b2d)

**Comment by GNatala** [comment]
#1107

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
