### ISSUE TITLE
Наши тренеры - концепция

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#19]
Утвердить с Светой - содержимое страницы

текущая имплементация
https://qax-camp.com.ua/our_trainers.php

**Comment by ABatalov** [comment]
Передал Свете, чтобы она внесла свои правки на страницу. Но @scholokov есть вопрос оставляем ли мы Олесю, Лену? Возможно нужно добавить нового тренера Артема (если не ошибаюсь в имени)?

**Comment by scholokov** [comment]
на данный момент нам нужен "типовой дизайн"
т.е. например как выглядят тренера с разным количеством информации.
а уже кто там конретно будет - вопрос контента

**Comment by scholokov** [comment]
Олесю, Лену - убираем

**Comment by ABatalov** [comment]
Ок, принято )
