### ISSUE TITLE
Test «Рівні тестування» - Grammatical error in the question about acceptance testing

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#190]
STR 
1. Open https://portal.qax-camp.com.ua/quizzes/q5-test-levels/
2. Click start
3. Pay attention to Що з нище переліченого 

Actual result: Що з нище переліченого відноситься 
Expected result: Що з нижче перерахованого належить до

<img width="1440" alt="Снимок экрана 2022-10-03 в 6 00 20 PM" src="https://user-images.githubusercontent.com/110661667/193614896-e6a2e227-3b6d-461f-9116-40d5dbf12c57.png">

**Comment by scholokov** [comment]
fixed

**Comment by Xalep4ik** [comment]
Verified
