### ISSUE TITLE
Test «Рівні тестування» - Punctuation error  in the question about acceptance testing

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#191]
STR 
1. Open https://portal.qax-camp.com.ua/quizzes/q5-test-levels/
2. Click start
3. Pay attention to no colon at the end of the question

Actual result: тестування 
Expected result: тестування: 

<img width="1440" alt="Снимок экрана 2022-10-03 в 6 27 23 PM" src="https://user-images.githubusercontent.com/110661667/193616404-c58f8afb-96ce-42b4-9058-5f40d1b4f3aa.png">

**Comment by scholokov** [comment]
fixed

**Comment by Xalep4ik** [comment]
Verified
