### ISSUE TITLE
Test/ The "Next" button is displayed in the lower left corner of the page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1912]
Steps to reproduce:

1. Open page https://www.qax-camp.com.ua/courses/q6-basic/lessons/who-is-qa/
2. Choose the "Тестувальник. Хто це?" test 
3. Pay attention to the "Next" button in the lower left corner of the page

Actual Result: the **"Next" button** in the lower left corner of the page

Expected Result: the **"Далі" button** in the lower left corner of the page

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/a9a33b27-2364-4e48-af89-48c9a524ce82)

**Comment by ODrobik** [comment]
#1916

**Comment by poroskundenys** [comment]
Готово

**Comment by ODrobik** [comment]
перевірено
