### ISSUE TITLE
Test - Check test for "Тестувальник. Хто це?" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1916]
We need to check test for "Тестувальник. Хто це?" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/q6-basic/
Requirements: https://qaxm.atlassian.net/wiki/spaces/PM/pages/10485769/QA

![Тестувальник](https://github.com/scholokov/qax-portal-2/assets/109460500/75e1914b-e5b6-4afd-a744-5fbddc9c476b)

**Comment by ODrobik** [comment]
перевірено
