### ISSUE TITLE
Test - Check test for "Види, методи та рівні тестування" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1917]
We need to check test for "Види, методи та рівні тестування" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/q6-basic/
Requirements: https://qaxm.atlassian.net/wiki/spaces/PM/pages/10485769/QA

![Види та методи](https://github.com/scholokov/qax-portal-2/assets/109460500/47eaf39e-6475-4b40-bebd-c37b071d8ec3)

**Comment by GNatala** [comment]
verified
