### ISSUE TITLE
Test «Рівні тестування» - Grammatical error in the question about testing

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#192]
STR 
1. Open https://portal.qax-camp.com.ua/quizzes/q5-test-levels/
2. Click start
3. Pay attention to Що з нище переліченого 

Actual result: Що з нище переліченого 
Expected result: Що з нижче перерахованого 

<img width="1363" alt="Снимок экрана 2022-10-03 в 6 29 09 PM" src="https://user-images.githubusercontent.com/110661667/193617717-e61259a9-052f-4b23-8da7-4ffc4d562b17.png">
<img width="1440" alt="Снимок экрана 2022-10-03 в 6 32 28 PM" src="https://user-images.githubusercontent.com/110661667/193617744-0c4e5e1c-4959-41e9-a821-038288d8fd01.png">
<img width="1440" alt="Снимок экрана 2022-10-03 в 6 32 57 PM" src="https://user-images.githubusercontent.com/110661667/193617770-29544250-9a45-4820-bc09-2ad4bfc19305.png">

**Comment by Xalep4ik** [comment]
Verified
