### ISSUE TITLE
Test - Check test for "Defect" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1920]
We need to check test for "Defect" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/q6-basic/
Requirements: https://qaxm.atlassian.net/wiki/spaces/PM/pages/10485769/QA

![Defect](https://github.com/scholokov/qax-portal-2/assets/109460500/8302cb83-ee07-42f2-9369-84abfc9e5b4b)

**Comment by DmitriiNasonov** [comment]
Testing completed
