### ISSUE TITLE
Test - Check test for "Тестова документація: чек-лісти та тест-кейси" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1921]
We need to check test for "Тестова документація: чек-лісти та тест-кейси" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/q6-basic/
Requirements: https://qaxm.atlassian.net/wiki/spaces/PM/pages/10485769/QA

![Тестова документація](https://github.com/scholokov/qax-portal-2/assets/109460500/e6b881c2-f554-4743-a4ae-869f398b3082)

**Comment by DmitriiNasonov** [comment]
Testing completed
