### ISSUE TITLE
Checkout page - When you click on the "Сюди" button, the field for entering a promotional code does NOT appear

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1922]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/checkout/
2. Click on "Сюди" button

**Actual Result**
When you click on the "Сюди" button, a field for entering a promotional code appears

**Expected Result**
When you click on the "Сюди" button, the field for entering a promotional code does NOT appear

**Additional information**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6398-1146&mode=design&t=TByD2tm1NIDgmwHt-0
The "Сюди" button has the "https://www.qax-camp.com.ua/checkout/#" link

**Environments**
Windows 10, Chrome 120.0.6099.217 (64 bit)
Android 8.1.0, Chrome 120.0.6099.210
![Portal design – Figma - Google Chrome 16 01 2024 15_52_35](https://github.com/scholokov/qax-portal-2/assets/95171672/3c53cb33-adaf-42de-8092-8a2099b2a415)
![Portal design – Figma - Google Chrome 16 01 2024 15_51_59](https://github.com/scholokov/qax-portal-2/assets/95171672/6f226692-b85d-4147-8a07-096055189ba6)
![photo_2024-01-16_15-59-29](https://github.com/scholokov/qax-portal-2/assets/95171672/3ce9ae52-5f96-47c7-96a5-bfe29c7ba353)

**Comment by ODrobik** [comment]
#1608

**Comment by poroskundenys** [comment]
Готово

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
