### ISSUE TITLE
Test "Види, методи та рівні тестування"/ Summary of test results is displayed in English

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1924]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-02-testing-types/quizzes/q5-test-types/
2. Click on "Розпочати тест" under the picture.
3. Test is opened.
4. Click on the last question of the test.
5. Click on the button "Finish Тест". 
6. Summary of test results is displayed.
7. Pay attention to the language of the Summary.

**Actual result:**
Summary of test results is displayed in **English.**

**Expected result:**
Summary of test results is displayed in **Ukrainian.**

**Requirements:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=1212-66&mode=design&t=Y7xjVIe4vEmuU4T2-0

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/cdb20863-380a-4ba4-b78e-2a9c1dfe7ec9)

**Comment by GNatala** [comment]
#1917

**Comment by scholokov** [comment]
оновіть буд ласка скріни відностно нового дизайну

**Comment by GNatala** [comment]
not actual
