### ISSUE TITLE
Test "Види, методи та рівні тестування"/ The name of the button is "Finish Тест"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1925]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-02-testing-types/quizzes/q5-test-types/
2. Click on "Розпочати тест" under the picture.
3. Test is opened.
4. Click on the last question of the test.
5. Pay attention to the button "Finish Тест". 

**Actual result:**
The name of the button is "Finish Тест".

**Expected result:**
The name of the button is "**Закінчити тест**".

**Requirements:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=931-91&mode=design&t=0BDLXAJSLk8aX677-0

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/9a100957-9461-4aca-9b33-04b49d2cdfa3)

**Comment by GNatala** [comment]
#1917

**Comment by scholokov** [comment]
Кнопка має називатися "Завершити"
оновіть буд ласка тіло

**Comment by GNatala** [comment]
not actual
