### ISSUE TITLE
Test "Види, методи та рівні тестування"/ The name of the button is "Натисніть, щоб продовжити"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1927]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-02-testing-types/quizzes/q5-test-types/
2. Click on "Розпочати тест" under the picture.
3. Test is opened.
4. Click on the last question of the test.
5. Click the button "Finish Тест".
6. Pay attention to the button "Натисніть, щоб продовжити". 

**Actual result:**
 The name of the button is "Натисніть, щоб продовжити.

**Expected result:**
 The name of the button is "**Далі**".

**Requirements:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=1218-415&mode=design&t=I4bdcsYXNDoIz4N3-0

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/7de7d2f2-d905-4b19-a0a0-81f031a2d220)

**Comment by GNatala** [comment]
#1917

**Comment by scholokov** [comment]
онововися дизайн. оновіть буд ласка скріни

**Comment by GNatala** [comment]
not actual
