### ISSUE TITLE
Test "Види, методи та рівні тестування"/ Missed style of the button "Далі"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1928]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-02-testing-types/quizzes/q5-test-types/
2. Click on "Розпочати тест" under the picture.
3. Test is opened.
4. Click on the last question of the test.
5. Click the button "Finish Тест".
6. Pay attention to the style of the button "Далі". 

**Actual result:**
The style of the button "Далі" does not match Figma.

**Expected result:**
The style of the button "Далі" does not match Figma.

**Requirements:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=1218-415&mode=design&t=I4bdcsYXNDoIz4N3-0

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/18df6fd3-5bf3-4474-a8f8-4c708e2236dc)
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/72d3a43b-e11a-4599-8cb5-2d403ee5a1f0)

**Comment by GNatala** [comment]
#1917

**Comment by scholokov** [comment]
оновився дизайн. оновіть буд ласка скріни

**Comment by GNatala** [comment]
not actual
