### ISSUE TITLE
Test "Види, методи та рівні тестування"/ Missed position of the button "Переглянути питання"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1929]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-02-testing-types/quizzes/q5-test-types/
2. Click on "Розпочати тест" under the picture.
3. Test is opened.
4. Click on the last question of the test.
5. Click the button "Finish Тест".
6. Pay attention to the position of the button "Переглянути питання". 

**Actual result:**
First appears the button "Далі"  and then appears the button "Переглянути питання".

**Expected result:**
First appears the button "Переглянути питання"  and then appears the button "Далі".

**Requirements:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=1218-415&mode=design&t=I4bdcsYXNDoIz4N3-0

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/12372873-9738-4e9f-ae1f-b74f7d96360a)

**Comment by GNatala** [comment]
#1917

**Comment by scholokov** [comment]
оновився дизайн. оновіть буд ласка скріни

**Comment by GNatala** [comment]
not actual
