### ISSUE TITLE
No possibility choose a mobile code from another country  in the registration form 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#193]
**STR**
1. Open https://www.qax-camp.com.ua/#write_to_us
2. Try to choose a mobile operator foreign country

**ACTUAL RESULT**
It is NOT possible to select a mobile operator code of another country.

**EXPECTED RESULT**
It is possible to select a mobile operator code of another country.

**NOTE**:
1. Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=1412%3A318
2. Pay attention to the registration form 
3. Open https://github.com/scholokov/qax-portal-2/wiki/Form and pay attention to the form requirements

![7yyX6i0b1R](https://user-images.githubusercontent.com/109384052/194003925-0e042e25-061f-4dc8-80bd-d44db956fb63.png)
![N7CjoBf2yG](https://user-images.githubusercontent.com/109384052/194003933-7d69bf85-5028-4b59-9cfd-b781b46db45c.png)
![RMDdVmT23V](https://user-images.githubusercontent.com/109384052/205658319-2a1edd01-dda1-4743-a725-81df8bd5f659.png)

**Comment by scholokov** [comment]
Please retest

**Comment by BatalovaOlha** [comment]
@scholokov можливості вибрати Код країни немає 
![KUbdePaefV](https://user-images.githubusercontent.com/109384052/204823900-7ae19891-7bf8-4c2e-a3b2-3af3da0bc42a.png)
