### ISSUE TITLE
Suggestion - After logging in, the user stays in the personal account

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1930]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/current_cources/
2. Click on "Увійти"  in the main menu.
3. The login form is open.
4. Enter your credentials - click "Увійти".
5. Pay attention to the current page - Personal account. 

**Actual result:**
After logging in, the user stays in the personal account.

**Expected result:**
After logging in, the user is automatically returned to the start link page as example https://www.qax-camp.com.ua/current_cources/.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/99119a59-ddc6-483c-9bb1-0bba775a95c5)

**Comment by scholokov** [comment]
зроблено редірект на стартову сторінку

**Comment by GNatala** [comment]
passed
