### ISSUE TITLE
Login page/ The size of the button "Увійти" is 210х43

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1932]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/login/
2. Pay attention to the size of the button "Увійти". 

**Actual result:**
The size of the button "Увійти" is  210х43.

**Expected result:**
The size of the button "Увійти" is 116х41.

**Requirements:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=2129-749&mode=design&t=7lxnYSnxVaANSDFI-0

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/f161688e-3428-4b5d-8baf-41febeb7d7b7)

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
перевірено
