### ISSUE TITLE
Login page/ Font weight of the name of the button "Увійти" is 400

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1933]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/login/
2. Pay attention to the font weight of the name of the button "Увійти". 

**Actual result:**
Font weight of the name of the button "Увійти" is 400.

**Expected result:**
Font weight of the name of the button "Увійти" is 500.

**Requirements:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=2129-749&mode=design&t=7lxnYSnxVaANSDFI-0

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://github.com/scholokov/qax-portal-2/assets/101987790/1cca40ef-37c1-4c21-9c31-b9a48f8bfa08)

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
passed
