### ISSUE TITLE
Login page/ Marked checkBox "Запам’ятати мене" does not match Figma

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1934]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/login/
2. Mark checkBox "Запам’ятати мене".
3. Pay attention to the checkBox style. 

**Actual result:**
Marked checkBox "Запам’ятати мене" does not match Figma.

**Expected result:**
Marked checkBox "Запам’ятати мене" matches Figma.

**Requirements:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=2178-1133&mode=design&t=cyf1xdpllpuCNSP5-0

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://github.com/scholokov/qax-portal-2/assets/101987790/c1d075f6-7470-4f1d-8bb6-74f5b4061ac6)

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
перевірено
