### ISSUE TITLE
Home page / "досягнення" word  is displayed in the Content of the "Ти лише робиш перші кроки до успішної кар’єри в ІТ?" card of the Home page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1943]
**Steps to reproduce:**

1. Open page https://www.qax-camp.com.ua/
2. Pay attention to the  "досягнення" word in the Content of the "Ти лише робиш перші кроки до успішної кар’єри в ІТ?" card 

**Actual result:** "досягнення" word is displayed in the Content ща the "Ти лише робиш перші кроки до успішної кар’єри в ІТ?" card 

**Expected result:** "досягнеш" word is displayed in the Content of the "Ти лише робиш перші кроки до успішної кар’єри в ІТ?" card 

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/569563b1-acf0-40c4-bc52-8bee82c6a545)

**Comment by ODrobik** [comment]
#1923

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
