### ISSUE TITLE
Діючі командні проєкти/ The "₴2,700Every 1 місяць" text is displayed in the "QAX Travel 2.0" page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1944]
**Steps to reproduce:**

1. Open page https://www.qax-camp.com.ua/qa-quest/
2. Choose the "Обрати" button the "QAX Travel 2.0" project of the "Діючі командні проєкти" section
3. Pay attention to the "₴2,700Every 1 місяць" text in the "QAX Travel 2.0" page

**Actual Result:** The "₴2,700Every 1 місяць" text is displayed in the "QAX Travel 2.0" page

**Expected Result:** The "₴2,700/місяць" text is displayed in the "QAX Travel 2.0" page

**Requirements:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=5444-750&mode=design&t=SGL3aTJYB3VDnufc-0

**Environment:**
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/763850ab-acc8-46a9-a58e-a7059aaa8869)

**Comment by poroskundenys** [comment]
готово

**Comment by ODrobik** [comment]
verified
