### ISSUE TITLE
Tests - "Тест: Тестова документація: чек-лісти та тест-кейси" test - The student has 20 minutes on the timer to complete the test

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1945]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-test-documentation/quizzes/q5-test-documentation/
2. Start test
3. Pay attention to the timer

**Actual Result**
The student has 20 minutes on the timer to complete the test

**Expected Result**
The student has 25 minutes on the timer to complete the test

**Additional information**
https://qaxm.atlassian.net/wiki/spaces/PM/pages/10485769/QA

**Environments**
Windows 10, Chrome 121.0.6167.86 (64 bit)
Android 8.1.0, Chrome 120.0.6099.230
![Тест_ Тестова документація_ чек-лісти та тест-кейси – QAX Camp - Google Chrome 24 01 2024 14_21_32](https://github.com/scholokov/qax-portal-2/assets/95171672/0bfb2e03-d6c0-4ad8-ae03-1d9ef48a0851)
![photo_2024-01-24_17-34-28](https://github.com/scholokov/qax-portal-2/assets/95171672/77df63c5-4036-4783-8fbe-a8741a1f0b6a)

**Comment by DmitriiNasonov** [comment]
#1927

**Comment by DmitriiNasonov** [comment]
#1921

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
