### ISSUE TITLE
Email - Check the email after registration

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1946]
We need to check the email after registration.
Please check availability of requirements, functional compliance and design compliance.
**It's important to check this:**
- a letter should come after registration;
- the design on mobile devices and computers should be different.

Environment: https://www.qax-camp.com.ua/register/
Requirements: https://qaxm.atlassian.net/wiki/spaces/PM/pages/16121884

<img width="516" alt="Після створення нового акаунту" src="https://github.com/scholokov/qax-portal-2/assets/109460500/cef0c0a5-fa16-4e05-9b10-ac85d2e8bce9">

**Comment by GNatala** [comment]
passed
