### ISSUE TITLE
Checkout / Mobile/ "25 px" distance of the "Ваше замовлення" and "замовлення" lines of text are displayed on the Checkout page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1949]
**Steps to reproduce:**

1. Open page https://www.qax-camp.com.ua/checkout/
2. Pay attention to the distance of the "Ваше замовлення" and "замовлення" lines of text on the Checkout page

**Actual result:** "25 px" distance of the "Ваше замовлення" and "замовлення" lines of text are displayed on the Checkout page

**Expected result:** "40 px" distance of the "Ваше замовлення" and "замовлення" lines of text are displayed on the Checkout page

**Requirements:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=6423%3A1770&mode=dev
 
**Environment:**
Samsung Galaxy A31
Android 12
Chrome 120.0.6099.211

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/b88ee5b8-047c-405a-bf4c-338d0599fdea)

**Comment by ODrobik** [comment]
#1608

**Comment by poroskundenys** [comment]
Готово

**Comment by ODrobik** [comment]
Перевірено
