### ISSUE TITLE
Checkout / Mobile/ "500 px" font-weight of the "Платіжні дані" and "Ваше замовлення" and "Деталі оплати"  lines of text are displayed on the Checkout page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1951]
**Steps to reproduce:**

1. Open page https://www.qax-camp.com.ua/checkout/
2. Pay attention to the font-weight of the "Платіжні дані", "Ваше замовлення" and "Деталі оплати" lines of text on the Checkout page

**Actual result:** "500 px" font-weight of the "Платіжні дані" and "Ваше замовлення" and "Деталі оплати"  lines of text are displayed on the Checkout page

**Expected result:** "700 px" font-weight of the "Платіжні дані", "Ваше замовлення" and "Деталі оплати"  lines of text are displayed on the Checkout page

**Requirements**: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=6423%3A1770&mode=dev

**Environment:**
Samsung Galaxy A31
Android 12
Chrome 120.0.6099.211

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/50172619-175a-4892-8c59-fe72a7583c53)

**Comment by ODrobik** [comment]
#1608

**Comment by poroskundenys** [comment]
Готово

**Comment by ODrobik** [comment]
Перевірено
