### ISSUE TITLE
The hryvnia sign "₴" font size is 16px in the cost of the Course/Quest/Subscription

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1955]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q6-basic/ or any paid Course/Quest/Subscription.
2. Pay attention to thryvnia sign "₴" font size is 16px in the cost of the Course. 

**Actual result:**
The hryvnia **sign "₴" font size is 16px** in the cost of the Course/Quest/Subscription.

**Expected result:**
The hryvnia **sign "₴" font size is 24px** in the cost of the Course/Quest/Subscription.

**Requirements:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=390-1036&mode=design&t=BZSNvpd28HIghPGQ-0

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/f3901822-d1b0-4853-80ce-cf83ea246c3e)

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
passed
