### ISSUE TITLE
Lesson "Компільовані та інтерпретовані мови програмування"/ The name and surname of the lesson's author "Scholokov Denis" is written in English

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#1957]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/web-mobile/lessons/comp-lang/
2. Scroll down to the text "Автор: Scholokov Denis".
3. Pay attention to the name and surname.

**Actual result:**
The name and surname of the lesson's author "Scholokov Denis" is written in English.

**Expected result:**
The name and surname of the lesson's author  "Денис Щолоков" is written in Ukrainian.

**Requirements:** 
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#web--mobile

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/0a2f740d-0fbf-416c-859c-df3fdec61a7e)

**Comment by GNatala** [comment]
#1122

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
The issue is reproduced.

**Attachment:**

![image](https://github.com/scholokov/qax-portal-2/assets/101987790/781c7e7b-d847-4809-9590-6466d4880268)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
