### ISSUE TITLE
Test - Виды Тестирования - Punctuation error in the question about functional testing

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#196]
1. Open https://portal.qax-camp.com.ua/quizzes/q5-test-types/
2. Click start
3. Pay attention to question about functional testing 

Actual result:  тестування це
Expected result: тестування - це

<img width="1440" alt="Снимок экрана 2022-10-05 в 5 08 02 PM" src="https://user-images.githubusercontent.com/110661667/194083061-b0635bd5-9138-4b61-b5a4-323810fd9ed4.png">

**Comment by scholokov** [comment]
fixed

**Comment by Xalep4ik** [comment]
verified
