### ISSUE TITLE
Not the same "Step" marking - lesson "Віддалене Debugging пристроїв Android" - course "Web & Mobile"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#1964]
**STR**
1. Open https://www.qax-camp.com.ua/courses/web-mobile/lessons/remote-debug-android-devices/ 
2. You should be logged;
3. Pay attention to the blocks "Step1" / "Step2"

**ACTUAL RESULT**
Steps 1 / 2 have different markings - Step 1 - without marking, Step 2 has "#" marking

**EXPECTED RESULT**
Each step should be equally marked or unmarked accordingly, to ensure the same appearance of the steps.
![kv6lE9r5YM](https://github.com/scholokov/qax-portal-2/assets/109384052/cb9f24f2-3e74-469f-aad7-587029e9e4eb)

**Comment by BatalovaOlha** [comment]
#1120

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
