### ISSUE TITLE
Тест: Defect - "Що таке – Summary (Title) у багу?" question - Type of checkboxes next to the answer options is Checkbox

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1966]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-defect/quizzes/deffect/
2. Find the "Що таке – Summary (Title) у багу?" question
3. Pay attention to the type of checkboxes next to the answer options

**Actual Result**
Type of checkboxes next to the answer options - Checkbox

**Expected Result**
Type of checkboxes next to the answer options - Radio button

**Additional Information**
https://github.com/scholokov/qax-portal-2/wiki/1.7.3.-Tests

**Environments**
Windows 10, Chrome 121.0.6167.140 (64 bit)
![Тест_ Defect – QAX Camp - Google Chrome 31 01 2024 16_17_55](https://github.com/scholokov/qax-portal-2/assets/95171672/45daee10-7e36-403c-b2f1-dbf637628af9)

**Comment by DmitriiNasonov** [comment]
#1920

**Comment by scholokov** [comment]
на чому базується?

**Comment by DmitriiNasonov** [comment]
There is only one correct answer to a question

**Comment by scholokov** [comment]
чого?

**Comment by DmitriiNasonov** [comment]
There is an answer in the presentation and it corresponds to only one of the answer options in the test
[Link to the lesson with a presentation](https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-defect/)
![Defect – QAX Camp - Google Chrome 13 02 2024 16_08_16](https://github.com/scholokov/qax-portal-2/assets/95171672/36770471-da3d-43eb-a285-d18eb6c1ce84)

**Comment by DmytroMarkulych** [comment]
можливо варто пошукати інфу яка буде стосуватися саме даного пункту

**Comment by DmitriiNasonov** [comment]
https://github.com/scholokov/qax-portal-2/wiki/1.7.3.-Tests
![1 7 3  Tests · scholokov_qax-portal-2 Wiki - Google Chrome 14 02 2024 14_54_17](https://github.com/scholokov/qax-portal-2/assets/95171672/f3612fb6-235a-42e7-aca8-548528cc9190)

**Comment by DmitriiNasonov** [comment]
canceled
