### ISSUE TITLE
Тест: Defect - "Хто визначає пріоритет бага?" question - Type of checkboxes next to the answer options is Checkbox

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1967]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-defect/quizzes/deffect/
2. Find the "Хто визначає пріоритет бага?" question
3. Pay attention to the type of checkboxes next to the answer options

**Actual Result**
Type of checkboxes next to the answer options - Checkbox

**Expected Result**
Type of checkboxes next to the answer options - Radio button

**Additional Information**
https://github.com/scholokov/qax-portal-2/wiki/1.7.3.-Tests

**Environments**
Windows 10, Chrome 121.0.6167.140 (64 bit)
![Тест_ Defect – QAX Camp - Google Chrome 31 01 2024 16_57_00](https://github.com/scholokov/qax-portal-2/assets/95171672/37428b13-a885-44fd-a68b-2b51dbbd7bf2)

**Comment by DmitriiNasonov** [comment]
#1920

**Comment by scholokov** [comment]
на чому базується?

**Comment by DmitriiNasonov** [comment]
There is only one correct answer to this question, which lists two roles at once. Because of this, there is a need to be able to select more than 1 answer option.

**Comment by scholokov** [comment]
чого?

**Comment by DmitriiNasonov** [comment]
There is an answer in the presentation and it corresponds to only one of the answer options in the test
[Link to the lesson with a presentation](https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-defect/)
![Defect – QAX Camp - Google Chrome 13 02 2024 16_11_32](https://github.com/scholokov/qax-portal-2/assets/95171672/10c49ae8-be11-44ad-9841-328f90ee0931)

**Comment by DmytroMarkulych** [comment]
Можливо варто пошукати специфікацію для цього функціоналу

**Comment by DmitriiNasonov** [comment]
https://github.com/scholokov/qax-portal-2/wiki/1.7.3.-Tests
![1 7 3  Tests · scholokov_qax-portal-2 Wiki - Google Chrome 14 02 2024 14_54_17](https://github.com/scholokov/qax-portal-2/assets/95171672/bee84dfb-2373-46ac-9ea5-55a6ec97bf86)

**Comment by DmitriiNasonov** [comment]
canceled
