### ISSUE TITLE
Тест: Defect - "Хто визначає Severity (Серйозність) бага?" question - Type of checkboxes next to the answer options is Checkbox

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1968]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-defect/quizzes/deffect/
2. Find the "Хто визначає Severity (Серйозність) бага?" question
3. Pay attention to the type of checkboxes next to the answer options

**Actual Result**
Type of checkboxes next to the answer options - Checkbox

**Expected Result**
Type of checkboxes next to the answer options - Radio button

**Environments**
Windows 10, Chrome 121.0.6167.140 (64 bit)
![Тест_ Defect – QAX Camp - Google Chrome 31 01 2024 17_03_15](https://github.com/scholokov/qax-portal-2/assets/95171672/3205ddeb-11d8-427a-906c-97b8624772de)

**Comment by DmitriiNasonov** [comment]
#1920

**Comment by scholokov** [comment]
на чому базується?

**Comment by DmitriiNasonov** [comment]
There is only one correct answer to a question

**Comment by scholokov** [comment]
чого? :)

**Comment by DmitriiNasonov** [comment]
Canceled. The bug report was written incorrectly. A new bug report will be created
