### ISSUE TITLE
"Завдання" requirements - Clause 1.1 - Example title does not start with "Завдання" word

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1969]
**Steps of reproducing**
1. Open https://qaxm.atlassian.net/wiki/spaces/PM/pages/11403268
2. Pay attention to the clause 1.1

**Actual Result**
Example title does not start with "Завдання" word

**Expected Result**
Example title starts with "Завдання" word

**Environments**
Windows 10, Chrome 121.0.6167.140 (64 bit)
![Завдання - Portal Mobile - Confluence - Google Chrome 31 01 2024 18_00_42](https://github.com/scholokov/qax-portal-2/assets/95171672/11e0c029-3bdd-49e0-bef8-cd4d5997dc68)

**Comment by DmitriiNasonov** [comment]
#1919

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
