### ISSUE TITLE
Test - Виды Тестирования - Punctuation error in the question about regression testing 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#197]
1. Open https://portal.qax-camp.com.ua/quizzes/q5-test-types/
2. Click start
3. Pay attention to question about regression testing

Actual result:  тестування це
Expected result: тестування - це

<img width="1440" alt="Снимок экрана 2022-10-05 в 5 23 31 PM" src="https://user-images.githubusercontent.com/110661667/194085167-c52a3514-85a3-4205-a7dd-989fdb0fa134.png">

**Comment by Xalep4ik** [comment]
An issue is reproduced
There is no " - "
![1](https://user-images.githubusercontent.com/92167884/198602461-e75c889f-f500-4f1e-8ba0-2dae3b8efa1a.png)

**Comment by scholokov** [comment]
fixed

**Comment by Xalep4ik** [comment]
Verified, an issue is not reproduced
