### ISSUE TITLE
Test/ The location of the "Finish Тест" button is displayed in the lower left corner of the page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1972]
**Steps to reproduce:**
1. Open page https://www.qax-camp.com.ua/courses/q6-basic/lessons/who-is-qa/
2. Choose the "Тестувальник. Хто це?" test
3. Pay attention to the location of the "Finish Тест" button in the lower right corner of the page

Actual Result: The location of the "Finish Тест button is displayed in the **lower left** corner of the page
Expected Result: The location of the "Finish Тест" button is displayed in the **lower right** corner of the page

**Requirements:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=931-91&mode=design&t=AKZOj7yffy2V1qbW-0

**Environment**:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/c8f13155-f13c-4935-960f-6aaebdd3840c)

**Comment by ODrobik** [comment]
#1916

**Comment by scholokov** [comment]
здається застарілий дизайн

**Comment by ODrobik** [comment]
не є багом
