### ISSUE TITLE
Test/ The caption of the "Finish Тест" button in the lower left corner of the page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1973]
Steps to reproduce:
1. Open page https://www.qax-camp.com.ua/courses/q6-basic/lessons/who-is-qa/
2. Choose the "Тестувальник. Хто це?" test
3. Pay attention to the caption of the "Finish Тест" button in the lower left corner of the page

Actual Result: The caption of the "Finish Тест" button is displayed in the lower left corner of the page

Expected Result: The caption of the "Закінчити тест" button is displayed in the lower left corner of the page

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/9fe5b189-1657-47b3-bf98-2b00a68ba411)

**Comment by ODrobik** [comment]
#1916

**Comment by poroskundenys** [comment]
Готово

**Comment by ODrobik** [comment]
Перевірено
