### ISSUE TITLE
QA Quest/ The "Продовжити" button with "F66F5D" color and "Price" button are displayed on the "Тестування валідації форми "Реєстрація" card for authorized

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1974]
**Steps to reproduce:**
1. Open page https://www.qax-camp.com.ua/qa-quest/
2. Scroll down to the "Або обирай на свій смак" section of the page
3. Pay attention to the present "Price" button and to the color of the "Проловжити" button of the "Тестування валідації форми "Реєстрація" card

**Actual Result:** The "Продовжити" button with "F66F5D" color and "Price" button are displayed on the "Тестування валідації форми "Реєстрація" card 

**Expected Result:** The "Price" button is not displayed and the "Продовжити" button no color on  the "Тестування валідації форми "Реєстрація" card 

**Environment:**
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/ada0197f-ce49-4cb4-92a1-8cdfc636f2bd)

**Comment by poroskundenys** [comment]
готово

**Comment by ODrobik** [comment]
Створено новий схожий баг #1991
