### ISSUE TITLE
QA Quest. Тестування двомовного Web-додатку/ All URL is not displayed as link in the "Завдання: Тестування – UI" page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1975]
Steps to reproduce:
1. Open page https://www.qax-camp.com.ua/courses/widiq-test/
2. Choose the "Тестування" stage of the "Тестування двомовного Web-додатку" quest
3. Choose the "Завдання: Тестування – UI" point in the "Урок Content" section
4. Pay attention to the All URL in the "Завдання: Тестування – UI" page

**Actual Result**: All the URL **is not displayed as link** in the "Завдання: Тестування – UI" page

**Expected Result**: All URL **is displayed as link** in the "Завдання: Тестування – UI" page

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/92076dc6-92b4-4e9b-a6de-aecf52692743)

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
Створено новий подібний баг  #2025
