### ISSUE TITLE
QA Quest. Тестування двомовного Web-додатку/ All URL is not displayed as link in the "Завдання: Тестування – функціональні тести" page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1976]
**Steps to reproduce:**
1. Open page https://www.qax-camp.com.ua/courses/widiq-test/
2. Choose the "Тестування" stage of the "Тестування двомовного Web-додатку" quest
3. Choose the "Завдання: Тестування – функціональні тести" point in the "Урок Content" section
4. Pay attention to the All URL in the "Завдання: Тестування – функціональні тести" page

**Actual Result:** All the URL is not displayed as link in the "Завдання: Тестування – функціональні тести" page

**Expected Result:** All URL is displayed as link in the "Завдання: Тестування – функціональні тести" page

**Environment:**
Windows 10 Pro,
Opera v 96.0.4693.80

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/45cc07f5-fbec-41f1-acfc-7009070543c2)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
Створено новий схожий баг https://github.com/scholokov/qax-portal-2/issues/2000
