### ISSUE TITLE
Tabs - Check the names of the new tabs on Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1977]
We need to check the names of the new tabs on Figma.
This is an example of modified tabs:

Cources → Directions *
Materials → Video Cources
Lesson → Lesson *
QA/PM/BA → QA/PM/BA *
Event → Event *
Test → Test *
Order → Order *
Test result → Test Results *
Essay → Essay *
Order → Order *
Checkout → Checkout *
Award → Award *
Certificate → Certificate *

![Figma](https://github.com/scholokov/qax-portal-2/assets/109460500/c0b2f46e-ecfa-42b4-bf2e-f8e7d6f18f4c)

**Comment by GNatala** [comment]
verified
