### ISSUE TITLE
Тест: Defect - "Де баг репорту має бути посилання на скріншот?" question - The letter "у" is missing at the beginning of the question title

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1979]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-defect/quizzes/deffect/
2. Open the "Де баг репорту має бути посилання на скріншот?" question
3. Pay attention to the question name

**Actual Result**
Question name is "Де баг репорту має бути посилання на скріншот?"

**Expected Result**
Question name is "Де у баг репорту має бути посилання на скріншот?"

**Additional information**
The letter "у" is missing at the beginning of the question title

**Environments**
Windows 10, Chrome 121.0.6167.140 (64 bit)
![Тест_ Defect – QAX Camp - Google Chrome 02 02 2024 16_07_05](https://github.com/scholokov/qax-portal-2/assets/95171672/f1352661-62e9-434b-9e51-1bb283836e5f)

**Comment by DmitriiNasonov** [comment]
#1920

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
Checked. Bug isn't reproduced
