### ISSUE TITLE
Test - Виды Тестирования - Grammatical  error in the question about regression testing 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#198]
1. Open https://portal.qax-camp.com.ua/quizzes/q5-test-types/
2. Click start
3. Pay attention to тстування

Actual result:  тстування
Expected result: тестування

<img width="1440" alt="Снимок экрана 2022-10-05 в 5 23 31 PM" src="https://user-images.githubusercontent.com/110661667/194085574-de7104fa-0443-4c41-ada7-d1a65b4ba82f.png">

**Comment by scholokov** [comment]
fixed

**Comment by Xalep4ik** [comment]
verified
