### ISSUE TITLE
Test - Check test for "SDLC/STLC" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1994]
We need to check test for "SDLC/STLC" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/q6-basic/
Requirements: https://qaxm.atlassian.net/wiki/spaces/PM/pages/10485769/QA

![SDLCSTLC test](https://github.com/scholokov/qax-portal-2/assets/109460500/191ef0ce-40fb-4c7a-9757-45181ef1556d)

**Comment by BatalovaOlha** [comment]
verified
