### ISSUE TITLE
Test results - Implement the design for "test results" according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#1998]
We need to implement the design for "test results" according to Figma.
Environment: https://www.qax-camp.com.ua/courses/q6-basic/lessons/who-is-qa/quizzes/q5-01-who-is-qa/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=1212-66&mode=design&t=AHHVi9a3xNL35Jdy-0

![Test result](https://github.com/scholokov/qax-portal-2/assets/109460500/686a6b6c-31c7-4db0-b236-566ff6d68d91)

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
verified
