### ISSUE TITLE
Тест: Defect - "Хто визначає Severity (Серйозність) бага?" question - Answer options "Lead QA" and "Team Lead" are missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#1999]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-defect/quizzes/deffect/
2. Find the "Хто визначає Severity (Серйозність) бага?" question
3. Pay attention to the answer options

**Actual Result**
Answer options "Lead QA" and "Team Lead" are missing

**Expected Result**
Answer options "Lead QA" and "Team Lead" are present

**Additional information**
https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-defect/ (Page 24 on presentation)

**Environments**
Windows 10, Chrome 121.0.6167.161 (64 bit)
![Тест_ Defect – QAX Camp - Google Chrome 13 02 2024 16_30_25](https://github.com/scholokov/qax-portal-2/assets/95171672/d6a05950-c83c-403f-8a4b-2d4758ffc194)
![Тест_ Defect – QAX Camp - Google Chrome 13 02 2024 16_30_30](https://github.com/scholokov/qax-portal-2/assets/95171672/09f0885f-9d0c-4c0f-b278-5230308288fb)

**Comment by DmitriiNasonov** [comment]
#1968

**Comment by scholokov** [comment]
прибрано, щоб виникало менше питань

**Comment by DmitriiNasonov** [comment]
canceled
