### ISSUE TITLE
Lesson: Error Message - Не изучен предыдущий урок

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#20]
придумать дизайн для сообщения:

![image](https://user-images.githubusercontent.com/22824947/183062867-0e1a9560-9c26-4679-8741-329628619d2a.png)

**Comment by ABatalov** [comment]
Here you can fing design in Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A12776

**Comment by KaterinaNimenko35** [comment]
verified
