### ISSUE TITLE
Wrong text - block "Ти лише робиш перші кроки до успішної кар'єри в ІТ?" - Figma design - Home page  

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#200]
**STR**
1. Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A23
2. Pay attention to the block description "Ти лише робиш перші кроки до успішної кар'єри в ІТ?"
3. Open https://github.com/scholokov/qax-portal-2/wiki
4. Pay attention to the block description "Ти лише робиш перші кроки до успішної кар'єри в ІТ?"

**ACTUAL RESULT**
2nd phrase looks like "Рухаючись ними ти обов'язково досягнення результату - отримаєш бажаний Job Offer."

**EXPECTED RESULT**
2nd phraseshould be "Рухаючись ними ти обов'язково досягнеш результату - отримаєш бажаний Job Offer."

![ib5TH36Mpe](https://user-images.githubusercontent.com/109384052/194284225-e6352bc2-4164-4eb0-bd1c-9bbf655c6cb7.png)

![9zjpbLmKlK](https://user-images.githubusercontent.com/109384052/194284238-53a1e96d-fefc-4484-9a41-251b1758fd12.png)

**Comment by scholokov** [comment]
у дизайні необов'язково виправляти орфографічні помилки, тому що у розрізі контенту ми звіряємо саме вимоги з реалізацією

**Comment by BatalovaOlha** [comment]
> у дизайні необов'язково виправляти орфографічні помилки, тому що у розрізі контенту ми звіряємо саме вимоги з реалізацією

Ок. Мені просто закрити цей баг?

**Comment by scholokov** [comment]
так. дякую

**Comment by BatalovaOlha** [comment]
no actual
