### ISSUE TITLE
QA Quest. Тестування двомовного Web-додатку/ "https://widiq.qax.com.ua/" URL is not displayed as link in the "Завдання: Тестування – функціональні тести" page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#2000]
Steps to reproduce:
1. Open page https://www.qax-camp.com.ua/courses/widiq-test/
2. Choose the "Тестування" stage of the "Тестування двомовного Web-додатку" quest
3. Choose the "Завдання: Тестування – функціональні тести" point in the "Урок Content" section
4. Pay attention to the "https://widiq.qax.com.ua/" URL in the "Завдання: Тестування – функціональні тести" page

Actual Result: "https://widiq.qax.com.ua/" URL is not displayed as link in the "Завдання: Тестування – функціональні тести" page

Expected Result:  "https://widiq.qax.com.ua/" URL is displayed as link in the "Завдання: Тестування – функціональні тести" page

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/e2acfced-72dd-4a03-b959-00cff7b0edc8)

**Comment by ODrobik** [comment]
Створено новий схожий баг #2000

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
