### ISSUE TITLE
Lessons - Check lesson for "Installation / Uninstallation testing" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2002]
We need to check lesson for "Installation / Uninstallation testing" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/testing/lessons/installation-uninstallation-testing/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F

![Installation  Uninstallation testing](https://github.com/scholokov/qax-portal-2/assets/109460500/9b3c29ae-721d-45b8-8438-2a767d8dfa40)

**Comment by ODrobik** [comment]
verified
