### ISSUE TITLE
Lessons - Check lesson for "Тестова документація: чек-лісти та тест-кейси" page (update)

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2004]
We need to check lesson for "Тестова документація: чек-лісти та тест-кейси" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-test-documentation/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F

![Тестова документація чек-лісти та тест-кейси](https://github.com/scholokov/qax-portal-2/assets/109460500/3380c438-6d6c-45f6-8797-749d78bcb697)

**Comment by ODrobik** [comment]
verified
