### ISSUE TITLE
Requirements - 1.7.1. Урок - Web & Mobile course - "Critical Rendering Path" lesson is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#2005]
**Steps of reproducing**
1. Open https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#web--mobile
2. Scroll to the Web & Mobile course

**Actual Result**
"Critical Rendering Path" lesson is missing

**Expected Result**
"Critical Rendering Path" lesson is present

**Additional information**
https://www.qax-camp.com.ua/courses/web-mobile/lessons/critical-rendering-path/

**Environments**
Windows 10, Chrome 121.0.6167.185 (64 bit)
![1 7 1  Урок · scholokov_qax-portal-2 Wiki - Google Chrome 14 02 2024 15_09_22](https://github.com/scholokov/qax-portal-2/assets/95171672/33319c24-faa0-4c48-a5b8-58239e6e2d33)

**Comment by DmitriiNasonov** [comment]
#1159

**Comment by scholokov** [comment]
застарілі вимоги

**Comment by DmitriiNasonov** [comment]
Canceled
