### ISSUE TITLE
Missing block "Чому обирають нас?" - in the Figma - Main_test design

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#201]
**STR**

1. Open https://github.com/scholokov/qax-portal-2/wiki and pay attention to the block "Чому обирають нас?"
2. Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A22

**ACTUAL RESULT**
 The block "Чому обирають нас?" - in the Figma - Main_test design is NOT shown

**EXPECTED RESULT**
The block "Чому обирають нас?" - in the Figma - Main_test design is shown

![mignojuGpG](https://user-images.githubusercontent.com/109384052/194291215-7077e3af-3c35-4fb7-99f9-577444af392b.png)
![lHJgbIxZPz](https://user-images.githubusercontent.com/109384052/194291227-f29d2745-3d39-4fd7-aa05-0e188f0669a3.png)

**Comment by ButKoff** [comment]
#315
