### ISSUE TITLE
Lesson "State & Transition Diagram"/ The name and surname of the lesson's author "Scholokov Denis" is written in English

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2014]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/testing/lessons/td-std/
2. Scroll down to the text "Автор: Scholokov Denis".
3. Pay attention to the name and surname.

**Actual result:**
The name and surname of the lesson's author "Scholokov Denis" is written in English.

**Expected result:**
The name and surname of the lesson's author  "Денис Щолоков" is written in Ukrainian.

**Requirements:** 
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/c9917562-b764-4c95-b777-5c617fa810a5)

**Comment by GNatala** [comment]
#1207

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
