### ISSUE TITLE
GitHub Wiki - Home - Link to the actual requirements in the Confluence is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#2022]
**Steps of reproducing**
1. Open https://github.com/scholokov/qax-portal-2/wiki

**Actual Result**
Link to the actual requirements in the Confluence is missing

**Expected Result**
Link to the actual requirements in the Confluence is present

**Additional information**
https://qaxm.atlassian.net/wiki/spaces/PM/pages/2228439

**Environments**
Windows 10, Chrome 122.0.6261.58 (64 bit)
![Home · scholokov_qax-portal-2 Wiki - Google Chrome 21 02 2024 15_25_45](https://github.com/scholokov/qax-portal-2/assets/95171672/d39cb826-f3d2-44a7-8a64-01f2cd9830fa)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
