### ISSUE TITLE
Confluence requirements -  Тести - Clause 4.2 -  The requirements are formulated as "Закрите питання, з багатьма відповіддями. Має квадрат, перед відповіддю."

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#2023]
**Steps of reproducing**
1. Open https://qaxm.atlassian.net/wiki/spaces/PM/pages/10420227
2. Scroll to the Clause 4.2

**Actual Result**
The requirements are formulated as "Закрите питання, з багатьма відповіддями. Має квадрат, перед відповіддю."

**Expected Result**
The requirements are formulated as "Закрите питання, одною чи більше відповіддями. Має квадрат, перед відповіддю."

**Environments**
Windows 10, Chrome 122.0.6261.58 (64 bit)
![Тести - Portal Mobile - Confluence - Google Chrome 21 02 2024 15_53_51](https://github.com/scholokov/qax-portal-2/assets/95171672/9660ae19-be49-45d4-96cb-cf0e7dbb9fe1)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
