### ISSUE TITLE
Lesson - Create a design for the completed test in the lesson

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2024]
We need to сreate a design for the completed test in the lesson.
Figma: https://www.figma.com/file/2JlqZybc4fOvZcPT7oiqrg/Portal-design?type=design&node-id=390-12775&mode=design&t=irvgfHi2XTgslFiT-0

Screen display №1: **ОДИН** тест не пройдено

![Тест не пройдено](https://github.com/scholokov/qax-portal-2/assets/109460500/51ea6f1e-4ffa-48de-96c1-620e7ee5a113)

Screen display №2: **ОДИН** тест пройдено

![Пройдений тест](https://github.com/scholokov/qax-portal-2/assets/109460500/8f9a056e-8faa-4c25-ba05-769b9a1fb06b)

Screen display №3: **ОБИДВА** теста пройдено

Screen display №4: **ОБИДВА** теста не пройдено

Screen display №5: **ОДИН** тест з **ДВОХ** пройдено

Screen display №6: Урок без тесту (він вже є у нас на Фігма, мабуть його зробити яскровіше)

**Comment by ButKoff** [comment]
#2043

**Comment by GNatala** [comment]
verified
