### ISSUE TITLE
QA Quest. Тестування двомовного Web-додатку/ "https://widiq.qax.com.ua/" URL is not displayed as link in the "Завдання: Тестування – UI" page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#2025]
Steps to reproduce:
1. Open page https://www.qax-camp.com.ua/courses/widiq-test/
2. Choose the "Тестування" stage of the "Тестування двомовного Web-додатку" quest
3. Choose the "Завдання: Тестування – UI" point in the "Урок Content" section
4. Pay attention to the "https://widiq.qax.com.ua/" URL in the "Завдання: Тестування – UI" page

**Actual Result:** 
"https://widiq.qax.com.ua/" URL **is not displayed as link** in the "Завдання: Тестування – UI" page

**Expected Result:**
 "https://widiq.qax.com.ua/" URL **is displayed as link** in the "Завдання: Тестування – UI" page

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/e23f876f-538e-4d7b-9373-4053b4abd06c)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
