### ISSUE TITLE
Email - Check the email when reset your password

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2026]
We need to check the email when reset your password.
Please check availability of requirements, functional compliance and design compliance.
**It's important to check this:**

- a letter should come after registration;
- the design on mobile devices and computers should be different.

Environment: https://www.qax-camp.com.ua/account/password/
Requirements: https://qaxm.atlassian.net/wiki/spaces/PM/pages/23363585

<img width="521" alt="Password Reset" src="https://github.com/scholokov/qax-portal-2/assets/109460500/1f087dd0-8ac8-487f-8767-f54c8d1e1bb7">

**Comment by DmitriiNasonov** [comment]
Testing completed. No bugs found
