### ISSUE TITLE
Email - Check the email when changed your password

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2027]
We need to check the email when changed your password.
Please check availability of requirements, functional compliance and design compliance.
**It's important to check this:**

- a letter should come after registration;
- the design on mobile devices and computers should be different.

Environment: https://www.qax-camp.com.ua/account/password/
Requirements: https://qaxm.atlassian.net/wiki/spaces/PM/pages/23363585

<img width="520" alt="Password Changed" src="https://github.com/scholokov/qax-portal-2/assets/109460500/0c66a789-5bc3-4bb5-94df-205d594551c8">

**Comment by DmitriiNasonov** [comment]
Testing completed. No bugs found
