### ISSUE TITLE
Email - Check the email after checking the assignment

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2028]
We need to check the email after checking the assignment.
Please check availability of requirements, functional compliance and design compliance.
**It's important to check this:**

- a letter should come after registration;
- the design on mobile devices and computers should be different.

Environment: https://www.qax-camp.com.ua/courses/portal-reg/lessons/portal-reg-test-req/quizzes/portal-reg-test-req/
Requirements: https://qaxm.atlassian.net/wiki/spaces/PM/pages/23363585

<img width="340" alt="Завдання перевірено" src="https://github.com/scholokov/qax-portal-2/assets/109460500/6a96309b-dfb7-4141-baaf-ea50afa67654">

**Comment by ODrobik** [comment]
verified
