### ISSUE TITLE
Email - Check the email after completing the task

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2029]
We need to check the email after completing the task.
Please check availability of requirements, functional compliance and design compliance.
**It's important to check this:**

- a letter should come after registration;
- the design on mobile devices and computers should be different.

Environment: https://www.qax-camp.com.ua/courses/portal-reg/lessons/portal-reg-test-req/quizzes/portal-reg-test-req/
Requirements: https://qaxm.atlassian.net/wiki/spaces/PM/pages/23363585

<img width="340" alt="Завдання виконано" src="https://github.com/scholokov/qax-portal-2/assets/109460500/edc49deb-87c1-4cfb-b9a3-e147255f0ab2">

**Comment by ODrobik** [comment]
verified
