### ISSUE TITLE
Email - Check the email after registering for the event

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2030]
We need to check the email after registering for the event.
Please check availability of requirements, functional compliance and design compliance.
**It's important to check this:**

- a letter should come after registration;
- the design on mobile devices and computers should be different.

Environment: https://www.qax-camp.com.ua/events/quest-crud-%d0%b0%d1%80%d1%96/
Requirements: https://qaxm.atlassian.net/wiki/spaces/PM/pages/23363585

<img width="340" alt="Підтвердження реєстрації на івент" src="https://github.com/scholokov/qax-portal-2/assets/109460500/0ff57f1e-df54-492f-93e4-2b32577c1fff">

**Comment by GNatala** [comment]
passed
