### ISSUE TITLE
Lessons - "GitFlow" / Spelling mistake оf the word "проект" and its variants in the content

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2031]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/processes/lessons/gitflow/
2. Find all variants of the word "проект"  in the content. **It appears 8 times.**
3. Pay attention to the spelling of the words "проект".

**Actual result:**
 The word "проект" and its variants are written with the letter "е" - 8 times.

**Expected result:**
 The word "проект" and its variants are written with the letter "є" - 8 times.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/abe9bbdb-207d-4bfe-afdd-029930566f5f)

**Comment by GNatala** [comment]
#1252

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
