### ISSUE TITLE
Subscription - Check the subscription payment function

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2032]
We need to check the subscription payment function.
You need to pay (50,1грн) for the subscription and check the next automatic payment.
Environment: https://www.qax-camp.com.ua/checkout/

![Subscription](https://github.com/scholokov/qax-portal-2/assets/109460500/34d75647-239e-41ef-a69d-dfacc01deee9)

**Comment by ODrobik** [comment]
verified
