### ISSUE TITLE
"Тестування" course -  "Основи тестування" section - "Емулятори та Симулятори у тестуванні" lesson is present

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#2038]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/courses/testing/
2. Scroll to the end of the "Основи тестування" section

**Actual Result**
"Емулятори та Симулятори у тестуванні" lesson is present

**Expected Result**
"Емулятори та Симулятори у тестуванні" lesson is missing

**Additional information**
https://qaxm.atlassian.net/wiki/spaces/PM/pages/30965858

**Environments**
Windows 10, Chrome 122.0.6261.112 (64 bit)
![Тестування – QAX Camp - Google Chrome 06 03 2024 15_56_42](https://github.com/scholokov/qax-portal-2/assets/95171672/6c42b69e-c335-4dc1-8e77-5ce18b9618e9)

**Comment by DmitriiNasonov** [comment]
#1180

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
