### ISSUE TITLE
"Тестування" course - "Види, методи та рівні тестування" section - "Installation / Uninstallation testing", and "White Box testing" lessons are present

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#2039]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/courses/testing/
2. Scroll to the "Види, методи та рівні тестування" section

**Actual Result**
"Installation / Uninstallation testing", and "White Box testing" lessons are present 

**Expected Result**
"Installation / Uninstallation testing", and "White Box testing" lessons are missing OR added to the requirements

**Additional information**
https://qaxm.atlassian.net/wiki/spaces/PM/pages/30965858

**Environments**
Windows 10, Chrome 122.0.6261.112 (64 bit)
![Тестування – QAX Camp - Google Chrome 06 03 2024 16_20_26](https://github.com/scholokov/qax-portal-2/assets/95171672/5eb31186-5c16-4515-8e5a-0df24816708a)

**Comment by DmitriiNasonov** [comment]
#1180

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
