### ISSUE TITLE
"Тестування" course - "Тест дизайн" section - "Таблиці рішень", and "State & Transition Diagram", and "Use-case Diagram" lessons are present

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#2040]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/courses/testing/
2. Scroll to the "Тест дизайн" section

**Actual Result**
"Таблиці рішень", and "State & Transition Diagram", and "Use-case Diagram" lessons are present

**Expected Result**
"Таблиці рішень", and "State & Transition Diagram", and "Use-case Diagram" lessons are missing OR added to the requirements

**Additional information**
https://qaxm.atlassian.net/wiki/spaces/PM/pages/30965858

**Environments**
Windows 10, Chrome 122.0.6261.112 (64 bit)
![Тестування – QAX Camp - Google Chrome 06 03 2024 16_26_31](https://github.com/scholokov/qax-portal-2/assets/95171672/9f950cb2-5c54-4438-abef-5032c19551e0)

**Comment by DmitriiNasonov** [comment]
#1180

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
