### ISSUE TITLE
"Тестування" course - "Документація, та робота з нею" section - "Traceability matrix", and "QA Звітність" lessons are present

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#2041]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/courses/testing/
2. Scroll to the "Документація, та робота з нею" section

**Actual Result**
"Traceability matrix", and "QA Звітність" lessons are present 

**Expected Result**
"Traceability matrix", and "QA Звітність" lessons are missing OR added to the requirements

**Additional information**
https://qaxm.atlassian.net/wiki/spaces/PM/pages/30965858

**Environments**
Windows 10, Chrome 122.0.6261.112 (64 bit)
![New Issue · scholokov_qax-portal-2 - Google Chrome 06 03 2024 16_39_23](https://github.com/scholokov/qax-portal-2/assets/95171672/443d589f-ba34-4d16-ae1f-409b4394f20d)

**Comment by DmitriiNasonov** [comment]
#1180

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
