### ISSUE TITLE
"Тестування" course - "Процеси" section - "STLC очима тестувальника", and "Production. Як його тестувати?" lessons are present

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#2042]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/courses/testing/
2. Scroll to the "Процеси" section

**Actual Result**
"STLC очима тестувальника", and "Production. Як його тестувати?" lessons are present 

**Expected Result**
"STLC очима тестувальника", and "Production. Як його тестувати?" lessons are missing OR added to the requirements

**Additional information**
https://qaxm.atlassian.net/wiki/spaces/PM/pages/30965858

**Environments**
Windows 10, Chrome 122.0.6261.112 (64 bit)
![Тестування – QAX Camp - Google Chrome 06 03 2024 16_42_04](https://github.com/scholokov/qax-portal-2/assets/95171672/b021d4e8-4730-4acc-92ee-987d5d535ed4)

**Comment by DmitriiNasonov** [comment]
#1180

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
