### ISSUE TITLE
Lesson - Implement the design for "lesson" according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2043]
We need to Implement a design for displaying tests for a “lesson” according to Figma.
Figma: https://www.figma.com/file/2JlqZybc4fOvZcPT7oiqrg/Portal-design?type=design&node-id=390-12775&mode=design&t=6FtCLLUvrCWT2VOu-0

This is a design for **DESKTOP**:

![Desktop](https://github.com/scholokov/qax-portal-2/assets/109460500/f8dd4575-f627-47ed-beaa-af9e7794cf29)

This hover is **ONLY** for **DESKTOP**:

![Ховери](https://github.com/scholokov/qax-portal-2/assets/109460500/f650a498-ae28-441e-ab3c-a95531571757)

This is a design for **TABLET**:

![Tablet](https://github.com/scholokov/qax-portal-2/assets/109460500/fd6a2d77-ab87-466d-883c-c7fcdd679a5f)

This is a design for **MOBILE**:

![Mobile](https://github.com/scholokov/qax-portal-2/assets/109460500/0fd4e4ae-c394-43f5-9c07-5e3707d8ee2b)

**Comment by ButKoff** [comment]
#2024

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
verified
