### ISSUE TITLE
Lessons - Check lesson for "SDLC та тестова стратегія" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2048]
We need to check lesson for "SDLC та тестова стратегія" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/processes/lessons/sdlc-test-strategy/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D0%B8

![SDLC та тестова стратегія](https://github.com/scholokov/qax-portal-2/assets/109460500/42190b78-d955-4c45-b370-5417dcbdadcd)

**Comment by ODrobik** [comment]
перевірено
