### ISSUE TITLE
wiki - Privacy policy - paragraph III  - wrong word "передані"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#205]
**STR**
1. Open https://github.com/scholokov/qax-portal-2/wiki/Privacy-policy
2. Pay attention to the III paragraph / 1st phrase "Персональна інформація, яку ви передані нам через наш веб-сайт...." 

**ACTUAL RESULT**
1st phrase looks like "Персональна інформація, яку ви **передані** нам через наш веб-сайт, буде використовуватися задля цілей, зазначених в цих правилах."

**EXPECTED RESULT**
The phrase sould be "Персональна інформація, яку ви **надаєте** нам через наш веб-сайт, буде використовуватися задля цілей, зазначених в цих правилах."

![jElZNOtbHw](https://user-images.githubusercontent.com/109384052/194848763-69ce2794-09ab-41aa-bc2f-40c358b16c87.png)

**Comment by ABatalov** [comment]
Fixed

**Comment by BatalovaOlha** [comment]
verified
