### ISSUE TITLE
Toolbar - The "User Avatar" icon is moved TOP after resizing or maximizing window

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#2053]
**Steps of reproducing**
1. Open https://t.qax-camp.com.ua/
2. Pay attention to the "User Avatar" 
3. Resize or Maximize the browser window

**Actual Result**
Icon moved TOP to the "Settings" icon

**Expected Result**
Icon Not moved

**Additional information**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design-(Old-Version)?type=design&node-id=10048-108&mode=design&t=yBewv4nMiRkgokl9-0

**Environments**
Windows 10, Chrome 122.0.6261.129 (64 bit)
![QAX Camp – Students Portal - Google Chrome 13 03 2024 20_06_37](https://github.com/scholokov/qax-portal-2/assets/95171672/b0409e9d-7647-42e7-aa9c-a6f8e2d21b23)

**Comment by DmitriiNasonov** [comment]
#1857

**Comment by DmitriiNasonov** [comment]
@DmytroMarkulych просьба проверить этот баг-репорт как можно скорее, баг должен быть исправлен до завтрашнего вечера

**Comment by scholokov** [comment]
опис не відповідає дійсності:
- виходячи з тайтлу іконка там знаходиться завжди
- необов'язково після ресайзу, а ще і після максимайзу

**Comment by poroskundenys** [comment]
Готово

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
