### ISSUE TITLE
Achievements - Сheck achievements for "Досягнення – Проєкти – За напрямками" page (DmitriiNasonov)

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2055]
We need to сheck achievements for "Досягнення – Проєкти – За напрямками" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/ach-project-all-by-topics/
Requirements: https://qaxm.atlassian.net/wiki/spaces/PM/pages/17989644

Test run - https://app.testomat.io/projects/long-travel-2-1/runs/41cffedf
![Досягнення – Проєкти – За напрямками](https://github.com/scholokov/qax-portal-2/assets/109460500/20809fde-9e19-4516-9fa1-d89805eba793)

**Comment by DmitriiNasonov** [comment]
Testing completed
