### ISSUE TITLE
Achievements - Сheck achievements for "Досягнення – Загальні" page (Natalia Huzyr)

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2056]
We need to сheck achievements for "Досягнення – Загальні" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/ach-all/
Requirements: https://qaxm.atlassian.net/wiki/spaces/PM/pages/17989644

![Досягнення - загальні](https://github.com/scholokov/qax-portal-2/assets/109460500/34024436-eea7-4137-890a-27688208ed57)

**Comment by GNatala** [comment]
not actual
