### ISSUE TITLE
Lessons  / The name of the element before the test is "Урок Content" 

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2058]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-defect/ or any Lesson with the test.
2. Scroll down to the test.
3. Pay attention to the name of the element is "Урок Content".

**Actual result:**
 The name of the element before the test is "Урок Content".

**Expected result:**
The name of the element before the test is "Додатковий матеріал".

**Requirements:** 
https://www.figma.com/file/2JlqZybc4fOvZcPT7oiqrg/Portal-design?type=design&node-id=223-144&mode=design&t=Nxl55Kaepk2lYj7e-0

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/8ba5deda-2ba8-4c72-bd42-b4a946b81921)

**Comment by GNatala** [comment]
#2043

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
passed
