### ISSUE TITLE
Lessons / The extra element "white dot" is before the text "Урок Content"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2059]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-defect/ or any Lesson with the test.
2. Scroll down to the test.
3. Pay attention to the element "white dot"  before the text "Урок Content".

**Actual result:**
 The extra element "white dot" is before the text "Урок Content".

**Expected result:**
The element "white dot" is absent before the text "Урок Content".

**Requirements:** 
https://www.figma.com/file/2JlqZybc4fOvZcPT7oiqrg/Portal-design?type=design&node-id=223-144&mode=design&t=Nxl55Kaepk2lYj7e-0

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/49480a43-3c92-44ca-9c56-86fb324cc54f)

**Comment by GNatala** [comment]
#2043

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
passed
