### ISSUE TITLE
Last phrase - part III Privacy policy - Wiki requirement - should be from a paragraph

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#206]
**STR**
1. Open https://github.com/scholokov/qax-portal-2/wiki/Privacy-policy
2. Pay attention to the block III / last phrase that starts from "Без вашої чітко вираженої згоди.... "

**ACTUAL RESULT**
The last phrase that starts from "Без вашої чітко вираженої згоди.... " in block III is shown in the same line that the previous phrase. 
**EXPECTED RESULT**
The last phrase that starts from "Без вашої чітко вираженої згоди.... " in block III is NOT shown in the same line that the previous phrase.

 
![iaVPrCxxEn](https://user-images.githubusercontent.com/109384052/194853622-3168189f-7409-4129-9097-64dff1e9847a.png)

**Comment by ABatalov** [comment]
Fixed

**Comment by BatalovaOlha** [comment]
![qsQ1F4o9ky](https://user-images.githubusercontent.com/109384052/195340381-d9caefa9-b278-416e-98b7-161a59beb765.png)


Look the same
