### ISSUE TITLE
"Project Quality Level" lesson - "Quality Level" lesson is displayed on the Preview 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#2061]
Steps to Reproduce:
1. Open page https://www.qax-camp.com.ua/courses/processes/lessons/q-levels/
2. Pay attention to the name of the "Quality Level" lesson 

Actual Result:  The "Quality Level" lesson is displayed on the Preview 
Expected Result: The "Project Quality Level" lesson is displayed on the Preview 

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/e569c042-500c-4bc6-b1d0-9d13b12dd18b)

**Comment by ODrobik** [comment]
#1254

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
