### ISSUE TITLE
"Project Quality Level" lesson - The "Scholokov Denis" author of the lesson is displayed in the End of the page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#2062]
Steps to Reproduce:
1. Open page https://www.qax-camp.com.ua/courses/processes/lessons/q-levels/
2. Pay attention to the author of the lesson

Actual Result: The "Scholokov Denis" author of the lesson is displayed in the End of the page
Expected Result: The "Денис Щолоков" author of the lesson is displayed in the End of the page

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/d2d30e73-dd7c-47ce-b679-e0601514c470)

**Comment by ODrobik** [comment]
#1254

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
