### ISSUE TITLE
Checkout/ "Правила та умови" text of this page is displayed on the Checkout page 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#2063]
Steps to reproduce:
1. Open page https://www.qax-camp.com.ua/checkout/
2. Choose the "Правила та умови" of the "Деталі оплати" section
3. Pay attention that a new "Правила та умови" page should open

Actual Result: 
"Правила та умови" text of this page is displayed on the **Current page**

Expected Result: 
"Правила та умови" text of this page is displayed on a **Separate page**

Requirements: 
https://github.com/scholokov/qax-portal-2/wiki/1.1.4.1.-%D0%94%D0%BE%D0%B3%D0%BE%D0%B2%D1%96%D1%80-%D0%BE%D1%84%D0%B5%D1%80%D1%82%D0%B8

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/9286ab7c-d60f-4e7b-b6ea-d869e673dbfa)
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/7d7c06e9-9e7b-4159-a685-88b4f404ab83)

**Comment by scholokov** [comment]
мабуть не те посилання на фігму

**Comment by scholokov** [comment]
і зробіть ще скрін з фігми

**Comment by ODrobik** [comment]
виправлено

**Comment by scholokov** [comment]
не до кінця розумілий опис.
треба явно описати - що має відкриватися окрема сторінка, а наразі тест сторінки відображається у блоку

**Comment by ODrobik** [comment]
виправлено

**Comment by scholokov** [comment]
потрібно написати - 
єкспектід - текст має відображатися на окремій сторінці
зараз - текст відображається на поточній сторінці

**Comment by ODrobik** [comment]
Додано уточнення до Актуального та Очікуваного результатів

**Comment by poroskundenys** [comment]
Готово

**Comment by ODrobik** [comment]
перевірено
