### ISSUE TITLE
Lessons - Check lesson for "Посадові обов’язки QA" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2067]
We need to check lesson for "Посадові обов’язки QA" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/processes/lessons/qa-positions/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D0%B8

![Посадові обов’язки QA](https://github.com/scholokov/qax-portal-2/assets/109460500/c33828c9-6505-4279-b0dc-0e2c670a1cea)

**Comment by ODrobik** [comment]
verified
