### ISSUE TITLE
No mark dots at the last phrase paragraph IV on the page Privacy policy 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#207]
**STR**
1. Open https://portal.qax-camp.com.ua/privacy_policy/
2. Scroll to the paragraph IV and pay attention to the last phrase.
3. Open https://github.com/scholokov/qax-portal-2/wiki/Privacy-policy pay attention to the last phrase of the paragraph IV 

**ACTUAL RESULT**
Mark dots at the last phrase of the paragraph IV is NOT shown
 
**EXPECTED RESULT**
Mark dots at the last phrase of the paragraph IV is  shown

![X5IGzQJPmf](https://user-images.githubusercontent.com/109384052/195026357-effea107-dc00-4976-80d2-0cfff49cc2a3.png)
![7rq7tiNA8x](https://user-images.githubusercontent.com/109384052/195026384-94e3ad9a-e21c-4d88-95fb-3b014ada0b25.png)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
