### ISSUE TITLE
Toolbar - Check the new changes to the "Toolbar" menu

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2072]
We need to check the new changes to the "Toolbar" menu.
Please check availability of requirements, functional compliance and design compliance.

**Сhanges to check:**
- font changed from 14 to 18;
- changed the height of the sub menu;
- same hover color and icons.

**Mobile changes to check:**
- duplicate points removed.

 Environment: https://www.qax-camp.com.ua/

![toolbar](https://github.com/scholokov/qax-portal-2/assets/109460500/fe52ea50-eaf0-4498-9bfa-f8c382a78a8e)

**Comment by GNatala** [comment]
verified
