### ISSUE TITLE
Test - Сhange the name of the button to "Завершити тест"

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2073]
We need to change the name of the button to "Завершити тест".
Environment: https://www.qax-camp.com.ua/courses/q6-basic/lessons/who-is-qa/quizzes/q5-01-who-is-qa/

![Test](https://github.com/scholokov/qax-portal-2/assets/109460500/2a16d39a-f208-4ba4-b684-a6230b9e97a9)

**Comment by scholokov** [comment]
а він на скріні не по дизайну?

**Comment by scholokov** [comment]
@ButKoff

**Comment by ButKoff** [comment]
@scholokov зараз на скріні, як на сайті (переробив) ... потрібно реалізувати дизайн, який зараз на фігмі за вказаним посиланням ...

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
passed
