### ISSUE TITLE
On the Course Page, the body container is moved down

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/qax-portal-2#2075]
Steps to reproduce:

1. Open the Course Page (for example https://www.qax-camp.com.ua/courses/q6-basic/)
2. Open the Elements of the DevTools
3. Pay attention to the margin size of the body container 

Actual result:

1. The margin size is 110px

Expected result:

1. The margin size of the body container must be 0px

Attachments:
![Снимок экрана 2024-03-22 в 13 27 57](https://github.com/scholokov/qax-portal-2/assets/130754297/6341c019-a6a9-48b8-a116-1cccc724bfa0)

Documentation:
[Designe](https://www.figma.com/file/2JlqZybc4fOvZcPT7oiqrg/Portal-design?type=design&node-id=302-1560&mode=design&t=05s8O1RpTQ6u6bi3-0)

Environment:
Browser: Google Chrome 122.0.6261.129
OS: macOS 10.15.7

**Comment by poroskundenys** [comment]
Готово

**Comment by Nanafox2010** [comment]
verified
