### ISSUE TITLE
"Наші Тренери" / Missed chronological order of the Dmytro Markulych's work experience

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2079]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/trainers/
2. Scroll down to the "Dmytro Markulych Trainer" block.
3. Pay attention to the work experience chronological order: 
"2019 – 2021 Software engineer at ATENA
2021 – present QA engineer GG4L".

**Actual result:**
Work experience is not in chronological order:
2019 – 2021 Software engineer at ATENA
2021 – present QA engineer GG4L

**Expected result:**
Work experience is in chronological order:
2021 – present QA engineer GG4L
2019 – 2021 Software engineer at ATENA

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/cb3de5b7-6b24-4427-8404-c166aa6d953a)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
verified
