### ISSUE TITLE
Lesson / DESKTOP / The color of the hover of the not completed test is not transparent

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2081]
**Steps to reproduce:**

1. Open any Lesson with not completed test https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-test-documentation/
2. Pay attention to the color of the hover of the "Тест: Тестова документація: чек-лісти та тест-кейси"

**Actual result:**
The color of the hover of the not completed test is not transparent.

**Expected result:**
The color of the hover of the not completed test is transparent.

Requirements:
https://www.figma.com/file/2JlqZybc4fOvZcPT7oiqrg/Portal-design?type=design&node-id=390-12775&mode=design&t=137zljyHzm4JX5yO-0

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/7d86922a-e110-4aeb-817f-0cd3fecbbe57)
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/50955f64-2174-4a91-a759-db62c611e782)

**Comment by GNatala** [comment]
#2043

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
passed
