### ISSUE TITLE
Home page - Implement the design for logo "QAX Camp" according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2083]
We need to implement the design for logo "QAX Camp" according to Figma.
Environment: https://www.qax-camp.com.ua/
Figma: https://www.figma.com/file/2JlqZybc4fOvZcPT7oiqrg/Portal-design?type=design&node-id=10048-108&mode=design&t=Za65iTHwDQqwxYjH-0

![Home page](https://github.com/scholokov/qax-portal-2/assets/109460500/dc0eab15-8911-4f07-96f5-aa445660f7c2)

**Comment by scholokov** [comment]
done
для десктопа - нове квадратне лого
для мобіли - старе плоске

**Comment by DmitriiNasonov** [comment]
Testing completed. Bugs not found
