### ISSUE TITLE
Toolbar / Radius of the Toolbar menu and Drop-down menu elements are different

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2084]
**Steps to reproduce:**

1. Open  https://www.qax-camp.com.ua/
2. Pay attention to the form of the elements Toolbar menu and Drop-down menu.

**Actual result:**
Radius of the Toolbar menu and Drop-down menu elements are different.

**Expected result:**
**Radius of the Toolbar menu and Drop-down menu elements are the same. The corners of the icons are rounded**.

Requirements:
https://www.figma.com/file/2JlqZybc4fOvZcPT7oiqrg/Portal-design?type=design&node-id=302-1560&mode=design&t=QYALCHA33xcNJ46B-00

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://github.com/scholokov/qax-portal-2/assets/101987790/af68c5ad-12a6-422e-8783-84ca4d059380)

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
passed
