### ISSUE TITLE
Lessons - Check lesson for "Створення тестової документації для тестування API" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2085]
We need to check lesson for "Створення тестової документації для тестування API" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/testing/lessons/api-test-doc/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F

![Створення тестової документації для тестування API](https://github.com/scholokov/qax-portal-2/assets/109460500/634cd205-620a-4a9d-b19f-18f3246e9aea)

**Comment by ODrobik** [comment]
verified
