### ISSUE TITLE
Block "Записатися на курс" - page Privacy policy - should not be displayed

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#209]
**STR**
1. Open https://portal.qax-camp.com.ua/privacy_policy/ and scroll down to the block "Записатися на курс" 
2. Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2090%3A1244 and pay attention to the end of the page.

**ACTUAL RESULT**
Block "Записатися на курс" on the page Privacy policy is shown

**EXPECTED RESULT**
Block "Записатися на курс" on the page Privacy policy is NOT shown

![UTWTNUudY3](https://user-images.githubusercontent.com/109384052/195036024-74454a84-8271-44e6-846e-f873bea4ee55.png)
![FWF1l3S5b2](https://user-images.githubusercontent.com/109384052/195036035-ae39fb53-cf17-4509-9112-e4952117359b.png)

**Comment by BatalovaOlha** [comment]
@ABatalov ти позначив, що баг пофіксили, однак на сайті блок "Записатися" все ще є, а відповідно до дизайну його бути не повинно. Я відправляю баг назад в Оpen.

**Comment by scholokov** [comment]
чому?

**Comment by BatalovaOlha** [comment]
Тепер в фігмі все з блоком "Записатись" Баг закриваю
