### ISSUE TITLE
"Course" or "lesson" page - Toolbar is moved DOWN

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#2097]
**Steps of reproducing**
1. Open [any "course" or "lesson" page](https://t.qax-camp.com.ua/user/dmitrii+nasonov/) AND https://www.qax-camp.com.ua/courses/practical-tools/
2. Pay attention to toolbar

**Actual Result**
Toolbar is moved DOWN 

**Expected Result**
Toolbar isn't moved DOWN 

**Additional information**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design-(Old-Version)?type=design&node-id=10048-108&mode=design&t=zFg82enXCiCetPiJ-0
Also fix it on the [Production](https://www.qax-camp.com.ua/courses/practical-tools/)

**Environments**
Windows 10, Chrome 123.0.6312.106 (64 bit)
![Практичні інструменти – QAX Camp - Google Chrome 10 04 2024 16_09_49](https://github.com/scholokov/qax-portal-2/assets/95171672/19cebb4b-2051-482e-b79b-50e0bd58c41e)

**Comment by DmitriiNasonov** [comment]
#1857

**Comment by poroskundenys** [comment]
готово

**Comment by DmitriiNasonov** [comment]
checked. The bug was fixed partly. Created new bug-report
