### ISSUE TITLE
Header - Hover - Color

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#21]
Надо определится с цветов ховера:

![image](https://user-images.githubusercontent.com/22824947/183077304-84304508-57a9-4576-ab8e-e6447e5bcfd1.png)

**Comment by ABatalov** [comment]
Here you can fing design in Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=799%3A110

**Comment by DmitriiNasonov** [comment]
testing completed
