### ISSUE TITLE
Wiki requirement "Privacy policy" - paragraph V - wrong subparagraph "V-2" name

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#210]
**STR**
1. Open https://github.com/scholokov/qax-portal-2/wiki/Privacy-policy and pay attention to paragraph V - 3d phrase

**ACTUAL RESULT**
The 3d phrase in paragraph V looks like "зазначених в пункті V-2"

**EXPECTED RESULT**
The 3d phrase in paragraph V looks like "зазначених в пункті 2 розділу V"

![0YqdXvzJ0Q](https://user-images.githubusercontent.com/109384052/195326856-d14daa1a-d333-4ad7-87c9-9a556f66f25b.png)

**Comment by ABatalov** [comment]
Fixed

**Comment by ABatalov** [comment]
Fixed

**Comment by BatalovaOlha** [comment]
verified
