### ISSUE TITLE
Menu - Implement a separate menu for mobile devices

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2102]
We need to implement a separate menu for mobile devices.
Environment: https://www.qax-camp.com.ua/
Figma: https://www.figma.com/file/2JlqZybc4fOvZcPT7oiqrg/Portal-design?type=design&node-id=10048-108&mode=design&t=Za65iTHwDQqwxYjH-0

![Menu](https://github.com/scholokov/qax-portal-2/assets/109460500/4992bf66-4c1a-42a0-b2e7-935d286c32f1)

**Comment by poroskundenys** [comment]
Готово

**Comment by ODrobik** [comment]
A new task has been created that is more relevant
