### ISSUE TITLE
Toolbar / Extra element "Налаштування" is in the Drop-down menu of User's icon

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2103]
**Steps to reproduce:**

1. Open  https://www.qax-camp.com.ua/ as authorized user.
2. Click on User's icon.
3. Pay attention to the element "Налаштування" in the Drop-down menu.

**Actual result:**
Extra element "Налаштування" is in the Drop-down menu of User's icon.

**Expected result:**
Extra element "Налаштування" is absent in the Drop-down menu of User's icon.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/1f22cfe8-fe10-4de0-a4ae-27cc78949c50)

**Comment by poroskundenys** [comment]
готово

**Comment by GNatala** [comment]
verified
