### ISSUE TITLE
In the "Course" Preview, the title has a grammatical error

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/qax-portal-2#2105]
Steps to reproduce:

1. Open the page https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-roles/
2. Pay attention to the Preview title

Actual result:

1. The title is "Ролі та артефакти у про**Е**ктній команді"

Expected result:

1. The title must be is "Ролі та артефакти у про**Є**ктній команді"

Attachments:
![Снимок экрана 2024-04-13 в 21 21 19](https://github.com/scholokov/qax-portal-2/assets/130754297/e2232997-4fc1-4e96-8f19-910141043735)

Environment:
Browser: Google Chrome 123.0.6312.122 
OS: macOS 10.15.7

**Comment by Nanafox2010** [comment]
#2107

**Comment by Nanafox2010** [comment]
#2106

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
