### ISSUE TITLE
In the "Course", the heading has a grammatical error

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/qax-portal-2#2106]
Steps to reproduce:
1. Open the page https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-roles/
2. Pay attention to the heading

Actual result:
1. The heading is "Ролі та артефакти у проЕктній команді"

Expected result:
1. The heading must be is "Ролі та артефакти у проЄктній команді"

Attachments:
![Снимок экрана 2024-04-13 в 21 37 15](https://github.com/scholokov/qax-portal-2/assets/130754297/af0a58d3-de2d-4b17-81dd-fadaa8a667e9)

Environment:
Browser: Google Chrome 123.0.6312.122
OS: macOS 10.15.7

**Comment by Nanafox2010** [comment]
#2106

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
