### ISSUE TITLE
"Тестова співбесіда - 06.11.2023" / Spelling mistake in the word "метології"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2109]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/interview/lessons/test-interview/
2. Open accordion "Інтерв’ю – 06.11.2023".
3. Pay attention to the last word "метології" in the second point of "Рецензія від HR до CV:".

**Actual result:**
Spelling mistake оf the word "**метології**".

**Expected result:**
 The word is written as "**методології**".

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/69e1a747-80c7-45e6-a87c-fb1ebbf8e1ed)

**Comment by GNatala** [comment]
#1621

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
