### ISSUE TITLE
Header - Hover - Word-button "Головна" is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#211]
Steps of reproducing:
1) Open https://portal.qax-camp.com.ua/
2) Pay attention to Hover

Actual Result:
Word-button "Головна" is missing

Expected Result:
Word-button "Головна" is present

Specification: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=799%3A110
                      https://github.com/scholokov/qax-portal-2/wiki/Header

Environment:
Windows 10, Chrome 106.0.5249.119 (64 bit)
![QAX Camp – Students Portal - Google Chrome 08 10 2022 15_33_49](https://user-images.githubusercontent.com/95171672/195356241-91f1e461-5502-4a81-ab67-09eac123500c.png)

**Comment by scholokov** [comment]
єкшуал резалт  у даному випадку не являється вимогами, там лише дизайн, а не "що саме потрібно виідображати у головному меню"

**Comment by DmitriiNasonov** [comment]
bug is not actual

**Comment by DmitriiNasonov** [comment]
bug is not actual
