### ISSUE TITLE
Lessons / D - T / Font size of the text "Додатковий матеріал" is 18px

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2110]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-defect/ or any Lesson with the test.
2. Scroll down to the test.
3. Pay attention to the font size of the text "Додатковий матеріал".

**Actual result:**
Font size of the text "Додатковий матеріал" is 18px on Desktop and Tablet.

**Expected result:**
Font size of the text **"Додатковий матеріал" is 24px on Desktop and 21px on Tablet**.
.
**Requirements:** 
https://www.figma.com/file/2JlqZybc4fOvZcPT7oiqrg/Portal-design?type=design&node-id=223-144&mode=design&t=Nxl55Kaepk2lYj7e-0

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/e441c67d-9815-4604-8109-38993cb201e8)
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/470c31cf-8a96-48fc-a6b7-80d2e771c30a)

**Comment by GNatala** [comment]
#2043

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
passed
