### ISSUE TITLE
"Course" and "lesson" page - Toolbar is moved DOWN

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#2111]
**Steps of reproducing**
1. Open [any "course" or "lesson" page](https://qax-camp.com.ua/courses/api-testing/)
2. Pay attention to toolbar

**Actual Result**
Toolbar is moved DOWN 

**Expected Result**
Toolbar isn't moved DOWN 

**Additional information**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design-(Old-Version)?type=design&node-id=10048-108&mode=design&t=zFg82enXCiCetPiJ-0

**Environments**
Windows 10, Chrome 124.0.6367.61 (64 bit)
![Тестування API  Postman   Swagger  Від теорії до практики – QAX Camp - Google Chrome 17 04 2024 16_44_42](https://github.com/scholokov/qax-portal-2/assets/95171672/93bdfe15-10dd-4835-ae23-3b03e568a21e)
![Тестування API  Postman   Swagger  Від теорії до практики – QAX Camp - Google Chrome 17 04 2024 16_44_57](https://github.com/scholokov/qax-portal-2/assets/95171672/1c634e52-03b6-426a-8191-07a0e7476980)

**Comment by DmitriiNasonov** [comment]
#1857

**Comment by DmitriiNasonov** [comment]
#2097

**Comment by scholokov** [comment]
будласка перевір на коректному середовищі

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
