### ISSUE TITLE
wiki/ Requirements - The "Project Quality Level" Lesson is not displayed in the "Процеси" table

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#2112]
**Steps to Reproduce:**

1. Open:https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F
2. Pay attention to the absence of "Project Quality Level" Lesson in the "Процеси" table

**Actual Result:** 
The "Project Quality Level" Lesson is not displayed in the "Процеси" table  

**Expected Result:** 
The "Project Quality Level" Lesson is displayed in the "Процеси" table  

**Environment:**
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/522860f2-da47-43e1-af7d-9ba1679330a6)

**Comment by ODrobik** [comment]
#1254

**Comment by scholokov** [comment]
застралі вимоги

**Comment by ODrobik** [comment]
не є багом
