### ISSUE TITLE
On the Lesson Page, the file icons are not on the same line as the links

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/qax-portal-2#2114]
Steps to reproduce:

1. Open the page https://www.qax-camp.com.ua/courses/postman-snip/lessons/postman-snip/
2. Scroll down to the file icons and links
3. Pay attention to their location with each other

Actual result:

1.  The file icons are not on the same line as the links

Expected result:

1. The file icons must be on the same line as links

Attachments:
![Снимок экрана 2024-04-19 в 17 47 06](https://github.com/scholokov/qax-portal-2/assets/130754297/2e319d7c-c081-44a4-9f45-d436d64d9f88)

Environment:
Browser: Google Chrome 123.0.6312.59
OS: macOS 10.15.7

**Comment by poroskundenys** [comment]
Готово

**Comment by Nanafox2010** [comment]
перевірено
