### ISSUE TITLE
Lessons - "Тестуємо форму Реєстрації" / Spelling mistake in the word "проект"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2118]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/mc-testing/lessons/sandbox-reg-testing/
2. Pay attention to the spelling of the word "проект" in the sentence "Розбираємо яким чином вирішувати завдання “Створення тестової документації” на **проекті** Sandbox.".

**Actual result:**
 The word "проект" is written with the letter "е".

**Expected result:**
 The word "проект" is written with the letter "є".

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/06bc966e-8fb4-4d18-8d79-3f4d3146034b)

**Comment by GNatala** [comment]
#1623

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
