### ISSUE TITLE
Lessons - Quest "Діаграма станів (UML)" / Notification "Please go back and complete the previous Тест." is written in English

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2119]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/sandbox-auth/lessons/sandbox-auth-uml/ o**r any lesson that should be done only after the previous one**.
2. **The previous lesson must not be completed**.
3. Pay attention to the notification " Please go back and complete the previous Тест.".

**Actual result:**
The notification "Please go back and complete the previous Тест." is written in English.

**Expected result:**
 The notification "Please go back and complete the previous Тест." is written in Ukrainian "Для проходження цього уроку вам потрібно пройти попередній".

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

Additional information:
https://www.figma.com/file/2JlqZybc4fOvZcPT7oiqrg/Portal-design?type=design&node-id=390-12775&mode=design&t=fLg5sHxDWqNw3Y7m-0

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/2ad48b9f-cdc5-4185-be0a-0053916e9a8c)

**Comment by GNatala** [comment]
#1622

**Comment by scholokov** [comment]
давайте узгодимо текст зі Свєтланою. можливо його можна дещо скоротити. бо є підозращо не влізе

**Comment by GNatala** [comment]
**Для проходження уроку, пройди попередній.**

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
The issue still exists
![image](https://github.com/user-attachments/assets/2769dd17-58e0-410f-b91b-5a95463e9c1b)

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
passed
