### ISSUE TITLE
Achievements "WiDiQ" / The completed lesson "Створення тестової документації - WDQ" id 18264 is not displayed in the achievements

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2132]
**Preconditions:**
1. Lesson "Створення тестової документації"  https://www.qax-camp.com.ua/courses/widiq-test/lessons/widiq-test-doc/ is completed.

**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/ach-quest-all-by-quest/
2. Pay attention that the Icon "Створення тестової документації" is not marked.

**Actual result:**
The completed lesson "Створення тестової документації - WDQ" id 18264 is not displayed in the achievements.

**Expected result:**
The completed lesson "Створення тестової документації - WDQ" id 18264 is displayed in the achievements.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/9cb6306b-d425-4b4d-aed3-1d2e36fed1d1)
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/003af587-b60e-4247-a39b-9c897e902007)

**Comment by GNatala** [comment]
#2056

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
