### ISSUE TITLE
 Achievements - "Досягнення – Проєкти" - "Web – TVL" - all text in English

### ISSUE THREAD

**Issue by Illia2810** [scholokov/qax-portal-2#2133]
Steps of reproducing

    Open  achievement https://www.qax-camp.com.ua/ach-project-all-by-project/

Actual Result
"Web – TVL" - all text in English(2 line 10)

Expected Result
the text must be in Ukrainian

Additional information
https://qaxm.atlassian.net/wiki/spaces/PM/pages/30277645/-+TVL

Environment:
System: Windows 10 Pro
Browser: FireFox

Attachment:
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/2208e930-9a3e-45b1-b258-37c60914c77a)
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/7cb9cc81-719f-4e62-8734-cc1d54dd4da9)
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/8eba63f9-7107-499c-8b75-d9c1984fdfd8)

**Comment by Illia2810** [comment]
#2113

**Comment by scholokov** [comment]
а що там перекладати?
мені здається написати Веб - ніхто не зрозуміє про що річ

**Comment by Illia2810** [comment]
не є помилкою
