### ISSUE TITLE
Achievements - "Досягнення – Проєкти" - the achievement card "Подорож - Комплексне тестування - Звіт - Web -TVL"  is duplicated

### ISSUE THREAD

**Issue by Illia2810** [scholokov/qax-portal-2#2135]
Steps of reproducing

Open  achievement https://www.qax-camp.com.ua/ach-project-all-by-project/

Actual Result
the achievement card "Подорож - Комплексне тестування - Звіт - Web -TVL"  is duplicated(4 line 11-12)

Expected Result
instead of one such card, there should be "Подорож - Комплексне тестування - Створення тестової документації - Mob - TVL"

Additional information
https://qaxm.atlassian.net/wiki/spaces/PM/pages/30277645/-+TVL

Environment:
System: Windows 10 Pro
Browser: FireFox

Attachment:
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/a6e02d47-f495-4e92-a58a-4fbcb8c344c1)
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/fdc02925-e686-4750-919f-711989f4fc73)

instead of one such card, there should be "Подорож - Комплексне тестування - Створення тестової документації - Mob - TVL"
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/bb21b468-bfd9-4844-b5de-86ae4e3e4aac)

**Comment by Illia2810** [comment]
#2113

**Comment by scholokov** [comment]
дублікат видалено

**Comment by Illia2810** [comment]
перевірено
