### ISSUE TITLE
Achievements - "Досягнення – Проєкти" - in "Metro Retro - TVL" it is not indicated which achievement is obtained

### ISSUE THREAD

**Issue by Illia2810** [scholokov/qax-portal-2#2138]
Steps of reproducing

Open the achievement category https://www.qax-camp.com.ua/ach-project-all-by-project/
Open achievement https://www.qax-camp.com.ua/p-travel/metro-retro-tvl/

Actual Result
Achievements - "Досягнення – Проєкти" - in "Metro Retro - TVL" it is not indicated which achievement is obtained

Expected Result
it is necessary to specify which achievement was obtained

Additional information
https://qaxm.atlassian.net/wiki/spaces/PM/pages/30277645/-+TVL

Environment:
System: Windows 10 Pro
Browser: FireFox

Attachment:
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/59c92bf8-1a0c-4c83-914f-60ccfa5b76ca)
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/2cc04c71-5cb7-435c-b030-d0a3f2da5782)

**Comment by Illia2810** [comment]
#2113

**Comment by scholokov** [comment]
посилання не на ту сторінку

**Comment by Illia2810** [comment]
виправлено

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
