### ISSUE TITLE
Achievements - "Досягнення – Проєкти" - "Testomat – TVL" card - the list of received awards does not meet the requirements

### ISSUE THREAD

**Issue by Illia2810** [scholokov/qax-portal-2#2139]
Steps of reproducing

Open the achievement category https://www.qax-camp.com.ua/ach-project-all-by-project/
Open achievement https://www.qax-camp.com.ua/p-travel/testomat-tvl/

Actual Result
"Testomat – TVL" card - the list of received awards does not meet the requirements

Expected Result
the list of awards meets the requirements

Additional information
https://qaxm.atlassian.net/wiki/spaces/PM/pages/30277645/-+TVL

Environment:
System: Windows 10 Pro
Browser: FireFox

Attachment:
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/f3befd88-0d30-40ca-936e-3bc8bf397025)
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/1237b86c-26c9-4aca-a583-b054ba3b9820)
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/4bf818b6-bd09-408f-b9bc-bac0ef279a6a)

**Comment by Illia2810** [comment]
#2113

**Comment by scholokov** [comment]
посилання не на ту сторінку

**Comment by Illia2810** [comment]
виправлено

**Comment by scholokov** [comment]
виправлено у вимогах

**Comment by Illia2810** [comment]
verified
