### ISSUE TITLE
Achievements - "Досягнення – Проєкти" - "Командний репорт за тиждень - TVL"  the number of points that can be obtained for the award is not specified as in the requirements

### ISSUE THREAD

**Issue by Illia2810** [scholokov/qax-portal-2#2140]
Steps of reproducing

Open the achievement category https://www.qax-camp.com.ua/ach-project-all-by-project/
Open achievement  https://www.qax-camp.com.ua/p-travel/team-report-week-tvl/

Actual Result
"Командний репорт за тиждень - TVL"  the number of points that can be obtained for the award is not specified as in the requirements(3 line 11)

Expected Result
the number of points in the awards must meet the requirements

Additional information
https://qaxm.atlassian.net/wiki/spaces/PM/pages/30277645/-+TVL

Environment:
System: Windows 10 Pro
Browser: FireFox

Attachment:
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/98ea2c00-8ca7-4236-9369-cbce254b2dd4)
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/169dae6d-e382-4218-85e9-41eaa5b5a027)

**Comment by Illia2810** [comment]
#2113

**Comment by scholokov** [comment]
не те посилання

**Comment by Illia2810** [comment]
виправлено

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
