### ISSUE TITLE
Achievements - "Досягнення – Проєкти" - "Подорож - Прев'ю - Верстка - Web"  the number of points that can be obtained for the award is not specified

### ISSUE THREAD

**Issue by Illia2810** [scholokov/qax-portal-2#2141]
Steps of reproducing
Open the achievement category https://www.qax-camp.com.ua/ach-project-all-by-project/
Open achievement https://www.qax-camp.com.ua/p-travel/trip-preview-html-web/

Actual Result
"Подорож - Прев'ю - Верстка - Web"  the number of points that can be obtained for the award is not specified(5 line 7)

Expected Result
the number of points in the awards must meet the requirements

Additional information
https://qaxm.atlassian.net/wiki/spaces/PM/pages/30277645/-+TVL

Environment:
System: Windows 10 Pro
Browser: FireFox

Attachment:
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/fa7f96c1-9db7-465a-ad81-fdfdefe09aa8)
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/1ee976c0-2cab-48ac-9d7d-ff9446d4eb64)

**Comment by Illia2810** [comment]
#2113

**Comment by scholokov** [comment]
не те посилання

**Comment by Illia2810** [comment]
виправлено

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
створив новий схожий баг #2198
