### ISSUE TITLE
Lessons - "Testomat" / Spelling mistake оf the word "проект" and its variants in the content 

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2144]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/testomat/
2. Find all variants of the word "проект"  in the content. **It appears 3 times.**
3. Pay attention to the spelling of the words "проект".

**Actual result:**
 The word "проект" and its variants are written with the letter "е" - 3 times.

**Expected result:**
 The word "проект" and its variants are written with the letter "є" - 3 times.

**Environment:**
Windows 10,
Google Chrome v 124.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/4ba356b1-5053-4d80-b148-85e48fd76b6d)

**Comment by GNatala** [comment]
#1766

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
