### ISSUE TITLE
Lessons - "Testomat" / In the accordion "Спробувати самостійно" there is the missed link from the text "https://app.testomat.io/" to the corresponding page

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2145]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/testomat/
2. Scroll down to the accordion "Спробувати самостійно" - open it. 
3. Pay attention to the text "https://app.testomat.io/ .

**Actual result:**
The text "https://app.testomat.io/ " is not a link to the corresponding page.

**Expected result:**
The text **"https://app.testomat.io/  " is a link** to the corresponding page.

**Environment:**
Windows 10,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/f5773618-2d40-4437-bd7f-feaa1561443b)

**Comment by GNatala** [comment]
#1766

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
