### ISSUE TITLE
"Досягнення – Проєкти – За напрямками" page - "Testomat - TVL" achievement - "Отримано досягнення "Регресія - Звіт - TVL"" and "Отримано досягнення "Регресія - Виконання тестів - TVL"" steps is present

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#2147]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/p-travel/testomat-tvl/

**Actual Result**
"Отримано досягнення "Регресія - Звіт - TVL"" and "Отримано досягнення "Регресія - Виконання тестів - TVL"" steps is present

**Expected Result**
"Отримано досягнення "Регресія - Звіт - TVL"" and "Отримано досягнення "Регресія - Виконання тестів - TVL"" steps is missing

**Additional information**
https://qaxm.atlassian.net/wiki/spaces/PM/pages/30277645/-+TVL

**Environments**
Windows 10, Chrome 124.0.6367.119 (64 bit)

![Testomat – TVL – QAX Camp - Google Chrome 01 05 2024 17_04_42](https://github.com/scholokov/qax-portal-2/assets/95171672/660f5383-d64a-421f-8292-45a9ac7cf265)

**Comment by DmitriiNasonov** [comment]
#2055

**Comment by scholokov** [comment]
виправлено у вимогах

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
