### ISSUE TITLE
"Досягнення – Проєкти – За напрямками" page - "Testomat - TVL" achievement - "Отримано досягнення "Регресія - Виконання тестів - Web"" and "Отримано досягнення "Регресія - Виконання тестів - Mob"" steps is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#2148]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/p-travel/testomat-tvl/

**Actual Result**
"Отримано досягнення "Регресія - Звіт - TVL"" and "Отримано досягнення "Регресія - Виконання тестів - TVL"" steps is present

**Expected Result**
"Отримано досягнення "Регресія - Звіт - TVL"" and "Отримано досягнення "Регресія - Виконання тестів - TVL"" steps is missing

**Additional information**
https://qaxm.atlassian.net/wiki/spaces/PM/pages/30277645/-+TVL

**Environments**
Windows 10, Chrome 124.0.6367.119 (64 bit)
![Testomat – TVL – QAX Camp - Google Chrome 01 05 2024 17_09_56](https://github.com/scholokov/qax-portal-2/assets/95171672/081935e5-6270-4bd4-99d0-0172825ce058)

**Comment by DmitriiNasonov** [comment]
#2055

**Comment by scholokov** [comment]
на чому базується баг?
![image](https://github.com/scholokov/qax-portal-2/assets/22824947/505c9dbc-07f1-4c15-bf76-6d5caf0fbe62)

**Comment by scholokov** [comment]
виправлено у вимогах

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
