### ISSUE TITLE
"Досягнення – Проєкти – За напрямками" page - "Metro Retro – TVL" achievement - "Отримано досягнення" step name is "Отримано досягнення"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#2149]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/p-travel/metro-retro-tvl/

**Actual Result**
"Отримано досягнення" step name is "Отримано досягнення"

**Expected Result**
"Отримано досягнення" step name is "Отримано досягнення - Retro"

**Additional information**
https://qaxm.atlassian.net/wiki/spaces/PM/pages/30277645/-+TVL

**Environments**
Windows 10, Chrome 124.0.6367.119 (64 bit)
![Metro Retro – TVL – QAX Camp - Google Chrome 01 05 2024 17_19_28](https://github.com/scholokov/qax-portal-2/assets/95171672/d45e7fbd-fa84-4db7-bb36-5c636c740b3e)

**Comment by DmitriiNasonov** [comment]
#2055

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
Checked. bug isn't reproducing
