### ISSUE TITLE
 Implemenet password resert

### ISSUE THREAD

**Issue by ABatalov** [scholokov/qax-portal-2#215]
We need to Implemenet password resert   

Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2120%3A431  

Production: https://portal.qax-camp.com.ua/password-reset/

**Comment by ABatalov** [comment]
@scholokov - please check is it correct page for implementation?

**Comment by Nadiyk** [comment]
Verified
