### ISSUE TITLE
"Досягнення – Проєкти – За напрямками" page - "Баг на дизайн – TVL" achievement - "Баг РЕПОТР схвалено ментором" step name is "Баг РЕПОТР схвалено ментором"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#2150]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/p-travel/issues-test-des-tvl/

**Actual Result**
"Баг РЕПОТР схвалено ментором" step name is "Баг РЕПОТР схвалено ментором"

**Expected Result**
"Баг РЕПОТР схвалено ментором" step name is "Баг РЕПОРТ схвалено ментором"

**Additional information**
Also, fix it on requirements (number 25) https://qaxm.atlassian.net/wiki/spaces/PM/pages/30277645/-+TVL

**Environments**
Windows 10, Chrome 124.0.6367.119 (64 bit)
![Баг на дизайн – TVL – QAX Camp - Google Chrome 01 05 2024 17_31_02](https://github.com/scholokov/qax-portal-2/assets/95171672/5b9a4ff9-8f1a-40d9-902e-666d9a865864)

**Comment by DmitriiNasonov** [comment]
#2055

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
Checked. bug isn't reproducing
