### ISSUE TITLE
"Досягнення – Проєкти – За напрямками" page - Achievements from "Звітність" section are duplicated

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#2151]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/p-travel/metro-retro-tvl/

**Actual Result**
Achievements from "Звітність" section are duplicated

**Expected Result**
Achievements from "Звітність" section aren't duplicated

**Additional Information**
https://qaxm.atlassian.net/wiki/spaces/PM/pages/49184769/-

**Environments**
Windows 10, Chrome 124.0.6367.119 (64 bit)
![Досягнення – Проєкти – За напрямками – QAX Camp - Google Chrome 01 05 2024 18_14_08](https://github.com/scholokov/qax-portal-2/assets/95171672/6cd74c2a-5a1c-4ce6-a5fb-e53c6811aa08)

**Comment by DmitriiNasonov** [comment]
#2055

**Comment by scholokov** [comment]
а у вимогах?

**Comment by DmitriiNasonov** [comment]
canceled
