### ISSUE TITLE
Сourse - "Корисні програми" / Spelling mistakes are in the words "проектів" in the course content

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2152]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/qa-basic-programs/
2. Find the words "проектів"  in the content. **It appears 2 times**  in the course content.
3. Pay attention to the spelling of the words "проектів".

**Actual result:**
 The words "проектів" are written with the letter "е" - 2 times.

**Expected result:**
 The words "проектів" are written with the letter "є" - 2 times.

**Environment:**
Windows 10,
Google Chrome v 124.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/df55c4d3-3eca-4f90-9522-b7a8e7894eb0)

**Comment by GNatala** [comment]
#1767

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
