### ISSUE TITLE
Сourse - "Корисні програми" / Spelling mistake is in the word "продуктивностю" in the course content

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2153]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/qa-basic-programs/
2. Find the word "продуктивностю"  in the course content.
3. Pay attention to the spelling of the word "продуктивностю".

**Actual result:**
 The word is written as "продуктивн**о**стю".

**Expected result:**
 The word is written as "продуктивн**і**стю".

**Environment:**
Windows 10,
Google Chrome v 124.0.5359.125 (x64)

**Attachment:**

![image](https://github.com/scholokov/qax-portal-2/assets/101987790/8147fabb-8616-4b7e-89d1-8c6fd9615f4f)

**Comment by GNatala** [comment]
#1767

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
