### ISSUE TITLE
Lesson "Звітуємо по тестуванню форми Реєстрації" / Spelling mistake is in the word "проекті" in the content 

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2154]
**Steps to reproduce:**

1. Open  https://www.qax-camp.com.ua/courses/mc-testing/lessons/sandbox-reg-reporting/
2. Find the sentense "Розбираємо яким чином вирішувати завдання “Тест звітність” на проекті Sandbox".
3. Pay attention to the spelling of the word "проекті".

**Actual result:**
 The words "проекті" is written with the letter "е".

**Expected result:**
 The word "проекті" is written with the letter "є".

**Environment:**
Windows 10,
Google Chrome v 124.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/f700e04a-942f-4955-8308-916b3c3f23b2)

**Comment by GNatala** [comment]
#1768

**Comment by scholokov** [comment]
мабуть не те посилання

**Comment by GNatala** [comment]
Виправила, дякую

**Comment by scholokov** [comment]
Please retest

**Comment by GNatala** [comment]
passed
