### ISSUE TITLE
Lesson "Звітуємо по тестуванню форми Реєстрації" / Spelling mistake is in the word "проекті" in the description of the Lesson 

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2155]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/mc-testing/
2. Find Lesson "Звітуємо по тестуванню форми Реєстрації".
3. Pay attention to the description of the Lesson "Розбираємо яким чином вирішувати завдання “Тест звітність” на проекті Sandbox".
4. Pay attention to the spelling of the word "проекті".

**Actual result:**
 The words "проекті" is written with the letter "е".

**Expected result:**
 The word "проекті" is written with the letter "є".

**Environment:**
Windows 10,
Google Chrome v 124.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/47e35341-0f14-4743-b58d-1468129fb8b8)

**Comment by GNatala** [comment]
#1768

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
passed
