### ISSUE TITLE
"Досягнення – Проєкти – За напрямками" page - "Тестова документація (тест кейси та чек-лісти)", "Системи управління розробкою та тестуванням", "Тестування, Відладка", "Колаборація, Планування" sections are missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#2156]
**Steps of reproducing**
1. Open https://www.qax-camp.com.ua/ach-project-all-by-topics/

**Actual Result**
"Тестова документація (тест кейси та чек-лісти)", "Системи управління розробкою та тестуванням", "Тестування, Відладка", "Колаборація, Планування" sections are missing

**Expected Result**
"Тестова документація (тест кейси та чек-лісти)", "Системи управління розробкою та тестуванням", "Тестування, Відладка", "Колаборація, Планування" sections are present

**Additional information**
https://qaxm.atlassian.net/wiki/spaces/PM/pages/30277645/-+TVL

**Environments**
Windows 10, Chrome 124.0.6367.156 (64 bit)
![Досягнення – Проєкти – За напрямками – QAX Camp - Google Chrome 08 05 2024 16_17_00](https://github.com/scholokov/qax-portal-2/assets/95171672/22dd70f5-4d5e-4d73-88d3-b8ad7be5fd0f)

**Comment by DmitriiNasonov** [comment]
#2055

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
