### ISSUE TITLE
Implement login/logout in Header 

### ISSUE THREAD

**Issue by ABatalov** [scholokov/qax-portal-2#216]
We need to implement login/logout in Header  

Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=1979%3A247  

Production: all pages  

"налаштування" - do not add now

**Comment by poroskundenys** [comment]
Я не нашел чтобы у пользователя были данные о поле, поэтому у всех будет выводится надпись Студент

**Comment by dmitryylev** [comment]
Verified
