### ISSUE TITLE
Achievements - "Досягнення – Загальні" - "Естімація та Ризики" the achievement is duplicated "Тестування вимог – REG"

### ISSUE THREAD

**Issue by Illia2810** [scholokov/qax-portal-2#2161]
Steps of reproducing

1. Open achievement https://www.qax-camp.com.ua/ach-all/

Actual Result
"Естімація та Ризики" the achievement is duplicated "Тестування вимог – REG"(extreme right)

Expected Result
achievements cannot be duplicated

Additional information
https://qaxm.atlassian.net/wiki/spaces/PM/pages/30277645/-+TVL

Environment:
System: Windows 10 Pro
Browser: FireFox

Attachment:
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/c70e8249-0598-41e9-b0db-c39391cc992a)

should be here
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/3c6df601-a3ae-48c9-b354-69ff2df13322)

**Comment by Illia2810** [comment]
#2113

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
