### ISSUE TITLE
Achievements - "Досягнення – Загальні" in the section "Тестування, Відладка" extra achievements

### ISSUE THREAD

**Issue by Illia2810** [scholokov/qax-portal-2#2163]
Steps of reproducing

    Open achievement https://www.qax-camp.com.ua/ach-all/

Actual Result
in the section "Тестування, Відладка" extra achievements

Expected Result
in the section "Тестування, Відладка" must be achievements "LambdaTest - TVL", "HTML & CSS Валідатори - TVL", "DevTools - TVL", "Miro - TVL", "Figma - TVL"

Additional information
https://qaxm.atlassian.net/wiki/spaces/PM/pages/30277645/-+TVL

Environment:
System: Windows 10 Pro
Browser: FireFox

Attachment:
shouldn't be here
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/dcabd6e7-6509-49fc-bb6a-4745633130e2)
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/3966a64c-d511-4602-b1e8-5c9aa9e0ce12)
should be here
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/2aab1b10-c762-4afd-bad8-87d76feb06ea)

**Comment by Illia2810** [comment]
#2113

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
