### ISSUE TITLE
Achievements - "Досягнення – Проєкти – За напрямками" in the "Тест Дизайн" block extra achievements 

### ISSUE THREAD

**Issue by Illia2810** [scholokov/qax-portal-2#2164]
Steps of reproducing

Open achievement https://www.qax-camp.com.ua/ach-project-all-by-topics/

Actual Result
in the "Тест Дизайн" block extra achievements 

Expected Result
in the "Тест Дизайн" block there should be only the achievement - "Декомпозиція"

Additional information
https://qaxm.atlassian.net/wiki/spaces/PM/pages/30277645/-+TVL

Environment:
System: Windows 10 Pro
Browser: FireFox

Attachment:
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/476451d9-dbe1-443f-b811-418398e28238)
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/5b70ec6e-438e-43d2-aac0-56814c55f978)

**Comment by Illia2810** [comment]
#2113

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
