### ISSUE TITLE
Test results / The style and name of the button "Натисніть, щоб продовжити" does not match Figma

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2165]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-02-testing-types/quizzes/q5-test-types/
2. Click on "Розпочати тест" under the picture.
3. Test is opened.
4. Complete the test successfully.
5. Click the button "Завершити тест".
6. Pay attention to the button "Натисніть, щоб продовжити" in the test results. 

**Actual result:**
The style and name of the button "Натисніть, щоб продовжити" does not match Figma.

**Expected result:**
The name of the button "Натисніть, щоб продовжити" is "Далі", the style of the button matches Figma.

**Requirements:**
https://www.figma.com/design/2JlqZybc4fOvZcPT7oiqrg/Portal-design?node-id=1212-66&t=Ubv2upOPo8wJxOq4-0

**Environment:**
Windows 10,
Google Chrome v 124

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/c9d99ac8-b255-424d-81b2-cc8ef3006bd8)

**Comment by GNatala** [comment]
#1998

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
passed
