### ISSUE TITLE
Achievements - "Досягнення – Проєкти – За напрямками" - "Досягнення та знання, які отримаєш" no "Тестова документація" block

### ISSUE THREAD

**Issue by Illia2810** [scholokov/qax-portal-2#2167]
Steps of reproducing

Open achievement https://www.qax-camp.com.ua/ach-project-all-by-topics/

Actual Result
"Досягнення та знання, які отримаєш" no "Тестова документація" block

Expected Result
must be a block "Тестова документація"

Additional information
https://qaxm.atlassian.net/wiki/spaces/PM/pages/30277645/-+TVL

Environment:
System: Windows 10 Pro
Browser: FireFox

Attachment:
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/8fd43357-b007-4937-a2d6-a84821a87ea5)
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/534519e7-6f5a-4a25-b4ec-9a476e3dd0c0)

**Comment by Illia2810** [comment]
#2113

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
#2113
