### ISSUE TITLE
Course / M / The extra element "black dot" is in the Lesson

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2173]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q6-basic/.
2. Scroll down to the Lesson
3. Pay attention to the element "black dot" is in the Lesson.

**Actual result:**
 The extra element "black dot" is in the Lesson
**Expected result:**
The element "black dot" " is absent is in the Lesson.

**Requirements:** 
https://www.figma.com/design/2JlqZybc4fOvZcPT7oiqrg/Portal-design?node-id=390-1035&t=Vem6TxkG3n6JASLa-0

**Environment:**
Mobile
Windows 10,
Google Chrome v 125

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/2b55e004-beb2-47cd-a3e5-1b3b574247aa)

**Comment by GNatala** [comment]
#1935

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
passed
