### ISSUE TITLE
Course / M / The color of the completed lesson card consists of two colors

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2178]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q6-basic/.
2. Scroll down to the completed Lesson.
3. Ореn card of the Lesson by clicking on down arrow.
4. Pay attention to that the color of the completed lesson card consists of two colors.

**Actual result:**
The color of the completed lesson card consists of two colors.
**Expected result:**
The color of the completed lesson is #E9E8EA.

**Requirements:** 
https://www.figma.com/design/2JlqZybc4fOvZcPT7oiqrg/Portal-design?node-id=390-1035&t=Vem6TxkG3n6JASLa-0

**Environment:**
Mobile
Windows 10,
Google Chrome v 125

**Attachment:**

![image](https://github.com/scholokov/qax-portal-2/assets/101987790/dbad4297-50cc-429c-bf8f-a988f715ae33)

**Comment by GNatala** [comment]
#1935

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
