### ISSUE TITLE
wiki/ Requirements - the name "StatCounter" lesson is not written in the "Корисні програми" table

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#2181]
Steps to Reproduce:
1. Open: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA
2. Pay attention to the name "StatCounter" lesson is not written in the "Корисні програми" table

**Actual Result:** 
the name "StatCounter" lesson is not written in the "Корисні програми" table
**Expected Result:** 
the name "StatCounter" lesson is written in the "Корисні програми" table

**Environment:**
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/bd668bd9-157a-4396-8109-7e441ad3753e)

**Comment by ODrobik** [comment]
#1427

**Comment by scholokov** [comment]
застарілі вимоги

**Comment by ODrobik** [comment]
не є багом
