### ISSUE TITLE
wiki/ Requirements - the name "QA Звітність" lesson is not written in the "Тестування" table

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#2183]
Steps to Reproduce:
1. Open: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA
2. Pay attention to the name "QA Звітність" lesson is not written in the "Тестування" table

**Actual Result:**
the name "QA Звітність" lesson is not written in the "Тестування" table
**Expected Result:**
the name "QA Звітність" lesson is written in the "Тестування" table

**Environment:**
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/7efad604-9de3-487c-92d7-c61e192b4e27)

**Comment by ODrobik** [comment]
#1426

**Comment by scholokov** [comment]
застарілі вимоги

**Comment by ODrobik** [comment]
не є багом
