### ISSUE TITLE
Certificate - Create a checklist or test case for Certificate testing

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2185]
We need to create a checklist or test case for Certificate testing.
Figma: https://www.figma.com/design/2JlqZybc4fOvZcPT7oiqrg/Portal-design?node-id=9618-114&t=74tvDZTfz7aYq18O-0
TMS: https://app.testomat.io/projects/portal-web/

![Certificate](https://github.com/scholokov/qax-portal-2/assets/109460500/f53e57e6-0229-4633-9cb3-75a079d33560)

**Comment by GNatala** [comment]
https://app.testomat.io/projects/portal-web/
