### ISSUE TITLE
Course / The color of the lesson's card is #e9e8ea in completed and uncompleted states

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2186]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q6-basic/ or any Course.
2. Scroll down to the Lessons.
4. Pay attention to the color of the lesson's card.

**Actual result:**
The color of the lesson's card is #e9e8ea in completed and uncompleted states.

**Expected result:**
**Desktop - The color of the lesson's card is #35324B in completed and uncompleted states.
Tablet, Mobile - The color of the lesson's card is #35324B in the uncompleted state and #e9e8ea is in the completed state.**

**Requirements:** 
https://www.figma.com/design/2JlqZybc4fOvZcPT7oiqrg/Portal-design?node-id=390-1035&t=Vem6TxkG3n6JASLa-0

**Environment:**
Windows 10,
Google Chrome v 125

**Attachment:**
https://jam.dev/c/33bc3698-43d8-477c-8cd1-77cb09f80758
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/3742c1e0-7180-4371-aea4-2587861aed87)

![image](https://github.com/scholokov/qax-portal-2/assets/101987790/8475c35d-8008-4f05-a6d9-ca970073f392)

**Comment by GNatala** [comment]
#1935

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
passed
