### ISSUE TITLE
"Основи Security Тестування" event - After registration link to the meeting is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#2187]
**Steps of reproducing**
1. Log in to your account with access to "Основи Security Тестування" event
2. Open https://www.qax-camp.com.ua/events/security-basics/

**Actual Result**
After registration link to the meeting is missing

**Expected Result**
After registration link to the meeting is present

**Additional information**
The display of the event page is the same when viewing while logging into the account where you registered for the event AND when viewing without logging into the account.
https://www.figma.com/design/UyTNSS6KCOdphdTev1HrLF/Portal-design-(Old-Version)?node-id=6076-949&t=i5ozV6NAxigtHwpy-0
https://www.figma.com/design/UyTNSS6KCOdphdTev1HrLF/Portal-design-(Old-Version)?node-id=5699-913&t=i5ozV6NAxigtHwpy-0

**Environments**
Windows 10, Chrome 125.0.6422.113 (64 bit)
Android 8.1.0, 125.0.6422.72 Chrome
![Основи Security Тестування – QAX Camp - Google Chrome 29 05 2024 14_19_31](https://github.com/scholokov/qax-portal-2/assets/95171672/4cd2230f-accb-450e-943d-15ef8399d8f6)
![photo_2024-05-29_14-35-25](https://github.com/scholokov/qax-portal-2/assets/95171672/44417128-ba61-424b-bac2-1cb33cfe5238)

**Comment by DmitriiNasonov** [comment]
#1236

**Comment by scholokov** [comment]
не актуально для цього івенту

**Comment by DmitriiNasonov** [comment]
canceled
