### ISSUE TITLE
Chat - Unfolded chat - Chat welcome message doesn't meet the requirements

### ISSUE THREAD

**Issue by KaterinaNimenko35** [scholokov/qax-portal-2#219]
**Steps to reproduce:**

1. Open page https://portal.qax-camp.com.ua/
2. In the lower right corner of the page, click on the chat button "Потрібна допомога?"
3. Pay attention to the chat welcome message

**Actual result:**
"Вау! Перший крок до мрії зроблено✅!" 

**Expected result:**
"Вітаємо у прогресивному просторі QAX!" "Чим можу бути корисним?"

**Environment:**
Desktop/W10/Google Chrome 101.0.4951.67 (64-bit)

![2022-10-16 18 41 01](https://user-images.githubusercontent.com/105543094/196044767-ae06ac36-ad02-4eb9-9a17-96cfda80bba1.png)

![2022-10-16 18 43 25](https://user-images.githubusercontent.com/105543094/196044897-fb4ab003-00db-40dc-91a5-cee6e9b74aeb.png)

**Comment by DmytroMarkulych** [comment]
@KaterinaNimenko35 давайте, зробимо більше чіткіше summary

**Comment by KaterinaNimenko35** [comment]
Corrected

**Comment by KaterinaNimenko35** [comment]
#292

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
