### ISSUE TITLE
Course / Extra elements "dot" and text "Додатковий матеріал" are in the card of the Lesson

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2192]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q6-basic/.
2. Scroll down to the Lesson
3. Pay attention to the elements "dot" and text "Додатковий матеріал" are in the card of the Lesson.

**Actual result:**
 Extra elements "dot" and text "Додатковий матеріал" are in the card of the Lesson.
 
**Expected result:**
Extra elements "dot" and text "Додатковий матеріал" are absent in the card of the Lesson.

**Requirements:** 
https://www.figma.com/design/2JlqZybc4fOvZcPT7oiqrg/Portal-design?node-id=390-1035&t=Vem6TxkG3n6JASLa-0

**Environment:**
Windows 10,
Google Chrome v 125

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/e9371927-2332-46b2-86c6-13e37f084873)

**Comment by GNatala** [comment]
#1935

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
passed
