### ISSUE TITLE
Achievements - "Досягнення – Проєкти" - "Подорож - Прев'ю - Верстка - Web" the name of the Points is incorrect

### ISSUE THREAD

**Issue by Illia2810** [scholokov/qax-portal-2#2198]
Steps of reproducing
Open the achievement category https://www.qax-camp.com.ua/ach-project-all-by-project/
Open achievement https://www.qax-camp.com.ua/p-travel/trip-preview-html-web/

Actual Result
"Подорож - Прев'ю - Верстка - Web" the name of the Points is incorrect "7 Points"
Expected Result
Points must be specified as "Travel-points"

Additional information
https://qaxm.atlassian.net/wiki/spaces/PM/pages/30277645/-+TVL

Environment:
System: Windows 10 Pro
Browser: FireFox

Attachment:
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/32a11c49-d7f1-433e-ba5c-a424efd3e54d)
![зображення](https://github.com/scholokov/qax-portal-2/assets/125801673/e3041657-f6cf-4a3d-87b7-165d656b8e8f)

**Comment by Illia2810** [comment]
#2113

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
