### ISSUE TITLE
Lesson-Topic: HTML Code

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#22]
Нужен дизайн для HTML блока

сейчас выглядит так:
![image](https://user-images.githubusercontent.com/22824947/183441837-b6044790-90a7-4ba2-b822-57333f959386.png)

а вот так мог. Нужен шрифт отличный от обычного текста
![image](https://user-images.githubusercontent.com/22824947/183441731-55c147c1-a5fb-4bba-8373-c49ff5c5979c.png)

пример:
https://portal.qax-camp.com.ua/lessons/basic-html-for-qa/

фігма:
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=799%3A168

**Comment by ABatalov** [comment]
Here you can fing design in Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=799%3A168

**Comment by KaterinaNimenko35** [comment]
verified
