### ISSUE TITLE
Photo "Dmytro Markulych trainer" - page "Наші тренери" - does not meet the requirements Figma

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#220]
**STR**
1. Open https://portal.qax-camp.com.ua/trainers/ 
2. Open https://www.figma.com/file/JwKf4NLnNlzrSCaBlbhKu4/QAX-Camp-(Copy)?node-id=4542%3A1268 
3. Pay attention to the photo "Dmytro Markulych trainer"

**ACTUAL RESULT**
"Dmytro Markulych trainer" photo displayed with sharp corners

**EXPECTED RESULT**
"Dmytro Markulych trainer" photo displayed with rounded corners
![YsVQlyT1Q4](https://user-images.githubusercontent.com/109384052/196055572-1513832a-b5d8-403f-843c-5eb58a41b800.png)

![xvo5gniLm1](https://user-images.githubusercontent.com/109384052/196055573-b6fdbe54-df60-435c-8559-8586f7616ee1.png)

**Comment by scholokov** [comment]
fiexed

**Comment by BatalovaOlha** [comment]
verified
