### ISSUE TITLE
Event "Майстер-клас по тестуванню модулю “Реєстрація” ч2" / The link http://meet.google.com/pwy-qpde-fpc to the event is not underlined. 

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2201]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/events/mc-registration-2/
2. Pay attention to the text **http://meet.google.com/pwy-qpde-fpc**.

**Actual result:**
The link http://meet.google.com/pwy-qpde-fpc to the event is not underlined. 

**Expected result:**
The link http://meet.google.com/pwy-qpde-fpc to the event is underlined.

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=390-12775&t=CCIMoK768HaqdmMQ-0

**Environment:**
Windows 10
Google Chrome v 125.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/acadfa75-c239-4ae0-8b61-786a379d82c8)

**Comment by GNatala** [comment]
#1375

**Comment by poroskundenys** [comment]
@scholokov @GNatala У меня нет этой ссылки https://prnt.sc/I_EOvzEPRuYF

**Comment by scholokov** [comment]
вона відображалось лише зареєстрованим. я виправив - тепер відображається всім
тут малося на увазі що в принципі всі посилання не підкреслюються

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
passed
