### ISSUE TITLE
Lesson "Test Management System (TMS)" / Missed word "Тест:" before the test in the Lesson

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2202]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/testing/
2. Pay attention to the lesson "Test Management System (TMS)".

**Actual result:**
Missed word "Тест:" before the test in the Lesson.

**Expected result:**
Word "Тест:" is present before the test in the Lesson

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=390-12775&t=CCIMoK768HaqdmMQ-0

**Environment:**
Windows 10
Google Chrome v 125.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/5a738c0a-ce6b-4865-acac-86623693a625)

**Comment by GNatala** [comment]
#1373

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
