### ISSUE TITLE
Paid event confirmation email do not delivered

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#2206]
**Steps to reproduce:**
1. Open https://www.qax-camp.com.ua/events/auth-web-jwt/
2. Register for the event
3. Check e-mail

**Actual result:**
Email "Реєстрацію на подію підтверджено!" was **not** delivered

**Expected result:**
Email "Реєстрацію на подію підтверджено!" was delivered

Notes:
you can check on the user:

e-mail | Registered
--- | ---
neptunxp@gmail.com | 18:12, July 9

**Additional information:**
 The "Реєстрацію на подію підтверджено!" email was sent to the user's email **for FREE events**

**Environment:**
Windows 10
Google Chrome v 125.0.5359.125 (x64)

**Comment by poroskundenys** [comment]
Готово

**Comment by ODrobik** [comment]
@poroskundenys 
Лист  "Реєстрацію на подію підтверджено!"  не прийшов для користувачів
e-mail | Registered
--- | ---
drobikoksana86@gmail.com | 12:07, July 17
natalya.guzir@gmail.com | 09:08, July 18

**Comment by poroskundenys** [comment]
@scholokov Проблема для новых событий еще существует?

**Comment by ODrobik** [comment]
Перевірено для нових платних подій. Лист "Реєстрацію на подію підтверджено!" прийшов
