### ISSUE TITLE
Test results - Implement a button "Назад" in according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2208]
After pressing the button "Назад" the user returns to the corresponding lesson.
Environment: https://www.qax-camp.com.ua/courses/testing/lessons/q6-02-testing-types/quizzes/q5-test-types/
Figma: https://www.figma.com/design/2JlqZybc4fOvZcPT7oiqrg/Portal-design?node-id=1212-66&t=2Wr1AqFRF3ZW8v55-0

![Кнопка назад](https://github.com/user-attachments/assets/7632a00e-f821-46c9-98da-e0edf80df088)

**Comment by poroskundenys** [comment]
Готово

**Comment by ODrobik** [comment]
перевірено
