### ISSUE TITLE
Create design of "404" page on Portal Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#221]
We need to create design of "404" page on Portal Figma.
Design on Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2452%3A542
Page design example:
![404](https://user-images.githubusercontent.com/109460500/196207000-1b81f8d3-4e4e-40ad-aa83-74f764e8fe7d.jpg)

**Comment by AlonaSarapina** [comment]
ready for testing https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2452%3A543

**Comment by AlonaSarapina** [comment]
tablet and mobile version added https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2452%3A542

**Comment by KaterinaNimenko35** [comment]
Verified
