### ISSUE TITLE
Event - Text in the "BOOK EVENT" block is written in English

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2210]
**Steps to reproduce:**
1. Open https://www.qax-camp.com.ua/events/auth-web-jwt/
2. Pay attention to the text in the booking for Event block.

**Actual result:**
Text in the booking for Event block is written in English.

**Expected result:**
Text in the booking for Event block is written in Ukrainian.

**Environment:**
Windows 10
Google Chrome v 125.0.5359.125 (x64)

**Additional information:**
![image](https://github.com/user-attachments/assets/b0d0e2a7-1d15-4c2b-8cb1-7a39adab37d0)

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
