### ISSUE TITLE
Event - Extra text "BOOK EVENT" in the booking for Event

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2212]
**Steps to reproduce:**
1. Open https://www.qax-camp.com.ua/events/auth-web-jwt/
2. Pay attention to the text in the block "BOOK EVENT" 

**Actual result:**
 Extra text "BOOK EVENT" in the booking for Event

**Expected result:**
Text "BOOK EVENT" is not present in the booking for Event.

**Environment:**
Windows 10
Google Chrome v 125.0.5359.125 (x64)

**Additional information:**
![image](https://github.com/user-attachments/assets/f7d7e1aa-694e-473b-bed7-cf72909f58d8)

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
