### ISSUE TITLE
Calendar - Measure distances between elements

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2213]
**To do**
Measure and write down the distances between the elements on these pages:
1. Calendar. Between the top banner and the calendar area.
2. Cards on the site's home page. Between the cards, not including the hover.

Environment: https://www.qax-camp.com.ua/calendars/

![Календар](https://github.com/user-attachments/assets/4b7428ce-ceda-4abe-8fe8-aa343ba7ac6e)

Figma: https://www.figma.com/design/2JlqZybc4fOvZcPT7oiqrg/Portal-design?node-id=10048-108&t=UHDaDT8cqDCjnHJS-0

![Карточки](https://github.com/user-attachments/assets/f67a0823-163b-4734-a1f9-66375833f0b3)

**Comment by GNatala** [comment]
1. Caledar 20px
![image](https://github.com/user-attachments/assets/3134f7df-1b4e-403a-8baf-24893e6c8a9b)
2.Home page Figma 45px
![image](https://github.com/user-attachments/assets/2bb923d0-f9bb-46cf-a9e3-4c7ee892880d)

Home page https://www.figma.com/design/2JlqZybc4fOvZcPT7oiqrg/Portal-design?node-id=10048-108&t=UHnDaDT8cqDCjnHJS-0 are not realized.

**Comment by ButKoff** [comment]
Зараз відстань між банаром та календарем 45px

**Comment by GNatala** [comment]
passed
