### ISSUE TITLE
Page elements - Color should be the same

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2214]
The background of page elements must be the same color.
Check the color of such elements:
- Home page
- Calendar page

Environment: https://www.qax-camp.com.ua/calendars/

![Календар](https://github.com/user-attachments/assets/74b83bd5-dd9a-4b4b-8a94-39f9839423a9)

Figma: https://www.figma.com/design/2JlqZybc4fOvZcPT7oiqrg/Portal-design?node-id=10048-108&t=UHDaDT8cqDCjnHJS-0

![Карточки](https://github.com/user-attachments/assets/a4ac6fc0-1dd4-4b06-a4e5-5ec62afb7f7b)

**Comment by GNatala** [comment]
1. Banner background: #3E3B5E;
![image](https://github.com/user-attachments/assets/0b8f2c49-6fcc-42dc-a601-f8a2a2944376)
2.Calendar background: #35324B;
![image](https://github.com/user-attachments/assets/6346d611-315b-4f7b-9fca-c66f7eed3fc6)
3. Home page card Figma background: #35324B
![image](https://github.com/user-attachments/assets/4c990b44-d779-4a09-b974-70fc1837c7cd)
