### ISSUE TITLE
Checkout - Implement the element "х" according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2215]
You should implement the element according to Figma.

Environment: https://www.qax-camp.com.ua/checkout/

Figma: https://www.figma.com/design/2JlqZybc4fOvZcPT7oiqrg/Portal-design?node-id=6398-1146&t=LEfGVsWTZacUV5ds-0

![Checkout](https://github.com/user-attachments/assets/9de28a1e-d08a-476c-92c0-15f067934d24)

**Comment by poroskundenys** [comment]
Готово
