### ISSUE TITLE
Body and Footer - Check the distance between elements

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2216]
The distance between the body and the footer on all pages of the site should be the same.

Application Decomposition: https://qaxm.atlassian.net/wiki/spaces/PM/pages/17989644

Example test area:

![Footer](https://github.com/user-attachments/assets/8cdfa548-fd0a-42f3-b92b-7927a14de0b9)

![Footer_](https://github.com/user-attachments/assets/de2df03a-e6f7-4427-93f0-bd0675b4c48f)

![Footer_1](https://github.com/user-attachments/assets/8e455f9f-b744-4cb2-971c-ba830761c442)

**Comment by GNatala** [comment]
1. https://www.qax-camp.com.ua/ **Home page - 150px**
![image](https://github.com/user-attachments/assets/111cd846-a05b-424d-b59f-480cbb315496)
2. https://www.qax-camp.com.ua/current_cources/ **Напрямки - 150px**
![image](https://github.com/user-attachments/assets/39521477-f9ff-4c80-8387-b35b89f0ea52)
3. https://www.qax-camp.com.ua/course-list/ **Курси список - 150px**
![image](https://github.com/user-attachments/assets/a6984124-1642-47b7-95e9-455d65b114b7)
3.1 https://www.qax-camp.com.ua/courses/c-qa-entry/ **Courses - 180px**
![image](https://github.com/user-attachments/assets/79feca70-03bd-44be-8b40-fb020e371b56)
3.2  https://www.qax-camp.com.ua/courses/c-qa-entry/lessons/who-is-qa/ **Lessons - 180px**
![image](https://github.com/user-attachments/assets/cae29b04-0d4a-49f0-8b9f-d08cc0ef4da1)
3.3  https://www.qax-camp.com.ua/courses/q6-basic/lessons/who-is-qa/quizzes/q5-01-who-is-qa/ -**Test -70px**
![image](https://github.com/user-attachments/assets/95f151e1-e1a1-41d1-9807-b7a88cd8b7a7)
4. https://www.qax-camp.com.ua/practice-team/ **Практика - 150px**
![image](https://github.com/user-attachments/assets/2daeac53-9e25-4ef0-8c73-bc19511960e6)
5. https://www.qax-camp.com.ua/courses/project-travel/ **Практика travel-180px**
![image](https://github.com/user-attachments/assets/83b0041d-325c-4842-9f58-996f7cfff21a)
6. https://www.qax-camp.com.ua/qa-quest/ **Квести- 150px**
![image](https://github.com/user-attachments/assets/524f6da1-f1a4-48d8-8526-d83eeab635f9)
7. https://www.qax-camp.com.ua/ach-all/ - **Досягнення - 0px** **ALL**
![image](https://github.com/user-attachments/assets/ef8d3b46-1c83-478d-bccc-45f62acb0416)
8. https://www.qax-camp.com.ua/calendars/  - **Календар - 140px**
![image](https://github.com/user-attachments/assets/3f492dcd-e43e-48d3-bda2-161ad2a65172)
8.1 https://www.qax-camp.com.ua/events/qax-practice-travel/?occurrence=2024-08-07 - **Event Practice- 20px** 
![image](https://github.com/user-attachments/assets/7a204f81-9f97-41d8-a41c-936cd4d67ea4)
8.2 https://www.qax-camp.com.ua/events/postman-snip/?occurrence=2024-08-08&time=1723138200 - **Event paid -250px**
![image](https://github.com/user-attachments/assets/9d44992e-f8bc-4b9c-97f3-ac5b3e516de0)
9. https://www.qax-camp.com.ua/about-us-2/ - **Про Нас -150px**
![image](https://github.com/user-attachments/assets/279cce7f-5166-4456-928a-cce26e25ce4b)
10. https://www.qax-camp.com.ua/trainers/ -**Наші тренери -150px**
![image](https://github.com/user-attachments/assets/06b4e9f9-8cf4-4a73-9980-2b0d0460ee47)
11. https://www.qax-camp.com.ua/login/  - **Логін - 0px** -30px
![image](https://github.com/user-attachments/assets/2c5bc988-3ff9-4717-a2b8-38353f64bb4f)
![image](https://github.com/user-attachments/assets/f03d14cd-c583-49db-b3ad-fcb93ee6f1f2)
12. https://www.qax-camp.com.ua/checkout/ **Checkout - 285px**
![image](https://github.com/user-attachments/assets/2c6c3f46-0c47-4364-86a5-3cca8c3524cd)
13. https://www.qax-camp.com.ua/product/qax-outsource-2-0/ **Order -300px**
![image](https://github.com/user-attachments/assets/f1f14542-1bfa-4747-9083-15aeeefe49c8)
14.https://www.qax-camp.com.ua/certificate/1273226CB-1276EB9D4-7B5A0/ - **Сертифікат - 70px**
![image](https://github.com/user-attachments/assets/94aa2591-b428-4853-b577-0d1305b35afe)
15. https://www.qax-camp.com.ua/courses/hrs-1/lessons/hrs-1-estimation/quizzes/hrs-1-estimation/ - **завдання в Квесті - 72px**
![image](https://github.com/user-attachments/assets/d8d837aa-43b3-4fa6-af0f-b908c7984b3a)
16. https://www.qax-camp.com.ua/user/natalia+huzyr/?um_action=edit - **Account - 60px**
![image](https://github.com/user-attachments/assets/aa557aea-6f24-4a13-a8a5-43ce35499ca0)

**Comment by GNatala** [comment]
passed
