### ISSUE TITLE
Popup - Implement a popup in site colors and change the names of elements

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2217]
You should implement the popup in the site colors and change the names of the elements.

Environment: https://www.qax-camp.com.ua/events/postman-snip/?occurrence=2024-08-08&time=1723138200

Example Popup:

![Popup](https://github.com/user-attachments/assets/9f8749be-3d05-4721-825f-1b9ae8ba4e99)

Name of items to change:

1. Select date - Графік зустрічей;
2. Ticket selected - Прийняти участь.

Name of items to delete:

1. Book Event.

![Popup_prod](https://github.com/user-attachments/assets/383db0a1-2c7e-4585-8820-23aabf26c553)

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
passed
