### ISSUE TITLE
Test "Q5 – Види тестування" - question 6 - incorrect word "лишній"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#222]
**STR**
1. Open https://portal.qax-camp.com.ua/login/ and login
2. Go to the page https://portal.qax-camp.com.ua/quizzes/q5-test-types/
3. Press "Start quiz" and press 6 question - "За рівнем тестування який вид лишній у наведеному нижче списку?"

**ACTUAL RESULT**
The question looks like  "За рівнем тестування який вид **лишній** у наведеному нижче списку?"

**EXPECTED RESULT**
The question looks like  "За рівнем тестування який вид **зайвий** у наведеному нижче списку?"

![VFvAa5o4V5](https://user-images.githubusercontent.com/109384052/196644395-7bab7199-1d15-4632-b275-281124a83b0a.png)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
