### ISSUE TITLE
Achievements - Postman: Сніпети - In all achievements, the lesson link gives a 404 error

### ISSUE THREAD

**Issue by Illia2810** [scholokov/qax-portal-2#2221]
Steps of reproducing

1 Open achievement https://www.qax-camp.com.ua/q-hrn-postman/api-hrn/
2 Click "Посилання на урок"

Actual Result
in all achievements, the quest Postman: Сніпети, the lesson link gives a 404 error
Expected Result
clicking the "Посилання на урок" button should take you to a specific lesson

Additional information
https://qaxm.atlassian.net/wiki/spaces/PM/pages/86048775/-+HRN

Environment:
System: Windows 10 Pro
Browser: FireFox

Attachment:

![зображення](https://github.com/user-attachments/assets/3bc4f4ae-c417-4ef1-b09c-d6fbdfe04716)

**Comment by Illia2810** [comment]
#2220

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
