### ISSUE TITLE
Achievements - Postman: Сніпети - In all achievements "Звітність - HRN" the conditions for receiving the achievement are not correctly specified

### ISSUE THREAD

**Issue by Illia2810** [scholokov/qax-portal-2#2222]
Steps of reproducing

Open achievement https://www.qax-camp.com.ua/q-hrn-postman/%d0%b7%d0%b2%d1%96%d1%82%d0%bd%d1%96%d1%81%d1%82%d1%8c-hrn/

Actual Result
In all achievements "Звітність - HRN" the conditions for receiving the achievement are not correctly specified
Expected Result
conditions must be specified as required:

- Виконати практичне завдання
- Завдання має пройти перевірку і бути позначене, як правильно виконане
- Всі уроки у курсі позначені як виконані

Additional information
https://qaxm.atlassian.net/wiki/spaces/PM/pages/86048775/-+HRN

Environment:
System: Windows 10 Pro
Browser: FireFox

Attachment:
![зображення](https://github.com/user-attachments/assets/0efea38f-3028-4cec-a2c9-39c47959ff02)
![зображення](https://github.com/user-attachments/assets/3bea7455-48ee-4325-91e2-5d2d85b8ce27)

**Comment by scholokov** [comment]
так цеж єдиний урок. він має бути описаний, саме як урок
<img width="439" alt="image" src="https://github.com/user-attachments/assets/5b4ebb16-24bc-4b2e-babb-b5a3de88f336">

**Comment by Illia2810** [comment]
не є помилкою. не розібрався у вимогах
