### ISSUE TITLE
Interview - The "Тестова співбесіда 2023.11.20" video and CV with date 2023.11.20 is displayed in the "Інтерв’ю – 04.12.2023

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#2226]
Steps to Reproduce:
1. Open page https://www.qax-camp.com.ua/courses/interview/lessons/test-interview/
2. Pay attention to the video of the "Інтерв’ю – 04.12.2023" and CV  in the "Тестова співбесіда"

Actual Result:
The "Тестова співбесіда 2023.11.20" video and CV with date 2023.11.20 are displayed in the "Інтерв’ю – 04.12.2023"
Expected Result:
The "Тестова співбесіда 04.12.2023" video and CV with date 04.12.2023 are displayed in the "Інтерв’ю – 04.12.2023"

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/user-attachments/assets/bdb82283-4aff-4032-9cc6-423e13fbb39f)

**Comment by ODrobik** [comment]
#1773

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
Verify
