### ISSUE TITLE
Checkout - After deleting a product from the "Сheckout" page, the "Main" page should open

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2227]
After deleting a product from the "checkout" page, the main page should open.

Environment:
Checkout - https://www.qax-camp.com.ua/checkout/
Home - https://www.qax-camp.com.ua/

![Checkout_Home page](https://github.com/user-attachments/assets/1950550b-c0d9-436f-9be3-1e20f2fc5bf4)

**Comment by poroskundenys** [comment]
Готово
