### ISSUE TITLE
Footer - Attach footer at bottom for pages with little information

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2228]
Attach a footer at the bottom for **ALL** pages with little information.

Environment: https://www.qax-camp.com.ua/courses/basic-qa-test/quizzes/test-basic-qa/

Example: 

![Futer](https://github.com/user-attachments/assets/9429f7cd-4691-454b-8b28-2683292f52c1)

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
passed
