### ISSUE TITLE
Test/ The distance between the body and the footer is 70px in the Test

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2229]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q6-basic/lessons/who-is-qa/quizzes/q5-01-who-is-qa/  - Test in the Lesson
2. Pay attention to the distance between the body and the footer.

**Actual result:**
The distance between the body and the footer is 70px in the Test.

**Expected result:**
The distance between the body and the footer is more than 100px in the Test

**Environment:**
Windows 10
Google Chrome v 127.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/user-attachments/assets/1a86c2a3-ff8f-4876-a991-294a9d2a1683)

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
