### ISSUE TITLE
Implement "404" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#223]
We need to implement "404" page:
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2452%3A542
Production: https://portal.qax-camp.com.ua/404
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.9.-%22404%22-page
![404](https://user-images.githubusercontent.com/109460500/200175791-06410e99-03e0-441f-85ab-a4d1a402f9f8.png)

**Comment by Nadiyk** [comment]
Verified
