### ISSUE TITLE
Achievements/ The distance between the body and the footer is 0px 

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2230]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/ach-all/
2. Pay attention to the distance between the body and the footer in the Achievements.

**Actual result:**
The distance between the body and the footer is 0px.

**Expected result:**
The distance between the body and the footer is more than 100px.

**Environment:**
Windows 10
Google Chrome v 127.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/user-attachments/assets/16de82ff-7e23-4ae4-acb7-e29de85703d3)

**Comment by scholokov** [comment]
fixed
please retest in all achivments

**Comment by GNatala** [comment]
passed
