### ISSUE TITLE
Checkout - Сhange the color of the frame "Код купона успішно застосовано!" element as in Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2234]
We need to change the color of the frame element as in Figma.

Environment: https://www.qax-camp.com.ua/checkout/

Figma: https://www.figma.com/design/2JlqZybc4fOvZcPT7oiqrg/Portal-design?node-id=9850-228&t=nKLv2cXlncG7rOLr-1

![Код купона](https://github.com/user-attachments/assets/f6fba455-7d87-4c71-a10d-985b51533bca)

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
passed
![image](https://github.com/user-attachments/assets/46a628b2-9f82-4a14-bc5a-105b47f8f504)
