### ISSUE TITLE
Checkout - Remove the "Замовити ще раз" button

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2235]
We need to remove the button "Замовити ще раз".

Environment: https://www.qax-camp.com.ua/checkout/

![Замовити ще раз](https://github.com/user-attachments/assets/abe640d7-2b70-4fa5-b05b-e8758c0010d0)

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
passed
