### ISSUE TITLE
Footer - Footer at bottom for pages with little information have scroll

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2236]
**Steps to reproduce:**

1. Open page where footer at bottom for pages with little information https://www.qax-camp.com.ua/login/ 
2. Pay attention to that we need to scroll to see the footer.

**Actual result:**
Footer at bottom for pages with little information have scroll.

**Expected result:**
The distance between the body and the footer is more than 100px in the Certificate.
Text "2020-2024 © QAX Camp" need to lift up.
Text "2020-2024 © QAX Camp" need to be centered vertically.

**Environment:**
Windows 10
Google Chrome v 127.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/user-attachments/assets/567eb784-d9db-4e1e-809e-940013048bef)
![image](https://github.com/user-attachments/assets/84b124a4-f321-4266-acc3-2914ce07499e)

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
