### ISSUE TITLE
Check page with API tests

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#224]
We need to check page with API test.
Here is page: https://portal.qax-camp.com.ua/courses/api-testing/
Design Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=931%3A91

**Comment by DmitriiNasonov** [comment]
API Testing Course - First Lesson Theory Test - The question has two potentially correct answers, there is no answer to the question in the theory of the lesson #249

**Comment by DmitriiNasonov** [comment]
Figma design - Test page - Panel for selecting any question in the test is missing #298

**Comment by DmitriiNasonov** [comment]
Testing completed
