### ISSUE TITLE
Lesson for "Проведення Demo" - The style cards are displayed in an accordion lesson is different from the style of displaying cards on "Курси в записі" page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#2241]
Steps to reproduce:
1. Open page https://www.qax-camp.com.ua/courses/mc-testing/lessons/mc-demo/
2. Scroll down to the second  "Більш детальніше про SCRUM" accordion
3. Open the  "Більш детальніше про SCRUM" accordion
4. Pay attention to the style of titles "Процеси" and "Керування розробкою ПЗ" of cards 
5. Pay attention to the style of button "Продовжити" of card in the "Більш детальніше про SCRUM" accordion

Actual Result:
The style cards are displayed in an accordion lesson is different from the style of displaying cards on "Курси в записі" page

Expected Result:
The card display style in the accordion lesson is the same as the card display style on "Курси в записі" page

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/user-attachments/assets/d754f18a-9540-4f50-8922-d099cd169845)
![image](https://github.com/user-attachments/assets/8dbb74d1-3807-441c-b7df-60a94c7d1df6)

**Comment by ODrobik** [comment]
#1780

**Comment by poroskundenys** [comment]
Готово

**Comment by ODrobik** [comment]
перевірено
