### ISSUE TITLE
Lesson for "Тестування пошуку" - An empty accordion is displayed in the "Завдання" accordion 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#2242]
Steps to reproduce:
1. Open page https://www.qax-camp.com.ua/courses/mc-testing/lessons/mc-travel-testing-search/
2. Scroll down to the "Завдання" accordion
3. Open the "Завдання" accordion
4. Pay attention to the empty accordion

Actual Result:
An empty accordion is displayed in the "Завдання" accordion  

Expected Result:
Content is displayed in the "Завдання" accordion 

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/user-attachments/assets/29affb8e-5829-4ea2-aa2b-0ebfd98364d0)

**Comment by ODrobik** [comment]
#1872

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
