### ISSUE TITLE
Courses - Check course for "Вступ у тестування" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2243]
You have to complete the lessons and track the sequence of rewards.
Recommends conducting lessons in the sequence shown in the picture.

Environment: https://www.qax-camp.com.ua/courses/c-qa-entry/

![Вступ у тестування](https://github.com/user-attachments/assets/11f582ad-d87b-4c6f-825c-5a67578be3aa)

**Comment by VasylynaF** [comment]
<html>
<body>
<summary style="box-sizing: border-box; display: list-item; cursor: pointer;">

ID Дефекту | Назва
-- | --
#2247 |  Courses - "Вступ у тестування" - Description of the book in Russian
#2248 |  Courses - "Вступ у тестування" - Location of the "Позначити як виконане" button is not the same as in previous tasks
#2249 | Courses - "Вступ у тестування" - Achievements are not displayed on the achievements page
#2250 | Achievements - One achievement is marked but counted as two
#2251 | Achievements - The number of achievements is not displayed
#2252 | Courses - "Вступ у тестування" - Description of the book ''Роман Савин – Тестирование dot com'' in Russian
#2253 | Achievements - Two achievements are duplicated - Тестувальник. Хто це? and Види, методи та рівні тестування
#2259 | Achievements - Not indicated that you need to authorize
#2260 | Test - Teстувальник Хто це? - Correct and incorrect answers are marked in red


</markdown-accessiblity-table></slot>
</body>
</html> Таблиця / Звіт:

**Comment by VasylynaF** [comment]
![image](https://github.com/user-attachments/assets/60e27ff8-5088-4a60-bb51-23ae7377f413)
Тут назву треба чи це Snake-case?

**Comment by VasylynaF** [comment]
У розділі ''Тестувальник. Хто це? – Максим Плакса'' є два практично однакові відео (різниця у даті та тривалості), так і має бути чи це баг? 
![image](https://github.com/user-attachments/assets/589d8798-d320-4ba2-968a-682e895ad039)
![image](https://github.com/user-attachments/assets/6ce2c701-c38d-4b10-9e70-86174ab97e8b)

**Comment by VasylynaF** [comment]
Картинка на порталі не така як у фігмі, це навмисний відступ від дизайну чи баг?
![image](https://github.com/user-attachments/assets/c0e8a233-528b-4925-b667-16cb203cef78)
![image](https://github.com/user-attachments/assets/1a4fe3e4-9a89-4f8b-ad48-863727aa89f6)

**Comment by VasylynaF** [comment]
Якщо позначити всі 5 завдань як виконані і отримати досягнення, потім завдання позначити як не виконані, то досягнення залишаються.

**Comment by VasylynaF** [comment]
У мобільній версії незареєстрований користувач, може переглядати матеріали курсу, завантажувати книги, не може лише скласти тест.

**Comment by VasylynaF** [comment]
Якщо я авторизувалась, система не дозволяє вийти - це веб.

**Comment by VasylynaF** [comment]
#2247

**Comment by VasylynaF** [comment]
#2248

**Comment by VasylynaF** [comment]
#2249

**Comment by VasylynaF** [comment]
#2250

**Comment by VasylynaF** [comment]
#2251

**Comment by VasylynaF** [comment]
#2253

**Comment by VasylynaF** [comment]
#2259

**Comment by VasylynaF** [comment]
#2260
