### ISSUE TITLE
Event - Popup - Implement two types of popup messages according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2244]
You should implement two types of popups.

Environment: https://www.qax-camp.com.ua/events/qax-outsource-2-0-24-09/?occurrence=2024-09-12&time=1726162200

Event that has multiple encounters:

![multiple encounters](https://github.com/user-attachments/assets/42517256-5acd-4673-8280-772e615c2366)

Figma: https://www.figma.com/design/2JlqZybc4fOvZcPT7oiqrg/Portal-design?node-id=1444-3219&t=tWWE70xhQXnwkxxB-1

Event that does **not** have multiple encounters:

![not have multiple](https://github.com/user-attachments/assets/e20f9899-c84d-4630-b101-01a88a498c83)

Figma: https://www.figma.com/design/2JlqZybc4fOvZcPT7oiqrg/Portal-design?node-id=1444-3519&t=tWWE70xhQXnwkxxB-1

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
verified
