### ISSUE TITLE
Courses - "Вступ у тестування" - Description of the book ''Книга: Святослав Куликов – Тестирование Программного Обеспечения'' in Russian

### ISSUE THREAD

**Issue by VasylynaF** [scholokov/qax-portal-2#2247]
Steps to reproduce:

1. Open the page: https://www.qax-camp.com.ua/
2. Сlick on ''Курси в записі''
3. Сlick on ''Основи тестування''
4. Сlick on ''Вступ у тестування''
5. Scroll down to the last task ''Книга: Святослав Куликов – Тестирование Программного Обеспечения''

Actual result:
Description of the book in Russian
![image](https://github.com/user-attachments/assets/ce8f36f2-f423-4eea-b73e-b7db7b9a4904)

Expected result:
Description of the book should be in Ukrainian

Environment:
Windows 11 Pro  (x64)
Google Chrome 128.0.6613.120 (Офіційне складання) (64-розрядна версія)

**Comment by VasylynaF** [comment]
Тут ще можна вказати, що книга мовою оригіналу, тому російською)

**Comment by scholokov** [comment]
fixed

**Comment by VasylynaF** [comment]
#2243
