### ISSUE TITLE
Courses - "Вступ у тестування" - Achievements are not displayed on the achievements page

### ISSUE THREAD

**Issue by VasylynaF** [scholokov/qax-portal-2#2249]
Steps to reproduce:
1. Open the page: https://www.qax-camp.com.ua/courses/c-qa-entry/lessons/sviatoalav-kulikov-testing-prog/
2. Сlick on button ''Позначити як виконане''
3. Receive notifications about achievements by email and open it
![image](https://github.com/user-attachments/assets/ce66288d-044d-405f-8d12-e6cd1eedfda4)
5. Click on ''На сторінку твоїх досягнень'' 
6. Open page: https://www.qax-camp.com.ua/achiev/

Actual result:
No achievements are displayed on the achievements page
![image](https://github.com/user-attachments/assets/c2ba44ec-303a-45f6-a0b8-f4641323ece6)

Expected result:
Achievements should be displayed on the achievements page

Environment:
Operating System: Windows 11 Pro (x64) (2560 x 1600)
Browser : Google Chrome 128.0.6613.119 (Офіційне складання) (64-розрядна версія)

**Comment by scholokov** [comment]
не вистачає кроків :)))
на якій саме сторінці "досягнень"
(No achievements are displayed on the achievements page)

**Comment by VasylynaF** [comment]
це сторінка яка відкривається, якщо клікнути на кнопку ''На сторінку твоїх досягнень'' що є у повідомленні надісланому на пошту
![image](https://github.com/user-attachments/assets/f79b1221-aab7-4944-9209-7549f171d838)

**Comment by scholokov** [comment]
я маю на увазі що гарно коли ці посилання всталяються. бо цеж набагато простіше потім відтворювати баг :)

**Comment by VasylynaF** [comment]
ок)

**Comment by scholokov** [comment]
просто тут проблема в іншому - тут посилання не на ту сторінку, що потрібна

**Comment by scholokov** [comment]
малоб бути сюди
https://www.qax-camp.com.ua/ach-all/

**Comment by VasylynaF** [comment]
#2243
