### ISSUE TITLE
Course: Выпадающий список - Figma - Name of button to expand drop-down list is "Collapse"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#225]
Steps of Reproduce:
1. Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A1036
2. Pay attention to name of button to expand drop-down list on the lesson with name "Заняття 4. Дефект"

Actual Result:
Name of button to expand drop-down list is "Collapse"

Expected Result:
Name of button to expand drop-down list is "Expand"

Environments:
Windows 10, Chrome 106.0.5249.119 (64 bit)
Android 8.1.0, Chrome 106.0.5249.126
![Portal design – Figma - Google Chrome 20 10 2022 21_07_52](https://user-images.githubusercontent.com/95171672/197255687-41e372ed-6c9f-4421-8216-6d7feb493419.png)
![photo_2022-10-21_20-16-55](https://user-images.githubusercontent.com/95171672/197255691-3226d186-2b21-43dd-82b3-0554b1ae2184.jpg)

**Comment by scholokov** [comment]
fixed
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A1035&t=zxWBau6Mp0OgR8Ay-0

**Comment by DmitriiNasonov** [comment]
bug-report isn't actual
