### ISSUE TITLE
Achievements - The number of achievements is not displayed

### ISSUE THREAD

**Issue by VasylynaF** [scholokov/qax-portal-2#2251]
Pre-condition:
1. Open the main page https://www.qax-camp.com.ua/ and log in
2. Open the page: https://www.qax-camp.com.ua/qa-quest/
3. Complete the task of the quest and mark it as completed
4. Receive notifications about achievements by email

Steps to reproduce:
1. To be on page: https://www.qax-camp.com.ua/ach-all/

Actual result:
The number of achievements is not displayed
![image](https://github.com/user-attachments/assets/42069859-ca02-4fcd-b42b-5478933b54cb)
![image](https://github.com/user-attachments/assets/0abacb4e-d36e-4fac-a3e4-2839067e9d1e)
![image](https://github.com/user-attachments/assets/ea8afee4-800d-4ece-88e0-cd13408f7d41)

Expected result:
The number of achievements should be displayed

Environment:
Operating System: Windows 11 Pro (x64) (2560 x 1600)
Browser : Google Chrome 128.0.6613.119 (Офіційне складання) (64-розрядна версія)

**Comment by scholokov** [comment]
кількість - відображається коректно лише для ачівок, отриманих після імплементації. тобто досягнення отримані раніше - не нараховуються.
треба їх отримати заново

**Comment by VasylynaF** [comment]
відображаються, але не рахуються - цікаво)

**Comment by VasylynaF** [comment]
це не баг і закрити?

**Comment by scholokov** [comment]
тому що по факту це різний підрахунок. тобто суто технічно це два різних підрахунки.
але ж сказане мною, не каже про те, що все працює правильно :)))
тобто для того щоб "впевнитись" у правильному підрахунку, потрібні інші тести :))

**Comment by VasylynaF** [comment]
#2243
