### ISSUE TITLE
Courses - "Вступ у тестування" - Description of the book ''Роман Савин – Тестирование dot com'' in Russian

### ISSUE THREAD

**Issue by VasylynaF** [scholokov/qax-portal-2#2252]
Steps to reproduce:
1. Open the main page https://www.qax-camp.com.ua/ and log in
2. Open the page: https://www.qax-camp.com.ua/courses/c-qa-entry/lessons/roman-savin-testing-dot-com/

Actual result:
Description of the book ''Роман Савин – Тестирование dot com '' in Russian
![image](https://github.com/user-attachments/assets/abed1f7e-c25d-441f-b8b2-687425454c12)

Expected result:
Description of the book ''Роман Савин – Тестирование dot com '' should be in Ukrainian

Environment:
Windows 11 Pro (x64)
Google Chrome 128.0.6613.120 (Офіційне складання) (64-розрядна версія)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/user-attachments/assets/ca2fe1e9-da9b-48c5-a782-d16b54a2c215)

**Comment by VasylynaF** [comment]
#2243
