### ISSUE TITLE
Achievements - Two achievements are duplicated - Тестувальник. Хто це? and Види, методи та рівні тестування

### ISSUE THREAD

**Issue by VasylynaF** [scholokov/qax-portal-2#2253]
Steps to reproduce:
1. Open the main page https://www.qax-camp.com.ua/ and log in
2. Click on icon Achievements - Загальні

Actual result:
Two achievements are duplicated - ``Тестувальник. Хто це? ``and `` Види, методи та рівні тестування``
![image](https://github.com/user-attachments/assets/44ffb54d-f866-437b-862c-b315a063fffc)

Expected result:
Achievements  shouldn't be duplicated

Environment:
Operating System: Windows 11 Pro (x64) (2560 x 1600)
Browser : Google Chrome 128.0.6613.119 (Офіційне складання) (64-розрядна версія)

**Comment by scholokov** [comment]
але ж  вони мають різний колір
тобто одна пара - теорія, а друга пара - тести. відповідно теорія - білі, а тести трохи синуваті

**Comment by VasylynaF** [comment]
тоді це не баг і close  це isssue
було б добре якби про цю відмінність було якось вказано)

**Comment by scholokov** [comment]
так. це не баг 
можна подумати яким чином. якщо кольора не виразливі, то можна подумати про зміну кольору. або на рівні тултипів щось придумати

**Comment by VasylynaF** [comment]
тоді я закриваю як Close as not planned 
![image](https://github.com/user-attachments/assets/b259fbca-a25e-4899-a596-ef3fe9ee097e)

тут кольори зрозуміло, що вони різні, але не одразу зрозуміло було мені як користувачу чому вони різні?

**Comment by scholokov** [comment]
на "поміркувати" завів окрему задачу

**Comment by VasylynaF** [comment]
#2243
