### ISSUE TITLE
Events/ The space is displayed before the year on the event date

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#2258]
Steps to Reproduce:
1. Open page https://www.qax-camp.com.ua/events/qax-practice-travel/?occurrence=2024-09-18
2. Scroll down to the date
3. Pay attention to the space before the year on the date

Actual Result:
The space is displayed before the year on the event date

Expected Result:
The space is not displayed before the year on the event date

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/user-attachments/assets/e2f2fcc8-6103-4269-82fc-3f4be52d3d01)

**Comment by poroskundenys** [comment]
Готово

**Comment by ODrobik** [comment]
перевірено
