### ISSUE TITLE
Achievements - Not all achievements are displayed after completing the quest

### ISSUE THREAD

**Issue by VasylynaF** [scholokov/qax-portal-2#2261]
Pre-condition:
1. Open the main page https://www.qax-camp.com.ua/ and log in
2. Open the page: https://www.qax-camp.com.ua/qa-quest/
3. Complete the quest 
4. Receive notification about achievement by email

Steps to reproduce:
1. Open the page: https://www.qax-camp.com.ua/qa-quest/
2. Click on ''Тестування двомовного web-додатку''
3. Scroll down to achievements

Actual result: 
Not all achievements are displayed after completing the quest
![image](https://github.com/user-attachments/assets/4df849e5-3063-4ba6-8dbe-051961cd0614)

Expected result:
All achievements should be displayed after completing the quest

Environment:
Operating System: Windows 11 Pro (x64) (2560 x 1600)
Browser : Google Chrome 128.0.6613.119 (Офіційне складання) (64-розрядна версія)

**Comment by scholokov** [comment]
пагано, коли по скріну не можна встановити що за розділ.
тобто гарно коли адресна строка попадає у скрін.

тобто у цьом прикладі скрін напевно з квесту, а посилання додано на загальні досягнення

виникають питання

тому краще скріна переробити

**Comment by ButKoff** [comment]
#2243

**Comment by scholokov** [comment]
please retest

**Comment by VasylynaF** [comment]
![image](https://github.com/user-attachments/assets/4c59a612-2fc1-4f65-b038-1cb719c48d6c)

**Comment by scholokov** [comment]
ви повторили всі кроки?

**Comment by VasylynaF** [comment]
так

**Comment by scholokov** [comment]
а на якому акаунті ви робили?
тобто це потрібно завести новий акаунт, відправиви наприклад 1 у результаті тестів
і тоді подивитися
інакше не зрозуміло як ви "повторили" тест :)

**Comment by VasylynaF** [comment]
Я перевірила на своєму акаунті і досягнення нема. Щоб зробити регресію,
треба відмітити проходження квесту на новому акаунті знову, правильно?

ср, 2 жовт. 2024 р. о 15:15 Denis Scholokov ***@***.***> пише:

**Comment by scholokov** [comment]
"відмінити" не можна
потрібно створити новий акаунт і перевірити на ньому

**Comment by VasylynaF** [comment]
Якщо тестувати на новому акаунті без оплати квест не пройти)

ср, 2 жовт. 2024 р. о 15:22 Denis Scholokov ***@***.***> пише:

**Comment by scholokov** [comment]
киньте мені у час ваш овий акаунт і я на нього дам доступ

**Comment by VasylynaF** [comment]
fridrikh.d12@gmail.com
