### ISSUE TITLE
Calendar / The names of events in the calendar are underlined

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2262]
**Steps to reproduce:**

1. Open  https://www.qax-camp.com.ua/calendars/
2. Pay attention to the names of events in the calendar.

**Actual result:**
The names of events in the calendar are underlined.

**Expected result:**
The names of events in the calendar are not underlined.

**Environment:**
Windows 10,
Google Chrome v 129.0.6668.59 (x64)

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6112-976&mode=design&t=Ef82tSUGZqS6zutk-0

**Attachment:**
![image](https://github.com/user-attachments/assets/b2cc0fd4-5a61-4b72-8484-2950df0da309)
![image](https://github.com/user-attachments/assets/598e340b-3110-432d-8f48-aa10110605d6)

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
passed
