### ISSUE TITLE
Event/ The name of the button "Зареєстуватись" is underlined

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2263]
**Steps to reproduce:**

1. Open  https://www.qax-camp.com.ua/calendars/
2. Click on the Event
3. Pay attention to the name of the button "Зареєстуватись".

**Actual result:**
 The name of the button "Зареєстуватись" is underlined.

**Expected result:**
 The name of the button "Зареєстуватись" is not underlined.

**Environment:**
Windows 10,
Google Chrome v 129.0.6668.59 (x64)

**Additional information:**
https://www.figma.com/design/UyTNSS6KCOdphdTev1HrLF/Portal-design-(Old-Version)?node-id=6076-949&node-type=canvas&t=KHeSSeuzGM7WBmtw-0

**Attachment:**
![image](https://github.com/user-attachments/assets/9057a07d-0165-405d-b597-4ef722a7ccf8)

**Comment by poroskundenys** [comment]
Готово

**Comment by GNatala** [comment]
passed
