### ISSUE TITLE
Quests/  The "Назад" button is displayed after moving to the next challenge if the previous challenge is not completed

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#2266]
Steps to Reproduce:
1. Open page https://www.qax-camp.com.ua/courses/sandbox-req/lessons/sandbox-req-test-doc/
2. Pay attention to the "Back" button in the Quests

Actual Result:
 In the Quests the "Back" button is written in English after moving to the next challenge if the previous challenge is not completed

Expected Result:
In the Quests the "Назад" button is written in Ukraine after moving to the next challenge if the previous challenge is not completed

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/user-attachments/assets/3a41368e-3687-42b7-9c74-bf9279f6c3a1)

**Comment by ODrobik** [comment]
#2208

**Comment by poroskundenys** [comment]
Готово

**Comment by ODrobik** [comment]
Перевірено
![image](https://github.com/user-attachments/assets/fa70b4f2-63a7-4cbe-83ca-66deafc02ef2)
