### ISSUE TITLE
Quest "Оцінка рівня якості веб додатку”" - "HTML & CSS Валідатори – OU1" achievements is highlighted in the "Інструменти" section after completing the “Тестування за допомогою HTML & CSS валідаторів” task

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#2268]
Steps to Reproduce:
1. Open page https://www.qax-camp.com.ua/courses/qax-outsource-1-0/
2. Scroll down to the "Досягнення та знання, які отримаєш:" block
3. Pay attention to the "HTML & CSS Валідатори – OU1" achievements no backlight in the "Інструменти" section

Actual Result:
"HTML & CSS Валідатори – OU1" achievement is not highlighted in the "Інструменти" section after completing the “Тестування за допомогою HTML & CSS валідаторів” task

Expected Result:
"HTML & CSS Валідатори – OU1" achievement is highlighted in the "Інструменти" section after completing the “Тестування за допомогою HTML & CSS валідаторів” task

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/user-attachments/assets/b64f10a6-c195-4ee9-ba74-1312b9662c2c)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified 
![image](https://github.com/user-attachments/assets/7761b4de-1aeb-4bc5-9c45-43982e3743d7)
