### ISSUE TITLE
Естімація та Ризики - The icon is not included in the progress

### ISSUE THREAD

**Issue by Illia2810** [scholokov/qax-portal-2#2269]
Steps to reproduce:

1. Open https://www.qax-camp.com.ua/achiev/

Actual result:
The icon is not included in the progress
Expected result:
In progress, all award icons should be impressed, and this one as well 16554

System: Windows 10 Pro
Browser: FireFox

Attachment:
![image (9)](https://github.com/user-attachments/assets/f50e018d-3445-4607-937d-07c2c4b9b891)

**Comment by scholokov** [comment]
fixed
