### ISSUE TITLE
Lesson "Ризики" - The lesson logo in the video preview is different from the one in the lesson preview

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#2272]
Steps to Reproduce:
1. Open page https://www.qax-camp.com.ua/courses/processes/lessons/risk/
2. Pay attention to the logo of the "Ризики" lesson in the video

Actual Result:
The lesson logo in the video preview is different from the one in the lesson preview

Expected Result:
The lesson logo in the video preview is the same as the lesson logo in the lesson preview

Requirements:
https://www.canva.com/design/DAGC95bo6Ps/6Udne8Hp-swvLAfwD8Glpg/edit

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/user-attachments/assets/291393c5-c1c2-41cc-984c-3a653d5f19d7)

**Comment by ODrobik** [comment]
#1782

**Comment by scholokov** [comment]
виправлено
а також виправлено ризики, а також естімація

**Comment by ODrobik** [comment]
перевірено
