### ISSUE TITLE
Lesson "Створюємо звіт по проведеному тестуванню" - The “Дивитись більше” button is not displayed in its lower part when you hover over it in the "Теорія" accordion

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#2273]
Steps to reproduce:
1. Open page https://www.qax-camp.com.ua/courses/mc-testing/lessons/mc-out-1-0-reporting/
2. Scroll down to the second "Теорія" accordion
3. Open the "Теорія" accordion
4. Pay attention to the incomplete drawing of the  "Дивитись більше" button when hovering after "QA Звітність" Preview

Actual Result:
The “Дивитись більше” button is not displayed in its lower part when you hover over it 

Expected Result:
The “Дивитись більше” button is displayed in its lower part when you hover over it 

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/user-attachments/assets/7158a405-b1ab-4a7c-b448-b878c7931c71)

**Comment by poroskundenys** [comment]
Готово

**Comment by ODrobik** [comment]
Перевірено ховер кнопки “Дивитись більше” в акордеонах і в інших уроках курсу "Майстер-класи"
