### ISSUE TITLE
Quest - ''Mock Server в Postman'' page - missing letter "в''

### ISSUE THREAD

**Issue by VasylynaF** [scholokov/qax-portal-2#2275]
**Steps to reproduce:**
1. To be on page https://www.qax-camp.com.ua/courses/q-hrm/
2. Click on ''Опис, умови, графік, програма лояльності''
3. Check the text

Actual result:
Missing letter "в'' in the text
![image](https://github.com/user-attachments/assets/27412887-773f-458e-a637-850978449262)

Expected result:
Shouldn't be missing letter "в'' in the text

Environment:
Operating System: Windows 11 Pro (x64) (2560 x 1600)
Browser : Google Chrome 128.0.6613.119 (64-розрядна версія)

**Comment by VasylynaF** [comment]
#2274

**Comment by scholokov** [comment]
fixed
