### ISSUE TITLE
Quest - ''Mock Server в Postman'' page - The price is not the same

### ISSUE THREAD

**Issue by VasylynaF** [scholokov/qax-portal-2#2276]
**Steps to reproduce:**

1. To be on page https://www.qax-camp.com.ua/courses/q-hrm/
2. Click on ''Опис, умови, графік, програма лояльності''
3. Scroll down and сheck the text 

Actual result:
The price is not the same
![image](https://github.com/user-attachments/assets/9b406d4b-9dd8-4a02-8d2b-43bc4128ddc5)
![image](https://github.com/user-attachments/assets/ae1fb1ed-8b74-4dc3-8276-b2cd6037279e)

Expected result:
The price should be the same

Environment:
Operating System: Windows 11 Pro (x64) (2560 x 1600)
Browser : Google Chrome 128.0.6613.119 (64-розрядна версія)

**Comment by VasylynaF** [comment]
#2274

**Comment by DmytroMarkulych** [comment]
@VasylynaF виглядає все вірно, що купон діє кілька днів - а далі повна вартість

**Comment by scholokov** [comment]
@DmytroMarkulych 
там просто різниця у "повній вартості" :))))

**Comment by scholokov** [comment]
видалено весь акордеон
він відносився до "онлайн-квесту", який вже пройшов
