### ISSUE TITLE
Achievements/The distance between the body and the footer is 0px in the "Квести – За напрямками"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2277]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/ach-quest-all-by-topics/
2. Pay attention to the distance between the body and the footer.

**Actual result:**
The distance between the body and the footer is 0px in the "Квести – За напрямками".

**Expected result:**
The distance between the body and the footer is more than 100px in the "Квести – За напрямками".

**Environment:**
Windows 10
Google Chrome v 125.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/user-attachments/assets/f1070177-4a1f-4776-abe5-1fd3c41b844a)

**Comment by GNatala** [comment]
#2230

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
