### ISSUE TITLE
Achievements/The distance between the body and the footer is 0px in the "Досягнення – Проєкти – За напрямками"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2279]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/ach-project-all-by-topics/
2. Pay attention to the distance between the body and the footer.

**Actual result:**
The distance between the body and the footer is 0px in the "Досягнення – Проєкти – За напрямками" .

**Expected result:**
The distance between the body and the footer is more than 100px in the "Досягнення – Проєкти – За напрямками" .

**Environment:**
Windows 10
Google Chrome v 128.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/user-attachments/assets/5bbe0945-6ca0-4475-a0b6-00ecd5ee177b)

**Comment by GNatala** [comment]
#2230

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
