### ISSUE TITLE
No icon letter in the header on the page "Наші тренери" in the screen version 768px / 360px

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#228]
**STR**
1. Open https://portal.qax-camp.com.ua/trainers/ in the tablet / mobile version
2. Open https://www.figma.com/file/JwKf4NLnNlzrSCaBlbhKu4/QAX-Camp-(Copy)?node-id=4542%3A1268
3. Pay attention to the header icons

**ACTUAL RESULT**
The icon letter in the header on the page "Наші тренери" is NOT shown

**EXPECTED RESULT**
The icon letter in the header on the page "Наші тренери" is shown

![CjqOIdp4vO](https://user-images.githubusercontent.com/109384052/197535594-a3e61a64-c3d0-4980-976a-561acd94bbc5.png)
![RauACWQ00s](https://user-images.githubusercontent.com/109384052/197535798-9da782c9-ec91-4f6e-8638-abd0e121ce54.png)
![zScD4oxS8A](https://user-images.githubusercontent.com/109384052/197535820-6748798f-937b-4953-abee-bbf8fc79a383.png)

**Comment by scholokov** [comment]
потрібно онивити скріни, так як добавилася іконка "логін"

**Comment by BatalovaOlha** [comment]
> потрібно онивити скріни, так як добавилася іконка "логін"

На мобільній версії логіну немає. При цьому з телефону вже є значок "лист". Я тоді закриваю задачу?

**Comment by BatalovaOlha** [comment]
no actual - header corresponds requirement
