### ISSUE TITLE
Achievements/The distance between the body and the footer is 0px in the "Досягнення – Теорія – За напрямками"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2280]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/%d0%b4%d0%be%d1%81%d1%8f%d0%b3%d0%bd%d0%b5%d0%bd%d0%bd%d1%8f-%d1%82%d0%b5%d0%be%d1%80%d1%96%d1%8f-%d0%b7%d0%b0-%d0%bd%d0%b0%d0%bf%d1%80%d1%8f%d0%bc%d0%ba%d0%b0%d0%bc%d0%b8/
2. Pay attention to the distance between the body and the footer.

**Actual result:**
The distance between the body and the footer is 0px in the "Досягнення – Теорія – За напрямками" .

**Expected result:**
The distance between the body and the footer is more than 100px in the "Досягнення – Теорія – За напрямками" .

**Environment:**
Windows 10
Google Chrome v 128.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/user-attachments/assets/489ae7a2-c700-4337-895b-a2822506896a)

**Comment by GNatala** [comment]
#2230

**Comment by scholokov** [comment]
змінено посилання
https://www.qax-camp.com.ua/ach-theory/

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
passed
