### ISSUE TITLE
Quest - ''Mock Server в Postman'' page - Spelling errors

### ISSUE THREAD

**Issue by VasylynaF** [scholokov/qax-portal-2#2281]
**Steps to reproduce:**

1. To be on page https://www.qax-camp.com.ua/courses/q-hrm/
3. Scroll down and сheck the text

Actual result:
There are spelling errors in the text
![image](https://github.com/user-attachments/assets/2bc064f1-c6d3-461c-9006-d4d4526765fb)

Expected result:
![image](https://github.com/user-attachments/assets/9f35a5b7-1fba-4fc4-ac84-c11738f65711)

Shouldn't be spelling errors in the text
Environment:
Operating System: Windows 11 Pro (x64) (2560 x 1600)
Browser : Google Chrome 128.0.6613.119 (64-розрядна версія)

**Comment by VasylynaF** [comment]
#2274

**Comment by scholokov** [comment]
fixed
