### ISSUE TITLE
Quest - ''Mock Server в Postman'' page - Spelling errors

### ISSUE THREAD

**Issue by VasylynaF** [scholokov/qax-portal-2#2282]
**Steps to reproduce:**

1. To be on page https://www.qax-camp.com.ua/courses/q-hrm/
2. Click on ''Тестування та звітність'' 
3. Scroll down and сheck the text

Actual result:
There are spelling errors in the text. Foreign words are written differently
![image](https://github.com/user-attachments/assets/e7b850c7-1c36-4c43-b0a0-c97a32be8e6e)

Expected result:
Shouldn't be spelling errors in the text. Foreign words should be written equally

Environment:
Operating System: Windows 11 Pro (x64) (2560 x 1600)
Browser : Google Chrome 128.0.6613.119 (64-розрядна версія)

**Comment by VasylynaF** [comment]
#2274

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/user-attachments/assets/10141034-4a1f-4b5c-87c6-a8622e3f973b)

**Comment by scholokov** [comment]
fixed
