### ISSUE TITLE
Quest - "веб" word is written in the title in the preview of Quests 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#2285]
Steps to Reproduce:
1. Open page https://www.qax-camp.com.ua/qa-quest/
2. Pay attention to the title in the preview of Quests that consist in the "веб" word 

Actual Result: 
 **"веб"** word is written in the title in the preview of Quests 

Expected Result: 
 **"web"** word is written in the title in the preview of Quests 

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/user-attachments/assets/67ab945e-8e9e-49cf-b541-f67c0a576f0b)

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
