### ISSUE TITLE
Home page - Check the block "Обирай напрям і нумо вчитись" design according to the Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#2289]
We need to check the block "Обирай напрям і нумо вчитись" design according to the Figma.
Please check the functional and design compatibility.

Environment: https://www.qax-camp.com.ua/home-test/
Figma: https://www.figma.com/design/2JlqZybc4fOvZcPT7oiqrg/Portal-design?node-id=10048-108&node-type=canvas&t=LSDypi6y2R6ONkYg-0

![367242072-bd96e05f-c7a8-42b8-aacb-97f4bc244880](https://github.com/user-attachments/assets/4b669ae4-1828-4dae-a966-b7407de8f486)

**Comment by ButKoff** [comment]
#2255

**Comment by GNatala** [comment]
Розмір блоку фактичний 373х409, згідно Figma 341x400

**Comment by ButKoff** [comment]
WAD (Work as designed)
