### ISSUE TITLE
Footer - after clicking the Telegram icon - messenger does not open 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#229]
**STR**
1. Open https://portal.qax-camp.com.ua/trainers/
2. Scroll down to the footer and click on the Telegram icon

**ACTUAL RESULT**
After clicking on the Telegram icon messenger does not open and opens sign into Telegram in the browser 

**EXPECTED RESULT**
After clicking on the Telegram icon messenger is open 

![Our-Team-–-QAX-Camp-Google-Chrome-2022-10-24-16-01-54](https://user-images.githubusercontent.com/109384052/197545623-8bf45e46-06ce-4512-9e54-3e417b9c7b38.gif)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
