### ISSUE TITLE
Home page - block "Чому обирають нас?" - The number of slides does not match the design

### ISSUE THREAD

**Issue by VasylynaF** [scholokov/qax-portal-2#2291]
Steps to reproduce:

1. Open the page: https://www.qax-camp.com.ua/home-test/

Actual result:
The number of slides does not match the design
![image](https://github.com/user-attachments/assets/3f072590-0226-47b7-9760-8e9eb501c56e)

Expected result:
The number of slides should be match the Figma's design
![image](https://github.com/user-attachments/assets/53e116fe-197a-4b24-9a4a-f88c1db2d8bd)

Environment:
Web: Windows 10 (x64)
Google Chrome 127.0.6533.120 (Офіційне складання) (64-розрядна версія)

**Comment by VasylynaF** [comment]
#2290

**Comment by scholokov** [comment]
fixed
