### ISSUE TITLE
Home page - block "Чому обирають нас?" - The size of the icons does not correspond to the design in Figma

### ISSUE THREAD

**Issue by VasylynaF** [scholokov/qax-portal-2#2292]
Steps to reproduce:

1. Open the page: https://www.qax-camp.com.ua/home-test/

Actual result:
The size of the icons does not correspond to the design in Figma
![image](https://github.com/user-attachments/assets/6c3c97c6-50e2-407c-8b1e-699a276c282d)
![image](https://github.com/user-attachments/assets/34a05e9e-c7fc-45d0-b1c9-6ab30d0e3f59)

Expected result:
The size of the icons should correspond to the design in Figma
![image](https://github.com/user-attachments/assets/d7248e7b-d598-4978-a7a5-ec7f5bc95a65)
![image](https://github.com/user-attachments/assets/23586988-e199-4fb1-96ba-63f25b22a332)

Environment:
Web: Windows 10 (x64) 2560 х 1600
Google Chrome 127.0.6533.120 (Офіційне складання) (64-розрядна версія)

**Comment by VasylynaF** [comment]
#2290

**Comment by DmytroMarkulych** [comment]
вкажіть розширення екрану на якому проводилося тестування

**Comment by VasylynaF** [comment]
2560 х 1600

**Comment by ButKoff** [comment]
@VasylynaF WAD (Work as designed)
