### ISSUE TITLE
Home page - "досягнення" word is written in the "Ти лише робиш перші кроки в ІТ?" block of Home page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#2293]
Steps to Reproduce:
1. Open page https://www.qax-camp.com.ua/home-test/
2. Pay attention to the "досягнення" word in the "Ти лише робиш перші кроки в ІТ?" block of Home page

Actual Result:
**"досягнення"** word is written in the "Ти лише робиш перші кроки в ІТ?" block 

Expected Result:
**"досягнеш"** word is written in the "Ти лише робиш перші кроки в ІТ?" block 

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/user-attachments/assets/17e67177-37d4-474e-8ebc-f4b35ae55e2a)

**Comment by ODrobik** [comment]
#2288

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
issue is still 
![image](https://github.com/user-attachments/assets/75b3d662-dad9-45ea-a4f2-56a98aced6e8)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
