### ISSUE TITLE
Home page - The font size of the text is displayed at 21 px in the "Ти лише робиш перші кроки в ІТ?" block

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#2294]
Steps to Reproduce:
1. Open page https://www.qax-camp.com.ua/home-test/
2. Pay attention to the font size of the text in the "Ти лише робиш перші кроки в ІТ?" block on the Home page

Actual Result:
The font size of the text is displayed **at 21 px** in the "Ти лише робиш перші кроки в ІТ?" block

Expected Result:
The font size of the text is displayed **at 18 px** the "Ти лише робиш перші кроки в ІТ?" block

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/user-attachments/assets/1e5f14c3-8e1f-4eba-aaf2-08fcc691e85d)

**Comment by ODrobik** [comment]
#2288

**Comment by poroskundenys** [comment]
Готово

**Comment by ODrobik** [comment]
перевірено
