### ISSUE TITLE
Footer - after clicking the button "Договір оферти" page doesn't open 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#230]
**STR**
1. Open https://portal.qax-camp.com.ua/ and scroll down to the footer 
2. Click the button "Договір оферти"

**ACTUAL RESULT**
After clicking the button "Договір оферти" open page "about:blank#blocked"

**EXPECTED RESULT**
After clicking the button "Договір оферти" open the page with the contract

![QAX-Camp-–-Students-Portal-Google-Chrome-2022-10-24-16-22-29](https://user-images.githubusercontent.com/109384052/197549620-a1bc0c3e-f0ea-4036-bf15-1dd1eb41d302.gif)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
@scholokov  Мені поки що закрити цей баг до розробки сторніки з договором?

**Comment by BatalovaOlha** [comment]
verified
