### ISSUE TITLE
Registration form - sending the form without the line "e-mail" completion

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#231]
**STR**
1. Open https://www.qax-camp.com.ua/#write_to_us 
2. Fill in all lines except “e-mail” and click “відправити“
3. Open https://github.com/scholokov/qax-portal-2/wiki/1.5.-Form and pay attention to the form's line whit e-mail

**ACTUAL RESULT**
Form “Записатися на курс“ successfully sending without the line "e-mail" completion

**EXPECTED RESULT**
Form “Записатися на курс“is NOT sending without the line "e-mail" completion and shows the error "Error message_Criteria" "input value is not corresponding to the comparing example"

![XTiUQJI2bE](https://user-images.githubusercontent.com/109384052/197713285-60b9aaae-6801-4ba4-b5c2-05114f6d5619.png)
![QAX Camp – Students Portal - Google Chrome 2023-02-07 12-23-21](https://user-images.githubusercontent.com/109384052/217232053-f0037590-783f-42e2-91e8-3916d7d3a1d8.gif)
![bbFeFgT4AH](https://user-images.githubusercontent.com/109384052/217232302-5366a34b-f32b-4bbc-bbba-501ef1c71df4.png)

**Comment by scholokov** [comment]
please retest according to the requirements
https://github.com/scholokov/qax-portal-2/wiki/1.5.-Form

**Comment by ABatalov** [comment]
Fixed https://github.com/scholokov/qax-portal-2/wiki/1.5.-Form

**Comment by BatalovaOlha** [comment]
No actUAL
