### ISSUE TITLE
Lesson - Font size of H2 title is 24px in the content

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2319]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/h-test/lessons/h-test/
2. Pay attention to the font size of H2 title in the lesson's content.

**Actual result:**
Font size of H2 title is 24px.

**Expected result:**
Font size of H2 title is 36px.

**Additional information:**
https://github.com/scholokov/qax-portal-2/issues/2296#issuecomment-2516653693

**Environment:**
Windows 10
Google Chrome v 130.0.5359.125 (x64)

**Attachment:**

![image](https://github.com/user-attachments/assets/8877f157-2f5f-47ba-b47d-da2d8c8c0232)

**Comment by GNatala** [comment]
#2296

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
