### ISSUE TITLE
Imlement page "Договір оферти" 

### ISSUE THREAD

**Issue by ABatalov** [scholokov/qax-portal-2#236]
We need to implement new page "Договір оферти" 

Here is content for page: https://github.com/scholokov/qax-portal-2/wiki/%D0%94%D0%BE%D0%B3%D0%BE%D0%B2%D1%96%D1%80-%D0%BE%D1%84%D0%B5%D1%80%D1%82%D0%B8  

User should be able to find this page after click this button in footer: 

![Договір](https://user-images.githubusercontent.com/72439798/198899184-d42b190e-cd49-446e-affc-88da327155ac.PNG)

**Comment by ABatalov** [comment]
@scholokov , plz chech task

**Comment by scholokov** [comment]
done
https://portal.qax-camp.com.ua/offer_agreement/

**Comment by ABatalov** [comment]
Super )
