### ISSUE TITLE
Create design of "Courses QA" page on Portal Figma

### ISSUE THREAD

**Issue by ABatalov** [scholokov/qax-portal-2#239]
We need to create design of "Courses QA" page on Portal Figma.
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=5469-749&t=kXVN6pe2wsSXCVwK-0
Product environment: https://www.qax-camp.com.ua/qa-courses/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.0.1.--Quality-Assurance-Engineer-(QA)
![QA courses](https://user-images.githubusercontent.com/109460500/225536953-07ce63df-6113-432e-8ee0-7fbc69efc17a.png)

**Comment by ABatalov** [comment]
@scholokov , plz check this task

**Comment by AlonaSarapina** [comment]
ready for testing 
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=1412%3A1313&t=Di2Zlq3G3mLlAOqY-1

**Comment by OlhaHutsman** [comment]
@scholokov  це завдання таке ж як #467, відмітити, як veryfied і закрити?

**Comment by scholokov** [comment]
але ж тут про зовсім різні сторінки річ

**Comment by OlhaHutsman** [comment]
@scholokov  Product environment: https://www.qax-camp.com.ua/qa-courses-2/     is not found
![error 404](https://user-images.githubusercontent.com/123729744/227706653-2f155496-9818-4f2a-ae48-62446f7cda45.png)

**Comment by ButKoff** [comment]
@OlhaHutsman Testing environment: https://www.qax-camp.com.ua/qa-courses/

**Comment by Nadiyk** [comment]
Verified
