### ISSUE TITLE
Block "Дякуємо!" does not change size, when the width of the window is reduced

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/qax-portal-2#240]
**Steps to reproduce:**
1. Open the page https://portal.qax-camp.com.ua/
2. Scroll down to the Form
3. Enter the data and click send
4. Reduce window width

**Actual result:** Block "Дякуємо!" does not reduce
**Expected result:** Block "Дякуємо!" is reduced with all content

**Description:** Also the bug is reproduced on tablet and mobile devices whose display width is lower than 800 px

**Environment:** Windows 11, Google Chrome - 106.0.5249.119 , (64 бит), display - 1920x1080px

![chrome_dsqJZvZ9Na](https://user-images.githubusercontent.com/57997443/198960830-9e178d01-962e-4645-9d02-8c5b27d83f95.png)
![chrome_siDwkXrUY5](https://user-images.githubusercontent.com/57997443/198960857-59098abd-7032-49e0-824b-3a875d8433b6.gif)

**Comment by DmytroMarkulych** [comment]
@dmitryylev давайте summary зробимо більш лаконічним, і не таким великим

**Comment by dmitryylev** [comment]
changed

**Comment by dmitryylev** [comment]
verified
