### ISSUE TITLE
No last work experience - trainer "Олеся Ломенко" - page "Наші тренери" 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#241]
**STR**
1. Open https://portal.qax-camp.com.ua/trainers/ and pay attention to the block "Олеся Ломенко"
2. Open https://github.com/scholokov/qax-portal-2/wiki/Our-Trainers#alesya-lomenko-trainer and pay attention to the last work experience.

**EXPECTED RESULT**
Last work experience "2021-зараз - Project Manager в FFW Agency" is NOT shown

**ACTUAL RESULT**
Last work experience "2021-зараз - Project Manager в FFW Agency" is shown

![qHoKaZsGVP](https://user-images.githubusercontent.com/109384052/198988273-8b5519a5-f776-4457-997b-e208aac617a5.png)

 
![s8JXWm1kqF](https://user-images.githubusercontent.com/109384052/198988279-0c7e9582-fbbc-4e78-8258-0c8c315fe565.png)

**Comment by scholokov** [comment]
fixxed

**Comment by BatalovaOlha** [comment]
verified
