### ISSUE TITLE
"Олеся Ломенко Trainer" - block "Досвід викладацької діяльності" - non-compliance Wiki

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#242]
**STR**
1. Open https://portal.qax-camp.com.ua/trainers/ and pay attention to the block "Олеся Ломенко Trainer" / "Досвід викладацької діяльності"
2. Open https://github.com/scholokov/qax-portal-2/wiki/Our-Trainers#alesya-lomenko-trainer

**ACTUAL RESULT**
"Досвід викладацької діяльності" "Олеся Ломенко Trainer" shown as "2021 – зараз – **PM Mentor**, Trainer в QAX Camp"

**EXPECTED RESULT**
"Досвід викладацької діяльності" "Олеся Ломенко Trainer" should show up as "2021 – зараз – Trainer в QAX Camp"

![LtHLkMExsT](https://user-images.githubusercontent.com/109384052/198994287-04dc207d-bef8-44fd-ae21-a49313334f71.png)

![FNg55eGHSn](https://user-images.githubusercontent.com/109384052/198994300-2a4e10fa-f82f-4cb1-a353-2b207eb9a9ea.png)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
