### ISSUE TITLE
Figma design - Test - question description text needs implementation in Figma

### ISSUE THREAD

**Issue by Xalep4ik** [scholokov/qax-portal-2#244]
**STR:**
1. Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=931%3A91
2. Pay attention to question.

**Actual result:**
There is no design for description text.

**Expected result:**
There is design for description text. 

![figma1](https://user-images.githubusercontent.com/92167884/199025572-6fa60df7-9d18-42af-abee-ac49dede2ae2.png)

Exemple from Portal:

![q_description](https://user-images.githubusercontent.com/92167884/199025689-233d7eea-d891-4fac-be09-97d1f8ae29b0.png)

**Comment by scholokov** [comment]
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=931%3A91&t=zxWBau6Mp0OgR8Ay-0

**Comment by KaterinaNimenko35** [comment]
Verified, an issue is not reproduced
