### ISSUE TITLE
Spelling mistake in a test question - block "Тестування API.Postman&Swagger. - page "Клієнт-серверна архітектура".

### ISSUE THREAD

**Issue by YulyaBaday** [scholokov/qax-portal-2#245]
Steps of reprodusing:

1) Open https://portal.qax-camp.com.ua/courses/api-testing/lessons/a1-01/quizzes/a100/
2) Сlick the button to continue Quiz
3) Pass API test

Expected Result:
Test questions Що можна побачити у вкладці Network?

Actual Result:
Test questions Що можно побачити у вкладці Network?
![1](https://user-images.githubusercontent.com/105633624/199055486-0d3e6b2e-abfb-4c8d-acc6-fa4781a6d181.png)

Environments:
Windows 10, Chrome 101.0.4951.67 (64 bit)

**Comment by YulyaBaday** [comment]
#224

**Comment by scholokov** [comment]
fixed
