### ISSUE TITLE
Grammatical error in one of the answers to the question: Що таке request? - block "Тестування API. - page "Клієнт-серверна архітектура".

### ISSUE THREAD

**Issue by YulyaBaday** [scholokov/qax-portal-2#246]
Steps of reprodusing:

1) Open https://portal.qax-camp.com.ua/courses/api-testing/lessons/a1-01/quizzes/a100/
2) Сlick the button to continue Quiz
3) Pass API test

Actual Result:
Answer: Це запит до офіс-менеджеру компанії про надання нової кулькової ручки, бо стара закінчилась.

Expected Result:
Answer: Це запит до офіс-менеджера компанії про надання нової кулькової ручки, бо стара закінчилась.

![2](https://user-images.githubusercontent.com/105633624/199066255-5aced3d2-63fc-4d5b-8695-493783518492.png)

Environments:
Windows 10, Chrome 101.0.4951.67 (64 bit)

**Comment by YulyaBaday** [comment]
#224

**Comment by DmytroMarkulych** [comment]
@YulyaBaday  Актуальний результат має йти відразу після кроків для вітворення, а вже за ним Очікуваний

**Comment by scholokov** [comment]
fixed

**Comment by YulyaBaday** [comment]
verified
![1](https://user-images.githubusercontent.com/105633624/201727561-d12bd858-15f1-40a1-8cbe-69a4d30267d0.png)
