### ISSUE TITLE
Duplicated text on the page about the company 

### ISSUE THREAD

**Issue by RostKleimenov** [scholokov/qax-portal-2#247]
Steps to reproduse:

1. Open page https://portal.qax-camp.com.ua/about-us/ 
2. Observe text "Томас Едісон ..."

Actual result:
The text contains a duplicate element
Expected result:
Duplication of text does not meet the requirements
 
Environment
windows 10
Google Chrome v.106.0.5249.103
Ubuntu 20.04.5 LTS
Google Chrome v 105.0.5195.125 (x64)
![image](https://user-images.githubusercontent.com/113580264/199703264-21006b31-88f6-4599-a3b8-b9068e6c61e7.png)

**Comment by scholokov** [comment]
fixed
https://www.qax-camp.com.ua/about-us/

**Comment by GNatala** [comment]
passed
