### ISSUE TITLE
missing picture in the "contact with qax" block"

### ISSUE THREAD

**Issue by RostKleimenov** [scholokov/qax-portal-2#248]
Steps to reproduse:

1. Open page https://portal.qax-camp.com.ua/about-us/ 
2. Observe unit "Зв’язок з QAX"

Actual result:
There is no picture in the description of the page about us 

Expected result:
According to the terms of the [specification](https://github.com/scholokov/qax-portal-2/wiki/About-us-page), the "Communication with QAX" block contains a picture

Environment
windows 10
Google Chrome v.106.0.5249.103
Ubuntu 20.04.5 LTS
Google Chrome v 105.0.5195.125 (x64)
![image](https://user-images.githubusercontent.com/113580264/199744968-ae80b4f4-067f-496a-9921-58356f1e264e.png)
![image](https://user-images.githubusercontent.com/113580264/199745068-26ea8e3a-2b85-434c-8cef-940cb4720c5b.png)

**Comment by DmytroMarkulych** [comment]
@RostKleimenov Давайте переформулюємо summary таким чином, щоб не було "There is".

**Comment by RostKleimenov** [comment]
@DmytroMarkulych змінив)

**Comment by scholokov** [comment]
please retest

**Comment by SOlkhova** [comment]
Requirements 1.3 "About us page"/Зв'язок з QAX - contradict Figma/About us. Created a bug on the requirements #504

**Comment by Nadiyk** [comment]
pass
