### ISSUE TITLE
API Testing Course - First Lesson Theory Test - The question has two potentially correct answers, there is no answer to the question in the theory of the lesson

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#249]
**Steps of reproducing:**
1. Login to user account with access to this course
2. Open https://portal.qax-camp.com.ua/courses/api-testing/lessons/a1-01/quizzes/a100/
3. Start Quiz
4. Press the "Next" button until you find the question "Created це статус код ..."

**Actual Result:**
The question has two potentially correct answers, there is no answer to the question in the theory of the lesson

**Expected Result:**
The question has one potentially correct answer and/or there is an answer to the question in the lesson theory

**Specification:**
https://portal.qax-camp.com.ua/courses/api-testing/lessons/a1-01/

**Environment:**
Windows 10, Chrome 106.0.5249.119 (64 bit)
Android 8.1.0, Chrome 107.0.5304.91

![Клієнт-серверна архітектура  HTTP  Status Code – QAX Camp - Google Chrome 03 11 2022 14_32_34](https://user-images.githubusercontent.com/95171672/199833674-595bddcb-87a6-4bf5-b5d2-2674beb27ce3.png)
![photo_2022-11-03_23-00-19](https://user-images.githubusercontent.com/95171672/199833680-3dfc6308-0ff0-441d-bc39-6d277ac0f732.jpg)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
verified. bug is not reproducing
