### ISSUE TITLE
New course descriptions and new icons QA, PM, BA and IT Recruiter

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#25]
Надо обновить заголовки, иконки и тексты:
"**Обирай свій напрям та починай рух до цілі разом з QAX**"
**Quality Assurance Engineer (QA)**:
Забезпечення якості продукту. Виявлення, дослідження та опис проблем. Створення тестової документаціі, взаємодія в проєктній команді та ще безліч захоплюючих процесів в даному напрямку чекають на тебе.
**Project Manager (PM)**:
Шлях від реалізації ідеї до успішного завершення проєкту. Створення та контроль ефективного процесу роботи. Постійний контакт з командою розробників та замовником. Відпрацювання найвдалішої стратегії реалізації проєкту.
**Business Analyst (BA)**:
Аналіз та оцінка проблем бізнесу, варіанти їх закриття шляхом впровадження цифрових рішень. Генерація ідей щодо потреб бізнесу. Уточнення ролей і обов’язків ІТ-фахівців у команді, створення вимог до реалізації та розробка ІТ-планів.
**IT Recruiter**:
Заглиблення з нуля у масштабний напрямок підбору фахівців ІТ індустрії. Рекрутмент повного циклу: від вивчення найдієвіших інструментів та платформ для пошуку кандидатів до засвоєння найдієвіших тонкощів проведення інтерв'ю та набуття навичок ефективної комунікації із усіма учасниками процесу рекрутменту.
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A22
![Напрямки](https://user-images.githubusercontent.com/109460500/187207424-a0d6f568-28ce-448b-96ca-d4d5e641bcba.png)

**Comment by ABatalov** [comment]
Ready for testing: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design

**Comment by KaterinaNimenko35** [comment]
verified
