### ISSUE TITLE
Implemenet Home page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#250]
We need to Implemenet Home page
Design on Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A22
Test environment: https://portal.qax-camp.com.ua/
![Home](https://user-images.githubusercontent.com/109460500/200175390-14350a19-9fb4-4129-a742-7a696641f0ec.png)

**Comment by dmitryylev** [comment]
verified
