### ISSUE TITLE
API Testing Course - Second lesson presentation -  Part of page's 12 content written in russian language

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#253]
**Steps of reproducing:**
1. Open https://drive.google.com/file/d/1MzkrXiDAfYsNkfqnJYZoBLW8xxpwUgea/view
2. Scroll to page 12

**Actual Result:**
Part of content written in russian language

**Expected Result:**
All content written in ukrainian language

**Environment:**
Windows 10, 107.0.5304.88 (64 bit)
Android 8.1.0, 107.0.5304.91
![Заняття 2  Api  Swagger pptx pdf - Google Диск - Google Chrome 10 11 2022 13_47_13](https://user-images.githubusercontent.com/95171672/201092434-e5e0f2c3-7a1f-41bb-ab13-2a77a9ed4c9e.png)
![photo_2022-11-10_14-27-23](https://user-images.githubusercontent.com/95171672/201092455-c06a167b-8513-460f-a77d-0a08f475b71a.jpg)

**Comment by scholokov** [comment]
technical limitation
can't be fix
