### ISSUE TITLE
Registration form - field Password, registration is not complete with valid data

### ISSUE THREAD

**Issue by Xalep4ik** [scholokov/qax-portal-2#254]
**STR:**

1.Open https://portal.qax-camp.com.ua/register/
2.Fill all fields with valid data, field password must be 7 characters
3.Click on "Зареєструватися"

**Actual result:**
There is a validation message under field Password : This field must contain at least 8 characters

**Expected result:**
Registration complete with message of success

Environment :
Windows 10 PRO
Google Chrome Версія 107.0.5304.88

Requirements: 
https://github.com/scholokov/qax-portal-2/wiki/Regitration

![pass_bug](https://user-images.githubusercontent.com/92167884/201091352-b9910d6a-9c89-4f0b-b4e2-4f0b8855079a.png)

**Comment by scholokov** [comment]
please retest according to updated requarements

**Comment by Xalep4ik** [comment]
@scholokov в нових вимогах допустима довжина пароля 2 символи, силку в репорті оновив, помилка відтворюється 
![pass_2char](https://user-images.githubusercontent.com/92167884/202502260-3289b857-9f14-407f-ab1e-0c54926cd80b.png)

**Comment by DmytroMarkulych** [comment]
@Xalep4ik краще заведіть новий баг репорт, якщо є зміни в вимогах а цей закрийте

**Comment by Xalep4ik** [comment]
Ок, заведу новий
