### ISSUE TITLE
Registration form - field Username, registration doesn't complete with valid data 

### ISSUE THREAD

**Issue by Xalep4ik** [scholokov/qax-portal-2#255]
**STR:**

1. Open https://portal.qax-camp.com.ua/register/
2. Fill all fields with valid data, Username must be 25 characters
3. Click on "Зареєструватися"  

**Actual result:**
There is a validation message under field Username: This field must contain less than 24 characters

**Expected result:**
Registration complete with message of success

Environment :
Windows 10 PRO
Google Chrome Версія 107.0.5304.88

Requirements:
https://portal.qax-camp.com.ua/auth-1-2/

![Username_bug](https://user-images.githubusercontent.com/92167884/201098837-cf5bc3d5-b15a-471f-8c89-3f65f88e1fef.png)

**Comment by scholokov** [comment]
please retest according to updated requarements

**Comment by Xalep4ik** [comment]
Verified
