### ISSUE TITLE
New button color in courses section

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#26]
Надо выделить кнопку "Позначити як виконане" коралловым цветом #F66F5D и создать hover
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A12775
![Кнопка + ховер](https://user-images.githubusercontent.com/109460500/186874709-bd973d4e-6d93-4431-a70f-3f2878398f33.png)

**Comment by ButKoff** [comment]
ready for testing

**Comment by scholokov** [comment]
у задачі не вистачає:
- в темі не указано ДЕ треба робити зміни. напевно Course?
- не вказано лінку з прикладом, де можна це подивитися

**Comment by KaterinaNimenko35** [comment]
@ButKoff    
1. Кнопка при наведенні курсору змінює колір (hover)?
2. Кнопка завжди має колір #F66F5D, який не змінюється при наведенні курсору?

**Comment by scholokov** [comment]
Hover ефект повинен бути присутнім

**Comment by ButKoff** [comment]
Все, привет!

**Comment by KaterinaNimenko35** [comment]
verified
