### ISSUE TITLE
Registration form - registration complete successful with 26 characters in field Last name    

### ISSUE THREAD

**Issue by Xalep4ik** [scholokov/qax-portal-2#261]
**STR:**

1. Open https://portal.qax-camp.com.ua/register/
2. Fill all fields with valid data, Last name must be 26 characters
3. Click on "Зареєструватися"
4. Pay attention to field Last name

**Actual result:**
Registration complete, success message

**Expected result:**
Validation message with description of error

Requirements: https://portal.qax-camp.com.ua/auth-1-2/

Environment :
Windows 10 PRO
Google Chrome Версія 107.0.5304.88
![last_name_26char](https://user-images.githubusercontent.com/92167884/201352920-96adfad2-6b07-4f74-8eb0-07853bc43f33.png)

**Comment by DmytroMarkulych** [comment]
@Xalep4ik

В Actual Result, Ви мабуть мали на увазі "message"?
В steps for reproduce додайте останнім пунктом рядок який починається "Pay attention to.." і вкажіть на місце проблеми

**Comment by Xalep4ik** [comment]
виправив

**Comment by scholokov** [comment]
please retest according to updated requarements

**Comment by Xalep4ik** [comment]
Verified
