### ISSUE TITLE
Registration form - registration complete successful with 26 characters in field E-mail Address 

### ISSUE THREAD

**Issue by Xalep4ik** [scholokov/qax-portal-2#264]
**STR:**

1. Open https://portal.qax-camp.com.ua/register/
2. Fill all fields with valid data, E-mail Address must be 26 characters
3. Click on "Зареєструватися"
4. Pay attention to field E-mail Address

**Actual result:**
Registration complete, success message

**Expected result:**
Validation message with description of error

Requirements: https://portal.qax-camp.com.ua/auth-1-2/

Environment :
Windows 10 PRO
Google Chrome Версія 107.0.5304.88
![email_26char](https://user-images.githubusercontent.com/92167884/201359967-64cd45ac-6e25-405e-8903-51fa68756b7f.png)

**Comment by DmytroMarkulych** [comment]
@Xalep4ik

В Actual Result, Ви мабуть мали на увазі "message"?
В steps for reproduce додайте останнім пунктом рядок який починається "Pay attention to.." і вкажіть на місце проблеми

@scholokov можливо варто було б збільшити кількість символів для поля EMAIL до 40?

**Comment by Xalep4ik** [comment]
виправив

**Comment by scholokov** [comment]
please retest according to updated requarements

**Comment by Xalep4ik** [comment]
Verified
