### ISSUE TITLE
Esse - Создать шаблонный дизайн страницы

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#27]
Создать шаблонный дизайн для типа страниц esse.
Это результаты прохождения тестов.
Так же на странице будут присутствовать комментарии

пример:
https://portal.qax-camp.com.ua/essay/%d0%ba%d0%b0%d0%ba%d0%b8%d0%b5-%d0%b2%d0%b8%d0%b4%d1%8b-%d0%b8%d1%82-%d0%ba%d0%be%d0%bc%d0%bf%d0%b0%d0%bd%d0%b8%d0%b9-%d0%b1%d1%8b%d0%b2%d0%b0%d1%8e%d1%82-35/
![image](https://user-images.githubusercontent.com/22824947/183907653-56886681-1943-42d7-87c4-5e88ce21a572.png)

**Comment by AlonaSarapina** [comment]
Esse design page https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=1212%3A66

**Comment by ABatalov** [comment]
@scholokov - I this task is not actual, am I right?

**Comment by scholokov** [comment]
задача актуальна
відсутній дизайн

**Comment by DmitriiNasonov** [comment]
Testing completed
