### ISSUE TITLE
The wrong word "передані" - on the paragraph III description - page - Privacy Policy  

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#275]
**STR**
1. Open page https://github.com/scholokov/qax-portal-2/wiki/Privacy-policy;
2. Scroll to paragraph III / pay attention to the first phrase (description); 
3. Open https://portal.qax-camp.com.ua/privacy_policy/ and pay attention to the first phrase.

**ACTUAL RESULT**
Word "передані" in the block description is shown

**EXPECTED RESULT**
Word "надаєте" in the block description is shown 

The phrase should look like "Персональна інформація, яку ви _надаєте_ нам через наш веб-сайт..."  instead of  "Персональна інформація, яку ви _передані_ нам через наш веб-сайт..."

![ueA6y0Zhl7](https://user-images.githubusercontent.com/109384052/201547500-71fa29de-96f0-4c81-a443-da3b89cf4923.png)

![Np6b04xcqS](https://user-images.githubusercontent.com/109384052/201547502-61917353-ece4-4d49-8b59-10fb26bfcc1e.png)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
