### ISSUE TITLE
Grammatical error - word "будь-яким" - paragraph IV - page Privacy Policy - Wiki requirement 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#276]
**STR**
1. Open https://github.com/scholokov/qax-portal-2/wiki/Privacy-policy
2. Pay attention to the third phrase block "IV. Розкриття персональної інформації". 

**ACTUAL RESULT**
The word "будь-яким" shown in the singular

**EXPECTED RESULT**
The word "будь-яким" is shown in the plural 

The phrase should look like "У зв’язку з _будь-якими_ поточними або майбутніми судовими процесами;"

![G8vzLuiTq3](https://user-images.githubusercontent.com/109384052/201548025-c0fcaf8b-d127-4dd8-81dc-b0b50b3e757e.png)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
