### ISSUE TITLE
Type of item numbering does not match Wiki - block V / third phrase - Privacy Policy page

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#277]
**STR**
1. Open https://portal.qax-camp.com.ua/privacy_policy/;
2. Pay attention to the third phrase in block V.

**ACTUAL RESULT**
Item numbering is shown like "пункті V-2"

**EXPECTED RESULT**
Item numbering is shown like "в пункті 2 розділу V"

Note:
1. Requuiremet:  https://github.com/scholokov/qax-portal-2/wiki/Privacy-policy;

Phrase should look like "Без обмежень положень, зазначених в пункті 2 розділу V...."

![qsVigvErLf](https://user-images.githubusercontent.com/109384052/201548418-6f6f203e-f314-4285-9628-af94c8db0486.png)
![88LZggE2Y3](https://user-images.githubusercontent.com/109384052/201548420-4463dfd4-590b-428b-9b26-20242f2715de.png)

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha Давайте замінемо слово "incorrect" в summary на таке щоб давало більше конкретики

**Comment by BatalovaOlha** [comment]
> @BatalovaOlha Давайте замінемо слово "incorrect" в summary на таке щоб давало більше конкретики

@DmytroMarkulych changed

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha в Expected result ми вказуємо фактично як має бути. 
Посилання на Wiki можна винести із STR в окремий пункт як додаткова інформація

**Comment by BatalovaOlha** [comment]
> @BatalovaOlha в Expected result ми вказуємо фактично як має бути. Посилання на Wiki можна винести із STR в окремий пункт як додаткова інформація

@DmytroMarkulych changed

**Comment by scholokov** [comment]
якби виправив "в лоб" - булаб помилка :))
![image](https://user-images.githubusercontent.com/22824947/210326024-dfd2a9b8-7944-4541-972f-5ba984a97163.png)

**Comment by scholokov** [comment]
fixed
