### ISSUE TITLE
Field Country from Registration Form appeared in central area below the menu list after click on Burger menu

### ISSUE THREAD

**Issue by Xalep4ik** [scholokov/qax-portal-2#278]
**STR:**

1. Open https://portal.qax-camp.com.ua/register/
2. Click on Burger menu in right corner of page
3. Pay attention to central area below the menu list 

**Actual result:**
There is Field Country from Registration Form 

**Expected result:**
There is no Field Country from Registration Form

Environment:
BrowserStack emulator - Samsung Galaxy Tab S8 12.0
Mozilla Firefox
![screenshot-Samsung Galaxy Tab S8-12 0](https://user-images.githubusercontent.com/92167884/201649701-fd310c81-d0c3-48ab-abbd-8957a4336edd.png)

**Comment by SOlkhova** [comment]
Verified
