### ISSUE TITLE
No extra space after description - paragraph VII - page Privacy Policy - Wiki requirement

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#279]
**STR**
1. Open https://github.com/scholokov/qax-portal-2/wiki/Privacy-policy and scroll down to paragraph VII
2. Pay attention to the end of the description.

**ACTUAL RESULT**
Sentences after the paragraph VII description do NOT start on a new line

**EXPECTED RESULT**
Sentences after the paragraph VII description start on a new line

![PYH1qkr4W6](https://user-images.githubusercontent.com/109384052/201921174-5198964d-9b1c-41a2-a19a-61585b3c9d0c.png)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
