### ISSUE TITLE
Implement about us page 

### ISSUE THREAD

**Issue by ABatalov** [scholokov/qax-portal-2#28]
We need to implement about us page:
https://portal.qax-camp.com.ua/about-us/

Design in Figma you can find here:  https://www.figma.com/file/JwKf4NLnNlzrSCaBlbhKu4/QAX-Camp-(Copy)?node-id=4542%3A1266 
Requirements here:  https://github.com/scholokov/qax-portal-2/wiki/About-us-page  

Here is product ver. on our Camp project: https://test.qax-camp.com.ua/about_us.php

**Comment by dmitryylev** [comment]
Partially Fixed. New issue #136 opened
