### ISSUE TITLE
MVP - Regression

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#280]
- Домашня - @DmitriiNasonov (done)
- Курси - @KaterinaNimenko35 (done)
- Про нас - @BatalovaOlha (done)
- Наші Тренери - @Nadiyk (done)
- Матеріали - not actual 
- Проекти - not actual 

- Записатися - @DmitriiNasonov (done)
- Live chat - @KaterinaNimenko35 (done)
- Footer - @BatalovaOlha (done)
- Header - @KaterinaNimenko35 (done)
- Facebook відгуки - @Nadiyk (done)

- Авторизація - @Xalep4ik (done)
- Реєстрація - @Xalep4ik (done)
- Відновлення паролю - @Xalep4ik (done)

**Comment by KaterinaNimenko35** [comment]
Header, Live chat, Курси

**Comment by Xalep4ik** [comment]
Авторизація , Реєстрація, Відновлення паролю

**Comment by YulyaBaday** [comment]
Наші тренери, Записатися

**Comment by Serhii-Ishchuk** [comment]
Матеріали, Проекти

**Comment by DmitriiNasonov** [comment]
домашня, записатися
