### ISSUE TITLE
Design - not design of tick in CheckBox of Privacy Policy in Figma

### ISSUE THREAD

**Issue by Xalep4ik** [scholokov/qax-portal-2#283]
**STR:**
1.Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2178%3A511&t=vkvgga0xoAggmWvv-0
2. Pay attention to the CheckBox of Privacy Policy at bottom of the Registration form

**Actual result:**
Not design of tick in CheckBox

**Expected result:**
The design of the tick in CheckBox is present

![figma_checbox](https://user-images.githubusercontent.com/92167884/202711463-2fd8fbd0-cd28-4bb7-ba4a-5a82d907e6fb.png)

**Comment by DmytroMarkulych** [comment]
@Xalep4ik Давайте перефразуємо  summary таким чином, щоб уникнути фразу there is

**Comment by Xalep4ik** [comment]
@DmytroMarkulych так?

**Comment by scholokov** [comment]
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2178%3A511&t=zxWBau6Mp0OgR8Ay-0

**Comment by GNatala** [comment]
passed
