### ISSUE TITLE
Regression MVP - Курси

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#286]
You need create test cases for the required section.
Checklist: https://docs.google.com/spreadsheets/d/1GTqXFBRoPAkEpoigvJG7OkL1s3wORklUrlyetCS2iTE/edit#gid=0

**Comment by ButKoff** [comment]
#280

**Comment by KaterinaNimenko35** [comment]
**Checklist**
https://docs.google.com/spreadsheets/d/1GTqXFBRoPAkEpoigvJG7OkL1s3wORklUrlyetCS2iTE/edit#gid=0
