### ISSUE TITLE
Regression MVP - Про нас

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#287]
You need create test cases for the required section.
Test Case: https://docs.google.com/spreadsheets/d/1uy7FIv3-8g4bwInUu8GhntCoufvOjnDK5SZVkel5A5s/edit#gid=0

**Comment by BatalovaOlha** [comment]
https://olhabatalova.testrail.io/index.php?/cases/view/2478

**Comment by BatalovaOlha** [comment]
https://olhabatalova.testrail.io/index.php?/cases/view/2479&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=1

**Comment by BatalovaOlha** [comment]
https://docs.google.com/spreadsheets/d/1uy7FIv3-8g4bwInUu8GhntCoufvOjnDK5SZVkel5A5s/edit#gid=0

**Comment by BatalovaOlha** [comment]
Додаю таску в to review, бо тут залишається ще один мій тест кейс

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha відсутній доступ до файлу

**Comment by BatalovaOlha** [comment]
Змінила. Перепрошую 🫣

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha якщо є кілька умов в чеклисті, то краще їх розділити на окремі пункти, і узагальнити назвою
