### ISSUE TITLE
Regression MVP - Наші Тренери

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#288]
You need create test cases for the required section.
Product environment: https://www.qax-camp.com.ua/trainers/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.4.-Our-Trainers
![Image](https://user-images.githubusercontent.com/109460500/212268917-44e9cb06-1f6c-49c5-8fba-7a07e2842ca8.png)

**Comment by ButKoff** [comment]
#280

**Comment by Nadiyk** [comment]
verified
