### ISSUE TITLE
Regression MVP - Facebook відгуки

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#289]
You need create test cases for the required section.
Product environment: https://www.qax-camp.com.ua/current_cources/
![Image](https://user-images.githubusercontent.com/109460500/212267233-ab8815f7-cb0f-4c34-87f4-351407762cb4.png)

**Comment by ButKoff** [comment]
#280

**Comment by Nadiyk** [comment]
verified
