### ISSUE TITLE
Regression MVP - Live chat

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#292]
You need create test cases for the required section.
Checklist:
https://docs.google.com/spreadsheets/d/1ahB3B1UTvLpwq9kHZkgFyPFg-vRd1BgIM0XVecopEI0/edit#gid=0
Visualization: https://miro.com/welcomeonboard/dzRPWmlBZ3VYcGRJUmpLcjQwbzFTYVNEZXpzYk14djRPREZ0WGdDdHV3bjZERkNqQzZndjBXQ2tLRGhvOVdvRHwzNDU4NzY0NTI2Njk1MjgyMDA0fDI=?share_link_id=104639293558

**Comment by ButKoff** [comment]
#280

**Comment by KaterinaNimenko35** [comment]
**Checklist**  
https://docs.google.com/spreadsheets/d/1ahB3B1UTvLpwq9kHZkgFyPFg-vRd1BgIM0XVecopEI0/edit#gid=0

**Visualization**  https://miro.com/welcomeonboard/dzRPWmlBZ3VYcGRJUmpLcjQwbzFTYVNEZXpzYk14djRPREZ0WGdDdHV3bjZERkNqQzZndjBXQ2tLRGhvOVdvRHwzNDU4NzY0NTI2Njk1MjgyMDA0fDI=?share_link_id=104639293558
