### ISSUE TITLE
Regression MVP - Header

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#294]
You need create test cases for the required section.
Checklist:
https://docs.google.com/spreadsheets/d/1rLoJ9gyAuGze0zhfesa-iRyERUh0wcEVsmt9kWpAapo/edit#gid=0
Visualization:
https://miro.com/welcomeonboard/dzRPWmlBZ3VYcGRJUmpLcjQwbzFTYVNEZXpzYk14djRPREZ0WGdDdHV3bjZERkNqQzZndjBXQ2tLRGhvOVdvRHwzNDU4NzY0NTI2Njk1MjgyMDA0fDI=?share_link_id=264318829100

**Comment by KaterinaNimenko35** [comment]
**Checklist**
https://docs.google.com/spreadsheets/d/1rLoJ9gyAuGze0zhfesa-iRyERUh0wcEVsmt9kWpAapo/edit#gid=0

**Visualization**
https://miro.com/welcomeonboard/dzRPWmlBZ3VYcGRJUmpLcjQwbzFTYVNEZXpzYk14djRPREZ0WGdDdHV3bjZERkNqQzZndjBXQ2tLRGhvOVdvRHwzNDU4NzY0NTI2Njk1MjgyMDA0fDI=?share_link_id=264318829100
