### ISSUE TITLE
Figma design - Test page - Panel for selecting any question in the test is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#298]
**Steps of reproducing:**
1. Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=931%3A91&t=qxzrUQZqNTZ8KIWy-0

**Expected Result:**
Panel for selecting any question in the test is present

**Actual Result:**
Panel for selecting any question in the test is missing

**Specification:**
https://github.com/scholokov/qax-portal-2/wiki/1.7.3.-Tests

**Environment:**
Windows 10, Chrome 107.0.5304.107 (64 bit)
![Portal design – Figma - Google Chrome 21 11 2022 12_17_23](https://user-images.githubusercontent.com/95171672/203317643-1a3306cc-b216-4e22-9ae4-400778517605.png)

**Comment by DmytroMarkulych** [comment]
@DmitriiNasonov виділіть проблемне місце на скріні

**Comment by DmitriiNasonov** [comment]
Требования к расположению этого UI элемента еще не созданы или утеряны, поэтому указать проблемное место не получается

**Comment by DmytroMarkulych** [comment]
@DmitriiNasonov тоді варто тегнути що ще UI задачка

**Comment by DmitriiNasonov** [comment]
verified. bug isn't reproducing
