### ISSUE TITLE
Requirements - Registration - Country field contains information which contradictory the meaning of a field 

### ISSUE THREAD

**Issue by Xalep4ik** [scholokov/qax-portal-2#299]
STR:
1. Open https://github.com/scholokov/qax-portal-2/wiki/Regitration
2. Pay attention to the field Country  

Actual result:
Field Country contains contradictory information which matches with information from the previous field and contradicts the meaning of a field

Expected result:
Field Country contains only unique information that matches the meaning of a field 

![spec_bug_country](https://user-images.githubusercontent.com/92167884/203506514-5453b6d7-6a1a-4ea5-8f91-6b00f7138d95.png)

**Comment by DmytroMarkulych** [comment]
@Xalep4ik тегніть, що це баг по специфікації

**Comment by Xalep4ik** [comment]
@DmytroMarkulych а як?

**Comment by Xalep4ik** [comment]
#Documentation
Verified.
