### ISSUE TITLE
Create design block "Чому обирають нас?" on the Home page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#315]
We need to create design block "Чому обирають нас?" on the Home page.
Design on Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A22&t=X8ceBdRtyjajaGzw-0
Test environment: https://portal.qax-camp.com.ua/
Block content: https://github.com/scholokov/qax-portal-2/wiki/Home-%5Bpage%5D
![Чому](https://user-images.githubusercontent.com/109460500/211314731-f2073dcb-4392-4476-9f29-b02c99a9853e.png)
![Чому_](https://user-images.githubusercontent.com/109460500/211314754-822b8d56-a170-4ed0-a53a-48ccf8ba0c7e.png)

**Comment by AlonaSarapina** [comment]
ready for testing 
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=3555%3A2910&t=5omo5OuoRUhKxG5G-1

**Comment by dmitryylev** [comment]
verified
