### ISSUE TITLE
Form: Сповіщення повинне приходити у телеграм

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#316]
Сповіщення з форми повинне приходити у телеграм, а не на пошту

приклад:
https://camp.qax-camp.com.ua/

![image](https://user-images.githubusercontent.com/22824947/205600576-5e4a70d8-3a84-4749-9b7d-21a53d30751f.png)

![image](https://user-images.githubusercontent.com/22824947/205600138-e51ca99b-8c50-4b40-b7ae-8c760f37b8df.png)

**Comment by poroskundenys** [comment]
Сообщение приходит и в телеграмм и на почту

**Comment by GNatala** [comment]
Сповіщення проходить на почту та в Телеграм

Перевірено
