### ISSUE TITLE
Mob-Tab - In the footer, social icons are displayed in two lines, when the screen width is 360px

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/qax-portal-2#317]
**Steps to reproduce:**
1. Open the page with a screen width 360px https://portal.qax-camp.com.ua/
2. Scroll down to the footer
3. Pay attention to how the social icons are displayed

**Actual result:** Icons are displayed in two lines
**Expected result:** Icons are displayed in line (according to [Figma ](https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A22))

**Environment:**  Windows 11, Google Chrome - 108.0.5359.73 , (64 бит)

![NVIDIA_Share_YzHDYGKCt4](https://user-images.githubusercontent.com/57997443/206154131-3d582fb4-7f0a-41fc-a956-5b1a48348105.png)

![NVIDIA_Share_0wVmdAAQvY](https://user-images.githubusercontent.com/57997443/206154627-77ba045d-1b16-490c-8eda-ab0a16a80a9a.png)

**Comment by scholokov** [comment]
please retest

**Comment by dmitryylev** [comment]
bug is fixed
