### ISSUE TITLE
In header, button hover "Записатися" is white

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/qax-portal-2#318]
**Steps to reproduce:**
1. Open the page https://portal.qax-camp.com.ua/
2. Pay attention to the button hover "Записатися"

**Actual result:** Hover is white
**Expected result:** Hover is transparent (according to [Figma](https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=1979%3A247&t=btz0FzldpaSmtOr2-0))

**Environment:**  Windows 11, Google Chrome - 108.0.5359.73 , (64 бит)

![NVIDIA_Share_I9VkBHV8CP](https://user-images.githubusercontent.com/57997443/206156689-d1620398-aa2a-4fa6-a881-ee261d29adbd.png)

![ShareX_8GXBKbrXhW](https://user-images.githubusercontent.com/57997443/206156714-7bc4f260-0906-4975-b558-8e609a188800.png)

**Comment by Nadiyk** [comment]
verified
