### ISSUE TITLE
No possibility delete dial code "+38 (0" in the registration form "Записатися на курс"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#320]
**STR**

1. Open https://www.qax-camp.com.ua/#write_to_us
2. Try to delete all numerals in the line where should be a mobile number 

**ACTUAL RESULT**
The numerals  "+38 (0" are NOT deleted

**EXPECTED RESULT**
All numerals in the phone line could be deleted

Environment:
iPhone (IOS 16) / Windows 10 Pro

![Що таке Camp_ – QAX Camp - Google Chrome 2022-12-01 18-23-00 (1)](https://user-images.githubusercontent.com/109384052/206467145-120f569c-fb85-4302-82ca-da832e5b5d06.gif)

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha доволі цікавий дефект)

**Comment by BatalovaOlha** [comment]
resolved

**Comment by scholokov** [comment]
@BatalovaOlha 
а ти на мобілі дивилася? :)
