### ISSUE TITLE
Create design of "Картка курсу" block on Portal Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#321]
We need to create design of "Картка курсу" page on Portal Figma.
Design on Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A43&t=MDdfrOhdMX2INsJH-0
Production environment:  https://www.qax-camp.com.ua/qa-courses-2/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials
![Картка курсу  Figma](https://user-images.githubusercontent.com/109460500/222439439-0067c764-d2eb-4811-b13a-fb69f2895ae9.png)

**Comment by ButKoff** [comment]
#368

**Comment by Nadiyk** [comment]
Verifed
