### ISSUE TITLE
Матеріали - Quality Assurance Engineer (QA) - Теорія тестування. Базовий рівень. Рівень складності 0 - Q2. Базовий курс QA - Q2.01 Тестувальник. Хто це? - Lesson control buttons missing

### ISSUE THREAD

**Issue by KaterinaNimenko35** [scholokov/qax-portal-2#325]
**Steps to reproduce:**

1. Open page https://www.qax-camp.com.ua/courses/q2-basic-cource/lessons/q2-01-%d1%82%d0%b5%d1%81%d1%82%d1%83%d0%b2%d0%b0%d0%bb%d1%8c%d0%bd%d0%b8%d0%ba-%d1%85%d1%82%d0%be-%d1%86%d0%b5/
2. Scroll down the page to the lesson control block

**Actual result:**
Lesson control buttons **missing**

**Expected result:**
Lesson control buttons **present**

**Notes:**
Design in Figma
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A12775&t=bY9As8LQbSiX11OI-0

**Environment:**
Desktop/W10/Google Chrome 101.0.4951.67 (64-bit) 1920х1080

https://user-images.githubusercontent.com/105543094/208306527-e3d9d39b-ef00-422f-9d81-18707fc66588.mp4

![2022-12-18 16 34 36](https://user-images.githubusercontent.com/105543094/208306554-8e8d5b3d-e509-4f7c-8254-7d6a19b86174.png)

![2022-12-17 14 27 5533](https://user-images.githubusercontent.com/105543094/208306569-7e4bc85d-9038-4b4a-8ff0-3597d161139f.png)

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
Partially Fixed. New issue #417 #418  opened
