### ISSUE TITLE
Mobile - Курси - Quality Assurance Engineer (QA) - Content - Text is displayed out of proportion

### ISSUE THREAD

**Issue by KaterinaNimenko35** [scholokov/qax-portal-2#326]
**Steps to reproduce:**

1. Open page https://www.qax-camp.com.ua/current_cources/
2. Click on the course "Quality Assurance Engineer (QA)" image
3. Pay attention to page content

**Actual result:**
Text is displayed out of proportion

**Expected result:**
Text is displayed proportionally

**Notes:**
Pay attention, an issue is reproduced on the pages:

- https://www.qax-camp.com.ua/pm-courses/
- https://www.qax-camp.com.ua/ba-courses/
- https://www.qax-camp.com.ua/recruiter-courses/

**Environment:**
Mobile Android 10/Chrome 103  720*1560

![2022-12-20 19 42 50](https://user-images.githubusercontent.com/105543094/208731744-c04b8482-8be9-4726-90c5-d9fb03b11e3f.png)

**Comment by KaterinaNimenko35** [comment]
#286

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
not actual
