### ISSUE TITLE
Figma design - Main test - "Button up" is missing

### ISSUE THREAD

**Issue by KaterinaNimenko35** [scholokov/qax-portal-2#327]
**Steps to reproduce:**

Open page https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A22&t=hf9EyxriEER797DM-0

**Actual result:**
"Button up" is missing

**Expected result:**
"Button up" is present

**Environment:**
Desktop/W10/Google Chrome 101.0.4951.67 (64-bit) 1920х1080

![2022-12-20 19 59 03](https://user-images.githubusercontent.com/105543094/208734939-d584653f-0f0b-45d0-ba33-489f1374c8ce.png)

**Comment by ButKoff** [comment]
retest @KaterinaNimenko35

**Comment by GNatala** [comment]
passed
