### ISSUE TITLE
Home page-ІСТОРІЇ УСПІХУ- linkedin-link Dmytro Hranovskyi- Цієї сторінки не існує

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#329]
**Кроки відтворення:**
1.Відкрити сторінку  https://www.qax-camp.com.ua/
2.Проскролити сторінку до"ІСТОРІЇ УСПІХУ"
3.Натиснути кнопку "дивитися усіх"
4.Знайти студента Dmytro Hranovskyi
5.Натиснути на linkedin-link студента Dmytro Hranovskyi
6.Звернути увагу на сторінку студента в linkedin

**Фактичний результат:** Цієї сторінки не існує
**Очікуваний результат:** Перенаправляє на сторінку студента в linkedin

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)

https://user-images.githubusercontent.com/109720075/209530109-a83624d5-8300-418f-8c57-6fa1e9078d64.mp4

**Comment by andry1729** [comment]
Ось нове посилання на сторінку студента
https://www.linkedin.com/in/dmytro-hranovskyi/

**Comment by scholokov** [comment]
fixed
