### ISSUE TITLE
Instagram button and new desktop footer design

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#33]
Надо добавить в footer иконку Instagram.
Для дизайна desktop предложить вариант "текст + картинка" (пример во вложении).
На tablet и mobile добавляем только иконку Instagram.
![Иконки Footer](https://user-images.githubusercontent.com/109460500/184691879-97577f72-2f69-46fa-a8ae-01aa0bf9a146.png)

**Comment by ABatalov** [comment]
@ButKoff , задвоилась эта задачка я ее уже оформил ранее: https://github.com/scholokov/qax-portal-2/issues/30 
Наверное нужно одну из этих задачек в Canceled

**Comment by ABatalov** [comment]
Ready for testing: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A23
