### ISSUE TITLE
Home page-ІСТОРІЇ УСПІХУ- відсутня кнопка "Згорнути "- згортає розгорнутий список

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#330]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/
2.Проскролити сторінку до"ІСТОРІЇ УСПІХУ"
3.Натиснути кнопку "дивитися усіх"
4.Звернути увагу на кнопку "Згорнути "

**Фактичний результат:** Відсутня кнопка "Згорнути "
**Очікуваний результат:** Присутня кнопка "Згорнути "- згортає розгорнутий список

**Додаткова інформація:** https://github.com/scholokov/qax-portal-2/wiki/1.1.-Home-%5Bpage%5D

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_1](https://user-images.githubusercontent.com/109720075/209532053-efabe671-18a2-46a2-a66a-b436128390a1.png)

https://user-images.githubusercontent.com/109720075/209532416-dfe0600a-2f31-4872-9363-4c5457750e6c.mp4

**Comment by GNatala** [comment]
перевірено
