### ISSUE TITLE
Home page-потрібна допомога?- живий чат-контент"Вау! Перший крок до мрії зроблено✅!  Маєш питання❓ З радістю допоможемо. Мерщій пиши!😉"

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#332]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/
2.Навести курсор миші на  кнопку "потрібна допомога?"
3.Вибрати живий чат та клікнути на кнопку
4.Звернути увагу на текст контенту  

**Фактичний результат:** Контент-"Вау! Перший крок до мрії зроблено✅!  Маєш питання❓ З радістю допоможемо. Мерщій пиши!😉"
**Очікуваний результат:** Контент-"Вітаємо у прогресивному просторі QAX!" "Чим можу бути корисним?"

**Додаткова інформація:** https://github.com/scholokov/qax-portal-2/wiki/Chat

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_4](https://user-images.githubusercontent.com/109720075/209549066-dbf881fb-e391-4a42-98dc-bf46229c7c6e.png)
![Screenshot_5](https://user-images.githubusercontent.com/109720075/209549069-0031b167-e734-4fbd-9314-838c4aff010b.png)

**Comment by GNatala** [comment]
Повідомлення актуальне. То інша помилка, що дата не змінюєть.
Сьогоднішній скрін:
![image](https://user-images.githubusercontent.com/101987790/226293707-19b0ea1b-f2ad-45a7-99e0-515e4556eb3e.png)

**Comment by GNatala** [comment]
Дякую. Passed
