### ISSUE TITLE
Наші тренери-linkedin-link Андрій Самойленко- Цієї сторінки не існує

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#334]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/trainers/
2.Проскролити сторінку до тренера Андрій Самойленко
3.Натиснути  на linkedin-link Андрій Самойленко
4.Звернути увагу на сторінку тренера в linkedin

**Фактичний результат:** Цієї сторінки не існує
**Очікуваний результат:** Перенаправляє на сторінку тренера в linkedin

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)

https://user-images.githubusercontent.com/109720075/209554763-831eb4c4-681a-4f6e-a8d8-9f89adf5fdd7.mp4

**Comment by scholokov** [comment]
fixed
