### ISSUE TITLE
Home page-Записатися- реєстрація проходить  з пустим полем email

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#335]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/
2.Натиснути на кнопку "Записатися"в правому верхньому кутку
3.З'являється форма "Записатися на курс"
4.Заповнити поля форми: ім'я-Андрій ,номер телефону-+380970707188.Поля email та коментар залишити пустими.Поставити галочку в "Погоджуюсь відправити мої контакти менеджеру QAX Camp. Конфіденційно. Без спаму"
5.Натиснути на кнопку "Відправити "
6.Звернути увагу на повідомлення після відправлення форми

**Фактичний результат:** Реєстрація проходить  з пустим полем email
**Очікуваний результат:** Приходить повідомлення "Невірний формат email адреси. 

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_10](https://user-images.githubusercontent.com/109720075/209558482-470c1881-84f5-44ba-bde7-f08196a8852e.png)
![Screenshot_11](https://user-images.githubusercontent.com/109720075/209558485-3735fb4b-2346-4920-aa6e-490cb89ac824.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 Очікуваний результат має містити один результат. Додаткову інформацію можна винести як "Додаткова інформація" або якщо є кілька варіантів то розділити баг репорт на кілька

**Comment by scholokov** [comment]
please retest according to requirements
https://github.com/scholokov/qax-portal-2/wiki/1.5.-Form
