### ISSUE TITLE
New text and images for the main page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#34]
Надо обновить текст приветствия домашней страницы:
_До оферу разом з QAX
Вдосконалення через практику на реальних проектах та менторство
Незалежно від точки відліку, в якій ти знаходишся зараз,  обравши QAX ти досягнеш поставленої цілі!
Ти лише робиш перші кроки до успішної кар'єри в ІТ?
Команда QAX допоможе підібрати відповідні сходинки для твого росту та розвитку. Рухаючись  ними ти обов'язково досягнення результату -  отримаєш бажаний Job Offer.
Ти вже впевнено почуваєш себе в сфері IT, але прагнеш постійно розвиватися?
 В QAX  ти зможеш підібрати потрібні скіли для розвитку. Вдосконалити свої знання та вміння і, відповідно, підвищити свій дохід.
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A22
![Главная страница](https://user-images.githubusercontent.com/109460500/186877677-f62e5970-d57d-41d4-a49c-4426cfc8d339.png)

**Comment by ABatalov** [comment]
Ready for testing: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design

**Comment by KaterinaNimenko35** [comment]
verified
