### ISSUE TITLE
Footer-Logo QAX- після натискання на лого QAX , перенаправлення на сторінку https://www.qax-camp.com.ua/

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#342]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/
2.Проскролити сторінку футера сторінки
3.Натиснути на лого QAX
2.Звернути увагу на яку сторінку перенаправляє

**Фактичний результат:** Перенаправлення на сторінку https://www.qax-camp.com.ua/
**Очікуваний результат:** Перенаправлення на сторінку https://qax.com.ua/

**Додаткова інформація:** https://github.com/scholokov/qax-portal-2/wiki/1.1.4.-Footer

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_124](https://user-images.githubusercontent.com/109720075/209789927-97241807-476d-4aca-bbbc-66001a433481.png)
![Screenshot_125](https://user-images.githubusercontent.com/109720075/209789974-7d16518a-5792-4ea7-a245-cdf502551707.png)

https://user-images.githubusercontent.com/109720075/209790287-1478d0e9-e442-401e-8032-a55f836f60ce.mp4

![Screenshot_1](https://user-images.githubusercontent.com/109720075/209963945-786c1cc9-4865-41ba-b389-093675ad1f76.png)

**Comment by BatalovaOlha** [comment]
@andry1729 цей баг давно стоворено #313

**Comment by scholokov** [comment]
коли у нас проблема с некоректною лінкою, краще робити скрін - коли мишка наведена на цей елемент. у цьому випадку одразу видно саму лінку (лівий нижній угол)

**Comment by andry1729** [comment]
Скрін додав в баг репорт

**Comment by scholokov** [comment]
для зняття скрінів краще використовуй спеціальне ПО. це у налаштуваннях вибери - захватувати курсор. для таких багів це важливо

**Comment by andry1729** [comment]
Зробив скрін з курсором

**Comment by scholokov** [comment]
duplicated to #313
