### ISSUE TITLE
Home page-при зменшинні маштабу сторінки до 50%,інформація під Header-ом зміщується в лівий край сторінки

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#344]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/
2.Зменшити маштаб до 50%
3.Звернути увагу на інформацію під Header-ом

**Фактичний результат:** Інформація під Header-ом зміщується в лівий край сторінки
**Очікуваний результат:** Інформація під Header-ом не зміщується в лівий край сторінки

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_1](https://user-images.githubusercontent.com/109720075/209801368-632ab84c-f335-4cfb-b709-089e722114d8.png)
![Screenshot_2](https://user-images.githubusercontent.com/109720075/209801376-7a11c7bc-1061-4a80-8b15-06d7e5b1eaf4.png)

**Comment by scholokov** [comment]
please retest

**Comment by OlhaHutsman** [comment]
@scholokov verified
