### ISSUE TITLE
Home - Form "Записатися на курс" - Text "Погоджуюсь відправити мої контакти менеджеру QAX Camp. Конфіденційно. Без спаму." shifted down and to the left

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#345]
**Steps of reproducing:**
1. Open https://portal.qax-camp.com.ua/
2. Scroll to structural block "Записатися на курс"
3. Pay attention to the location of the text "Погоджуюсь відправити мої контакти менеджеру QAX Camp. Конфіденційно. Без спаму."

**Expected Result:**
The text is placed to the right of the checkbox

**Actual Result:**
Text shifted down and to the left

**Specification:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A22&t=W6QHIHen6yCCvRgN-0

**Enviroments:**
Windows 10, Chrome 108.0.5359.125 (64 bit)
Android 8.1.0, Chrome 108.0.5359.128
![QAX Camp – Students Portal - Google Chrome 28 12 2022 14_58_18](https://user-images.githubusercontent.com/95171672/209816929-78b952f9-4a1b-4620-8e38-0d066f069f08.png)
![photo_2022-12-28_15-04-56](https://user-images.githubusercontent.com/95171672/209816930-4fdb4151-87c6-42b4-91a9-331f2277f7a6.jpg)

**Comment by scholokov** [comment]
please retest

**Comment by DmitriiNasonov** [comment]
retested
![long-travel live - Google Chrome 03 01 2023 16_21_03](https://user-images.githubusercontent.com/95171672/210376654-572b7683-2cc9-4fc6-adb6-c09874f17945.png)
![photo_2023-01-03_16-24-51](https://user-images.githubusercontent.com/95171672/210376657-82bc10e5-3a51-4615-80df-88172683a6e6.jpg)

**Comment by ButKoff** [comment]
#291

**Comment by DmitriiNasonov** [comment]
verified. bug isn't reproducing
