### ISSUE TITLE
Home page-Матеріали-Quality Assurance Engineer (QA)-відсутній блок "Базовий рівень. Додаткові матеріали"після блоку"Теорія тестування. Базовий рівень"

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#347]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/
2.В Header-і сторінки клікнути на "Матеріали"
3.Вибрати Quality Assurance Engineer (QA) і клікнути на зображення Quality Assurance Engineer (QA)
4.Звернути увагу на блок "Базовий рівень. Додаткові матеріали"після блоку"Теорія тестування. Базовий рівень"

**Фактичний результат:** Відсутній блок "Базовий рівень. Додаткові матеріали"
**Очікуваний результат:** Присутній блок "Базовий рівень. Додаткові матеріали"

**Додаткова інформація:** https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_6](https://user-images.githubusercontent.com/109720075/209830707-ea62157a-d86d-4ba5-9250-94c23aecfc87.png)
![Screenshot_7](https://user-images.githubusercontent.com/109720075/209830708-b56879cb-6715-4eb2-a3fa-1022713aab1c.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в Кроках для відтворення не потрібно вказувати очікувані результати. Вказуємо тільки дії які потрібно виконати для відтворення дефекту

**Comment by DmytroMarkulych** [comment]
@andry1729 вкажіть будь ласка в 3-му кроці на яке саме зображення клікнути

**Comment by scholokov** [comment]
виправлено у вимогах

**Comment by GNatala** [comment]
Вимоги  https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials, що до пункту "Базовий рівень. Додаткові матеріали" не змінились.

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/226297657-ca35e1f6-7d81-4b4b-8eed-7bf3448e7d50.png)

**Comment by scholokov** [comment]
виправлено у вимогах
https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials

**Comment by GNatala** [comment]
passed
