### ISSUE TITLE
Home page-Матеріали-Quality Assurance Engineer (QA)-Блок "Інструменти QA"-відсутній рівень складності

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#348]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/
2.В Header-і сторінки клікнути на "Матеріали"
3.Вибрати Quality Assurance Engineer (QA) і клікнути на зображення Quality Assurance Engineer (QA)
4.Звернути увагу на рівень складності в назві блоку"Інструменти QA"

**Фактичний результат:** Відсутній рівень складності
**Очікуваний результат:** Присутній рівень складності

**Додаткова інформація:** https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_8](https://user-images.githubusercontent.com/109720075/209832499-ff466b88-93bd-4d1e-86ed-18f5ec13ae96.png)
![Screenshot_9](https://user-images.githubusercontent.com/109720075/209832501-85be1290-b131-4dbb-8fa4-d83b8ebb6047.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в Кроках для відтворення не потрібно вказувати очікувані результати. Вказуємо тільки дії які потрібно виконати для відтворення дефекту

**Comment by DmytroMarkulych** [comment]
@andry1729 вкажіть будь ласка в 3-му кроці на яке саме зображення клікнути

**Comment by scholokov** [comment]
please retest
