### ISSUE TITLE
Home page-Матеріали-Quality Assurance Engineer (QA)-Блок "Процеси"-відсутній курс"Processes"

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#350]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/
2.В Header-і сторінки клікнути на "Матеріали"
3.Вибрати Quality Assurance Engineer (QA) і клікнути на зображення Quality Assurance Engineer (QA)
4.Розгорнути блок "Процеси"
5.Звернути увагу на курси

**Фактичний результат:** Відсутній курс"Processes"
**Очікуваний результат:** Присутній курс"Processes"

**Додаткова інформація:** https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_12](https://user-images.githubusercontent.com/109720075/209833708-5711ba37-8d2f-4f2f-861d-e23f54f9b00d.png)
![Screenshot_13](https://user-images.githubusercontent.com/109720075/209833711-fdae3f26-0ebc-4419-9ac1-a8b83a0e86bb.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в Кроках для відтворення не потрібно вказувати очікувані результати. Вказуємо тільки дії які потрібно виконати для відтворення дефекту

**Comment by DmytroMarkulych** [comment]
@andry1729 вкажіть будь ласка в 3-му кроці на яке саме зображення клікнути

**Comment by scholokov** [comment]
виправлено у вимогах

**Comment by GNatala** [comment]
passed
