### ISSUE TITLE
Home page-Матеріали-Quality Assurance Engineer (QA)-відсутній блок "Поглиблена теорія тестування"після блоку"Процеси"

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#351]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/
2.В Header-і сторінки клікнути на "Матеріали"
3.Вибрати Quality Assurance Engineer (QA) і клікнути на зображення Quality Assurance Engineer (QA)
4.Проскролити сторінку до блоку"Процеси"
5.Звернути увагу на блок "Поглиблена теорія тестування"після блоку"Процеси"

**Фактичний результат:** Відсутній блок "Поглиблена теорія тестування"
**Очікуваний результат:** Присутній блок "Поглиблена теорія тестування"

**Додаткова інформація:** https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_14](https://user-images.githubusercontent.com/109720075/209835828-9a9b0928-c053-49fd-ae10-c9ef7ed7e2fe.png)
![Screenshot_15](https://user-images.githubusercontent.com/109720075/209835834-7e74fc28-9ea6-48c6-a81a-4c42c045dd82.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в Кроках для відтворення не потрібно вказувати очікувані результати. Вказуємо тільки дії які потрібно виконати для відтворення дефекту

**Comment by DmytroMarkulych** [comment]
@andry1729 вкажіть будь ласка в 3-му кроці на яке саме зображення клікнути

**Comment by andry1729** [comment]
Додав

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
