### ISSUE TITLE
Home page-Матеріали-Quality Assurance Engineer (QA)-Блок "Різні домени тестування"-відсутній рівень складності

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#352]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/
2.В Header-і сторінки клікнути на "Матеріали"
3.Вибрати Quality Assurance Engineer (QA) і клікнути на зображення Quality Assurance Engineer (QA)
4.Проскролити сторінку до блоку"Різні домени тестування"
5.Звернути увагу на рівень складності в назві блоку"Різні домени тестування"

**Фактичний результат:** Відсутній рівень складності
**Очікуваний результат:** Присутній рівень складності

**Додаткова інформація:** https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_16](https://user-images.githubusercontent.com/109720075/209836448-579ca595-9ea1-4d71-af90-9caf693da611.png)
![Screenshot_17](https://user-images.githubusercontent.com/109720075/209836452-c86455bb-7f5c-48c0-bf02-6506c7ec6bc8.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в Кроках для відтворення не потрібно вказувати очікувані результати. Вказуємо тільки дії які потрібно виконати для відтворення дефекту

**Comment by DmytroMarkulych** [comment]
@andry1729 вкажіть будь ласка в 3-му кроці на яке саме зображення клікнути

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
