### ISSUE TITLE
Home page-Матеріали-Quality Assurance Engineer (QA)-Блок "Різні домени тестування"-назва курсу"Особенности тестирования на различных платформах" на російській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#353]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/
2.В Header-і сторінки клікнути на "Матеріали"
3.Вибрати Quality Assurance Engineer (QA) і клікнути на зображення Quality Assurance Engineer (QA)
4.Проскролити сторінку до блоку"Різні домени тестування"
5.Розгорнути блок для перегляду курсів
6.Звернути увагу на назву курсу"Особенности тестирования на различных платформах"

**Фактичний результат:** Назва курсу на російській мові
**Очікуваний результат:** Назва курсу на українській мові

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_18](https://user-images.githubusercontent.com/109720075/209837142-2ca0f0c5-b278-4230-92ec-149205c9a943.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в Кроках для відтворення не потрібно вказувати очікувані результати. Вказуємо тільки дії які потрібно виконати для відтворення дефекту

**Comment by DmytroMarkulych** [comment]
@andry1729 вкажіть будь ласка в 3-му кроці на яке саме зображення клікнути.

**Comment by scholokov** [comment]
fixed
