### ISSUE TITLE
Home page-Матеріали-Quality Assurance Engineer (QA)-відсутній блок "Web технології"після блоку"Різні домени тестування"

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#354]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/
2.В Header-і сторінки клікнути на "Матеріали"
3.Вибрати Quality Assurance Engineer (QA) і клікнути на зображення Quality Assurance Engineer (QA)
4.Проскролити сторінку до блоку"Різні домени тестування"
5.Звернути увагу на блок "Web технології"після блоку"Різні домени тестування"

**Фактичний результат:** Відсутній блок "Web технології"
**Очікуваний результат:** Присутній блок "Web технології"

**Додаткова інформація:** https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_19](https://user-images.githubusercontent.com/109720075/209838503-93da4a9c-3050-448c-8ca7-1666c0841f38.png)
![Screenshot_20](https://user-images.githubusercontent.com/109720075/209838572-997d7060-e4a2-4648-846d-b6a6c5762e8e.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в Кроках для відтворення не потрібно вказувати очікувані результати. Вказуємо тільки дії які потрібно виконати для відтворення дефекту

**Comment by DmytroMarkulych** [comment]
@andry1729 вкажіть будь ласка в 3-му кроці на яке саме зображення клікнути

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
