### ISSUE TITLE
Home page-Матеріали-Quality Assurance Engineer (QA)-Блок "Бази даних"-відсутній рівень складності

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#355]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/
2.В Header-і сторінки клікнути на "Матеріали"
3.Вибрати Quality Assurance Engineer (QA) і клікнути на зображення
4.Проскролити сторінку до блоку"Бази даних"
5.Звернути увагу на рівень складності в назві блоку"Бази даних"

**Фактичний результат:** Відсутній рівень складності
**Очікуваний результат:** Присутній рівень складності

**Додаткова інформація:** https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_21](https://user-images.githubusercontent.com/109720075/209839052-2c1c4ceb-3413-4a7f-a476-dbaeb5c86a0f.png)
![Screenshot_22](https://user-images.githubusercontent.com/109720075/209839057-92a62835-0d67-4138-b5b2-d92449dc7d83.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в Кроках для відтворення не потрібно вказувати очікувані результати. Вказуємо тільки дії які потрібно виконати для відтворення дефекту

**Comment by GNatala** [comment]
Курс актуальний 
**Passed**
