### ISSUE TITLE
Home page-Матеріали-Quality Assurance Engineer (QA)-відсутній блок "Бази даних. Додатковий матеріал"після блоку"Бази даних"

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#356]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/
2.В Header-і сторінки клікнути на "Матеріали"
3.Вибрати Quality Assurance Engineer (QA) і клікнути на зображення
4.Проскролити сторінку до блоку"Бази даних"
5.Звернути увагу на блок "Бази даних. Додатковий матеріал"після блоку"Бази даних"

**Фактичний результат:** Відсутній блок "Бази даних. Додатковий матеріал"
**Очікуваний результат:** Присутній блок "Бази даних. Додатковий матеріал"

**Додаткова інформація:** https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_23](https://user-images.githubusercontent.com/109720075/209839658-66f2e82c-77a2-4dc3-9d36-72c1751362f3.png)
![Screenshot_24](https://user-images.githubusercontent.com/109720075/209839665-9227711f-21d7-44d4-9b68-0051cc29b1c0.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в Кроках для відтворення не потрібно вказувати очікувані результати. Вказуємо тільки дії які потрібно виконати для відтворення дефекту

**Comment by scholokov** [comment]
курс відправлено у архів
