### ISSUE TITLE
Home page-Матеріали-Quality Assurance Engineer (QA)-Блок "API"-відсутній рівень складності

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#357]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/
2.В Header-і сторінки клікнути на "Матеріали"
3.Вибрати Quality Assurance Engineer (QA) і клікнути на зображення Quality Assurance Engineer (QA)
4.Проскролити сторінку до блоку"API"
5.Звернути увагу на рівень складності в назві блоку"API"

**Фактичний результат:** Відсутній рівень складності
**Очікуваний результат:** Присутній рівень складності

**Додаткова інформація:** https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_25](https://user-images.githubusercontent.com/109720075/209840290-08c0f154-ed85-4b5b-854f-ffe765055143.png)
![Screenshot_26](https://user-images.githubusercontent.com/109720075/209840296-973bac23-0783-44f3-819b-769a87a2a551.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в Кроках для відтворення не потрібно вказувати очікувані результати. Вказуємо тільки дії які потрібно виконати для відтворення дефекту

**Comment by DmytroMarkulych** [comment]
@andry1729 вкажіть будь ласка назву зображення на яке клікнути в 3-му кроці

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
