### ISSUE TITLE
Home page-Матеріали-Quality Assurance Engineer (QA)-Блок ""API""-відсутній курс"REST, SOAP, API (Додатковий матеріал)"

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#358]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/
2.В Header-і сторінки клікнути на "Матеріали"
3.Вибрати Quality Assurance Engineer (QA) і клікнути на зображення
4.Проскролити сторінку до блоку"API"
5.Розгорнути блок "API"
6.Звернути увагу на курси

**Фактичний результат:** Відсутній курс"REST, SOAP, API (Додатковий матеріал)"
**Очікуваний результат:** Присутній курс"REST, SOAP, API (Додатковий матеріал)"

**Додаткова інформація:** https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_27](https://user-images.githubusercontent.com/109720075/209840998-ccc5fbf7-521c-417b-bee2-62244ca23033.png)
![Screenshot_28](https://user-images.githubusercontent.com/109720075/209841002-d12fb0b9-9db4-4c3c-8a75-5b7fc016720b.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в Кроках для відтворення не потрібно вказувати очікувані результати. Вказуємо тільки дії які потрібно виконати для відтворення дефекту

**Comment by GNatala** [comment]
Якщо курс "REST, SOAP, API (Додатковий матеріал)" відправлено у архів, то тоді його немає бути в вимогах або має бути примітка  *курс відправлено у архів.  

Чи коректніше закритий цей баг та завести новий на вимоги?

**Фактичний результат**: Присутній курс"REST, SOAP, API (Додатковий матеріал)" в вимогах
**Очікуваний результат:** Відсутній курс"REST, SOAP, API (Додатковий матеріал)" в вимогах

**Додаткова інформація:**
![image](https://user-images.githubusercontent.com/101987790/226905912-23fc6eee-4cfb-475f-8ae2-c32cee600591.png)

**Comment by DmytroMarkulych** [comment]
@scholokov як вважаєш?

**Comment by scholokov** [comment]
внесено зміни у вимоги
