### ISSUE TITLE
Home page-Матеріали-Quality Assurance Engineer (QA)-Блок "Підготовка до співбесіди"-відсутній рівень складності

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#359]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/
2.В Header-і сторінки клікнути на "Матеріали"
3.Вибрати Quality Assurance Engineer (QA) і клікнути на зображення Quality Assurance Engineer (QA)
4.Проскролити сторінку до блоку"Підготовка до співбесіди"
5.Звернути увагу на рівень складності в назві блоку"Підготовка до співбесіди"

**Фактичний результат:** Відсутній рівень складності
**Очікуваний результат:** Присутній рівень складності

**Додаткова інформація:** https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_29](https://user-images.githubusercontent.com/109720075/209841690-c3a617b0-5e39-4daf-b9aa-45dc7b41587d.png)
![Screenshot_30](https://user-images.githubusercontent.com/109720075/209841712-bf0c21eb-4bee-48a7-844c-6b2d1828d9fb.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в Кроках для відтворення не потрібно вказувати очікувані результати. Вказуємо тільки дії які потрібно виконати для відтворення дефекту

**Comment by DmytroMarkulych** [comment]
@andry1729 вкажіть, будь ласка, в 3-му кроці на яке саме зображення клікнути

**Comment by andry1729** [comment]
Змінив

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
