### ISSUE TITLE
Home page-Матеріали-Quality Assurance Engineer (QA)-Блок "Підготовка до співбесіди"-відсутній курс"Додаткові матеріали"

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#360]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/
2.В Header-і сторінки клікнути на "Матеріали"
3.Вибрати Quality Assurance Engineer (QA) і клікнути на зображення
4.Проскролити сторінку до блоку"Підготовка до співбесіди"
5.Розгорнути блок "Підготовка до співбесіди"
6.Звернути увагу на курси

**Фактичний результат:** Відсутній курс"Додаткові матеріали"
**Очікуваний результат:** Присутній курс"Додаткові матеріали"

**Додаткова інформація:** https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_31](https://user-images.githubusercontent.com/109720075/209842535-ab1a7dc7-71b6-4aa5-8ce8-34ae8b62761b.png)
![Screenshot_32](https://user-images.githubusercontent.com/109720075/209842541-acb0d8cc-10cc-4fb1-a6dd-3b4cb370ab3b.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в Кроках для відтворення не потрібно вказувати очікувані результати. Вказуємо тільки дії які потрібно виконати для відтворення дефекту

**Comment by scholokov** [comment]
виправлено у вимогах

**Comment by OlhaHutsman** [comment]
@DmytroMarkulych  не можу відтворити крок 2 .Де в хедері є  "Матеріали"?
![руфвук](https://user-images.githubusercontent.com/123729744/225891928-bf5891b2-fe21-470b-9a77-3d507c3e5430.png)

**Comment by DmytroMarkulych** [comment]
@OlhaHutsman Трішки змінилася структура сайту

**Comment by OlhaHutsman** [comment]
@DmytroMarkulych  verified
