### ISSUE TITLE
Наші Тренери-Dmytro Markulych-досвід роботи 4 років

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#361]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/trainers/
2.Проскролити сторінку до тренера Dmytro Markulych
3.Звернути увагу на досвід роботи

**Фактичний результат:** Досвід роботи 4 років
**Очікуваний результат:** Досвід роботи 4 роки

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_112](https://user-images.githubusercontent.com/109720075/209920717-aba86b4b-0f95-4680-85bc-d248c45b9599.png)

**Comment by scholokov** [comment]
fixed
