### ISSUE TITLE
Блок"Різні домени тестування"-курс"Особенности тестирования на различных платформах"-урок"Особенности тестирования на различных платформах"-назва на російській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#362]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/qa-program/
2.Проскролити сторінку до блоку "Різні домени тестування"
3.Розгорнути блок "Різні домени тестування"
4.Вибрати  курс"Особенности тестирования на различных платформах" та клікнути по ньому
5.Проскролити до уроку"Особенности тестирования на различных платформах"
6.Звернути увагу на назву уроку "Особенности тестирования на различных платформах"

**Фактичний результат:** Назва уроку "Особенности тестирования на различных платформах"
 на російській мові
**Очікуваний результат:** Назва уроку "Особливості тестування на різних платформах"на українській мові

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_113](https://user-images.githubusercontent.com/109720075/209922973-5e98f651-f789-4a5a-82de-777e62c7447c.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в Кроках для відтворення не потрібно вказувати очікувані результати. Вказуємо тільки дії які потрібно виконати для відтворення дефекту

**Comment by DmytroMarkulych** [comment]
@andry1729  В кроки 3 та 6 додайте назву блоку та назву курсу. В Очікуваний та Актуальний результати, додайте теж назву блоку. Таким чином, на кожному кроці не втрачається інформація про баг

**Comment by andry1729** [comment]
Змінив

**Comment by scholokov** [comment]
fixed
