### ISSUE TITLE
Блок"Різні домени тестування"-курс"Особенности тестирования на различных платформах"-урок"Особенности мобильного тестирования"-назва на російській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#363]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/qa-program/
2.Проскролити сторінку до блоку "Різні домени тестування"
3.Розгорнути блок "Різні домени тестування"
4.Вибрати курс"Особенности тестирования на различных платформах" та клікнути по ньому
5.Проскролити до уроку"Особенности мобильного тестирования"
6.Звернути увагу на назву уроку "Особенности мобильного тестирования"

**Фактичний результат:** Назва уроку "Особенности мобильного тестирования"
на російській мові
**Очікуваний результат:** Назва уроку "Особливості мобільного тестування"
на українській мові

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_114](https://user-images.githubusercontent.com/109720075/209923347-adfcc197-a94c-4dc4-8df3-0ca18de6c7f7.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в Кроках для відтворення не потрібно вказувати очікувані результати. Вказуємо тільки дії які потрібно виконати для відтворення дефекту

**Comment by DmytroMarkulych** [comment]
@andry1729  В кроки 3 та 6 додайте назву блоку та назву курсу. В Очікуваний та Актуальний результати, додайте теж назву блоку. Таким чином, на кожному кроці не втрачається інформація про баг

**Comment by andry1729** [comment]
Змінив

**Comment by scholokov** [comment]
fixed
