### ISSUE TITLE
Блок"Різні домени тестування"-курс"Особенности тестирования на различных платформах"-урок"Особенности тестирования десктопных приложений"-назва на російській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#364]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/qa-program/
2.Проскролити сторінку до блоку "Різні домени тестування"
3.Розгорнути блок "Різні домени тестування"
4.Вибрати курс"Особенности тестирования на различных платформах" та клікнути по ньому
5.Проскролити до уроку"Особенности тестирования десктопных приложений"
6.Звернути увагу на назву уроку

**Фактичний результат:** Назва на російській мові
**Очікуваний результат:** Назва на українській мові

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_115](https://user-images.githubusercontent.com/109720075/209923561-55848928-610a-40cb-a5e2-8ec136780361.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в Кроках для відтворення не потрібно вказувати очікувані результати. Вказуємо тільки дії які потрібно виконати для відтворення дефекту

**Comment by DmytroMarkulych** [comment]
@andry1729 вкажіть будь ласка в 3-му кроці назву блоку який має розгорнутися

**Comment by scholokov** [comment]
відсутня пряма лінка на курс

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_11](https://user-images.githubusercontent.com/109720075/210329527-81e7030f-2c24-4c93-a289-e36f602fc9e8.png)

**Comment by scholokov** [comment]
fixed
