### ISSUE TITLE
Блок"Різні домени тестування"-курс"Особенности тестирования на различных платформах"-урок"Тестирование игр"-назва на російській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#365]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/courses/platform-testing/
2.Проскролити до уроку"Тестирование игр"
3.Звернути увагу на назву уроку

**Фактичний результат:** Назва на російській мові
**Очікуваний результат:** Назва на українській мові

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_116](https://user-images.githubusercontent.com/109720075/209923829-6504b705-af6a-4285-a76c-91c3e56e7bb0.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в Кроках для відтворення не потрібно вказувати очікувані результати. Вказуємо тільки дії які потрібно виконати для відтворення дефекту

**Comment by DmytroMarkulych** [comment]
@andry1729 вкажіть будь ласка в 3-му кроці назву блоку

**Comment by scholokov** [comment]
треба вказати пряму лінку на урок

**Comment by andry1729** [comment]
Змінив
