### ISSUE TITLE
Блок"Різні домени тестування"-курс"Особенности тестирования на различных платформах"-урок"GameDev, Отличия тестирования игр от классических приложений"-назва на російській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#366]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/courses/platform-testing/
2.Проскролити до уроку"GameDev, Отличия тестирования игр от классических приложений"
3.Звернути увагу на назву уроку

**Фактичний результат:** Назва на російській мові
**Очікуваний результат:** Назва на українській мові

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_117](https://user-images.githubusercontent.com/109720075/209924142-f2233fc7-30d9-43d0-8f5f-690b3cacfe6f.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в Кроках для відтворення не потрібно вказувати очікувані результати. Вказуємо тільки дії які потрібно виконати для відтворення дефекту

**Comment by DmytroMarkulych** [comment]
@andry1729 вкажіть будь ласка в 3-му кроці назву блоку

**Comment by scholokov** [comment]
потрібно вказати пряму лінку на урок

**Comment by scholokov** [comment]
fixed
