### ISSUE TITLE
Check the Ukrainian content of the lesson "Jira"

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#369]
We need to check the Ukrainian content of the lesson "Jira"
Production environment: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/jira/
Old russian content: https://portal.qax-camp.com.ua/courses/qa-basic-programs/lessons/jira-%d1%81%d0%be%d0%b7%d0%b4%d0%b0%d0%bd%d0%b8%d0%b5-%d0%b7%d0%b0%d0%b4%d0%b0%d1%87%d0%b8-%d0%b1%d0%b0%d0%b3%d0%b8/
Requirements: https://github.com/scholokov/qax-portal-2/wiki
![Jira](https://user-images.githubusercontent.com/109460500/209966928-b4c29a17-4e5f-4c2f-aff6-0d0538e4399b.png)

**Comment by BatalovaOlha** [comment]
Заасайнила на себе
