### ISSUE TITLE
Home - Implement block Cards

### ISSUE THREAD

**Issue by ABatalov** [scholokov/qax-portal-2#37]
We need to implement block Cards:
https://portal.qax-camp.com.ua/

![image](https://user-images.githubusercontent.com/22824947/185736772-76915746-c5fe-493b-9920-fd7d7be5ff0f.png)
Here is Figma: 
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A22

Requirements: 
You should use custom blocks for this card, we need to make changes in this block easy in future)

**Comment by poroskundenys** [comment]
@scholokov тут ссылка должна быть?

**Comment by scholokov** [comment]
так, блок зліва являється активним, тобто ссилкою

**Comment by scholokov** [comment]
добре зробити так, щоб це не було важким процессом (додавання наступних блоків)
@poroskundenys

**Comment by poroskundenys** [comment]
Новые блоки через эту кнопку добавляются. https://prnt.sc/epxnO6uqgT6I. Сам блок называется Cards https://prnt.sc/5Q3SB_yo-Qov

**Comment by dmitryylev** [comment]
verified
