### ISSUE TITLE
Check the Ukrainian content of the lesson "TMS"

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#371]
We need to check the Ukrainian content of the lesson "TMS"
Production environment: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/tms/
Old russian content: https://portal.qax-camp.com.ua/courses/qa-basic-programs/lessons/tms/
Requirements: https://github.com/scholokov/qax-portal-2/wiki
![TMS](https://user-images.githubusercontent.com/109460500/209968672-83a1efa1-1d75-4380-a0c5-24a66fdeb315.png)

**Comment by BatalovaOlha** [comment]
#436
