### ISSUE TITLE
Check the Ukrainian content of the lesson "Zephyr Scale"

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#372]
We need to check the Ukrainian content of the lesson "Zephyr Scale"
Production environment: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/zephyr-scale-tm4j-basics/
Old russian content: https://portal.qax-camp.com.ua/courses/qa-basic-programs/lessons/zephyr-scale-tm4j-basics/
Requirements: https://github.com/scholokov/qax-portal-2/wiki
![Zephyr Scale](https://user-images.githubusercontent.com/109460500/209969184-fc8d5a06-e116-4387-b3cd-c572819be518.png)

**Comment by KaterinaNimenko35** [comment]
Verified
