### ISSUE TITLE
Check the Ukrainian content of the lesson "TestRail"

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#373]
We need to check the Ukrainian content of the lesson "TestRail"
Production environment: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/testrail/
Old russian content: https://portal.qax-camp.com.ua/courses/qa-basic-programs/lessons/testrail-2/
Requirements: https://github.com/scholokov/qax-portal-2/wiki
![TestRail](https://user-images.githubusercontent.com/109460500/209969803-cfd384f4-601e-4628-bde7-bc97f12ad981.png)

**Comment by Nadiyk** [comment]
Verifide
