### ISSUE TITLE
Курс"Рекомендована література"- відсутній опис курсу

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#374]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/courses/%d1%80%d0%b5%d0%ba%d0%be%d0%bc%d0%b5%d0%bd%d0%b4%d0%be%d0%b2%d0%b0%d0%bd%d0%b0-%d0%bb%d1%96%d1%82%d0%b5%d1%80%d0%b0%d1%82%d1%83%d1%80%d0%b0/
2.Звернути увагу на опис курсу

**Фактичний результат:** Відсутній опис курсу
**Очікуваний результат:** Присутній опис курсу

**Додаткова інформація:** https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_12](https://user-images.githubusercontent.com/109720075/210077263-5c3be832-99aa-4984-821e-f7a44d863b2c.png)
![Screenshot_13](https://user-images.githubusercontent.com/109720075/210077338-4ff62fbd-e37a-48f0-a0a8-a498afe7cb55.png)

**Comment by scholokov** [comment]
видалено, як окремий курс. додано у вигляді уроків у загальний курс

**Comment by OlhaHutsman** [comment]
@scholokov  Закривати як Canceled  в такому випадку?

**Comment by scholokov** [comment]
так
