### ISSUE TITLE
Курс"Програми для QA"- відсутній опис курсу

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#375]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/courses/qa-basic-programs/
2.Звернути увагу на опис курсу

**Фактичний результат:** Відсутній опис курсу
**Очікуваний результат:** Присутній опис курсу

**Додаткова інформація:** https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_12](https://user-images.githubusercontent.com/109720075/210078028-ea103a12-d575-42d5-8360-2dd00b3a3647.png)
![Screenshot_14](https://user-images.githubusercontent.com/109720075/210078030-fc212786-8ee1-42df-adb8-7db18d75f1b8.png)

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
