### ISSUE TITLE
Курс"Рекомендована література"- відсутній опис курсу

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#377]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/courses/books-processes/
2.Звернути увагу на опис курсу

**Фактичний результат:** Відсутній опис курсу
**Очікуваний результат:** Присутній опис курсу

**Додаткова інформація:** https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_12](https://user-images.githubusercontent.com/109720075/210078466-b686218a-a1c8-4c96-b6ca-f9c2b6a22eac.png)
![Screenshot_16](https://user-images.githubusercontent.com/109720075/210078470-413919f6-ace4-485d-8f82-26e88f121824.png)

**Comment by scholokov** [comment]
курс з'єднано з базовим курсом QA

**Comment by GNatala** [comment]
passed
