### ISSUE TITLE
Курс"Особенности тестирования на различных платформах"- відсутній опис курсу

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#378]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/courses/platform-testing/
2.Звернути увагу на опис курсу

**Фактичний результат:** Відсутній опис курсу
**Очікуваний результат:** Присутній опис курсу

**Додаткова інформація:** https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_12](https://user-images.githubusercontent.com/109720075/210078694-099474a7-2d33-4774-8d88-30eb1563f32c.png)
![Screenshot_17](https://user-images.githubusercontent.com/109720075/210078698-002d07ff-e0a1-4173-bc7e-4bed156c9bf5.png)

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
