### ISSUE TITLE
Курс"UI"- відсутній опис курсу

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#379]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/courses/ui/
2.Звернути увагу на опис курсу

**Фактичний результат:** Відсутній опис курсу
**Очікуваний результат:** Присутній опис курсу

**Додаткова інформація:** https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_12](https://user-images.githubusercontent.com/109720075/210079030-b2985e28-d118-4ec2-a0b6-f2437eb7cd5a.png)
![Screenshot_18](https://user-images.githubusercontent.com/109720075/210079031-b9a8ba71-ad38-43b8-b12b-dbc6cd1b4fa2.png)

**Comment by scholokov** [comment]
Please retest to update the current status

**Comment by DmitriiNasonov** [comment]
retested. "UI" course has been deleted. bug-report isn't actual
