### ISSUE TITLE
Курс"Основи SQL"- відсутній опис курсу

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#380]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/courses/basics-of-sql/
2.Звернути увагу на опис курсу

**Фактичний результат:** Відсутній опис курсу
**Очікуваний результат:** Присутній опис курсу

**Додаткова інформація:** https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_12](https://user-images.githubusercontent.com/109720075/210079405-6093cff2-4034-4d03-95bc-912eb597cf46.png)
![Screenshot_19](https://user-images.githubusercontent.com/109720075/210079410-1d6688a5-6132-4d9e-801d-f14e0124afdb.png)

**Comment by scholokov** [comment]
курс переведоно у архів
неактуально

**Comment by GNatala** [comment]
Курс "Основи SQL" є актуальним на сайті: https://www.qax-camp.com.ua/courses/basics-of-sql/
і в вимогах п.11: https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81

**Comment by GNatala** [comment]
An issue is reproduced.
Фактичний результат: Відсутній опис курсу
Очікуваний результат: Присутній опис курсу
![image](https://user-images.githubusercontent.com/101987790/232508274-fe650ed5-e157-4ad9-a8b2-6ac23c744dae.png)

**Comment by DmytroMarkulych** [comment]
@GNatala даний дефект не актуальний
