### ISSUE TITLE
Рекомендована література-блок під назвою курсу- колір тексту "Обрати цей курс" #fff

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#381]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/courses/%d1%80%d0%b5%d0%ba%d0%be%d0%bc%d0%b5%d0%bd%d0%b4%d0%be%d0%b2%d0%b0%d0%bd%d0%b0-%d0%bb%d1%96%d1%82%d0%b5%d1%80%d0%b0%d1%82%d1%83%d1%80%d0%b0/
2.Проскролити до блоку під назвою курсу
2.Звернути увагу на колір тексту "Обрати цей курс"

**Фактичний результат:** Колір тексту "Обрати цей курс" #fff
**Очікуваний результат:** Колір тексту "Обрати цей курс" #728188

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_20](https://user-images.githubusercontent.com/109720075/210082736-2ab728c4-8e4e-4334-9579-8c08e8616f8e.png)

**Comment by scholokov** [comment]
курс видалено

**Comment by GNatala** [comment]
passed
