### ISSUE TITLE
Рекомендована література-блок під назвою курсу- колір тексту "Обрати цей курс" #fff

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#383]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/courses/books-processes/
2.Проскролити до блоку під назвою курсу
2.Звернути увагу на колір тексту "Обрати цей курс"

**Фактичний результат:** Колір тексту "Обрати цей курс" #fff
**Очікуваний результат:** Колір тексту "Обрати цей курс" #728188

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_22](https://user-images.githubusercontent.com/109720075/210083505-d1e4f720-ec17-442c-87f9-e153e74901c4.png)

**Comment by scholokov** [comment]
курс видалено

**Comment by GNatala** [comment]
passed
