### ISSUE TITLE
UI-відсутній блок з "Current Status,Price,Get Started" під назвою курсу

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#384]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/courses/ui/
2.Проскролити до назви курсу
2.Звернути увагу на блок з "Current Status,Price,Get Started"

**Фактичний результат:** Відсутній блок
**Очікуваний результат:** Блок присутній

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_23](https://user-images.githubusercontent.com/109720075/210084983-fa0939d4-8aca-4bc0-8d32-203f21ab0c94.png)
![Screenshot_24](https://user-images.githubusercontent.com/109720075/210084985-711e28bb-ff86-4776-9446-96db47ff7170.png)

**Comment by scholokov** [comment]
блок вітсутній, тому що в тебе вже є доступ до цього курсу

**Comment by GNatala** [comment]
passed
