### ISSUE TITLE
UI- назви уроків на російській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#385]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/courses/ui/
2.Проскролити до уроків курсу
2.Звернути увагу на назви  уроків

**Фактичний результат:** Назви уроків на російській мові
**Очікуваний результат:** Назви уроків на українській  мові

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_25](https://user-images.githubusercontent.com/109720075/210086274-98c88b91-660c-465a-b781-a098e85d015f.png)

**Comment by scholokov** [comment]
fixed
