### ISSUE TITLE
UI-Что такое Viewport-опис уроку на російській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#386]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/courses/ui/lessons/viewport/
2.Проскролити до опису уроку
2.Звернути увагу на опис уроку

**Фактичний результат:** Опис уроку на російській мові
**Очікуваний результат:** Опис уроку на українській мові

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_26](https://user-images.githubusercontent.com/109720075/210086629-30fd8d75-53d4-4127-bb87-f520990ee5e0.png)
![Screenshot_27](https://user-images.githubusercontent.com/109720075/210086632-a213c414-df08-4617-be7a-43913c2a01c7.png)

**Comment by scholokov** [comment]
fixed
