### ISSUE TITLE
UI-Параметры Экрана-опис уроку на російській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#387]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/courses/ui/lessons/screens/
2.Проскролити до опису уроку
2.Звернути увагу на опис уроку

**Фактичний результат:** Опис уроку на російській мові
**Очікуваний результат:** Опис уроку на українській мові

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_28](https://user-images.githubusercontent.com/109720075/210086858-dbec3301-ce0f-4cbf-b371-795224454294.png)

**Comment by scholokov** [comment]
fixed
