### ISSUE TITLE
Content - in the text of the description lesson "Jira", tautology - the word "найрізноманітніших" is used twice 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#388]
**STR**
1. Open https://www.qax-camp.com.ua/
2. Login 
3. Go to the page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/jira/
4. Pay attention to the block description.

**ACTUAL RESULT**
In the one text (different phrases) twice used word "найрізноманітніших" is incorrect in the Ukrainian language.

**EXPECTED RESULT**
On of the word "найрізноманітніших" should be changed for - "різних / різноманітних"

NOTE:
For example, the text sounds like this:

Jira Software входить до сімейства продуктів, розроблених з метою спростити управління робочим процесом для **_різних_** команд. Спочатку система Jira створювалася як рішення для відстеження завдань та помилок. Але сьогодні Jira – це потужний інструмент управління роботою, що підходить для найрізноманітніших випадків, від управління вимогами і сценаріями тестування до agile-розробки програмного забезпечення.
 
![CPq9MW4tPz](https://user-images.githubusercontent.com/109384052/210086942-280c40fe-6b8c-4350-8d0c-e190e9f01d71.png)

**Comment by BatalovaOlha** [comment]
#369

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
Resolved
