### ISSUE TITLE
HR - Розробити картку для напрямку HR

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#39]
Розробити картку для напрямку HR

вона піде в даний блок:
![image](https://user-images.githubusercontent.com/22824947/185733660-e0f54a9d-1372-48de-a170-5a73ecfa35c1.png)

як варіан, перегрупувати картки по принципу 3+2 (зараз вони 4 в ряд)

**Comment by scholokov** [comment]
outdated requirements
@ABatalov

**Comment by ButKoff** [comment]
no actual
