### ISSUE TITLE
Рекомендована література-Link складається з англійських та українських букв 

### ISSUE THREAD

**Issue by andry1729** [scholokov/qax-portal-2#390]
**Кроки відтворення:**
1.Відкрити сторінку https://www.qax-camp.com.ua/qa-program/
2.Розгорнути блок"Теорія тестування. Базовий рівень"
3.Клікнути на курс "Рекомендована література"
4.Звернути увагу на Link

**Фактичний результат:** Link складається з англійських та українських букв 
**Очікуваний результат:** Link складається з  англійських літер та/або цифр

**Додаткова інормація :** https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_30](https://user-images.githubusercontent.com/109720075/210088400-97e1d7a4-eb34-4bce-a744-a6aaeb44490a.png)
![Screenshot_31](https://user-images.githubusercontent.com/109720075/210088403-b1962061-f6a0-48a0-824a-9a7932cd4eef.png)

**Comment by scholokov** [comment]
потрібно вказати лінку на курс

**Comment by andry1729** [comment]
![Screenshot_31](https://user-images.githubusercontent.com/109720075/210088403-b1962061-f6a0-48a0-824a-9a7932cd4eef.png)
Ось пряма лінка https://www.qax-camp.com.ua/courses/%d1%80%d0%b5%d0%ba%d0%be%d0%bc%d0%b5%d0%bd%d0%b4%d0%be%d0%b2%d0%b0%d0%bd%d0%b0-%d0%bb%d1%96%d1%82%d0%b5%d1%80%d0%b0%d1%82%d1%83%d1%80%d0%b0/

**Comment by scholokov** [comment]
fixed
