### ISSUE TITLE
Content - no punctuation marks ";" in the paragraph "Опис полів" - subparagraph "Description" - lesson "Jira"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#391]
**STR**

1. Open https://www.qax-camp.com.ua/;
2. Login;
3. Go to the page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/jira/;
4. Pay attention to the block "Опис полів" - subparagraphs "Description".

**ACTUAL RESULT**
In the subparagraphs "Description" paragraph "Опис полів" there are NO punctuation marks ";" at the end of phrases. 

**EXPECTED RESULT**
In the subparagraphs "Description" paragraph "Опис полів" there are punctuation marks ";" at the end of phrases. 

![aLU58YJMnR](https://user-images.githubusercontent.com/109384052/210089128-420de596-6f8c-4747-85da-1410a0fa272e.png)

**Comment by BatalovaOlha** [comment]
#369

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
resolved
