### ISSUE TITLE
Content - from great letters words after dashes in the block "Опис полів"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#392]
**STR**

1. Open https://www.qax-camp.com.ua/;
2. Login;
3. Go to the page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/jira/;
4. Pay attention to the block "Опис полів".

**ACTUAL RESULT**
Text in the block  "Опис полів" after dashes shown from great letters.

**EXPECTED RESULT**
Text in the block  "Опис полів" after dashes shown from small letters.

![DEtpFbx05l](https://user-images.githubusercontent.com/109384052/210090855-30d905b8-22f0-40e4-80aa-7d8e73c419bc.png)

![afas1y1OdC](https://user-images.githubusercontent.com/109384052/210090865-c1be93b4-7e2f-4e59-b1c8-7b405b61542c.png)

**Comment by BatalovaOlha** [comment]
#369

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha це швидше переклад назви артефакту, тому вони із великих літер

**Comment by BatalovaOlha** [comment]
@DmytroMarkulych , але ж це не власне ім'я, що має українською писатись з великої літери, це просто переклад. Тому на мою думку логічніше це написати з малої...

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha 
додайте будь ласка наступні атрибути 

![Image](https://user-images.githubusercontent.com/88647733/214506662-630c9e69-328c-42aa-a672-f3d9052a39ce.png)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
Resolved
