### ISSUE TITLE
Content -word "завдання" out of context  in the block "Переведення Задачі/Багу по статусам" - lesson "Jira" 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#396]
**STR**

1. Open https://www.qax-camp.com.ua/
2. Login
3. Go to the page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/jira/
4. Scroll to the block  "Переведення Задачі/Багу по статусам" 
5. Pay attention to the block name and text 

**ACTUAL RESULT**
Name of the phrase "Переведення **Задачі**/Багу по статусам" not the same as that in the text "**завдання/**баг "

**EXPECTED RESULT**
The name of the phrase "Переведення Задачі/Багу по статусам" is the same as in the block context 

NOTE:
Якщо в назві іде мова про Задачу/баг, то по тексту потрібно використовувати тіж самі значення, тому доцільно буде виправити контекст наступним чином:

"Після створення, задача/баг потрапляє у статус Backlog. Для того щоб перевести задачі в інші статуси необхідно змінити поле Status задачі/багу ([пересування відбувається згідно з встановленим Workflow](https://www.qax-camp.com.ua/jira-moving-statuses/#workflow))"

![MCgZMMxD4h](https://user-images.githubusercontent.com/109384052/210173797-c0d7bdc5-6513-417a-b201-f8d216575ddb.png)

**Comment by BatalovaOlha** [comment]
#369

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha Давайте перфразуємо Summary таким чином, щоб не використовувати слово "incorrect"

**Comment by BatalovaOlha** [comment]
змінила

**Comment by BatalovaOlha** [comment]
змінила

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
![nCwxNjGrr7](https://user-images.githubusercontent.com/109384052/211868410-247dfa3c-3f5e-4cb1-a820-cbe5e1f1d762.png)


Все ще актуально:
"Після створення, задача/баг потрапляє у статус Backlog. Для того щоб перевести задачі в інші статуси необхідно змінити поле Status задачі/багу ([пересування відбувається згідно з встановленим Workflow](https://www.qax-camp.com.ua/jira-moving-statuses/#workflow))"

**Comment by scholokov** [comment]
виправив у багатьох місцях. є сенс перевірити заново

**Comment by BatalovaOlha** [comment]
Resolved
