### ISSUE TITLE
Content - grammatical error in the word "Шаринг" - step 4 - lesson Jira

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#397]
**STR**

1. Open https://www.qax-camp.com.ua/
2. Login
3. Go to the page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/jira/
4. Scroll to block 4 "Шаринг"
5. Pay attention to the block name

**ACTUAL RESULT**
Name of the step 4 "Шаринг" is the wrong transliteration of the word "Sharing"

**EXPECTED RESULT**
Name of the step 4 should be "Шеринг"

![VqhwQJhUoV](https://user-images.githubusercontent.com/109384052/210180519-94aa7f0e-1e1a-4e42-a528-8b46cc334eaa.png)

**Comment by BatalovaOlha** [comment]
#369

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha в описі дефекту краще не використовувати слова типу "некоректно", це загальні назви

**Comment by BatalovaOlha** [comment]
changed

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
:) resolved
