### ISSUE TITLE
Course "Програми для QA" - Lesson "Zephyr Scale (TM4J)" - Lesson description missing

### ISSUE THREAD

**Issue by KaterinaNimenko35** [scholokov/qax-portal-2#399]
**Steps to reproduce:**

1. Open page https://www.qax-camp.com.ua/courses/qa-basic-programs/
2. Scroll down the page to the lesson "Zephyr Scale (TM4J)"

**Actual result:**
Lesson description is missing

**Expected result:**
Lesson description is present

**Notes:**
Requirements
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA

**Environment:**
Desktop/W10/Google Chrome 101.0.4951.67 (64-bit) 1920х1080

![2023-01-02 10 00 51](https://user-images.githubusercontent.com/105543094/210208463-e8865e15-28a8-4b1e-99ed-ed79dde44a9d.png)

![2023-01-02 10 29 00](https://user-images.githubusercontent.com/105543094/210208485-5fafe54e-ebc1-43cc-b480-0793d8bfe801.png)

**Comment by KaterinaNimenko35** [comment]
#372

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
passed
