### ISSUE TITLE
Main - Історія успіху

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#40]
Основна сторінка:
https://portal.qax-camp.com.ua/

Імплементувати блок "Історія успіху"
![image](https://user-images.githubusercontent.com/22824947/185736744-92619778-8f46-4603-b9f2-023fb161fa78.png)

дизайн:
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A22

Кнопка "Дивитися усіх" повинна розкривати повний список. 
Подібний функціонал можна подивитися на 
qax-camp.com.ua

**Comment by KaterinaNimenko35** [comment]
verified
