### ISSUE TITLE
Course "Програми для QA" - Курс Content - Lesson card "Zephyr Scale (TM4J)" - Topics dropdown list is missing

### ISSUE THREAD

**Issue by KaterinaNimenko35** [scholokov/qax-portal-2#400]
**Steps to reproduce:**

1. Open page https://www.qax-camp.com.ua/courses/qa-basic-programs/
2. Scroll down the page to the lesson "Zephyr Scale (TM4J)"
3. Pay attention to the lesson card

**Actual result:**
Topics dropdown list is missing

**Expected result:**
Topics dropdown list is present

**Notes:**
Requirements
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA

Task #46 
 

**Pay attention, the lesson "Zephyr Scale (TM4J)" contains 8 topics**

**Environment:**
Desktop/W10/Google Chrome 101.0.4951.67 (64-bit) 1920х1080

![2023-01-02 10 00 51](https://user-images.githubusercontent.com/105543094/210223094-013abde5-a2d3-4aee-8e49-4d292d6d1829.png)

![2023-01-02 152 5733 00](https://user-images.githubusercontent.com/105543094/211152015-461c433a-39c3-4b02-8e75-3fa463417f81.png)

**Comment by KaterinaNimenko35** [comment]
#372

**Comment by scholokov** [comment]
контент же на месте... просто изменилось отображение. непонятно на чем основан баг

**Comment by KaterinaNimenko35** [comment]
@scholokov  опис виправила, маю на увазі відсутність випадаючого списку з топіками в картці уроку. Згідно з задачею #46 , якщо урок містить топіки або тести, це повинно відображатися у випадаючому списку картки уроку.

**Comment by scholokov** [comment]
@KaterinaNimenko35 наразі - він їх не має. все перешло у тіло уроку

**Comment by KaterinaNimenko35** [comment]
@scholokov 
1. Баг можу перемістити в Canceled як неактуальний?
2. Випадаючий список не буде відображати топіки, чи це тимчасово?

**Comment by scholokov** [comment]
@KaterinaNimenko35 
1. так
2. випадаючий список буде відображати топіки, просто тут не буде топіків. матеріал переїхав з них у сам урок

**Comment by KaterinaNimenko35** [comment]
issue is not relevant
