### ISSUE TITLE
Extra space space between the exclamation mark and equals "! =" - block "Filters, Bulk Tasks Edit" - phrase 2 - paragraph 1 "Приклади"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#402]
**STR**

1. Open https://www.qax-camp.com.ua/;
2. Login;
3. Go to the page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/jira/;
4. Scroll to the phrase 2 paragraph 1 "Приклади" in the block "Filters, Bulk Tasks Edit": 

**ACTUAL RESULT**
Between the exclamation mark and equals "! =" is extra space

**EXPECTED RESULT**
Phrase 2 paragraph 1 "Приклади" should be "У даному прикладі виведено всі статуси КРІМ “Resolved” (**!=** В даному випадку означає заперечення)".

![9Pc09i4CfM](https://user-images.githubusercontent.com/109384052/210267771-ef4992b3-b7f9-4390-9d9f-2d180742c6fd.png)

**Comment by BatalovaOlha** [comment]
#369

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
Resolved
