### ISSUE TITLE
The text wrap sign is moved to the text on the mobile version of the screen - lesson Jira

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#403]
**STR**

1. Open https://www.qax-camp.com.ua/, you need the screen size (360x740 / 375x667) 
2. Login;
3. Go to the page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/jira/;

**ACTUAL RESULT**
In the mobile screen, the text wrap sign is moved _to the text_ on the mobile version of the screen

**EXPECTED RESULT**
The text wrap mark _is next_ to the text in any screen size. 

![i5mpEG5r1S](https://user-images.githubusercontent.com/109384052/210271839-a9451368-e2d7-430f-a83e-9a8c3e8a3db9.png)
![HcgvPQd7w0](https://user-images.githubusercontent.com/109384052/210271844-e97e570a-5cea-4638-8171-f07b8026dcb3.png)

**Comment by BatalovaOlha** [comment]
#369

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha 4-й крок можна винести як умову

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha я про те, що можна вказати як "Precondition: Screen 360x740", як окремим пунктом

**Comment by scholokov** [comment]
помилка в іншому
глянь як це реалізовано у фігмі
