### ISSUE TITLE
Content - word "При **закладі** бага" should be changed for another ukrainian word in the phrase- block "Создание бага" - lesson GitHub

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#405]
**STR**

1. Open https://www.qax-camp.com.ua/;
2. Login;
3. Go to the page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/github/
4. Scroll to the block "How To Create a Bug?" and pay attention to the 3d phrase block "Создание бага"

**ACTUAL RESULT**
3d phrase is with grammatical error and look like "При **закладі** бага обов’язкові до заповнення всі поля відмічені зірочкою:"

**EXPECTED RESULT**
Correct phrase will be better - "При **створенні** бага обов’язкові до заповнення всі поля відмічені зірочкою:"

![9Yt6l4iwo5](https://user-images.githubusercontent.com/109384052/210344311-5b35f3fd-d63e-43cc-9f3e-aa9639f2aecc.png)

**Comment by BatalovaOlha** [comment]
#370

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha в Summary краще не вказувати "not correct" - це є загальна фраза

**Comment by BatalovaOlha** [comment]
changed

**Comment by scholokov** [comment]
fixed

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha додайте, будь ласка, скрін дефекту, що відтворюється

**Comment by BatalovaOlha** [comment]
ця задача закрита на старій дошці, скрін в мене відображається
