### ISSUE TITLE
GitHub Wiki - Form "Записатися" - Requirements for the "Slider" design element is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#406]
**Steps of reproducing**
1. Open https://github.com/scholokov/qax-portal-2/wiki/1.5.-Form
2. Scroll to field "Коментар"

**Actual Result**
Requirements for the "Slider" design element is missing

**Expected Result**
 Requirements for the "Slider" design element is present

**Notes**
The desired design element is marked on the first screenshot

**Enviroments**
Windows 10, Chrome 108.0.5359.125 (64 bit)
![long-travel live - Google Chrome 03 01 2023 16_56_03](https://user-images.githubusercontent.com/95171672/210382123-ccd5cc00-f76e-48c8-b59d-9dbf019bf58e.png)
![1 5  Form · scholokov_qax-portal-2 Wiki - Google Chrome 03 01 2023 17_20_36](https://user-images.githubusercontent.com/95171672/210386867-f36ac66f-4f6e-4d63-881a-ed44b0981375.png)

**Comment by DmitriiNasonov** [comment]
Canceled

**Comment by ButKoff** [comment]
#291
