### ISSUE TITLE
GitHub Wiki - Requarements to Phone number - Operator code consists 3 numbers

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#407]
**Steps of reproducing:**
1. Open https://github.com/scholokov/qax-portal-2/wiki/1.5.-Form
2. Scroll to Requarements to Phone number
3. Pay attention to the number of numbers in the operator code

**Actual Result**
Operator code consists 3 numbers (ZZZ)

**Expected Result**
Operator code consists 2 numbers (ZZ)

**Enviroments**
Windows 10, Chrome 108.0.5359.125 (64 bit)
![1 5  Form · scholokov_qax-portal-2 Wiki - Google Chrome 03 01 2023 18_04_01](https://user-images.githubusercontent.com/95171672/210395085-d0b38837-b826-46ca-853b-7d5952537798.png)

**Comment by DmytroMarkulych** [comment]
@DmitriiNasonov вкажіть будь ласка тег, що це дефект в документації

**Comment by ButKoff** [comment]
#291

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
verified.  bug isn't reproducing
