### ISSUE TITLE
GitHub Wiki - Requarements to Phone number - Abonent code consists 6 numbers

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#408]
**Steps of reproducing:**
1. Open https://github.com/scholokov/qax-portal-2/wiki/1.5.-Form
2. Scroll to Requarements to Phone number
3. Pay attention to the number of numbers in the abonent code

**Actual Result**
Abonent code consists 6 numbers (XX-XX-XX)

**Expected Result**
Abonent code consists 7 numbers (XXX-XX-XX)

**Enviroments**
Windows 10, Chrome 108.0.5359.125 (64 bit)
![1 5  Form · scholokov_qax-portal-2 Wiki - Google Chrome 03 01 2023 18_14_28](https://user-images.githubusercontent.com/95171672/210397042-e3ebfd22-d037-4634-bae3-cc2bf0a44d79.png)

**Comment by DmytroMarkulych** [comment]
@DmitriiNasonov вкажіть, будь ласка, що це дефект в документації

**Comment by ButKoff** [comment]
#291

**Comment by ABatalov** [comment]
Fixed https://github.com/scholokov/qax-portal-2/wiki/1.5.-Form

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
