### ISSUE TITLE
Main Menu - Дизайн

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#41]
Імплементувати дизайн главного меню

![image](https://user-images.githubusercontent.com/22824947/185741812-0ed753b1-a4e7-4e85-b891-e35dfa6eb158.png)

фігма:
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A22

**Comment by KaterinaNimenko35** [comment]
Надайте будь ласка роз'яснення:

1. імплементувати дизайн головного меню **Зареєстрованого користувача**
2. імплементувати дизайн головного меню **Незареєстрованого користувача**

**Comment by scholokov** [comment]
https://github.com/scholokov/qax-portal-2/wiki/%D0%A0%D0%BE%D0%BB%D0%B5%D0%B2%D0%B0-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0

**Comment by KaterinaNimenko35** [comment]
verified
