### ISSUE TITLE
Home - Form "Записатися" - "Email" field allows the use of the email address format "username@ukr.net"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#411]
**Steps of reproducing:**
1. Open https://portal.qax-camp.com.ua/
2. Scroll to Form "Записатися"
3. Fill in the field "Name"
4. Enter the email address in the "Email" field in the format "username@ukr.net"
5. Put a check in checkbox
6. Press button "Записатися"

**Actual Result**
Message sent. You don't see the error message

**Expected Result**
Message not sent. You see an error message: "Невірний формат email адреси. Правильний формат: username@gmail.com"

**Enviroments**
Windows 10, Chrome 108.0.5359.125 (64 bit)

![210610375-567cccec-43ab-4f08-a6ee-637cd7cd1ae4](https://user-images.githubusercontent.com/95171672/213138638-6ef97917-47a0-4515-85cd-6ff86676d133.png)

**Comment by DmytroMarkulych** [comment]
@DmitriiNasonov не дуже можу зрозуміти в чому проблема?

**Comment by ButKoff** [comment]
#291

**Comment by DmitriiNasonov** [comment]
canceled
