### ISSUE TITLE
Content - grammatical error in phrase "про багу" - block "How To Create a Bug?" / "Description" - lesson GitHub

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#412]
**STR**

1. Open https://www.qax-camp.com.ua/;
2. Login;
3. Go to the page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/github/
4. Scroll to the block "How To Create a Bug?" / "Description" and pay attention to the end of the phrase.

**ACTUAL RESULT**
There is an extra letter in the word "про" in the sentence "сюди пишемо степи і вказуємо всю необхідну інформацію **про** багу"

**EXPECTED RESULT**
The phrase should be "Description – сюди пишемо степи і вказуємо всю необхідну інформацію **по** багу"

![p8CL3gvcS3](https://user-images.githubusercontent.com/109384052/210747142-16b79781-ae26-47b5-b5ae-d2e29462b7b8.png)

**Comment by BatalovaOlha** [comment]
#370

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
resolved
