### ISSUE TITLE
Content - grammatical error in phrase "дозволяє асайнірувати кілька людей відразу." - block "How To Create a Bug?" / "Assignees" - lesson GitHub

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#413]
**STR**

1. Open https://www.qax-camp.com.ua/;
2. Login;
3. Go to the page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/github/
4. Scroll to the block "How To Create a Bug?" / "Assignees" and pay attention to the word " асайнірувати".

**ACTUAL RESULT**
The word "асайнірувати" is the wrong transliteration of the word "assign"

**EXPECTED RESULT**
The phrase should be "GitHub дає змогу асайнити кількох людей відразу"

**NOTE**:

_Цю фразу можна зробити двома варіантами:_

1. GitHub дає змогу асайнити кількох людей відразу.
2. GitHub дає змогу заасайнити на декількох людей відразу. 

![igbL9NylkM](https://user-images.githubusercontent.com/109384052/210752211-5119d0ae-fab9-4e7b-9694-48f17d6e17c4.png)

**Comment by BatalovaOlha** [comment]
#370

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
resolved

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha додайте скрін дефекту, що відтворився

**Comment by BatalovaOlha** [comment]
@DmytroMarkulych ця задача теж вже в резолвді на старій дошці і скрін в мене відображається
