### ISSUE TITLE
Content - grammatical error in phrase "вибираєте з списку" - block "How To Create a Bug?"/"Milestone" - lesson GitHub

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#414]
**STR**

1. Open https://www.qax-camp.com.ua/;
2. Login;
3. Go to the page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/github/
4. Scroll to the block How To Create a Bug? / Milestone and pay attention to the preposition "з" at the end of the phrase

**ACTUAL RESULT**
The preposition "з" is the wrong usage in the Ukrainian language 

**EXPECTED RESULT**
The preposition should be changed to "зі" and all phrase sound like  "...вказуєте поточний спринт, теж вибираєте зі списку".

![QUJuaq5WIP](https://user-images.githubusercontent.com/109384052/210755955-6ff09af6-a451-467f-b5c1-e06f5681fedc.png)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
resolved

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha додайте будь ласка скрін

**Comment by BatalovaOlha** [comment]
@DmytroMarkulych, скрін багу є.. Ця задача перенеслась зі страрої дошки, але вона вже в резолвді, тому і тут я відправляю іі в закриту.
