### ISSUE TITLE
В розділі "Попрактикуватися" Немає інтервалу  1,15 між рядками

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#416]
Передумови:
Відкрити https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/testrail/
Кроки для відтворення:

1. Відкрийте розділ "Попрактикуватися"
2. Зверніть на відстань між рядками в розділі 

Фактичний результат:  В розділі "Попрактикуватися" немає інтервалу 1,15 між рядками
Очікуваний результат:  В розділі "Попрактикуватися" є інтервал 1,15 між рядками

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версия 108.0.5359.125 
![тест траіл](https://user-images.githubusercontent.com/113175298/210875704-e9dabda8-1cb1-44d5-87d5-6ac07c853ea4.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk "мала відстань" - це дуже відносне значення, давайте додами конкретики

**Comment by Nadiyk** [comment]
виправила

**Comment by ButKoff** [comment]
#373

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk давайте ще виправимо слово "малий"

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk давайте поставимо себе на місце девелопера, він відкриває дефект, бачить опис і бачить суть дефекту. Але не може зрозуміти який має бути інтервал в числовому значенні

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk і ще давайте Актуальний і Очікуваний результат і буде супер)

**Comment by Nadiyk** [comment]
виправила

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
Переходжу за посиланням
небачу бага який заводила.....
![image](https://user-images.githubusercontent.com/113175298/220605441-7e2b946d-cdb6-4ce3-a1f0-bbf3afb4a2d2.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk тоді закривайте

**Comment by Nadiyk** [comment]
pass
