### ISSUE TITLE
Матеріали - Quality Assurance Engineer (QA) - Теорія тестування. Базовий рівень - Q2. Базовий курс QA - Q2.01 Тестувальник. Хто це? - Button "Позначити як виконане" is missing 

### ISSUE THREAD

**Issue by KaterinaNimenko35** [scholokov/qax-portal-2#417]
**Steps to reproduce:**

1. Open page https://www.qax-camp.com.ua/courses/q2-basic-cource/lessons/q2-01-%d1%82%d0%b5%d1%81%d1%82%d1%83%d0%b2%d0%b0%d0%bb%d1%8c%d0%bd%d0%b8%d0%ba-%d1%85%d1%82%d0%be-%d1%86%d0%b5/
2. Scroll down the page to the lesson control block

**Actual result:**
Button "Позначити як виконане" is **missing**

**Expected result:**
Button "Позначити як виконане" is **present**

**Notes:**
Design in Figma
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A12775&t=bY9As8LQbSiX11OI-0

**Pay attention, an issue is reproduced on the pages:**
1. Q2.02 Види тестування 
https://www.qax-camp.com.ua/courses/q2-basic-cource/lessons/q2-02-%d0%b2%d0%b8%d0%b4%d0%b8-%d1%82%d0%b5%d1%81%d1%82%d1%83%d0%b2%d0%b0%d0%bd%d0%bd%d1%8f/

2. Q2.03 Рівні тестування
https://www.qax-camp.com.ua/courses/q2-basic-cource/lessons/q2-03-%d1%80%d1%96%d0%b2%d0%bd%d1%96-%d1%82%d0%b5%d1%81%d1%82%d1%83%d0%b2%d0%b0%d0%bd%d0%bd%d1%8f/

**Environment:**
Desktop/W10/Google Chrome 101.0.4951.67 (64-bit) 1920х1080

![2023-01-07 17 39 15](https://user-images.githubusercontent.com/105543094/211158825-314f200a-9171-48af-8298-096ad61c5d4c.png)

![2023-01-07 17 04 09](https://user-images.githubusercontent.com/105543094/211158838-71a1fe3d-9dd8-43dd-9efe-4969e04eaf55.png)

**Comment by scholokov** [comment]
please retest

**Comment by KaterinaNimenko35** [comment]
An issue is reproduced

![2023-01-10 09 29 57](https://user-images.githubusercontent.com/105543094/211489057-16966a33-bcd9-4f4d-96c8-7a0ccc4825d2.png)

**Comment by scholokov** [comment]
а тест пройдений?

**Comment by KaterinaNimenko35** [comment]
@scholokov  Після проходження тесту з'являється кнопка "Позначити як невиконане".  

1. Проходження тесту є обов'язковою умовою для переходу на наступний урок?

![2023-01-10 11 45 52](https://user-images.githubusercontent.com/105543094/211518499-fbbfddb2-9881-4174-bada-d53344c2a334.png)

**Comment by scholokov** [comment]
це вже залежить від налаштувань курсу:
1. потрібно всі уроки проходити один за одним. у такому випадку обов'язково проходити тести
2. можна проходити уроки у любому порядку. але для того щоб "зарахувався" урок "виконаним" - потрібно пройти тест

**Comment by GNatala** [comment]
passed
