### ISSUE TITLE
Матеріали - Quality Assurance Engineer (QA) - Теорія тестування. Базовий рівень - Q2. Базовий курс QA - Q2.04 Дефект - Button "Позначити як виконане" is missing 

### ISSUE THREAD

**Issue by KaterinaNimenko35** [scholokov/qax-portal-2#418]
**Steps to reproduce:**

1. Open page https://www.qax-camp.com.ua/courses/q2-basic-cource/lessons/q2-04-%d0%b4%d0%b5%d1%84%d0%b5%d0%ba%d1%82/
2. Scroll down the page to the lesson control block

**Actual result:**
Button "Позначити як виконане" is **missing**

**Expected result:**
Button "Позначити як виконане" is **present**

**Notes:**
Design in Figma
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A12775&t=bY9As8LQbSiX11OI-0

**Pay attention, an issue is reproduced on the page:**

Q2.05 Тестова документація: чек-лісти та тест-кейси
https://www.qax-camp.com.ua/courses/q2-basic-cource/lessons/q2-05-%d1%82%d0%b5%d1%81%d1%82%d0%be%d0%b2%d0%b0-%d0%b4%d0%be%d0%ba%d1%83%d0%bc%d0%b5%d0%bd%d1%82%d0%b0%d1%86%d1%96%d1%8f-%d1%87%d0%b5%d0%ba-%d0%bb%d1%96%d1%81%d1%82%d0%b8-%d1%82%d0%b0-%d1%82%d0%b5/

**Environment:**
Desktop/W10/Google Chrome 101.0.4951.67 (64-bit) 1920х1080

![2023-01-07 17 49 30](https://user-images.githubusercontent.com/105543094/211159141-031bb761-3835-40b9-ac5f-681fd820f4b9.png)

![2023-01-07 17 04 09](https://user-images.githubusercontent.com/105543094/211159152-883ff1d6-1076-43c9-b49a-aa7829f86d55.png)

**Comment by scholokov** [comment]
відсутня кнопка, тому що непройдений тест

**Comment by GNatala** [comment]
passed
