### ISSUE TITLE
 Lesson Zephyr Scale (TM4J) - Topics - Numbering color does not match the design

### ISSUE THREAD

**Issue by KaterinaNimenko35** [scholokov/qax-portal-2#420]
**Steps to reproduce:**

1. Open page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/zephyr-scale-tm4j-basics/
2. Scroll down the page to the lesson topics
3. Click the button to open the topic "2. Creating: Test Cases / Checklists"
4. Pay attention to numbering in the text

**Actual result:**
#E9E8EA

**Expected result:**
#F66F5D

**Notes:**
Design in Figma
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A12775&t=wwfG026GU36MhL1g-0

Task #77

**Pay attention, an issue is reproduced in topics:**

**2a. Difference between Test-cases and Check-lists
3. Linking: Cases to Tasks
5. Creating: Cycle Execution
6. Linking: Execution to Tasks
7. Cycle Execution
8. Linking: Issues to Cycles**

**Environment:**
Desktop/W10/Google Chrome 101.0.4951.67 (64-bit) 1920х1080

![www qax-camp com ua_courses_qa-basic-programs_lessons_zephyr-scale-tm4j-basics_ (1)](https://user-images.githubusercontent.com/105543094/211169921-bdde4f75-83a2-47d0-87a3-7566f01988ea.png)

![2023-01-07 22 51 57](https://user-images.githubusercontent.com/105543094/211169928-e12cc8d7-e2b5-4d72-ae89-083043d61019.png)

**Comment by Nadiyk** [comment]
баг відтворюється 
![ретест](https://github.com/scholokov/qax-portal-2/assets/113175298/d7a2d447-affa-4f4e-a450-dbcf89bdff18)
![ретест 2](https://github.com/scholokov/qax-portal-2/assets/113175298/7691b987-c0ae-4e98-b864-8435ec1be843)
