### ISSUE TITLE
Implemenet block "Чому обирають нас?" on the Home page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#421]
We need to Implemenet block "Чому обирають нас?" on the Home page.
Design on Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A22&t=X8ceBdRtyjajaGzw-0
Test environment: https://portal.qax-camp.com.ua/
Block content: https://github.com/scholokov/qax-portal-2/wiki/Home-%5Bpage%5D
![Чому](https://user-images.githubusercontent.com/109460500/211315770-53e34141-8398-467a-a07c-9db626e5486d.png)
![Чому_](https://user-images.githubusercontent.com/109460500/211315797-6074c6cb-d5a1-4b6c-88b9-112b756efc4c.png)

**Comment by dmitryylev** [comment]
verified
