### ISSUE TITLE
Пропущена " , "  в описі сайта

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#422]
Передумови:
Відкрити https://portal.qax-camp.com.ua/about-us/
Кроки для відтворення:

1. Прокрутіть сторінку до розділу "НашА ДНК - це практика"
2. Зверніть увагу, що в перому рядку доущена граматична помилка

Фактичний результат: Пропущений знак "," в описі сайту
Очікуваний результат: В описі сайту немає граматичних помилок

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версия 108.0.5359.125 
![КЕМП](https://user-images.githubusercontent.com/113175298/211585299-c75c1bdc-d7a8-4a10-8c4b-b1362fd530b7.png)

**Comment by Nadiyk** [comment]
#304

**Comment by GNatala** [comment]
Content of the page meets the requirements

**Comment by Nadiyk** [comment]
баг відтворюється
![портал кома](https://user-images.githubusercontent.com/113175298/222432630-e1699be2-00fb-4b4c-a3bf-cdb5f522e1c5.png)
