### ISSUE TITLE
Implemenet block "Увага!" on the Home page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#423]
We need to Implemenet block "Увага!" on the Home page.
Design on Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A22&t=X8ceBdRtyjajaGzw-0
Product environment: https://www.qax-camp.com.ua/
![Увага](https://user-images.githubusercontent.com/109460500/211583128-17c797a9-2bf6-4bc4-ac77-eff0b398dbd5.png)

**Comment by Nadiyk** [comment]
verified
