### ISSUE TITLE
В описі сайту є відкрита ( але закритої немає

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#424]
Передумови:
Відкрити  https://portal.qax-camp.com.ua/about-us/
Кроки для відтворення:

1. Прокрутіть сторінку до розділу "Наше ДНК - це практика"
2. Зверніть увагу, що в кінці першого абзацу є відкрита ( але не закривається

Фактичний результат: В описі сайту є відкрита ( але закритої немає
Очікуваний результат: В описі сайту є відкриті та закриті  ( )

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версия 108.0.5359.125 
  
![дужка](https://user-images.githubusercontent.com/113175298/211611589-71884d34-d493-4698-be99-1049e4c3eba8.png)

**Comment by Nadiyk** [comment]
#304

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
