### ISSUE TITLE
Перед розділами 1,2 немає між рядкового інтервалу 1,5

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#425]
Передумови:
Відкрити  https://portal.qax-camp.com.ua/about-us/
Кроки для відтворення:

1. Прокрутіть сторінку до розділу "Як з"явився CAMP"
2. Зверіти увагу що після останнього немає міжрядкового інтервалу

Фактичний результат: Перед розділами 1,2 немає між рядкового інтервалу 1,5
Очікуваний результат: Перед розділами 1,2 є між рядкового інтервалу 1,5

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версия 108.0.5359.125 
![інтервал](https://user-images.githubusercontent.com/113175298/211909903-efb90409-06e2-491d-aef6-a746e532d9fb.png)

**Comment by Nadiyk** [comment]
#304

**Comment by DmytroMarkulych** [comment]
@Nadiyk як це? в кінці речення міжрядковий інтервал?

**Comment by Nadiyk** [comment]
виправила

**Comment by scholokov** [comment]
на чому оснований баг?

**Comment by Nadiyk** [comment]
В фігмі є відстань
![image](https://user-images.githubusercontent.com/113175298/217206200-772bac8c-a2a0-4603-af88-6aa636903a1e.png)

**Comment by scholokov** [comment]
от в саме в цьому і було питання. тобто ви базувалися на фігмі :)

**Comment by Nadiyk** [comment]
not relevant
