### ISSUE TITLE
Максим Плакса пропущена діяльність "2020 - 2022 - QA Engineer в ModXart"

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#430]
Передумови:
Відкрити https://www.qax-camp.com.ua/trainers/
Кроки для відтворення:

1. Прокрутіть сторінку до розділу Максим Плакса
2. Зверніть увагу що роки діяльності"2020 -2022 QA Engineer в ModXart "   не має на сайті

Фактичний результат: Максим Плакса, опис робти "2020 -2022 QA Engineer в ModXart " не вказаний на сайті
Очікуваний результат:  Максим Плакса опис робти  відповідає вимогам

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версия 108.0.5359.125 
![ПЛАКСА](https://user-images.githubusercontent.com/113175298/212339870-23e8c549-8c9f-431d-855a-9a4e14e2b99f.png)

**Comment by Nadiyk** [comment]
#288

**Comment by DmytroMarkulych** [comment]
@Nadiyk 1. Давайте вкажемо якої саме роботи, і виправимо граматичну помилку)

**Comment by Nadiyk** [comment]
Виправила, але я незнайшла граматичну помилку(

**Comment by DmytroMarkulych** [comment]
@Nadiyk давайте додамо теги: Type issue, Component, Severity 

![Image](https://user-images.githubusercontent.com/88647733/213397047-59401c2f-184f-484b-b60a-993236e6cca2.png)

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk 

![Image](https://user-images.githubusercontent.com/88647733/213864113-a61db15b-c466-464c-a2bd-655fb182af74.png)

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
https://github.com/users/scholokov/projects/1/views/10?pane=issue&itemId=18045070

**Comment by DmytroMarkulych** [comment]
@Nadiyk давайте прибиремо priority

**Comment by Nadiyk** [comment]
виправила

**Comment by scholokov** [comment]
помилка у вимогах

**Comment by ABatalov** [comment]
@Nadiyk - fixed https://github.com/scholokov/qax-portal-2/wiki/1.4.-Our-Trainers

**Comment by Nadiyk** [comment]
Pass
