### ISSUE TITLE
Катерина Котелева опис  діяльності не відповідає вимогам

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#431]
Передумови:
Відкрити  https://www.qax-camp.com.ua/trainers/
Кроки для відтворення:

1. Прокрутіть сторінку до розділу Катерина Котелева
2. Зверініть увагу, що опис 2014 не відповідає вимогам

Фактичний результат: Катерина Котелева опис  діяльності не відповідає вимогам
Очікуваний результат: Катерина Котелева опис  діяльності  відповідає вимогам

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версия 108.0.5359.125 
  
![Катерина Котелева 2014](https://user-images.githubusercontent.com/113175298/212347610-42703921-c6ee-40a8-a14a-1df58ab308a0.png)

**Comment by Nadiyk** [comment]
#288

**Comment by ABatalov** [comment]
@Nadiyk - fixed. Сайт та Wiki співпадають https://github.com/scholokov/qax-portal-2/wiki/1.4.-Our-Trainers

**Comment by Nadiyk** [comment]
Pass
