### ISSUE TITLE
Опис розділу "Наші тренери" не відповідає вимогам 

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#433]
Передумови:
Відкрити  https://www.qax-camp.com.ua/trainers/
Кроки для відтворення:

1. Опис "Наші тренери не" відповідає вимогам

Фактичний результат:  Опис розділу "Наші тренери" не відповідає вимогам 
Очікуваний результат: Опис розділу "Наші тренери"  відповідає вимогам 

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версия 108.0.5359.125 
![тренери](https://user-images.githubusercontent.com/113175298/212354008-e1b6b3b4-184e-49a8-b2a7-96a0d639586b.png)
вимоги
![вимоги тренери](https://user-images.githubusercontent.com/113175298/212354243-f2d78739-99f5-4883-8af6-b84c7a561cc9.png)

**Comment by Nadiyk** [comment]
#288

**Comment by scholokov** [comment]
помилка у вимогах.

**Comment by Nadiyk** [comment]
значить закриваю це баг?

**Comment by scholokov** [comment]
ні. нткба обновити документацію

**Comment by Nadiyk** [comment]
а які мої дії?

**Comment by ABatalov** [comment]
@Nadiyk - fixed https://github.com/scholokov/qax-portal-2/wiki/1.4.-Our-Trainers

**Comment by Nadiyk** [comment]
Pass
