### ISSUE TITLE
В розділі "Історії успіху", на сайті є конопка "Дивитись усіх", а в фігмі "Згорнути"

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#435]
Передумови:
Відкрити https://www.qax-camp.com.ua/
Кроки для відтворення:

1. Прокрутіть сторінку до форми рейстрації
2. З ліва є кнопка "дивитися всіх", а в фігмі "згорнути"

Фактичний результат: На сайті є кнопка "дивитися всіх", а на фігмі "згорнути"
Очікуваний результат: На сайті є кнопка "дивитися всіх", і на фігмі "дивитися всіх"

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версия 108.0.5359.125
![дивитися всіх](https://user-images.githubusercontent.com/113175298/212475888-6c5d9a99-498e-4283-8bfb-4a0f9d734146.png)
![фігма](https://user-images.githubusercontent.com/113175298/212475896-85d33b62-e009-45e7-a500-2039204b10d6.png)

**Comment by Nadiyk** [comment]
#423

**Comment by DmytroMarkulych** [comment]
@Nadiyk Це стан одноєї кнопки в різних умовах. Коли у нас не розгорнутий список всіх тоді буде "Дивитися всіх", а коли розгорнутий то "Згонути"

**Comment by Nadiyk** [comment]
закривати це питання?

**Comment by DmytroMarkulych** [comment]
@Nadiyk Тоді варто переробити Summary вказавши по принципу Де? Що? Коли?

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk 

![Image](https://user-images.githubusercontent.com/88647733/213864146-510f59e3-75db-4da9-9192-c749c2898ee9.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk Денис додав нові view. За посиланням Ваш дефект вже в новому view 
https://github.com/users/scholokov/projects/1/views/10?pane=issue&itemId=18086318

**Comment by Nadiyk** [comment]
що мені робити?

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk давайте прибиремо priority

**Comment by Nadiyk** [comment]
виправила?

**Comment by Nadiyk** [comment]
Pass
