### ISSUE TITLE
Content - russian block names - in the test - lesson "Test Management System (TMS)" - "Програми для QA"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#436]
**STR**

1. Open https://www.qax-camp.com.ua/;
2. Login;
3. Go to the page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/tms/
4. Scroll to the block "Урок Content" and press TMS 
5. After opening the page press "Start test". pay attention to the test's blocks names

**ACTUAL RESULT**
The name of the topics has a russian text "Для чего используются TMS?" / "Кто из участников проектной команды обычно имеет доступ к TMS?" / "Что такое TMS?"

**EXPECTED RESULT**
The name of the topics are 
"Для чого використовуються TMS"
"Хто із учасників проектної команди зазвичай має доступ до TMS"
"Що таке TMS"

![4OX0pYC8Yl](https://user-images.githubusercontent.com/109384052/212676464-75a938f4-6f17-43aa-890b-1042b7eded63.png)
![T0bzoV6cNf](https://user-images.githubusercontent.com/109384052/212676518-3ecdce91-a836-432b-8142-edc916a02a4b.png)

**Comment by BatalovaOlha** [comment]
#371

**Comment by scholokov** [comment]
please retest

**Comment by BatalovaOlha** [comment]
the same

![Image](https://user-images.githubusercontent.com/109384052/213886829-fd17cb57-17c3-4069-aeca-fae13fc26ee6.png)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
Resolved
