### ISSUE TITLE
Content - subsection in the test mark different symbols - lesson "Test Management System (TMS)"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#437]
**STR**

1. Open https://www.qax-camp.com.ua/;
2. Login;
3. Go to the page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/tms/
4. Scroll to the block "Урок Content" and press TMS
5. After opening the page press "Start test" and pay attention to the type of mark of subsections

**ACTUAL RESULT**
After starting the test showed a different type of marking subsection - circle, and square. 

**EXPECTED RESULT**
The type of marking subsection is one for tests. 

![RKQksMH5Xc](https://user-images.githubusercontent.com/109384052/212678966-8259969e-8ea5-4086-aa26-a900239dc5d9.png)
![H1LIAcCTZK](https://user-images.githubusercontent.com/109384052/212678981-1ea077b5-243f-4723-9d25-09fd06664d07.png)

**Comment by BatalovaOlha** [comment]
#371

**Comment by scholokov** [comment]
це залежить від самого питання:
- круг - коли має бути лише одна відповідь
- квадрат - коли може бути люба кількість відповідей

це стандартний функціонал

**Comment by BatalovaOlha** [comment]
@scholokov можливо треба десь зробити примітку про це на сторінці тесту, бо не знаючи цього, не відразу здогадаєшся...

**Comment by BatalovaOlha** [comment]
non actual
