### ISSUE TITLE
Content - russian language in block name - lesson "Test Data Generation Tools"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#438]
**STR**

1. Open https://www.qax-camp.com.ua/;
2. Login;
3. [Go to the page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/tms/](https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/test-data-generation-tools/)
4. Pay attention to the language in the block

**ACTUAL RESULT**
The name of the topics has a russian text "Приложения для генерации тестовых данных"

**EXPECTED RESULT**
The text in topic should be "Застосунки для генерації тестових даних" 

![fqB347CYFw](https://user-images.githubusercontent.com/109384052/212702233-48ca3fed-a087-45e6-9832-7aa2c93ff05d.png)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
Resolved
