### ISSUE TITLE
Unreadable text color in the tools description - lesson "Test Data Generation Tools"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#439]
**STR**

1. Open https://www.qax-camp.com.ua/;
2. Login;
3. [Go to the page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/tms/](https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/test-data-generation-tools/)
4. Pay attention to the table with tools in the block "Приложения для генерации тестовых данных"

**ACTUAL RESULT**
The color of the text in the table with the description of the tools is unreadable (text color #FFFFFF / background #E9E8EA / white on the white)

**EXPECTED RESULT**
The color of the text in the table with the description of the tools is contrasting to the background
![ldH0FMylvm](https://user-images.githubusercontent.com/109384052/212706459-9dbee296-491f-46cd-aad8-34034459cd77.png)

![5Tkuz7yJiF](https://user-images.githubusercontent.com/109384052/212706469-16facac7-da25-4b2f-8ad0-afab053b31dc.png)
![2vkuKWYvg4](https://user-images.githubusercontent.com/109384052/212706569-7f13f8ab-0227-49df-aa15-e78d5509028c.png)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
Resolved
