### ISSUE TITLE
Lesson: Error Message - Не изучен предыдущий урок

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#44]
![image](https://user-images.githubusercontent.com/22824947/185742689-2f68e358-07f5-454b-9696-8ee9134168b9.png)

фігма:
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A12776

**Comment by KaterinaNimenko35** [comment]
Created bug #226

**Comment by KaterinaNimenko35** [comment]
verified
