### ISSUE TITLE
Content - russian text in the description - lesson "SessionBox" - "Програми для QA"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#441]
**STR**

1. Open https://www.qax-camp.com.ua/;
2. Login;
3. Go to the page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/sessionbox/
4. Pay attention to the language of the description

**ACTUAL RESULT**
The lesson description is in russian language.

**EXPECTED RESULT**
The lesson description is in the Ukrainian language.

**_NOTE:
The text should be:_**

Використовувати сайти декількома користувачами тепер легко. Створюйте незалежні один від одного вкладки одним натисканням кнопки.
Використовуйте один браузер із кількома активними сесіями на сайті. Заходьте в кілька облікових записів на одному сайті одночасно. Більше немає потреби у додаткових браузерах, приватних сесіях – дозвольте SessionBox зробити це за вас.

![rNCIc1buCs](https://user-images.githubusercontent.com/109384052/212737159-280ba896-9a6b-4ccf-b3dc-8597db9e1c61.png)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
Resolved
