### ISSUE TITLE
Відсутнє зображення в розділі "QA Program"

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#443]
Передумови:
Відкрити  https://www.qax-camp.com.ua/qa-program/
Кроки для відтворення:

1. Зверніть увагу, що на головній сторінці немає зображення

Фактичний результат: В розділі "QA Program" відсутнє зображення
Очікуваний результат: В розділі "QA Program" є забраження

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версия 108.0.5359.125 
![QA PROGRAM](https://user-images.githubusercontent.com/113175298/213457860-edc36d68-4f31-4e7f-b6d6-14154173c7f6.png)
![PR-FIGM](https://user-images.githubusercontent.com/113175298/213458084-9568dae2-6b42-4a4f-9d25-bf71eb7f3aab.png)

**Comment by Nadiyk** [comment]
#363

**Comment by DmytroMarkulych** [comment]
@Nadiyk Давайте в Summary вкажемо просто: Відсутнє зображення в розділі "QA Програм". І не будемо використовувати фразу "Яке є в фігмі"

**Comment by DmytroMarkulych** [comment]
@Nadiyk 

![Image](https://user-images.githubusercontent.com/88647733/213864258-56c6e4f9-6ef8-4c7e-b1bc-14524d9a761a.png)

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk Денис додав нові view. За посиланням Ваш дефект вже в новому view https://github.com/users/scholokov/projects/1/views/10?pane=issue&itemId=18454895

**Comment by Nadiyk** [comment]
випраавила

**Comment by DmytroMarkulych** [comment]
@Nadiyk давайте прибиремо priority та видалимо фразу "Яке є в фігмі " із summary

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk зОбраження - summary

**Comment by Nadiyk** [comment]
не зрозуміла, що тут виправити?
![image](https://user-images.githubusercontent.com/113175298/222455655-435d7a6c-953d-4f1c-a3b2-696e168a59b2.png)
