### ISSUE TITLE
Requirements - When the course is bought, the button "Записатися" should be changed to "Продовжити"

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/qax-portal-2#444]
**Steps to reproduce:**
1. Open [requirements](https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials)
2. Pay attention to the course card requirements

**Actual result:** Requirements for the bought course is miss
**Expected result:** Requirements include: When the course is bought, the button "Записатися" should be changed to "Продовжити" 

![NVIDIA_Share_e03fb9blQ8](https://user-images.githubusercontent.com/57997443/213462886-ce8f0a19-8d3c-4eb2-9324-2cc33af1b68e.png)

**Comment by dmitryylev** [comment]
#368

**Comment by ABatalov** [comment]
@dmitryylev - fixed https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials

**Comment by GNatala** [comment]
passed
