### ISSUE TITLE
Requirements - When the course is bought, block with price should be missed or change to "Придбано"

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/qax-portal-2#445]
**Steps to reproduce:**
1. Open [requirements](https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials)
2. Pay attention to the course card requirements

**Actual result:** Requirements for the bought course is miss
**Expected result:** Requirements include: When the course is bought, block with price should be missed or change to "Придбано"

![NVIDIA_Share_KMWqgL6QqF](https://user-images.githubusercontent.com/57997443/213465243-a6ced25f-7479-495d-a6c4-a34e8af71750.png)

**Comment by dmitryylev** [comment]
#368

**Comment by ABatalov** [comment]
@dmitryylev - fixed https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials

**Comment by GNatala** [comment]
passed
