### ISSUE TITLE
Requirements - The button "Записатися" should be different from the button "Продовжити" in color

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/qax-portal-2#446]
**Steps to reproduce:**
1. Open [requirements](https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials)
2. Pay attention to the course card requirements

**Actual result:** Requirements for the button color "Записатися" and "Продовжити" is miss
**Expected result:** Requirements include: The button "Записатися" should be different from the button "Продовжити" in color

![NVIDIA_Share_JrLThoWlZo](https://user-images.githubusercontent.com/57997443/213467347-7686a973-235c-44d0-8704-d29db2243e2b.png)

**Comment by dmitryylev** [comment]
#368

**Comment by ABatalov** [comment]
fixed - https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials

**Comment by GNatala** [comment]
passed
