### ISSUE TITLE
Requirements - In the course card the button "Записатися", price and progress bar should be displayed at the bottom of block

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/qax-portal-2#447]
**Steps to reproduce:**
1. Open [requirements](https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials)
2. Pay attention to the course card requirements

**Actual result:** Requirements for the elements in course card display are miss
**Expected result:** Requirements include: The button "Записатися", price and progress bar should be displayed at the bottom of block

![NVIDIA_Share_DE6hp88pZU копия](https://user-images.githubusercontent.com/57997443/213470297-fcdef091-14df-4108-af94-5262e368ae93.jpg)

**Comment by dmitryylev** [comment]
#368

**Comment by scholokov** [comment]
fixed

**Comment by dmitryylev** [comment]
verified
