### ISSUE TITLE
In the course card, the hover of the button "Записатися" is miss

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/qax-portal-2#448]
**Steps to reproduce:**
1. Open [design](https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A43)
2. Pay attention to the course card

**Actual result:** The hover of the button "Записатися" is miss
**Expected result:** The hover of the button "Записатися" is present

![NVIDIA_Share_CLSDK1FCkY](https://user-images.githubusercontent.com/57997443/213474285-6cabaf39-75d6-48b6-9046-06643b5a12d5.png)

**Comment by dmitryylev** [comment]
#368

**Comment by scholokov** [comment]
ready
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A43&t=ltaTMZMLgLQkfgJc-0

**Comment by dmitryylev** [comment]
verified
