### ISSUE TITLE
В розділі "Історії успіху" кнопка  "згорнути" коли розгорнутий список

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#449]
Передумови:
Відкрити  https://www.qax-camp.com.ua/
Кроки для відтворення:

1. Прокрутіть сторінку до розділу "Історії успіху"
2. Відкрийте весь список "Історії успіху"
3. Зверніть увагу, що немає кнопки "згорнути"

Фактичний результат:  В розділі "Історії успіху" коли список повністю відкритий немає кнопки "згорнути"
Очікуваний результат: В розділі "Історії успіху" коли список повністю відкритий є кнопки "згорнути"

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версия 108.0.5359.125
![кнопка згорнути](https://user-images.githubusercontent.com/113175298/213519540-699a586c-e034-43c0-a141-19d63abed732.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk Де? В розділі... Що? кнопка Коли? після розгортання списку

**Comment by DmytroMarkulych** [comment]
@Nadiyk і ще додамо, в Summary, що саме кнопка "Згорнути". (У нашому випадку не відображається), і буде взагалі класс)

**Comment by DmytroMarkulych** [comment]
@Nadiyk і не забуваємо про атрибути дефекту)

**Comment by DmytroMarkulych** [comment]
@Nadiyk давайте прибиремо priority

**Comment by Nadiyk** [comment]
виправила
