### ISSUE TITLE
Link: Hover

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#45]
Нужен ховер для линков:

приклад:
https://portal.qax-camp.com.ua/courses/recruiter-program/lessons/lesson_5_continue-to-work-with-vacancy/

![image](https://user-images.githubusercontent.com/22824947/183054645-3e086f1c-57b8-4cf1-b59c-10355594c1b8.png)

фігма:
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=799%3A168

**Comment by KaterinaNimenko35** [comment]
Посилання https://portal.qax-camp.com.ua/courses/recruiter-program/lessons/lesson_5_continue-to-work-with-vacancy/
веде на сторінку https://portal.qax-camp.com.ua/courses/recruiter-program/

**Comment by poroskundenys** [comment]
> Посилання https://portal.qax-camp.com.ua/courses/recruiter-program/lessons/lesson_5_continue-to-work-with-vacancy/ веде на сторінку https://portal.qax-camp.com.ua/courses/recruiter-program/

Нужно смотреть под пользователем у которого этот курс куплен и есть доступ к урокам, тогда ссылка открывается правильно

**Comment by KaterinaNimenko35** [comment]
Надайте будь ласка пароль і логін користувача  який має необмежений доступ. Я як звичайний зареєстрований користувач маю обмежений доступ до контенту.

**Comment by scholokov** [comment]
@KaterinaNimenko35 
скажи якому юзеру треба дати доступ
так простіше зробити :)

**Comment by KaterinaNimenko35** [comment]
verified
