### ISSUE TITLE
Different placement of the button "Записатися" - block "Теорія тестування. Базовий рівень" - page "QA Программа" 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#450]
**STR**
1. Open https://portal.qax-camp.com.ua/qa-program/
2. Go to the block "Теорія тестування. Базовий рівень" and unfold it, pay attention to the placement of the button "Записатися" 

**ACTUAL RESULT**
Button "Записатися" is at a _different height_ in all theme blocks

**EXPECTED RESULT**
 Button "Записатися" is at a _one height_ in all theme blocks
![EF4RsgACCg](https://user-images.githubusercontent.com/109384052/213662189-e6eb7362-e3f8-4740-af69-d11f25230ebf.png)

**Comment by BatalovaOlha** [comment]
#368

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha 

![Image](https://user-images.githubusercontent.com/88647733/213864777-fb571aa0-6ea6-4643-b688-5ba9de4e9556.png)

**Comment by BatalovaOlha** [comment]
@DmytroMarkulych, все додала

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
resolved
