### ISSUE TITLE
 Figma requirement - payment procedure - course card "QA Basics" - shown only monthly payment

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#451]
**STR**
1. Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A44&t=cixz9xENCueB3BXt-0
2. Pay attention to the card with the course "QA Basics" / part with the price 

**ACTUAL RESULT**
The course card shows the price for every single month of the course

**EXPECTED RESULT**
The course card should be 2 ways of payment - shows the price for every single month / for the entire course 

![efLCeqj6vn](https://user-images.githubusercontent.com/109384052/213667067-4626549f-573d-47d1-a84f-66ad78330e03.png)

**Comment by BatalovaOlha** [comment]
#368

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha 

![Image](https://user-images.githubusercontent.com/88647733/213864812-c41df799-1e4e-49e8-88bb-18e1e0f7d66d.png)

**Comment by scholokov** [comment]
давай передбачимо 2 варіанти:
- 50$ / на місяць
- 50$

**Comment by AlonaSarapina** [comment]
перший варіант: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A44&t=GhIczmEMUf8hEs5f-1
другий варіант: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=4745%3A740&t=GhIczmEMUf8hEs5f-1

**Comment by scholokov** [comment]
ready
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A43&t=ltaTMZMLgLQkfgJc-0

**Comment by BatalovaOlha** [comment]
resolved
