### ISSUE TITLE
No price for the courses in the cards "Recruitment: from zero to hero.." / "ФИДБЕК ПО КАНДИДАТУ..." / "ФИНАЛЬНЫЙ ЭКЗАМЕН..." / "Q0..." - block "Теорія тестування. Базовий рівень" - page "QA Программа"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#452]
**STR**

1. Open https://portal.qax-camp.com.ua/qa-program/
2. Go to the block "Теорія тестування. Базовий рівень" and unfold it, scroll to the last card and pay attention to the missing price.

**ACTUAL RESULT**
Cards with courses "[Recruitment: from zero to hero - Додаткові матеріали](https://portal.qax-camp.com.ua/courses/recruiter-program-2/)" / "[ФИДБЕК ПО КАНДИДАТУ ДЛЯ HIRING МЕНЕДЖЕРА ПОСЛЕ RECRUITMENT ИНТЕРВЬЮ](https://portal.qax-camp.com.ua/courses/feedback-for-hiring-manager/)" / "[ФИНАЛЬНЫЙ ЭКЗАМЕН ПО РЕКРУТМЕНТ ПРОГРАММЕ](https://portal.qax-camp.com.ua/courses/recruitment_final/)" / [Q0. Тестування. Основи](https://portal.qax-camp.com.ua/courses/qa-basics-denis/) shown without price. 

**EXPECTED RESULT**
Cards with 4 last courses shown with price - for full course / free course / monthly payment 

![FMiMoA9x5y](https://user-images.githubusercontent.com/109384052/213671272-b09751d3-0bec-44b4-8eb3-3d2ec118f7f8.png)

**Comment by BatalovaOlha** [comment]
#368

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha 
![image](https://user-images.githubusercontent.com/88647733/213864836-eb9b0e90-a2cd-4751-95e1-408af3418abf.png)

**Comment by scholokov** [comment]
тобто питання  - яким чином відображати:
- якщо у курса немає ціни (тобто він ще не куплений, але безкоштовний)

**Comment by scholokov** [comment]
ready
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A43&t=ltaTMZMLgLQkfgJc-0

**Comment by BatalovaOlha** [comment]
Resolved
