### ISSUE TITLE
Content - russian text in the card with courses - block "Теорія тестування. Базовий рівень" - page "QA Программа"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#453]
**STR**

1. Open Open https://portal.qax-camp.com.ua/qa-program/
2. Go to the block "Теорія тестування. Базовий рівень" and unfold it, scroll to the last card and pay attention to the language of the title -  "[ФИДБЕК ПО КАНДИДАТУ ДЛЯ HIRING МЕНЕДЖЕРА ПОСЛЕ RECRUITMENT ИНТЕРВЬЮ](https://portal.qax-camp.com.ua/courses/feedback-for-hiring-manager/)" / "[ФИНАЛЬНЫЙ ЭКЗАМЕН ПО РЕКРУТМЕНТ ПРОГРАММЕ](https://portal.qax-camp.com.ua/courses/recruitment_final/)"

**ACTUAL RESULT**
To cards with course shown in russian language

**EXPECTED RESULT**
The title of the cards should be in the Ukrainian language:

"ФІДБЕК ПО КАНДИДАТУ ДЛЯ HIRING МЕНЕДЖЕРА ПІСЛЯ RECRUITMEN ІНТЕРВ'Ю"
"ФІНАЛЬНИЙ ЕКЗАМЕНТ З РЕКРУТМЕНТ ПРОГРАМИ"

![YTChS3NGUB](https://user-images.githubusercontent.com/109384052/213674327-ce79aecf-7d2d-47cf-ad84-cff631e4ec4c.png)

**Comment by BatalovaOlha** [comment]
#368

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha 

![Image](https://user-images.githubusercontent.com/88647733/213864884-8e62961c-c9d9-4492-898a-079fec98f006.png)

**Comment by BatalovaOlha** [comment]
@DmytroMarkulych, додала

**Comment by scholokov** [comment]
please retest on prod env
qax-camp.com.ua

**Comment by BatalovaOlha** [comment]
resolved
