### ISSUE TITLE
In the line with price shown two monetary currencies "$₴" in one line - block "Теорія тестування. Базовий рівень" - page "QA Программа"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#454]
**STR**

1. Open https://portal.qax-camp.com.ua/qa-program/
2. Go to the block "Теорія тестування. Базовий рівень" and unfold it, pay attention to the line with price 
3. Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A44&t=cixz9xENCueB3BXt-0 and pay attention how shown the price.

**ACTUAL RESULT**
In the one line with the price shown  two monetary currencies "$₴"

**EXPECTED RESULT**
In the one line with the price, only one currency is displayed

![JcSbS3JXEE](https://user-images.githubusercontent.com/109384052/213678440-d92e2581-769c-4fcb-981e-e7f562dc4547.png)
![ocwL1bzZpj](https://user-images.githubusercontent.com/109384052/213678910-2a17b7ef-3acf-4fd5-a3ad-182d7ccb8354.png)

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha 

![Image](https://user-images.githubusercontent.com/88647733/213864912-f72d51c3-e844-47ef-a716-c6593af3bccf.png)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
Resolved
