### ISSUE TITLE
Missing lines "Рівень складності" / "Мова" - in the courses card - block "Теорія тестування. Базовий рівень" - page "QA Программа"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#455]
**STR**

1. Open https://portal.qax-camp.com.ua/qa-program/
2. Go to the block "Теорія тестування. Базовий рівень" and unfold it, pay attention to the complete availability of information
3. Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A44&t=cixz9xENCueB3BXt-0 and pay attention to the course card.

**ACTUAL RESULT**
The course cards shown without full information - missed lines with  "Рівень складності" / "Мова" in the cards:
[Тестування API. Postman & Swagger. Від теорії до практики](https://portal.qax-camp.com.ua/courses/api-testing/)
[Привабливе CV та успішна співбесіда](https://portal.qax-camp.com.ua/courses/cv_and_interview/)
[Q2. Базовий курс QA](https://portal.qax-camp.com.ua/courses/q2-basic-cource/)
[Recruitment: from zero to hero - Додаткові матеріали](https://portal.qax-camp.com.ua/courses/recruiter-program-2/)
[ФИДБЕК ПО КАНДИДАТУ ДЛЯ HIRING МЕНЕДЖЕРА ПОСЛЕ RECRUITMENT ИНТЕРВЬЮ](https://portal.qax-camp.com.ua/courses/feedback-for-hiring-manager/)
[ФИНАЛЬНЫЙ ЭКЗАМЕН ПО РЕКРУТМЕНТ ПРОГРАММЕ](https://portal.qax-camp.com.ua/courses/recruitment_final/)
[Q0. Тестування. Основи](https://portal.qax-camp.com.ua/courses/qa-basics-denis/)

**EXPECTED RESULT**
The course cards are shown with lines "Рівень складності" / "Мова"

![lcz1ZIXMhK](https://user-images.githubusercontent.com/109384052/213681599-169b4e3d-21aa-4a57-9235-a4147cc1aa29.png)
![CEPbRhmkCs](https://user-images.githubusercontent.com/109384052/213681799-ec5e036d-9d78-457a-80cb-1094a5b2eb7f.png)

**Comment by BatalovaOlha** [comment]
#368

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha 

![Image](https://user-images.githubusercontent.com/88647733/213864937-32350397-7e3f-477e-93fe-712037eb6daa.png)

**Comment by scholokov** [comment]
рівень складності відображається тільки, якщо він "заданий".
коли реалізуємо цю фічу, треба буде перевіряти на присутність її у поточних курсів, бо наразі на портал середовищі, інфа по курсам не актуальна

**Comment by BatalovaOlha** [comment]
no actual
