### ISSUE TITLE
Extra text "Entry level" under the preview picture - block "Теорія тестування. Базовий рівень" - page "QA Программа"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#456]
**STR**
1. Open https://portal.qax-camp.com.ua/qa-program/
2. Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A44&t=trIrznRO3TntPWMd-0
3. Pay attention to the  preview picture - bottom left edge of the picture

**ACTUAL RESULT**
Extra text is displayed on the lower left edge of the picture

**EXPECTED RESULT**
Extra text is NOT displayed under the picture

![EpVBj19Gs1](https://user-images.githubusercontent.com/109384052/213865543-56847c1c-3894-4845-a76e-d7bd6a1f702f.png)
![b0MFzLB4KF](https://user-images.githubusercontent.com/109384052/213865553-a4491cef-1293-475e-a14a-00a38607b706.png)

**Comment by BatalovaOlha** [comment]
#368

**Comment by scholokov** [comment]
please retest on prod env
qax-camp.com.ua
