### ISSUE TITLE
Shown preview picture in the tablet (screen size 768x1024) - block "Теорія тестування. Базовий рівень" - page "QA Программа"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#457]
**STR**
1. Open https://portal.qax-camp.com.ua/qa-program/
2. Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A44&t=trIrznRO3TntPWMd-0
3. Pay attention to the screen size 768 (tablet)

**ACTUAL RESULT**
The preview picture on the tablet screen is shown 

**EXPECTED RESULT**
The preview picture on the tablet screen is NOT shown.
![tPSZPNFKMo](https://user-images.githubusercontent.com/109384052/213865851-59c995c4-b143-4861-9dcf-c045785f10a9.png)
![FMio7Q8eT3](https://user-images.githubusercontent.com/109384052/213865877-0a2d62ca-7436-46f7-98cf-86d3e1e6a21c.png)

**Comment by BatalovaOlha** [comment]
#368

**Comment by scholokov** [comment]
на фігмі наразі застаріла інформація. треба повністю оновити цей розділ

**Comment by scholokov** [comment]
треба зрозуміти яким чином відображати цей розділ

**Comment by scholokov** [comment]
@ButKoff  треба оговорити це зі Светою

**Comment by ABatalov** [comment]
@scholokov - я правильно розумію, що це зараз для документації неактуально? Чи оформити по цій тасці сторінку Курси в записі в Wiki?

**Comment by ButKoff** [comment]
not actual
