### ISSUE TITLE
Check Materials Page

### ISSUE THREAD

**Issue by ABatalov** [scholokov/qax-portal-2#462]
Please check:  

- [x] access to the page
- [x] logic on the page  
- [x] content 

Link to page:   
https://www.qax-camp.com.ua/topics/

**Comment by BatalovaOlha** [comment]
#55

**Comment by BatalovaOlha** [comment]
https://www.qax-camp.com.ua/topics/ за даним посиланням відкривається сторінка з напрямками навчання, ця сторінка відкривається незалежно від статусу логіну на сторінці.  Я прикріпила баг який створено на це, в нього статус "Ready for documentation". Дадам скрін сторінки 
![yxUOKvhwmX](https://user-images.githubusercontent.com/109384052/216819697-7a9a3b88-8782-4078-8f18-759ed893a6de.png)

**Comment by ABatalov** [comment]
https://www.qax-camp.com.ua/programs/ - please check new features of this page!
