### ISSUE TITLE
Check English for QA page

### ISSUE THREAD

**Issue by ABatalov** [scholokov/qax-portal-2#463]
Please check:  

- [x] access to the page
- [x] logic on the page  
- [x] content 

Link to page:   

https://www.qax-camp.com.ua/ 

Content here:  ![QAX1 (2)](https://user-images.githubusercontent.com/72439798/215336532-869d62aa-fe55-49bc-ace5-8dbf1c7689a9.jpg)

Content you can find here: https://test.qax-camp.com.ua/courses.php?course=qa&name=en_practice

**Comment by BatalovaOlha** [comment]
Cheked
