### ISSUE TITLE
Create new design of "QA Program" page on Portal Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#467]
We need to create new design of "QA Program" page on Portal Figma.
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A43&t=ifkNNEiLdgT8BPIg-0
Product environment: https://www.qax-camp.com.ua/qa-courses-2/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.0.1.--Quality-Assurance-Engineer-(QA)
![qa-courses_](https://user-images.githubusercontent.com/109460500/225232870-2406a742-0224-4a12-89ac-44a3b1a7990a.png)

**Comment by scholokov** [comment]
ready:
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A43&t=v4s7Mr4QiCDN1gkj-0

**Comment by OlhaHutsman** [comment]
@scholokov  verifyed
