### ISSUE TITLE
Requirements - On the home page, in block "Чому обирають нас?" text with orthographic mistakes

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/qax-portal-2#469]
**Steps to reproduce:**
1. Open [requirements](https://github.com/scholokov/qax-portal-2/wiki/1.1.-Home-%5Bpage%5D)
2. Pay attention to the block "Чому обирають нас?"

**Actual result:**  Text with orthographic mistakes
**Expected result:** Orthographic mistakes corrected

![NVIDIA_Share_nASgyv2sKk](https://user-images.githubusercontent.com/57997443/216032403-20d7c264-02ac-4469-b75e-3788930432ec.png)

**Comment by dmitryylev** [comment]
#421

**Comment by DmytroMarkulych** [comment]
@dmitryylev правильно буде проЄкт

**Comment by dmitryylev** [comment]
irrelevant
