### ISSUE TITLE
On the course page, when the lesson unavailable, the tooltip is not present on Tab and Mob

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/qax-portal-2#471]
**Steps to reproduce:**
1. Open [design](https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A1035&t=oAsLssMS8lMLxNcq-0)
2. Pay attention to the lesson with tooltip

**Actual result:**  Tooltip is not present on Tab and Mob
**Expected result:**  Tooltip is present on Tab and Mob

![NVIDIA_Share_A1vphww7se](https://user-images.githubusercontent.com/57997443/216043813-70c11e18-4a0f-4b3d-9861-304ab8af4c1f.png)

**Comment by scholokov** [comment]
fixed

**Comment by dmitryylev** [comment]
verified
