### ISSUE TITLE
Home page - Implement a button "Згорнути" in a block "Історії Успіху"

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#472]
We need to implement a button "Згорнути" in a block "Історії Успіху"
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A22&t=k7AW5DPNkkRkIalG-0
Product environment: https://www.qax-camp.com.ua/
![Історії Успіху](https://user-images.githubusercontent.com/109460500/216952760-a5838d7a-d11f-4529-a38e-0aa4eeada155.png)

**Comment by Nadiyk** [comment]
Verified
