### ISSUE TITLE
Russian content - topic "Створення резюме (CV) – Точка зору технічного спеціаліста"- lesson "Привабливе CV та успішна співбесіда" - page "QA Program" 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#474]
**STR**
1. Open https://www.qax-camp.com.ua/courses/cv_and_interview/ 
2. Login and open https://www.qax-camp.com.ua/courses/cv_and_interview/
3. Go to the second lesson "Створення резюме (CV) – Точка зору технічного спеціаліста" and pay attention to the text language

**ACTUAL RESULT**
All text on the page is in the russian language

**EXPECTED RESULT**
Page with lesson shown in the Ukrainian language.

![6IMfQM7NQg](https://user-images.githubusercontent.com/109384052/217349940-9a6a075c-48fa-4620-986e-40c1177be30a.png)
![0pW8YmyY4z](https://user-images.githubusercontent.com/109384052/217350024-64f4d241-8c71-41a4-8a8a-d2b16cffa846.png)
![Z57nUaaC28](https://user-images.githubusercontent.com/109384052/217350100-575b8976-4010-45f8-89ad-e3415f44140e.png)

**Comment by BatalovaOlha** [comment]
#461

**Comment by scholokov** [comment]
please retest

**Comment by BatalovaOlha** [comment]
verified
