### ISSUE TITLE
Mob-Tab - On the course page, when the lesson is not available, the tooltip is missing at a screen width of 767px or less

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/qax-portal-2#479]
**Steps to reproduce:**
1. Open [course with unavailable lesson](https://www.qax-camp.com.ua/courses/q2-basic-cource/) at a screen width of 767px or less
2. Pay attention the tooltip is missing

**Actual result:**  Tooltip is missing 
**Expected result:**  Tooltip is present 

![NVIDIA_Share_UeQzAC2ytS](https://user-images.githubusercontent.com/57997443/217508421-5261df98-6c93-4350-beb6-f3b3ebdbf44d.png)

![NVIDIA_Share_2VjhlOWGBf](https://user-images.githubusercontent.com/57997443/217508680-d8296fe3-52b8-451a-bf5d-797ec5772284.png)

**Comment by poroskundenys** [comment]
готово

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
