### ISSUE TITLE
Courses - Check course for "Web технології" page

### ISSUE THREAD

**Issue by ABatalov** [scholokov/qax-portal-2#480]
Please check page web technology :  

- [x] access to the page
- [x] logic on the page  
- [x] content 

Link to page:    

https://www.qax-camp.com.ua/courses/web-tech/

**Comment by Nadiyk** [comment]
Verified

**Comment by ButKoff** [comment]
#663

**Comment by DmitriiNasonov** [comment]
The task isn't relevant. The "Web технології" course has been deleted
