### ISSUE TITLE
Check page work flow

### ISSUE THREAD

**Issue by ABatalov** [scholokov/qax-portal-2#481]
Please check page work flow:  

- [x] access to the page
- [x] logic on the page  
- [x] content 

Link to page:   
https://www.qax-camp.com.ua/lessons/workflow-project/

**Comment by SOlkhova** [comment]
#518

**Comment by SOlkhova** [comment]
#519

**Comment by SOlkhova** [comment]
#522

**Comment by Nadiyk** [comment]
Verified
