### ISSUE TITLE
Link to the page "Web технології" contains the word Cyrillic "технології" - Різні домени тестування - QA Матеріали

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#483]
**STR**

1. Open https://www.qax-camp.com.ua/courses/web-%d1%82%d0%b5%d1%85%d0%bd%d0%be%d0%bb%d0%be%d0%b3%d1%96%d1%97/
2. Pay attention to the URL page

**ACTUAL RESULT**
In the URL of the page "Web технології" is Ukrainian word "технології".

**EXPECTED RESULT**
URL consists only of the Latin alphabet and the word  "технології" looks like "technology"

![nwNQQY4MT5](https://user-images.githubusercontent.com/109384052/218113572-5c018d34-401c-4f1e-9685-72c479e1ba26.jpg)

**Comment by BatalovaOlha** [comment]
#480

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
resolved
