### ISSUE TITLE
There are no site requirements

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#484]
Prerequisites:
Open: https://www.qax-camp.com.ua/courses/practise/
Steps to play:

1. There are no site requirements

Actual result: There are no site requirements
Expected result: Тhere are requirements for the site

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 107.0.5304.122
![image](https://user-images.githubusercontent.com/113175298/218140573-71f0f963-14a5-4771-b677-c1eea5abb1ea.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
