### ISSUE TITLE
Prodaction environment - Header - Section "Materials" is visible to an unauthorized user

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#485]
**Preconditions:**
1. User not authorized

**Steps of reproducing:**
1. Open https://www.qax-camp.com.ua/
2. Pay attention to Header

**Actual Result:**
Section "Materials" is visible to an unauthorized user

**Expected Result:**
Section "Materials" isn't visible to an unauthorized user

**Environment:**
Windows 10, Chrome 109.0.5414.122 (64 bit)
Android 8.1.0, Chrome 109.0.5414.118
![Настройки – О браузере Chrome - Google Chrome 15 02 2023 15_40_41](https://user-images.githubusercontent.com/95171672/219043522-d13ab474-2cdf-44e5-baf0-19ac83c71864.png)
![photo_2023-02-15_15-34-43](https://user-images.githubusercontent.com/95171672/219043533-4c314d0d-bec0-4047-8680-e8eab806d839.jpg)

**Comment by DmytroMarkulych** [comment]
@DmitriiNasonov додайте наступні атрибути, та видаліть Priority- його додають РМ

**Comment by scholokov** [comment]
виправлено у вимогах

**Comment by DmitriiNasonov** [comment]
verified. bug isn't reproducing
