### ISSUE TITLE
Урок-Топік - Виділення активних лінків

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#486]
Треба придумати яким чином виділяти "лінки" у тексті. 
наразі вони мають лише помаранчовий ховер. 
а інакше ніяк не виділяються. 
іноді це не зручно
отут:
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A12775&t=8c39Hu7prTg7LSeO-0

**Comment by AlonaSarapina** [comment]
ready for testing https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=5103%3A708&t=MdkoM31fIh4kAQeR-1

**Comment by AlonaSarapina** [comment]
ready for testing https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2178%3A512&t=MdkoM31fIh4kAQeR-1

**Comment by ButKoff** [comment]
#564

**Comment by GNatala** [comment]
verified
