### ISSUE TITLE
Реєстрація - Поле вибору фото аватару

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#487]
Додати на дизайн форми реєстрації можливість загрузки файлу-картинки аватару

як наразі виглядає форма:
https://www.qax-camp.com.ua/register/

![image](https://user-images.githubusercontent.com/22824947/219069590-6197ef5a-8b70-4676-b652-99eabc6727a0.png)

нанести на дизайн:
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2178%3A511&t=8c39Hu7prTg7LSeO-0

**Comment by AlonaSarapina** [comment]
ready for testing https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2178%3A512&t=MdkoM31fIh4kAQeR-1

**Comment by ButKoff** [comment]
#565

**Comment by GNatala** [comment]
verified
