### ISSUE TITLE
[Desktop_only] Course - Сompleted lesson is indicated by a filled dot and color #E9E8EA

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/qax-portal-2#488]
**Preconditions:**
1. Log in https://www.qax-camp.com.ua/

**Steps to reproduce:**
1. Open [course with completed lesson](https://www.qax-camp.com.ua/courses/qa-basic-programs/)
2. Pay attention to how indicated completed lesson

**Actual result:** Filled dot and color **#E9E8EA**
**Expected result:** Filled dot and color **#35324B**

**Notes:** _Pay attention:_
- **Only for desktop**  completed lesson is indicated by a **filled dot** and **color #35324B** 
- **For tablet**, its indicated by a **filled dot** and **color #35324B**
- **For mobile**, its indicated by **color #FFFFFF**

**Environment:**  Windows 11, Google Chrome - 108.0.5359.73 , (64 бит)

![chrome_svt0mEJ2iL](https://user-images.githubusercontent.com/57997443/219116029-48edcdc7-00ee-4869-9c02-e4a9fc893c58.png)

![ZXDAkVrXyA](https://user-images.githubusercontent.com/57997443/219115877-b9adec2d-e0fc-40da-b10c-3eb738d12cb0.png)

**Comment by scholokov** [comment]
не враховано дуже важливий момент:
![image](https://user-images.githubusercontent.com/22824947/219076105-0f45b2a9-3fd0-4355-9609-9e3f6e5a783d.png)

**Comment by dmitryylev** [comment]
not actual

**Comment by scholokov** [comment]
не. ти не зрозумів
просто повинна бути різна поведінка на десктопі та мобілі
на десктопі - білий колір - це ховер
а на мобілі, так як немає ховера і немає місця під помаранчову кнопку - там використовується білий колір для виділення пройдених курсів

**Comment by dmitryylev** [comment]
@scholokov виправив

**Comment by scholokov** [comment]
please retest

**Comment by dmitryylev** [comment]
bug is reproduce

**Comment by GNatala** [comment]
not actual
