### ISSUE TITLE
Header - Hover - Color of the word "Матерiали" is #fff

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#49]
Steps of reproducing:
1) Open https://portal.qax-camp.com.ua/
2) Login to user account
3) Pay attention to color of the word "Матерiали"

Expected Result:
#FFFFFF

Actual Result:
#fff

Specification: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=799%3A110

Environment:
Windows 10, Chrome 105.0.5195.54 (64 bit)
![QAX Camp – Students Portal - Google Chrome 02 09 2022 17_09_20](https://user-images.githubusercontent.com/95171672/188168309-04916154-09d1-4dc3-a5f7-ce497c803fec.png)

**Comment by DmytroMarkulych** [comment]
Додайте будь ласка деталей в степи, що потрібно не просто відкрити сайт, а щей залогінитися як юзер. Тому що якщо зараз перейти за посиланням, даний UI елемент не доступний. І якщо у Вас є посилання на специфікаю, то було б дуже круто його вказати..

**Comment by DmytroMarkulych** [comment]
Трішки спателичує просто слово "Login".. Давайте додамо деталей в 2 степ

**Comment by DmytroMarkulych** [comment]
@DmitriiNasonov Трішки спантеличує просто слово "Login".. Давайте додамо деталей в 2 степ

**Comment by DmytroMarkulych** [comment]
@DmitriiNasonov Login куди?

**Comment by scholokov** [comment]
![image](https://user-images.githubusercontent.com/22824947/196450829-71e322b5-747c-43d9-a8dd-172821e5158e.png)

**Comment by DmitriiNasonov** [comment]
bug is not actual
