### ISSUE TITLE
Design Course - Comleted lesson and hover lesson are same color

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/qax-portal-2#490]
**Steps to reproduce:**
1. Open [design](https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A1036&t=LbKCUtoEySmIXVbo-0)
2. Pay attention to **completed** and **hover** lessons

**Actual result:**   Comleted lesson and hover lesson are **same color**
**Expected result:**   Comleted lesson and hover lesson are **different color**

![chrome_g7rp1Q5ECm](https://user-images.githubusercontent.com/57997443/219083054-e7d15c4b-160a-44ca-bb9f-6a708ed95345.png)

**Comment by scholokov** [comment]
тут теж, просто різна поведінка для десктопа та мобіли

**Comment by dmitryylev** [comment]
@scholokov на десктопі ховер і пройдений урок одного кольору, тобто ховер пройденого уроку ніяк не відображається

**Comment by scholokov** [comment]
просто повинна бути різна поведінка на десктопі та мобілі
на десктопі - білий колір - це ховер. коли урок виконано - помаранчова цятка.
а на мобілі, так як немає ховера і немає місця під помаранчову цятку - там використовується білий колір для виділення пройдених курсів

**Comment by dmitryylev** [comment]
not actual
