### ISSUE TITLE
no requirements for the task  #464

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#495]
Prerequisites:
Open https://www.qax-camp.com.ua/courses/testing-theory/
Steps to play:

1. no requirements for the task #464

Actual result: no requirements for the task  #464
Expected result: There are requirements for the task  #464

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.96 
![image](https://user-images.githubusercontent.com/113175298/219676682-2b1afec4-4622-4e04-adb2-cb956a0d8249.png)

**Comment by Nadiyk** [comment]
#464

**Comment by ABatalov** [comment]
Ready for testing: 
https://github.com/scholokov/qax-portal-2/wiki/1.0.1.1.-%D0%A2%D0%B5%D0%BE%D1%80%D1%96%D1%8F-%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F
