### ISSUE TITLE
Picture on the card "Особливості тестування на різних платформах" smaller then other - Крок 3. Технічні скіли - П’ять складових професійного QA - Quality Assurance Engineer (QA) (NEW)

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#499]
**STR**
1. Open https://www.qax-camp.com.ua/qa-courses/ and scroll to the "Крок 3. Технічні скіли"
2. Pay attention to the size of the pictures on the card 

**ACTUAL RESULT**
On the card "Особливості тестування на різних платформах" picture size is 326.67x193.95 and it`s NOT the same that other (326.67x217.9)

**EXPECTED RESULT**
On the card "Особливості тестування на різних платформах" picture size  is the same that other (326.67x217.9)

![ri8bmi2BFD](https://user-images.githubusercontent.com/109384052/220150758-1a7782b4-4724-44e2-a98c-5b4819519409.png)

![nmorPw2Qy0](https://user-images.githubusercontent.com/109384052/220151745-3d4c28bc-ab59-481f-adf7-e1046282807b.png)

**Comment by BatalovaOlha** [comment]
#497

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
