### ISSUE TITLE
Header - Hover - Color of the word "Головна" is #fff

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#50]
Steps of reproducing:
1) Open https://portal.qax-camp.com.ua/
2) Pay attention to color of the word "Головна"

Expected Result:
#FFFFFF

Actual Result:
#fff

Environment:
Windows 10, Chrome 105.0.5195.54 (64 bit)
![QAX Camp – Students Portal - Google Chrome 02 09 2022 17_09_20](https://user-images.githubusercontent.com/95171672/188175092-7e6c0bf5-68ab-45a6-a2f4-253461330a90.png)

**Comment by scholokov** [comment]
please retest

**Comment by DmitriiNasonov** [comment]
retested. bug is reproduced

![QAX Camp – Students Portal - Google Chrome 22 09 2022 16_31_06](https://user-images.githubusercontent.com/95171672/191763229-f4d81604-6ae3-4656-9f04-ac05c0fd263f.png)

**Comment by scholokov** [comment]
#50 #51
два бага на те саме місце, але різні експект резалти.

**Comment by DmytroMarkulych** [comment]
@DmitriiNasonov так як ці дефекти фактично дублікати, будь ласка, оберіть один, а інший прокоментуйте, що це дублікат, та закрийте його

**Comment by DmitriiNasonov** [comment]
duplicate
