### ISSUE TITLE
Picture on the cards different sizes - "Наші поточні тестові проекти" - Крок 2. Практика - П’ять складових професійного QA - Quality Assurance Engineer (QA) (NEW)

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#500]
**STR**

1. Open https://www.qax-camp.com.ua/qa-courses/ and scroll to the end of "Крок 2. Практика" 
2. Pay attention to the size of the pictures on the card

**ACTUAL RESULT**
The pictures on the card have 4 different sizes - 1) 326.66x152.05; 2) 326.67x163.39 3) 326.67x155.98 4) 326.66x160.31

**EXPECTED RESULT**
The pictures are the same size 

![aZFFjGXT4a](https://user-images.githubusercontent.com/109384052/220155408-db52452a-a922-466c-8642-79c0d7ba974d.png)
![Fo2TKxpf79](https://user-images.githubusercontent.com/109384052/220155418-20b0dc7c-d2db-4b66-b2a7-e200d971ae1c.png)

**Comment by BatalovaOlha** [comment]
#497

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
