### ISSUE TITLE
Grammatical error in link - page https://www.qax-camp.com.ua/qa-cources/

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#501]
**STR**
1. Open https://www.qax-camp.com.ua/qa-cources/
2. Pay attention to the word "cources" in the link

**ACTUAL RESULT**
The word "cources" in the link was written with a mistake using the letter "C"

**EXPECTED RESULT**
The link looks like https://www.qax-camp.com.ua/qa-**courses/** 

NOTE:
Correct writing is courses - using "S" instead of "C"

![f2abfWwW4k](https://user-images.githubusercontent.com/109384052/220172834-3beb50ca-d215-4b57-a08e-633d1f831189.png)

**Comment by BatalovaOlha** [comment]
#497

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
resolved
