### ISSUE TITLE
Grammatical error -phrase "Поряд ретесту багів" - Порядок роботи QA з новими багами - QA Workflow - Workflow на проекті

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#503]
**STR**

1. Open https://www.qax-camp.com.ua/courses/practise/lessons/workflow-project/
2. You must be login to the site.
3. Scroll to the QA Workflow and expand
4. Scroll to the "Поряд ретесту багів" and pay attention to how the phrase look

**ACTUAL RESULT**
The phrase looks like "Поряд ретесту багів"

**EXPECTED RESULT**
The phrase should look like "Порядок ретесту багів"

![9hj8Xh0bCn](https://user-images.githubusercontent.com/109384052/220700853-6f4fb38b-d8fa-4825-828f-a49dea63e680.png)

**Comment by BatalovaOlha** [comment]
#481

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
Verifed
