### ISSUE TITLE
 In the header no section "Курси в записі"

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#514]
Prerequisites:
Open: https://www.qax-camp.com.ua/
Steps to reproduce:

1. Pay attention to header no section  "Курси в записі"

Actual result: In the header no section "Курси в записі"
Expected result: In the header, there is a section called  "Курси в записі"

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.177
![кемп 2](https://user-images.githubusercontent.com/113175298/221631485-cddcd9eb-0f16-4647-80c0-472981e507c3.png)

**Comment by scholokov** [comment]
тестування проводиться не на тому середовищі

**Comment by Nadiyk** [comment]
закривати цей баг?

**Comment by scholokov** [comment]
в плані?
треба ретестнути на коректному і перевірити чи є баг? :)))

**Comment by Nadiyk** [comment]
а яке саме коректне середовище?

**Comment by DmytroMarkulych** [comment]
Якщо в контексті регресу то на проді https://www.qax-camp.com.ua/

**Comment by Nadiyk** [comment]
Вставити мені це посилання  в прекондишин  https://www.qax-camp.com.ua/

**Comment by DmytroMarkulych** [comment]
![Image](https://user-images.githubusercontent.com/88647733/224734229-26d43380-e6bc-4162-b0c9-a2e253ce0db8.png)
