### ISSUE TITLE
Description text is out of page content - Проєкт QAX Camp-Portal - Наші поточні тестові проекти - Крок 2. Практика - page Quality Assurance Engineer (QA)

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#515]
**STR**
1. Open https://www.qax-camp.com.ua/courses/project-camp-portal/ unfold "Опис" and pay attention to the description text 

**ACTUAL RESULT**
The description text is from another Camp project "Travell" and describes a travel project

**EXPECTED RESULT**
The description text describes the current project Camp-Portal 

![RcNEaPvzMy](https://user-images.githubusercontent.com/109384052/221635032-f6dbcd7e-cbf8-4778-ad24-3e0ae5fcaeaa.png)

**Comment by BatalovaOlha** [comment]
#506

**Comment by scholokov** [comment]
неактуальне

**Comment by BatalovaOlha** [comment]
no-actual
