### ISSUE TITLE
Description text is out of page content - QAX Database 2.0 - Наші поточні тестові проекти - Крок 2. Практика - Quality Assurance Engineer (QA)

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#516]
**STR**

1. Open https://www.qax-camp.com.ua/courses/project-database-2/ unfold "Опис" and pay attention to the description text

**ACTUAL RESULT**
The description text is from another Camp project "Travell" and describes a travel project

**EXPECTED RESULT**
The description text describes the current project Database

![w1i5YqwD6V](https://user-images.githubusercontent.com/109384052/221637039-a9468569-dbe2-4162-ad96-03ec04c121f6.png)

**Comment by BatalovaOlha** [comment]
#506

**Comment by scholokov** [comment]
please retest

**Comment by BatalovaOlha** [comment]
verified
