### ISSUE TITLE
The Workflow lesson description and the accordion tab have the same name

### ISSUE THREAD

**Issue by SOlkhova** [scholokov/qax-portal-2#519]
Steps to Reproduce:
   1. Open page:https://www.qax-camp.com.ua/courses/practise/lessons/workflow-project/
   2. Pay attention to the lesson description and the accordion tab have the same name

Actual Result:

   1. The lesson description and the accordion tab have the same name

Expected Result:

   1. The lesson has a description
  
Environment:

   1.  MacOS Monterey
   2. Browser: Google Version 110.0.5481.100 (Official Build) (x86_64)

Attachments:

![Screenshot 2023-03-01 at 15 55 31](https://user-images.githubusercontent.com/99362773/222173296-63a50a3e-28a1-4a40-9980-9b252aac04c9.png)

![Screenshot 2023-03-01 at 16 24 15](https://user-images.githubusercontent.com/99362773/222173365-c5e01eb5-eace-4d4b-9ef4-bab6f67faef1.png)

**Comment by SOlkhova** [comment]
@DmytroMarkulych виправила

**Comment by SOlkhova** [comment]
@DmytroMarkulych Priority прибрала)

**Comment by scholokov** [comment]
fixed

**Comment by SOlkhova** [comment]
Verified
