### ISSUE TITLE
Wiki requirements - the price on the courses page is shown as USD accept UAH

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#520]
**STR**

1. Open https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81 and pay attention to how the price look  

**ACTUAL RESULT**
The price on the courses page is shown as USD

**EXPECTED RESULT**
The price on the courses page is shown as UAH

![xJmRP60kMG](https://user-images.githubusercontent.com/109384052/222180414-73fa6845-f4ee-4094-b095-7163be59fbed.png)

![HhrDYnzVhs](https://user-images.githubusercontent.com/109384052/222180640-d9041b0b-930a-43d4-85b1-9ed8d8a99174.png)
![lZVAVVc2Xo](https://user-images.githubusercontent.com/109384052/222180780-1134a351-df43-45ad-8c6a-d390481e0b37.png)

**Comment by scholokov** [comment]
видалено колонку

**Comment by BatalovaOlha** [comment]
close bug
