### ISSUE TITLE
No placemark on the page "Quality Assurance Engineer (QA)" in contrast to Figma design

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#523]
**STR**
1. Open https://www.qax-camp.com.ua/qa-courses-2/ and pay attention to the design of the steps
2. Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=5133%3A709&t=5oNlUk0eviAnY8O5-0 and pay attention to the design of the steps

**ACTUAL RESULT**
In Figma, nearly every step is shown a placemark, and on the site, the placemark is missing

**EXPECTED RESULT**
Placemark is shown on the site as in the Figma design

![ZBA8fjz3Gw](https://user-images.githubusercontent.com/109384052/222217845-ac275912-bd37-412f-af18-77d4d4c1dc74.png)
![YKOvSBgbeQ](https://user-images.githubusercontent.com/109384052/222217860-fdbe06e6-0893-4cb7-841d-6a8a42d9815e.png)
![uWdFEww0cC](https://user-images.githubusercontent.com/109384052/222219228-ba5146ac-5d92-442f-b389-342cc3b93c24.png)

**Comment by poroskundenys** [comment]
Добавил галочку в аккардион https://prnt.sc/ma1HBccJcSZy

**Comment by BatalovaOlha** [comment]
verified
