### ISSUE TITLE
Wiki requirements 1.3. About us page /  Punctuation mistake - missed comma after "домашок…"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#524]
**Steps to reproduce:**

1. Open Wiki requirements 1.3. About us page: https://github.com/scholokov/qax-portal-2/wiki/1.3.-About-us-page
2. Scroll down to the "Як це працює?" chapter.
3. Pay attention to the text in the fourth paragraph.

**Actual result:**
There is no comma after word "**домашок…**" in the sentence -  "Тут немає “вигаданих” завдань, домашок… а є лише реальні задачі на проєкті - це твоя робота, від якої залежать інші учасники команди та проєкт загалом!  
**Expected result:**
There is comma after word "**домашок…,**" in the sentence "Тут немає “вигаданих” завдань, домашок…**,** а є лише реальні задачі на проєкті - це твоя робота, від якої залежать інші учасники команди та проєкт загалом! "

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/222425758-deddf70e-b06b-4ec8-99e5-4c02341a3ff5.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
