### ISSUE TITLE
Сreate a new image QA, PM, BA page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#525]
We need to сreate a new picture QA, PM, BA page
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=5469-749&t=8zVgE4KLSgXHPUwz-0
QA image:
![QA](https://user-images.githubusercontent.com/109460500/222654725-bf63f1a0-ad1d-4d85-ac28-4b077c5ed187.png)
PM image:
![PM](https://user-images.githubusercontent.com/109460500/222654770-90265cc8-82d5-42ec-bfd8-8cbd51474c7b.png)
BA image:
![BA](https://user-images.githubusercontent.com/109460500/222654800-692633ad-4d9b-4321-ae3b-602d3d0c54cc.png)

**Comment by AlonaSarapina** [comment]
ready for testing 
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=5469%3A749&t=Qo1i9pTD7idMz3i7-1

**Comment by ButKoff** [comment]
592

**Comment by OlhaHutsman** [comment]
verified
