### ISSUE TITLE
Test - SCRUM / Dot instead of comma after the word "спринта" in the question options "Що таке Sprint Retrospective?"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#527]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/quizzes/scrum/
2. Click on "Start Тест" under the picture.
3. Test is opened.
4. Find the question "Що таке Sprint Retrospective?"  among 16 questions.
5. Pay attention to 4-th answer option, the 2-nd sentence.

**Actual result:**
Dot is after the word "**спринта.**" in sentence "Є «пульсом» ходу **спринта.** триває не більш ніж 15 хвилин;"

**Expected result:**
Comma is after the word "**спринта,**" in sentence "Є «пульсом» ходу **спринта,** триває не більш ніж 15 хвилин;"

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/222698087-512e1e7c-59b9-4ea8-97a5-84583021448d.png)

**Comment by GNatala** [comment]
#96

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
