### ISSUE TITLE
Test - SCRUM / Dot instead of comma after the word "спринта" in the question options "Що таке Sprint Planning Meeting?"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#530]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/quizzes/scrum/
2. Click on "Start Тест" under the picture.
3. Test is opened.
4. Find the question "Що таке Sprint Planning Meeting?" among 16 questions.
5. Pay attention to the 1st answer option, the 2nd sentence.

**Actual result:**
Dot is after the word "**спринта.**" in sentence "Є «пульсом» ходу **спринта.** триває не більш ніж 15 хвилин;"

**Expected result:**
Comma is after the word "**спринта,**" in sentence "Є «пульсом» ходу **спринта,** триває не більш ніж 15 хвилин;"

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/222733430-01005184-0535-4551-b146-03ef80ed7784.png)

**Comment by GNatala** [comment]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/quizzes/scrum/
2. Click on "Start Тест" under the picture.
3. Test is opened.
4. Find the question "Що таке Sprint Planning Meeting?" among 16 questions.
5. Pay attention to the 1st answer option, the 2nd sentence.

**Actual result:**
Dot is after the word "**спринта.**" in sentence "Є «пульсом» ходу **спринта.** триває не більш ніж 15 хвилин;"

**Expected result:**
Comma is after the word "**спринта,**" in sentence "Є «пульсом» ходу **спринта,** триває не більш ніж 15 хвилин;"

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/222733430-01005184-0535-4551-b146-03ef80ed7784.png)

**Comment by GNatala** [comment]
Баг https://github.com/scholokov/qax-portal-2/issues/527 було виправлено - заміною "крапки" на "кому". Результат в реченні - "Є «пульсом» ходу спринта, триває не більш ніж 15 хвилин;"

А в https://github.com/scholokov/qax-portal-2/issues/528, https://github.com/scholokov/qax-portal-2/issues/529, https://github.com/scholokov/qax-portal-2/issues/530, https://github.com/scholokov/qax-portal-2/issues/531 було виправлено - заміною першої літери наступного після коми слова на велику. Результат в реченні- "Є «пульсом» ходу спринта. Триває не більш ніж 15 хвилин;"

Виправлення в https://github.com/scholokov/qax-portal-2/issues/527, https://github.com/scholokov/qax-portal-2/issues/528, https://github.com/scholokov/qax-portal-2/issues/529, https://github.com/scholokov/qax-portal-2/issues/530, https://github.com/scholokov/qax-portal-2/issues/531 - маєть бути однаковими.

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
