### ISSUE TITLE
In the "Курс контент" no detailed description of the topic "Види тестування"

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#532]
Prerequisites:
Open: https://www.qax-camp.com.ua/courses/q2-basic-cource/
Steps to reproduce:

1. Please note that in the topic "Види тестування" no detailed description  

Actual result: In the "Курс контент" no detailed description of the topic "Види тестування"
Expected result: In the "Курс контент" is a detailed description of the topic "Види тестування"

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104  
![Види тестування](https://user-images.githubusercontent.com/113175298/222748161-eaa96296-ad83-4d62-97f2-8abdda663a39.png)

**Comment by Nadiyk** [comment]
#466

**Comment by scholokov** [comment]
fixed
