### ISSUE TITLE
Test - SCRUM / Extra element - legend of recording states is under the Progress bar

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#533]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/quizzes/scrum/
2. Click on "Start Тест" under the picture.
3. Test is opened.
4. Pay attention to the Progress bar with number of questions under the timer.
5. Pay attention to the legend of recording states under the Progress bar.

**Actual result:**
Extra element - legend of recording states is under the Progress bar.

**Expected result:**
Extra element - legend of recording states is not under the Progress bar

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://user-images.githubusercontent.com/101987790/223672995-dc1a1ca9-83b3-4a83-a701-83a81bc9f18b.png)
![image](https://user-images.githubusercontent.com/101987790/223673315-399eebeb-883c-4d27-acdc-0189decd6ca1.png)

**Comment by GNatala** [comment]
https://github.com/scholokov/qax-portal-2/issues/96

**Comment by scholokov** [comment]
краще переробити опис, тому що "опис станів" тут зайвий

**Comment by GNatala** [comment]
Дякую, змінила.

**Comment by GNatala** [comment]
passed
