### ISSUE TITLE
The text of the course description on the mobile version has 3 different size - Базовий курс QA - Крок 1. Базова теорія - П’ять складових професійного QA - page Quality Assurance Engineer (QA) 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#535]
**STR**
1. Open https://www.qax-camp.com.ua/courses/q6-basic/ on the mobile and pay attention to the text sizes  

**ACTUAL RESULT**
The text of the course description on the mobile version has 3 different sizes - 14 / 18 / 21 Relaway

**EXPECTED RESULT**
The text size should be 21 Relaway or the text is correctly aligned in size

Note:
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=5469-750&t=jGS2aF9QDCKO6J7u-0 its page with the design were all text is 21 size

![5MvQRWRh7Z](https://user-images.githubusercontent.com/109384052/222776349-a3892e32-1362-4e9d-bdf7-955122e2f927.png)

![CR0JDDetyu](https://user-images.githubusercontent.com/109384052/222779835-cb54d2f0-91dd-4d93-970e-d9881f345510.png)

![OubL68OtQI](https://user-images.githubusercontent.com/109384052/222779859-056e338e-fef5-46bb-8792-a6a92767a1cd.png)

**Comment by scholokov** [comment]
якщо ти силаєся на дизайн, то краще вставляти силку на дизайн
