### ISSUE TITLE
"Our team" - page - block "Денис Щолоков, Founder, Trainer" - company names are shown in quotation marks

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#54]
**STR**
1. Open https://portal.qax-camp.com.ua/trainers/
2. Scroll to "Досвід роботи" in block "Денис Щолоков, Founder, Trainer"

""ACTUAL RESULT""
In a block "Денис Щолоков, Founder, Trainer" - company names are shown in quotation marks.

""EXPECTED RESULT""
In a block "Денис Щолоков, Founder, Trainer" - company names are NOT shown in quotation marks.
![Vp5vVPkx6I](https://user-images.githubusercontent.com/109384052/188276784-4be40fa8-8670-4dda-9c8b-455454e0095b.png)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
