### ISSUE TITLE
Information about the last activity in Recruiter program - shows DD.MM.YYYY and time

### ISSUE THREAD

**Issue by SOlkhova** [scholokov/qax-portal-2#540]
Steps to Reproduce:

   1. Open page: https://www.qax-camp.com.ua/courses/recruiter-program/
   2. Scroll to Progress Bar
   3. Pay attention to the information on the right of the Progress Bar
   4. Information about the last activity shows DD.MM.YYYY and time
   
Actual Result:

   1.  Information about the last activity shows DD.MM.YYYY **and time**

Expected Result:
  
 1. Information about the last activity shows DD.MM.YYYY

Attachments:
![Screenshot 2023-03-04 at 12 44 13](https://user-images.githubusercontent.com/99362773/222896722-94488a79-7681-41a9-8cbc-fe2e8c7445ad.png)
![Screenshot 2023-03-04 at 12 44 41](https://user-images.githubusercontent.com/99362773/222896726-3b4bde92-1639-4024-be47-47467b086c43.png)

**Comment by scholokov** [comment]
фігма не є  функціональними вимогами

**Comment by SOlkhova** [comment]
Так. Але якщо у вимогах відсутня інформація про відображення останньої активності на сайті, то як мені зрозуміти, який варіант правильний?

**Comment by scholokov** [comment]
- запитати у PO
- написати баг на вимоги (але це наш навчальний кейс лише, а перший варіант завжди працює)

**Comment by SOlkhova** [comment]
Дякую)

**Comment by GNatala** [comment]
Крім дати, реалізован і час також.
Closed
