### ISSUE TITLE
Title Курс Content in Recruiter program - contradicts Figma

### ISSUE THREAD

**Issue by SOlkhova** [scholokov/qax-portal-2#541]
Steps to Reproduce:

   1. Open page: https://www.qax-camp.com.ua/courses/recruiter-program/
   2. Scroll to accordion
   3. Pay attention title **Курс Content**

Actual Result:

   1.  Title has name **Курс Content**

Expected Result:

   1. Title has name - Програма курсу

Attachments:
![Screenshot 2023-03-04 at 14 38 19](https://user-images.githubusercontent.com/99362773/222901871-06424582-03c9-487e-aa06-32ee4b52b4fb.png)

**Comment by Nadiyk** [comment]
Pass
![image](https://user-images.githubusercontent.com/113175298/230345272-ab5874db-f879-4bd2-9b3f-7315e899501e.png)
