### ISSUE TITLE
Numbering of lessons Recruiter program - absent

### ISSUE THREAD

**Issue by SOlkhova** [scholokov/qax-portal-2#543]
Steps to Reproduce:

   1. Open page: https://www.qax-camp.com.ua/courses/recruiter-program/
   2. Scroll to the list of classes
   3. Pay attention to the lesson Numbering

Actual Result:

   1. Numbering of lessons - absent

Expected Result:

   1. The lessons have a number

Attachments:
![Screenshot 2023-03-04 at 15 18 57](https://user-images.githubusercontent.com/99362773/222905696-70c1c591-3f78-4317-958e-a1a560d53394.png)

**Comment by scholokov** [comment]
фігма - не є функціональними вимогами

**Comment by GNatala** [comment]
closed
