### ISSUE TITLE
The size of the Recruiter lesson preview is different from Figma

### ISSUE THREAD

**Issue by SOlkhova** [scholokov/qax-portal-2#544]
Steps to Reproduce:

   1. Open page: https://www.qax-camp.com.ua/courses/recruiter-program/
   2. Scroll to the list of classes
   3. Pay attention to the size of the preview lesson

Actual Result:

   1. Size of the preview lesson 1200 x 295,84

Expected Result:

  1. Size of the preview lesson 1200 x 198

Attachments:
![Screenshot 2023-03-04 at 15 31 40](https://user-images.githubusercontent.com/99362773/222914489-bf1dfa91-9d52-457a-a4e1-6b4de1a169ac.png)

**Comment by DmytroMarkulych** [comment]
@SOlkhova  відкрийте  devtools та спробуйте змінити ширину екрану

**Comment by SOlkhova** [comment]
@DmytroMarkulych помилка відтворюється, навіть при зміні розміру ширини екрану)

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
passed
