### ISSUE TITLE
The lesson map open/close by clicking on the arrow/ Recruiter program

### ISSUE THREAD

**Issue by SOlkhova** [scholokov/qax-portal-2#545]
Steps to Reproduce:

   1. Open page: https://www.qax-camp.com.ua/courses/recruiter-program/
   2. Scroll to the list of classes
   3. Pay attention to the lesson map open/close by clicking on the arrow

Actual Result:
   
   1. The lesson map open/close by clicking on the **Expand/Collapse** and arrow

Expected Result:

   1. The lesson map open/close ONLY by clicking on the arrow
   
Attachments:
![Screenshot 2023-03-04 at 17 36 49](https://user-images.githubusercontent.com/99362773/222917021-c1a47b3a-0fb3-4aed-afb8-c736ad654517.png)

**Comment by scholokov** [comment]
please retest

**Comment by SOlkhova** [comment]
Verified
