### ISSUE TITLE
Location of the open/close arrow of the lesson card differs from Figma/ Recruiter program

### ISSUE THREAD

**Issue by SOlkhova** [scholokov/qax-portal-2#546]
Steps to Reproduce:

   1. Open page: https://www.qax-camp.com.ua/courses/recruiter-program/
   2. Scroll to the list of classes
   3. Pay attention to the open/close arrow of the lesson card 

Actual Result:

   1. The arrow open/close is located **on the left**

Expected Result:

   1. The arrow open/close is located **on the RIGHT**

Attachments:
![Screenshot 2023-03-04 at 18 00 43](https://user-images.githubusercontent.com/99362773/222918631-84982b81-6e8a-4e4c-8876-af64565a718d.png)

**Comment by Nadiyk** [comment]
Pass
![image](https://user-images.githubusercontent.com/113175298/230347058-906689da-64fa-4139-823a-2425ac9dda76.png)
