### ISSUE TITLE
Lesson preview is NOT default/Recruiter program

### ISSUE THREAD

**Issue by SOlkhova** [scholokov/qax-portal-2#547]
Steps to Reproduce:

   1. Open page: https://www.qax-camp.com.ua/courses/recruiter-program/
   2. Scroll to the list of lesson preview
   3. Pay attention to the lesson preview is default

Actual Result:

   1. Lesson preview is DEFAULT
   
Expected Result:

   1. Lesson preview is NOT default

Attachments:
![Screenshot 2023-03-04 at 19 05 42](https://user-images.githubusercontent.com/99362773/222919697-ab2fbcb9-3eea-47cf-b46e-bae35873bc02.png)

**Comment by scholokov** [comment]
оце дефолтне. тобто саме таким не повинне бути...
![image](https://user-images.githubusercontent.com/22824947/223665530-6851f39c-ac48-413d-85d9-4cbf3d1221bd.png)

**Comment by SOlkhova** [comment]
not relevant
