### ISSUE TITLE
The description of the header in the Figma requirements does not correspond to the latest changes on the website and Wiki

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#548]
**STR**
1. Open https://www.qax-camp.com.ua/ 
2. [Open https://github.com/scholokov/qax-portal-2/wiki/1.1.1.-Header](https://github.com/scholokov/qax-portal-2/wiki/1.1.3.-Main-menu)
3. Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A22&t=DUyBoRZiQw6zksSI-0
4. Pay attention to the header and what pages are available here

**ACTUAL RESULT**
The description of the header in the Figma requirements does not correspond to the latest changes on the website

**EXPECTED RESULT**
The description of the header in the Figma requirements is the same as on the website

NB:
On the website header is Напрямки - Курси в записі - Практика - Наші тренери - Про нас - Увійти - Записатися 

![kVYsecr04C](https://user-images.githubusercontent.com/109384052/222921146-491eb91d-3849-4659-b9b4-205cbac10351.png)

![LK1KcvZsEp](https://user-images.githubusercontent.com/109384052/222921075-391080c8-42bf-475a-91ea-1d1f3e550a23.png)

**Comment by BatalovaOlha** [comment]
#482

**Comment by scholokov** [comment]
The description of the header in the Figma requirements does not correspond to the latest changes on the website and Wiki #548


у фігмі немає функціональних вимог. лише вимоги на зображення елементів. помилка суто у функціональних вимогах....
