### ISSUE TITLE
Element Instagram has moved to another line in Footer when breakpoint 1194 px

### ISSUE THREAD

**Issue by SOlkhova** [scholokov/qax-portal-2#549]
Steps to Reproduce:

   1. Open page: https://www.qax-camp.com.ua/courses/recruiter-program/
   2. Make breakpoint 1194 px
   3. Scroll down 
   4. Pay attention to the element Instagram in Footer

Actual Result:

   1. Element Instagram has moved to another line

Expected Result:

   1. Element Instagram is located on one line as other elements
  
Attachments:
![Screenshot 2023-03-05 at 17 11 47](https://user-images.githubusercontent.com/99362773/222969086-7ac44f6e-d929-4b44-85d2-9f4846a06fcf.png)

**Comment by Nadiyk** [comment]
Pass
![image](https://user-images.githubusercontent.com/113175298/230354580-c2d68ca6-0cbb-4cc3-97de-8bb6daa94e1a.png)
