### ISSUE TITLE
After clicking on the page "Матеріали" - open information "Напрямки" 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#55]
**STR**
1. Open page https://portal.qax-camp.com.ua/
2. Login 
3. Click on the button "Матеріали"

**ACTUAL RESULT**
After clicking on the button "Матеріали" - open the page with the information "Напрямки" 

**EXPECTED RESULT**
After clicking on the button "Матеріали"  the page with the information "Напрямки" NO opens and opens the page according to https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials

NOTE:
Pay attention to the page in Wiki https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials

![QAX Camp – Students Portal - Google Chrome 2022-09-03 18-58-50 (1)](https://user-images.githubusercontent.com/109384052/188280951-9e87a1cb-3993-42f3-8d59-7db01804b4ee.gif)

 
![bB7APrKeyA](https://user-images.githubusercontent.com/109384052/212670271-0fa91ac4-4c93-40c0-b325-924ea1c58cc5.png)

![HgCKMrgtva](https://user-images.githubusercontent.com/109384052/212670515-cc4e6e50-028c-4023-9449-99b762bd1a49.png)

![Tq9vWA8BzZ](https://user-images.githubusercontent.com/109384052/212670524-c532d34c-387d-415d-bf0f-75e52ad07f7b.png)

**Comment by DmytroMarkulych** [comment]
1. Додайте, будь ласка, деталів в 2-й пункт для Steps for reproduce. 
2. EXPECTED RESULT. Якщо судити по очіваному результату, то клікнуши на сторінку Матеріали, не має відкритися Напрямки.. тобто якщо навіть у нас буде 404 то це відповідає expected result. Додайте будь ласка, деталей вказавши чітко, що має бути після відкриття

**Comment by scholokov** [comment]
fixed

**Comment by DmytroMarkulych** [comment]
@BatalovaOlha краще вкажіть, що дефект відтворюється
