### ISSUE TITLE
Element Facebook has moved to another line in Footer when breakpoint 1102 px

### ISSUE THREAD

**Issue by SOlkhova** [scholokov/qax-portal-2#551]
Steps to Reproduce:

   1. Open page: https://www.qax-camp.com.ua/courses/recruiter-program/
   2. Make breakpoint 1102 px
   3. Scroll down
   4. Pay attention to the element Facebook in Footer

Actual Result:

   1. Element Facebook has moved to another line

Expected Result:

   1. Element Facebook is located on one line as other elements

Attachments:
![Screenshot 2023-03-05 at 17 54 38](https://user-images.githubusercontent.com/99362773/222971491-9997e529-da0d-457d-a040-b2ab695fe8fd.png)

**Comment by Nadiyk** [comment]
Pass
![image](https://user-images.githubusercontent.com/113175298/230355227-d598bf6d-d4cb-45d3-b02f-a2e184fc58ae.png)
