### ISSUE TITLE
QA Courses - Implement block content "Крок 2. Практика" on the page "Quality Assurance Engineer (QA)" according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#554]
We need implement block content "Крок 2. Практика" according to Figma for desktop, tablet and mobile.
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=1412%3A425&t=Y8IoCOvpnDYzD47r-0
Product environment: https://www.qax-camp.com.ua/qa-courses/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.0.1.--Quality-Assurance-Engineer-(QA)
![Крок 2_Приктика](https://user-images.githubusercontent.com/109460500/223061526-4a60db95-a42a-43c9-89c6-24fbde1d85e3.png)

**Comment by poroskundenys** [comment]
Я вижу отличие между дизайном и тем, что сейчас на странице только в этом элементе https://prnt.sc/hirlobtcHJU3. Только его добавить?

**Comment by scholokov** [comment]
різниця:
- графічний елемент. але щоб у нас був вибір з 2 акордеонів. тобто старий (без картинки) не затирати
- форматування тексту. він більш менш на десктопі, а таблет і мобіла - трешака
