### ISSUE TITLE
Test SCRUM / Elements of Progress bar with number of questions is in a different than required colors: #235af3, #8224e3,  #74d62f

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#555]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/quizzes/scrum/
2. Click on "Start Тест" under the picture.
3. Test is opened.
4. Pay attention to the Progress bar with number of questions under the timer.
5. Pay attention to colors of the Progress bar.

**Actual result:**
Elements of Progress bar with number of questions is implemented in different than required colors: #235af3, #8224e3, 
#74d62f

**Expected result:**
Elements of Progress bar with number of questions is implemented in required colors: #F66F5D, #F7F7F7, 
#3E3B5E

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://user-images.githubusercontent.com/101987790/223107576-5df17dbf-b6d9-4027-8a8a-338290a796e1.png)
![image](https://user-images.githubusercontent.com/101987790/223739643-d3baff88-6e9a-4a6a-acf5-a3a057af84d0.png)

![image](https://user-images.githubusercontent.com/101987790/223734808-229e5c55-8cbd-4eb3-b7b5-9ecd7c44b499.png)

**Comment by GNatala** [comment]
https://github.com/scholokov/qax-portal-2/issues/96

**Comment by scholokov** [comment]
на фігмі зліва розписано, яке значення має кожний колір.
а справа - як має бути
тобто помилка є, але у тому, що саме не повинно бути тих надписів
ну і звісно, що кольори не збігаються
![image](https://user-images.githubusercontent.com/22824947/223664749-da393d1b-2606-4893-98a5-1fd951011af1.png)

**Comment by GNatala** [comment]
Дякую. На те, що не має бути написів переробила #533 . 
А в цьому випадку маю на увазі, що елемент "Review" зайвий і відсутній в вимогах. Може краще сказати, що це не елемент, в Стан системи?

**Comment by scholokov** [comment]
я думаю, що в даному випадку буде достатньо сказати, що різні кольори. а там уже дивитися на реалізацію

**Comment by GNatala** [comment]
Відредагувала

**Comment by GNatala** [comment]
passed
