### ISSUE TITLE
Create design of "Практика" page on Portal Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#556]
We need to create design of "Практика" page on Portal Figma.
Product environment: https://www.qax-camp.com.ua/practice/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=5444-749&t=YBACVWuLdixy8BMx-0
Database Icons: https://www.flaticon.com/search?word=Database&k=1678282894871&sign-up=google
Project pictures:
![Camp_portal](https://user-images.githubusercontent.com/109460500/223729076-cdfbe198-4d31-40cc-abc0-0051d8e4f165.jpg)
![Database](https://user-images.githubusercontent.com/109460500/223729095-00d81acc-c1ba-4818-9d1b-bb509737598d.jpg)
![Outsource](https://user-images.githubusercontent.com/109460500/223729117-a6795c93-6ec9-4623-bbbb-dae3ba91090f.jpg)
![Travel](https://user-images.githubusercontent.com/109460500/223729151-6d291ac0-63a8-4aed-8280-949ba4372615.jpg)

**Comment by AlonaSarapina** [comment]
Desktop version ready for testing 
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=5444%3A750&t=MTvllxGKCt2RKVH2-1

**Comment by ButKoff** [comment]
#628

**Comment by GNatala** [comment]
passed
