### ISSUE TITLE
Test SCRUM / Timer shows spent time on the scale from right to left

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#557]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/quizzes/scrum/
2. Click on "Start Тест" under the picture.
3. Test is opened.
4. Pay attention to the scale of the Timer.

**Actual result:**
Timer shows spent time on the scale from right to left.

**Expected result:**
Timer shows spent time on the scale from left to right.

**Додаткова інформація:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=931%3A91&t=Ea1k4niGY92Vjp1p-0

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/223748770-bd2d11ab-1af2-44bd-84a1-206f279a583e.png)
![image](https://user-images.githubusercontent.com/101987790/224362674-0db668b5-27a7-4fa8-83ca-f31136eaf65b.png)

**Comment by GNatala** [comment]
https://github.com/scholokov/qax-portal-2/issues/96

**Comment by scholokov** [comment]
ттак як баг по дизайну - додайте ще пліз лінку на дизайн (фігму)

**Comment by GNatala** [comment]
Дякую. Додала.

**Comment by DmytroMarkulych** [comment]
@GNatala Лінку можна додати як "Додаткова інформація"

**Comment by GNatala** [comment]
Дякую, додала лінку в "Додаткову інформацію"

**Comment by DmytroMarkulych** [comment]
@GNatala і прибрати із кроків для відтворення. В загальному, якщо у нас є специфікація чи інформація яка дає змогу більше зрозуміти проблему то її варто додавати як Додаткова інформація

**Comment by GNatala** [comment]
Дякую, прибрала із кроків для відтворення.

**Comment by scholokov** [comment]
не зрозумів. воно ж так і працює...


![Image](https://user-images.githubusercontent.com/22824947/225283985-6e9b63c7-34be-4b99-aedc-893a70c47023.png)

**Comment by GNatala** [comment]
Трохи ні. Якщо вважати, що таймер показує час, котрий лишився, то при однаковому залишку часу 2.40 (як на скріншоті), картинки мають бути однаковими.
А у нас:
**Actual result: Помаранчeвий "бігунець" зменшується вліво.**

**Expected result: Помаранчeвий "бігунець" збільшується вправо.**

![image](https://user-images.githubusercontent.com/101987790/225306184-45da07e0-8557-4378-bc28-5fbe3cc4a85b.png)

**Comment by scholokov** [comment]
виправлено у фігмі

**Comment by GNatala** [comment]
checked
