### ISSUE TITLE
The block "Що таке регресія" is described in Russian

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#558]
Prerequisites:
Open:  https://www.qax-camp.com.ua/courses/testing-theory/
Steps to reproduce:

1.  Scroll to the item "Щто такоє регресія"

Actual result:  The block "Що таке регресія" is described in Russian
Expected result: The block "Що таке регресія" is described in Ukrainian

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104  
![regresia](https://user-images.githubusercontent.com/113175298/223773323-2291b924-8f7c-45d3-810c-c638438a027c.png)

**Comment by Nadiyk** [comment]
#464

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
Що робити в випадку якщо перевіряю чи виправлено, відкриваю посилання, а сторінки не існує?
![image](https://github.com/scholokov/qax-portal-2/assets/113175298/25206ef3-268d-4d31-aa65-5663d664de0f)

**Comment by scholokov** [comment]
бо урок переїхав у інший курс
https://www.qax-camp.com.ua/courses/testing/lessons/regression/

**Comment by Nadiyk** [comment]
актуально буде змінити в цьому багу URL на цю яку ви вище вказали?

**Comment by Nadiyk** [comment]
ну якщо не роблять то і я робити не буду.
По цій https://www.qax-camp.com.ua/courses/testing/lessons/regression/ 
є баги, я заведу і прикріплю до задачі https://github.com/scholokov/qax-portal-2/issues/464

**Comment by Nadiyk** [comment]
Pass
