### ISSUE TITLE
GitHub Wiki - 1.0.1. Quality Assurance Engineer (QA) - Spelling error in tool name: M* iro

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#559]
**Steps of reproducing:**
1.  Open https://github.com/scholokov/qax-portal-2/wiki/1.0.1.--Quality-Assurance-Engineer-(QA)
2. Scroll to headline "Крок 2. Практика"
3. Scroll to list "Твої інструменти:"
4.  Pay attention to last tool name at last line

**Actual Result**
tool name is "M* iro"

**Expected Result**
tool name is "Miro"

**Enviroments**
Windows 10, Chrome 110.0.5481.178 (64 bit)
![1 0 1  Quality Assurance Engineer (QA) · scholokov_qax-portal-2 Wiki - Google Chrome 08 03 2023 17_41_42](https://user-images.githubusercontent.com/95171672/223772841-125b51ea-d3ba-4d2f-8213-a0389bca5c9d.png)

**Comment by DmytroMarkulych** [comment]
@DmitriiNasonov 
Давайте приберемо слово Wrong бо воно не несе ніякої корисної інформації і є загальним. 
Не забуваємо ставити атрибути 

![Image](https://user-images.githubusercontent.com/88647733/223825706-fb338d8f-4c8c-40da-bf8d-1ce730e26fdb.png)

**Comment by DmitriiNasonov** [comment]
corrected

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
verified. bug sin't reproducing
