### ISSUE TITLE
Test SCRUM / Button "Finish Тест" does not match design in Figma

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#562]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/quizzes/scrum/
2. Click on "Start Тест" under the picture.
3. Test is opened.
4. Click on the last question of the test.
5. Pay attention to the button "Finish Тест" that appears under the list of answers.

**Actual result:**
Button is named "Finish Тест" and does not match the design in Figma.

**Expected result:**
Button is named "Закінчити тест" and has design according to Figma.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/224292861-84f84e51-0584-4e96-a728-fc79d3339ea5.png)
![image](https://user-images.githubusercontent.com/101987790/224294149-583fefef-2f0a-4628-98b7-d6a6a9b6debc.png)

**Comment by GNatala** [comment]
https://github.com/scholokov/qax-portal-2/issues/96

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
An issue is reproduced.

**Actual result:**
Button is named "**Finish Тест**" and does not match the design in Figma - font size 15.75px, font-weight 800, Padding
15.75px, 15.75px, 15.75px, 15.75px.
**Expected result:**
Button is named "**Закінчити тест**" and has design according to Figma  - font size 18px, font-weight 500, Padding
10px, 30px, 10px, 30px

![Image](https://user-images.githubusercontent.com/101987790/225346830-27b26653-e2ff-48ee-aa8b-f65fa61ccfc3.png)

![Image](https://user-images.githubusercontent.com/101987790/225341571-adb0efa8-6e7c-4b11-aa58-0d0304e73216.png)

**Comment by GNatala** [comment]
passed
