### ISSUE TITLE
Test SCRUM / Summary of test results is displayed in English

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#563]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/quizzes/scrum/
2. Click on "Start Тест" under the picture.
3. Test is opened.
4. Click on the last question of the test.
5. Click on the button "Finish Тест". 
6. Summary of test results is displayed.
7. Pay attention to the language of the Summary.

**Actual result:**
Summary of test results is displayed in **English and Ukrainian.**

**Expected result:**
Summary of test results is displayed in **Ukrainian.**

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/224360445-78cac73b-0933-4af4-9650-528c3bd97330.png)

**Comment by GNatala** [comment]
https://github.com/scholokov/qax-portal-2/issues/96

**Comment by scholokov** [comment]
таблицю видалено
на інше, буд ласка, створіть окремий баг
