### ISSUE TITLE
Сourses - Topic - Implement anchor link according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#564]
We need Implement anchor link according to figma on all pages with URL:
https://www.qax-camp.com.ua/courses ...
https://www.qax-camp.com.ua/topic ...
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A12775&t=9YH47dfQ2xZA3w4L-0
![Anchor link](https://user-images.githubusercontent.com/109460500/224528928-f2915fed-07dc-47cc-bd17-e07e842174b3.png)

**Comment by ButKoff** [comment]
#486

**Comment by poroskundenys** [comment]
@ButKoff По ссылкам в описании нет примера с ссылками. У меня открываются страницы нет текста

**Comment by ButKoff** [comment]
@poroskundenys This is an example: https://www.qax-camp.com.ua/courses/project-travel/lessons/travel-2-0/
![Anchor link](https://user-images.githubusercontent.com/109460500/226113959-59d3e870-71b7-4461-9563-a0bb0db0b371.png)

**Comment by GNatala** [comment]
verified
