### ISSUE TITLE
Cources - Implement block "Відгуки про курси"

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#566]
We need to implement block "Відгуки про курси" on pages above block "Записатися на курс".
Pages for implementation:
1. https://www.qax-camp.com.ua/current_cources/
2. https://www.qax-camp.com.ua/qa-courses/
3. https://www.qax-camp.com.ua/pm-courses/
4. https://www.qax-camp.com.ua/ba-courses/
5. https://www.qax-camp.com.ua/practice/

![Відгуки про курси](https://user-images.githubusercontent.com/109460500/224535526-26ebeda5-760e-4042-938f-2ba023a1adfc.png)

**Comment by scholokov** [comment]
@poroskundenys

**Comment by poroskundenys** [comment]
Чтобы вывести отзывы на странице нужно поменять шаблон на review https://prnt.sc/FCntmFj3tViV

**Comment by poroskundenys** [comment]
Для курса мне нужен пример куда выводить

**Comment by scholokov** [comment]
поки виводимо лише на "сторінку". тобто все ок

**Comment by GNatala** [comment]
verified
