### ISSUE TITLE
No placemark on the page "Business Analyst (BA)" in contrast to Figma design 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#567]
**STR**

1. Open https://www.qax-camp.com.ua/ba-courses-2/ and pay attention to the design of the steps 
2. Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=5133%3A709&t=5oNlUk0eviAnY8O5-0 and pay attention to the design of the steps

**ACTUAL RESULT**
In Figma, nearly every step is shown a placemark, and on the site, the placemark is missing

**EXPECTED RESULT**
Placemark is shown on the site as in the Figma design

![NFl3Zku05D](https://user-images.githubusercontent.com/109384052/224536508-aaf95a33-1865-4e08-bfaa-6c036ef823be.png)

**Comment by BatalovaOlha** [comment]
#509

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
