### ISSUE TITLE
No placemark on the page "Project Manager (PM)" in contrast to Figma design

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#568]
**STR**

1. Open https://www.qax-camp.com.ua/pm-courses-2/ and pay attention to the design of the steps
2. Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=5133%3A709&t=5oNlUk0eviAnY8O5-0 and pay attention to the design of the steps

**ACTUAL RESULT**
In Figma, nearly every step is shown a placemark, and on the site, the placemark is missing

**EXPECTED RESULT**
Placemark is shown on the site as in the Figma design

![SVdnXBcF8k](https://user-images.githubusercontent.com/109384052/224537630-5768e9e3-eb5b-47e6-955c-e82a555d0eef.png)

**Comment by BatalovaOlha** [comment]
#508

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
