### ISSUE TITLE
Test SCRUM / Font of the question numbers in Progress bar is Raleway

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#569]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/quizzes/scrum/
2. Click on "Start Тест" under the picture.
3. Test is opened.
4. Pay attention to the font of the question numbers in Progress bar under the timer.

**Actual result:**
Font of the question **numbers in Progress bar is Raleway**.

**Expected result:**
Font of the question **numbers in Progress bar is Rubik**.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional іnformation:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=931%3A91&t=Ea1k4niGY92Vjp1p-0

**Attachment:**

![image](https://user-images.githubusercontent.com/101987790/224554809-0da7bbbf-69b4-4f96-a2e2-b202610c6e29.png)

**Comment by GNatala** [comment]
https://github.com/scholokov/qax-portal-2/issues/96

**Comment by DmytroMarkulych** [comment]
@GNatala Pay attention.. варто вказувати як останній крок в кроках для відтворення

**Comment by GNatala** [comment]
Дякую, змінила.

**Comment by GNatala** [comment]
Closed. Relared to #602
