### ISSUE TITLE
The section is described "Как работают веб приложения Front-and Back-end " Russian language

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#572]
Prerequisites:
Open: https://www.qax-camp.com.ua/courses/web-tech/
Steps to reproduce:

1. Pay attention to the section

Actual result:  The section is described as "Как работают веб приложения Front-and Back-end " Russian language
Expected result:  The section is described as "Как работают веб приложения Front-and Back-end " Ukrainian language

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104     
 
![front and beck](https://user-images.githubusercontent.com/113175298/224704579-d421b363-4105-489a-ad4b-5bf4dc33ef9a.png)

**Comment by Nadiyk** [comment]
#480

**Comment by Nadiyk** [comment]
not actual

**Comment by scholokov** [comment]
Please retest to update the current status

**Comment by Nadiyk** [comment]
Не можу повторити перевірку
https://www.qax-camp.com.ua/courses/web-tech/

**Comment by scholokov** [comment]
як варіант - зазирнути у вимоги і знайти актуальну лінку до курсу (а от якщо там будуть якісь проблеми - говорити про проблему). а бо пошукати вручну :)

**Comment by Nadiyk** [comment]
У вимогах пошукала, мова іде про веб додатки, я думаю по цій лінці ми маємо знайти потрібний розділ  "Як працюють веб додатки фронтент та бекенд"  але лінка не працює 
![image](https://github.com/scholokov/qax-portal-2/assets/113175298/91380166-673a-4795-a4a6-18d4237244b1)

**Comment by Nadiyk** [comment]
Уроку немає на сайті, баг не актуальний
