### ISSUE TITLE
The section "HTML-валідатори" described in Russian

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#573]
Prerequisites:
Open: https://www.qax-camp.com.ua/courses/web-tech/
Steps to reproduce:

1. Pay attention to the section "HTML- CSS валідатори"

Actual result: "HTML- CSS валидаторы"
Expected result: "HTML - CSS валідатори"

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104     
![ШТМЛ валідатори](https://user-images.githubusercontent.com/113175298/224726813-599611c4-2ba7-4c87-97d8-5bbb46fcdc4a.png)

**Comment by Nadiyk** [comment]
#480

**Comment by Nadiyk** [comment]
corrected

**Comment by scholokov** [comment]
please retest to update  status

**Comment by Nadiyk** [comment]
Що робити коли я не можу повторити перевірку?

![image](https://github.com/scholokov/qax-portal-2/assets/113175298/6434d269-ff34-4145-b387-04f77288b163)

**Comment by scholokov** [comment]
як варіант - зазирнути у вимоги і знайти актуальну лінку до курсу (а от якщо там будуть якісь проблеми - говорити про проблему). а бо пошукати вручну :)

**Comment by Nadiyk** [comment]
Щоб знайти актуальну лінку у вимогах спробувала відкрити цей розділ і ця лінка також не працює
Quality Assurance Engineer (QA)](https://www.qax-camp.com.ua/qa-courses-2/)

**Comment by Nadiyk** [comment]
уроку намає на сайті, баг не актуальний
