### ISSUE TITLE
Test SCRUM / Numbers of questions in Progress bar is reduced from 16 to 14 in breakpoint 479px

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#574]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/quizzes/scrum/
2. Click on "Розпочати тест" under the picture.
3. Test is opened.
4. Make breakpoint 479px.
5. Pay attention to the number of questions in Progress bar under the timer.

**Actual result:**
**Numbers of questions** in Progress bar **is reduced to 14 ,  2 questions are not shown.**

**Expected result:**
**Numbers of questions** in Progress bar **is 16**.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/224745755-b2e77c3a-d99f-4ea6-84ec-56b5ef86eb5b.png)
![image](https://user-images.githubusercontent.com/101987790/224746812-d9c92f80-9972-42e5-bdb8-dedad57a866d.png)

**Comment by GNatala** [comment]
#96

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
An issue is reproduced in Chrome, Opera, Mozilla and mobile.

![image](https://user-images.githubusercontent.com/101987790/225296969-92218e35-6ad1-49e3-9dd0-19d613ac72b2.png)
