### ISSUE TITLE
Courses - Check course for "Основи проектного менеджменту" page

### ISSUE THREAD

**Issue by ABatalov** [scholokov/qax-portal-2#578]
Please check page:  

- [ ] access to the page
- [ ] logic on the page  
- [ ] content 
- [ ] any other checks that you think is important

Link to page:   

https://www.qax-camp.com.ua/courses/pm-basics/

**Comment by ABatalov** [comment]
@scholokov added one free check point )

**Comment by ButKoff** [comment]
#663
