### ISSUE TITLE
Tests - Results - Створити дизайн

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#581]
Створити дизайн до сторінки результатів тесту:

![image](https://user-images.githubusercontent.com/22824947/225287905-2fbf9fc4-3412-43f0-833e-eb488d687b9b.png)

![image](https://user-images.githubusercontent.com/22824947/225288004-c63e08a3-0666-4140-9904-adf1345567bb.png)

![image](https://user-images.githubusercontent.com/22824947/225288072-e020ee74-6fab-4429-90db-c45d64223db3.png)

**Comment by AlonaSarapina** [comment]
ready for testing
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=1218%3A415&t=IytRh9nIfvOxUqCl-1

**Comment by ButKoff** [comment]
#632
