### ISSUE TITLE
Size of button " Згорнути" is 16px .

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/qax-portal-2#590]
**Pre-conditions:**
Open https://www.qax-camp.com.ua/

**Steps to reproduce:**

1.Scroll down to the bootom of the page.
2.Find the block "Історії успіху''.
3.Click on button "Дивитися усіх ".
4. Click on button "Згорнути".

**Actual result:**
Size of button " Згорнути" is 16px .

**Expected result:**
Size of button " Згорнути" is 18px  according [requirements](https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=3555-4076&t=5UQvXsdbW2V0Ar3S-0)

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![PUwFdj1k2P](https://user-images.githubusercontent.com/123729744/225866273-2ff78196-0da2-4d5f-9f23-4385f1977d6d.png)

**Comment by OlhaHutsman** [comment]
#472

**Comment by poroskundenys** [comment]
Панель лучше размещать с низу, тогда не меняется ширина проверяемой области https://prnt.sc/O12TT-1svfol

**Comment by OlhaHutsman** [comment]
@poroskundenys verified
