### ISSUE TITLE
Grammar mistake in word "документаціі" in text at the top of the page.

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/qax-portal-2#591]
**Pre-conditions:**
Open https://www.qax-camp.com.ua/qa-courses-2/

**Steps to reproduce:**

1.Find the block of description of Quality Assurance Engineer (QA).
2.Pay attention to the word "документаціі''.

**Actual result:**
The word "документаціі'' is written with "і"

**Expected result:**
The word "документаціі''  is written with "ї"

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![grammar](https://user-images.githubusercontent.com/123729744/225877550-26828572-2b54-470d-a913-727dd09017d1.png)

**Comment by OlhaHutsman** [comment]
#497

**Comment by scholokov** [comment]
fixed

**Comment by OlhaHutsman** [comment]
@scholokov verified
