### ISSUE TITLE
All zeroes are allowed for filling the form of phone number in block  "Записатися на курс".

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/qax-portal-2#600]
**Pre-conditions:**
Open https://www.qax-camp.com.ua/qa-courses-2/

**Steps to reproduce:**

1.Scroll down to the bottom of the page
2.Find block "Записатися на курс".
3.Click on form of phone number.
4.Fill in the form with all zeroes.

**Actual result:**
All zeroes are allowed for filling the form of phone number in block   "Записатися на курс".

**Expected result:**
Two subsequent zeros  at the border between Country Code and Operator Code are not allowed for filling the form of phone number in block   "Записатися на курс" acoording [requirements](https://github.com/scholokov/qax-portal-2/wiki/1.5.-Form).

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![mnnBoTpRks](https://user-images.githubusercontent.com/123729744/226115824-23ab2a09-27a8-4228-8238-782052206cb3.png)

**Comment by OlhaHutsman** [comment]
#497

**Comment by DmytroMarkulych** [comment]
![Image](https://user-images.githubusercontent.com/88647733/226175387-2d781c58-7a06-4dae-b037-19ebe854d0d0.png)

**Comment by OlhaHutsman** [comment]
@DmytroMarkulych edited
