### ISSUE TITLE
The word " проект" is written   with letter "е"   in the block   Крок 2. Практика

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/qax-portal-2#601]
**Pre-conditions:**
Open https://www.qax-camp.com.ua/qa-courses-2/

**Steps to reproduce:**

1.Scroll down to the block Крок 2. Практика
2.Pay attention to the word " проект"  with letter "е"

**Actual result:**
The word " проект"is written   with letter "е"   in the block Крок 2. Практика

**Expected result:**
The word " проект"is written   with letter "є"   in the block Крок 2. Практика

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)
![project](https://user-images.githubusercontent.com/123729744/226116381-9e6bfa27-d33f-41a4-affc-c13e9bde939f.png)

**Comment by OlhaHutsman** [comment]
#497

**Comment by scholokov** [comment]
fixed

**Comment by OlhaHutsman** [comment]
@scholokov  verified
