### ISSUE TITLE
Test Defect / Content of the question "Правильно ли утверждение: Баг — это отклонение фактического результата от ожидаемого результата?" and answers are in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#603]
**Steps to reproduce:**
1. Open https://www.qax-camp.com.ua/courses/q2-basic-cource/lessons/q2-04-%d0%b4%d0%b5%d1%84%d0%b5%d0%ba%d1%82/quizzes/deffect/
2. Click on "Розпочати Тест" under the picture.
3. Test is opened.
4. Find question "Правильно ли утверждение: Баг — это отклонение фактического результата от ожидаемого результата?".
5. Pay attention to the language of the content of the question and answers.

**Actual result:**
**Content of the question** "Правильно ли утверждение: Баг — это отклонение фактического результата от ожидаемого результата?" **and answers are in russian**.

**Expected result:**
**Content of the question** "Правильно ли утверждение: Баг — это отклонение фактического результата от ожидаемого результата?" **and answers are in Ukranian.**

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://user-images.githubusercontent.com/101987790/226175204-8a28f1a7-37f8-4fa9-bf55-b124912c3768.png)

**Comment by GNatala** [comment]
#86

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
