### ISSUE TITLE
Test Defect / No Progress bar with number of questions under the timer

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#604]
**Steps to reproduce:**
1. Open https://www.qax-camp.com.ua/courses/q2-basic-cource/lessons/q2-04-%d0%b4%d0%b5%d1%84%d0%b5%d0%ba%d1%82/quizzes/deffect/
2. Click on "Розпочати Тест" under the picture.
3. Test is opened.
4. Pay attention to the place under the timer.

**Actual result:**
**No Progress bar** with number of questions under the timer.

**Expected result:**
**Progress bar with number of questions is under the timer.**

**Additional information:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=931-91&t=cF5vwEobCy3PRQtA-0

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/226178048-3c56067a-3ddf-4e7e-93d4-0653aaadef42.png)

![image](https://user-images.githubusercontent.com/101987790/226177994-52acb421-fe4b-40e6-8f56-121602e175cf.png)

**Comment by GNatala** [comment]
#86

**Comment by GNatala** [comment]
An issue is reproduced.

**Actual result:** **No Progress bar** with number of questions under the timer.

**Expected result:** **Progress bar with number of questions is under the timer.**

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/227342315-8c500a50-1c96-4f27-86a0-1187b3592e1e.png)

![image](https://user-images.githubusercontent.com/101987790/227322359-951df9c2-2c22-4c42-b8a8-6384dbe0a9a0.png)

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
An issue is reproduced. **Сache was cleaned.**

**Actual result:** **No Progress bar** with number of questions under the timer.

**Expected result:** **Progress bar with number of questions is under the timer.**

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64), Mozilla 111.0.1,  мобільних Android 8.1.0 Chrome 111.0.5563.116

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/229057754-75a61e0f-d64f-4fda-b15b-3c8c029f537c.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
