### ISSUE TITLE
Test Defect / Mis font of the question "Яку пріорітетність  має наступний баг “В описі ноутбука на  ...”  - font style is italic, font weight 400

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#605]
**Steps to reproduce:**
1. Open https://www.qax-camp.com.ua/courses/q2-basic-cource/lessons/q2-04-%d0%b4%d0%b5%d1%84%d0%b5%d0%ba%d1%82/quizzes/deffect/
2. Click on "Розпочати Тест" under the picture.
3. Test is opened.
4. Find question "Яку пріорітетність має наступний баг “В описі ноутбука на сайті вказали суму 1 000 грн замість 10 000".
5. Pay attention to the font of the name of the question.

**Actual result:**
**Name of the question** "Яку пріорітетність має наступний баг “В описі ноутбука на сайті вказали суму 1 000 грн замість 10 000” - **font style is italic, font weight 400.**

**Expected result:**
**Name of the question** "Яку пріорітетність має наступний баг “В описі ноутбука на сайті вказали суму 1 000 грн замість 10 000” - **font style is normal, font weight 700.**

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/226187976-51ee4cb3-1d4c-4dc9-a941-f91da48e67de.png)

**Comment by GNatala** [comment]
#86

**Comment by DmytroMarkulych** [comment]
@GNatala Вийшов великий баг репорт по інформації. Як його можна скоротити, щоб зробити не таким громіздким

**Comment by GNatala** [comment]
@DmytroMarkulych  Дякую. Скоротила, як могла. В системі є 2 майже однакових питання і шукати їх можна тільки по назві.

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
An issue is reproduced.

**Actual result:**
**Name of the question** "Яку пріорітетність має наступний баг “В описі ноутбука на сайті вказали суму 1 000 грн замість 10 000” - **font weight 400.**

**Expected result:**
**Name of the question** "Яку пріорітетність має наступний баг “В описі ноутбука на сайті вказали суму 1 000 грн замість 10 000” - **font weight 700.**

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/227456729-0ea807c5-38ec-43d5-ae3a-31a9eefed641.png)

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
An issue is reproduced. **Сache was cleaned.**

Actual result:
Name of the question "Яку пріорітетність має наступний баг “В описі ноутбука на сайті вказали суму 1 000 грн замість 10 000” - font weight 400.

Expected result:
Name of the question "Яку пріорітетність має наступний баг “В описі ноутбука на сайті вказали суму 1 000 грн замість 10 000” - font weight 700.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64), Mozilla 111.0.1,  мобільних Android 8.1.0 Chrome 111.0.5563.116

**Environment:**
![image](https://user-images.githubusercontent.com/101987790/228907390-24a94e53-7405-468b-bb36-a433c4b75e4b.png)
![image](https://user-images.githubusercontent.com/101987790/228910254-85fda811-d610-475b-b7ec-1f11ecd771bc.png)

**Comment by scholokov** [comment]
останній опис відрізняється від первинного
буд ласка створіть новий баг

**Comment by GNatala** [comment]
passed
