### ISSUE TITLE
Test Defect / Mis font of the name of the question "Що має містити в собі обов’язково хороший баг репорт?” - font style is italic, font weight 400

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#606]
**Steps to reproduce:**
1. Open https://www.qax-camp.com.ua/courses/q2-basic-cource/lessons/q2-04-%d0%b4%d0%b5%d1%84%d0%b5%d0%ba%d1%82/quizzes/deffect/
2. Click on "Розпочати Тест" under the picture.
3. Test is opened.
4. Find question "Що має містити в собі обов’язково хороший баг репорт?".
5. Pay attention to the font of the name of the question.

**Actual result:**
**Name of the question** "Яку пріорітетність має наступний баг “Що має містити в собі обов’язково хороший баг репорт?"- **font style is italic, font-weight 400.**

**Expected result:**
**Name of the question** "Що має містити в собі обов’язково хороший баг репорт?” - **font style is normal, font-weight 700.**

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/226191651-7219d46b-0dae-4a9f-b16e-0cf360d15cba.png)

**Comment by GNatala** [comment]
#86

**Comment by GNatala** [comment]
An issue is reproduced.

**Actual result:**
**Name of the question** "Яку пріорітетність має наступний баг “Що має містити в собі обов’язково хороший баг репорт?"- **font-weight 400.**

**Expected result:**
**Name of the question** "Що має містити в собі обов’язково хороший баг репорт?” - **font-weight 700.**

**Attachment:**![image](https://user-images.githubusercontent.com/101987790/227340968-47e1fbc9-287d-45b4-ad8f-284dd6f1fbeb.png)

**Comment by GNatala** [comment]
An issue is reproduced.  **Сache was cleaned.**

**Actual result:**
**Name of the question** "Яку пріорітетність має наступний баг “Що має містити в собі обов’язково хороший баг репорт?"- **font-weight 400.**

**Expected result:**
**Name of the question** "Що має містити в собі обов’язково хороший баг репорт?” - **font-weight 700.**

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64), Mozilla 111.0.1,  мобільних Android 8.1.0 Chrome 111.0.5563.116
 
![image](https://user-images.githubusercontent.com/101987790/228913635-7494407a-fe31-4b1a-909e-ba7c975726c6.png)

**Comment by scholokov** [comment]
поточна помилка відрізняється від попереднього
буд ласка створіть новий баг

**Comment by GNatala** [comment]
passed
