### ISSUE TITLE
Test Defect / Mis font of the name of the question "Виберіть правильно описаний Title” - font style is italic, font weight 400

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#608]
**Steps to reproduce:**
1. Open https://www.qax-camp.com.ua/courses/q2-basic-cource/lessons/q2-04-%d0%b4%d0%b5%d1%84%d0%b5%d0%ba%d1%82/quizzes/deffect/
2. Click on "Розпочати Тест" under the picture.
3. Test is opened.
4. Find question "Виберіть правильно описаний Title".
5. Pay attention to the font of the name of the question.

**Actual result:**
**Name of the question** "Виберіть правильно описаний Title” - **font style is italic, font weight 400.**

**Expected result:**
**Name of the question** "Виберіть правильно описаний Title” - **font style is normal, font weight 700.**

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/226274598-d667f579-3563-44e5-ac7a-07b9ca95b2b9.png)

**Comment by GNatala** [comment]
#86

**Comment by scholokov** [comment]
fixed

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
An issue is reproduced.

**Actual result:**
**Name of the question** "Виберіть правильно описаний Title” - **font weight 400.**

**Expected result:**
**Name of the question** "Виберіть правильно описаний Title” - **font weight 700.**

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/228800886-308cdc43-4821-4615-9325-4a38cd9de059.png)

**Comment by scholokov** [comment]
поточний баг відрізняється від попереднього
буд ласка заведіть новий
