### ISSUE TITLE
The width of the picture QA is 906.8px

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/qax-portal-2#609]
**Pre-conditions:**
Open https://www.qax-camp.com.ua/qa-courses-2/

**Steps to reproduce:**

1.Scroll down to the picture QA
2.Pay attention to the width of the picture QA

**Actual result:**
The width of the picture QA is 906.8px

**Expected result:**
The width of the picture QA is 980px

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)
![GSMVd6EbaN](https://user-images.githubusercontent.com/123729744/226316161-a4f0982a-6200-4248-8603-1263c2073e41.png)

**Comment by OlhaHutsman** [comment]
#592

**Comment by DmytroMarkulych** [comment]
@OlhaHutsman Якщо судити по Summary то це не дефект. Розмір відповідає вимогам

**Comment by scholokov** [comment]
заміри робились на меншій ширині, тому не відповідають дійсності
