### ISSUE TITLE
The height of the picture QA is 607.925px

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/qax-portal-2#610]
**Pre-conditions:**
Open https://www.qax-camp.com.ua/qa-courses-2/

**Steps to reproduce:**

1.Scroll down to the picture QA
2.Pay attention to the height of the picture QA

**Actual result:**
The height of the picture QA is 607.925px

**Expected result:**
The height of the picture QA is 657px

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)
![icxSHHeNr3](https://user-images.githubusercontent.com/123729744/226317108-dff22c8e-3cb9-447c-9aa5-6f27480089c9.png)

**Comment by OlhaHutsman** [comment]
#592

**Comment by DmytroMarkulych** [comment]
@OlhaHutsman даний елемент адаптивний, і його розмір залежить від розширення екрану
