### ISSUE TITLE
In the section card  "Технічні скіли" there is no sign up button

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#611]
Prerequisites:
Open: https://www.qax-camp.com.ua/qa-courses-2/
Steps to reproduce:

1. In the section card "Технічні скіли"
2. Please note that there is no "register" button

Actual result: In the section card   "Технічні скіли" there is no signup button 
Expected result:  In the section card  "Технічні скіли" there are buttons to sign up
Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104 
![записатись](https://user-images.githubusercontent.com/113175298/226334797-0a6e359d-bd24-4a49-9e2f-bc361d2c7632.png)

**Comment by Nadiyk** [comment]
#368

**Comment by scholokov** [comment]
тому що тестування проводить уже авторизованим юзером
