### ISSUE TITLE
Test SCRUM / Mis font of answer options  is #E9E8EA

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#613]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/quizzes/scrum/
2. Click on "Start Тест" under the picture.
3. Test is opened.
4. Pay attention to the color of the font of answer options.

**Actual result:**
Font of answer options color is #E9E8EA.

**Expected result:**
Font of answer options color is #FFFFFF.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional іnformation:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=931-92&t=zeMww3kFgnKrxFlL-0

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/226377671-56f29695-9f67-42aa-b810-3bb813b80f50.png)

**Comment by GNatala** [comment]
#96

**Comment by scholokov** [comment]
в усіх відповідях чи лише тут?

**Comment by GNatala** [comment]
Так. В усіх відповідях.

**Comment by GNatala** [comment]
виправлено в Figma
перевірено
