### ISSUE TITLE
Type "Купуй абонемент в QAX – отримуй досвід!"   does not match the requirements

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#621]
Prerequisites:
Open: https://www.qax-camp.com.ua/practice/
Steps to reproduce:

1. Pay attention to the font and compare it with the requirements

Actual result:  Type "Купуй абонемент в QAX – отримуй досвід!"   does not match the requirements
Expected result:  Type "Купуй абонемент в QAX – отримуй досвід!"    match the requirements

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104
![портал фігма](https://user-images.githubusercontent.com/113175298/226621405-8c6e7758-b7cf-4b2c-9008-ca638bae0dd9.png)

**Comment by Nadiyk** [comment]
#498

**Comment by DmytroMarkulych** [comment]
![Image](https://user-images.githubusercontent.com/88647733/226847187-418e33e1-d0f3-4679-a14d-f737076e4e2b.png)

**Comment by Nadiyk** [comment]
виправила

**Comment by scholokov** [comment]
виправлено

**Comment by Nadiyk** [comment]
Баг відтворюється
![портал 700](https://user-images.githubusercontent.com/113175298/230723334-06f4ec60-d106-45f5-bc75-a12529a01723.png)

**Comment by Nadiyk** [comment]
Відтворюється
![image](https://user-images.githubusercontent.com/113175298/233779467-0195df8d-45c1-4b35-848d-0782cc9adfb0.png)

**Comment by scholokov** [comment]
виправлено

**Comment by Nadiyk** [comment]
pass
