### ISSUE TITLE
Lesson - Оновлення дизайну

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#624]
We need to design the HTML-document on the "Lesson" page according to Figma for desktop, tablet and mobile.
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390-12775&t=dGJWG2VYLWGDWtDB-0
Environment: https://www.qax-camp.com.ua/courses/web-tech/lessons/basic-html-for-qa/
![HTML](https://user-images.githubusercontent.com/109460500/230447542-39a0968a-b394-4608-b72e-724e7c4862b4.png)
 <img width="373" alt="image" src="https://user-images.githubusercontent.com/22824947/226861470-9dca954f-ed27-487d-a6e0-71a0cff85939.png">

**Comment by AlonaSarapina** [comment]
ready for testing 
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A12775&t=cRH3rqLOOWkNmZuQ-1

**Comment by GNatala** [comment]
verified
