### ISSUE TITLE
Color of the phrase "П’ять складових професійного BA" on the site is #F66F5D instead #E9E8EA in the Figma

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#625]
**STR**
1. Open https://www.qax-camp.com.ua/ba-courses-2/
2. Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=5475-4760&t=t1aHDRlEcHDZ4hus-0
3. Pay attention to the color "П’ять складових професійного BA"

**ACTUAL RESULT**
The number of color is #F66F5D 

**EXPECTED RESULT**
The number of color is #E9E8EA

![b62QbutBLO](https://user-images.githubusercontent.com/109384052/226969119-99ea8d9c-d8d6-4952-b493-64101b62e1e2.png)

**Comment by BatalovaOlha** [comment]
#509

**Comment by scholokov** [comment]
виконано

**Comment by BatalovaOlha** [comment]
![chrome_F0Qlp2PIXF](https://github.com/scholokov/qax-portal-2/assets/109384052/29571b16-c3a3-4671-9a2e-c0f9e1b06621)


The same

**Comment by scholokov** [comment]
fixed
