### ISSUE TITLE
Button " Згорнути" font-size is 16px in the block "Історії успіху''.

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/qax-portal-2#626]
**Pre-conditions:**
Open https://www.qax-camp.com.ua/

**Steps to reproduce:**

1.Scroll down to the bootom of the page.
2.Find the block "Історії успіху''.
3.Click on button "Дивитися усіх ".
4. Pay attentiion to the button "Згорнути".

**Actual result:**
Button " Згорнути" font-size is 16px .

**Expected result:**
Button " Згорнути" font-size is 18px .

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![hqz8IUyUjg](https://user-images.githubusercontent.com/123729744/227171553-eeefbff5-03d9-4009-b1bb-5a7683322d3d.png)

**Comment by OlhaHutsman** [comment]
#472

**Comment by poroskundenys** [comment]
Панель лучше размещать с низу, тогда не меняется ширина проверяемой области https://prnt.sc/O12TT-1svfol

**Comment by OlhaHutsman** [comment]
@poroskundenys verified
