### ISSUE TITLE
Button " Згорнути"  line-height is 20.8px in the block "Історії успіху''  .

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/qax-portal-2#627]
**Pre-conditions:**
Open https://www.qax-camp.com.ua/

**Steps to reproduce:**

1.Scroll down to the bootom of the page.
2.Find in.
3.Click on button "Дивитися усіх ".
4. Pay attentiion to the button "Згорнути".

**Actual result:**
Button " Згорнути"  line-height is 20.8px .

**Expected result:**
Button " Згорнути"  line-height is 23px .

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![hQHj4UZU5z](https://user-images.githubusercontent.com/123729744/227172682-b78b6a43-5462-4aee-adf4-c62808f136c7.png)

**Comment by OlhaHutsman** [comment]
https://github.com/scholokov/qax-portal-2/issues/472

**Comment by GNatala** [comment]
passed
