### ISSUE TITLE
Implement design of "Практика" page according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#628]
We need to implement design of "Практика" page according to Figma for desktop, tablet and mobile.
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=5444-749&t=YBACVWuLdixy8BMx-0
Product environment: https://www.qax-camp.com.ua/practice/
![Практика](https://user-images.githubusercontent.com/109460500/227176824-f3f2e2bc-bbc6-413b-a283-96e66a5efb6c.png)

**Comment by ButKoff** [comment]
#556

**Comment by GNatala** [comment]
passed
