### ISSUE TITLE
Test Defect / Mis spelling in the word "с кладється” in the name of the question

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#631]
**Steps to reproduce:**
1. Open https://www.qax-camp.com.ua/courses/q2-basic-cource/lessons/q2-04-%d0%b4%d0%b5%d1%84%d0%b5%d0%ba%d1%82/quizzes/deffect/
2. Click on "Розпочати Тест" under the picture.
3. Test is opened.
4. Find question "Детальний опис (Description) с кладється з:".
5. Pay attention to the spelling of the word "с кладється”.

**Actual result:**
Spelling of the word is **"с кладється”**.

**Expected result:**
Spelling of the word is **"с кладється”**.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/227594345-e4e35223-419b-4c29-89dd-1443013d6c88.png)

**Comment by GNatala** [comment]
#86

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
