### ISSUE TITLE
Tests - Results - Implement design of "Test results" page according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#632]
We need to implement design of "Test results" page according to Figma.
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=1212-66&t=d5cnz6VSiXMW10Bg-0
Environment: https://portal.qax-camp.com.ua/quizzes/scrum/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.3.-Tests
![Test results](https://user-images.githubusercontent.com/109460500/227485807-5f2996a2-46ea-4991-8131-b6fd387d81b9.png)
![Test results card](https://user-images.githubusercontent.com/109460500/227485888-4fb178d1-f9f8-4361-aa25-a28ba0f55ecc.png)

**Comment by ButKoff** [comment]
#581

**Comment by poroskundenys** [comment]
У меня после прохождения теста при обновлении страницы тест нужно проходить и нет результатов прошлого теста. Как сделать чтобы результат теста показывался при обновлении страницы всегда?

**Comment by scholokov** [comment]
ну саме результати зберігаються. і можна потім отримати доступ до всіх результатів.
як після рефреша - все ще мати результати - не знаю. можливо залежить від налаштувань самого тесту.
наразі всі тести можна проходити безліч разів і немає ніякої паузи між ними.
можливо коли це додати - з'явиться...

**Comment by poroskundenys** [comment]
@scholokov Где можно получить доступ до всех результатов?

**Comment by scholokov** [comment]
наприклад отак по кожному тесту:
![image](https://github.com/scholokov/qax-portal-2/assets/22824947/66cb8445-5bfe-4f7a-a06b-2932155a4771)

**Comment by scholokov** [comment]
в Learn Dash LMS

**Comment by poroskundenys** [comment]
@scholokov Это результаты для админа. А для пользователя есть какая-то страница? Как тут показано https://prnt.sc/LNt3FWRL_nWw

**Comment by scholokov** [comment]
то ще не готове. ту сторінку не реалізовуємо поки
лише поточні результати

**Comment by DmitriiNasonov** [comment]
Testing completed
