### ISSUE TITLE
Course* / Mis font of lesson descriptions is Montserrat

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#635]
**Steps to reproduce:**

1. Open Course page: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390-1036&t=5Zpfs00z5d03fYoS-0
2. Pay attention to the font of lessons descriptions in Decktop, Tablet and Mobile mockups.

**Actual result:**
**Font of lessons descriptions is Montserrat** in Decktop, Tablet and Mobile mockups.

**Expected result:**
**Font of lessons descriptions is Raleway** in Decktop, Tablet and Mobile mockups.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/227712366-0a5b54d5-d4ed-4079-83f4-01bbc83fed34.png)

**Comment by AlonaSarapina** [comment]
fixed 
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A1035&t=9F0VBmDnbmDBjuor-1

**Comment by GNatala** [comment]
passed
