### ISSUE TITLE
Login page / No CheckBox "Запам’ятати мене" in Mobile mockup

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#636]
**Steps to reproduce:**

1. Open Login page: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2129-748&t=9Dl9ZhNxeTWD9EXw-0
2. Pay attention to the absence of CheckBox "Запам’ятати мене" in Mobile mockup.

**Actual result:**
**No CheckBox "Запам’ятати мене" in Mobile mockup.**

**Expected result:**
**There is CheckBox "Запам’ятати мене" in Mobile mockup.**

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/227731450-32c69086-5d81-4197-ab0c-805ad2cf7387.png)

**Comment by AlonaSarapina** [comment]
fixed 
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=2129%3A1134&t=9F0VBmDnbmDBjuor-1

**Comment by GNatala** [comment]
passed
