### ISSUE TITLE
The color of the text  "П’ять складових професійного QA" is #F66F5D. 

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/qax-portal-2#637]
**Pre-conditions:**
Open https://www.qax-camp.com.ua/qa-courses/

**Steps to reproduce:**

1.Pay attention to the color of the text  "П’ять складових професійного QA"

**Actual result:**
The color of the text  "П’ять складових професійного QA" is #F66F5D. 

**Expected result:**
The color of the text  "П’ять складових професійного QA" is #E9E8EA .

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![jP8StXtjTc](https://user-images.githubusercontent.com/123729744/227788084-770b85b8-4045-4f18-8c36-7df31aafc03b.png)

**Comment by OlhaHutsman** [comment]
#239

**Comment by scholokov** [comment]
виконано

**Comment by Nadiyk** [comment]
pass
