### ISSUE TITLE
Крок 4.Англійська мова is missed in requirements.

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/qax-portal-2#638]
**Pre-conditions:**
Open https://www.qax-camp.com.ua/qa-courses/

**Steps to reproduce:**

1.Scroll down to "П’ять складових професійного QA"
2. Pay attention to   _Крок 4.Англійська мова._

**Actual result:**
Крок 4.Англійська мова  is missed in requirements.

**Expected result:**
Крок 4.Англійська мова  isn't  missed in requirements.

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![wduogF3V7C](https://user-images.githubusercontent.com/123729744/227788692-cdf1ddf9-b229-4181-af2e-b75c4d796bc6.png)

**Comment by OlhaHutsman** [comment]
#239

**Comment by ABatalov** [comment]
@scholokov - fixed https://github.com/scholokov/qax-portal-2/wiki/1.0.1.--Quality-Assurance-Engineer-(QA) - додай тільки, пліз, ID - я щось не зрозумів що це ))

**Comment by Nadiyk** [comment]
pass
