### ISSUE TITLE
Test SCRUM / Mis name of the button "Next" is in English

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#639]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/quizzes/scrum/
2. Click on "Start Тест" under the picture.
3. Test is opened.
4. Pay attention to the name of the button "Next" after the answer options.

**Actual result:**
Name of the button "Next" is in English language.

**Expected result:**
Name of the button "Next" is in Ukrainian language.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/227873641-9cdfe306-3837-4ecd-9d1c-ec5fe768dcaa.png)

**Comment by GNatala** [comment]
#96

**Comment by scholokov** [comment]
а у нас є ця кнопка у фігмі?

**Comment by DmytroMarkulych** [comment]
@GNatala тоді варто закрити баш репорт
