### ISSUE TITLE
Courses - Implement a design button "Обрати цей курс" and "Ціна" according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#643]
We need to implement a design button "Обрати цей курс" and "Ціна" according to Figma.
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390-1035&t=CtALutaIeK5nY9zj-0
Environment: https://www.qax-camp.com.ua/courses/q6-basic/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81
![Course](https://user-images.githubusercontent.com/109460500/227943386-ca1b6002-f803-4730-afb4-dc6031b1ec2a.png)

**Comment by GNatala** [comment]
verified
