### ISSUE TITLE
In the course card specified language "Мова: російська" - page " Business Analyst (BA)" - Крок 5. CV - Card course Інструменти пошуку вакансій.

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#644]
**STR**
1. Open https://www.qax-camp.com.ua/ba-courses-2/ and scroll to the "Крок 5. CV", pay attention to the card "Інструменти пошуку вакансій" and that in the preview shown "Мова: російська"

**ACTUAL RESULT**
The preview of the course card indicates that the language of the course is "Мова: російська", although when you open the course page, the language is Ukrainian

**EXPECTED RESULT**
The preview of the course card indicates that the language of the course is "Мова: українська"

![8paXCePe5q](https://user-images.githubusercontent.com/109384052/227998742-cbc664b0-f1ef-4c9d-acae-b2ddbea017fd.png)

**Comment by BatalovaOlha** [comment]
#509

**Comment by scholokov** [comment]
більшість уроків в цьому курсі на рос мові

**Comment by BatalovaOlha** [comment]
non-actual
