### ISSUE TITLE
Character '':'' is mised at the end of the text

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/qax-portal-2#648]
**Pre-conditions:**
Open https://www.qax-camp.com.ua/qa-courses/

**Steps to reproduce:**

1.Pay attention to the  text "Quality Assurance Engineer (QA)"

**Actual result:**
Character '':'' is mised at the end of the text

**Expected result:**
Character '':'' isn't  mised at the end of the text

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![QnZ96SmBoM](https://user-images.githubusercontent.com/123729744/228522314-39c94ca3-0087-4ef4-9cc7-abb29ec0e8de.png)

**Comment by scholokov** [comment]
фігма не є функціональними вимогами
