### ISSUE TITLE
Practice / Buttom "Записатися" does not match design in Figma in breakpoint 813px

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#649]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/practice/
2. Make breakpoint 813px.
3. Scroll down to the "Діючі проєкти".
4. Pay attention to the Buttom "Записатися" in the four Project cards.

**Actual result:**
 Buttom "Записатися" does not match design in Figma.

**Expected result:**
 Buttom "Записатися" match design in Figma.

**Aditional information**: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=5444-749&t=YBACVWuLdixy8BMx-0

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://user-images.githubusercontent.com/101987790/228543513-68e4cba6-4a90-4e6c-812f-1b709bb081bd.png)

**Comment by GNatala** [comment]
#628

**Comment by GNatala** [comment]
**An issue is reproduced.**

**Actual result:**
Buttom "Записатися" does not match design in Figma.

**Expected result:**
Buttom "Записатися" match design in Figma.

**Attachment:**
![Image](https://github.com/scholokov/qax-portal-2/assets/101987790/88165ff8-1ac3-4152-b160-7369ba7ca331)

**Comment by scholokov** [comment]
але ж 813px являється проміжним. тобто на нього ж немає конкретного дизайну. тобто він просто має виглядати "не критично"....

**Comment by GNatala** [comment]
перевірено
