### ISSUE TITLE
Video block is missed in figma

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/qax-portal-2#652]
**Pre-conditions:**
Open https://www.qax-camp.com.ua/qa-courses/

**Steps to reproduce:**

1.Pay attention to the abcense of Video block "А хто взагалі такий QA?" in figma.

**Actual result:**
Video block "А хто взагалі такий QA?" is missed  in figma 

**Expected result:**
Video block "А хто взагалі такий QA?" is  represented   in figma

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![rSryy4wXKr](https://user-images.githubusercontent.com/123729744/228742004-7a4835b3-2783-427b-a762-1552c9e2b84c.png)

**Comment by OlhaHutsman** [comment]
#239

**Comment by AlonaSarapina** [comment]
fixed 
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=5469%3A749&t=9F0VBmDnbmDBjuor-1

**Comment by OlhaHutsman** [comment]
@AlonaSarapina verified
