### ISSUE TITLE
The section  "Особенности тестирования на различных платформах" is described in Russian

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#654]
Prerequisites:
Open:  https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA
Steps to reproduce:

1. Прокрутіть сторінку до розділу 

Actual result: The section  "Особенности тестирования на различных платформах" is described in Russian
Expected result: The section  "Особенности тестирования на различных платформах" is described in Ukrainian 

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104
![portal Documentation in Russian](https://user-images.githubusercontent.com/113175298/228778152-5e81b6c1-a3ff-471a-9cf7-e5530352ab85.png)

**Comment by Nadiyk** [comment]
#510

**Comment by scholokov** [comment]
виправлено

**Comment by Nadiyk** [comment]
pass
