### ISSUE TITLE
 No section   "Відео блок з функцією згортання" on the website

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#655]
Prerequisites:
Open: https://www.qax-camp.com.ua/courses/pm-basics/
Steps to reproduce:

1. Please note that there is no video on the site

Actual result:   No such thing as "Відео блок з функцією згортання" on the website
Expected result:  There is a section on the website "Відео блок з функцією згортання"

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104
![відео ПМ](https://user-images.githubusercontent.com/113175298/228797855-0f873fd8-75c3-49c8-8bf4-371c5cd0dc25.png)

**Comment by Nadiyk** [comment]
#510

**Comment by DmytroMarkulych** [comment]
@Nadiyk Давайте, перефразуємо Summary таким чином, щоб воно не містило синтаксичних помилок (І не використовували there is/are)

**Comment by Nadiyk** [comment]
corrected

**Comment by DmytroMarkulych** [comment]
@Nadiyk і ще прибиремо із Expected Result there is

**Comment by Nadiyk** [comment]
Corrected

**Comment by Nadiyk** [comment]
testing on wrong environment
