### ISSUE TITLE
Lessons - Check lesson for "Тестування вимог - Чат-Бот" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#658]
We need to check lesson for "Тестування вимог - Чат-Бот" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/mc-testing/lessons/mc-testing-chat-bot/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F--%D0%BC%D0%B0%D0%B9%D1%81%D1%82%D0%B5%D1%80-%D0%BA%D0%BB%D0%B0%D1%81%D0%B8

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
passed
