### ISSUE TITLE
In the section "Твої інструменти" does not have  "Trello - таск"

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#659]
Prerequisites:
Open: https://www.qax-camp.com.ua/pm-courses/
Steps to reproduce:

1. scroll to the section "Твої інструменти"
2. pay attention does not have "Trello-таск"

Actual result: In the section "Твої інструменти" does not have  "Trello - таск"
Expected result: In the section "Твої інструменти"  there is a section  "Trello - таск"

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104
![YUR TOOLS](https://user-images.githubusercontent.com/113175298/229084621-c670d06a-eafb-45d1-abe8-cb7577d388c9.png)

**Comment by scholokov** [comment]
буд ласка перепровірте на коректному середовищу
https://www.qax-camp.com.ua/pm-courses-2/

**Comment by Nadiyk** [comment]
not correct
