### ISSUE TITLE
 Pictures are placed to the left of the text in mobile version - Main page - Block "Обирай свій напрям" 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#66]
**STR**
1. Open the main page https://portal.qax-camp.com.ua/
2. Open design -  https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A23
3. Pay attention to the course description/ the placement of the pictures. 

**ACTUAL RESULT**
Pictures are placed to the left of the text 

**EXPECTED RESULT**
Pictures are placed under the text 

![8pokphPpJe](https://user-images.githubusercontent.com/109384052/188638342-c041e3d4-47f1-4867-9492-fd6b26ae9598.png)
![mQq87k2KyU](https://user-images.githubusercontent.com/109384052/188638348-83861449-090d-43ae-996f-2236e03fecba.png)

**Comment by DmytroMarkulych** [comment]
1. В Summary НЕ використовуйте, будь ласка, слова типу wrong, incorrect, don't-doesn't work ... вони не дають конкретики в опис дефекту і збивають із суті проблеми.

2. Додайте деталей в STR, якщо відтворювати дефект, то ми відкрили одне посилання, тоді дизайн..а далі? Я думаю, що фраза Pay attention to..(вказавши місце проблеми), то всі питання зникнуть де саме є цей дефект.

**Comment by BatalovaOlha** [comment]
Змінила

**Comment by BatalovaOlha** [comment]
Verified
