### ISSUE TITLE
Miro - онлайн платформ для створення дощок / схем / діаграм, not on the site in the section "Твої інструменти"

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#661]
Prerequisites:
Open:  https://www.qax-camp.com.ua/pm-courses/
Steps to reproduce:

1. Scroll to the section "Твої інструменти"
2. Note that there is no section Miro - онлайн платформ для створення дощок / схем / діаграм

Actual result:  Miro - онлайн платформ для створення дощок / схем / діаграм, not on the site in the section "Твої інструменти"
Expected result: Miro - онлайн платформ для створення дощок / схем / діаграм, the site in the section "Твої інструменти"

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104
![немає Miro](https://user-images.githubusercontent.com/113175298/229090461-9cf6aa2e-d10e-4df6-bfa8-eb6ed7ec26ca.png)

**Comment by scholokov** [comment]
please retest on correct env

**Comment by Nadiyk** [comment]
not correct
