### ISSUE TITLE
The name of the lesson is "Тестуємо вимоги по Чат-Боту"

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/qax-portal-2#666]
**Pre-conditions:**
Open https://www.qax-camp.com.ua/courses/mc-testing/

**Steps to reproduce:**
1.Scroll down to the last lesson of the course.
2. Pay attention to the name of the lesson.

**Actual result:**
The name of the lesson is "Тестуємо вимоги по Чат-Боту"

**Expected result:**
The name of the lesson is "Тестування вимог - Чат-Бот" 

**Environment**

Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Additional information**
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA

**Attachment:**

![mJ2uCpzmtI](https://user-images.githubusercontent.com/123729744/229450579-32038815-0046-4451-8b6d-6e29776d85fc.png)

**Comment by scholokov** [comment]
додайте буд ласка лінку на вимоги

**Comment by OlhaHutsman** [comment]
@scholokov вимоги додано

**Comment by OlhaHutsman** [comment]
@DmytroMarkulych edited

**Comment by scholokov** [comment]
виправлено у вимогах

**Comment by OlhaHutsman** [comment]
@scholokov verified
