### ISSUE TITLE
The name of the lesson is "Тестування - Portal - Тест - SCRUM"

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/qax-portal-2#667]
**Pre-conditions:**
Open https://www.qax-camp.com.ua/courses/mc-testing/

**Steps to reproduce:**
1.Scroll down to the 4th lesson of the course.
2. Pay attention to the name of the lesson.

**Actual result:**
The name of the lesson is "Тестування - Portal - Тест - SCRUM"

**Expected result:**
The name of the lesson is "Тестування - Portal - Тест / SCRUM"

**Environment**

Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![ZbIwdulKHF](https://user-images.githubusercontent.com/123729744/229453984-4082dd8a-3ea0-46da-90b3-09a827a11717.png)

**Comment by OlhaHutsman** [comment]
#651

**Comment by scholokov** [comment]
fixed

**Comment by OlhaHutsman** [comment]
@scholokov verified
