### ISSUE TITLE
Requirement 2.2 is incomplete

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/qax-portal-2#668]
**Pre-conditions:**
Open https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81#%D1%84%D0%BE%D1%80%D0%BC%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F-%D0%BB%D1%96%D0%BD%D0%BA%D1%83

**Steps to reproduce:**
1. Pay attention to the requirement 2.2

**Actual result:**
Requirement 2.2 is incomplete

**Expected result:**
Requirement 2.2 is  complete

**Environment**

Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![req](https://user-images.githubusercontent.com/123729744/229455772-b22e76b5-d573-4b3f-932f-a776011629c9.png)

**Comment by OlhaHutsman** [comment]
#651

**Comment by scholokov** [comment]
fixed

**Comment by OlhaHutsman** [comment]
@scholokov verified
