### ISSUE TITLE
The preview is not unique

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/qax-portal-2#669]
**Pre-conditions:**
Open https://www.qax-camp.com.ua/courses/mc-testing/

**Steps to reproduce:**
1. Find preview picture.
2. Pay attention to the picture.

**Actual result:**
The preview is not unique. It doesn't have specific unique picture to be different from other courses.

**Expected result:**
The preview is unique according [requirements](https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81#%D0%BF%D0%BE%D0%B2%D0%BD%D0%B8%D0%B9-%D0%BF%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA-%D0%BA%D1%83%D1%80%D1%81%D1%96%D0%B2)

**Environment**

Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![uxpDdxLgp5](https://user-images.githubusercontent.com/123729744/229465506-0655cb79-e79d-4502-9804-9981302f025e.png)

**Comment by OlhaHutsman** [comment]
#651

**Comment by DmytroMarkulych** [comment]
@OlhaHutsman давайте додамо більше деталей в баг репорт

**Comment by OlhaHutsman** [comment]
@DmytroMarkulych edited

**Comment by scholokov** [comment]
превью унікальне
не зовсім зрозуміло у чому помилка

**Comment by OlhaHutsman** [comment]
@scholokov Чим саме превью повинне бути унікальним? Згідно вимог, зрозуміло, що назвою і фото(картинкою). У вимогах зображене фото (як приклад) , а у курсі ні. Чи це питання стосовно повноти вимог для кращого розуміння?

**Comment by scholokov** [comment]
наразі підписом та іконкою
