### ISSUE TITLE
Requirements, there is no English language in the course list

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#672]
Prerequisites:
Open:  https://www.qax-camp.com.ua/pm-courses-2/
Steps to reproduce:

1. Please note that there is no English section in the requirements

Actual result:  Requirements, there is no English language in the course list
Expected result:   English section in the requirements

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104     
![анг вимоги](https://user-images.githubusercontent.com/113175298/229490373-f0619d79-58ec-4784-b84a-04ef0cd14e7d.png)

**Comment by Nadiyk** [comment]
#510

**Comment by ABatalov** [comment]
@Nadiyk - fixed - https://github.com/scholokov/qax-portal-2/wiki/1.0.1.--Quality-Assurance-Engineer-(QA)

**Comment by Nadiyk** [comment]
pass
