### ISSUE TITLE
 In the Practice section, a card "Тест дизайн на практиці" is not the first on the list 

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#673]
Prerequisites:
Open:  https://www.qax-camp.com.ua/pm-courses-2/
Steps to reproduce:

1. Scroll to the section "Тест дизайн на практиці"
2. , Pay attention to "Тест дизайн на практиці" not the first on the list

Actual result:  In the Practice section, a card "Тест дизайн на практиці" is not the first on the list 
Expected result:  In the Practice section, a card "Тест дизайн на практиці" stands first on the list

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104     
![прак, ТСТ- ДИЗАЙН](https://user-images.githubusercontent.com/113175298/229504525-3fb335d3-daef-4ac6-beb4-2741bc01bc53.png)

**Comment by Nadiyk** [comment]
#510

**Comment by scholokov** [comment]
він же перший у приведеному блоці....

**Comment by Nadiyk** [comment]
![image](https://user-images.githubusercontent.com/113175298/229824220-38bc82c2-2ee3-4396-8209-93a6003df488.png)

**Comment by Nadiyk** [comment]
В вимогах немає прописано, що така послідовність повинна бути в блоці БОНУСНІ КУРСИ.
![image](https://user-images.githubusercontent.com/113175298/229825977-cca727a1-39da-4601-b940-0a31ec8f0c4f.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk виглядає як не дефект
