### ISSUE TITLE
Practice / Preview of the Project card does not match Wiki requirements 1.1.5-Preview

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#675]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/practice/
2. Scroll down to the "Архів".
3. Open accordion "Архів".
4. Pay attention to the Preview of the Project card.

**Actual result:**
 Preview of the Project card does not match Wiki requirements 1.1.5-Preview.

**Expected result:**
Preview of the Project card matches Wiki requirements 1.1.5-Preview.

**Additional information:** 
https://github.com/scholokov/qax-portal-2/wiki/1.1.5-Preview

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/229579709-ed93bc26-62f9-4bc8-abc2-0d1caa6e2c95.png)

**Comment by GNatala** [comment]
#628

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
passed
