### ISSUE TITLE
The picture in figma doesn't match requirements

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/qax-portal-2#677]
**Pre-conditions:**
Open https://www.qax-camp.com.ua/qa-courses/

**Steps to reproduce:**

1. Scroll down to "П’ять складових професійного QA"
3. Pay attention to the picture under.

**Actual result:**
The picture in figma doesn't match requirements

**Expected result:**
The picture in figma  matches requirements

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Additional information**
https://github.com/scholokov/qax-portal-2/wiki/1.0.1.--Quality-Assurance-Engineer-(QA)

**Attachment:**
![sCqrAFyLFx](https://user-images.githubusercontent.com/123729744/229552689-ac446605-859d-4eaa-af03-1df7312c0b69.png)

**Comment by OlhaHutsman** [comment]
#239

**Comment by DmytroMarkulych** [comment]
@OlhaHutsman додайте лінку на вимоги як окремий пункт

**Comment by OlhaHutsman** [comment]
@DmytroMarkulych edited

**Comment by scholokov** [comment]
please retest

**Comment by OlhaHutsman** [comment]
@scholokov verified
