### ISSUE TITLE
Mis name of the lesson "Тестуємо Portal – Тест – SCRUM"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#678]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/mc-testing/lessons/mc-testing-portal-test-scrum/
2. Pay attention to the name of the lesson.

**Actual result:**
Name of the lesson is "Тестуємо Portal – Тест – SCRUM".

**Expected result:**
Name of the lesson is "Тестування - Portal - Тест / SCRUM".

**Additional information:** 
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://user-images.githubusercontent.com/101987790/229588561-9c0dd54d-13a8-40b1-a528-5a267e259238.png)

**Comment by GNatala** [comment]
https://github.com/scholokov/qax-portal-2/issues/664

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
