### ISSUE TITLE
Block "Історії успіху" - Main page - name/surname shown on the left side of the text in mobile version 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#68]
**STR**
1. Open https://portal.qax-camp.com.ua/
2. Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A23
3. Scroll to the block "Історії успіху"

**ACTUAL RESULT**
Name/Surname shown on the left side of the text

**EXPECTED RESULT**
Name/Surname shown above the text/left text alignment

![B4QvVCaw99](https://user-images.githubusercontent.com/109384052/188672042-c9c49f16-25c0-4c5c-a1f0-fed93bbb0faa.png)
![xFqIXFBlVF](https://user-images.githubusercontent.com/109384052/188672043-a73169e3-199c-4ff4-9af2-44718828757c.png)

**Comment by DmytroMarkulych** [comment]
1. В Summary НЕ використовуйте, будь ласка, слова типу wrong, incorrect, don't-doesn't work ... вони не дають конкретики в опис дефекту і збивають із суті проблеми.
2. Додайте в EXPECTED RESULT місце по якому краю, має вирівнюватися текст, бо девелопер може і по центру вирівняти, йому не ліньки

**Comment by BatalovaOlha** [comment]
> 1. В Summary НЕ використовуйте, будь ласка, слова типу wrong, incorrect, don't-doesn't work ... вони не дають конкретики в опис дефекту і збивають із суті проблеми.
> 2. Додайте в EXPECTED RESULT місце по якому краю, має вирівнюватися текст, бо девелопер може і по центру вирівняти, йому не ліньки

Змінила

**Comment by BatalovaOlha** [comment]
verified
