### ISSUE TITLE
Practice / Mis font of the subtitle "Купуй абонемент в QAX – отримуй досвід!" in breakpoint 360px 

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#680]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/practice/
2. Make breakpoint 360px.
3. Pay attention to the font of the subtitle "Купуй абонемент в QAX – отримуй досвід!".

**Actual result:**
Font of the **subtitle "Купуй абонемент в QAX – отримуй досвід!" in breakpoint 360px is font-weight: 700, font-size: 21px.** 

**Expected result:**
Font of the **subtitle "Купуй абонемент в QAX – отримуй досвід!" in breakpoint 360px is font-weight: 500,
font-size: 14px.**

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/229878234-16598548-ec16-401f-9d82-1bf4ee8e3738.png)

**Comment by GNatala** [comment]
#628

**Comment by DmytroMarkulych** [comment]
@GNatala додайте будь ласка скріншот

**Comment by GNatala** [comment]
passed
