### ISSUE TITLE
Test Defect / Mis font of the name of the question "Виберіть правильно описаний Title” - font weight 400 

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#681]
**Steps to reproduce:**
1. Open https://www.qax-camp.com.ua/courses/q2-basic-cource/lessons/q2-04-%d0%b4%d0%b5%d1%84%d0%b5%d0%ba%d1%82/quizzes/deffect/
2. Click on "Розпочати Тест" under the picture.
3. Test is opened.
4. Find question "Виберіть правильно описаний Title".
5. Pay attention to the font of the name of the question.

**Actual result:**
**Name of the question** "Виберіть правильно описаний Title” - ** font weight 400.**

**Expected result:**
**Name of the question** "Виберіть правильно описаний Title” - ** font weight 700.**

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/229880478-3b64a664-5c9e-4baf-9188-217571675bf3.png)

**Comment by GNatala** [comment]
https://github.com/scholokov/qax-portal-2/issues/86

**Comment by DmytroMarkulych** [comment]
@GNatala додайте будь ласка скріншот та лінку специфікацію

**Comment by GNatala** [comment]
перевірено
