### ISSUE TITLE
Test Defect / Mis font of the question "Яку пріорітетність має наступний баг “В описі ноутбука на ...” - font weight 400

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#683]
**Steps to reproduce:**
1. Open https://www.qax-camp.com.ua/courses/q2-basic-cource/lessons/q2-04-%d0%b4%d0%b5%d1%84%d0%b5%d0%ba%d1%82/quizzes/deffect/
2. Click on "Розпочати Тест" under the picture.
3. Test is opened.
4. Find question "Яку пріорітетність має наступний баг “В описі ноутбука на сайті вказали суму 1 000 грн замість 10 000".
5. Pay attention to the font of the name of the question.

**Actual result:**
**Name of the question** "Яку пріорітетність має наступний баг “В описі ноутбука на сайті вказали суму 1 000 грн замість 10 000” - **font weight 400.**

**Expected result:**
**Name of the question** "Яку пріорітетність має наступний баг “В описі ноутбука на сайті вказали суму 1 000 грн замість 10 000” - **font weight 700.**

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/229778407-54013c17-0131-4cd6-8f5e-c788b1fba0e5.png)

**Comment by GNatala** [comment]
#86

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
