### ISSUE TITLE
Test Defect / Content of answer options for the question ''Хто визначає Severity (Серйозність) бага?" is in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#687]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/q2-basic-cource/lessons/q2-04-%d0%b4%d0%b5%d1%84%d0%b5%d0%ba%d1%82/quizzes/deffect/
2. Click on "Розпочати Тест" under the picture.
3. Test is opened.
4. Find question "Хто визначає Severity (Серйозність) бага".
5. Pay attention to the language of the content of answer options for the question.

**Actual result:**
**Content of answer options** for the question 'Хто визначає Severity (Серйозність) бага?" **is in russian.**

**Expected result:**
**Content of answer options** for the question ''Хто визначає Severity (Серйозність) бага?" **is in Ukrainian.**

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/229869797-f8a1d5be-b783-4d9e-a352-c9d536d297d1.png)

**Comment by GNatala** [comment]
#86

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
passed
