### ISSUE TITLE
The button "Записатися" - Main page - after clicking button form for registration is not shown

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#69]
**STR**
1. Open https://portal.qax-camp.com.ua/
2. Click the button "Записатися"

**ACTUAL RESULT**
After clicking the button "Записатися"  form for registration is NOT shown 

**EXPECTED RESULT**
After clicking the button "Записатися"  form for registration is  shown 

![QAX-Camp-–-Students-Portal-Google-Chrome-2022-09-06-17-42-52](https://user-images.githubusercontent.com/109384052/188678516-e6911a18-45b7-4c5b-9e99-5d141b073ea7.gif)

**Comment by DmytroMarkulych** [comment]
Хорошим тоном є дотримуватися написання Summary за принципом Де? Що? Коли?

**Comment by BatalovaOlha** [comment]
> Хорошим тоном є дотримуватися написання Summary за принципом Де? Що? Коли?

Змінила

**Comment by BatalovaOlha** [comment]
verified
