### ISSUE TITLE
courses/practise/lessons/defect/ The words "Короткий" and "дефектів" have a grammatical error 

### ISSUE THREAD

**Issue by TetianaSulima** [scholokov/qax-portal-2#690]
Prerequisites:
Open https://www.qax-camp.com.ua/courses/practise/lessons/defect/

Steps to reproduce:

Scroll down to "Складові опису дефекту"

Pay attention to word "Коротки"

Actual result: The words "Короткий" and "дефектів" have a grammatical error 

Expected result: The words "Короткий" and "дефектів" don't have a grammatical error 

Environment: Windows 10 Home
system:
Browser: Google Chrome Version 110.0.5481.178

![image](https://user-images.githubusercontent.com/123786969/230243121-5efc24e9-1807-4b94-ad16-79650ec4e2b3.png)

**Comment by scholokov** [comment]
виправлено

**Comment by TetianaSulima** [comment]
Fixed not all "дефекті" changed to "дефекти".  must be "дефектів"

**Comment by scholokov** [comment]
fixed

**Comment by TetianaSulima** [comment]
the error is reproduced , must be "дефектів"

![image](https://user-images.githubusercontent.com/123786969/232637484-a0da5ebf-f45d-4740-b321-2d7d761cd299.png)

**Comment by scholokov** [comment]
виправлено

**Comment by Nadiyk** [comment]
Pass
