### ISSUE TITLE
courses/practise/lessons/defect/ In the sentence, there are many grammatiacal errors

### ISSUE THREAD

**Issue by TetianaSulima** [scholokov/qax-portal-2#691]
Prerequisites:
Open https://www.qax-camp.com.ua/courses/practise/lessons/defect/

Steps to reproduce:

1. Scroll down to "Найзручніше Summary формувати виходячи з принципу: Де-Що-Коли"

2. Pay attention to phrase "Де інтерфейс користувача або архітектури програмного продукту перебуває проблема" 

Actual result: There are many grammatiacal errors  in the sentence - 2 missing preposition "в"  and "i" id the ending of words "інтерфейсі" and 'архітектурі'.
 
Expected result: Correct sentence is "Де в інтерфейсі користувача або в архітектурі програмного продукту перебуває проблема " 

Environment: Windows 10 Home
system:
Browser: Google Chrome Version 110.0.5481.178

![image](https://user-images.githubusercontent.com/123786969/230247185-bde982c2-c18d-41a5-9307-e4e6a94d43fc.png)

**Comment by DmytroMarkulych** [comment]
@TetianaSulima прономеруйте кроки для відтворення

**Comment by scholokov** [comment]
fixed
