### ISSUE TITLE
20150623_0711_croatia/ in the preview one, 3 flags are displayed, but there should be 4. Іs displayed in the mobile version

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#697]
Prerequisites:
Open:  https://test.long-travel.live/20150623_0711_croatia/
Steps to reproduce:

 1. Note how many flags are displayed in the preview
 
Actual result:   in the preview one, 3 flags are displayed
Expected result:  in the preview one, 4 flags are displayed

Environment: Samsung Galaxy M52
system: Android 
Browser: Google Chrome Version 111.0.5563.116

![FLAG na Sumsung](https://user-images.githubusercontent.com/113175298/230722354-96ba7129-bbbe-4af8-8d3f-ab72064bbd16.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk в Актуальний результат ви пишете ще Очікуваний, не варто так роботи. Просто констатуємо що у нас є по факту

**Comment by Nadiyk** [comment]
Виправила

**Comment by scholokov** [comment]
у тайтлі має бути зазначено, що помилка стосується лише моб версії

**Comment by Nadiyk** [comment]
виправила

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
Pass
