### ISSUE TITLE
Основи PM / List of lessons in "Програма курсу" does not match wiki/1.7.1.-Урок "Основи проектного менеджменту"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#699]
**Steps to reproduce:**
1. Open https://www.qax-camp.com.ua/courses/pm-basics/
2. Pay attention to the list of lessons in "Програма курсу".

**Actual result:**
List of lessons in "Програма курсу" does not match wiki/1.7.1.-Урок "Основи проектного менеджменту".
**Expected result:**
List of lessons in "Програма курсу" match wiki/1.7.1.-Урок "Основи проектного менеджменту".

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

Additional information:
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/230787733-c23ae061-b29b-4465-9431-6d29a583adca.png)

**Comment by GNatala** [comment]
#578

**Comment by scholokov** [comment]
виправлено у вимогах

**Comment by GNatala** [comment]
passed
