### ISSUE TITLE
Registration form - Main page -  differ from the design requirements in Figma 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#70]
**STR**
1. Open https://portal.qax-camp.com.ua/
2. Scroll to the registration form
3. Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A23

**ACTUAL RESULT**
The registration form is sown in the wrong place and does not match the Figma design

**EXPECTED RESULT**
The registration form is NOT sown in the wrong place and does not match the Figma design

![B9lAglWHbS](https://user-images.githubusercontent.com/109384052/188682749-6d079d9b-c030-4ebc-b69b-190e0ab4f75d.png)
![LHHT2fuTKP](https://user-images.githubusercontent.com/109384052/188682755-cc4135ff-f392-4713-910e-2b0dae064c26.png)

**Comment by DmytroMarkulych** [comment]
1. В Summary НЕ використовуйте, будь ласка, слова типу wrong, incorrect, don't-doesn't work ... вони не дають конкретики в опис дефекту і збивають із суті проблеми.

**Comment by BatalovaOlha** [comment]
> 1. В Summary НЕ використовуйте, будь ласка, слова типу wrong, incorrect, don't-doesn't work ... вони не дають конкретики в опис дефекту і збивають із суті проблеми.

Зробила по іншому

**Comment by BatalovaOlha** [comment]
verified
