### ISSUE TITLE
Practice page - Check the "Найчастіші питання" section in accordion

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#700]
We need to check the "Найчастіші питання" section in accordion.
Please check the content and design.
Environment: https://www.qax-camp.com.ua/practice/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=5444-749&t=OPuxccwnc0gI1ikV-0
![Найчастіші питання](https://user-images.githubusercontent.com/109460500/230789309-312c5548-8249-4db7-bb86-6193560154b6.png)

**Comment by GNatala** [comment]
verified
