### ISSUE TITLE
Practice page - Check the "Підписка на використання навчальних матеріалів" section in accordion

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#701]
We need to check the "Підписка на використання навчальних матеріалів" section in accordion.
Please check functionality, content and design.
Environment: https://www.qax-camp.com.ua/practice/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=5444-749&t=OPuxccwnc0gI1ikV-0
![Підписка](https://user-images.githubusercontent.com/109460500/230790055-8c451a3d-c29c-4971-a158-d2d58e5e4d2a.png)

**Comment by GNatala** [comment]
verified
