### ISSUE TITLE
Calendar - Create design of "Наступна подія" block on Portal Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#702]
We need to create design of "Наступна подія" block on Portal Figma.
Environment: https://www.qax-camp.com.ua/calendars/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6704-1434&mode=design&t=rikt0LKosmdbG81Z-0

![Next event](https://user-images.githubusercontent.com/109460500/230873842-5193b76e-fca1-4a7d-ad2c-0933dc581f9f.png)

**Comment by ButKoff** [comment]
#1128

**Comment by DmitriiNasonov** [comment]
Testing completed. bugs not found
