### ISSUE TITLE
Calendar - Create design of "Календар на місяць" block on Portal Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#703]
We need to create design of "Календар на місяць" block on Portal Figma.
Environment: https://www.qax-camp.com.ua/calendars/
Example №1
![Calendars_1](https://user-images.githubusercontent.com/109460500/230875215-c5917198-4f51-424c-af43-ba9c1c9b3090.png)
Example №2
![Calendars_2](https://user-images.githubusercontent.com/109460500/230875270-2461d02f-4b08-4028-8237-96fd7bca0d52.png)

**Comment by scholokov** [comment]
ready for testing
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=6112-975&t=YNjBpWGGGpwKM4sC-0

**Comment by GNatala** [comment]
verified
