### ISSUE TITLE
Practice / Mis font of the main text in breakpoint 767px is font-size: 14px

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#708]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/practice/
2. Make breakpoint 767px.
3. Pay attention to the font of the text after the title "Купуй абонемент в QAX – отримуй досвід!".

**Actual result:**
Font of the main text in breakpoint 767px is font-size: 14px.

**Expected result:**
Font of the main text in breakpoint 767px is font-size: 21px.

Additional information:
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=5640-872&t=sD7TG3ebUTjv611F-0

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/231108369-f394f0b3-58a0-4b9c-82e0-09ae3b5d64b7.png)

**Comment by GNatala** [comment]
https://github.com/scholokov/qax-portal-2/issues/628

**Comment by GNatala** [comment]
An issue is reproduced.

**Actual result:**
Font of the main text in breakpoint 767px is font-size: 14px.

**Expected result:**
Font of the main text in breakpoint 767px is font-size: 21px.

Environment:
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

Attachment:


![Image](https://github.com/scholokov/qax-portal-2/assets/101987790/7edb0d92-00a2-4eb7-9e19-f9dd7b3e756c)

**Comment by poroskundenys** [comment]
У меня в двух браузерах при размере 767 показывается версия для tab https://prnt.sc/G3fMsZRSRDPh. На скринах еще мобильная версия отображается. Также по размерам шрифтом на макетах разных страниц размеры шрифтом одинаковых элементов для декстопа и мобильной версии одинаковые, а для tab разные есть 21px, 18px и 16px. Размеры шрифта должны быть как тут сделано https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=5699%3A913&mode=dev

**Comment by GNatala** [comment]
closed
