### ISSUE TITLE
Tab "Курси" - not show information with courses - contains one word "Программы" 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#71]
""STR""
1. Open https://portal.qax-camp.com.ua/
2. Click on the tab "Курси" 

""ACTUAL RESULT""
After clicking "Курси" on the main page NOT show information whit courses 

""EXPECTED RESULT""
After clicking "Курси" on the main page show information whit courses 

![yosB4RsLwC](https://user-images.githubusercontent.com/109384052/188685665-586b772b-793f-4e0c-88fe-c79009f19799.png)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
