### ISSUE TITLE
Event: оновлення дизайну

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#712]
1. Прибрати "місце проведення"
<img width="461" alt="image" src="https://user-images.githubusercontent.com/22824947/231478775-2e58fde7-6bcc-4998-b50d-1e138f9e00d3.png">

2. Час мабуть зробити більшим і написати "Місцевий час ...."

3. Додати кнопку "Зареєструватися" (мабуть помаранчового кольору)

4.  Додати блок з "описом події". Він буде необов'язковим

5. Назву "QAX Outsource" прибрати з картинки і перемістити "під" картинку, як у нас всюди

6. Внизу додати блок:
<img width="619" alt="image" src="https://user-images.githubusercontent.com/22824947/231480123-6f5e8577-17b5-4775-bbec-bd23456672b6.png">
<img width="592" alt="image" src="https://user-images.githubusercontent.com/22824947/231480365-371e2cf0-fc89-4d2f-9a9c-fc136c12ab17.png">
<img width="594" alt="image" src="https://user-images.githubusercontent.com/22824947/231480440-a3bd15ed-b735-455a-b1be-df3ab5388a2b.png">

**Comment by ButKoff** [comment]
#770

**Comment by GNatala** [comment]
verified
