### ISSUE TITLE
Block with video shown without description - page "Процеси" - lesson "Ролі та артефакти у проектній команді"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#714]
**STR**
1. Open https://www.qax-camp.com.ua/courses/processes/. You should be login to the page;
2. Open first lesson "Ролі та артефакти у проектній команді";
3. Pay attention to the video;
4. Open https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA scroll to the end of the page, to 1.10.1 line.

**ACTUAL RESULT**
Block with video on the page without a description, that does not match the requirement in the Wiki.

**EXPECTED RESULT**
Block with the video shown with the description as in Wiki "Якщо Урок має відео, то відео має містити прев'ю"

![Z0Z42i6Yey](https://user-images.githubusercontent.com/109384052/232290077-0cd02a6b-686d-43f7-acad-4b340dfa41a1.png)
![8DLBu2bAvC](https://user-images.githubusercontent.com/109384052/232290104-1d7902f1-70c8-4134-ab34-6886415401d3.png)

**Comment by BatalovaOlha** [comment]
#580

**Comment by scholokov** [comment]
так на скріні і так є превью....

**Comment by BatalovaOlha** [comment]
closed not actual
