### ISSUE TITLE
Block with video shown without description - page "Процеси" - lesson "SDLC/STLC"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#715]
**STR**

1. Open https://www.qax-camp.com.ua/courses/processes/. You should be login to the page;
2. Open the lesson "SDLC/STLC";
3. Pay attention to the video;
4. Open https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA scroll to the end of the page, to 1.10.1 line.

**ACTUAL RESULT**
Block with video on the page without a description, that does not match the requirement in the Wiki.

**EXPECTED RESULT**
Block with the video shown with the description as in Wiki "Якщо Урок має відео, то відео має містити прев'ю"

![PoKW1Fc4tZ](https://user-images.githubusercontent.com/109384052/232290440-934c1871-0f56-4acd-a42f-aabf28dbae46.png)
![8DLBu2bAvC](https://user-images.githubusercontent.com/109384052/232290445-83c086e4-f0e5-46af-98db-7e11dd0e501d.png)

**Comment by BatalovaOlha** [comment]
#580

**Comment by scholokov** [comment]
так на скріні присутне превью....

**Comment by BatalovaOlha** [comment]
Напевно тоді в мене запитання по вимогам, чи має бути опис до відео чи відео допустимо так як є, без опису?
