### ISSUE TITLE
Block with video shown without description - page "Процеси" - lesson "SCRUM"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#718]
**STR**

1. Open https://www.qax-camp.com.ua/courses/processes/. You should be login to the page;
2. Open the lesson "SCRUM";
3. Pay attention to the video;
4. Open https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA scroll to the end of the page, to 1.10.1 line.

**ACTUAL RESULT**
Block with video on the page without a description, that does not match the requirement in the Wiki.

**EXPECTED RESULT**
Block with the video shown with the description as in Wiki "Якщо Урок має відео, то відео має містити прев'ю"

![49IqpRuv1U](https://user-images.githubusercontent.com/109384052/232292736-c3c577ef-b4d1-40fb-8473-19049f70146c.png)
![8DLBu2bAvC](https://user-images.githubusercontent.com/109384052/232292760-a6bd66fa-51d3-45ac-bc95-fd9d2c096173.png)

**Comment by BatalovaOlha** [comment]
#580

**Comment by scholokov** [comment]
так на скріні присутнє превью...
