### ISSUE TITLE
"Про нас" page - block "Що таке Camp?" - text does not match requirements

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#72]
**STR** 
1. Open https://portal.qax-camp.com.ua/about-us/
2. Scroll to the block "Що таке Camp?"
3. Open https://github.com/scholokov/qax-portal-2/wiki/About-us-page#%D0%A9%D0%BE-%D1%82%D0%B0%D0%BA%D0%B5-camp

**ACTUAL RESULT**
The page "Про нас" / block "Що таке Camp?" shows the text that does NOT meet the requirements in the Wiki

**EXPECTED RESULT**
The page "Про нас" / block "Що таке Camp?" shows the text that does meet the requirements in the Wiki

![fKN4r53hjm](https://user-images.githubusercontent.com/109384052/188689270-94643730-94b8-47a0-b0bc-74ff3091342b.png)
![IoUAXVDnjJ](https://user-images.githubusercontent.com/109384052/188689274-7c5dd661-1865-49ce-acde-bc4c8bbe3097.png)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
