### ISSUE TITLE
Order - Створити дизайн сторінки

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#721]
1. Блоки мабуть треба розмістити вертикально
2. Ціна - поруч з "Придбати зараз"

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/22824947/232460910-92919c97-ed6e-4bc4-a6a2-d35ef9e90048.png">

подивитися приклад:
https://www.qax-camp.com.ua/product/test/

**Comment by ButKoff** [comment]
#768

**Comment by ODrobik** [comment]
verified
