### ISSUE TITLE
Checkout - створити дизайн сторінки

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#722]
<img width="653" alt="image" src="https://user-images.githubusercontent.com/22824947/232462561-eb7fc59b-e27c-4be8-aab9-6ce28fc301ad.png">

<img width="725" alt="image" src="https://user-images.githubusercontent.com/22824947/232471357-9baa1d35-0b07-4197-b78a-071f5972ac59.png">

**Comment by AlonaSarapina** [comment]
ready for testing 
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6398%3A1146&t=pXJldqInpmQtCDFK-1

**Comment by ButKoff** [comment]
#769

**Comment by ODrobik** [comment]
verified
