### ISSUE TITLE
Chechout - Authorization - Дизайн блока 

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#723]
1. Зробити дизайн блоку авторизації

<img width="772" alt="image" src="https://user-images.githubusercontent.com/22824947/232472154-11b56c80-ba4f-4ff1-a824-cdfd0fbf0bbd.png">

<img width="745" alt="image" src="https://user-images.githubusercontent.com/22824947/232472313-303db23f-072b-4045-b2d4-e26ebe43bf19.png">

**Comment by AlonaSarapina** [comment]
ready for testing 
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6398%3A1146&t=pXJldqInpmQtCDFK-1

**Comment by ButKoff** [comment]
#769

**Comment by ODrobik** [comment]
verified
