### ISSUE TITLE
courses/practise/lessons/defect/  grammatiacal erros on page 

### ISSUE THREAD

**Issue by TetianaSulima** [scholokov/qax-portal-2#726]
Prerequisites:
Open https://www.qax-camp.com.ua/courses/practise/lessons/defect/

Steps to reproduce:

1. Scroll down to "Складносурядні та складнопідрядні речення"

2. Pay attention to red lined word .

Actual result: grammatiacal error on page
побудована

Expected result: correct is
побудоване 

![image](https://user-images.githubusercontent.com/123786969/232638408-db1577ff-6a25-48b1-a75e-3879a94d2145.png)

Environment: Windows 10 Home
system:
Browser: Google Chrome Version 110.0.5481.178

**Comment by DmytroMarkulych** [comment]
@TetianaSulima прономеруйте будь ласка кроки для відтворення

**Comment by scholokov** [comment]
виправлено

**Comment by Nadiyk** [comment]
Pass
