### ISSUE TITLE
Test Documentation / Default preview before the test

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#727]
**Steps to reproduce:**
1. Open https://www.qax-camp.com.ua/quizzes/q5-test-documentation/
2. Pay attention to the preview before the test.

**Actual result:**
Preview before the test is default.

**Expected result:**
Preview before the test is not default.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/232709042-d343b424-1a34-4d55-a4ed-ba7109e3e979.png)

**Comment by GNatala** [comment]
#87

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
passed
