### ISSUE TITLE
Test Documentation / Missed Timer in the test

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#728]
**Steps to reproduce:**
1. Open https://www.qax-camp.com.ua/quizzes/q5-test-documentation/
2. Click on "Розпочати Тест" under the picture.
3. Test is opened.
4. Pay attention to the absence of the Timer under the preview.

**Actual result:**
There is no Timer under the preview.

**Expected result:**
There is Timer under the preview.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://github.com/scholokov/qax-portal-2/wiki/1.7.3.-Tests
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=931-91&t=jUQfGSH0fMRG4agN-0

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/232724848-3a94b82a-4abb-40de-bd10-fc4f7a6dd932.png)

**Comment by GNatala** [comment]
#87

**Comment by scholokov** [comment]
виправлено
