### ISSUE TITLE
Test Documentation / Missed Progress bar with number of questions in the test

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#729]
**Steps to reproduce:**
1. Open https://www.qax-camp.com.ua/quizzes/q5-test-documentation/
2. Click on "Розпочати Тест" under the picture.
3. Test is opened.
4. Pay attention to the absence Progress bar with number of questions.

**Actual result:**
**No Progress bar** with number of questions.

**Expected result:**
There is **Progress bar with number of questions.**

**Additional information:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=931-91&t=cF5vwEobCy3PRQtA-0

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/232733730-a3554001-655c-460f-9ce8-ef5bde77bb89.png)

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
passed
