### ISSUE TITLE
WIKI requirements - About us page - block "Що таке Camp?" - wrong name of the course "IT Recruiter"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#73]
**STR**
1. Open https://github.com/scholokov/qax-portal-2/wiki/About-us-page#%D0%A9%D0%BE-%D1%82%D0%B0%D0%BA%D0%B5-camp
2. Pay attention to the second paragraph in the block "Що таке Camp?"

**ACTUAL RESULT**
The Wiki requirements show the name of the course "Recruitment"

**EXPECTED RESULT**
The Wiki requirements show the name of the course "IT Recruiter"

![6B1YNAhpSW](https://user-images.githubusercontent.com/109384052/188695319-6068120a-a5c2-468f-a00b-7dc94716426e.png)
![rGrHiy9Og6](https://user-images.githubusercontent.com/109384052/188695323-33aff93a-eaf2-4b5e-8b05-e7d42f357007.png)

**Comment by DmytroMarkulych** [comment]
1. В Summary НЕ використовуйте, будь ласка, слова типу wrong, incorrect, don't-doesn't work ... вони не дають конкретики в опис дефекту і збивають із суті проблеми.

**Comment by ABatalov** [comment]
@BatalovaOlha, напоминаю, что нужно баги/таски которые перемещены в Resolved должны быть отмечены как Close
