### ISSUE TITLE
Test Documentation / Mis font of the name of the question "Коли бажано використовувати Test case?” - font style is italic, font weight 400

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#734]
**Steps to reproduce:**
1. Open  https://www.qax-camp.com.ua/quizzes/q5-test-documentation/
2. Click on "Розпочати Тест" under the picture.
3. Test is opened.
4. Find question "Коли бажано використовувати Test case?".
5. Pay attention to the font of the name of the question.

**Actual result:**
**Name of the question** "Коли бажано використовувати Test case?” - **font style is italic, font weight 400.**

**Expected result:**
**Name of the question** "Коли бажано використовувати Test case?” - **font style is normal, font weight 700.**

**Additional information:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=931-91&t=cF5vwEobCy3PRQtA-0

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/232745459-a807dfce-eb34-4237-ac1f-40b9f9d198fe.png)

**Comment by GNatala** [comment]
#87

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
passed
