### ISSUE TITLE
Test "Тестувальник. Хто це?" / Mis font of 8 from 10 names  questions of the test - font style is italic, font weight 400

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#735]
**Steps to reproduce:**
1. Open  https://www.qax-camp.com.ua/quizzes/q5-01-who-is-qa/
2. Click on "Розпочати Тест" under the picture.
3. Test is opened.
4. Pay attention to the font of the title of the questions.

**Actual result:**
**8 from 10 question titles of the test**  - **font style is italic, font weight 400.**

**Expected result:**
**10 question titles of the test** " - **font style is normal, font weight 700.**

**Additional information:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=931-91&t=cF5vwEobCy3PRQtA-0

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/232784868-ededdbad-e4a6-4099-9e16-034dbdfa0f26.png)

**Comment by GNatala** [comment]
[#83](https://github.com/scholokov/qax-portal-2/issues/83)

**Comment by GNatala** [comment]
An issue is reproduced.

**Actual result:**
8 from 10 question titles of the test - font style is italic, font weight 400.

**Expected result:**
10 question titles of the test " - font style is normal, font weight 700.

**Additional information:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=931-91&t=cF5vwEobCy3PRQtA-0

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/8f7edc38-df4e-4b20-823c-005aa303b322)
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/08918f5d-fe46-4c3b-9124-fb2d230b6604)

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
passed
