### ISSUE TITLE
Calendar - Імплементувати блок "Календар"

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#737]
Імплементувати блок "Календар", щоб його можна було додавати на різні сторінки

дизайн:
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=6112-975&t=VcNUBChuF7ljf4VF-0

функціонал (використовуємо саме той що на скріні):
![image](https://user-images.githubusercontent.com/22824947/233032619-caa9738b-e21a-4bca-badc-931cb18c6f4b.png)
https://www.qax-camp.com.ua/calendar/

**Comment by poroskundenys** [comment]
Дизайн блока, который появляется при наведении, не получится переделать. Его позиция и стили на js формируются

**Comment by GNatala** [comment]
verified
