### ISSUE TITLE
 Розділу "English for QA" Немає у вимогах 

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#738]
Prerequisites:
Open https://www.qax-camp.com.ua/
Steps to play:

 1. Відкрийте розділ 1.2 Courses page
 2. Прокрутіть сторінку до розділіу "Обирай свій напрям та починай рух до цілі разом з QA"
 3. Зверніть увагу, що немає розділу "English for QA"

Actual result:  Розділу "English for QA" Немає у вимогах 
Expected result:  Розділ "English for QA" є у вимогах 

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104
![англійська для кюа, немає в вимогах](https://user-images.githubusercontent.com/113175298/233355353-13993359-f6d9-4ad4-8498-2acd92fe23f3.png)

**Comment by Nadiyk** [comment]
#338

**Comment by ABatalov** [comment]
Fixed: https://github.com/scholokov/qax-portal-2/wiki/1.2.-Courses-page

**Comment by Nadiyk** [comment]
Pass
