### ISSUE TITLE
QA BASIC - Text points Elipse - Not available 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#74]
Steps To Reproduce: 
Open https://portal.qax-camp.com.ua/courses/q2-basic-cource/
Pay attention block text "на курсі тебе чекає" 

Expected result: 
<img width="1440" alt="Снимок экрана 2022-09-08 в 12 24 04 PM" src="https://user-images.githubusercontent.com/110661667/189086578-b15c97b5-b97c-45b2-b80e-7f3f592e2e6b.png">
Actual result: 
<img width="1440" alt="Снимок экрана 2022-09-08 в 12 28 20 PM" src="https://user-images.githubusercontent.com/110661667/189087294-10583e60-593a-4c9f-bc72-c6ba174a980c.png">

**Comment by scholokov** [comment]
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A12775

**Comment by Xalep4ik** [comment]
verified
