### ISSUE TITLE
Missing word  "твоє" в розділі "Підготовка до проходження співбесіди. Створення CV" 

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#742]
Prerequisites:
Open: https://www.qax-camp.com.ua/courses/cv/
Steps to play:

1.  Click on the button "Курси в записі"
2.  Click on the button "Підготовка до співбесіди"
3.  Pay attention to the missing word in the sentence

Actual result: Missing word  "твоє" в розділі "Підготовка до проходження співбесіди. Створення CV" 
Expected result: Word  "твоє" в розділі "Підготовка до проходження співбесіди. Створення CV" 

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104
![СВ  Твоя реклама](https://user-images.githubusercontent.com/113175298/233387116-8e00f365-88d4-4e97-8947-03159050085c.png)

**Comment by scholokov** [comment]
виправлено

**Comment by Nadiyk** [comment]
pass
