### ISSUE TITLE
Practice / Mis padding after the text in the block "Мінімальні вимоги"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#744]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/practice/
2. Scroll down to the "Мінімальні вимоги".
3. Open it.
4. Pay attention to the padding after the text in the block.

**Actual result:**
There is no padding after the text in the block.

**Expected result:**
There is padding after the text in the block.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/233636174-20aeff76-ff14-4d93-8bd1-7d177bad9fdc.png)

**Comment by scholokov** [comment]
а де лінка на дизайн, так як проблема стосується саме дизайну...

**Comment by GNatala** [comment]
@scholokov На жаль, цього немає в Filma. Це реалізовано в інших блоках з текстом та в блоці "Діючі проєкти" (хоча там трохи інша логіка).

Питання в тому, що після тексту або між основним текстом і блоком з картками курсів немає відступу.

![image](https://user-images.githubusercontent.com/101987790/233996269-629c8e82-c3b5-4120-a553-8faaecbfd374.png)

**Comment by GNatala** [comment]
passed
