### ISSUE TITLE
Practice / Mis space after the text in the block "Підписка на використання навчальних матеріалів"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#745]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/practice/
2. Scroll down to the "Підписка на використання навчальних матеріалів".
3. Open it.
4. Pay attention to the padding after the text in the block.

**Actual result:**
There is no padding after the text in the block.

**Expected result:**
There is padding after the text in the block.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/233642328-d89264f8-814a-4358-8045-08536000495e.png)

**Comment by GNatala** [comment]
https://github.com/scholokov/qax-portal-2/issues/628

**Comment by DmytroMarkulych** [comment]
@GNatala Елемент на сторінці не обовязково може мати padding,він може отримувати за рахунок іншого елемента відносно якого він вирівняний. Додайте будь ласка точні значення в опис дефекту

**Comment by GNatala** [comment]
Дякую. Переформулюю, бо маю на увазі відступ між текстом та наступним блоком карток.

**Comment by GNatala** [comment]
@scholokov На жаль, цього немає в Filma. Це реалізовано в інших блоках з текстом та в блоці "Діючі проєкти" (хоча там трохи інша логіка).

Питання в тому, що після тексту або між основним текстом і блоком з картками курсів немає відступу.

![image](https://user-images.githubusercontent.com/101987790/233996269-629c8e82-c3b5-4120-a553-8faaecbfd374.png)

**Comment by GNatala** [comment]
passed
