### ISSUE TITLE
Test "Види тестування" / Mis font of all 10 question titles of the test - font style is italic

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#746]
**Steps to reproduce:**
1. Open  https://www.qax-camp.com.ua/quizzes/q5-test-types/
2. Click on "Розпочати Тест" under the picture.
3. Test is opened.
4. Pay attention to the font style of the title of the questions.

**Actual result:**
**All 10 question titles of the test**  - **font style is italic.**

**Expected result:**
**All 10 question titles of the test**  - **font style is normal.**

**Additional information:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=931-91&t=cF5vwEobCy3PRQtA-0

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://user-images.githubusercontent.com/101987790/233661459-5372e869-8b22-4c19-a0ce-b7b4cbcaf56d.png)

![image](https://user-images.githubusercontent.com/101987790/233663243-f8f37dcc-fad9-4753-9583-ed6059326597.png)

**Comment by GNatala** [comment]
#84

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
passed
