### ISSUE TITLE
Recruitment - Test types of IT companies - Test text in Russian

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/qax-portal-2#75]
Steps To Reproduce:
1. Open https://portal.qax-camp.com.ua/courses/recruiter-program/lessons/differense-in-type-of-it-comanies/quizzes/%d1%82%d0%b5%d1%81%d1%82-%d0%bf%d0%be-%d0%bc%d0%b0%d1%82%d0%b5%d1%80%d0%b8%d0%b0%d0%bb%d0%b0%d0%bc-%d0%bb%d0%b5%d0%ba%d1%86%d0%b8%d0%b8-%d0%b2%d0%b8%d0%b4%d1%8b-%d0%b8%d1%82-%d0%ba%d0%be%d0%bc%d0%bf/
2. Click the "Start Quiz" button
3. Pay attention to the language of the test 

Actual result:  The text of the test is in Russian
Expected result: The text of the test is in **Ukrainian** 
<img width="1440" alt="Снимок экрана 2022-09-08 в 1 58 48 PM" src="https://user-images.githubusercontent.com/110661667/189105654-c2bbc6d8-dba7-4378-984f-27c249c1e780.png">
<img width="1440" alt="Снимок экрана 2022-09-08 в 1 58 29 PM" src="https://user-images.githubusercontent.com/110661667/189105683-bb7a7daa-d093-436a-bb8a-1d7655098cbc.png">

**Comment by DmytroMarkulych** [comment]
@LesiaBezukh зверніть увагу на послідовність Actual and Expected Results

**Comment by scholokov** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
