### ISSUE TITLE
Test "Рівні тестування" / Mis font of 9 from 10 question titles of the test - font style is italic

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#750]
**Steps to reproduce:**
1. Open  https://www.qax-camp.com.ua/quizzes/q5-test-levels/
2. Click on "Розпочати Тест" under the picture.
3. Test is opened.
4. Pay attention to the font style of the title of the questions.

**Actual result:**
**9 from 10 question titles of the test**  - **font style is italic.**

**Expected result:**
**9 from 10 question titles of the test**  - **font style is normal.**

**Additional information:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=931-91&t=cF5vwEobCy3PRQtA-0

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/234004553-91144ce2-d39d-469e-bab6-83e15b10c582.png)
![image](https://user-images.githubusercontent.com/101987790/234005701-ec9d6f79-e22d-4295-b660-98ea0e591d71.png)

**Comment by GNatala** [comment]
#85

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
