### ISSUE TITLE
Lessons - Check lesson for "Test Plan" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#751]
We need to check lesson for "Test Plan" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/testing/lessons/test-plan/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F
![Test Plan](https://github.com/scholokov/qax-portal-2/assets/109460500/af82a3e2-e848-4cf2-830a-3607f7ef855e)

**Comment by ButKoff** [comment]
#664

**Comment by prokopenkoga1977** [comment]
[#978](https://github.com/scholokov/qax-portal-2/issues/978) , [#979](https://github.com/scholokov/qax-portal-2/issues/979) , [#980](https://github.com/scholokov/qax-portal-2/issues/980) , [#981](https://github.com/scholokov/qax-portal-2/issues/981) , [#982](https://github.com/scholokov/qax-portal-2/issues/982)
