### ISSUE TITLE
Home Page - Regression Testing

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#752]
You should Regression Test the Home Page.
Environment: https://www.qax-camp.com.ua/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.1.-Home-%5Bpage%5D
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408-22&t=SL1szRTR6mFX6rvS-0

**Comment by DmitriiNasonov** [comment]
[GitHub Wiki - 1.1. Home [page] - Content of the block "До оферу разом з QAX" - Symbol "." is missing at the end of the sentence "Вдосконалення через практику на реальних проектах та менторство"#758](https://github.com/scholokov/qax-portal-2/issues/758)

**Comment by DmitriiNasonov** [comment]
Home page - "Обирай свій напрям та починай рух до цілі разом з QAX" block - "English for QA" block is present #759

**Comment by DmitriiNasonov** [comment]
testing completed
