### ISSUE TITLE
Lessons - Check lesson for "Jira" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#753]
We need to check lesson for "Jira" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/jira/
Requirements:https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BA%D0%BE%D1%80%D0%B8%D1%81%D0%BD%D1%96-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%B8

**Comment by ButKoff** [comment]
#664

**Comment by Nadiyk** [comment]
Verified
