### ISSUE TITLE
Test "Тестувальник. Хто це?" / Preview of the Test does not match Wiki requirements 1.1.5-Preview

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#754]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/quizzes/q5-01-who-is-qa/
2. Pay attention to the Preview of the Test.

**Actual result:**
 Preview of the Test does not match Wiki requirements 1.1.5-Preview.

**Expected result:**
Preview of the Test matches Wiki requirements 1.1.5-Preview.

**Additional information:** 
https://github.com/scholokov/qax-portal-2/wiki/1.1.5-Preview

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/234599600-41088955-5e2c-4739-9031-7e3bd95a70e1.png)

**Comment by GNatala** [comment]
#83

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
