### ISSUE TITLE
Practice - Travel - Сheck block "Якщо щось не зрозуміло" on project page "QAX Travel 2.0"

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#756]
We need to check block "Якщо щось не зрозуміло" on project page "QAX Travel 2.0"
Environment: https://www.qax-camp.com.ua/courses/project-travel/lessons/project-dt-travel-2-0/
![Travel](https://user-images.githubusercontent.com/109460500/234858828-9d8dcb8b-b144-4a96-8900-e666277dc5e9.png)

**Comment by DmitriiNasonov** [comment]
checked. Bugs is not found
