### ISSUE TITLE
GitHub Wiki - 1.1. Home [page] - Content of the block "До оферу разом з QAX" - Symbol "." is missing at the end of the sentence "Вдосконалення через практику на реальних проектах та менторство"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#758]
**Steps of reproducing:**
1. Open https://github.com/scholokov/qax-portal-2/wiki/1.1.-Home-%5Bpage%5D
2. Open dropdown "Структура сторінки"
3. Pay attention to the end of the sentence "Вдосконалення через практику на реальних проектах та менторство" in the content of the block "До оферу разом з QAX"

**Actual Result**
A symbol "." is present

**Expected Result**
A symbol "." is missing

**Enviroments**
Windows 10, Chrome 112.0.5615.138 (64 bit)
![1 1  Home  page  · scholokov_qax-portal-2 Wiki - Google Chrome 30 04 2023 16_35_30](https://user-images.githubusercontent.com/95171672/235355819-df9cd6f0-f375-4815-ae5a-4c66b4022dfd.png)

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
verified. bug isn't reproduced
