### ISSUE TITLE
Наші тренери - запропонувати дизайн

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#76]
запропонувати дизайн сторінки "Наші тренери"
https://portal.qax-camp.com.ua/trainers/

наприклад зробити такою як і на кемпі:
https://qax-camp.com.ua/our_trainers.php

**Comment by AlonaSarapina** [comment]
ready for testing 
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=1617%3A70

**Comment by KaterinaNimenko35** [comment]
verified
