### ISSUE TITLE
"Найчастіші питання" section / Spelling mistake оf the word "проект" and its variants

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#760]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/practice/
2. Scroll down to the "Найчастіші питання".
3. Open it.
4. Pay attention to the spelling of the words "проект" in the section.

**Actual result:**
The **word "проект"** and its variants **are written with the letter "е".**

**Expected result:**
The **word "проект"** and its variants **are written with the letter "є".**

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/235364133-a8400125-08d4-4f94-b47b-e81a2f0d94c5.png)

**Comment by GNatala** [comment]
#700

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
passed
