### ISSUE TITLE
"Найчастіші питання" section / Misposition of the part of the sentence "цінними, експертними та актуальними на сьогодні знаннями."

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#761]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/practice/
2. Scroll down to the "Найчастіші питання".
3. Open it, find the 3rd section.
4. Pay attention to the of the sentence "20-річний досвід експерта який напрацьовувався кропіткою працею та постійно вдосконалюється, щоб ділитись з учнями, цінними, експертними та актуальними на сьогодні знаннями."

**Actual result:**
**Part "цінними, експертними та актуальними на сьогодні знаннями."** of the sentence  "20-річний досвід експерта який напрацьовувався кропіткою працею та постійно вдосконалюється, щоб ділитись з учнями, цінними, експертними та актуальними на сьогодні знаннями." **is on the next line.**

**Expected result:**
**Part "цінними, експертними та актуальними на сьогодні знаннями."** of the sentence  "20-річний досвід експерта який напрацьовувався кропіткою працею та постійно вдосконалюється, щоб ділитись з учнями, цінними, експертними та актуальними на сьогодні знаннями." **is on the same line.**

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/235367151-7e3a6cda-ddb0-4f6e-8601-dcb4911ab843.png)

**Comment by GNatala** [comment]
#700

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
