### ISSUE TITLE
"Найчастіші питання" section / Missed punctuation mark "dot" at the end of the sentence "А якщо ціль стати кваліфікованим фахівцем ..."

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#763]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/practice/
2. Scroll down to the "Найчастіші питання".
3. Open it, find the 2rd section.
4. Pay attention to the absence of the punctuation mark "dot" at the end of the sentence "А якщо ціль стати кваліфікованим фахівцем в своєму напрямку, досконало володіти різними практичними інструментами та отримати офер, то бажано працювати на кожному з проєктів"

**Actual result:**
**Punctuation mark "dot" is missed at the end of the sentence** "А якщо ціль стати кваліфікованим фахівцем в своєму напрямку, досконало володіти різними практичними інструментами та отримати офер, то бажано працювати на кожному з проєктів"

**Expected result:**
**Punctuation mark "dot" is at the end of the sentence** "А якщо ціль стати кваліфікованим фахівцем в своєму напрямку, досконало володіти різними практичними інструментами та отримати офер, то бажано працювати на кожному з проєктів"

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/235367843-7006a690-6a34-4b56-804d-efcc2d7a8ac7.png)

**Comment by GNatala** [comment]
#700

**Comment by scholokov** [comment]
виправлено
