### ISSUE TITLE
Lesson "Як тестувати задачу (приклад)?" / Title of the lesson preview "Тестуємо вимоги по Чат-Боту"does not match the title of the lesson

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#764]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/courses/mc-testing/lessons/how-to-test-task/
2. Pay attention to the Preview of the Lesson.

**Actual result:**
 Title of the lesson preview is "Тестуємо вимоги по Чат-Боту" not match the title of the lesson "Як тестувати задачу (приклад)?"

**Expected result:**
Title of the lesson preview is "Як тестувати задачу (приклад)?" and match the title of the lesson "Як тестувати задачу (приклад)?"

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/235496800-401cd7e6-49fb-4cdd-bcb6-96175e2a14ad.png)

**Comment by GNatala** [comment]
#731

**Comment by scholokov** [comment]
виправлено у вимогах

**Comment by GNatala** [comment]
@scholokov 
Трохи уточнень - **урок називається "Як тестувати задачу (приклад)?"**, а на в **Preview назва: "Тестуємо вимоги по Чат-Боту"?**

**Comment by scholokov** [comment]
fixed
