### ISSUE TITLE
Test "Рівні тестування" / Mis font of 9 from 10 question titles of the test - font weight is 400 

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#767]
**Steps to reproduce:**
1. Open  https://www.qax-camp.com.ua/quizzes/q5-test-levels/
2. Click on "Розпочати Тест" under the picture.
3. Test is opened.
4. Pay attention to the font weight of the title of the questions.

**Actual result:**
**9 from 10 question titles of the test**  - **font weight is 400.**

**Expected result:**
**9 from 10 question titles of the test** - **font weight is 700.**

**Additional information:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=931-91&t=cF5vwEobCy3PRQtA-0

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/235888935-a26cf21d-1192-4eac-884f-26544c5d5e3e.png)

**Comment by GNatala** [comment]
#85

**Comment by scholokov** [comment]
виконано

**Comment by GNatala** [comment]
перевірено
