### ISSUE TITLE
Order - Implement a design "Заказ" page according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#768]
We need to implement a design "Заказ" page according to Figma.
Environment: https://www.qax-camp.com.ua/courses/qa-basics/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=6195-1085&t=nViYz7LqwgXH07Vk-0
![Order](https://user-images.githubusercontent.com/109460500/236175467-36a21794-1b5c-435b-b686-6c3f016e05c9.png)

**Comment by ButKoff** [comment]
#721

**Comment by ODrobik** [comment]
verified

**Comment by poroskundenys** [comment]
@scholokov готово

**Comment by ODrobik** [comment]
перевірено

**Comment by ODrobik** [comment]
перевірено
