### ISSUE TITLE
Checkout - Implement a design "Оформить заказ" page according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#769]
We need to implement a design "Оформить заказ" page according to Figma.
Environment: https://qax-camp.com.ua/checkout/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=6398-1146&t=nViYz7LqwgXH07Vk-0
![Checkout](https://user-images.githubusercontent.com/109460500/236182485-a51cb7e0-2aee-4b65-8f34-ce91781ee4b6.png)

**Comment by ButKoff** [comment]
#722

**Comment by ButKoff** [comment]
#723

**Comment by poroskundenys** [comment]
Готово

**Comment by ODrobik** [comment]
verified
