### ISSUE TITLE
Event - Implement a design "Событие" page according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#770]
We need to implement a design "Событие" page according to Figma.
Environment: https://www.qax-camp.com.ua/events/test/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=6076-949&t=nViYz7LqwgXH07Vk-0
![Event](https://user-images.githubusercontent.com/109460500/236186618-904db59d-1981-49ce-b6d9-5fa003f3430a.png)

**Comment by ButKoff** [comment]
#712

**Comment by scholokov** [comment]
так. вбудований у плагін з івентами

**Comment by poroskundenys** [comment]
@scholokov Нужно эту страницу сделать как на макете? https://www.qax-camp.com.ua/events/test/

**Comment by scholokov** [comment]
так

**Comment by poroskundenys** [comment]
@scholokov там есть организаторы и есть спикеры https://prnt.sc/qycOFYm94ufr. Сюда кого выводить https://prnt.sc/22f9zmdwE8bd?

**Comment by scholokov** [comment]
лише спікери
@poroskundenys

**Comment by GNatala** [comment]
verified
