### ISSUE TITLE
Courses - Check course for "Web & Mobile" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#771]
We need to check course for "Web & Mobile" page.
You must test the groups and the order of the lessons as in the requirements.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/
Requirements/courses: https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81
Requirements/lessons: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA

**Comment by ButKoff** [comment]
#663

**Comment by Nadiyk** [comment]
verified
