### ISSUE TITLE
Lessons - Check lesson for "Типові елементи інтерфейсу" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#772]
We need to check lesson for "Типові елементи інтерфейсу" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/lessons/standard-elements/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA
![Елементи інтерфейсу](https://github.com/scholokov/qax-portal-2/assets/109460500/0019770d-c590-4669-a6bf-3906899c677c)
![Типові елементи](https://github.com/scholokov/qax-portal-2/assets/109460500/ea928a02-f63a-41bc-91ea-3a30e1911ee9)

**Comment by ButKoff** [comment]
#664

**Comment by prokopenkoga1977** [comment]
[#836](https://github.com/scholokov/qax-portal-2/issues/836) , [#838](https://github.com/scholokov/qax-portal-2/issues/838) , [#849](https://github.com/scholokov/qax-portal-2/issues/849)
