### ISSUE TITLE
Назва карти ''Log Files'' не співпадає з насзвою у вимогах

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#773]
Необхідні умови:
Відкрийте https://www.qax-camp.com.ua/programs/
Кроки для гри:

1. Вдкрийте розділ "Інструменти"
2. Зверніть увагу на карту ''Log Files'' 

Фактичний результат: Назва карти ''Log Files'' не співпадає з назвою у вимогах
Очікуваний результат: Назва карти у вимогах  ''Log Files''

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 110.0.5481.104
![вимоги помелка](https://user-images.githubusercontent.com/113175298/236243132-ac6cfbb5-d227-48c4-8d53-2c5c2eb9d35b.png)

**Comment by Nadiyk** [comment]
#505

**Comment by DmytroMarkulych** [comment]
@Nadiyk давайте додамо в Очікуваний результат саме те що має бути

**Comment by Nadiyk** [comment]
виправила

**Comment by scholokov** [comment]
ви використовуєте перекладач сторінки, тому не бачите справжні назви
