### ISSUE TITLE
Home page - Create a new design "Главная" page on Portal Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#774]
We need to create new design of "Главная" page on Portal Figma.
Environment: https://www.qax-camp.com.ua/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6704-1434&t=WmH9Nx6Pt04tprzV-0
Canva: https://www.canva.com/design/DAFh3If6i9Q/B65aOnMKqtgYxfFslxPkNQ/edit?utm_content=DAFh3If6i9Q&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
![Home](https://user-images.githubusercontent.com/109460500/236446464-9b407ed5-8879-4e7b-8049-f53b9f81f9e3.png)
![Напрямки](https://user-images.githubusercontent.com/109460500/236446525-d1b2d3fd-5828-4549-820b-f145c7c48106.png)

**Comment by ButKoff** [comment]
#853

**Comment by BatalovaOlha** [comment]
verified
