### ISSUE TITLE
Карта "Базовий курс QA" не відповідає назві у вимогах

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#775]
Prerequisites:
Open: https://www.qax-camp.com.ua/programs/
Steps to play:

1. Клікніть "Курси в записі"
2. Клікніть "Базові курси"

Actual result: Карта "Базовий курс QA" не відповідає назві у вимогах
Expected result: Карта "Q2 Базовий курс QA" а у вимогах "Q2 Базовий курс QA"

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104
![кюа2](https://user-images.githubusercontent.com/113175298/236472146-f301871b-6d39-4810-83ba-8623a7d9728b.png)

**Comment by Nadiyk** [comment]
#505

**Comment by DmytroMarkulych** [comment]
@Nadiyk давайте в очікуваний результат додамо назву яка має бути по факту

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk Summary виглядає як очікуваний та фактичні результати об'єднані.

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk 
Actual result: Карта "Базовий курс QA" а у вимогах "Q2 Базовий курс QA"
Expected result: Карта "Q2 Базовий курс QA" а у вимогах "Q2 Базовий курс QA"
Два ідентичні тексти, будь ласка виправте щоб очікуваний був очікуваним, а актуальний - актуальним

**Comment by Nadiyk** [comment]
виправила

**Comment by Nadiyk** [comment]
Pass
Вимоги
https://github.com/scholokov/qax-portal-2/wiki/1.7.-Materials
