### ISSUE TITLE
Картка "Тестування" відсутня у вимогах

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#777]
Prerequisites:
Open: https://www.qax-camp.com.ua/programs/
Steps to reproduce :

1. Зверніть увагу, що на сайті є карта "Тестування"
2. Зверніть увагу, що у вимогах карти  " Тестування" немає

Actual result: Карта  "Тестування" відсутня у вимогах  
Expected result: Карта  "Тестування" є у вимогах 

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104
![карти Тестування немає](https://user-images.githubusercontent.com/113175298/236477765-83247d66-9a95-4aff-b91a-d306355482db.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk Давайте summary сформулюємо таким чином, що воно відповідало на питання Де ? Що? Коли?

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk  Вийшло summary із двома умовами, давайте зробимо щоб була тільки одна

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk "Картка "Тестування" відсутня в вимогах"

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk то картка Є чи вона відсутня у вимогах?)

**Comment by Nadiyk** [comment]
Виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk і поправте будь ласка в Актуальному і очікуваному результатах

**Comment by Nadiyk** [comment]
Виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk 

![Image](https://github.com/scholokov/qax-portal-2/assets/88647733/f7bad772-1626-40a8-837f-f631c5e2c927)

давайте переправимо таким чином щоб було порівнянь

**Comment by Nadiyk** [comment]
виправила

**Comment by scholokov** [comment]
виправлено

**Comment by Nadiyk** [comment]
Pass
