### ISSUE TITLE
Колір заголовка "Пять складових професійного QA" на фігмі білий

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#779]
Необхідні умови:
Відкрийте https://www.qax-camp.com.ua/programs/
Кроки для відтворення:

1. Зверніть, що колір заголовка "Пять складових професійного QA" #F66F5D
2. На фігмі #E9E8EA 

Фактичний результат:  Колір заголовка "Пять складових професійного QA" на фігмі білий
Оцінений результат: Колір заголовка "Пять складових професійного QA" на фігмі та на сайті червоного кольору 

Посилання на фігму: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=5473-3066&t=oQeC49iN6y6v6t5d-0

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 110.0.5481.104
![FIGMA #E9E8EA - #F66F5D](https://user-images.githubusercontent.com/113175298/236618796-0675ef2c-6927-48eb-8287-4a0da174b9ac.png)

**Comment by Nadiyk** [comment]
#239

**Comment by DmytroMarkulych** [comment]
@Nadiyk Summary вийшло із двома умовами, давайте зробимо щоб була одна

**Comment by Nadiyk** [comment]
виправила

**Comment by Nadiyk** [comment]
Виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk 
1. В Summary - напишіть що у нас є фактично на сайті (що колір заголовку білий)
2. В баг репорті використовуються кроки для відтворення, не для гри
3. Кроки для відтворення пишуться в наказовому способі, без "а у.."
4. Очікуваний та Фактичні результати, призначені для того шоб в них було що є по факту, і що має бути. 
5. І цей дефект буде відтворюватися на всіх девайсах швидше за все
6. Додайте посилання на дизайн в баг репорт

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk Що ми тестуємо? дизайн чи сайт?

**Comment by Nadiyk** [comment]
дизайн на відповідність вимогам

**Comment by DmytroMarkulych** [comment]
@Nadiyk а можна тоді будь ласка додати вимоги?

**Comment by DmytroMarkulych** [comment]
@Nadiyk щось тут не складається )
