### ISSUE TITLE
Courses - Змінити дизайн шапки курсу

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#78]
Шапка складається з:
- тайлт
- картинка превью
- текст опису

текст опису може бути:
- відсутнім
- бути коротким
- чи бути довгим

зараз якщо він довгий - виглядить не дуже

як варіант - перемістити текст вниз (а не з боку) і  поставити його на всю ширину
як думаеш?

приклад з довгим текстом:
https://portal.qax-camp.com.ua/courses/cv_and_interview/

![image](https://user-images.githubusercontent.com/22824947/189349781-2501b914-b475-4462-929c-475c3e27e6e3.png)

**Comment by AlonaSarapina** [comment]
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A1035

**Comment by Nadiyk** [comment]
Актуальне середовище: https://github.com/scholokov/qax-portal-2/issues/78

**Comment by Nadiyk** [comment]
Verufied

**Comment by Nadiyk** [comment]
Verified
