### ISSUE TITLE
Lessons - Check lesson for "Total Commander" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#780]
We need to check lesson for "Total Commander" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/total-commander/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BA%D0%BE%D1%80%D0%B8%D1%81%D0%BD%D1%96-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%B8

**Comment by ButKoff** [comment]
#664

**Comment by prokopenkoga1977** [comment]
[#975](https://github.com/scholokov/qax-portal-2/issues/975) , [#976](https://github.com/scholokov/qax-portal-2/issues/976) , [#977](https://github.com/scholokov/qax-portal-2/issues/977)
