### ISSUE TITLE
Course - Desktop - Header - змінити структуру

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#79]
Тільки на десктопі
внести зміни стосовно дизайну:

було:
![image](https://user-images.githubusercontent.com/22824947/189357225-ef0a3fdd-2c9a-4b67-b3e0-b8a826fcd5fe.png)

треба:
![image](https://user-images.githubusercontent.com/22824947/189357282-7b1b0c8d-2569-4e05-95bc-9096b1b1b809.png)

подивитися можна тут:
https://portal.qax-camp.com.ua/courses/cv_and_interview/

дизайн:
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A1035

**Comment by KaterinaNimenko35** [comment]
verified
