### ISSUE TITLE
Заголовок "П"ять складових профисійного QA" на сайті червоного кольору

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#790]
Необхідні умови:
Відкрийте https://www.qax-camp.com.ua/programs/
Кроки для відтворення:

1. Відкрийте код заголовка  "П"ять складових профисійного QA"
2. Зрівняйте колір з фігмою 

Фактичний результат: Заголовок "П"ять складових профисійного QA" на сайті червоного кольору
Очікуваний результат: Заголовок "П"ять складових профисійного QA" на фігмі та на сайті  червоного кольору
Середовище: Samsung Galaxy M52
система: Android
Браузер: Google Chrome 113.0.5672.76
![самсунг](https://github.com/scholokov/qax-portal-2/assets/113175298/10638397-bfce-4124-8cef-136710dd4906)

**Comment by Nadiyk** [comment]
#554

**Comment by DmytroMarkulych** [comment]
@Nadiyk  В Summary пишемо фактично що маємо на сайті

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk

1. В Summary - напишіть що у нас є фактично на сайті 
2. Очікуваний та Фактичні результати, призначені для того шоб в них було що є по факту, і що має бути.
3. Додайте посилання на дизайн в баг репорт

**Comment by Nadiyk** [comment]
Виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk зверніть увагу на зауваження 2 та 3

**Comment by scholokov** [comment]
виправлено

**Comment by Nadiyk** [comment]
Pass
