### ISSUE TITLE
About Us - Implement a design "Про Нас" page according to Figma

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#793]
We need to implement a design "Про Нас" page according to Figma.
Test Environment: https://www.qax-camp.com.ua/about-us-2/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=2090-286&t=GUFBCOMowu1LERrt-0
![About Us](https://github.com/scholokov/qax-portal-2/assets/109460500/e73c79bc-9318-4cb9-9932-4de4350874b9)

**Comment by ButKoff** [comment]
#789

**Comment by BatalovaOlha** [comment]
verifed
