### ISSUE TITLE
Irrelevant work experience "Досвід роботи 5 років" - тренер Андрій Самойленко - page "Наші тренери"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#795]
**STR**

Open https://www.qax-camp.com.ua/trainers/ and pay attention to the work experience "Андрій Самойленко"

**ACTUAL RESULT**
Work experience showed as 5 років

**EXPECTED RESULT**
Work experience should be "Досвід роботи 6 років"
![mittlouQrL](https://github.com/scholokov/qax-portal-2/assets/109384052/36329e87-3394-40e9-a22d-fd34d0550a31)

**Comment by scholokov** [comment]
fixed
