### ISSUE TITLE
Irrelevant work experience "Досвід роботи 10 років" - тренер Олеся Ломенко - page "Наші тренери"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#796]
**STR**

Open https://www.qax-camp.com.ua/trainers/ and pay attention to the work experience "Олеся Ломенко"

**ACTUAL RESULT**
Work experience showed as 10 років

**EXPECTED RESULT**
Work experience should be "Досвід роботи 11 років"

![ca0Ebdeh4A](https://github.com/scholokov/qax-portal-2/assets/109384052/34205547-7460-4db6-ab95-2a2ddf890aa3)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
resolved
