### ISSUE TITLE
Irrelevant work experience "Досвід роботи 4 років" - тренер Юлія Рудченко - page "Наші тренери"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#797]
**STR**

Open https://www.qax-camp.com.ua/trainers/ and pay attention to the work experience "Юлія Рудченко"

**ACTUAL RESULT**
Work experience showed as 4 років

**EXPECTED RESULT**
Work experience should be "Досвід роботи 5 років"
![chrome_royrijQxgY](https://github.com/scholokov/qax-portal-2/assets/109384052/daad1a8a-063c-4408-af12-e1f3dc2ac813)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/qax-portal-2/assets/88647733/71f0fd25-3590-4518-b339-85b942248c3d)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verifed
