### ISSUE TITLE
Irrelevant work experience "Досвід роботи 6 років" - тренер Ольга Компанець - page "Наші тренери"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#798]
**STR**

Open https://www.qax-camp.com.ua/trainers/ and pay attention to the work experience "Ольга Компанець"

**ACTUAL RESULT**
Work experience showed as 6 років

**EXPECTED RESULT**
Work experience should be "Досвід роботи 8 років"

![BombTKDBK9](https://github.com/scholokov/qax-portal-2/assets/109384052/2e4bb629-0be1-4f25-ac89-7999da2445f9)

**Comment by scholokov** [comment]
виправлено

**Comment by BatalovaOlha** [comment]
Verified
