### ISSUE TITLE
Irrelevant work experience "Досвід роботи 10 років" - тренер Дарія Казарінова - page "Наші тренери"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#799]
**STR**

Open https://www.qax-camp.com.ua/trainers/ and pay attention to the work experience "Дарія Казарінова"

**ACTUAL RESULT**
Work experience showed as 10 років

**EXPECTED RESULT**
Work experience should be "Досвід роботи 13 років"

![Ws4LRzSB35](https://github.com/scholokov/qax-portal-2/assets/109384052/d5368ea1-2465-419a-b34f-7b66881f81c4)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/qax-portal-2/assets/88647733/649883a4-0d10-4176-bdec-28ea5ce66ee2)

**Comment by BatalovaOlha** [comment]
changed

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
Verified
