### ISSUE TITLE
Lesson - Button - Позначити як виконане

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#80]
Button - Позначити як виконане - змінити дизайн

було:
![image](https://user-images.githubusercontent.com/22824947/189374561-d2d4f26b-18fc-446a-ab78-069054624cf9.png)

треба:
![image](https://user-images.githubusercontent.com/22824947/189374646-8e6e069f-553c-4db3-b3f5-6a19e42c99f2.png)

приклад:
https://portal.qax-camp.com.ua/courses/cv_and_interview/lessons/cv-hr/

дизайн:
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A12775

**Comment by KaterinaNimenko35** [comment]
Verified
