### ISSUE TITLE
Irrelevant work experience "Досвід роботи 6 років" - тренер Ольга Лавриненко - page "Наші тренери"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#800]
**STR**

Open https://www.qax-camp.com.ua/trainers/ and pay attention to the work experience "Ольга Лавриненко"

**ACTUAL RESULT**
Work experience showed as 6 років

**EXPECTED RESULT**
Work experience should be "Досвід роботи 7 років"

![OIAO6INMyF](https://github.com/scholokov/qax-portal-2/assets/109384052/c20343b2-e7d7-4999-bffb-a60baedd13d4)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
resolved
