### ISSUE TITLE
Irrelevant work experience "Досвід роботи 10 років" - тренер Максим Плакса - page "Наші тренери" 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#801]
**STR**

Open https://www.qax-camp.com.ua/trainers/ and pay attention to the work experience "Максим Плакса "

**ACTUAL RESULT**
Work experience showed as 10 років

**EXPECTED RESULT**
Work experience should be "Досвід роботи 11 років"

![vKK6eqTGYO](https://github.com/scholokov/qax-portal-2/assets/109384052/3582b713-590e-4fe0-8c9b-ea47739ce4d3)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/qax-portal-2/assets/88647733/09a4182d-b2bd-4be8-8dfb-8bf526a238c5)

**Comment by scholokov** [comment]
виправлено

**Comment by BatalovaOlha** [comment]
verifed
