### ISSUE TITLE
"Як тестувати задачу (приклад)?" page #731/The word "приклад" in the requirements in the sentence "Як тестувати задачу (приклад)?"  with a small letter

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#809]
**Steps to retroduce:**
1. Open: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F--%D0%BC%D0%B0%D0%B9%D1%81%D1%82%D0%B5%D1%80-%D0%BA%D0%BB%D0%B0%D1%81%D0%B8
2. Pay attantion to the sentence "Як тестувати задачу (приклад)?"
3. Open: https://www.qax-camp.com.ua/courses/mc-testing/lessons/how-to-test-task/
4. Pay attantion to the sentence "Як тестувати задачу (Приклади)?"
**Actual result:**
The word "приклад" in the requirements in the sentence "Як тестувати задачу (приклад)?"  with a small letter and with a capital letter on the website page.

**Expected result:**
The word "Приклади" must be capitalized in both cases.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F--%D0%BC%D0%B0%D0%B9%D1%81%D1%82%D0%B5%D1%80-%D0%BA%D0%BB%D0%B0%D1%81%D0%B8

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/5e4a4862-b579-497e-a88f-42186fbc060a)

**Attachments:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/78416f1b-157d-4f0e-855e-84491ec2bc0b)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
