### ISSUE TITLE
Courses - Блок з ціною

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#81]
Розробити дизайн блока з ціною
Design on Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A1035&t=KRZJePyQWgzWdn69-0
Test environment: https://portal.qax-camp.com.ua/courses/cv_and_interview/
![Price](https://user-images.githubusercontent.com/109460500/206704389-3a7da706-13eb-452f-89a4-0fb249d1efa2.png)

**Comment by AlonaSarapina** [comment]
ready for testing 
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A1035

**Comment by KaterinaNimenko35** [comment]
verified
