### ISSUE TITLE
Courses - Повідомлення про те що курс недоступний

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#82]
1. Вибрати курс, який недоступний
2. підвести мишку до назви lesson
- Повідомлення з'являється при ховері

подивитись можна тут:
https://portal.qax-camp.com.ua/courses/cv_and_interview/

![image](https://user-images.githubusercontent.com/22824947/189379063-3d978b88-b320-4c23-a977-2e0a18686a7a.png)

**Comment by AlonaSarapina** [comment]
ready for testing https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A1036

**Comment by AlonaSarapina** [comment]
![ggg](https://user-images.githubusercontent.com/99277105/191994964-42a24eb9-29af-4c36-90ab-9548b30b053f.JPG)

**Comment by dmitryylev** [comment]
verified
