### ISSUE TITLE
"Тестування" course - Header - Description is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#825]
**Steps of reproducing:**
1.  Open https://www.qax-camp.com.ua/courses/testing/
2. Pay attention to space under name of the course

**Actual Result**
Description is missing

**Expected Result**
Description is present

**Additional information**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=390-1035&t=NzZ9qcFPtB2AIMzN-0

https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81#%D0%BF%D0%BE%D0%B2%D0%BD%D0%B8%D0%B9-%D0%BF%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA-%D0%BA%D1%83%D1%80%D1%81%D1%96%D0%B2

**Enviroments**
Windows 10, Chrome 113.0.5672.127 (64 bit)
Android 8.1.0, Chrome 113.0.5672.132
![Тестування – QAX Camp - Google Chrome 22 05 2023 13_03_08](https://github.com/scholokov/qax-portal-2/assets/95171672/c0a369bf-f4e2-461b-8000-56e7793517c4)
![photo_2023-05-22_16-24-02](https://github.com/scholokov/qax-portal-2/assets/95171672/64a3ba70-7b19-4ac5-bcef-5f756bdc0642)

**Comment by scholokov** [comment]
fixed
