### ISSUE TITLE
"Тестування" course - Body - The lesson "Види, методи та рівні тестування" is present in the course "Тестування" and is not in the requirements

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#826]
**Steps of reproducing:**
1. Open https://www.qax-camp.com.ua/courses/testing/
2. Scroll to "Види, методи та рівні тестування" lesson

**Actual Result**
The lesson "Види, методи та рівні тестування" is present

**Expected Result**
The lesson "Види, методи та рівні тестування" is missing

**Additional information**
https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F

**Enviroments**
Windows 10, Chrome 113.0.5672.127 (64 bit)
Android 8.1.0, Chrome 113.0.5672.132
![Тестування – QAX Camp - Google Chrome 22 05 2023 17_16_57](https://github.com/scholokov/qax-portal-2/assets/95171672/762c3474-f0c3-46ed-9d28-60a3b50971a8)
![photo_2023-05-22_17-16-43](https://github.com/scholokov/qax-portal-2/assets/95171672/e2c8bdb3-ee4e-40bd-a970-7cd32e57956a)

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
