### ISSUE TITLE
"Найчастіші питання" section / Font weight of the 1st and other sections is different

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#831]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/practice/
2. Scroll down to the "Найчастіші питання".
3. Open it.
4. Pay attention to the font weight of the 1st and other sections.

**Actual result:**
Font weight of the 1st and other sections is different.

**Expected result:**
Font weight of the 1st and other sections is the same.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/47fbe5c2-3e97-4282-ac85-db13d9aacd16)
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/5ad4c3e0-f127-415f-bc53-351bcef62cdc)

**Comment by GNatala** [comment]
#700

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
