### ISSUE TITLE
Lessons - Check lesson for "Типові елементи інтерфейсу" page #772/Color of the text "До курсу" is #fff

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#836]
**Steps to retroduce:**
1. Open https://www.qax-camp.com.ua/courses/web-mobile/lessons/standard-elements/
2. Scroll down to the link "До курсу".
3. Enter the button "Позначити як невиконане"
4. Pay attention to the color of the text of link "До курсу".
**Actual result:**
Color of the text "До курсу" is #fff if the enter button "Позначити як невиконане" is pressed.

**Expected result:**
Color of the text "До курсу" must be #E9E8EA 

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:**https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=390-12776&t=svjoJ5Z0XZQDVBCm-0

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/1ff9b423-e02f-4e7e-aaf2-d74284ff6501)

**Attachments:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/681c951f-ad0d-48ee-8bca-5b86fdb62112)

**Comment by poroskundenys** [comment]
В инкогнито эта страница не открывается. Для пользователя у меня так https://prnt.sc/2Nhd2ey5_RF2

**Comment by prokopenkoga1977** [comment]
Passed
