### ISSUE TITLE
Checkout - Implement new content in the form "Оформлення замовлення"

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#837]
We need to implement new content in the form "Оформлення замовлення".
Environment: https://www.qax-camp.com.ua/checkout/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=6398-1146&t=nViYz7LqwgXH07Vk-0

Old content:
![Old content_замовлення](https://github.com/scholokov/qax-portal-2/assets/109460500/19d2dfd4-1809-45d0-926c-5717861c16a2)
![Old content_персональні дані](https://github.com/scholokov/qax-portal-2/assets/109460500/a2ae2ca1-67df-4191-a07c-d096b2a54c48)

New content:
![New content_замовлення](https://github.com/scholokov/qax-portal-2/assets/109460500/af41a30c-ea84-4211-9c19-7a09cc64b581)
![New content_персональні дані](https://github.com/scholokov/qax-portal-2/assets/109460500/57057f81-f67c-4ee4-a947-9007427a5270)

**Comment by scholokov** [comment]
fixed

**Comment by poroskundenys** [comment]
Это задание на другом сайте делать?

**Comment by scholokov** [comment]
не. на тому ж
https://qax-camp.com.ua/checkout/
@poroskundenys

**Comment by poroskundenys** [comment]
Для чего используется на сайте Elementor?

**Comment by scholokov** [comment]
здавалося на ньому легше буде редагувати
наразі для цього проекту думаю він зайвий

**Comment by poroskundenys** [comment]
Готово

**Comment by poroskundenys** [comment]
Нужно только текст поменять на новый без изменения дизайна?

**Comment by scholokov** [comment]
так. виключно текст

**Comment by poroskundenys** [comment]
Готово

**Comment by ODrobik** [comment]
verified
