### ISSUE TITLE
Practice - Check new edits in the practical course "QAX Travel 2.0"

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#839]
We need to check new edits in the practical course "QAX Travel 2.0"
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/project-travel/lessons/project-dt-travel-2-0/
![Travel 2 0](https://github.com/scholokov/qax-portal-2/assets/109460500/6b480824-7a80-466c-a35c-f9b1f33e5fc4)

**Comment by DmitriiNasonov** [comment]
Testing completed
