### ISSUE TITLE
Lessons - Check lesson for "Хто такий IT PM" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#840]
We need to check lesson for "Хто такий IT PM" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/pm-basics/lessons/who-is-pm/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%B8-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BC%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%BC%D0%B5%D0%BD%D1%82%D1%83

**Comment by ButKoff** [comment]
#664

**Comment by Nadiyk** [comment]
Verified
