### ISSUE TITLE
PM Courses - Сheck for update in video block "А хто взагалі такий PM?"

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#841]
We need to check for update in video block "А хто взагалі такий PM?".
Environment: https://www.qax-camp.com.ua/pm-courses-2/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.0.2.-Project-Manager-(PM):
![А хто взагалі такий PM](https://github.com/scholokov/qax-portal-2/assets/109460500/eea1c425-a50f-45f4-a711-5392edc75fc5)

**Comment by Nadiyk** [comment]
Verified
