### ISSUE TITLE
After clicking  "політика конфіденційності" open page https://t.qax-camp.com.ua/offer_agreement/ - Page "Checkout"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#843]
**STR**
1. Open https://t.qax-camp.com.ua/checkout/
2. Go to the block "Оформлення замовлення" and click [політика конфіденційності](https://t.qax-camp.com.ua/privacy_policy/).
3. Pay attention to what text is displayed

**ACTUAL RESULT**
After clicking  "політика конфіденційності" open the page https://t.qax-camp.com.ua/offer_agreement/ instead of https://t.qax-camp.com.ua/privacy_policy/ (all platforms)

**EXPECTED RESULT**
After clicking  "політика конфіденційності" https://t.qax-camp.com.ua/privacy_policy/ 

![nf6TkQrCOU](https://github.com/scholokov/qax-portal-2/assets/109384052/c044ed81-918f-4121-aa75-08c100c02bf5)

![Оформлення замовлення – QAX Camp - Google Chrome 2023-05-27 21-40-04](https://github.com/scholokov/qax-portal-2/assets/109384052/3a821d4c-95ad-49a0-a803-cd92edbd1319)

**Comment by BatalovaOlha** [comment]
#769

**Comment by scholokov** [comment]
please retest

**Comment by BatalovaOlha** [comment]
Verified
