### ISSUE TITLE
No displayed typing numbers in the line "Телефон" - form "Оформлення замовлення" - page "Checkout" - all platforms

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#844]
**STR**
1. Open https://t.qax-camp.com.ua/checkout/#  and try to type the phone number in the line "Телефон"

**ACTUAL RESULT**
When you type the phone number in the line "Телефон" numbers are NOT displayed 

**EXPECTED RESULT**
Numbers **displaying** during the phone number typing 

![Оформлення замовлення – QAX Camp - Google Chrome 2023-05-27 22-00-36 (1)](https://github.com/scholokov/qax-portal-2/assets/109384052/4d9ea1e9-feb5-45f2-9264-02f56fc2391a)

**Comment by BatalovaOlha** [comment]
#769

**Comment by scholokov** [comment]
fixed
