### ISSUE TITLE
Incorrect Error message when you try pay for oder - page "Оформлення замовлення" - page "Checkout"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#845]
**STR**
1. Open https://t.qax-camp.com.ua/checkout/# 
2. Fill in all the lines in the block "Платіжні дані"
3. Click the button "Підтвердити замовлення" 
4. Pay attention to the error message

**ACTUAL RESULT**
After filling in all lines in the block "Платіжні дані" whit correct data (except CVV2) shown the wrong error message (shown that should filled in lines with Name/Surname/Phone/E-mail)  

**EXPECTED RESULT**
After filling incorrect CVV2 an error message should be displayed 

![chrome_qjjhvp2Vqe](https://github.com/scholokov/qax-portal-2/assets/109384052/7165312e-00c4-47d5-af44-72f55813513f)

**Comment by BatalovaOlha** [comment]
#769

**Comment by scholokov** [comment]
please retest

**Comment by BatalovaOlha** [comment]
verified
