### ISSUE TITLE
Create page with tests "Рівні тестування"

### ISSUE THREAD

**Issue by ABatalov** [scholokov/qax-portal-2#85]
We need to implement first block of tests "Рівні тестування" 

Quastions here: https://docs.google.com/document/d/1e67_f2WRXYPTl1FyxLAD35EO3zMqC0c-uah9T-oJIMY/edit

Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=931%3A91

**Comment by scholokov** [comment]
https://portal.qax-camp.com.ua/quizzes/q5-test-levels/

**Comment by GNatala** [comment]
verified
