### ISSUE TITLE
Сources - The page should not offer "Гарячі акційні пропозиції"

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#851]
We need to check that the page does not offer "Гарячі акційні пропозиції".
Product Environment: https://www.qax-camp.com.ua/current_cources/
Test Environment: https://t.qax-camp.com.ua/current_cources/
![Напрямки](https://github.com/scholokov/qax-portal-2/assets/109460500/74f3bef1-cb21-4265-8d3b-19b3ceda43fd)

**Comment by Nadiyk** [comment]
Verified
