### ISSUE TITLE
Programs - Сheck in the block "Тестування" for the new course "Матеріали для практики"

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#852]
We need to check in the block "Тестування" for the new course "Матеріали для практики".
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/programs/
![Тестування](https://github.com/scholokov/qax-portal-2/assets/109460500/bceb9cca-058a-4ece-a544-afabb5f4431e)
![Матеріали для практики](https://github.com/scholokov/qax-portal-2/assets/109460500/c054bbfe-2e16-4f95-9816-7ce54d902550)

**Comment by Nadiyk** [comment]
Veified
