### ISSUE TITLE
Home page - Implement the design of the "До оферу разом з QAX" block on the "Main page"

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#853]
We need to implement the design of the "До оферу разом з QAX" block on the "Main page".
Environment: https://www.qax-camp.com.ua/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6704-1434&t=WmH9Nx6Pt04tprzV-0

New design:
![До оферу з QAX](https://github.com/scholokov/qax-portal-2/assets/109460500/018c229f-e138-49f6-8496-692ea86b90d2)

Old design:
![Old](https://github.com/scholokov/qax-portal-2/assets/109460500/be271749-9008-4fa5-87dc-6f53c2601875)

**Comment by ButKoff** [comment]
#774

**Comment by poroskundenys** [comment]
@scholokov такой функционал уже есть на сайте?

**Comment by scholokov** [comment]
@poroskundenys 
є ось таке
https://www.qax-camp.com.ua/calendars/
тобто я думаю так (там на скільки я розумію) треба лише верстку підігнати

**Comment by poroskundenys** [comment]
@scholokov попроси у дизайнера сделать это одной картинкой https://prnt.sc/uv7w_vyCXPvR

**Comment by BatalovaOlha** [comment]
verified
