### ISSUE TITLE
Create page with tests "Дефект"

### ISSUE THREAD

**Issue by ABatalov** [scholokov/qax-portal-2#86]
We need to implement first block of tests "Дефект" 

Quastions here: https://docs.google.com/document/d/1e67_f2WRXYPTl1FyxLAD35EO3zMqC0c-uah9T-oJIMY/edit

Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=931%3A91

**Comment by scholokov** [comment]
done
https://portal.qax-camp.com.ua/quizzes/deffect
