### ISSUE TITLE
Lessons - Check lesson for "Log files" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#861]
We need to check lesson for "Log files" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/lessons/log-files/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81#%D0%BF%D0%BE%D0%B2%D0%BD%D0%B8%D0%B9-%D0%BF%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA-%D0%BA%D1%83%D1%80%D1%81%D1%96%D0%B2

**Comment by ButKoff** [comment]
#664

**Comment by BatalovaOlha** [comment]
verified
