### ISSUE TITLE
Courses - Сheck course "Log files" page that was deleted

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#862]
We need to check the course "Log files" page, that was deleted.
Environment: https://www.qax-camp.com.ua/courses/log-files/
![Log Files](https://github.com/scholokov/qax-portal-2/assets/109460500/2d0abcb0-bb9c-450f-9cdb-912cb3e58527)

**Comment by Nadiyk** [comment]
Verified
