### ISSUE TITLE
Order/The buttons and the text above them are not located on the same vertical level

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#863]
**Steps to Reproduce:**

1. Open page https://www.qax-camp.com.ua/product/test/
2. Pay attention to the placement of the buttons and the text above them 

**Actual Result:** The buttons and the text above them **are not** located on the same vertical level
**Expected Result:** The buttons and the text above them **are** located on the same vertical level

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6195-1087&t=8ykTMVmJ9Hlmv731-0

**Environment:**
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/3c72371d-db5a-4140-be6e-ab742223558d)

**Comment by ODrobik** [comment]
#768

**Comment by scholokov** [comment]
please retest

**Comment by ODrobik** [comment]
issue still exists
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/ec790b6c-d14c-472f-9d83-353961978b8a)

**Comment by scholokov** [comment]
it is ok for this page

**Comment by ODrobik** [comment]
is not an error
