### ISSUE TITLE
Lessons - Сheck lesson "HTML & CSS Валидаторы" page that was deleted

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#872]
1. We need to check the lesson "HTML & CSS Валидаторы" page, that was deleted.
   Environment: https://www.qax-camp.com.ua/courses/web-tech/lessons/html-css-validation/
![HTML   CSS Валидаторы](https://github.com/scholokov/qax-portal-2/assets/109460500/dfab654f-839e-4628-93a1-9a1f45986ab4)
2. We need to check the lesson "HTML & CSS Валидаторы" page, that has been removed from the course "Web технології".
    Environment: https://www.qax-camp.com.ua/courses/web-tech/

**Comment by ODrobik** [comment]
verified
