### ISSUE TITLE
Lessons - Check the removal of a lesson "JSON – що це?" from a course "Web технології" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#874]
We need to check the removal of a lesson "JSON – що це?" from a course "Web технології" page.
The course "Web технології" should not contain a lesson "JSON – що це?".
Environment: https://www.qax-camp.com.ua/courses/web-tech/

**Comment by Nadiyk** [comment]
не змогла відкрити сайт
![image](https://github.com/scholokov/qax-portal-2/assets/113175298/02eb48b4-aaab-46f5-b926-d15729e53aa4)

**Comment by ButKoff** [comment]
@Nadiyk Курс "Web технології" на сьогодні повністю видалено, задача не має актуальності. Можно закривати.
