### ISSUE TITLE
Lessons - Check lesson for "Вступ у Performance Тестування" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#876]
We need to check lesson for "Вступ у Performance Тестування" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/testing/lessons/perfomance-testing/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F
![Perfomance](https://github.com/scholokov/qax-portal-2/assets/109460500/5af24325-7887-46aa-a3b6-373e1d2de4fd)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
verified
