### ISSUE TITLE
Lessons - Сheck lesson "Load Testing" page that was deleted

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#877]
We need to check the lesson "Load Testing" page, that was deleted.
Environment: https://www.qax-camp.com.ua/courses/testing-theory/lessons/load-testing/
![Load Testing](https://github.com/scholokov/qax-portal-2/assets/109460500/ed76ffab-7b5c-4919-bb99-c5b5fe5e8e5b)

**Comment by GNatala** [comment]
verified
