### ISSUE TITLE
Lessons - Check the removal of a lesson "Task/issue flow" from a course "Теорія тестування" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#879]
We need to check the removal of a lesson "Task/issue flow" from a course "Теорія тестування" page.
The course "Теорія тестування" should not contain a lesson "Task/issue flow".
Environment: https://www.qax-camp.com.ua/courses/testing-theory/

**Comment by DmitriiNasonov** [comment]
Testing completed. Bugs not found
