### ISSUE TITLE
На сайті після розділу "Корисні програми" є текст

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#884]
Передумови: (тестувала як зарейстрований юзер)
Відкрити: https://www.qax-camp.com.ua/courses/qa-basic-programs/
Кроки для відтворення:

1. Зверніть увагу що на сайті після заголовку "Корисні програми" є текст з описом
2. Відкрийте вимоги https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BA%D0%BE%D1%80%D0%B8%D1%81%D0%BD%D1%96-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%B8  і зверніть увагу, що після заголовку "Корисні програми іде перелік програм"

Фактичний результат:  Після розділу "Корисні програми" є текст
Очікуваний результат: У вимогах після розділу "Корисні програми" є текст
Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104
![корисні програми](https://github.com/scholokov/qax-portal-2/assets/113175298/68cdbd09-8fdf-424f-abe5-84605ae9df22)

**Comment by Nadiyk** [comment]
#755

**Comment by DmytroMarkulych** [comment]
А як щодо дизайну?
