### ISSUE TITLE
Test - Check test "TMS" in course "Тестування"

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#890]
We need to сheck test "TMS" in course "Тестування"
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/testing/lessons/tms/quizzes/tms/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F
![TMS](https://github.com/scholokov/qax-portal-2/assets/109460500/8b60c7c1-6bcb-4f70-9ce5-d85bfaa834bf)

**Comment by ODrobik** [comment]
перевірено
