### ISSUE TITLE
Lessons - Сheck lesson "Test Plan vs Test Strategy" page that was deleted

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#891]
1. We need to check the lesson "Test Plan vs Test Strategy" page, that was deleted.
    Environment: https://www.qax-camp.com.ua/courses/testing-theory/lessons/test-plan-vs-test-strategy/
![Test Plan vs Test Strategy](https://github.com/scholokov/qax-portal-2/assets/109460500/a74e0914-f179-425b-82af-c58fe7ea9c00)
2. We need to check the lesson "Test Plan vs Test Strategy" page, that has been removed from the course "Теорія тестування".
    Environment: https://www.qax-camp.com.ua/courses/testing-theory/

**Comment by DmitriiNasonov** [comment]
Testing completed. Bugs isn't found
