### ISSUE TITLE
Lessons - Check lesson for "Структура команди, як чинник її ефективності" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#892]
We need to check lesson for "Структура команди, як чинник її ефективності" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/processes/lessons/team-structure/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D0%B8

**Comment by ButKoff** [comment]
#664

**Comment by ODrobik** [comment]
перевірено
