### ISSUE TITLE
Practice - Check new content in practical course "QAX Camp-Portal"

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#893]
We need to сheck new content in practical course "QAX Camp-Portal"
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/project-camp-portal/
![QAX Camp-Portal](https://github.com/scholokov/qax-portal-2/assets/109460500/90d756bb-dbd1-4102-87a8-a65767b60d20)

**Comment by DmitriiNasonov** [comment]
Testing completed. Bugs not found
