### ISSUE TITLE
"SessionBox" - Body - The title of the lesson is above the lesson preview

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal-2#897]
**Steps of reproducing**
1.  Open https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/sessionbox/
2. Pay attention to title of the lesson

**Actual Result**
The title of the lesson is above the lesson preview

**Expected Result**
The title of the lesson is below the lesson preview

**Additional information**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=390-12775&t=gmq0P4iytCgcY7wc-0

**Enviroments**
Windows 10, Chrome 114.0.5735.110 (64 bit)
Android 8.1.0, Chrome 114.0.5735.61
![SessionBox – QAX Camp - Google Chrome 14 06 2023 18_11_51](https://github.com/scholokov/qax-portal-2/assets/95171672/7882feb9-151f-4ca3-ae92-c7ba5de61d83)
![photo_2023-06-14_18-15-35](https://github.com/scholokov/qax-portal-2/assets/95171672/013de2c8-7afa-4ec2-a7a3-9752a72d863c)

**Comment by scholokov** [comment]
please retest

**Comment by DmitriiNasonov** [comment]
retested. bug isn't reproduced
