### ISSUE TITLE
Lesson-Topic: Хедер урока - некрасиво выгдядит на разных уроках

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#9]
Надо как то перераспределить текст.
Так как текущий - не есть описание курса. А это уже само наполнение курса

<img width="472" alt="image" src="https://user-images.githubusercontent.com/22824947/183050985-a8d205bb-5331-410e-9330-5c678fe8f6ee.png">

т.е. варианты - сместить его вниз.
Так же у нас есть уроки и с более длинным названием, например:
https://portal.qax-camp.com.ua/courses/recruiter-program/lessons/differense-in-type-of-it-comanies/
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/22824947/183051178-74f2dc0e-f8cc-4a87-abdd-f94800310bb6.png">
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/22824947/183051332-1d1b0f8c-0c28-4622-b207-673fae3e7b36.png">

еще кейс - у нас есть уроки, в содержании которых только "видео"
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/22824947/183051620-23351d6e-d010-407f-999b-ab7f7063eed1.png">

**Comment by ABatalov** [comment]
Here you can fing design in Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=390%3A12776

**Comment by scholokov** [comment]
а может превью все таки оставить?

**Comment by KaterinaNimenko35** [comment]
verified
