### ISSUE TITLE
Block "Відгуки про курси" is absent on the page https://www.qax-camp.com.ua/qa-courses/

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#903]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/qa-courses/
2. Scroll down to the "Записатися на курс".

**Actual result:**
Block "Відгуки про курси" is absent on the page.

**Expected result:**
Block "Відгуки про курси" **is above** the block "Записатися на курс".

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/d0ac1b4a-82ae-4e7a-b411-62ebeb69b5e8)

**Comment by GNatala** [comment]
#566

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
