### ISSUE TITLE
Practice - Check new content in practical course "Детальний опис проекту Travel 2.0"

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#907]
We need to сheck new content in practical course "Детальний опис проекту Travel 2.0"
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/project-travel/lessons/project-dt-travel-2-0/
![Детальний опис проекту Travel 2 0](https://github.com/scholokov/qax-portal-2/assets/109460500/fcf7513b-2f0c-4c14-8a48-d1c22456e715)

**Comment by DmitriiNasonov** [comment]
Testing completed. Bugs not found
