### ISSUE TITLE
Practice - Check new content for "Практика" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#908]
We need to check new content for "Практика" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/practice/
![WiDiQ](https://github.com/scholokov/qax-portal-2/assets/109460500/ddc4c61a-f400-4f43-852a-e6836d8c8061)
![Архів](https://github.com/scholokov/qax-portal-2/assets/109460500/3f7b13cc-8814-4e61-8d87-60aee2a682bf)

**Comment by Nadiyk** [comment]
veryfied
