### ISSUE TITLE
Practice - Check new content in practical course "QAX WiDiQ"

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#909]
We need to сheck new content in practical course "QAX WiDiQ"
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/project-widiq/
![QAX WiDiQ](https://github.com/scholokov/qax-portal-2/assets/109460500/cfbc73ec-9306-4941-9011-9797d34e5a5f)

**Comment by Nadiyk** [comment]
verified
