### ISSUE TITLE
Practice - Check new content in practical course "Детальний опис проекту WiDiQ"

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#910]
We need to сheck new content in practical course "Детальний опис проекту WiDiQ"
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/project-widiq/lessons/project-dt-widiq/
![Детальний опис проекту WiDiQ](https://github.com/scholokov/qax-portal-2/assets/109460500/fddab128-e8e8-4c47-8132-04af5f2e0288)

**Comment by DmitriiNasonov** [comment]
testing completed. bugs isn't found
