### ISSUE TITLE
Requirements - Сheck the list "Повний перелік курсів" update and preview "Canva" of current courses

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#911]
We need to check the list "Повний перелік курсів" update and preview "Canva" of current courses.
Please check availability of requirements, functional compliance and design compliance.
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81#%D0%BF%D0%BE%D0%B2%D0%BD%D0%B8%D0%B9-%D0%BF%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA-%D0%BA%D1%83%D1%80%D1%81%D1%96%D0%B2

**Comment by GNatala** [comment]
verified
