### ISSUE TITLE
Lessons - Check lesson for "Priority vs Severity" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#912]
We need to check lesson for "Priority vs Severity" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/testing/lessons/priority-vs-severity/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F
![Priority vs Severity](https://github.com/scholokov/qax-portal-2/assets/109460500/5a4ce425-c297-4f2a-8114-cc0451075fd1)

**Comment by ButKoff** [comment]
#664

**Comment by DmitriiNasonov** [comment]
Testing completed
