### ISSUE TITLE
Lessons - Check lesson for "Тестувальник. Хто це?" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#915]
We need to check lesson for "Тестувальник. Хто це?" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/testing/lessons/who-is-qa/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F
![Тестувальник](https://github.com/scholokov/qax-portal-2/assets/109460500/11879af7-f5a2-44ab-b396-18d1c33bc6ae)

**Comment by ButKoff** [comment]
#664

**Comment by BatalovaOlha** [comment]
verified
