### ISSUE TITLE
Lessons - Check lesson for "Види, методи та рівні тестування" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#916]
We need to check lesson for "Види, методи та рівні тестування" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/testing/lessons/q6-02-testing-types/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F
![Види, методи та рівні тестування](https://github.com/scholokov/qax-portal-2/assets/109460500/ab16f628-638a-4030-8155-bc90f4415de8)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
verified
