### ISSUE TITLE
Order/ In the footer of the page, the Instagram social item is not located in the same line as the others

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#921]
**Steps to Reproduce:**
1. Open page https://www.qax-camp.com.ua/product/test/
2. Pay attention to the location of the Instagram social item

**Actual Result:** the Instagram social item **is not** located in the same line as the others
**Expected Result:** the Instagram social item **is** located in the same line as the others

**Additional information:**
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6195-1087&t=8ykTMVmJ9Hlmv731-0

**Environment:**
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/c7f900b9-39d3-4547-b33b-6a17c71c830b)

**Comment by ODrobik** [comment]
#768

**Comment by scholokov** [comment]
цеж є той самий баг, про те що шрифт завеликий. том і переноситься на інший рядок

**Comment by ODrobik** [comment]
не є актуальним
