### ISSUE TITLE
Figma design should correspond website - page Checkout - block "Деталі оплати"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#924]
**STR**
1. Open https://www.qax-camp.com.ua/checkout/
2. Open https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6398-1146&t=beKngDdB8TuhloJM-0
3. Pay attention to the block "Деталі оплати" and line with an agreement with terms and rules  

**ACTUAL RESULT**
The design in the Figma is NOT the same as on the website

**EXPECTED RESULT**
Design in the Figma should be AS on the website  

Note:
The design must be adapted to the site

![5foucyot2f](https://github.com/scholokov/qax-portal-2/assets/109384052/ed597074-7a95-4691-8d0f-22e7cd6a2af9)

**Comment by BatalovaOlha** [comment]
#769

**Comment by AlonaSarapina** [comment]
ready for testing 
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=6398%3A1146&t=Kc6IrOgsO4dEn8gp-1

**Comment by BatalovaOlha** [comment]
verified
