### ISSUE TITLE
Розділу GitHub немає у вимогах

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/qax-portal-2#925]
Передумови:
Відкрити https://www.qax-camp.com.ua/courses/qa-basic-programs/
Кроки для відтворення:

1. Відкрийте вимоги https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#%D0%BA%D0%BE%D1%80%D0%B8%D1%81%D0%BD%D1%96-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%B8

2. Порівняйте перший розділ на сайті та у вимогах

Фактичний результат: Розділу GitHub немає у вимогах

Очікуваний результат:  Розділ GitHub є у вимогах 

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104
![ГітХаб немає у виомгах](https://github.com/scholokov/qax-portal-2/assets/113175298/a1d114d8-061b-4fb3-a15f-fe5175f502ca)

**Comment by DmytroMarkulych** [comment]
Такого мабуть взагалі не існує- giyhub

**Comment by Nadiyk** [comment]
Виправила

**Comment by DmytroMarkulych** [comment]
а як щодо іншої частини баг репорту?

**Comment by Nadiyk** [comment]
Виправила

**Comment by scholokov** [comment]
please retest

**Comment by Nadiyk** [comment]
pass
