### ISSUE TITLE
Lessons - Check lesson for "Grammarly" page #805/Text "Denis Scholokov" is in English

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#926]
**Steps to retroduce:**

1. Open: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/grammarly/
2. Scroll down to the text "Denis Scholokov".
3. Pay attention to the text "Denis Scholokov".
**Actual result:**
Text "Denis Scholokov" is in English
**Expected result:**
Text "Denis Scholokov" is in Ukrainian
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&t=lUbdc1NaVMIM9dtZ-0

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/d2cfb4b9-35d8-42d4-b60b-b81992ad272b)

**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/f5a1a957-5521-414c-9e5c-075132b783df)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed

**Comment by ButKoff** [comment]
#805
