### ISSUE TITLE
Requirements/Footer/Course author is in English

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#927]
**Steps to retroduce:**
1. Open: https://github.com/scholokov/qax-portal-2/wiki/1.0.1.1.-%D0%A2%D0%B5%D0%BE%D1%80%D1%96%D1%8F-%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F
2. Scroll down to the "Курс Content".
3. Pay attention to the footer screenshot and name of a author.
**Actual result:**
Text "Denis Scholokov" is in English
**Expected result:**
Text "Denis Scholokov" is in Ukrainian
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&t=lUbdc1NaVMIM9dtZ-0

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/7a5e2494-07e7-4b9c-9516-77367ece75c6)

**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/510e15fb-cfcb-47f4-a7bd-17b6a299b017)

**Comment by ButKoff** [comment]
#805
