### ISSUE TITLE
Wrong ID "D03KQQLLL9L" ( PM Andrii Butkov) to redirect to chat page in the Slack - block "Комунікація" - page "Детальний опис проекту Camp-Portal" 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#929]
**STR**
1. Open https://www.qax-camp.com.ua/courses/project-camp-portal/lessons/project-dt-camp-portal/
2. Pay attention to PM Andrii Butkov and ID for the redirection 

**ACTUAL RESULT**
The ID for redirection on the page is D03KQQLLL9L ( <a href="https://qax-hq.slack.com/archives/D03KQQLLL9L">PM Andrii Butkov</a> )

**EXPECTED RESULT**
The ID for redirection is _U03LA36F665_

![k6eOLFy7X2](https://github.com/scholokov/qax-portal-2/assets/109384052/42c89eee-24e2-45f4-991b-939b26dab07c)

![wSx4VjIcHJ](https://github.com/scholokov/qax-portal-2/assets/109384052/1171fdf7-4d67-4d11-a21f-8c39a96da2e7)

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
