### ISSUE TITLE
Wrong chanal ID ("наш проектний чат") to redirect to chat "qax-camp-portal" page in the Slack - block "Комунікація" - page "Детальний опис проекту Camp-Portal" 

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#932]
**STR**

1. Open https://www.qax-camp.com.ua/courses/project-camp-portal/lessons/project-dt-camp-portal/
2. Pay attention to "наш проектний чат" and ID for the redirection

**ACTUAL RESULT**

The ID for redirection on the page is C03KQHQN3FF ( <a href="https://qax-hq.slack.com/archives/C03KQHQN3FF">наш проектний чат</a> )

**EXPECTED RESULT**
The ID for redirection to the correct chat is C03PS9YRB3N
![gCqP6mptfi](https://github.com/scholokov/qax-portal-2/assets/109384052/82c963a8-d6ae-4583-bd3c-7152d267cdae)

![HGJQEywyZL](https://github.com/scholokov/qax-portal-2/assets/109384052/bd825dc7-8a81-482c-8dce-d19bb63477d4)
![xTKUnZp6pV](https://github.com/scholokov/qax-portal-2/assets/109384052/b4ffff0a-0a70-42ea-b7ea-4ad819d40151)

**Comment by BatalovaOlha** [comment]
#894

**Comment by scholokov** [comment]
fixed

**Comment by BatalovaOlha** [comment]
verified
