### ISSUE TITLE
wiki/Requirements - table "Корисні програми"- the lesson "Notepad++" is missing

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#936]
**Steps to Reproduce:**
1. Open page https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA
2. Pay attention to the table "Корисні програми".

**Actual Result:** the lesson "Notepad++" is **missing**
**Expected Result:** the lesson "Notepad++" is **present**

**Environment:**
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/8a3e47e1-d34c-4cad-8862-ccc221ec01c1)

**Comment by ODrobik** [comment]
#804

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
