### ISSUE TITLE
Wrong link for redirection from the main page to the page "Продуктова зустріч..." - block "Комунікація" - page "Детальний опис проекту Camp-Portal"

### ISSUE THREAD

**Issue by BatalovaOlha** [scholokov/qax-portal-2#937]
**STR**
1. Open https://www.qax-camp.com.ua/courses/project-camp-portal/lessons/project-dt-camp-portal/
2. Pay attention to the link "<a href="https://qax-hq.slack.com/archives/C03PS9YRB3N">Продуктова зустріч, де можна задавати любі питання, якщо ви їх не задали у чаті</a>" and ID for the redirection

**ACTUAL RESULT**

The ID for redirection on the page is C03PS9YRB3N 

**EXPECTED RESULT**

The ID for redirection to the correct chat is https://meet.google.com/rcc-cdet-sgp

Note:
the redirection should be to the link in Google Calander, google meet
QAX WiDiQ
Вторник, 20 июня · 16:30–17:30
Часовой пояс: Europe/Berlin
Контактная информация для встречи в Google Meet
Ссылка на видеовстречу: https://meet.google.com/gaq-nvhy-ahr
Номер телефона: PIN-код для номера ‪(DE) +49 30 300195060‬: ‪551 309 599 1120‬#
Дополнительные номера: https://tel.meet/gaq-nvhy-ahr?pin=5513095991120

![CYSO8cUbEH](https://github.com/scholokov/qax-portal-2/assets/109384052/67cd74ed-e0c4-442c-b098-a05699e98e1d)

![Ii6OC5ukut](https://github.com/scholokov/qax-portal-2/assets/109384052/8a9a10c4-d8ca-414d-b836-40e1b13fcfdd)

**Comment by BatalovaOlha** [comment]
#894

**Comment by scholokov** [comment]
виправлено

**Comment by BatalovaOlha** [comment]
verified
