### ISSUE TITLE
Lessons - Check lesson for "Що таке Viewport" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#939]
We need to check lesson for "Що таке Viewport" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/lessons/viewport/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA

**Comment by DmitriiNasonov** [comment]
Lesson deleted. Task isn't actual
![Search Results - QAX - Slack - Google Chrome 27 09 2023 15_09_38](https://github.com/scholokov/qax-portal-2/assets/95171672/7b4f98fe-16fd-465f-af1e-470586437f2c)
