### ISSUE TITLE
Lesson - defect - переклад на укр мову, додано контент

### ISSUE THREAD

**Issue by scholokov** [scholokov/qax-portal-2#94]
https://portal.qax-camp.com.ua/lessons/defect/

- перекладено на укр мову
- доданий контент

**Comment by Nadiyk** [comment]
[qax-camp.com.ua](http://qax-camp.com.ua/
[portal.qax-camp.com.ua](http://portal.qax-camp.com.ua/

**Comment by ButKoff** [comment]
@Nadiyk ось правильне посилання: https://www.qax-camp.com.ua/courses/practise/lessons/defect/
Не забуваємо авторизуватися :)

**Comment by Nadiyk** [comment]
Verified
