### ISSUE TITLE
Lessons - Check lesson for "Параметри Екрану" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#940]
We need to check lesson for "Параметри Екрану" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/lessons/screens/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA

**Comment by ButKoff** [comment]
#664

**Comment by DmitriiNasonov** [comment]
Testing completed
