### ISSUE TITLE
Lessons - Check lesson for "Ролі та артефакти у проектній команді" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#942]
We need to check lesson for "Ролі та артефакти у проектній команді" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-roles/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#q2-%D0%B1%D0%B0%D0%B7%D0%BE%D0%B2%D0%B8%D0%B9-%D0%BA%D1%83%D1%80%D1%81-qa
![Ролі та артефакти у проектній команді](https://github.com/scholokov/qax-portal-2/assets/109460500/213388f5-0369-4933-a080-e7d9205bfad5)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
verified
