### ISSUE TITLE
Lessons - Check lesson for "SDLC/STLC" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#943]
We need to check lesson for "SDLC/STLC" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/q6-basic/lessons/q6-sdlc-stlc/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA#q2-%D0%B1%D0%B0%D0%B7%D0%BE%D0%B2%D0%B8%D0%B9-%D0%BA%D1%83%D1%80%D1%81-qa
![SDLC](https://github.com/scholokov/qax-portal-2/assets/109460500/facf6935-e01c-4916-8ffb-729f47f2ad34)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
verified
