### ISSUE TITLE
Lessons - Check lesson for "ToDoIst" page #806/The name of program is ToDoIst

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#945]
**Steps to retroduce:**

1. Open: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/todoist/
2. Scroll down to the name of program ToDoIst.
3. Pay attention to the name of program ToDoIst.
**Actual result:**
The name of program is ToDoIst
**Expected result:**
Official program name is **Todoist**
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Attachments:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/26b57d0c-fe0b-44b2-bb29-8c8b36488f90)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/qax-portal-2/assets/88647733/dd6ad375-5a28-4080-a358-995d38b37a99)

**Comment by scholokov** [comment]
вииправлено

**Comment by prokopenkoga1977** [comment]
Passed
