### ISSUE TITLE
Invite - Check new content for "Здобувай досвід з QAX!" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#947]
We need to check new content for "Здобувай досвід з QAX!" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/invite/
![Invite](https://github.com/scholokov/qax-portal-2/assets/109460500/713d2846-71ab-47b8-a1b9-e6618238eb7a)

**Comment by GNatala** [comment]
Verified
