### ISSUE TITLE
Practice - Implement updates to the "Практика" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#948]
We need to implement updates to the "Практика" page.
Environment: https://www.qax-camp.com.ua/practice/

![Практика](https://github.com/scholokov/qax-portal-2/assets/109460500/c431b738-c14c-4054-8e8a-d98a254a4996)
![New content](https://github.com/scholokov/qax-portal-2/assets/109460500/be6773ac-eb6f-4727-a3ef-15c85b94088d)
![Вартисть навчання](https://github.com/scholokov/qax-portal-2/assets/109460500/39d5720f-fa19-4fd7-bb6d-4a7808b0d361)

**Comment by scholokov** [comment]
виконано

**Comment by GNatala** [comment]
verified
