### ISSUE TITLE
Lessons - Check lesson for "JSON vs XML vs HTML" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#950]
We need to check lesson for "JSON vs XML vs HTML" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/lessons/json-vs-xml-vs-html/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81
![JSON vs XML vs HTML](https://github.com/scholokov/qax-portal-2/assets/109460500/4d405bd1-c8ed-4c28-9cb0-5052e7c41b93)

**Comment by ButKoff** [comment]
#664

**Comment by DmitriiNasonov** [comment]
Testing completed. Bugs not found
