### ISSUE TITLE
Lessons - Check lesson for "DNS, ping, tracert" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#951]
We need to check lesson for "DNS, ping, tracert" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/lessons/dns-ping/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81
![DNS, ping, tracert](https://github.com/scholokov/qax-portal-2/assets/109460500/f5ab6bea-fa37-4ff9-a435-ad29f8ccae16)

**Comment by ButKoff** [comment]
#664

**Comment by DmitriiNasonov** [comment]
Testing completed
