### ISSUE TITLE
Lessons - Check lesson for "Коды состояния HTTP и как их интерпретировать" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#952]
We need to check lesson for "Коды состояния HTTP и как их интерпретировать" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/lessons/%d0%ba%d0%be%d0%b4%d1%8b-%d1%81%d0%be%d1%81%d1%82%d0%be%d1%8f%d0%bd%d0%b8%d1%8f-http-%d0%b8-%d0%ba%d0%b0%d0%ba-%d0%b8%d1%85-%d0%b8%d0%bd%d1%82%d0%b5%d1%80%d0%bf%d1%80%d0%b5%d1%82%d0%b8%d1%80%d0%be/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81
![Коды состояния HTTP и как их интерпретировать](https://github.com/scholokov/qax-portal-2/assets/109460500/e9425148-a46f-48f0-95a5-0fb5b2f4c933)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
verified
