### ISSUE TITLE
Lessons - Check lesson for "Разница между HTTP и HTTPS" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#953]
We need to check lesson for "Разница между HTTP и HTTPS" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/lessons/http-https/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81
![Разница между HTTP и HTTPS](https://github.com/scholokov/qax-portal-2/assets/109460500/aa564873-3d37-445e-98d9-82788eaa5b83)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
verified
