### ISSUE TITLE
Lessons - Check lesson for "Grammarly" page #805/Grammar error "Миттєву зворотну зв’язок"

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#957]
**Steps to retroduce:**

1. Open: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/grammarly/
2. Scroll down to the text "Миттєву зворотну зв’язок: Grammarly відображає помилки у режимі реального часу, що дозволяє виправляти їх на льоту.".
3. Pay attention to the text "Миттєву зворотну зв’язок".

**Actual result:**
Grammar error "Миттєву зворотну зв’язок"
**Expected result:**
Text  must be "Миттєвий зворотній зв'язок"
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/8db3680b-dcd6-43c7-8667-a0ef13be8f11)

**Comment by ButKoff** [comment]
#805

**Comment by prokopenkoga1977** [comment]
@scholokov bug not fixed 

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/1e875bab-af45-464c-825f-8e1c87b6fa28)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
