### ISSUE TITLE
Invite / Spelling mistakes in the word "оволодіє" in the accordion "Найчастіші питання"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#959]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/invite/
2. Scroll down to the "Найчастіші питання" - open the accordion.
3. Find item number 4.
4. Pay attention to the sentence "Все залежить від того, як швидко ти досконально **оволодіє** та відпрацюєш навички з попереднього проєкту.".

**Actual result:**
Word "оволодіє" is written without letter "ш".

**Expected result:**
Word "оволодіє" is written with letter "ш" - "**оволодієш**".

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/c5bdd969-9441-4aa9-938e-e11b78c30f92)

**Comment by GNatala** [comment]
#947

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
