### ISSUE TITLE
Invite / Spelling mistakes in the word "популізувати" in the accordion "Діючі проєкти"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#960]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/invite/
2. Scroll down to the "Діючі проєкти" - open the accordion.
3. Pay attention to the sentence "Разом з командою Денис створив унікальні, навчальні проєкти в котрі вкладено максимум досвіду, безмежне бажання **популізувати** сферу ІТ та безкінечне прагнення вдосконалення".

**Actual result:**
Sentence "Разом з командою Денис створив унікальні, навчальні проєкти в котрі вкладено максимум досвіду, безмежне бажання **популізувати** сферу ІТ та безкінечне прагнення вдосконалення" is written with the wrong word **"популізувати".**

**Expected result:**
Sentence "Разом з командою Денис створив унікальні, навчальні проєкти в котрі вкладено максимум досвіду, безмежне бажання **популяризувати** сферу ІТ та безкінечне прагнення вдосконалення" is written with the word **"популяризувати".**

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/3eca12e7-75f4-4932-84f2-05e8e44d6627)

**Comment by GNatala** [comment]
#947

**Comment by scholokov** [comment]
fixed
