### ISSUE TITLE
Invite / Spelling mistake оf the word "дошок" in the text of the accordion "Як все відбувається"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#961]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/invite/
2. Scroll down to the accordion "Як все відбувається" - open it.
3. Pay attention to the item "Твої інструменти:" and the last sentence "Miro – онлайн платформа для створення дошок / схем / діаграм".

**Actual result:**
Word "дошок" is wrriten with letter "ш"

**Expected result:**
Word "**дощок**" is wrriten with letter "щ"

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/6ebe3024-a7c1-447f-bf4f-a9d913f48d15)

**Comment by GNatala** [comment]
#947

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
