### ISSUE TITLE
Lessons - Check lesson for "Объяснение асимметричного шифрования (HTTPS) на почтовых голубях" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#963]
We need to check lesson for "Объяснение асимметричного шифрования (HTTPS) на почтовых голубях" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/lessons/https-pigeon/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81
![Объяснение асимметричного шифрования](https://github.com/scholokov/qax-portal-2/assets/109460500/242b6946-164e-41e2-90c5-c5f00c05c688)

**Comment by ButKoff** [comment]
#664

**Comment by DmitriiNasonov** [comment]
Testing completed
