### ISSUE TITLE
Lessons - Check lesson for "Как работает SSL-сертификат, как браузер и сайт устанавливают безопасное соединение" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#964]
We need to check lesson for "Как работает SSL-сертификат, как браузер и сайт устанавливают безопасное соединение" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/lessons/%d0%ba%d0%b0%d0%ba-%d1%80%d0%b0%d0%b1%d0%be%d1%82%d0%b0%d0%b5%d1%82-ssl-%d1%81%d0%b5%d1%80%d1%82%d0%b8%d1%84%d0%b8%d0%ba%d0%b0%d1%82-%d0%ba%d0%b0%d0%ba-%d0%b1%d1%80%d0%b0%d1%83%d0%b7%d0%b5%d1%80/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81
![Как работает SSL-сертификат](https://github.com/scholokov/qax-portal-2/assets/109460500/454a446a-7166-4237-8d26-27b734f3fb70)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
verified
