### ISSUE TITLE
Lessons - Check lesson for "Обзор способов и протоколов аутентификации в веб-приложениях" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#965]
We need to check lesson for "Обзор способов и протоколов аутентификации в веб-приложениях" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/lessons/%d0%be%d0%b1%d0%b7%d0%be%d1%80-%d1%81%d0%bf%d0%be%d1%81%d0%be%d0%b1%d0%be%d0%b2-%d0%b8-%d0%bf%d1%80%d0%be%d1%82%d0%be%d0%ba%d0%be%d0%bb%d0%be%d0%b2-%d0%b0%d1%83%d1%82%d0%b5%d0%bd%d1%82%d0%b8%d1%84/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81
![Обзор способов и протоколов](https://github.com/scholokov/qax-portal-2/assets/109460500/8c801859-855f-49c7-9615-90e56d8f5d63)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
verified
