### ISSUE TITLE
Lessons - Check lesson for "Путь критической визуализации" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#966]
We need to check lesson for "Путь критической визуализации" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/lessons/%d0%bf%d1%83%d1%82%d1%8c-%d0%ba%d1%80%d0%b8%d1%82%d0%b8%d1%87%d0%b5%d1%81%d0%ba%d0%be%d0%b9-%d0%b2%d0%b8%d0%b7%d1%83%d0%b0%d0%bb%d0%b8%d0%b7%d0%b0%d1%86%d0%b8%d0%b8/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81
![Путь критической визуализации](https://github.com/scholokov/qax-portal-2/assets/109460500/c69439c0-3893-4533-9a32-2fb446fdec0e)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
verified
