### ISSUE TITLE
Lessons - Check lesson for "Типы Web-атак" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#968]
We need to check lesson for "Типы Web-атак" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/lessons/types-of-web-attack/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81
![Типы Web-атак](https://github.com/scholokov/qax-portal-2/assets/109460500/b408e1fb-f833-4381-87e1-46775d9a9de6)

**Comment by ButKoff** [comment]
#664

**Comment by DmitriiNasonov** [comment]
Testing completed. bugs isn't found
