### ISSUE TITLE
Lessons - Check lesson for "Что на самом деле происходит, когда пользователь вбивает в браузер адрес google.com" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#969]
We need to check lesson for "Что на самом деле происходит, когда пользователь вбивает в браузер адрес google.com" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/web-mobile/lessons/%d1%87%d1%82%d0%be-%d0%bd%d0%b0-%d1%81%d0%b0%d0%bc%d0%be%d0%bc-%d0%b4%d0%b5%d0%bb%d0%b5-%d0%bf%d1%80%d0%be%d0%b8%d1%81%d1%85%d0%be%d0%b4%d0%b8%d1%82-%d0%ba%d0%be%d0%b3%d0%b4%d0%b0-%d0%bf%d0%be%d0%bb/
Requirements: https://github.com/scholokov/qax-portal-2/wiki/1.2.1.-%D0%9A%D1%83%D1%80%D1%81
![Что на самом деле происходит](https://github.com/scholokov/qax-portal-2/assets/109460500/478d01d8-3f87-4631-9d75-d708f966a11e)

**Comment by ButKoff** [comment]
#664

**Comment by GNatala** [comment]
verified
