### ISSUE TITLE
Registration form design "Записатися на курс""

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#97]
We need to implement the design according to the figma.
Design on figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=408%3A22
Implementation in a test environment: https://portal.qax-camp.com.ua/
![Записатися на курси](https://user-images.githubusercontent.com/109460500/192505128-91c69343-c13e-422c-9ea2-f888bf67e115.png)

**Comment by BatalovaOlha** [comment]
Verified
