### ISSUE TITLE
Subscriptions - Check subscription for "Абонемент “Мінімальний”" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#970]
We need to check subscription for "Абонемент “Мінімальний”" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/pass-min/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=390-1035&mode=design&t=zrWihmokGoLEN3Io-0
![min](https://github.com/scholokov/qax-portal-2/assets/109460500/2d71efdb-802b-4bbd-97d5-90c9ab29c2ec)

**Comment by GNatala** [comment]
verified
