### ISSUE TITLE
Subscriptions - Check subscription for "Абонемент “Максимальний”" page

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#972]
We need to check subscription for "Абонемент “Максимальний”" page.
Please check availability of requirements, functional compliance and design compliance.
Environment: https://www.qax-camp.com.ua/courses/pass-max/
Figma: https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=390-1035&mode=design&t=zrWihmokGoLEN3Io-0
![max](https://github.com/scholokov/qax-portal-2/assets/109460500/3608420a-14d3-4f00-95ab-c544aa71ce90)

**Comment by GNatala** [comment]
verified
