### ISSUE TITLE
Lessons - Check lesson for "ToDoIst" page #806/Grammar error "та нагадування про завдання"

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#974]
**Steps to retroduce:**
1. Open: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/todoist/
2. Scroll down to the text "Todoist надає можливість встановлювати терміни та нагадування про завдання, що допомагає уникнути забуття та забезпечити вчасне виконання."
3. Pay attention to the text "та **нагадування** про завдання"

**Actual result:**
Grammar error "та **нагадування** про завдання"

**Expected result:**
Text must be "та **нагадувати** про завдання"

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/90ad233f-e402-44ab-8868-586ace0f3c27)

**Comment by prokopenkoga1977** [comment]
[#806](https://github.com/scholokov/qax-portal-2/issues/806)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
