### ISSUE TITLE
Lessons - Check lesson for "Total Commander" page #780/Grammar error " Він має подвійну панельний інтерфейс"

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#975]
**Steps to retroduce:**
1. Open: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/total-commander/
2. Scroll down to the text "Він має **подвійну** панельний інтерфейс, що дозволяє зручно працювати з двома різними папками одночасно.
3. Pay attention to the text "Він має **подвійну** панельний інтерфейс"

**Actual result:**
Grammar error " Він має **подвійну** панельний інтерфейс"

**Expected result:**
Text must be "Він має **двопанельний інтерфейс**"

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/da5754e1-4823-4205-a176-44682d903b23)

**Comment by ButKoff** [comment]
#780

**Comment by prokopenkoga1977** [comment]
@scholokov bug not fixed 

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/aa782311-0c9e-407c-bf26-d2b021d00e90)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
