### ISSUE TITLE
Lessons - Check lesson for "Total Commander" page #780/Grammar error " Завдяки подвійному панельному інтерфейсу"

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#976]
**Steps to retroduce:**

1. Open: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/total-commander/
2. Scroll down to the text "Завдяки **подвійному панельному інтерфейсу** ви можете легко порівнювати файли та папки, виконувати синхронізацію та копіювання між двома різними місцями."
3. Pay attention to the text "Завдяки **подвійному панельному інтерфейсу**"

**Actual result:**
Grammar error " " Завдяки **подвійному панельному інтерфейсу**"

**Expected result:**
Text must be "Завдяки **двопанельному інтерфейсу**"

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/8973626e-4ad8-4190-9d04-21c129613cfd)

**Comment by ButKoff** [comment]
#780

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
