### ISSUE TITLE
Lessons - Check lesson for "Total Commander" page #780/Grammar error "забезпечує безпечну та точну копіювання даних"

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#977]
**Steps to retroduce:**

1. Open: https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/total-commander/
2. Scroll down to the text "Це дозволяє швидко знайти різницю між версіями файлів та **забезпечує безпечну та точну копіювання даних**."
3. Pay attention to the text "**забезпечує безпечну та точну копіювання даних.**"

**Actual result:**
Grammar error  " забезпечує безпечну та точну копіювання даних."
**Expected result:**
Text must be "забезпечує **безпечне та точне** копіювання даних"

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/3077e7f8-45f0-4ebd-9ed1-d57b6083f8ef)

**Comment by ButKoff** [comment]
#780

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/qax-portal-2/assets/88647733/ebfb06bf-248c-4bfc-bfea-9f22bfd732a9)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
