### ISSUE TITLE
Lessons - Check lesson for "Test Plan" page (Issue #751)/Grammar error "Тест-план (план тестування, або план тестування)"

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#978]
**Steps to retroduce:**

1. Open: https://www.qax-camp.com.ua/courses/testing/lessons/test-plan/
2. Scroll down to the text "Тест-план (план тестування, або план тестування)"
3. Pay attention to the text "Тест-план (**план тестування, або план тестування**)"
**Actual result:**
Grammar error "Тест-план (**план тестування, або план тестування**) "
**Expected result:**
Text must be "Тест-план (**план тестування**)"
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/4e1bcdf8-ab2b-4d00-b147-5dfc596f551d)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
