### ISSUE TITLE
Lessons - Check lesson for "Test Plan" page (Issue #751)/Grammar error "що?" - lower case

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#979]
**Steps to retroduce:**

1. Open: https://www.qax-camp.com.ua/courses/testing/lessons/test-plan/
2. Scroll down to the text "що?"
3. Pay attention to the text "що?" lower case

**Actual result:**
Grammar error "що?" - lower case
**Expected result:**
Text must be "Що?" - uppercase
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/865112e6-3eff-4412-924a-26810ce3c641)

**Comment by prokopenkoga1977** [comment]
[#751](https://github.com/scholokov/qax-portal-2/issues/751)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
