### ISSUE TITLE
Lessons - Check lesson for "Test Plan" page (Issue #751)/Grammar error "коли?" - lower case

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#980]
**Steps to retroduce:**

1. Open: https://www.qax-camp.com.ua/courses/testing/lessons/test-plan/
2. Scroll down to the text "коли?"
3. Pay attention to the text "коли?" lower case

**Actual result:**
Grammar error "коли?" - lower case
**Expected result:**
Text must be "Коли?" - uppercase
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/2097a5db-dac1-4581-9092-ebdfd99a114c)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
