### ISSUE TITLE
Lessons - Check lesson for "Test Plan" page (Issue #751)/Grammar error "Побудова тестування стратегій"

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/qax-portal-2#982]
**Steps to retroduce:**

1. Open: https://www.qax-camp.com.ua/courses/testing/lessons/test-plan/
2. Scroll down to the text "Побудова **тестування стратегій**"
3. Pay attention to the text "Побудова **тестування стратегій**" 

**Actual result:**
Grammar error "Побудова **тестування стратегій**"
**Expected result:**
Text must be "Побудова **стратегій тестування**"
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Attachment:**

![Image](https://github.com/scholokov/qax-portal-2/assets/125134112/a6b2b452-bff4-4533-8818-7e3fb25d6a0f)

**Comment by prokopenkoga1977** [comment]
[#751](https://github.com/scholokov/qax-portal-2/issues/751)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
