### ISSUE TITLE
Базовий курс QA / Mis hover of the button "Обрати цей курс"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#983]
**Steps to reproduce:**
1. Open https://www.qax-camp.com.ua/courses/q6-basic/
2. Make hover of the button "Обрати цей курс".
5. Pay attention to the color of hover.

**Actual result:**
Color of the hover of the button "Обрати цей курс" is not #35324B.

**Expected result:**
Color of the hover of the button "Обрати цей курс" is #35324B.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

Additional information:
https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?node-id=476-583&t=A1CPb5Hh5Rjo0X39-0

**Attachment:**
https://github.com/scholokov/qax-portal-2/assets/101987790/024c2e22-678b-4939-be1f-d115f06d9957

![image](https://github.com/scholokov/qax-portal-2/assets/101987790/4e211097-f55a-4928-81b0-21ee948a19d6)

**Comment by GNatala** [comment]
#643

**Comment by DmytroMarkulych** [comment]
додайте будь ласка скріншот

**Comment by GNatala** [comment]
додала

**Comment by GNatala** [comment]
passed
