### ISSUE TITLE
Invite / Missed punctuation mark at the end of the sentence "Спікер та наставник"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#987]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/invite/
2. Scroll down to the accordion "Засновник, автор навчальних проєктів – Денис Щолоков" - open it.
3. Pay attention to the punctuation at the end of the sentence "Спікер та наставник".

**Actual result:**
There is no punctuation mark at the end of the sentence "Спікер та наставник"

**Expected result:**
There is punctuation mark at the end of the sentence "Спікер та наставник"

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/9191a1bb-130e-4395-b476-26bb221a536d)

**Comment by GNatala** [comment]
#947

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
