### ISSUE TITLE
Lesson "Notepad++"/ In the text "Автодоповнення: додаток має функцію автодоповнення, яка ..."  the word "набираних" is a spelling mistake

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#990]
Steps to Reproduce:
1. Open page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/notepad-plus-plus/
2. Scroll down to the points "Переваги Notepad++"
3. Pay attention to the word "набираних" in the text "Автодоповнення: додаток має функцію автодоповнення, яка ..."

Actual Result: in the text "Автодоповнення: додаток має функцію автодоповнення, яка ..." the word "набираних" is a spelling mistake
Expected Result: in the text "Автодоповнення: додаток має функцію автодоповнення, яка ..." the word "набраних" is without a spelling mistake

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/5eb9b603-1486-4989-8401-079ed9122b08)

**Comment by ODrobik** [comment]
#804

**Comment by scholokov** [comment]
виправлено
