### ISSUE TITLE
Lesson "Test Data Generation Tools"/In the line about "regex" the text alignment in cell "Link" is different from neighboring cells

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#991]
Steps to Reproduce:
1. Open page https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/test-data-generation-tools/
2. Scroll down to the the table with the row about "regex"
3. Pay attention to the alignment of the text in the cell "Link"

Actual Result: the text alignment in cell "Link" is **different** from neighboring cells
Expected Result: the text alignment in cell "Link" is **the same as** neighboring cells

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/dc896d66-208d-4423-8ab4-fb90263cb45b)

**Comment by ODrobik** [comment]
#803

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
