### ISSUE TITLE
wiki/Requirements - table "Корисні програми" - lesson "Test Data Generation Tools" - author "Denis Scholokov" is written in English

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#992]
Steps to Reproduce:
1. Open page https://github.com/scholokov/qax-portal-2/wiki/1.7.1.-%D0%A3%D1%80%D0%BE%D0%BA
2. Pay attention to the table "Корисні програми".

Actual Result: author "Denis Scholokov is written in English
Expected Result: author "Денис Щолоков" is written in Ukrainian

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/a433181f-fe0b-4a6f-a1ad-08cf0ec607d7)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/qax-portal-2/assets/88647733/5c0ac50c-5867-46bd-9f05-2ac8ce9973a3)

**Comment by ODrobik** [comment]
виправлено

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
