### ISSUE TITLE
Invite / Missed punctuation mark at the end of the sentence "19 років у сфері тестування"

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#997]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/invite/
2. Scroll down to the accordion "Засновник, автор навчальних проєктів – Денис Щолоков" - open it.
3. Pay attention to the punctuation at the end of the sentence "19 років у сфері тестування".

**Actual result:**
There is no punctuation mark at the end of the sentence "19 років у сфері тестування"

**Expected result:**
There is punctuation mark dot at the end of the sentence "19 років у сфері тестування."

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/101987790/addabd74-451b-4ac4-a22a-635513557ff0)

**Comment by GNatala** [comment]
#947

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
passed
