### ISSUE TITLE
Cources - Implement updates to the "QA, PM, BA" pages

### ISSUE THREAD

**Issue by ButKoff** [scholokov/qax-portal-2#998]
We need to implement updates to the "QA, PM, BA" pages.
Environments: 
1. https://www.qax-camp.com.ua/qa-courses/
2. https://www.qax-camp.com.ua/pm-courses-2/
3. https://www.qax-camp.com.ua/ba-courses/

![Практика](https://github.com/scholokov/qax-portal-2/assets/109460500/c7c806ec-eb55-4018-afd0-3713fba5b270)
![Абонементи](https://github.com/scholokov/qax-portal-2/assets/109460500/972c3dd5-8ae6-4f83-aed6-ede08e25d4d2)
![Абонимент_вартисть](https://github.com/scholokov/qax-portal-2/assets/109460500/085f1e39-860b-4ba6-a147-3aca4197e4c7)

**Comment by GNatala** [comment]
verified
